### ISSUE TITLE
Readmes pointing to wrong location for the SDK

### ISSUE THREAD

**Issue by ToddKerpelman** [firebase/quickstart-unity#1]
It appears as though the `readme` files in various sample projects (`quickstart-unity/database/readme.me`, etc.) are still pointing to the version of the SDK that's hosted at dev-partners.googlesource.com. I'm pretty sure they should just be using the version hosted at dl.google.com.

**Comment by stewartmiles** [comment]
Fixed with 5ea23daf60ef6478a62c71cad07a9f90d6d13a55
