### ISSUE TITLE
 And how to change the icon? - А как изменить иконку?

### ISSUE THREAD

**Issue by Hyper00** [firebase/quickstart-unity#10]
And how to change the icon? After importing firebase message, I have instead of icons with Unity3D changed to standard Android icon, where it can be corrected?
-----------------
А как изменить иконку? После импорта firebase message, у меня вместо иконки с Unity3D поменялось на стандартную иконку Андроид, где это можно исправить?

**Comment by stewartmiles** [comment]
We have a fix that will make it into our next release.
The workaround for now is to replace Plugins/Android/AndroidManifest.xml with the attached file.

[AndroidManifest.xml.zip](https://github.com/firebase/quickstart-unity/files/605014/AndroidManifest.xml.zip)

Cheers,
Stewart

**Comment by Hyper00** [comment]
Спасибо!)) Thank you!))

2016-11-22 7:00 GMT+08:00 Stewart Miles <notifications@github.com>:

**Comment by stewartmiles** [comment]
No problem

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart
