### ISSUE TITLE
Unity app not sending notification_open events.

### ISSUE THREAD

**Issue by FedericoLaGreca** [firebase/quickstart-unity#100]
Hello, 

Our Unity3d app is not sending (since they aren't shown in the console) the automatic notification_open events.

We have overridden the main activity, but we actually can't follow the documentation from [https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_a_custom_entry_point_activity](url)
because the class MessageForwardingService can't be found. so we implemented a simple 
`@Override
    protected void onNewIntent(Intent i) {
        super.onNewIntent(i);
}`
with some more custom code after that in the override.

Could this be the issue? Or, if this doesn't influence the notification_open event, where should we look to fix our problem?

**Comment by FedericoLaGreca** [comment]
An update, because it looks like it's a console issue, not an implementation one. It looks like if we go in the Analytics Events dashboard in the application, we correctly get notification_open events.
But if we look in the Nofications tab, we have a 0% open rate with 0 notification_open events.
Looks like we've opened this issue in the wrong place ;)

**Comment by stewartmiles** [comment]
Could you report this to firebase-talk@ or firebase support?
