### ISSUE TITLE
[Question]When I was using Firebase Storage, I had problems with the iOS side

### ISSUE THREAD

**Issue by a314266177** [firebase/quickstart-unity#1000]
I run this code used in table to a normal no problem, but ran to the IOS side there is the problem, I have seen in print background my file is downloaded, but can't write in show that resultTask IsFaulted this condition is true, then my file is not in, I initially thought it was not written to the file, but I wrote my own a piece of code also can be written to the file is written to, so I promise I have write permissions, and can be written to the file, I have to print the file path is also there, I want to ask you if you have encountered such a problem
![image](https://user-images.githubusercontent.com/18459275/111410169-34821200-8713-11eb-83a5-d6c15f1a7611.png)
![image](https://user-images.githubusercontent.com/18459275/111410209-4663b500-8713-11eb-9899-5aca6a94c824.png)

**Comment by paulinon** [comment]
Hi @a314266177,

It seems that your inquiry doesn't follow the template. With this, I'll be closing this ticket for now. 

In order for me to get a better understanding of this issue, you may file another ticket that uses the issue template.

Thanks!
