### ISSUE TITLE
[Bug]  This client does not have permission to perform this operation but Auth is completed

### ISSUE THREAD

**Issue by kapyar** [firebase/quickstart-unity#1002]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.0
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK:  Unity Package Manager
  * Problematic Firebase Component: Auth, Database, 
  * Other Firebase Components in use: Messaging, Instance, Core, DynamicLinks, Remote Config
  * Additional SDKs you are using: AdMob Unity
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the issue here:
Ok, here the deal. I am using in my project these modules: 
![image](https://user-images.githubusercontent.com/6231331/112147689-ac55ae00-8be5-11eb-868d-9773de26f8b6.png)
Previously I was using the 6.1.1 version of it and it worked fine. After I updated the version I got the following error `"This client does not have permission to perform this operation";` in editor and the editor is freeing.

#### Steps to reproduce:
So How structure is setted up.
1. I am using Zenject for DI
2. Auth module setted up first
3. In FirebaseDbController I have properties     'private DatabaseReference _invitePath;' 
4. I am subscribing for event `_invitePath.ValueChanged`
5. I generate link like `_invitePath = _dbService.GetDb().Child("users").Child(_currentUserId).Child("invited");` _currentUserId is FirebaseAuth.DefaultInstance.User.CurrentUser and the value is inited
6. When event `_invitePath.ValueChanged` triggered in callback I have that error 
`private void InvitedCountValueChanged(object sender, ValueChangedEventArgs args)
        {
            _dispatcher.DispatchOnNextFrame(() =>
            {
                if (args.DatabaseError != null) {
                    Log.Err(args.DatabaseError.Message);
                    Log.Err(args.DatabaseError.Code.ToString());
                    return;
                }`

#### How I was trying to resolve this issue
I found [this](https://github.com/firebase/quickstart-unity/issues/412) issue related to 6.2.2 version. But make `_auth `static field doesn't help. `public FirebaseUser User => _auth.CurrentUser; 
        private static FirebaseAuth _auth;`

**Comment by paulinon** [comment]
Hi @kapyar,

In order for me to verify if your issue is reproducible, could you provide the following information:
- A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project
- Sample dummy data that shows your database structure
- Realtime Database Security Rules

Thanks!

**Comment by kapyar** [comment]
@paulinon I will try to create it tonight. But meanwhile this is config:
1. Security Rule:
`{
  "rules": {
    "users": {
      "$uid": {
        ".write": "$uid === auth.uid",
        ".read": "$uid === auth.uid",
        "invitedBy":{
          ".validate": "newData.isString() && newData.val().length < 40 && newData.val().length > 5"
        },
        "charName":{
          ".validate": "newData.isString() && newData.val().length < 100"
        },
        "token":{
          ".validate": "newData.isString() && newData.val().length < 250 && newData.val().length > 5"
        }
      }
    }
  }
}`
2. Structure:
   ` "001FCqA06QeuGMLItadRV8" : {
      "charName" : "ximenaa",
      "invited" : 0,
      "token" : "dNid9xIGSZuZb78pwSUT7JHzWXg7ikM1IHPDuhlCZokwGpdFCKMVliqsO4niHW31HXZvb6vEcdDj3IBee6GUXI1nfGfx2sDsA24N1PtPyUpbv9sxdYwpC5Xabrm0pl73SI7CrBLjlT9jjqU"
    }
` token id and name were changed
