### ISSUE TITLE
When the app is opened through a notification, Intent doesn't have Extra data.

### ISSUE THREAD

**Issue by Vitalii-Dudnyk** [firebase/quickstart-unity#1006]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Cloud Messaging
  * Other Firebase Components in use: No, I have only one component
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

When I open my app through a notification Intent doesn't have Extra data. I tried to get this data with the help of AndroidNotificationCenter.GetLastNotificationIntent() or directly from Activity, but this data is always empty. The app uses default UnityPlayerActivity. Apart from this when I added the package Asset/Plugins/Android/AndroidManifest wasn't updated, to do the update I had to remove Asset/Plugins/Android/AndroidManifest and run force dependency manager resolver. Moreover, Asset/Plugins/Android/FirebaseApp.androidlib/AndroidManifest was added and I don't know and can't find out its purpose. The app receives notifications from a custom server through Amazon SNS.

#### Relevant Code:

**Asset/Plugins/Android/AndroidManifest:**
<img width="1736" alt="Screenshot 2021-03-25 at 10 40 27" src="https://user-images.githubusercontent.com/71373823/112444395-a9c69600-8d56-11eb-9b66-4174a7c0019b.png">

**Asset/Plugins/Android/FirebaseApp.androidlib/AndroidManifest:**
<img width="647" alt="Screenshot 2021-03-25 at 10 19 15" src="https://user-images.githubusercontent.com/71373823/112444139-6704be00-8d56-11eb-9392-c8826e64408d.png">

**Comment by Vitalii-Dudnyk** [comment]
<img width="1712" alt="Screenshot 2021-03-25 at 10 20 15" src="https://user-images.githubusercontent.com/71373823/112443800-0b3a3500-8d56-11eb-8931-1caff9d85fc9.png">

**Comment by paulinon** [comment]
Hi @Vitalii-Dudnyk,

In order to see if your behavior can be replicated, could you try our quickstart and see if the issue persists? I would also like to request for the code you're using in handling messages and confirmation if your device has Google Play Services so that we can have a better understanding of this issue.

Thanks!

**Comment by Vitalii-Dudnyk** [comment]
Hi, @paulinon 

Unfortunately, I couldn't try your quickstart because I think it is irrelevant for my situation, besides I don't have a problem with all stuff that describes there. There is no description of how to pull out data from Android Intent.

**This is my code:**
`private Action<string> _onTokenGotAction;
        private Action<string> _onNotificationGot;

        protected override void Initialize()
        {
            Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
                var dependencyStatus = task.Result;
                if (dependencyStatus == Firebase.DependencyStatus.Available) {
                    this.Log($"Dependencies resolved");
                }
                else
                {
                    this.LogError($"Could not resolve all Firebase dependencies: {dependencyStatus.ToString()}");
                }
            });
        }

        public void GetTokenAsync(Action<string> action)
        {
            _onTokenGotAction = action;
            Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
        }

        private void OnTokenReceived(object sender, TokenReceivedEventArgs e)
        {
            Firebase.Messaging.FirebaseMessaging.TokenReceived -= OnTokenReceived;
            _onTokenGotAction?.Invoke(e.Token);
        }
        
        public bool TryGetNotificationData(out string data)
        {
            var notificationIntentData = AndroidNotificationCenter.GetLastNotificationIntent();

            if (notificationIntentData != null)
            {
                var id = notificationIntentData.Id;
                var channel = notificationIntentData.Channel;
                var notification = notificationIntentData.Notification;
                data = notification.IntentData;
                return true;
            }

            data = null;
            return false;
        }`
        
        **This is code of Mobile notification unity package**
        `var notificationIntent = s_CurrentActivity.Call<AndroidJavaObject>("getIntent");
        var id = notificationIntent.Call<int>("getIntExtra", "id", -1);
            if (id == -1)
                return null;

            var channelId = notificationIntent.Call<string>("getStringExtra", "channelID");

            var notification = new AndroidNotification();
            notification.Title = notificationIntent.Call<string>("getStringExtra", "textTitle");
            notification.Text = notificationIntent.Call<string>("getStringExtra", "textContent");
            notification.ShouldAutoCancel = notificationIntent.Call<bool>("getBooleanExtra", "autoCancel", false);
            notification.UsesStopwatch = notificationIntent.Call<bool>("getBooleanExtra", "usesChronometer", false);
            notification.FireTime = notificationIntent.Call<long>("getLongExtra", "fireTime", -1L).ToDatetime();
            notification.RepeatInterval = notificationIntent.Call<long>("getLongExtra", "repeatInterval", -1L).ToTimeSpan();
            notification.Style = notificationIntent.Call<int>("getIntExtra", "style", 0).ToNotificationStyle();
            notification.Color = notificationIntent.Call<int>("getIntExtra", "color", 0).ToColor();
            notification.Number = notificationIntent.Call<int>("getIntExtra", "number", -1);
            notification.IntentData = notificationIntent.Call<string>("getStringExtra", "data");
            notification.Group = notificationIntent.Call<string>("getStringExtra", "group");
            notification.GroupSummary = notificationIntent.Call<bool>("getBooleanExtra", "groupSummary", false);
            notification.SortKey = notificationIntent.Call<string>("getStringExtra", "sortKey");
            notification.GroupAlertBehaviour = notificationIntent.Call<int>("getIntExtra", "groupAlertBehaviour", 0).ToGroupAlertBehaviours();

            return new AndroidNotificationIntentData(id, channelId, notification);`

**Comment by Vitalii-Dudnyk** [comment]
Apart from my previous comment, I found out that adding an additional <intent-filter> to AndroidManifest could help to solve my problem. Example of the filter

`<intent-filter>
        <action android:name="android.intent.action.SEARCH" />`
        
  However Android Intent has hundreds of actions and I don't know which I should use.

**Comment by paulinon** [comment]
Hi @Vitalii-Dudnyk,

I believe this is the intent filter you're looking for:
### 
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>


For an Android build, it's important that this be added in order to utilize the messaging service. With that, could you try adding this and see if the issue is fixed?

**Comment by Vitalii-Dudnyk** [comment]
Hi @paulinon,

Thank you) I'm going to try it next week and I will write you a result.
