### ISSUE TITLE
[Bug] Crash if windows user has non-ascii name

### ISSUE THREAD

**Issue by infuzo** [firebase/quickstart-unity#1007]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.8f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase app (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Firestore (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook Api, Universal Media Player (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: desktop (iOS, Android, and/or desktop)
  * Scripting Runtime: both (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Windows platform: if user has non-ascii user name (cyrillic for example) builded application crashes after unity splash screen. Log hasn't useful information:

`Mono path[0] = 'C:/zMEET_v3.32a/zMEET_Data/Managed'
Mono config path = 'C:/zMEET_v3.32a/MonoBleedingEdge/etc'
Initialize engine version: 2019.4.16f1 (e05b6e02d63e)
[Subsystems] Discovering subsystems at path C:/zMEET_v3.32a/zMEET_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1650 (ID=0x1f99)
    Vendor:   
    VRAM:     3962 MB
    Driver:   27.21.14.5256
Begin MonoManager ReloadAssembly
- Completed reload, in  0.094 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.939600 ms`

If user has latin username, but application was installed in folder by non-ascii path, there is this issue - https://github.com/firebase/quickstart-unity/issues/690

**Comment by paulinon** [comment]
Hi @infuzo,

In order to ensure that you have the latest updates and bug fixes, could you try using an up-to-date version of the Unity editor (Unity 2021.1.0) and see if the issue persists? If so, I'd like you to provide the logs seen from the [Android Logcat](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html) while your app is running.

Thanks!

**Comment by infuzo** [comment]
> Hi @infuzo,
> 
> In order to ensure that you have the latest updates and bug fixes, could you try using an up-to-date version of the Unity editor (Unity 2021.1.0) and see if the issue persists? If so, I'd like you to provide the logs seen from the [Android Logcat](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html) while your app is running.
> 
> Thanks!

Hi! I'll try using newest version of unity. But Android Logcat isn't actual for this problem - how I described above, this problem exists on Windows OS when user name has non-ascii symbols.

**Comment by infuzo** [comment]
I tried to launch builds, that were built by 2020.3.1f1 unity (latest in the unity hub). It still crashes, mono and il2cpp. That's only log I have:

`
Initialize engine version: 2020.3.1f1 (77a89f25062f)
[Subsystems] Discovering subsystems at path C:/WinZetMeet/zMEET_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1650 (ID=0x1f99)
    Vendor:   
    VRAM:     3962 MB
    Driver:   27.21.14.5256
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.382500 ms
`

**Comment by DellaBitta** [comment]
I believe this is related to #690 which was linked in the initial report.  Firebase persists data between sessions on mobile devices and this functionality is replicated on desktop systems by storing data in the Windows current user's directory.

Could you answer a few questions:

- Does the editor crash with a clean project before adding firebase?
- Does the editor crash by simply adding Firebase as an imported asset but without invoking any Firebase functions?
- Does the editor crash the first time you use a Firebase by invoking a method?
- Which Firebase products are you using?

Thanks!
