### ISSUE TITLE
NSAllowsArbitraryLoadsInWebContent in info.plist

### ISSUE THREAD

**Issue by roointan** [firebase/quickstart-unity#1009]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Core Firebase (Auth, Database, etc.)
  * Other Firebase Components in use: Crashlytics (Auth, Database, etc.)
  * Additional SDKs you are using: ironsource with mediation (Unityads, FAN, Admob), also Facebook, OneSignal, AppMetrica
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
Hello,
we are using ironsource with mediation, and in their documentation:
https://developers.ironsrc.com/ironsource-mobile/unity/unity-plugin/#step-3

They say nothing besides NSAllowsArbitraryLoads should be set to true under NSAppTransportSecurity in info.plist
But I think Firebase is adding NSAllowsArbitraryLoadsInWebContent to info.plist too.
Why is that? and is it safe to remove that flag? And can it be automated, so I don't have it added to info.plist on export?

**Comment by paulinon** [comment]
Hi @roointan,

It appears that you may be facing an issue similar to [#397](https://github.com/firebase/quickstart-unity/issues/397) where one of our Firebase advocates recommended whitelisting domains that don't support TLS/SSL. Could you try the recommendations in this ticket and see if your issue persists?

Additionally, please ensure that you're using the latest versions of the editor and SDK so that you can have the latest updates and bug fixes for your implementation.

**Comment by roointan** [comment]
> Hi @roointan,
> 
> It appears that you may be facing an issue similar to [#397](https://github.com/firebase/quickstart-unity/issues/397) where one of our Firebase advocates recommended whitelisting domains that don't support TLS/SSL. Could you try the recommendations in this ticket and see if your issue persists?
> 
> Additionally, please ensure that you're using the latest versions of the editor and SDK so that you can have the latest updates and bug fixes for your implementation.

Thanks for your reply.
I don't think this is an applicable solution for us, because removal of the key is recommended by external ad networks, and we can't know which URLs several of the mediated ad networks are going to use.
