### ISSUE TITLE
[Bug] - IOS - Opening a dynamic link several times from Messages results in a corrupted link

### ISSUE THREAD

**Issue by chris-o3h** [firebase/quickstart-unity#1012]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.5f1
  * Firebase Unity SDK version: 7.01
  * Source you installed the SDK: Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Dynamic Links (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Database, Cloud Messaging, Crashalytics, Analytics
  * Additional SDKs you are using: _____ 
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: IOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
Opening a dynamic link from Messages several times results in the link being partially expanded.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Have not tried. (Don't have time)
What's the issue repro rate? (eg 100%, 1/5 etc)
100% after several attempts.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

* Create a dynamic link with a Unity App that uses FireBase Dynamic links on IOS and ensure that it is a short link
* Copy said link to the clipboard
* Paste said link in Messages and send to yourself
* Tap on the link
* The first several times the link will behave as normal and is the short version
* After several taps on the link you will notice that `Application.absoluteURL` is no longer the shortened dynamic link but rather a garbled/incomplete expanded link.

Sample Link Corruption:
Original link:
https://oooh.page.link/5k9S

Corrupted link:
https://oooh.page.link/s?socialDescription=It%27s+about+time+a+video+platform+switched+up+the+game.%0A%0AJoin+the+Beta!&socialImageUrl=https://cdn.sanity.io/images/h2sx4hl4/dev/605a06df422d90187a6dfbf516909ed65ccaf2be-588x588.jpg?fm%3Djpg&socialTitle=Oooh

Note that this only happens in Messages so far. We've tried other methods like via slack and it appears to work appropriately.
IOS 14.4.2

**Comment by paulinon** [comment]
Hi @chris-o3h,

I have tried the link that you provided, but even after at least ten tries, I haven't been able to replicate the behavior you're facing. Could you try creating your dynamic link after updating your SDK and Unity editor to their latest versions and see if the issue persists? 

You could also try using the quickstart and see if the issue will persist there as well. If it does, please indicate the number of attempts you've made in tapping the link before facing the issue.

**Comment by chris-o3h** [comment]
Hi @paulinon,
I too can no longer repro the problem. However a colleague and I were both seeing the problem last week. I'll close this and we will monitor as we are logging when/if the issue occurs.

**Comment by chris-o3h** [comment]
@paulinon Not sure but potentially this is what I've experienced: https://developer.apple.com/forums/thread/123554
