### ISSUE TITLE
[Bug] Can not use firebase services in ios when facebook sdk version 9.0.0 added to the unity project. 

### ISSUE THREAD

**Issue by ervandogan12** [firebase/quickstart-unity#1013]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _2019.4.13f1____
  * Firebase Unity SDK version: 7.0.2____
  * Source you installed the SDK: Unity Package Manager _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _Auth, Database,Cloud Messaging, Analytics____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using:Facebook, AdMob, Agora (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac(Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

 Our project's firebase services was working correctly until we added facebook sdk.   

#### Steps to reproduce:
1. Create an emty firebase unity ios project.
2. Add firebase auth/database services to this project.
3. Add facebook unity sdk to the project.
4. Build project for xcode in order to run on a simulator.
5. When we run project on xcode (for iPhone 12 pro max) we encountered this error in the log file of xcode:
"Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly."
6. Although, GoogleService-Info.plist is located in the asset folder of project we get this error. 
7. Our podfile looks like this:

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 9.0'
  pod 'FBSDKGamingServicesKit', '~> 9.0'
  pod 'FBSDKLoginKit', '~> 9.0'
  pod 'FBSDKShareKit', '~> 9.0'
  pod 'Firebase/Analytics', '7.0.0'
  pod 'Firebase/Auth', '7.0.0'
  pod 'Firebase/Core', '7.0.0'
  pod 'Firebase/Database', '7.0.0'
  pod 'Firebase/Functions', '7.0.0'
  pod 'Firebase/Messaging', '7.0.0'
  pod 'Firebase/Storage', '7.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.63'
end
target 'Unity-iPhone' do
end
use_frameworks!

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @ervandogan12,

Thanks for reporting the issue. Could you verify if the issue persists with the latest version of the Firebase SDK (7.1.0) and the Unity Editor (2020.3.2f1 for LTS)?

**Comment by ervandogan12** [comment]
thanks for your interest. The problem has been solved by the use of Facabook SDK 9.0.0.

**Comment by surajsk1812** [comment]
@ervandogan12  How did you resolve this issue?
Which Facebook SDK version was causing this problem and which Facebook SDK version resolved the issue?
