### ISSUE TITLE
Duplicate class Issue

### ISSUE THREAD

**Issue by arjungaonkar** [firebase/quickstart-unity#1014]
### Please fill in the following fields:

  * Unity editor version: 2019.4.1f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: -
  * Other Firebase Components in use: -
  * Additional SDKs you are using: Cardboard SDK
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Andriod
  * Scripting Runtime: IL2CPP

### Please describe the issue here:

java.lang.RuntimeException: Duplicate class com.google.protobuf.AbstractMessageLite found in modules protobuf-javalite-3.14.0.jar (com.google.protobuf:protobuf-javalite:3.14.0) and protobuf-lite-3.0.0.jar (com.google.protobuf:protobuf-lite:3.0.0)
This issue started after adding Cardboard SDK.

#### Steps to reproduce:

1. Add Firestore package
2. Add Cardboard SDK as instructed here [https://developers.google.com/cardboard/develop/unity/quickstart]().
2. Follow Firebase related steps from here https://github.com/googlevr/cardboard/issues/140 
3. Add android.enableR8=false to gradle properties file
4. Build

**Comment by paulinon** [comment]
Hi @arjungaonkar,

For issues like this, you can try going to Assets -> External Dependency Manager -> Android Resolver -> Resolve.

I'll be closing this for now. If the issue persists, you may reach out to [Google Cardboard's GitHub issue tracker](https://github.com/googlevr/cardboard/issues).

Thanks.
