### ISSUE TITLE
unity edior

### ISSUE THREAD

**Issue by 18252371466** [firebase/quickstart-unity#1018]
Win32Exception: ApplicationName='F:\Unity\Editor\Data\Tools\RoslynScripts\unity_csc.bat', CommandLine='/noconfig @Temp/UnityTempFile-1e68021493e5c3d49846895a6b09cc7d', CurrentDirectory='', Native error= 系统找不到指定的文件。

System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.Diagnostics.Process.Start () (at <aa976c2104104b7ca9e1785715722c9d>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
UnityEditor.Utils.Program.Start (System.EventHandler exitCallback) (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Utils.Program.Start () (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.Compilers.MicrosoftCSharpCompiler.BeginCompiling () (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.CompilationTask.QueuePendingAssemblies () (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.CompilationTask.Poll () (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CompileScriptAssemblies (UnityEditor.Scripting.ScriptCompilation.ScriptAssembly[] scriptAssemblies, UnityEditor.Scripting.ScriptCompilation.ScriptAssemblySettings scriptAssemblySettings, System.String tempBuildDirectory, UnityEditor.Scripting.ScriptCompilation.CompilationTaskOptions compilationTaskOptions, UnityEditor.Scripting.ScriptCompilation.EditorCompilation+CompileScriptAssembliesOptions compileScriptAssembliesOptions) (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CompileScriptsWithSettings (UnityEditor.Scripting.ScriptCompilation.ScriptAssemblySettings scriptAssemblySettings, System.String tempBuildDirectory, UnityEditor.Scripting.ScriptCompilation.TargetAssembly[]& notCompiledTargetAssemblies, System.String[]& notCompiledScripts, UnityEditor.Scripting.ScriptCompilation.CompilationTaskOptions compilationTaskOptions) (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CompileScripts (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions editorScriptCompilationOptions, UnityEditor.BuildTargetGroup platformGroup, UnityEditor.BuildTarget platform, System.String[] extraScriptingDefines, UnityEditor.Scripting.ScriptCompilation.CompilationTaskOptions compilationTaskOptions) (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface+<>c__DisplayClass40_0.<CompileScriptsNoStop>b__0 () (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.EmitExceptionAsError[T] (System.Func`1[TResult] func, T returnValue) (at <a5fdc7e75f6d4630a4503d091a36206b>:0)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:CompileScriptsNoStop(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget, String[])

What happened? i need your help.

**Comment by 18252371466** [comment]
I tried to grant everyone full access and I can definitely edit the unity_csc.bat file now and save it, however unity is still complaining:
Win32Exception: ApplicationName='C:\Program Files\Unity 2019.3.0a3\Editor\Data\Tools\RoslynScripts\unity_csc.bat', CommandLine='/noconfig @temp/UnityTempFile-2f8d3f5f0c51ba547a3710b9bb4c5d70', CurrentDirectory='', Native error= Access is denied.


When I add a new "C#" script and try and attach it to a gameobject it crashes saying that the script class name cannot be found.

I am 100% sure that the class name for example MyScript matches the file name MyScript ...

**Comment by paulinon** [comment]
Hi @18252371466,

Based on the details you provided, it seems that there are no errors related to Firebase. With that, I would like to ask for the following details:
- Unity Editor version
- Firebase product/s used
- Firebase SDK version
- Complete steps to reproduce this issue
- Confirmation if the issue persists without the Firebase SDK


Thanks!
