### ISSUE TITLE
Unity Cloud Build and iOS - no events registers

### ISSUE THREAD

**Issue by oosmoxiecode** [firebase/quickstart-unity#102]
Hi,

I did a test implementation of firebase analytics in my unity project. I followed the instructions here: https://firebase.google.com/docs/analytics/unity/start

Android seems to be working fine, getting events and can see users in the "streamview".

For iOS I use Unity's Cloud Build(adhoc), it seems to compile/build fine, but when testing I get no events and can't see any users.

Is it supposed to work "out of the box" with Cloud Build or do I need to do something else as well? Like add some pre-export method, some argument to xcode or similar?
Anyone got it to work together with Cloud Build? Any help would be much appreciated!

Thanks!

**Comment by stewartmiles** [comment]
This has the same root cause as https://github.com/firebase/quickstart-unity/issues/101 so I'll close as a dupe . 

As a workaround you'll need to add the additional preprocessor symbols / macros PB_FIELD_32BIT=1 and PB_NO_PACKED_STRUCTS=1 to your Xcode project from an editor plugin for  Unity Cloud Build using the XcodeApi.   You can see an example here https://github.com/googlesamples/unity-jar-resolver/blob/master/source/IOSResolver/src/IOSResolver.cs#L1236 as part of an asset preprocessor you'll need to add the flags PB_FIELD_32BIT=1 and PB_NO_PACKED_STRUCTS=1 to OTHER_CFLAGS.

**Comment by oosmoxiecode** [comment]
Thanks for your answer and for clarifying!

Not sure I completely understand though, I´m not really familiar with xcode or how it works.
Would I do something like this then?

```
[PostProcessBuild]
public static void OnPostProcessBuild(BuildTarget buildTarget, string path) {
	if (buildTarget == BuildTarget.iOS) {
		string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";

		PBXProject proj = new PBXProject();
		proj.ReadFromString(File.ReadAllText(projPath));
		string target = proj.TargetGuidByName("Unity-iPhone");

		proj.AddBuildProperty(target, "OTHER_CFLAGS", "$(inherited)");
		proj.AddBuildProperty(target, "PB_FIELD_32BIT", "1");
		proj.AddBuildProperty(target, "PB_NO_PACKED_STRUCTS", "1");

		File.WriteAllText(projPath, proj.WriteToString());
	}
}
```

Or you said "add the flags to OTHER_CFLAGS", how do you do that?
Thanks!

**Comment by stewartmiles** [comment]
I think it's 

[PostProcessBuild]
public static void OnPostProcessBuild(BuildTarget buildTarget, string path) {
	if (buildTarget == BuildTarget.iOS) {
		string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";

		PBXProject proj = new PBXProject();
		proj.ReadFromString(File.ReadAllText(projPath));
		string target = proj.TargetGuidByName("Unity-iPhone");
		proj.AddBuildProperty(target, "OTHER_CFLAGS", "PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 $(inherited)");
		File.WriteAllText(projPath, proj.WriteToString());
	}
}

In Xcode you should end up with the following settings:
<img width="879" alt="screen shot 2017-08-17 at 2 51 05 pm" src="https://user-images.githubusercontent.com/6042948/29428530-8e3c09be-835b-11e7-92fc-64c316fed53d.png">

**Comment by stewartmiles** [comment]
Ok I have a temporary patch you can drop into your project.  Replace the existing IOSResolver.dll under PlayServicesResolver/Editor with the attached file and regenerate your Xcode project.

[IOSResolver.dll.zip](https://github.com/firebase/quickstart-unity/files/1232913/IOSResolver.dll.zip)

**Comment by oosmoxiecode** [comment]
Yes, that seemed to work fine now!

Thanks a million, @stewartmiles, much appreciated!

**Comment by 2yonghyun** [comment]
@stewartmiles Thanks for a solution.
But I hava a question for a temporary patch.
<img width="381" alt="2017-08-20 12 39 04" src="https://user-images.githubusercontent.com/20157363/29491887-dc9b60c8-85a4-11e7-9274-1fee60dc9e5c.png">
In my case, replace Google.IOSResolver_v1.2.35.0.dll  to new Google.IOSResolver.dll you uploaded with changeing a file name equal to old one? Is it right??
