### ISSUE TITLE
[Bug] RemoteConfig fetch settings not functioning correctly

### ISSUE THREAD

**Issue by burakomer** [firebase/quickstart-unity#1021]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.18f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Auth, Firestore
  * Additional SDKs you are using: Play Games
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono
### [REQUIRED] Please describe the issue here:

**First Problem:**
Expected Behaviour: **MinimumFetchInternalInMilliseconds** is in milliseconds. If set to 0, it fetches the new values.
Current Behaviour: **MinimumFetchInternalInMilliseconds** variable in **RemoteConfigSettings** is not in milliseconds, it is in **seconds** (printed the default value, then tested with various values). Also, if this is set to 0, it doesn't fetch the new values. I had to set it to 1 in order for it to fetch the new values quickly.

**Second Problem:** 
Expected Behaviour: When the time set in **MinimumFetchInternalInMilliseconds** runs out, even if the game is running, next fetch will fetch new values and activate will activate new values.
Current Behaviour: No matter what I set **MinimumFetchInternalInMilliseconds** to, or no matter what TimeSpan value I use in **FetchAsync**, it does not fetch the new values, EVEN IF I set them to 1 seconds. **It works however, when I restart the game.** This means that I can't supply immediate updates while users are playing my game, they have to restart it regardless. If this is an intended feature, then I suppose Remote Config is not for me.  My main usage of Remote Config is to set game-changing variables, like item and gold drop rates. I want to increase them when an event happens, but after that event ends, I want to IMMEDIATELY affect each connected user so they won't be able to abuse it until they close the app.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I tested on my app, it functions like that every time.

What happened? How can we make the problem occur?

For the first problem:
- Set Remote Config MinimumFetchInternalInMilliseconds to 0.
- Run the game, set defaults, fetch and activate values.
- Change the values in Remote Config in console.
- Return to the game, fetch and activate again while running. Fetched values will be the same.
- Restart the game, fetch and activate values. Fetched values will be the same.

For the second problem:
- Set Remote Config MinimumFetchInternalInMilliseconds to 1.
- Run the game, set defaults, fetch and activate values.
- Change the values in Remote Config in console.
- Return to the game, fetch and activate again while running. Fetched values will be the same.
- Restart the game, fetch and activate values. Fetched values will be the new ones.

**Comment by paulinon** [comment]
Hi @burakomer,

Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so that I can try to isolate the cause of this behavior?

**Comment by burakomer** [comment]
Hello @paulinon 

I wrote this quickly. Is this okay?
 
    public class RemoteConfigTest : MonoBehaviour
    {
        private bool ready;
        private FirebaseRemoteConfig rc;
        
        private void Awake()
        {
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(initTask =>
            {
                if (initTask.Result != DependencyStatus.Available) return;
                
                rc = FirebaseRemoteConfig.DefaultInstance;
                var config = new ConfigSettings {MinimumFetchInternalInMilliseconds = 0}; // Set 0 for first problem, 1 for second.
                rc.SetConfigSettingsAsync(config).ContinueWithOnMainThread(setConfigTask =>
                {
                    var defaults = new Dictionary<string, object>
                    {
                        ["value1"] = 5,
                        ["value2"] = 10
                    };
                    rc.SetDefaultsAsync(defaults).ContinueWithOnMainThread(setDefaultsTask =>
                    {
                        ready = true;
                    });
                });
            });
        }

        private void OnGUI()
        {
            if (!ready) return;
            if (GUI.Button(new Rect(Vector2.zero, Vector2.one * 100), "Fetch And Activate"))
            {
                rc.FetchAsync().ContinueWithOnMainThread(fetchTask =>
                {
                    rc.ActivateAsync().ContinueWithOnMainThread(activateTask =>
                    {
                        var value1 = rc.GetValue("value1").DoubleValue;
                        var value2 = rc.GetValue("value2").DoubleValue;
                
                        Debug.Log($"Value1: {value1}, , Value2: {value2}");
                    });
                });
            }
        }
    }`

**Comment by paulinon** [comment]
Hi @burakomer,

In order for me to get a better understanding of your issue, it would be great if you could provide the minimal, reproducible example in a form of a project repository so that I can try to replicate this behavior on my end. If that's not possible, you can provide the complete steps you've taken before encountering this issue.

Thanks.
