### ISSUE TITLE
Mobile device unable to connect to firebase database while it works on unity editor 

### ISSUE THREAD

**Issue by sooiou** [firebase/quickstart-unity#1024]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.2f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Dynamic links
  * Additional SDKs you are using: x
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime:

### [REQUIRED] Please describe the question here:
Hi, I'm trying to use firebase database on an android device but it's not working,
when I hit play in unity editor I can modify this database normaly.

When I have a look at the devices connected at same time in firebase console I can see that my android device never access firebase database.

If somebody can help, (I saw some other posts on this issue but without real solutions...)
Thanks

**Comment by alexames** [comment]
Are you running a custom project or the quickstart project in this repo? Did you make sure to follow the instructions in the readme, making sure to include the right google-services.json? Are there any log messages from logcat when you run the app?

**Comment by sooiou** [comment]
Thanks alexames, 
I'm running a custom project, my google-services.json file is the one that I can download from the app settings in the firebase console.
I will try to use logcat to give you informations

**Comment by sooiou** [comment]
Okay I try logcat on my project and I get these errors :

2021/04/13 19:52:42.560 4343 4379 Error Unity DllNotFoundException: FirebaseCppApp-7_1_0
2021/04/13 19:52:42.560 4343 4379 Error Unity   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)

this is for the first 2 error lines.
