### ISSUE TITLE
[Bug] Auth Android crash

### ISSUE THREAD

**Issue by abogarsukov-braingames** [firebase/quickstart-unity#1025]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.23
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Auth, Database, Messaging, Crashlytics, Analytics
  * Additional SDKs you are using: Facebook, IronSource (AdMob, FB Audience, Unity Ads), Adjust
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

We observe crashes on Android 5 and 9 with the following stack trace (the relevant part):
```
libFirebaseCppApp-7_1_0.firebase::auth::Auth::app() (app:4)
libFirebaseCppApp-7_1_0.firebase::auth::AuthNotifier::AuthNotifier(firebase::auth::Auth*, void (*)(firebase::App*)) (AuthNotifier:60)
libFirebaseCppApp-7_1_0.firebase::auth::AuthStateListenerImpl::AuthStateListenerImpl(firebase::auth::Auth*, void (*)(firebase::App*)) (AuthStateListenerImpl:32)
libFirebaseCppApp-7_1_0.Firebase_Auth_CSharp_CreateAuthStateListener (Firebase_Auth_CSharp_CreateAuthStateListener:24)
libil2cpp.0x191e57c (AuthUtilPINVOKE_CreateAuthStateListener_m4D66F27FEB2ED372EC3E955B8EA982FA6C7DF6F0 at XXX\Temp\StagingArea\Il2Cpp\il2cppOutput/Firebase.Auth.cpp:4825)
libil2cpp.0x191e44c (AuthUtil_CreateAuthStateListener_m79B4AB49D383DB7458D564F1BE4E31A76F2C3A24 at XXX\Temp\StagingArea\Il2Cpp\il2cppOutput/Firebase.Auth.cpp:4169)
libil2cpp.0x1921cc0 (FirebaseAuth_GetAuth_mF9F3471073B652BC9FF94BD40D81B7360C75BC36 at XXX\Temp\StagingArea\Il2Cpp\il2cppOutput/Firebase.Auth.cpp:7004)
libil2cpp.0x1ad0634 (U3CInitializeAsyncU3Ed__11_MoveNext_m775EC62A65C672013682039F1365B156B4E30CA7 at XXX\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp7.cpp:41247)
...
```

#### Steps to reproduce:

According to the crash reports this happens on the very app start when we initialize Firebase.

#### Relevant Code:
The code we use to initialize Firebase:
```
protected async Task InitializeAsync(Player player, CancellationToken cancellationToken)
{
    Debug.Log($"[{Tag}] FA.CheckAndFixDependenciesAsync");
    var dependencyStatus = await FirebaseApp.CheckAndFixDependenciesAsync();

    if (dependencyStatus == DependencyStatus.Available)
    {
#if UNITY_EDITOR
        Debug.Log($"[{Tag}] FA.CheckAndFixDependenciesAsync success");
#endif
        _app = FirebaseApp.DefaultInstance;
        _auth = FirebaseAuth.GetAuth(_app);

#if UNITY_IOS
        // Do not show user notifications prompt until level 5 (iOS only).
        if (player.LastLevelWon >= _gameConfig.GetIosNotificationsPromptLevel())
#endif
        {
            FirebaseMessaging.TokenReceived += OnTokenReceived;
            FirebaseMessaging.MessageReceived += OnMessageReceived;
        }

        // Crahlytics
        {
            Crashlytics.IsCrashlyticsCollectionEnabled = _appInfo.IsRelease;
            Crashlytics.SetUserId(player.UserID);
            Crashlytics.Log("FirebaseInitialized");
        }

        // Analytics
        {
            FirebaseAnalytics.SetAnalyticsCollectionEnabled(_appInfo.IsRelease);
            FirebaseAnalytics.SetUserProperty(FirebaseAnalytics.UserPropertySignUpMethod, "Google");
            FirebaseAnalytics.SetUserId(player.UserID);
            FirebaseAnalytics.SetUserProperty("ouid", player.OriginalUserID);
            FirebaseAnalytics.SetUserProperty("level", player.LastLevelWon.ToString());
        }
    }
    else
    {
        Debug.LogError($"[{Tag}] FA.CheckAndFixDependenciesAsync failed: {dependencyStatus}.");
        throw new Exception("FirebaseApp.CheckAndFixDependenciesAsync failed with result " + dependencyStatus);
    }
}
```

**Comment by paulinon** [comment]
Hi @abogarsukov-braingames,

In order for me to get a better understanding of your issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that I can try to replicate this behavior on my end. If that's not possible, you can provide the complete steps you've taken before encountering this issue.

Thanks!

**Comment by abogarsukov-braingames** [comment]
Hello @paulinon,

We are not able to reproduce this issue on our side. We get a few crash reports like this in our Crashlytics. All cases are Android, it doesn't look like an out of memory issue.

**Comment by paulinon** [comment]
Thanks for the confirmation, @abogarsukov-braingames. Could you try building your app after updating your Unity Editor to the latest LTS version and see if the issue persists?

**Comment by abogarsukov-braingames** [comment]
Unfortunately, we're not ready to upgrade the project to 2020 LTS. It's a huge amount of work we cannot afford right now (the upgrade is scheduled to summer). That said, next release will use latest 2019 LTS. I'll watch the crashlytics and follow up if I have any updates.
