### ISSUE TITLE
[Bug] Crashlytics is not being enabled (Did not register exception handlers: Crashlytics SDK was not initialized) 

### ISSUE THREAD

**Issue by Dimidrol112** [firebase/quickstart-unity#1027]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14f1 and 2020.1.17f1
  * Firebase Unity SDK version: 7.1.0 and 6.16.1
  * Source you installed the SDK: both (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Messaging, remote config, analytics in 2019.4.14f1 and just Crashlytics in  2020.1.17f1
  * Additional SDKs you are using: Facebook, AppMetrica, Mycom.Tracker.Unity in 2019.4.14f1 and none in 2020.1.17f1
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Im making my project in 2019.4.14f1. I tried 7.1.0 and 6.16.1 SDK. Then i tried in clean 2020.1.17f1 with just Crashlytics
![изображение](https://user-images.githubusercontent.com/15066688/114813860-64810b80-9dcc-11eb-8fba-f6ec66dc2a8a.png)
![изображение](https://user-images.githubusercontent.com/15066688/114813915-7f538000-9dcc-11eb-9ac9-ef1cd02625f8.png)
`Did not register exception handlers: Crashlytics SDK was not initialized
UnityEngine.Debug:Log(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.tpC7OdQUHa/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:89)
Firebase.LogUtil:LogMessage(LogLevel, String) (at Z:/tmp/tmp.JYnsY9apCV/firebase/app/client/unity/proxy/LogUtil.cs:68)
Firebase.Crashlytics.PlatformAccessor:.cctor() (at Z:/tmp/tmp.t4KIuy72sN/firebase/crashlytics/client/unity/proxy/Crashlytics.cs:123)
Firebase.Crashlytics.Crashlytics:Initialize() (at Z:/tmp/tmp.t4KIuy72sN/firebase/crashlytics/client/unity/proxy/Crashlytics.cs:59)
System.Reflection.MethodBase:Invoke(Object, Object[])
Firebase.FirebaseApp:InitializeCrashlyticsIfPresent() (at Z:/tmp/tmp.JYnsY9apCV/firebase/app/client/unity/proxy/FirebaseApp.cs:507)
Firebase.FirebaseApp:<CreateAndTrack>m__1() (at Z:/tmp/tmp.JYnsY9apCV/firebase/app/client/unity/proxy/FirebaseApp.cs:635)
Firebase.Dispatcher:Run(Func`1) (at Z:/tmp/tmp.tpC7OdQUHa/firebase/app/client/unity/src/Platform/Dispatcher.cs:40)
Firebase.Platform.FirebaseHandler:RunOnMainThread(Func`1) (at Z:/tmp/tmp.tpC7OdQUHa/firebase/app/client/unity/src/Unity/FirebaseHandler.cs:115)
Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp) (at Z:/tmp/tmp.JYnsY9apCV/firebase/app/client/unity/proxy/FirebaseApp.cs:633)
Firebase.FirebaseApp:Create() (at Z:/tmp/tmp.JYnsY9apCV/firebase/app/client/unity/proxy/FirebaseApp.cs:119)
Firebase.FirebaseApp:get_DefaultInstance() (at Z:/tmp/tmp.JYnsY9apCV/firebase/app/client/unity/proxy/FirebaseApp.cs:94)
Firebase.Sample.Crashlytics.UIHandler:InitializeFirebase() (at Assets/TestCrash/UIHandler.cs:63)
Firebase.Sample.Crashlytics.<Wait5>d__9:MoveNext() (at Assets/TestCrash/UIHandler.cs:50)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes.
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
Just fallow guide.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.
Link to 2020.1.17f1 project.
https://drive.google.com/file/d/1vPe5NqXjDS7XgL6672uvnEOtwMQckYLY/view?usp=sharing

Related issue #963

**Comment by paulinon** [comment]
Hi @Dimidrol112,

Take note that crashes reported from the SDK are non-fatal unless you're using some native code to force crashes. Could you verify if you're receiving any crashes by removing the filters from your Crashlytics dashboard?

**Comment by Dimidrol112** [comment]
Yes. I removed filter and can see now. But is it ok to have this errors?

**Comment by paulinon** [comment]
Thanks for confirming, @Dimidrol112. Having these reports means that Crashlytics has been successfully enabled for your app. Also, take note that Crashlytics reports will be sent after your app is relaunched.

I'll be closing this for now. Feel free to reopen if you have any other questions or if an issue arises.

Thanks!
