### ISSUE TITLE
[Question] [Dynamic Links] "No pre-install link matched for this device." on iOS but Android works

### ISSUE THREAD

**Issue by PlayaPeter** [firebase/quickstart-unity#1029]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.3f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: FirebaseDynamicLinks.unitypackage, FirebaseMessaging.unitypackage
  * Problematic Firebase Component: Dynamic Links
  * Other Firebase Components in use: Cloud Messaging
  * Additional SDKs you are using: Facebook, Fyber, AppsFlyer, Ultimate Mobile Pro, Game Analytics
  * Platform you are using the Unity editor on: MacOS Catalina 10.15.6 (for iOS), Win 10 (for Android)
  * Platform you are targeting: iOS, Android, Win, Mac, Browser
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

I'm using Firebase Dynamic Links and they are working fine on Android.
I can't manage to make them work properly on iOS though. I'm testing like this:

1. Uninstall app
2. Click the (short) dynamic link (https://link.sfgame.net/link/deal) in the Notes app
3. The browsers opens with the interstitial webpage. Continue with the checkbox checked. App store opens with the right app.
4. Build and run the app via XCode on the same device (because app store doesn't have the latest build)

Expected behavior: I get the data from the deeplink I clicked before.
Actual behavior: I get this error:
`7.5.0 - [Firebase/Analytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    "match_message" = "No pre-install link matched for this device.";
    "request_ip_version" = "IP_V4";
}`

The link is added as associated domain ("applinks:link.sfgame.net"). I also added the "FirebaseDynamicLinksCustomDomains" array to plist with the value "https://link.sfgame.net/link". GoogleService-Info.plist is also in the right folder.

Any idea what's wrong? I'm running out of things I can try.
Is it possible that other plugins interfere with Firebase? Multiple of the other plugins also support deep linking but none of them prints the correct deep link data.

**Comment by paulinon** [comment]
Hi @PlayaPeter,

In order to identify what could be causing the issue, could you provide a minimal, reproducible example of your project that I can run locally? You may also try our quickstart and see if the you can replicate the same issue as a baseline for troubleshooting.

**Comment by PlayaPeter** [comment]
@paulinon Thank you for the quick reply.

I was able to successfully test it with the quickstart project. By comparing the actual project and the quickstart project I found out that for some reason my FirebaseDynamicLinksCustomDomains-array was removed/not properly added to the plist. After adding it manually it worked.

Problem solved.
