### ISSUE TITLE
Is firebase-analytics required when using firebase-auth?

### ISSUE THREAD

**Issue by Whyser** [firebase/quickstart-unity#103]
Is there a dependency between the two? 

I'm trying to minimize the amount of ref count (DEX-limit stuff). And currently I only wanna use the ´firebase-auth´, but it seems that it comes bundled with ´firebase-analytics´ which uses around 5k refs.

Is it safe to remove ´firebase-analytics´? My guess is not, but would like to confirm, and also make a wish for the decoupling of the two?

**Comment by stewartmiles** [comment]
Yep Firebase Analytics is required by all Firebase components for the suite to work correctly.

To reduce the number of included methods you can export to Android Studio and enable proguard for the moment.   We currently have experimental proguard stripping support in https://github.com/googlesamples/unity-jar-resolver but unfortunately we're having some issues specifically with the Analytics AAR at the moment.

@johnb003 FYI

**Comment by Whyser** [comment]
Thanks for the quick response! I've never used Proguard, does it apply to the whole project, or is it possible to use only for certain libs (like play services)?

Thanks again!

**Comment by stewartmiles** [comment]
Yep proguard applies to your whole project.  See
https://developer.android.com/topic/performance/reduce-apk-size.html and
https://developer.android.com/studio/build/shrink-code.html

**Comment by Whyser** [comment]
I thought as much, with all libs currently in the project it seems risky to try proguard:ing it. Thanks anyway, I'll have to stick with the Firebase REST API for now.
