### ISSUE TITLE
[Question] Game Package Registry (GPR) by Google will shut down on May 19, 2021

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#1030]
Received an email saying that will have to go back to the old way installing .unitypackage

I would like to know why because I think is going a step back

**Comment by thsbrown** [comment]
You are not the only one that feels this way. Many others have expressed frustration in the issue https://github.com/firebase/quickstart-unity/issues/1029.

**Comment by thsbrown** [comment]
Context for anyone else seeing this

![image](https://user-images.githubusercontent.com/2967721/115444800-e5c01000-a1c9-11eb-9fb5-de86631b9508.png)

**Comment by uprootstudios** [comment]
Also mentioned here https://github.com/firebase/quickstart-unity/issues/1028

**Comment by MartinGonzalez** [comment]
Thanks for sharing other issues!

**Comment by ErnSur** [comment]
I suspect that this is a problem with the management of the Game Package Registry, not the UPM package format itself. For this reason, I **strongly suggest** you keep the current SDK folder structure that is compatible with UPM while delivering it in ".unitypackage". This way we can still get some advantages of the UPM system. There are multiple ways to use local UPM packages.

**Comment by stopiccot** [comment]
Can Firebase explain the reason why the do this?

**Comment by mgrogin** [comment]
now that UPM isnt supported Whats the right way to deal with this github issue? remote: error: File Assets/Firebase/Plugins/x86_64/FirebaseCppApp-7_1_0.so is 105.01 MB; this exceeds GitHub's file size limit of 100.00 MB

**Comment by fliperamma** [comment]
Sorry for the language, but this sucks 💔

**Comment by snorrsi** [comment]
Stopping support of this easy installation way is incredible bad decision.
UPM made my life so much easier dealing with firebase packages and dependencies between them.

> now that UPM isnt supported Whats the right way to deal with this github issue? remote: error: File Assets/Firebase/Plugins/x86_64/FirebaseCppApp-7_1_0.so is 105.01 MB; this exceeds GitHub's file size limit of 100.00 MB

@mgrogin you could use Git LFS

**Comment by stopiccot** [comment]
Wow, to use Git LFS only because of Firebase libraries

**Comment by stopiccot** [comment]
It's time write feature requests to get UPM packages back https://firebase.google.com/support/troubleshooter/report/features

**Comment by snorrsi** [comment]
As Firebase was using Scoped Registries, can´t we set up scoped registries ourselves since they no longer seem to care about customer support.
If anyone tries to setup scoped registry it would be very interesting to hear about their efforts.
I will try it later when I have more time although clock is ticking.
Please Firebase at least extend this too short period before deprecation.
Honestly I was expecting they would rather force us to use UPM and stop using the horrid unitypackage install which is as any of you know terrible to keep track of in Git.

Why oh why?

**Comment by kalikane** [comment]
I'm so sad about this news. but I have a question What going to happen if we just keep the actual  firebase SDK? the only problem I see is I wouldn't be able to upgrade this version of a firebase by UPM

**Comment by mgrogin** [comment]
> As Firebase was using Scoped Registries, can´t we set up scoped registries ourselves since they no longer seem to care about customer support.
> If anyone tries to setup scoped registry it would be very interesting to hear about their efforts.
> I will try it later when I have more time although clock is ticking.
> Please Firebase at least extend this too short period before deprecation.
> Honestly I was expecting they would rather force us to use UPM and stop using the horrid unitypackage install which is as any of you know terrible to keep track of in Git.
> 
> Why oh why?

There's this: https://developers.google.com/unity/instructions#install-tgz but I'm not sure they'll continue to support it...

**Comment by snorrsi** [comment]
> I'm so sad about this news. but I have a question What going to happen if we just keep the actual  firebase SDK? the only problem I see is I wouldn't be able to upgrade this version of a firebase by UPM 

@kalikane I suspect that you will have trouble every time you try to use your project on another computer which has not stored the packages in their Unity package cache.
Getting errors about being unable to fetch the packages which if you actively are using Firebase without build define settings based on existence of included frameworks would surely end up with errors and asking you to load the project in safe mode.

**Comment by chkuang-g** [comment]
Thanks for the feedback. It matters a lot to us.  

Our previous solution is no longer compatible with Unity's vision for scoped registries as reflected in their new [package guidelines](https://forum.unity.com/threads/updates-to-our-terms-of-service-and-new-package-guidelines.999940/), so we've decided to switch to [Google APIs for Unity](https://developers.google.com/unity).  

[We still provide .tgz files](https://developers.google.com/unity/archive) for developers and will continue to invest in this format.

We'll continue to seek new ways to improve the experience, and this feedback helps us understand what's working and what's not.

**Comment by uprootstudios** [comment]
> Our previous solution is no longer compatible with Unity's vision for scoped registries as reflected in their new [package guidelines](https://forum.unity.com/threads/updates-to-our-terms-of-service-and-new-package-guidelines.999940/)

What is provided by you in the scoped registry that falls outside the limitations defined in the package guidelines?

**Comment by ErnSur** [comment]
I think this is it:
> Can I create a package that add other optional package dependencies to enable more features in this package by clicking a button?
No. If the package is intended for external distribution beyond your designated users, this use case does not comply with the Terms of Service.

and:

> Can I create a package that add a scoped registry into their project by clicking a button?
> No. If the package is intended for external distribution beyond your designated users, this use case does not comply with the Terms of Service.

Basically, Unity is now prohibiting the use of "Unity Editor as a marketing or distribution platform".

**Comment by HitCache** [comment]
> As Firebase was using Scoped Registries, can´t we set up scoped registries ourselves since they no longer seem to care about customer support.
> If anyone tries to setup scoped registry it would be very interesting to hear about their efforts.

Maybe via OpenUPM? There is some informal Firebase related stuff already I see (https://openupm.com/packages/com.dopamine.firebase.core/) but I haven't looked into it yet that's just the first thing that came to mind where maybe the dependency issue could be solved. @favoyang might know more?

**Comment by snorrsi** [comment]
> > As Firebase was using Scoped Registries, can´t we set up scoped registries ourselves since they no longer seem to care about customer support.
> > If anyone tries to setup scoped registry it would be very interesting to hear about their efforts.
> 
> @snorrsi Maybe via OpenUPM? There is some informal Firebase related stuff already I see (https://openupm.com/packages/com.dopamine.firebase.core/) but I haven't looked into it yet that's just the first thing that came to mind where maybe the dependency issue could be solved. @favoyang might know more?

@HitCache there seems to be some issue with terms with using Scoped Registries. I suspect that also applies with OpenUPM.
It would also be greatly appreciated if OpenUPM packages which are copies of other frameworks could use same version numbering as the frameworks they are based upon.

Personally I think that the Github solution I mentioned on #1028 would be easy solution for this, not requiring Scoped Registry. However the dependencies issue with Github urls needs to be solved and EDM4U could do that if Unity allows.

**Comment by HitCache** [comment]
Hail marry throw here but @joeante can Unity just fix the terms please so hoardes of people don't have to spend all this brain power finding workarounds to get our job done? And then inevitably flip back to UPM when Unity pulls their head out of sand three years later?

Can we PLEASE skip the whole song and dance this time entirely?

**Comment by favoyang** [comment]
@HitCache thanks for inviting me to the discussion.

I only operate the [OpenUPM](https://openupm.com/) project, and I don't work for Unity. Though I have some discussions with Unity term teams, what I write here is based on my understanding. To get the official feedback, please reach to terms@unity3d.com.

#### Why GPR not compatible with [Unity Package Guidelines](https://unity3d.com/legal/terms-of-service/software/package-guidelines)?

I downloaded the firebase from Google API for Unity website, and import it to Unity. I found two parts that may break the Unity terms.

First, during the setup processes, it asks to allow Google to track in-editor usage with Google to improve this product. This is clearly disallowed, UPM packages can not contain an in-editor analytics feature even with an opt-out option.

> B. You cannot make any Package (including via Package update) available from within the Unity Editor to third parties (other than your Designated Users) if such Package provides a service that collects or aggregates data. For example:
> A Package that enables a third party analytics service. 

![image](https://user-images.githubusercontent.com/125390/115979141-bf79e600-a5b6-11eb-9fec-ce1a7961d4c4.png)
![image](https://user-images.githubusercontent.com/125390/115979143-c274d680-a5b6-11eb-9ddc-9e9aeaf04833.png)

Solution: remove the in-editor feature entirely.

Second, the firebase panel contains a few buttons to link to the documentation website. From here you can visit other marketing features like the pricing page to promote other products.

![image](https://user-images.githubusercontent.com/125390/115979397-4aa7ab80-a5b8-11eb-93ed-6f19354e0cfa.png)

It may break the terms:

> A. You cannot make any Package (including via Package update) available from within the Unity Editor to third parties (other than your Designated Users) that, directly or indirectly, advances or is intended to advance the commercial or economic interests of you and/or your affiliated entities.  For example:
> A Package that induces a person to buy or subscribe to products or services.
> A Package that otherwise enables or affects a commercial transaction.

I also like to list a few practices that will be considered as marketing efforts.
- Using in-editor script to help set up a scoped registry.
- Using in-editor script to help install/update other packages.
- Using banner/image/text/link to promote other packages/products.

Basically think of Kindle for iOS, you can have a UI to login to your account to fetch content you purchase already, you can also have QA, documentation on a website. But you can not provide a way to directly/indirectly visit your paid content.

Solutions
- Remove the firebase panel entirely, let users find documentation from the web on their own.
- Or, create a dedicated website for documentation that strip any links may reach your paid content.
- Or, embed documentation with the package.
- Or, reach to Unity for Verified Solutions Partners, which has a separate agreement that won't need to follow the package terms.

#### Is it safe to use the community bundled packages from OpenUPM?

Short answer: No, (at the moment).

As an open-source community,
- We don't guarantee software collected by the service is 100% working technically speaking of dependencies and bug fixes. You have to reach to the package author for details. 
- We try our best to follow the Unity terms, but still in a trial-and-error process. If users find something packages break terms or local law, reach to us for a review, and we may remove the content.

The Firebase SDK is [open-sourced](https://opensource.google/projects/firebase-sdk) to allow a community re-bundle.

The current Firebase contents ([core](https://openupm.com/packages/com.dopamine.firebase.core/), [analytics](https://openupm.com/packages/com.dopamine.firebase.analytics/), [remote config](https://openupm.com/packages/com.dopamine.firebase.remoteconfig/)) are maintained by @dopaminegamesstudio and @uchar

I installed the core package, it has the same issue as the official package. That means it will be removed later.

If anyone has the energy to read the thread carefully and remove anything that may break the Unity terms, I'm happy to bring it back. Please notice your package name can not start with "com.google" to imply it's an official bundle.

**Comment by chkuang-g** [comment]
Thank you for the feedback.

Game Package Registry by Google was shut down as planned this week. [Google APIs for Unity](https://developers.google.com/unity) is the solution we will continue to invest in.

We continue to support the tgz format on the [Google APIs for Unity archive page](https://developers.google.com/unity/archive). URLs for accessing these files haven’t changed, and we have no plans to change them.

We are committed to improving workflows for Unity developers, and we’re very open to feedback. If you have suggestions, please make a [feature request](https://github.com/firebase/quickstart-unity/issues/new/choose) or upvote an existing one.
