### ISSUE TITLE
[Question] First_open event in Firebase analytics

### ISSUE THREAD

**Issue by jk296** [firebase/quickstart-unity#1033]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.0f1
  * Firebase Unity SDK version: 6.6.0
  * Source you installed the SDK: Firebase website (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Additional SDKs you are using: Admob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS and Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:

Hi,
I have one question regarding Firebase analytics.
I noticed that some first_open events shown are older verions of my app, both on iOS and Android.
Does anyone know why older versions are logged as first_open?
Could it be:
1. Users transferred the app to a new device, and it is logged as a first_open event when the user opens the app.
2. It may be an app_update event, but logged as a first_open event.
3. Users downloaded the app from App Store or Google Play, but never opened the app. After some time the users open the app, and logged as first_open events.
4. Users can download older versions from App Store or Google Play.
5. Other reasons.
Many thanks for your help!

**Comment by paulinon** [comment]
Hi @jk296,

The first_open event is triggered based on app installation or reinstallation. When first_open events are being logged, it's possible that there are users who downloaded the app via methods other than the Play Store/App Store, so the app's version remains.

I noticed that you're using an old version of the SDK. I recommend that you use the latest version (7.1.0) as this contains the latest improvements and bug fixes.

I'll be closing this for now. Let me know if you have any SDK-related questions. Thanks!
