### ISSUE TITLE
[Bug] Firebase iOS builds are not supported on Windows. Please build on a OSX machine instead.

### ISSUE THREAD

**Issue by slaw** [firebase/quickstart-unity#1044]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version:  Any
  * Firebase Unity SDK version: Any
  * Source you installed the SDK: Any (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows  (Mac, Windows, or Linux)
  * Platform you are targeting:  iOS (iOS, Android, and/or desktop)
  * Scripting Runtime:  IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

I have seen this posted before and I want to bring more attention to it.

This error message is driving me and my team crazy. We develop on windows machines - including for iOS.
There are 3 ways we build for iOS from our Windows machines.

    Unity Cloud Build
    Headless networked Mac
    iOS Project Builder for Windows

I understand it's purpose, but please add a way to suppress this message from spamming the console.

#### Steps to reproduce:

Every code recompile spams this error message in the console.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @slaw, I just noticed that you left a comment in #976. I'll be closing this ticket and marking it as a duplicate for now, but you may refer to any updates using that thread.
