### ISSUE TITLE
[Bug] Crashed: com.google.fira.worker

### ISSUE THREAD

**Issue by a314266177** [firebase/quickstart-unity#1045]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: ___2018.4.11f1__
  * Firebase Unity SDK version: __7.2.0___
  * Source you installed the SDK: ___unitypackage__ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: __I don't know___ (Auth, Database, etc.)
  * Other Firebase Components in use: __RemoteConfig,Crashlytics,Analytics,Performance___ (Auth, Database, etc.)
  * Additional SDKs you are using: ___Facebook,Admob,Appsflyer,MaxSDK__ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: __iOS___ (Mac, Windows, or Linux)
  * Platform you are targeting: __iOS___ (iOS, Android, and/or desktop)
  * Scripting Runtime: __IL2CPP___ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Crashed: com.google.fira.worker
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000c34bd7560
objc_release

Crashed: com.google.fira.worker
0  libobjc.A.dylib                0x1a92b7de0 objc_release + 16
1  libobjc.A.dylib                0x1a92b9574 AutoreleasePoolPage::releaseUntil(objc_object**) + 200
2  libobjc.A.dylib                0x1a92b9450 objc_autoreleasePoolPop + 208
3  libdispatch.dylib              0x194b50260 _dispatch_last_resort_autorelease_pool_pop + 40
4  libdispatch.dylib              0x194af9908 _dispatch_lane_invoke$VARIANT$mp + 520
5  libdispatch.dylib              0x194b03338 _dispatch_workloop_worker_thread + 712
6  libsystem_pthread.dylib        0x1dc94d5a4 _pthread_wqthread + 272
7  libsystem_pthread.dylib        0x1dc950874 start_wqthread + 8

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

I can't reproduce the problem

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Direct normal boot is likely to be found

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

[Firebase_UseFrameworks_UnityIPhone.txt](https://github.com/firebase/quickstart-unity/files/6465183/Firebase_UseFrameworks_UnityIPhone.txt)

**Comment by a314266177** [comment]
Now this problem affects a lot of users, hope to get effective help

**Comment by paulinon** [comment]
Hi @a314266177,

In order to identify what's causing the issue, I'd like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project and the complete steps you've taken before facing this issue.

Thanks!

**Comment by a314266177** [comment]
> Hi @a314266177,
> 
> In order to identify what's causing the issue, I'd like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project and the complete steps you've taken before facing this issue.
> 
> Thanks!

I think this problem should be related to my receiving a new SDK, I only got this problem after I received the SDK of Max, but this problem is suggested by the problem in Firebase, I have a little doubt that it is the conflict between different versions in Google, I can tell you roughly how this problem will occur. You open a new project, then access Firebase SDK (RemoteConfig Crashlytics, Analytics, and Performance) and such, and facebook, and then the next step is to continue to access the Max SDK, link: https://dash.applovin.com/documentation/mediation/unity/getting-started/integration, there is a probability will be I the problem now, I bad also to reproduce the problem

**Comment by paulinon** [comment]
Hi @a314266177,

In order to verify this claim, could you verify if the issue persists in your implementation without the Firebase SDKs? If not, it would be great if you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that we can isolate how Firebase is causing this behavior.

**Comment by a314266177** [comment]
> Hi @a314266177,
> 
> In order to verify this claim, could you verify if the issue persists in your implementation without the Firebase SDKs? If not, it would be great if you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that we can isolate how Firebase is causing this behavior.

Hello, I think I know what the problem is. I have solved it

**Comment by paulinon** [comment]
That's great to hear, @a314266177. Could you share the steps you've done in resolving the issue? This way, this thread could be helpful for other developers with a similar issue.

**Comment by a314266177** [comment]
> That's great to hear, @a314266177. Could you share the steps you've done in resolving the issue? This way, this thread could be helpful for other developers with a similar issue.

I received your native AdMob ads for my own project, and then I received other SDKs with the AdMob SDK in the intermediary, and then your own AdMob SDK itself came into conflict, something like this

**Comment by paulinon** [comment]
Thanks for sharing this, @a314266177. With that, I'll be closing this ticket for now. Let me know if you have any questions or if the issue arises.
