### ISSUE TITLE
[Question] Trouble with collection group security rules

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1046]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.7f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK:  Unity Package Manager
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: 
  * Additional SDKs you are using:
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP)

### [REQUIRED] Please describe the question here:

I'm having the following Firestore structure:
```
root
-main_collection
--group1 (random document ID)
---users (fixed collection ID)
----user1 (random document ID)
----user2 (random document ID)
--group2 (random document ID)
---users (fixed collection ID)
----user1 (random document ID)
...
```

With this, I'm trying to query all "users" collections with the collection group feature, but using `firestoreDB.CollectionGroup("users").GetSnapshotAsync()` results in a permission exception with my current security rules. 

What would be the correct rules for this scenario?

**Comment by thebrianchen** [comment]
@Nyankoo Can you provide the permissions exception you are getting along with the security rules you are using? Thanks!

**Comment by Nyankoo** [comment]
@thebrianchen The exception is `FirestoreException: Missing or insufficient permissions.`

```
match /main_collection/{groupid}/users/{document=**} {
      allow create, read, update: if request.auth != null;
      allow delete: if false;
    }
```

I'm still trying to learn how to write these rules, so any tips would be appreciated!

**Comment by thebrianchen** [comment]
@Nyankoo Based on your rules, reads are allowed as long as the the user is signed in or authenticated to the application, so your reads are failing because you're not authenticated. You probably need to sign in with [FirebaseAuth](https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth) before sending the request for it to succeed.

For help writing security rules, please refer to our [documentation](https://firebase.google.com/docs/firestore/security/get-started), or watch one of our videos ([1](https://www.youtube.com/watch?v=eW5MdE3ZcAw), [2](https://www.youtube.com/watch?v=8Mzb9zmnbJs)).

I'm going to mark this issue as closed because it doesn't seem like there's a bug with the underlying SDK. Please feel free to ask any follow up questions you may have though!

**Comment by Nyankoo** [comment]
@thebrianchen I'm authenticated when testing this, please re-open!

**Comment by thebrianchen** [comment]
@Nyankoo Sorry about that! Can you please provide a repro sample for us to reproduce the error?

**Comment by Nyankoo** [comment]
@thebrianchen So the above security rule is correct with my posted Firebase structure and the `CollectionGroup` call?

**Comment by thebrianchen** [comment]
@Nyankoo The `CollectionGroup.GetSnapshotAsync()` call on its own will not work with the security rules you have pasted. You will need to sign in first, such as with `FirebaseAuth.SignInAnonymouslyAsync()` in order for the `request.auth != null` check in your security rules to allow the read.

**Comment by Nyankoo** [comment]
@thebrianchen Yes, I know that! What I meant is if what I posted above is correct in general? When doing the call, the client is already signed in.

**Comment by Nyankoo** [comment]
@thebrianchen To update on this, the following rule also creates a `FirestoreException: Missing or insufficient permissions.`:

```
match /wlb/{groupid}/p/{document=**} {
      allow create, read, update;
      allow delete: if false;
    }
```

This more sounds like an issue that the path doesn't exist compared to a permission issue.

**Comment by thebrianchen** [comment]
@Nyankoo Actually, your security rules are incorrect for the path you've specified. For collection group queries, you'll need to use the wildcard at the top level: `match /{path=**}/users/{doc}` along with `rules_version = '2';`. There's a section in the [documentation](https://firebase.google.com/docs/firestore/security/rules-query#secure_and_query_documents_based_on_collection_groups) that explains Version 2 of rules, and why you need to start the rule with the `{path=**}` wildcard.

**Comment by Nyankoo** [comment]
Thank you for the explanation, working now!
