### ISSUE TITLE
[Bug] Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly. Firebase.AppUtil:PollCallbacks() Firebase.Platform.FirebaseHandler:Update()

### ISSUE THREAD

**Issue by surajsk1812** [firebase/quickstart-unity#1047]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _2019.4.5f1
  * Firebase Unity SDK version: 7.0.0
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component:  Auth, Analytics, Dynamic Links (Auth, Database, etc.)
  * Other Firebase Components in use:  (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, Admob(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS and Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
Getting "Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly. Firebase.AppUtil:PollCallbacks() Firebase.Platform.FirebaseHandler:Update()" When i launch iOS build.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
1. Launch the app

**Logs**
1. Failed to read Firebase options from the app's resources (). Either make sure GoogleService-Info.plist is included in your build or specify options explicitly. Firebase.AppUtil:PollCallbacks() Firebase.Platform.FirebaseHandler:Update()
2. App ID, API key, and Project ID must be specified in App options. Firebase.AppUtil:PollCallbacks() Firebase.Platform.FirebaseHandler:Update()

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
**PodFile**
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 9.0'
  pod 'FBSDKGamingServicesKit', '~> 9.0'
  pod 'FBSDKLoginKit', '~> 9.0'
  pod 'FBSDKShareKit', '~> 9.0'
  pod 'Firebase/Analytics', '7.0.0'
  pod 'Firebase/Auth', '7.0.0'
  pod 'Firebase/Core', '7.0.0'
  pod 'Firebase/DynamicLinks', '7.0.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.68'
  pod 'GoogleSignIn', '>= 4.0.2'
end
target 'Unity-iPhone' do
end
use_frameworks!

**Comment by surajsk1812** [comment]
Facebook SDK version is 9.0.0
Admob version 5.4.0

I know there are duplicate issues of this issue, but I didn't get any solution or I couldn't understood the solution.
Before marking it has a duplicate of any issue please send me proper solution.

**Comment by paulinon** [comment]
Hi @surajsk1812,

It seems that you're facing an issue similar to what's described in #862. Using SDK version 7.1.0 or higher should resolve this. 

With that, I'll be closing this ticket for now. Let me know if you have any other questions or if your scenario is different from what I described.
