### ISSUE TITLE
[FR] Allow opting out of reporting analytics in the editor

### ISSUE THREAD

**Issue by tallior** [firebase/quickstart-unity#1048]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "[FR]".

### Feature proposal

* Firebase Component: Editor

The Firebase SDK for Unity reports analytics events to Google Analytics via the **Measurement** class.
There's no option to opt out of this.

1. Teams concerned with their privacy should be able to opt out of this process 
2. The code used for this slows down the editor performance (entering play mode, for example).

Please allow disabling this behaviour.

**Comment by paulinon** [comment]
Hi @tallior,

You can temporarily disable Analytics collection for your Unity implementation, and the steps to do this depend on your intended platform ([Android](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#disable_data_collection), [iOS](https://firebase.google.com/docs/analytics/configure-data-collection?platform=ios#disable_data_collection)).

I'll be closing this ticket for now. Let me know if you have questions or if what I suggested doesn't work with your use case.

**Comment by tallior** [comment]
@paulinon i was referring to data Firebase are collecting in the Unity editor. These links are not relevant for that case.

**Comment by cynthiajoan** [comment]
Hi @tallior, you can turn that off through Assets->External Dependency Manager->Package Manager Resolver->Settings, and uncheck "Enable Analytics Reporting".
<img width="349" alt="Screen Shot 2021-05-19 at 8 49 01 AM" src="https://user-images.githubusercontent.com/2354618/118844579-e9ee5480-b87f-11eb-8afa-751eef7f8e9c.png">

**Comment by chkuang-g** [comment]
Hi @tallior

- There are actually options to opt out in the setting menu. However, there are two settings menu you will need visit
   1. Disable editor usage reporting from EDM4U.  You can find the option in ANY settings from EDM4U. @cynthiajoan  mentioned about the one from Package Manager Resolver. But all EDM4U components use the same flag. For instance, you can disable it in `Assets > External Dependency Manager > Version Handler > Settings` menu item as well.
   2. Disable editor usage reporting from Firebase editor tool. You can find the option at the very bottom of `Windows > Firebase > Documentation`. 
      <img width="394" alt="Screen Shot 2021-05-24 at 1 59 46 PM" src="https://user-images.githubusercontent.com/31869252/119407033-8063b100-bc98-11eb-8d44-cb3cb99dd443.png">
- Editor usage reporting is DISABLED by default until it receives the user's consent, which is a pop-up dialog. There are one consent **per product** (ex. EDM4U and Firebase) **per machine**. Before the consent is received, there will be NO data reporting even though the settings described in the previous section is enabled. 
   <img width="736" alt="Screen Shot 2021-05-24 at 2 07 00 PM" src="https://user-images.githubusercontent.com/31869252/119407736-7f7f4f00-bc99-11eb-8ec2-167a066d1d4b.png">
- We are absolutely not sending any personal data and we are using anonymous GUID for each machine. You can double check [our implementation in EDM4U](https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/EditorMeasurement.cs). If you like to know what EDM4U reports, you can do a quick code search, like [this one](https://github.com/googlesamples/unity-jar-resolver/search?q=%22.Report%28%22+extension%3Acs). Unfortunately Firebase editor tool is not open-sourced yet. 
- We are considering adding a team-wide flag to disable measurement entirely for all machine and all products. See the [FR here](https://github.com/googlesamples/unity-jar-resolver/issues/387).

Hope this answer your question! I understand your concern and we take privacy pretty serious.
If you still choose to send us your editor usage, the data will help us to identify the issue and to improve the products.

Shawn
