### ISSUE TITLE
[Bug] Using FieldPath.DocumentId results in editor crash

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1054]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.9f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: Unity Package Manager with tgz
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Auth, Crashlytics, Remote Config
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

When using `FieldPath.DocumentId` to filter a query, the editor crashes:
`firestoreDB.CollectionGroup("p").WhereEqualTo(FieldPath.DocumentId, "1234").GetSnapshotAsync();`

**Comment by dconeybe** [comment]
Hello again, @Nyankoo. Thank you for reporting the issues that you're running into with the Firebase Unity SDK. Like #1053, I'll take a look at this one on Tuesday as well (Monday is a holiday in Canada where I'm located). Would you be able to provide the stack trace and crash information from the Android logcat?

**Comment by Nyankoo** [comment]
@dconeybe The crash on the editor results in a different "type" of crash compared to the one in the other issue:
![crash](https://user-images.githubusercontent.com/6652214/119258300-5f805a80-bbc9-11eb-8585-8631a400217a.png)

On Android, logcat shows this:
```
2021.05.23 13:16:02.106 18687 18840 Error Unity FirestoreException: This instance is in an invalid state. This could either because the underlying Firestore instance has been destructed or because you're running on an unsupported platform.
2021.05.23 13:16:02.106 18687 18840 Error Unity   at Firebase.Firestore.Internal.Util.FlattenAndThrowException (System.Threading.Tasks.Task completedTask) [0x00000] in <00000000000000000000000000000000>:0 
2021.05.23 13:16:02.106 18687 18840 Error Unity   at Firebase.Firestore.Internal.Util+<MapResult>c__AnonStorey0`2[T,U].<>m__0 (System.Threading.Tasks.Task`1[TResult] completedTask) [0x00000] in <00000000000000000000000000000000>:0 
2021.05.23 13:16:02.106 18687 18840 Error Unity   at System.Func`2[T,TResult].Invoke (T arg) [0x00000] in <00000000000000000000000000000000>:0 
2021.05.23 13:16:02.106 18687 18840 Error Unity   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00000] in <00000000000000000000000000000000>:0 
2021.05.23 13:16:02.106 18687 18840 Error Unity   at System.Threading.Tasks.Task.Execute () [0x00000] in <00000000000000000000000000000000>:0 
2021.05.23 13:16:02.106 18687 18840 Error Unity   at System.Threading.ContextCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
2021.05.23 13:16:02.106 18687 18840 Error Unity   at System.Threadin
```

Especially the last part (`running on an unsupported platform`) makes me worry, as the function to filter after a document ID would be really helpful to minimize what's loaded from Firestore.

**Comment by dconeybe** [comment]
Hmmm interesting. Sorry for the additional request, but could you attach the unity editor log as well? That will have some extra crash information too.

https://docs.unity3d.com/Manual/LogFiles.html

**Comment by Nyankoo** [comment]
@dconeybe No worries! Here is the error message from Unity's editor log:

`ERROR: Invalid argument: Invalid query. When querying a collection group by document ID, the value provided must result in a valid document path, but '1234' is not because it has an odd number of segments.`

"1234" is actually a random alphanumeric string, which I omitted here.

**Comment by dconeybe** [comment]
After some more investigation, I realized that the query being issued is indeed invalid (as the error message from the previous comment conveys); however, this should *not* crash the app or the Unity Editor. The good news is that this was a known issue and the fix will be included in the next Firebase Unity SDK release. The fix is to throw a C# exception instead of crashing. I'll reply back and close this issue once the fix is released. Googlers, see b/149105903 for details.

**Comment by dconeybe** [comment]
Unfortunately, when you specify `FieldPath.DocumentId` in the "where" clause of a collection group query it must specify a full document path.

One workaround you could use would be to explicitly add a field to the document whose value is the document ID. Then, you can query on this field in the collection group query.

**Comment by Nyankoo** [comment]
@dconeybe This is probably not changing in the future, correct? It just seems that adding an extra field to the document that holds it's own ID is a little bit redundant.

**Comment by dconeybe** [comment]
@Nyankoo That is correct: there are no plans to change this behavior. The suggested workaround is indeed bit redundant, but, unfortunately, it's the only workaround for the foreseeable future.
