### ISSUE TITLE
[Bug] The dynamic link reopens after reinstalling the app iOS Unity 

### ISSUE THREAD

**Issue by IvanKlimov1** [firebase/quickstart-unity#1056]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.2
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: DynamicLink (Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, CleverTap (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac and Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

The dynamic link reopens after reinstalling the app.

Please add API to clear dynamic link after receiving or fix the error.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
yeas i can

1. Create a dynamic link.
2. Click on the link
3. The application will open
4. Hide the application
5. Update the app
6. Open the app

as a result, the last dynamic link is opened again.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by IvanKlimov1** [comment]
we need at least something like that for iOS

https://github.com/firebase/quickstart-unity/issues/565#issuecomment-731660477

**Comment by paulinon** [comment]
Hi @IvanKlimov1,

I see that you're able to reproduce this issue with the quickstart, but I'd like to clarify the procedure you shared. When you said "Update the app", do you mean updating the app from the App Store?

Additionally, could you try updating the SDK to its latest version (7.2.0) and see if this makes a difference?

**Comment by IvanKlimov1** [comment]
"Update " I mean reinstall 

Hey I'll test it today with 7.2.0
