### ISSUE TITLE
[FR] Add binary support for x86_64

### ISSUE THREAD

**Issue by CIVITAS-John** [firebase/quickstart-unity#1058]
Hi,

We recently noticed that Unity added support for Chrome OS, which means they added binary support for x86 and x86_64. However, in recent versions of Google API for Unity, I could only see x86 .so binary files - which means if I used any of those packages, it is not possible for me to release anything to Chrome OS - because Google Play only accepts builds with BOTH x86 and x86_64. Could you please add x86_64 binaries?

Best,
John Chen

**Comment by paulinon** [comment]
Hi @CIVITAS-John,

It appears that this request isn't related to the Firebase SDK for Unity. You may file this at the [Google Play Plugins tracker](https://github.com/google/play-unity-plugins/issues) so that this could be handled accordingly.

With that, I'll be closing this ticket for now.
