### ISSUE TITLE
[Bug] Random Firebase DataBase 7.2 Unity Editor Crash 2020.3 when game logic calls to download a lot of data in a single call with many other small databse download calls. But no crash on android.

### ISSUE THREAD

**Issue by gputhread** [firebase/quickstart-unity#1059]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.11
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: unitypackage  (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database(Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here: Random Firebase DataBase 7.2 Unity Editor Crash 2020.3 when game logic calls to download a lot of data in a single call with many other small databse download calls. But no crash on android.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
- when game logic calls to download a lot of data in a single call with many other small databse download calls on firebase db.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by abogarsukov-braingames** [comment]
There is an issue for the same problem here: https://github.com/firebase/quickstart-unity/issues/933.

**Comment by dconeybe** [comment]
This issue has actually been reported several times in the past: https://github.com/firebase/quickstart-unity/search?q=SWIGRegisterStringCallback_StorageInternal&type=issues. It doesn't look like it was ever really resolved though. There is also a very recent duplicate #1053 that is supposedly triggered by access to the Firestore SDK. I'm looking into that one and since I suspect that this has the same root cause I'll look into this one too.

If possible, please attach the full Unity log file (https://docs.unity3d.com/Manual/LogFiles.html).

**Comment by gputhread** [comment]
> There is an issue for the same problem here: #933.

How to turn off presistent for editor? you said there it is the fix!

**Comment by abogarsukov-braingames** [comment]
@gputhread here's the code we use for this:
`protected void ResetUserId(string userId)
{
    FirebaseDatabase db;

    Crashlytics.SetUserId(userId);

    db = FirebaseDatabase.GetInstance(_app, GetUsersDatabaseUrl(userId));
#if UNITY_EDITOR
    db.SetPersistenceEnabled(false);
#endif
    _usersDatabaseReference = GetUserDatabaseRef(db, userId);

    db = FirebaseDatabase.GetInstance(_app, _appConfig.FirebaseGiftsDatabaseUrl);
#if UNITY_EDITOR
    db.SetPersistenceEnabled(false);
#endif
    _giftsDatabaseReference = GetGiftsDatabaseRef(db, userId);

    db = FirebaseDatabase.GetInstance(_app, _appConfig.FirebaseInternalDatabaseUrl);
#if UNITY_EDITOR
    db.SetPersistenceEnabled(false);
#endif
    _pushTokensDatabaseReference = GetPushTokensDatabaseRef(db, userId);
}`

**Comment by gputhread** [comment]
> @gputhread here's the code we use for this:
> ![image](https://user-images.githubusercontent.com/68687154/119623446-d8bdbe80-be10-11eb-85df-bd8d26f832bd.png)

Ok i will try root reference but do i need to call it everytime i set or get value?

**Comment by abogarsukov-braingames** [comment]
No, i should be enough to do this once per database reference.

**Comment by alexames** [comment]
Hi @gputhread  and @abogarsukov-braingames,

Do you have a minimal reproduction case that we could take a look at? Something is clearly going wrong here but it's hard to diagnose what without more information about the state of the editor when it crashes.

**Comment by gputhread** [comment]
Its crashing alot now in 7.2.0

**Comment by gputhread** [comment]
is this have any connection?
after editor crash silently this created in project:

* shadercompiler-UnityShaderCompiler.exe0.log

-Unhandled exception: Protocol error - failed to read magic number (error -2147483644, transferred 0/4)

-Quitting shader compiler process

**Comment by gputhread** [comment]
i thing its crashing when firebase Realtime database downdling alot of data like when i call to donwload a parent with 4 childs and those 4 child have 10 childs each with string data size 0-25 characters its crashing. i will confirm in a week.

**Comment by chkuang-g** [comment]
Ah, this seems to be fixed in `7.2.0`. https://github.com/firebase/quickstart-unity/issues/517

Could you update and see if the issue still occurs?

Shawn

**Comment by chkuang-g** [comment]
This seems to be similar to this issue https://github.com/firebase/quickstart-unity/issues/517

Hmm, it is claimed to be fixed in `7.2.0` but you still experience the issue.

Could you give me an example how the database node looks like, and the exact code about how you call Firebase Database API to get those data?

Thank you,
Shawn

**Comment by gputhread** [comment]
**Change of title**

1. Random FirebaseCppApp-7_1_0.dll crash Unity 2020.3 after hitting play button in editor! 

is no more!!!

Solution: It was may be by incorrect using of Application.onfucus which was terminating app at wrong time. I didnt see any more  SWIGRegisterStringCallback error on editor crash.

2. Now its: Random Unity Editor silent crash on downloading a lot of data from Realtime Database at single call in between parts of my game but no crash on android.

**Comment by gputhread** [comment]
> This seems to be similar to this issue #517
> 
> Hmm, it is claimed to be fixed in `7.2.0` but you still experienced the issue.
> 
> Could you give me an example how the database node looks like, and the exact code about how you call Firebase Database API to get those data?
> 
> It would save us a lot of time to track this issue with a minimum viable project (MVP). :)
> Even better if you can tell us how to modify the quickstart to reproduce this issue.
> 
> Also, I usually found the crash stack track from Unity not very useful. If you have Visual Studio, could you attach VS to Unity process and capture the exact callstack in different threads when the crash happens?
> 
> Thank you,
> Shawn

Reference.Child("Users").Child(auth.CurrentUser.UserId).GetValueAsync().ContinueWithOnMainThread(task =>
              {
                  if (task.IsFaulted)
                  {
                      Debug.Log(task.Exception);
                      return;
                  }
                  if (task.IsCompleted)
                  {
                      DataSnapshot Snapshot = task.Result;

                      if (Snapshot.Child("Parent1").HasChild("Child1"))
                      {
                          Name = Snapshot.Child("Parent1").Child("Child1").Value.ToString();
                      }
                      if (Snapshot.Child("Parent1").HasChild("Child2"))
                      {
                          MaskedName = Snapshot.Child("Parent1").Child("Child2").Value.ToString();
                      }
                     // ....+ 7 similar nodes like above.


                      return;
                  }
              });

// Child("Users").Child(auth.CurrentUser.UserId) has 4 nodes named parent1, parent2, parent3, parent4 all parents have 7-13 childs, all childs have 0-25character value. Like this: 

//Firebase Database structure of that parent child:

"auth.CurrentUser.UserId" : {
      "parent1" : {
        "Child1" : "valueeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        "Child2" : "",
        "Child3" : "value",
        "Child4" : "",
        "Child5" : "valueeeeeeeeeee",
        "Child6" : 1,
        "Child7" : "valueeeeeeeeeeeeee-valueeeeeeeeeeeeeeeee",
        "Child8" : "2",
        "Child9" : "valueeeeeeeeeeeeeeeeeeeee"
      },
      "parent2" : {
        "Child1" : "valueeeeeeeeeeeeeeeeeeee",
        "Child2" : "valueeeeeeeeeeeeeeeeeeeeeee"
      },
      "parent3" : {
        "Child1" : "",
        "Child2" : "0,0",
        "Child3" : "",
        "Child4" : "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
        "Child5" : "0",
        "Child6" : "8040",
        "Child7" : "0,0,0,0",
        "Child8" : "",
        "Child9" : "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
        "Child10" : "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
        "Child11" : "0,0,0,0,0,0,0",
        "Child12" : "2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2",
        "Child13" : "0,0,0",
        "Child14" : "0,2,2,2,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2",
        "Child15" : "0,0,0,0,0,0,0,0,0,0,0,0",
        "Child16" : "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
        "Child17" : "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
        "Child18" : "0,0,0,0,0,0,0,0,0",
        "Child19" : "0,0",
        "Child20" : "0,0,0,0,0,0,0",
        "Child21" : "99999"
      },
      "parent4" : {
        "Child1" : "19,4,0,0,0,0,0,1,0,1,2,9,4,7,1,0",
        "Child1" : "1,6,1,1,2,1,1",
        "Child1" : "0,4,0,0,0,0,0,1,0,1,2,10,4,7,1,0",
        "Child1" : "1,1,1,1,1,1,1",
        "Child1" : "0,4,0,0,0,0,0,1,0,1,2,10,4,7,1,0",
        "Child1" : "1,1,1,1,1,1,1",
        "Child1" : "0,4,0,0,0,0,0,1,0,1,2,10,4,7,1,0",
        "Child1" : "1,1,1,1,1,1,1",
        "Child1" : "2,2,2,2"


//the game logic calls many other smaller snapshots than this with this in the way:

Reference.Child("Users").Child(auth.CurrentUser.UserId).Child("parent2").GetValueAsync().ContinueWithOnMainThread(task =>
              {

**Comment by DellaBitta** [comment]
Hi @gputhread,

Unfotunately I'm still not able to reproduce this issue. I've created [a version of UIHandler.cs](https://gist.github.com/DellaBitta/ff0eb582c96b2243b56da475dc399327) which you can copy and paste over the Database Quickstart's version of UIHandler.cs.  This new version should populate your dataset into a `UnityIssue_1059` node in your database when you press the `BuildTable` button.  Note that you need only do this once, and you should wait a moment and confirm the data was populated by looking at your RTDB in the Firebase Console. 

Then you can run the queries by clicking `QueryTable`. The queries are run on each `parent1` -> `parent4` and the results are logged to the Unity console but also into the app itself.

Could you run this to see if it crashes for you, and if not can you rework this to make this crash?  I tested this on Mac and Windows editors using 7.1.0, 7.20, and 8.0.0.  

Thanks!

**Comment by gputhread** [comment]
Unity Editor by Unity Technologies [version: Unity 2020.3.11f1_99c7afb366b3]

FirebaseCppApp-8_0_0.dll caused an Access Violation (0xc0000005)
  in module FirebaseCppApp-8_0_0.dll at 0033:60bc27c8.

Error occurred at 2021-07-16_141438.
C:\CustomApps\UnityEngine\2020.3.11f1\Editor\Unity.exe, run by Admin.

30% physical memory in use.
24534 MB physical memory [16946 MB free].
2078 MB process peak paging file [1728 MB used].
1290 MB process peak working set [1263 MB used].
System Commit Total/Limit/Peak: 10446MB/28118MB/12762MB
System Physical Total/Available: 24534MB/16946MB
System Process Count: 203
System Thread Count: 2237
System Handle Count: 85701
Disk space data for 'C:\Users\Admin\AppData\Local\Temp\Unity\Editor\Crashes\Crash_2021-07-16_084425853\': 53364490240 bytes free of 215871385600 total.

Read from location 0000000000000000 caused an access violation.

Context:
RDI:    0x0000000000000000  RSI: 0x0000009da53ff8f0  RAX:   0x0000000000000000
RBX:    0x0000009da53ff620  RCX: 0x0000009da53ff620  RDX:   0x000001c4ba73a120
RIP:    0x00007ffb60bc27c8  RBP: 0x0000000000000000  SegCs: 0x000001c400000033
EFlags: 0x0000000000010287  RSP: 0x0000009da53ff5b0  SegSs: 0x000001c40000002b
R8:     0x000001c4ba73a120  R9:  0x000001c495a4d040  R10:   0x0000000000000000
R11:    0x0000009da53ff938  R12: 0x0000000000000000  R13:   0x000001c53e6b6478
R14:    0x000001c50e9fa900  R15: 0x000001c4c5b7f790


Bytes at CS:EIP:
0f 10 07 be 0f 00 00 00 0f 11 01 eb 71 48 b9 ff 

Mono DLL loaded successfully at 'C:\CustomApps\UnityEngine\2020.3.11f1\Editor\Data\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll'.


Stack Trace of Crashed Thread 14076:
0x00007FFB60BC27C8 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_FirebaseAnalytics
0x00007FFB60D86EF6 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D95C06 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D89DDC (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D8F999 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D0CEB1 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D0E329 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D97FA2 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D96845 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60D979EA (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60EC2707 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60EC3E2A (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60C7EAD5 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB60C2D338 (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFB6107849D (FirebaseCppApp-8_0_0) SWIGRegisterStringCallback_StorageInternal
0x00007FFBE0617034 (KERNEL32) BaseThreadInitThunk
0x00007FFBE07C2651 (ntdll) RtlUserThreadStart

**Comment by gputhread** [comment]
[https://www.audiokinetic.com/qa/7910/wwise-unity-aksoundengine-caused-access-violation-0xc0000005](url)

Will this work?
My Windows is windows to go, Windows Pro On External HDD

**Comment by gputhread** [comment]
I moved my project to c drive, maybe  access violation(with unity crash popup) gone but
There is still a random silent crash(without any crash popup) with heavy use of auth and database i will see if i get ref for you on how to reproduce
