### ISSUE TITLE
Firebase RealTime Database sometimes return some incorrect data

### ISSUE THREAD

**Issue by jiyeershi** [firebase/quickstart-unity#1060]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2018.4.28f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: FirebaseDatabase.unitypackage 
  * Problematic Firebase Component: Database
  * Other Firebase Components in use:  Auth, Database, Storage, RemoteConfig
  * Additional SDKs you are using: Facebook, AdMob
  * Platform you are using the Unity editor on:  Windows
  * Platform you are targeting:iOS, Android
  * Scripting Runtime:  IL2CPP)

### [REQUIRED] Please describe the question here:
I am using firebase database to save and sync users data.
Recently, i have found the user data i get using database Api 'GetValueAsync' is not right with data shown in database console,
it seems to be some old data in someday before.
To be stranged, this situation not occurs everytimes i get user data, most of time, it's a right data same with database console.
What happened with my firebase database, does it return some cache data to me?

**Comment by jiyeershi** [comment]
Hi @paulinon 

As far as i know, event listeners is use for this scenary, in which some value changes for key can be notified to my client
And i'm also using this feature for my app to listen the value change of 'device' key in database to identify which device have been bind to this remote data at this moment.

And now, at the time of my app start i have been using 'FirebaseDatabase.DefaultInstance.GetReference(userBasePath).GetValueAsync().ContinueWithOnMainThread(task => {})' for a one call to download all data of current user and compare this downloaded data with local, if they are not same, i will show the difference in UI for current user to let he/she decide which data does he/she want. And all data of _user_ is only retrieved one time during each my app running. It's just convenience for someone who changed her/his device to contine his/her progress  by fetch and apply all his userdata at time of app startup.

May be i can use event listener to listen my 'userBasePath' path in remote to get all data of user once my app startup, but i still worry about the value is same or not everytime i get from remote when actually the remote data has no changes at all. Because for now, most of time the downloaded value is same with remote value and sometimes they are different, when remote data has no changes at all. On the other hand, i had never been found this problem until recently since my app published 2 years ago, so i can also hardly comfirm if or not this problem can be solved absolutely by this method. 

here is my code:
![5](https://user-images.githubusercontent.com/5441832/119784370-b60ad300-bf00-11eb-9c7b-a4c650daf5fb.png)

**Comment by paulinon** [comment]
Hi @jiyeershi,

I noticed that you're using an old version of the SDK. Could you try if version 7.2.0 makes any difference? If not, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that we can isolate what's causing this behavior.
