### ISSUE TITLE
[Bug] Issue getting FCM token on app start

### ISSUE THREAD

**Issue by Flaurenss** [firebase/quickstart-unity#1063]
### [REQUIRED] Please fill in the following fields:

* Unity editor version: 2018.4.10f
* Firebase Unity SDK version: 5.7.0
* Source you installed the SDK: .unitypackage
* Problematic Firebase Component: Not really sure, probably the Messaging package.
* Other Firebase Components in use: Auth, Database, Storage,
* Additional SDKs you are using: I was using EasyMobile. But I tried to use the default methods from the Messaging package and I'm still getting the same issue.
* Platform you are using the Unity editor on: Mac
* Platform you are targeting: iOS v 12.5.3
* Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I have an application that uses the messaging package. Every time that the app is executed the OnTokenReceived function is executed, I get the token and I send it to the real-time database (and so for every user).  Normally I receive with no issues the notifications, with the app closed, foreground, and background. But trying the app with the previous named iOS version, once I start the application by clicking on a notification the next notification prompts this error in the Firebase console:

 { code: 'messaging/registration-token-not-registered', message: 'Requested entity was not found.' }

Is that a normal issue? I follow some similar issues regarding the registration-token-not-registred, but what I don't understand is the fact that every time I launch the app I'm receiving always the same token.  I would understand that for any reason the APNS has unregistered the token and then once I launch the app I would receive a new fresh token, but it's not the case.
(and from that moment I don't receive any notification anymore).

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I haven't been able to reproduce this issue on the quickstart due to the case that it's a work project. And I don't actually have time enough to focus on a sample project.

What happened? How can we make the problem occur?
I attach an image of the functions register:
![issueAPNS](https://user-images.githubusercontent.com/42294298/120226300-399d2a80-c247-11eb-9a3d-3e6b3b40118e.png)
Please write me any doubts that you have related to the issue I will try to respond to everyone taking into account that I signed an NDA.

**Comment by paulinon** [comment]
Hi @Flaurenss,

I noticed that you're using an old version of the SDK. Could you try using version 7.2.0 and see if this makes any difference? If this didn't fix the issue, please provide relevant code along with the detailed steps you've taken before facing the issue so that the cause of this behavior could be identified.

**Comment by Flaurenss** [comment]
> 
> 
> Hi @Flaurenss,
> 
> I noticed that you're using an old version of the SDK. Could you try using version 7.2.0 and see if this makes any difference? If this didn't fix the issue, please provide relevant code along with the detailed steps you've taken before facing the issue so that the cause of this behavior could be identified.

@paulinon what would be the best approach in order to update de SDK, delete all the files related the old version? Or just import the package related to 7.2.0? May I asume that I should also update Auth, Database and Storage packages?

**Comment by paulinon** [comment]
Hi @Flaurenss,

You can simply import version 7.2.0 of the SDK. Take note that this applies to all Firebase products as well.

Let me know of it goes.

**Comment by alexames** [comment]
That error code can be found here:

https://firebase.google.com/docs/cloud-messaging/send-message#admin_sdk_error_reference

> **messaging/registration-token-not-registered**
> 
> The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons, including:
> 
>   - The client app unregistered itself from FCM.
>   - The client app was automatically unregistered. This can happen if the user uninstalls the application or, on iOS, if the APNs Feedback Service reported the APNs token as invalid.
>   - The registration token expired. For example, Google might decide to refresh registration tokens or the APNs token may have expired for iOS devices.
>   - The client app was updated, but the new version is not configured to receive messages.
> 
> For all these cases, remove this registration token and stop using it to send messages.

Without knowing more about your specific case it's hard to tell why this may have happened.
