### ISSUE TITLE
[Bug] RemoteConfig.ConfigSettings.MinimumFetchInternalInMilliseconds does not work on iOS and desktop

### ISSUE THREAD

**Issue by steve6t6** [firebase/quickstart-unity#1067]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.4f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Auth, Database, Crashlytics, Storage, Functions
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android.
  * Scripting Runtime: (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

During setup of Remote config we set the settings value MinimumFetchInternalInMilliseconds using:
`var configSettings = new ConfigSettings();
  configSettings.MinimumFetchInternalInMilliseconds = (2*60*1000); // 2 Minutes`
and `Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.SetConfigSettingsAsync(configSettings).ContinueWithOnMainThread()`
The issue we are encountering is that on iOS and in Editor this interval is ignored, but it works as expected on Android. 

#### Steps to reproduce:

1 ) After Firebase dependancy state == available we create and set a ConfigSettings object using SetConfigSettingsAsync.
2) On main thread after SetConfigSettingsAsync, we define and set our default values using SetDefaultsAsync.
3) On main thread after SetDefaultsAsync, we print out the value `Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.ConfigSettings.MinimumFetchInternalInMilliseconds` and confirm it is now the same as the value we set. 
4) We wait 5 seconds with a Unity co-routine. (For testing purposes)
5) We pull the remote config values using FetchAndActivateAsync.
6) On main thread, we confirm success, then interrogate the RemoteConfig Info object and note a last fetch date time of several hours ago, noting that we set the interval to 2 minutes.

All values can be accessed and report a source Enum of 1 (RemoteValue). We reduce the MinimumFetchInternalInMilliseconds to 1 and tested on iOS and in the editor, but we always get the cached values from an earlier pull from hours ago (According to Info.FetchTime).

**Comment by paulinon** [comment]
Hi @steve6t6,

Could you provide a sample code along with the detailed steps you've taken before facing this issue? This way, we can identify the possible cause of this behavior.

Thanks!

**Comment by steve6t6** [comment]
These test solutions assume that Firebase has passed the Fix dependancies step.

Test One, using a ConfigSettings with 2 minutes in milliseconds and FetchAndActivateAsync:
```
public void FetchTestOne()
    {
        Debug.Log("Fetching remote config, this test uses a ConfigSettings object and FetchAndActivate method");
        ConfigSettings cSet = new ConfigSettings();
        cSet.MinimumFetchInternalInMilliseconds = (2*60*1000); 
        Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.SetConfigSettingsAsync(cSet).ContinueWithOnMainThread(task =>
        {
            Debug.Log($"Setting set, MinimumFetchInternalInMilliseconds = {Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.ConfigSettings.MinimumFetchInternalInMilliseconds}");
            Dictionary<string,object> _defaults = new Dictionary<string, object>();
            _defaults.Add("app_min_version", "0.0.1");

            Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.SetDefaultsAsync(_defaults).ContinueWithOnMainThread(setTask =>
            {
                Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.FetchAndActivateAsync().ContinueWithOnMainThread(fetchTask =>
                {
                    PrintConfigState();
                });
            });
        });
    }
```

Function 2, using just FetchAsync with a 2 minute time span and then activating afterwards:
```
public void FetchTestTwo()
    {
        Debug.Log("Fetching remote config, this test uses Fetch with a timespan method");
 
        Dictionary<string,object> _defaults = new Dictionary<string, object>();
        _defaults.Add("app_min_version", "0.0.1");

        Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.SetDefaultsAsync(_defaults).ContinueWithOnMainThread(setTask =>
        {
            Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.FetchAsync(TimeSpan.FromMinutes(2)).ContinueWithOnMainThread(fetchTask =>
            {
                Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.ActivateAsync().ContinueWithOnMainThread(faccTask =>
                {
                    PrintConfigState();
                });
            });
        });
    }
```

And a print method for details:
```
private void PrintConfigState()
    {
        var info = Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.Info;
        switch (info.LastFetchStatus) 
        {
            case Firebase.RemoteConfig.LastFetchStatus.Success:
                Debug.Log(String.Format("Remote data loaded and ready (last fetch time {0}).",info.FetchTime));
            break;
            case Firebase.RemoteConfig.LastFetchStatus.Failure:
                switch (info.LastFetchFailureReason) {
                    case Firebase.RemoteConfig.FetchFailureReason.Error:
                    Debug.LogError("Fetch failed for unknown reason");
                    break;
                    case Firebase.RemoteConfig.FetchFailureReason.Throttled:
                    Debug.LogError("Fetch throttled until " + info.ThrottledEndTime);
                    break;
                }
            break;
            case Firebase.RemoteConfig.LastFetchStatus.Pending:
                Debug.Log("Latest Fetch call still pending.");
            break;
        }

        Debug.Log(Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.GetValue("app_min_version").StringValue);
        Debug.Log($"app_min_version source = {Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.GetValue("app_min_version").Source}");
        
    }
```

Testing, I ran these methods on both Android (One plus 6) and an iPhone (iPhone 7) and the results are as follows:

(Android) Method one, pulls cached value within the 2 minutes, pulls new values after 2 minutes. (Expected behaviour)
(Android) Method two, always pulls latest values from remote. 
(iOS) Method one, never pulls the new values from the remote, even after the 2 minutes.
(iOS) Method two, always pulls latest values from remote. 

Conclusions:
FetchAsync(Timespan) never functions as expected on either platform.
FetchAndActivate() using a ConfigSettings with 2 seconds set, works only on Android but not iOS.

**Comment by paulinon** [comment]
Hi @steve6t6,

Before I try to reproduce this issue, could you provide the complete steps you've taken in the Firebase console as well?

**Comment by steve6t6** [comment]
> Hi @steve6t6,
> 
> Before I try to reproduce this issue, could you provide the complete steps you've taken in the Firebase console as well?

Hi @paulinon 
I have created a brand new project in Firebase just to test this issue.

--- CONSOLE ---
- Created the new project.
- Added App 'Android' to the project, got google-service and added it to Unity project.
- Added App 'iOS', got p-list and added it to Unity project.
- Added a guest account to Auth.
- Added a storage bucket (Not used, but part of our main development)
- Added Realtime Database (Not used, but part of our main development)
- Added Remote Config values, a variable named min_app_version and gave it an iOS and Android value condition.

--- UNITY ---
- Boot
- Resolve google services
- Show login / Subscribe to Auth changes.
- show simple UI to select which of the two approaches to try.
- Build to Android 
- Build to iOS

**Comment by paulinon** [comment]
Hi @steve6t6,

I've built the app for both platforms, and I haven't been successful in reproducing your issue so far. To be specific, both methods in both platforms return the remote value, and nothing significant appears in the logs after two minutes.

I noticed that you're using an old version of the Unity editor. Could you try updating it to its latest version (Unity 2020.3.11f1) and see if the issue persists? If so, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the debug logs for both platforms so that we can be on the same page with this issue.

**Comment by paulinon** [comment]
Hi @steve6t6,

You may upload your project to a private repository and add me as a collaborator. Let me know how it goes.

**Comment by steve6t6** [comment]
> Hi @steve6t6,
> 
> You may upload your project to a private repository and add me as a collaborator. Let me know how it goes.

Hello Paulonon,  have uploaded a project, but FirebaseCppApp-7_2_0.so had to be ignored due to size, also my management advised me to omit the google-services setup for security reasons, so you will need to setup a quick firebase project in console. I left some notes in the Readme file.

**Comment by chkuang-g** [comment]
So there are two parts of this issue

- On iOS, this seems to occur in iOS as well. https://github.com/firebase/firebase-ios-sdk/issues/7877. This will depends on the patch from iOS SDK. There is an internal bug for iOS SDK to track this issue: b/184929396
- For desktop implementation, I suspect this is just not implemented at all.

@cynthiajoan What do you think?

**Comment by cynthiajoan** [comment]
This feature is supported at desktop, but there's bug on if set the interval to 0 the fetch will not respect that. Made a fix to CPP SDK to address this issue.

**Comment by cynthiajoan** [comment]
Fix included in the next release
