### ISSUE TITLE
[Question] Authentication for private server

### ISSUE THREAD

**Issue by dacodelaac** [firebase/quickstart-unity#1068]
* Unity editor version: 2019.4.21f
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Auth
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

Hi all, I want to use Firebase auth service to login to my server by using login with some providers: Google Play Game, Facebook,... Here is how I do it:
1. Client signs in to Firebase auth with a provider, and receives a user info in FirebaseAuth.CurrentUser
2. Client request a token from Firebase and send it to my server. The server will verify the token then send result back to client.

Normally it works well. But if client want to log in to other provider, then fail at step 2, how to keep FirebaseAuth.CurrentUser back to the previous login time. I just want to show an error message, and current user info must be not changed.

Thank you

**Comment by paulinon** [comment]
Hi @dacodelaac,

Based on your description, you would like to implement a method where the client won't be able to log in if a value for FirebaseAuth.CurrentUser exists. Did I get that right?

Could you also provide a sample code for your current implementation so that we can identify other functions to be added?

Thanks.

**Comment by dacodelaac** [comment]
Hi @paulinon,

For example, the client logged in to Firebase (`account 1`) and then verified at my server successfully. Now, he logs in to another Firebase account `(account 2`) but failed to verify at my server, I want his Firebase account to stay as `account 1`, but actually, it is `account 2`. I don't want to force him to log out, just want to show an error message to him and he can try again later.

Or can you provide me a better way to implement authentication for my server with Firebase auth?

**Comment by paulinon** [comment]
Hi @dacodelaac 

You can get the current user from your default instance by using the following code:

`Firebase.Auth.FirebaseUser user = auth.CurrentUser;`

For your login providers, you can check if a value for this exists. If a user exists, the client doesn't get to proceed with the authentication process.

I'll be closing this for now. Should you have any other questions or clarifications about your implementation, you may get in touch with [Firebase Support](https://firebase.google.com/support).
