### ISSUE TITLE
[Question] Can Dynamic Links be set up using Unity Cloud?

### ISSUE THREAD

**Issue by NroL** [firebase/quickstart-unity#1074]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.15f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Dynamic Links 
  * Other Firebase Components in use: Auth, Analytics, Crashlytics, Database, Dynamic Links, Storage
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows 10 
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:
Hi, I use Unity Cloud to build my app for iOS.
I've tried implementing Dynamic Links for iOS & Android. Android works 100% fine. 
However, with the iOS app, the dynamic link always open the App Store page. 
I am not using a custom domain, so my link is in this format:  https://example.page.link/

I've looked up potential issues and realised it may be because I have not configured the iOS project capabilities to send invites and receive links using xCode on a Mac.

I have enabled Associated Domains capability on my app provisioning profiles within my Apple developer account.
However, I have **not** followed this last step from the quickstart-unity guide for Dynamic Links:

_________________
Configure the iOS project capabilities to send invites and receive links.

- Enable the Keychain Sharing capability on iOS 10 or above (required by Google Sign-In to send invites). You can enable this capability on your project in Xcode 8 by going to your project's settings, Capabilities, and turning on Keychain Sharing.
- Copy the domain URI prefix for your project under the Dynamic Links tab of the Firebase console Then, in your project's Capabilities tab:
    - Enable the Associated Domains capability.
    - Add applinks:YOUR_DYNAMIC_LINKS_DOMAIN For example "applinks:xyz.app.goo.gl".
_________________

To check whether I have my Firebase project properly configured, I go to this site:
https://example.page.link/apple-app-site-association    (replacing example with my actual link of course)

It shows something like:
{"applinks":{"apps":[],"details":[{"appID":"123456.com.example.ios","paths":["NOT /_/*","/*"]}]}}

I'm not sure if this means it is correctly configured, even though I skipped adding an applink using xCode (since I use Unity Cloud).

**So my question is, can Dynamic Links be set up using Unity Cloud?** 
Specifically, to add enable the "Associated Domains" capability and add my applinks.

I haven't really touched using advanced configs available in Unity Cloud, but would like to know this answer before I go down that rabbit hole.

Big fan of Firebase, have used other components with no issues, but I'm stamped at getting Dynamic Links to work for iOS built with Unity Cloud.

**Comment by vimanyu** [comment]
Hi,
Thanks for providing all the information in the ticket. A few questions to help us narrow down the issue since I am not sure how Unity Cloud builds handles any custom XCode project configuration (eg: adding Associate Domains)

- Have you tried building our dynamic links quickstart example locally (without Unity Cloud) and does iOS work there? This will answer if something in the latest release affected iOS dynamic links or if there is something specific in your project settings. 
- Have you tried building your Unity project locally? Export to an XCode project from Unity and perform the required modifications before building the app.
- Can you check the debug flow for your app and verify if it looks as expected? (Add `?d=1` at the end of your dynamic link in a web browser)

**Comment by NroL** [comment]
I don't normally build locally as I don't have a Mac, so I've been using Unity Cloud exclusively to build. 

I will borrow a Mac and test a local build over the next few days and report back.

**Comment by NroL** [comment]
Update - I haven't been able to get my hands on a Mac yet, but I did more testing on iOS. Dynamic Links seems to be working partly on iOS.

At the moment on iOS, the dynamic link works exactly 1 time after app install. 

This scenario A works:
- A user does not have the app installed. 
- User clicks on the dynamic link and is taken to the App Store page to install the app.
- User installs the app 
- User manually opens the app (pressing on the dynamic link again always take user to the App Store)
- Dynamic Link is received and works as intended.

This scenario B partly works:
- A user does not have the app installed. 
- User installs the app (not through a dynamic link)
- User clicks on the dynamic link
- User is taken to the App Store (instead of opening the app automatically)
- User manually opens the app
- Dynamic Link is received and works as intended.

This scenario C does not work at all:
- User already have the app installed and the app has been opened at least once before (either through dynamic link or not). 
- User clicks on the dynamic link (doesn't matter if app is opened in the background or not)
- User is always incorrectly taken to the App Store. (Existing app is never detected)
- User opens the app manually, dynamic link is never received.

A few things to note:
- Tried to use the dynamic link in both safari and chrome but same results
- Tested on iOS 14

**Comment by alexames** [comment]
Hi @NroL, 

This is a use case I'm not super familiar with, but I'll see if I can at least point you in the right direction. While looking around for a possible solution I found [this stackoverflow page](https://stackoverflow.com/questions/47233982/how-to-automatically-set-associated-domain-for-ios-app-using-unity) where someone was trying to set the associated domain capability without doing so directly from Xcode. Some of the people in the answers section look like they have code snippets that you could work into your project to get the capability set up as a post build step.

Let me know if this helps.
