### ISSUE TITLE
[Bug] Functions : Unity Editor crash when exiting play mode after calling a cloud function

### ISSUE THREAD

**Issue by Sov3rain** [firebase/quickstart-unity#1075]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.11.f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK:  .unitypackage
  * Problematic Firebase Component: Functions
  * Other Firebase Components in use: Auth
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

When exiting Editor play mode after calling a cloud function, Unity editor crash. There is no error message.

Here are my editor and error log files:
[Editor.log](https://github.com/firebase/quickstart-unity/files/6670415/Editor.log)
[error.log](https://github.com/firebase/quickstart-unity/files/6670417/error.log)

#### Steps to reproduce:

1. Start editor play mode.
2. Call your cloud function **ONCE** (if you call it multiple times, the crash don't occur).
3. Stop editor play mode.
4. Editor crash.

I can reproduce 100% of the time.

EDIT: I can not reproduce on macOS, so it seems to be Windows only.

#### Relevant Code:

```csharp
// CloudFunction.cs

public static FirebaseFunctions Functions
{
    get
    {
        if (_functions == null)
        {
            _functions = FirebaseFunctions.GetInstance(FirebaseApp.DefaultInstance, "europe-west1");
        }
        return _functions;
    }
}

private static FirebaseFunctions _functions;

public static void CanScan(
    Action<CanScanResponse> onSuccess,
    Action onError
)
{
    CanScanAsync().ContinueWithOnMainThread((task) =>
    {
        if (task.IsFaulted)
        {
            HandleError(task);
            onError();
        }
        else
        {
            var result = JsonUtility.FromJson<CanScanResponse>(task.Result);
            onSuccess(result);
        }
    });
}

private static Task<string> CanScanAsync()
{
    var function = Functions.GetHttpsCallable("canScan");

    return function.CallAsync().ContinueWithOnMainThread((task) =>
    {
        var result = (string)task.Result.Data;
        return result;
    });
}
```

```csharp
// MonoBehaviour.cs

private void CanScan()
{
    CloudFunctions.CanScan(
        onSuccess: (response) => { },
        onError: () => { }
    );
}
```

**Comment by paulinon** [comment]
Hi @Sov3rain,

Thanks for reporting this. Could you verify if this issue persists when using our quickstart?

**Comment by vimanyu** [comment]
Hi @Sov3rain,
As @paulinon  suggested, I just tried this on my end with the [functions quickstart unity example] and didn't see any errors there. Tested on Windows 10 and Unity 2020.3.1f1, firebase-unity-sdk v8.0.0.

Steps:
- Place a `google-services.json` file under 'Assets'
- Installed "Functions.unitypackage"
- Hit Play button in editor and stopped editor play. 

As far as I can see the function is being called once. 
Let us know if you are noticing the crash in the quickstart example too.

**Comment by Sov3rain** [comment]
Hi @vimanyu,

I'm currently using firebase SDK v7.2. I'll update my project with v8.0 and let your know.
I'll also try the quickstart example.

**Comment by Sov3rain** [comment]
Tried in my project with `Firebase Auth 8.0` and `Firebase Functions 8.0`. Same problem.

Here are the log files:
[Editor.log](https://github.com/firebase/quickstart-unity/files/6686010/Editor.log)
[error.log](https://github.com/firebase/quickstart-unity/files/6686011/error.log)

I'll try in the functions quickstart and let you know.
