### ISSUE TITLE
[Question] Is it possible to track user presence in RTDB?(Without Firestore)

### ISSUE THREAD

**Issue by MuhsinEge** [firebase/quickstart-unity#1076]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.26f
  * Firebase Unity SDK version: 7.0.0
  * Source you installed the SDK: Unity Package
  * Problematic Firebase Component: None for now. 
  * Other Firebase Components in use: Auth, Database, Cloud Functions, Analytics, Cloud Messaging
  * Additional SDKs you are using: Facebook, GameAnalytics
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Hi Everyone, 

We are building a real time turn based combat system with Firebase RTDB. Is there a way to store user presence on RTDB? I want Player1 to know if Player2 has left the game or lose connection? 

I have seen some examples with firestore but none with RTDB. 

Thanks!

**Comment by paulinon** [comment]
Hi @MuhsinEge,

The Firebase Unity SDK has an [onDisconnect](https://firebase.google.com/docs/reference/android/com/google/firebase/database/OnDisconnect) class that handles functions that will be running on the server when the client disconnects. With this, you can cancel any operation and even add or remove data to a database reference whenever a user is disconnected. That being said, I'll be closing this for now.
