### ISSUE TITLE
[Bug] Mapping.txt file will generate but it's empty

### ISSUE THREAD

**Issue by zeegfa** [firebase/quickstart-unity#1078]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2019.2.21f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth, Database, Functions, Messaging, Crashlytics, Analytics
  * Additional SDKs you are using: Facebook 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP 

### [REQUIRED] Please describe the issue here:

mapping file will generate but it's empty

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? 100% (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
After update from 6.16.0 to 7.2.0 and for APK build or AAB the mapping file will generate but it's empty

**Comment by DellaBitta** [comment]
Hi @zeegfa, 

could you describe your build configuration a bit more?  I started with a fresh quickstart project from this repo, and set `Project Settings` -> `Publish Settings` -> `Minify` to enable both `Release` and `Debug`.  Subsequent builds with either `Build` or `Build And Run` both produce a mapping file.

Thanks!
