### ISSUE TITLE
[Question] Crashlytics not working in some condition.

### ISSUE THREAD

**Issue by MayisGM** [firebase/quickstart-unity#1079]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.12f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Database, Storage, DynamicLinks, Analytics, Function, Messaging (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
Hello,
Crashlytics not reporting exceptions to Firebase Console, if I disable "Debug.unityLogger.logEnabled = false" in Awake method for release purposes. When "Debug.unityLogger.logEnabled = true" everything works well. Is this a bug or this is by design? I prefer to disable all unity logs before releasing my application, so it be more optimized and not fill memory with log garbage. I downloaded and tested with quickstart-unity sample the same issue I described.

**Comment by samedson** [comment]
Hey @MayisGM, this is due to how Unity handles unhandled exceptions. Crashlytics must listen to the Unity log for exceptions for them to be reported.

Crashlytics listens to the [logMessageReceived](https://docs.unity3d.com/ScriptReference/Application-logMessageReceived.html) callback, and reports when the [LogType is Exception](https://docs.unity3d.com/ScriptReference/LogType.html).

You may be able to get the desired behavior by setting the [LogLevel to Error](https://docs.unity3d.com/2021.1/Documentation/ScriptReference/PackageManager.LogLevel.html)

**Comment by MayisGM** [comment]
> Hey @MayisGM, this is due to how Unity handles unhandled exceptions. Crashlytics must listen to the Unity log for exceptions for them to be reported.
> 
> Crashlytics listens to the [logMessageReceived](https://docs.unity3d.com/ScriptReference/Application-logMessageReceived.html) callback, and reports when the [LogType is Exception](https://docs.unity3d.com/ScriptReference/LogType.html).
> 
> You may be able to get the desired behavior by setting the [LogLevel to Error](https://docs.unity3d.com/2021.1/Documentation/ScriptReference/PackageManager.LogLevel.html)

@samedson thank you for response. Will crashlytics record fatal crashes even I keep "Debug.unityLogger.logEnabled = false", or it will  listen logMessageReceived callback for fatal crashes too?

**Comment by paulinon** [comment]
Hi @MayisGM, 

Since Crashlytics is able to report fatal crashes from Unity (such as when using Unity-native code), it will still listen to the logMessageReceived callback for this instance.

I'll be closing this ticket for now. Let me know if you have any other questions.
