### ISSUE TITLE
FirebaseDatabase does not work with Unity 2017 .NET 4.6

### ISSUE THREAD

**Issue by ItsLeeOwen** [firebase/quickstart-unity#108]
Enabling .NET 4.6 Player runtime in Unity 2017 breaks the Firebase Unity SDK.  FirebaseDatabase transactions no longer successfully result in either an error or response object. 

To reproduce:

- download the latest 2017 beta
- enable the .NET 4.6 Player runtime
- clone & run the Firebase quickstart testapp
- try either the Parse/Plugins/Unity.tasks dll or Parse/Pugins/dotNet45/Unity.tasks dll
- run the project in the editor, enter an email and observe the transaction does not complete

More info:  https://forum.unity3d.com/threads/unity-2017-net-4-6-firebase-scripting-runtime-websocket-errors.476078/

**Comment by stewartmiles** [comment]
Hi @ItsLeeOwen in future it would be great to provide some context on the issue you're running into.  "does not work" isn't that useful.

Perhaps you're running into a similar issue to https://groups.google.com/forum/#!topic/firebase-talk/OMtbNrb9FEI ?  If so, see my response for the solution.

Cheers,
Stewart

**Comment by ItsLeeOwen** [comment]
@stewartmiles my apologies, I've updated.
