### ISSUE TITLE
[Bug]  FirebaseRemoteConfigurations crash 

### ISSUE THREAD

**Issue by Archi97** [firebase/quickstart-unity#1082]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.4
  * Firebase Unity SDK version: 7.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Remote Configurations (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics, Crashandler  (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob, Avpro, etc
  * Platform you are using the Unity editor on:  Windows
  * Platform you are targeting: iOS/Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I have updated my app. and now getting some crashes connected with Remote config.
here is the stack trace.
Is it something that I did wrong?

Non-fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
at FirebaseRemoteConfigurations+d__11.MoveNext(FirebaseRemoteConfigurations+d__11)
at System.Threading.ContextCallback.Invoke(System.Threading.ContextCallback)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run(System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner)
at System.Action.Invoke(System.Action)
at System.Threading.ThreadPoolWorkQueue.Dispatch(System.Threading.ThreadPoolWorkQueue)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
at System.Threading.WaitCallback.Invoke(System.Threading.WaitCallback)
at System.Threading.ContextCallback.Invoke(System.Threading.ContextCallback)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext)
at System.Threading.ThreadPoolWorkQueue.Dispatch(System.Threading.ThreadPoolWorkQueue)

#### Steps to reproduce:

Have no idea how to reproduce. I have published app for 10% of my user, got crashes from them.  Never got problem on local test.

**Comment by paulinon** [comment]
Hi @Archi97,

Could you try if updating to version 8.0.0 of the SDK resolves the issue? If not, I'd like you to confirm if this behavior also occurs using the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/remote_config/testapp).

**Comment by Archi97** [comment]
> Hi @Archi97,
> 
> Could you try if updating to version 8.0.0 of the SDK resolves the issue? If not, I'd like you to confirm if this behavior also occurs using the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/remote_config/testapp).

Nope.  with latest version of Firebase SDK still getting issues. 

now also this kind of 

Non-fatal Exception: java.lang.Exception: FirebaseException : 
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
       at FirebaseRemoteConfigurations+<RemoteConfig>d__11.MoveNext(FirebaseRemoteConfigurations+<RemoteConfig>d__11)
       at System.Threading.ContextCallback.Invoke(System.Threading.ContextCallback)
       at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext)
       at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext)
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run(System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner)
       at System.Action.Invoke(System.Action)
       at System.Threading.ThreadPoolWorkQueue.Dispatch(System.Threading.ThreadPoolWorkQueue)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(System.Runtime.ExceptionServices.ExceptionDispatchInfo)
       at System.Threading.WaitCallback.Invoke(System.Threading.WaitCallback)
       at System.Threading.ContextCallback.Invoke(System.Threading.ContextCallback)
       at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext)
       at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem(System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem)
       at System.Threading.ThreadPoolWorkQueue.Dispatch(System.Threading.ThreadPoolWorkQueue)

**Comment by paulinon** [comment]
Hi @Archi97,

In order to identify the cause of this behavior and hopefully find a solution, I would like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps you've taken before facing the issue.

**Comment by Archi97** [comment]
> Hi @Archi97,
> 
> In order to identify the cause of this behavior and hopefully find a solution, I would like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the steps you've taken before facing the issue.

Well. as i said before. im getting this stacktrace from Firebase. it happens for my users. 
For me it it not happening. I have tested 5-6 local devices, and also 10-20 devices with test lab. all clear.

**Comment by cynthiajoan** [comment]
Hi @Archi97,

Can you provide the code piece examples of how you use Firebase and Remote Config? The keyword FirebaseRemoteConfigurations is unfamiliar to me, is that your wrapper class? Thanks!

**Comment by Archi97** [comment]
Hi @cynthiajoan 
Here is the scripts that I'm using.

FirebaseAppInitializer.cs is on GameObject which is on start Scene
FirebaseRemoteConfigurations.cs has static function that is called form previous script. 

These was worked perfectly on Unity 2018.4.23, with Firebase 7.0.  After updating to Unity 2020.3.4 i have got the non-fatal(crashes) on Firebase Console from the users. 
 
![Firebase](https://user-images.githubusercontent.com/36793459/124231004-caa24280-db20-11eb-8778-d9637e3d14f2.png)

**Comment by alexames** [comment]
Hi @Archi97 

I have a suspicion of what might be happening. It's possible that some of your users, for whatever reason (e.g. bad connection), and are failing to fetch the data. You shouldn't call `ActivateAsync` unless the fetch was successful, so before doing so you should throw in a check to verify that it went through.

[Here's an example in our quickstart app](https://github.com/firebase/quickstart-unity/blob/master/remote_config/testapp/Assets/Firebase/Sample/RemoteConfig/UIHandler.cs#L142) where we do just that. 

```
switch (info.LastFetchStatus) {
  case Firebase.RemoteConfig.LastFetchStatus.Success:
    Firebase.RemoteConfig.FirebaseRemoteConfig.DefaultInstance.ActivateAsync()
    .ContinueWithOnMainThread(task => {
      DebugLog(String.Format("Remote data loaded and ready (last fetch time {0}).",
                           info.FetchTime));
    });

    break;
  case Firebase.RemoteConfig.LastFetchStatus.Failure:
    switch (info.LastFetchFailureReason) {
      case Firebase.RemoteConfig.FetchFailureReason.Error:
        DebugLog("Fetch failed for unknown reason");
        break;
      case Firebase.RemoteConfig.FetchFailureReason.Throttled:
        DebugLog("Fetch throttled until " + info.ThrottledEndTime);
        break;
    }
    break;
  case Firebase.RemoteConfig.LastFetchStatus.Pending:
    DebugLog("Latest Fetch call still pending.");
    break;
}
```

Try adding a similar block of code to your app and see if that resolves the issue.

**Comment by Archi97** [comment]
@alexames  Hi. sorry for late response. 
Yes it was slow connection. When i tested the new release, i was connected to the farest wifi,  and the issue happened to me as well.
i will take a look at your code and will find some way to no let user inside app, if the fetching is not complete :D

**Comment by Archi97** [comment]
@alexames  how is this possible. 
Im removing code from line 23 to 34, but remote params still working.

**Comment by Archi97** [comment]
Yes it keeps values in cache.  I guess it is kind of optimization. Like if fetch data 1st time, but didn't second time, then it will use old fetched data.  but i think it should use default, isn't it?

**Comment by Archi97** [comment]
How can I clean cache for remote config values? 
I want my default values if fetching was not successful.  But currently sdk uses values from cache(values from previous fetch)

**Comment by chkuang-g** [comment]
@Archi97 
One quick way to clear cache is to uninstall the app and reinstall it.

I do not recall any Unity API to clear the cache. Well, I just noticed that there is a missing API in C++/Unity/iOS SDK to reset the value, which is provided by [Android SDK](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#public-taskvoid-reset). So...uninstall and reinstall is the way to clear cache.

Let us know if @alexames's suggestion works for you.

**Comment by Archi97** [comment]
> @Archi97
> One quick way to clear cache is to uninstall the app and reinstall it.
> 
> I do not recall any Unity API to clear the cache. Well, I just noticed that there is a missing API in C++/Unity/iOS SDK to reset the value, which is provided by [Android SDK](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#public-taskvoid-reset). So...uninstall and reinstall is the way to clear cache.
> 
> Let us know if @alexames's suggestion works for you.

Ok. So there is no way to clear Firebase cache only. Or Force to use default values and ignore cached ones?

Ok Will let you know.  But mostly it is right solution to check if data fetched or not before activating them.
What i currently want is to use default values if data not fetched, and to not use the last cached data.

**Comment by chkuang-g** [comment]
I think you can set [FirebaseRemoteConfig.DefaultCacheExpiration](https://firebase.google.com/docs/reference/unity/class/firebase/remote-config/firebase-remote-config#class_firebase_1_1_remote_config_1_1_firebase_remote_config_1a7cd1c5067fe16f01f5cc3afe98a785bc) to a shorter period of time.  I don't think there is any way to not using cache at all (which is what you want: use default if `FetchAsync` failed).

Let me ping the team and see if there is any way,

**Comment by chkuang-g** [comment]
Seems like there is no way to achieve the behavior you expect: `to use default values if data not fetched, and to not use the last cached data.` The current behavior is, if fetch failed
-  If the cache is not expired, use cache
- Otherwise, use default


I would recommend you to file a feature request for this, unless you like me to turn this issue into a FR.

Anyway, please let us if what @alexames suggested works for you :)

**Comment by Archi97** [comment]
> Seems like there is no way to achieve the behavior you expect: `to use default values if data not fetched, and to not use the last cached data.` The current behavior is, if fetch failed
> 
> * If the cache is not expired, use cache
> * Otherwise, use default
> 
> I would recommend you to file a feature request for the behavior you want. However, this will take sometime since we need to have all iOS, Android and C++/Unity team to implement this feature.
> 
> Anyway, please let us if what @alexames suggested works for you :)

Hi @chkuang-g 
1. I have tried to solve that caching issue in this way:   I'm not calling SetDefault function,  instead I'm assigning the value to my static variables. If last fetch is succeeded, only then im assigning new values to my variables.  What do you think, is this method good to use? 
2. About @alexames solution, i have changed my script and added that last fetch status check. After some test I got result that my issue is not happening when im activating fetched data(without checking statud). But instead the issue is happening on Fetching method when you have very slow connection. 
I will do more test to be sure about it. I guess try-catch will solve the issue for now(of course it is not best solution)

**Comment by Archi97** [comment]
@alexames @chkuang-g  I can confirm that the issue happening on Fetching thread when the internet is very, very slow. 
![Untitled](https://user-images.githubusercontent.com/36793459/127511960-b8cb65d0-8f78-49b3-b6fe-48d9df15e8be.png)

**Comment by DellaBitta** [comment]
Hi @Archi97,

A few of us have attempted to reproduce this but we haven't been able to.  I personally attempted to connect an Android phone to a wifi hotspot, and shut down the hotspot after starting the sync attempt.  I get an error returned but no crash (unforutnately ?).

Could you clarify, is the crash a thrown exception or does the app completely exit or become non responsive?

Thanks!

**Comment by Archi97** [comment]
Hi @DellaBitta . The issue is logging as non-fatal error. It is not crashing app. But when the error happening,  the fetching value comes zero or empty(something like that) 

e.g.   In my app I have this kind of logic ("local variable" always increasing).  When the error happens. the if state become always true, which means that fetched value is not correct. 
```
if( "local_variable" > "fetched_variable") 
{ "local_variable" = 0; 
///"do something"
}
```

**Comment by DellaBitta** [comment]
Hi @Archi97, 

I'm sorry to say that I still haven't been able to cause the exception that you've encountered, but not for lack of trying!  Can you give me some pointers as to how you're testing a weak network connection?  Starting a fetch operation and turning off the WIFI doesn't seem to be good enough on my end -- usually the fetch is over very quickly and/or I get the standard error without the exception. I attempted to run the test app on the fringe of my WIFI range hoping that there would be some network turbulence but I still cannot reproduce this.  

Thank you!
