### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by adityathoutam** [firebase/quickstart-unity#1084]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.13f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth 
  * Other Firebase Components in use: Auth, Database, Storage, Functions, Messaging etc
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android and iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:
Is there anyway to get proper error code from the verificationFailed callback while using VerifyPhoneNumber in PhoneAuth?

 verificationFailed: (error) => {
    // The verification code was not sent.
    // `error` contains a human readable explanation of the problem.
  },

Right now it is giving a human readable explanation like this

"The format of the phone number provided is incorrect. Please enter the phone number in a " +
                     "format that can be parsed into E164 format. E164 phone numbers are written in the format  " +
                     "[+][country code][subscriber number including area code] [ TOO_SHORT]"

I'm assuming TOO_SHORT is the error code, where can I find the other types of error codes, and is there anyway to just get TOO_SHORT instead of this whole "human readable explanation"?

**Comment by paulinon** [comment]
Hi @adityathoutam,

I found this [list of error codes](https://firebase.google.com/docs/reference/unity/namespace/firebase/auth#autherror) for Firebase Authentication in Unity. `TOO_SHORT` isn't part of the list, so it's possible that the explanation corresponds to another error code.

Should you have any other questions about this, you may reach out to [Firebase Support](https://firebase.google.com/support).

**Comment by adityathoutam** [comment]
@paulinon should I make this a feature request? It seems like an oversight, I couldn't find AuthError anywhere.

**Comment by paulinon** [comment]
Hi @adityathoutam,

You may file a feature request for retrieving the error code when verification fails.
