### ISSUE TITLE
[Question] Firebase is not detected when building the app in Android

### ISSUE THREAD

**Issue by dizcampeador** [firebase/quickstart-unity#1086]
* Unity editor version: 2019.4.21f1
  * Firebase Unity SDK version: 26.1.1
  * Source you installed the SDK: Unity Hub
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: RealTime Database
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

Hello there! First of all, excuse me if I get any mistakes in my question, but it is my first time.

I have developed a videogame in Unity which connects with Firebase in order to get authenticated or to get some data from the RealTime Database.

In editor mode, when I start the game and when I build the app for Windows as target, all works perfectly. I can register new users, login and save/retrieve data from RealTime Database.

The problem is that when I build the videogame for Android, my variable **auth** is null. 

This is how I initialize Firebase and get my **auth** variable:

```
public Firebase.DependencyStatus dependencyStatus;
public Firebase.Auth.FirebaseAuth auth;
 public Firebase.Database.DatabaseReference DBReference;

void Awake() 
{
  Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
          {
              dependencyStatus = task.Result;
              if (dependencyStatus == Firebase.DependencyStatus.Available)
              {
                  // If available, initialize Firebase
                  InitializeFirebase();
              }
              else
              {
                  Debug.LogError("Could not resolve all Firebase dependencies: " + dependencyStatus);
              }
          });
}
private void InitializeFirebase()
    {
        Debug.Log("Setting up Firebase Auth");
        // Set the authentication instance object
        auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
        DBReference = Firebase.Database.FirebaseDatabase.DefaultInstance.RootReference;
    }
```

I read that you have to write the complete dependency, because Android has problem resolving them.

The Awake function works fine, and it gets to InitializeFirebase function, but is then when the **auth** variable is null.

These are my Build Settings:
![android build settings](https://user-images.githubusercontent.com/86913860/124383311-1d6c2d80-dccc-11eb-9a02-99cc02e2ee65.PNG)

These are my Player Settings -> Other Settings:
![settings](https://user-images.githubusercontent.com/86913860/124383346-4c829f00-dccc-11eb-9e53-03a54c6f754e.PNG)

These are the Publishing Settings, where I put my keystore:
![keystore](https://user-images.githubusercontent.com/86913860/124383379-6de38b00-dccc-11eb-87ef-3ef9723e86b5.PNG)

I created the keystore using the Keystore Manager, and then I used the command `keytool -list -v -keystore "C:\Users\happy\Documents\PFG Data\user.keystore"`

Then I copied the SHA-1 code in Firebase, as you can see here:
![sha](https://user-images.githubusercontent.com/86913860/124383493-08dc6500-dccd-11eb-91ae-873cc00f42b7.png)

And when I install the app via APK it's not working. I debugged the APK with the tablet connected to my PC, and I realized that the auth variable was null.

**Comment by paulinon** [comment]
Hi @dizcampeador,

In order to identify the cause of your issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the [debug logs](https://answers.unity.com/questions/1368808/how-to-see-debuglog-when-using-android.html) when your app is running?

**Comment by dizcampeador** [comment]
> 
> 
> Hi @dizcampeador,
> 
> In order to identify the cause of your issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the [debug logs](https://answers.unity.com/questions/1368808/how-to-see-debuglog-when-using-android.html) when your app is running?

Hello! I don't know how to create a reproducible example, since the code works in Editor but not in my tablet. The only log I receive when I click the login button to do the Login function is that the **auth** variable is null... If I can do anything more for giving you more info I will do it, but I don't know how to provide you more info...

**Comment by paulinon** [comment]
Hi @dizcampeador,

It's possible that your implementation may work on the editor but not on my device on my end. With that you may upload using a private repository and invite me as a collaborator. If you're unable to create a minimal, reproducible example, you may provide the debug logs along with the complete steps you've taken before facing the issue.
