### ISSUE TITLE
[Bug][Desktop] Unable to load Firebase app options 

### ISSUE THREAD

**Issue by Remzicik11** [firebase/quickstart-unity#1089]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.0f5
  * Firebase Unity SDK version: lastest
  * Source you installed the SDK: FirebaseAuth.unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: none
  * Additional SDKs you are using: none 
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

i did everything i can to avoid an error called: "couldn't read app options"
i aleardy put the json file in assets folder but it is still not working what can do?

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
*yes
What's the issue repro rate? 
*100%

_What happened? How can we make the problem occur?
InitializationException:  Firebase app creation failed.
Firebase.FirebaseApp.CreateAndTrack (Firebase.FirebaseApp+CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/FirebaseApp.cs:597)
Firebase.FirebaseApp.Create () (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/FirebaseApp.cs:124)
Firebase.FirebaseApp.get_DefaultInstance () (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/FirebaseApp.cs:99)
Script.Start () (at Assets/Script.cs:10)

Unable to load Firebase app options ([C:/Users/RamizKöfte/Desktop/yey/Assets/StreamingAssets\google-services-desktop.json, C:/Users/RamizKöfte/Desktop/yey/Assets/StreamingAssets\google-services.json] are missing or malformed)
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.OO6FyxgDHk/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:95)
Firebase.LogUtil:LogMessage(LogLevel, String) (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/LogUtil.cs:69)
Firebase.LogUtil:LogMessageFromCallback(LogLevel, String) (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/LogUtil.cs:77)
Firebase.AppUtilPINVOKE:PollCallbacks()
Firebase.AppUtil:PollCallbacks() (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/AppUtil.cs:32)
Firebase.Platform.FirebaseAppUtils:PollCallbacks() (at Z:/tmp/tmp.AX0cecligL/firebase/app/client/unity/proxy/FirebaseAppUtils.cs:33)
Firebase.Platform.FirebaseHandler:Update() (at Z:/tmp/tmp.OO6FyxgDHk/firebase/app/client/unity/src/Unity/FirebaseHandler.cs:208)
Firebase.Platform.FirebaseMonoBehaviour:Update() (at Z:/tmp/tmp.OO6FyxgDHk/firebase/app/client/unity/src/Unity/FirebaseMonoBehaviour.cs:45)_

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```cs
public class Script : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        var yey = Firebase.FirebaseApp.DefaultInstance;
    }
}
```

![Ekran Alıntısı](https://user-images.githubusercontent.com/73258096/124743468-13416d80-df1e-11eb-9bee-ff3c24f4e7f2.PNG)

![Ekranw Alıntısı](https://user-images.githubusercontent.com/73258096/124743653-3a983a80-df1e-11eb-976f-e570b52d56dc.PNG)

![w](https://user-images.githubusercontent.com/73258096/124743766-58659f80-df1e-11eb-985e-fcf74460db4e.PNG)

**Comment by paulinon** [comment]
Hi @Remzicik11,

It appears that this issue is similar to #1069. With that, could you try if this [workaround](https://github.com/firebase/quickstart-unity/issues/1069#issuecomment-857266535) resolves your issue?
