### ISSUE TITLE
[Bug] Firebase Realtime Database - Setting Values Suddenly Extremely Slow

### ISSUE THREAD

**Issue by danielginovker** [firebase/quickstart-unity#1091]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.28f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth (not related)
  * Additional SDKs you are using: Unity packages (multiplayer, purchasing, notifications, etc) (not related)
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android, Desktop
  * Scripting Runtime: Mono, IL2CPP

### [REQUIRED] Please describe the issue here:

After weeks of using the Firebase Realtime Database with minimal issues on my Unity project, today with no changes to my code, I'm experiencing extremely long write, and sometimes read times on the database (up to 4-5 minutes for extremely basic calls).

The code looks something like this:

```
var newEntry = FirebaseDatabase.GetInstance("https://my-database-url.firebaseio.com/").RootReference.Child(path);

Debug.Log("Starting write..");
newEntry.SetRawJsonValueAsync(someJson).ContinueWith(task =>
{
    if (task.Exception != null || !task.IsCompleted)
    {
        Debug.LogError("Something went wrong adding data!");
        return;
    }
    Debug.Log("Upload success.");
}

```

The logs previously used to show
```
00:00 - Starting write..
00:00 - Upload success.
```

But today show something like

```
00:00 - Starting write..
07:32 - Upload success.
```

Some related information:

* The data being uploaded is <1 KB
* Half the time it will upload in ~0s as usual
* I'm using the Blaze plan
* Firebase Rules shows no Errors or Deny logs
* My entire Database is roughly 4MB

**Comment by danielginovker** [comment]
Possibly related -

Another bug I've noticed in the past is manually removing data in console.firebase.google.com sometimes keeps the data cached somewhere for up to ~12 hours, and read attempts in the Unity SDK will retrieve old data that no longer exists. However, I don't think it's related since these SetRawJsonValueAsync calls are all on unique paths.

**Comment by paulinon** [comment]
Hi @danielginovker,

Could you try if updating the SDK to its latest version (8.0.0) makes a difference? If not, please provide sample data so that I could try to identify what's causing this behavior.

Additionally, you may file a new ticket for the issue related to retrieving deleted data so that it can be addressed accordingly.

**Comment by danielginovker** [comment]
Sure thing, I'll do an update!

Before I update though, I noticed using the Monitor system from Google Cloud that although the data I was uploading was small (less than a KB), it was taking a long time because it was uploading something large:

![image](https://user-images.githubusercontent.com/76956873/125069728-17d46600-e085-11eb-890c-983a97f438fb.png)

**Comment by danielginovker** [comment]
Closing for now because I cannot upgrade to the latest version at this time
