### ISSUE TITLE
what exactly is google-services-desktop.json generated - is this relevant for ios and android builds?

### ISSUE THREAD

**Issue by shanukp** [firebase/quickstart-unity#1092]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _2020 LTS____
  * Firebase Unity SDK version: latest
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
what exactly is google-services-desktop.json generated - is this relevant for ios and android builds?

**Comment by paulinon** [comment]
Hi @shanukp,

In your Unity project, Firebase automatically generates a desktop Firebase config file (google-services-desktop.json), and it contains the Unity project ID that you entered in the Firebase console setup workflow. With this, you can simulate your Firebase app from the Unity editor.

I'll be closing this for now. Let me know if you have any other questions.
