### ISSUE TITLE
[Bug] Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules jetified-firebase-iid-20.0.1-runtime.jar (com.google.firebase:firebase-iid:20.0.1) and jetified-firebase-messaging-22.0.0-runtime.jar (com.google.firebase:firebase-messaging:22.0.0)

### ISSUE THREAD

**Issue by mikeypdev** [firebase/quickstart-unity#1093]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.6f1
  * Firebase Unity SDK version: 8.0.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: InstanceID
  * Other Firebase Components in use: Analytics, Auth, Crashlytics, Database, DynamicLinks, Functions, Messagin, RemoteConfig, Storage
  * Additional SDKs you are using: Unity IAP
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android, iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Firebase Instance ID is deprecated, and I was not using it, so I removed the Instance ID SDK from my project when updating to SDK 8.0.0. In SDK 7.2.0, Instance ID implemented firebase-iid:21.1.0 on Android, as seen in mainTemplate.gradle. After removing Instance ID, and upgrading all other Firebase components to 8.0.0, there are no references to firebase-iid in mainTemplate.gradle or AndroidResolverDependecies.xml, as expected.

However, when building to Android, the gradle build fails with the following error:
` Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules jetified-firebase-iid-20.0.1-runtime.jar (com.google.firebase:firebase-iid:20.0.1) and jetified-firebase-messaging-22.0.0-runtime.jar (com.google.firebase:firebase-messaging:22.0.0)
`
I do not know where the reference to firebase-iid:20.0.1 is coming from.

As a workaround, I am able to solve the build error by manually adding a reference to firebase-iid:21.1.0 to my mainTemplate.gradle file:
`
implementation 'com.google.firebase:firebase-iid:21.1.0'
`

This is reproducible 100% of the time in my project, on two different development systems. I have not yet had the bandwidth to repro in any Quickstart example.

**Comment by paulinon** [comment]
Hi @mikeypdev,

This seems like a bug related to the dependencies. Could you provide the complete steps you've taken before facing this issue so that we can confirm this?

**Comment by mikeypdev** [comment]
Before updating to 8.0.0, I updated from 7.1.0 to 7.2.0 (this was 2 months ago). In the process of updating from 7.1.0 to 7.2.0, I removed the deprecated Google Game Package Registry from UPM, and migrated to local tgz files. I did the upgrade entirely outside of Unity, by manually adding a project-level GooglePackages folder containing the Firebase 7.2.0 and EDM tgz files and then updating Packages/manifest.json to remove the scopedRegistries entry for Google Game Package Repository, and update each Firebase SDK entry to point to the new local tgz files.

I seem to recall trying to remove the InstanceID SDK at the time, and getting some errors. I'm afraid I don't remember the issue, as I decided it was easier to leave the SDK in place. I was able to move forward without further issues.

In the process of updating from 7.2.0 to 8.0.0, I replaced the Firebase and EDM tgz files and manually updated Packages/manifest.json. I then encountered the Instance ID conflict when building for Android. I did not see any conflict or errors for Desktop or iOS builds. At this point, I was not using a custom gradle file for Android builds, so I enabled it in my project settings and EDM settings, and was then able to implement the workaround I noted above.

**Comment by paulinon** [comment]
Hi @mikeypdev,

Could you try going to **Assets** > **External Dependency Manager** > **Android Resolver** > **Force Resolve** and see if the issue persists?

**Comment by visioncored** [comment]
I am also facing this issue after updating from 7.2.0 to 8.1.0. 

Tried doing _Force Resolve_ via **Assets > External Dependency Manager > Android Resolver > Force Resolve**, but the issue still persists. I realised there is a change in Android Resolver Dependencies xml file.

![image](https://user-images.githubusercontent.com/15306107/126676833-0282b84b-8cf9-41bd-8d40-c9bec0013959.png)
![image](https://user-images.githubusercontent.com/15306107/126676861-337cbe19-87d3-4a2b-88ba-2f728370a3cb.png)
![image](https://user-images.githubusercontent.com/15306107/126676923-d8cc27e3-9e5a-49ee-9242-46b9f8945cfc.png)

I had attached the two dependencies files, not sure if it helps.

[AndroidResolverDependenciesOld.txt](https://github.com/firebase/quickstart-unity/files/6863914/AndroidResolverDependenciesOld.txt)

[AndroidResolverDependenciesNew.txt](https://github.com/firebase/quickstart-unity/files/6863917/AndroidResolverDependenciesNew.txt)

**Comment by thsbrown** [comment]
Also facing this issue. Also, @paulinon tried Force resolving with no fix. Seems like another case of dependency hell with firebase & unity 😭

**Comment by DanielWaiguru91** [comment]
Having the same issue over here in my android kotlin project, I haven't even implemented the FirebaseMessagingService, just adding the deps and my project cannot run or build

**Comment by mikeypdev** [comment]
@paulinon I can confirm that Force Resolve does not fix the issue for me. The workaround that I noted above is still required.

**Comment by paulinon** [comment]
Hi @mikeypdev,

I haven't been able to reproduce your issue on my end so far. Could you try to make use of the quickstart and see if the issue persists there?

**Comment by AhmadouDiarra** [comment]
Hi all, I'm having the same problem. The only thing I did is upgrading Firebase (Analytics, Auth, Firestore) from 7.0.2 to 8.1.0 and add (database, functions, messaging, storage) at 8.1.0. It's been days I'm looking for fix

**Comment by thsbrown** [comment]
I think this has something to do with EDM4U use Gradle setting. If I turn
it that on, I get issues, however if I leave settings at default and then
re add all packages the issue no longer persists.

**Comment by adityazvky** [comment]
Upgrading from 7.2.0 to 8.1.0. Got the same issue

**Comment by adityathoutam** [comment]
Upgrading from 7.2.0 to 8.1.0. Got the same issue

**Comment by Jack37** [comment]
I can reproduce this in a blank project just with the Firebase Functions and Firebase Messaging installed.

Unity version: 2020.3.15f1
External Dependency Manager version: 1.2.166
Firebase SDKs installed: Functions, Messaging (8.1.0, dotnet4)
MultiDex enabled, building on Android using Mono

Gradle error:
```
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzb found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzc found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzd found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zze found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzf found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzh found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzm found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzo found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzp found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzq found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzr found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.android.gms.internal.firebase_messaging.zzs found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
  Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules com.google.firebase.firebase-iid-20.0.1-runtime.jar (:com.google.firebase.firebase-iid-20.0.1:) and com.google.firebase.firebase-messaging-22.0.0-runtime.jar (:com.google.firebase.firebase-messaging-22.0.0:)
```

**Comment by kashif789us** [comment]
This was introduced in version 8.0.0 and I am amazed Firebase released 8.1.0 without fixing it. It only gets produced when you are using Messaging SDK.

**Comment by kashif789us** [comment]
> ### [REQUIRED] Please fill in the following fields:
> 
>     * Unity editor version: 2020.3.6f1
> 
>     * Firebase Unity SDK version: 8.0.0
> 
>     * Source you installed the SDK: Unity Package Manager
> 
>     * Problematic Firebase Component: InstanceID
> 
>     * Other Firebase Components in use: Analytics, Auth, Crashlytics, Database, DynamicLinks, Functions, Messagin, RemoteConfig, Storage
> 
>     * Additional SDKs you are using: Unity IAP
> 
>     * Platform you are using the Unity editor on: Mac
> 
>     * Platform you are targeting: Android, iOS
> 
>     * Scripting Runtime: IL2CPP
> 
> 
> ### [REQUIRED] Please describe the issue here:
> 
> Firebase Instance ID is deprecated, and I was not using it, so I removed the Instance ID SDK from my project when updating to SDK 8.0.0. In SDK 7.2.0, Instance ID implemented firebase-iid:21.1.0 on Android, as seen in mainTemplate.gradle. After removing Instance ID, and upgrading all other Firebase components to 8.0.0, there are no references to firebase-iid in mainTemplate.gradle or AndroidResolverDependecies.xml, as expected.
> 
> However, when building to Android, the gradle build fails with the following error:
> `Duplicate class com.google.android.gms.internal.firebase_messaging.zza found in modules jetified-firebase-iid-20.0.1-runtime.jar (com.google.firebase:firebase-iid:20.0.1) and jetified-firebase-messaging-22.0.0-runtime.jar (com.google.firebase:firebase-messaging:22.0.0)`
> I do not know where the reference to firebase-iid:20.0.1 is coming from.
> 
> As a workaround, I am able to solve the build error by manually adding a reference to firebase-iid:21.1.0 to my mainTemplate.gradle file:
> `implementation 'com.google.firebase:firebase-iid:21.1.0'`
> 
> This is reproducible 100% of the time in my project, on two different development systems. I have not yet had the bandwidth to repro in any Quickstart example.

Workaround works. It would be better to include a dependency xml file in the project then force resolve it. It will auto add it to the mainTemplate.gradle.
[KTDependencies.xml.zip](https://github.com/firebase/quickstart-unity/files/6900953/KTDependencies.xml.zip)

**Comment by mikeypdev** [comment]
Replying in order to flip the Needs Info status. I have not yet had a chance to repro in the Quickstart project, but @Jack37 seems to have a simple repro case.

**Comment by licexicel** [comment]
Also facing this, same as  Jack37  above.
Pretty sure that was cause by Firebase Functions and Firebase Messaging coexist.
Happened when I try to add Firebase Functions to my current project with Messaging already exist.
Testing on Firebase SDKs:7.2.0 & 8.1.0, both happened.

Also reproduce under a blank project
Unity version: 2020.3.15f2
External Dependency Manager version: 1.2.166
Firebase SDKs installed: Functions, Messaging (8.1.0, dotnet4)
MultiDex enabled, building on Android using Mono

**Comment by DellaBitta** [comment]
Hi all,

We have a fix for this issue that should be in our next release `v.8.2.0`. 

In the meantime, if you would like try to use `8.0.0` or `8.1.0` then you can attempt to manually apply the fix locally. 

In `Assets/Firebase/Editor/MessagingDependencies.xml` add the following to the list of android packages:

```
<androidpackages>
 ...
   <androidPackage spec="com.google.firebase:firebase-iid:21.1.0"></androidPackage>
 ...
</androidpackages>
```

Then re-run the Android resolver.

Note that we have not thoroughly tested this with `8.0.0` or `8.1.0`, so it would be an experimental and unsupported local change.  Still, it should unblock you from using v8+.

I'm going to close this issue for now, but if you continue to encounter this problem after `8.2.0`'s release, then please reopen it so that we can investigate it further. Thank you!

**Comment by YongjinK** [comment]
> Hi all,
> 
> We have a fix for this issue that should be in our next release `v.8.2.0`.
> 
> In the meantime, if you would like try to use `8.0.0` or `8.1.0` then you can attempt to manually apply the fix locally.
> 
> In `Assets/Firebase/Editor/MessagingDependencies.xml` add the following to the list of android packages:
> 
> ```
> <androidpackages>
>  ...
>    <androidPackage spec="com.google.firebase:firebase-iid:21.1.0"></androidPackage>
>  ...
> </androidpackages>
> ```
> 
> Then re-run the Android resolver.
> 
> Note that we have not thoroughly tested this with `8.0.0` or `8.1.0`, so it would be an experimental and unsupported local change. Still, it should unblock you from using v8+.
> 
> I'm going to close this issue for now, but if you continue to encounter this problem after `8.2.0`'s release, then please reopen it so that we can investigate it further. Thank you!

With 8.0.0, this fix does not work. The resolver ignores MessagingDependencies.xml and adds firebase-iid:20.0.01 rather than 21.1.0. 

I cannot believe that the team didn't even try to build a blank Firebase project before world-wide public distribution. Firebase 8 should better be 8-alpha if things will keep going this way.
