### ISSUE TITLE
[Question] Using Firestore in Desktop (Windows) Builds

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1095]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.9f1
  * Firebase Unity SDK version: 8.0.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Auth, Crashlytics, RemoteConfig
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Desktop (Windows)
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

As far as I understand the documentation for Firestore, it is not possible to use the Unity Firestore SDK directly in a Windows desktop build, correct?

When yes, what would be the recommended approach for accessing a Firestore database on a desktop build made with Unity? Via REST, or something else?

And are there other hurdles with this, like the Auth SDK?

**Comment by schmidt-sebastian** [comment]
We don't officially support Unity for Windows. Our Windows support is mainly targeted to allow development using the Unity editor on Desktop, but not to build games that run on Windows.

Please follow the Readme in the firebase_unity_sdk distribution for instructions.
