### ISSUE TITLE
[Bug] DllNotFoundException: FirebaseCppApp-8_0_0   

### ISSUE THREAD

**Issue by kalikane** [firebase/quickstart-unity#1096]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: **2019.3.0f6**
  * Firebase Unity SDK version: **8.0.0**
  * Source you installed the SDK: __**unitypackage** ___ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: __**Auth**___ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: __Facebook__ InAppReview___InAppPurchase__GoogleSignIn (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: __**Windows**___ (Mac, Windows, or Linux)
  * Platform you are targeting: __**Android**___ (iOS, Android, and/or desktop)
  * Scripting Runtime: ___**Mono**__ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
I have imported the SDK firebase Auth 8.0.0 that I use to implement Google authentication. 
I build the app I click on my Google button for Authentication I get the error DllNotFoundException: FirebaseCppApp-8_0_0 
When I go to folder Firebase->Plugin->x86_84 I see the FirebaseCppApp-8_0_0.dll but I don't understand why I got **DllNotFoundException: FirebaseCppApp-8_0_0** 

![image](https://user-images.githubusercontent.com/35786793/125933671-33b1e3cb-a585-4a66-ad19-a55fcb831073.png)

**Comment by paulinon** [comment]
Hi @kalikane,

Could you try going to **Assets** > **External Dependency Manager** > **Android Resolver** > **Force Resolve** and see if the issue persists?
