### ISSUE TITLE
iOS will not send custom analytics events.

### ISSUE THREAD

**Issue by ginterpto** [firebase/quickstart-unity#1099]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.10f
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Messaging, RemoteConfig, Crashlytics, Dynamic Links, Database(Auth, Database, etc.)
  * Additional SDKs you are using: AppsFlyer (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS and Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Since the transition to the Unity SDK way of implementing firebase, we are not able to get any custom event from firebase on iOS. Custom events are working fine for Android, but will fail to show up in the console DebugView or the events tab even after 3 weeks. Again, android events are coming as expected, all events are defined in the console properly.

The issue started after the latest transition to the way Firebase for Unity is being integrated. Before that, Analytics events worked just fine for us (version 7.0.2).

Even after downgrading back to 7.0.2, custom analytics events are not being sent. Firebase built in event are being sent though, so we can see in the console events like first_open, session_start, user_engagement, screen_view. But nothing else will not reach.

We have attempted to send the event directly from the native app (the one unity is generating) via a bridge. Again, nothing gets sent.

Again, upgrading or downgrading all have the same result. Builtin events are sent, but custom events are not.

#### Steps to reproduce:

Just add the 7.2.0 package to your project and see if you get events from iOS.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Just add the 7.2.0 package to your project and see if you get events from iOS.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @ginterpto,

Could you try using version 8.0.0 of the SDK and see if this resolves the issue?

**Comment by ginterpto** [comment]
Did try that too, latest external build tools and all. This does not reproduces on the analytics example with the same sdk and unity version, all events are being send and registered in the console as expected (i used the same firebase project we use for our production app). What could be causing this?

**Comment by paulinon** [comment]
Hi @ginterpto,

In order to identify the cause of this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps needed to replicate the issue?

**Comment by ginterpto** [comment]
Hi, 
I will try to reproduce this in a clean project over the weekend.

**Comment by zkunsang** [comment]
I have same problem

- Unity editor version: 2020.3.2f1
- Firebase Unity SDK version: 8.1.0
- Source you installed the SDK: .unitypackage
- Problematic Firebase Component: Analytics
- Other Firebase Components in use: Auth, Message, Crashtalics
- Additional SDKs you are using: None
- Platform you are using the Unity editor on: Mac M1
- Platform you are targeting: iOS and Android
- Scripting Runtime: IL2CPP

Android Analytics shows custom events very well. story_start, story_end, banner_click like what I created custom_events.
But no custom_events on iOS device.  I spend enough time for three days but there's no custom_events on Firebase Dashboard.
It show only default events like  screen_view, user_engagement.

I don't make screen_view  events **className UnityDefaultViewController** but it collected automatically and it shows on Firebase Dashboard.
> 2021-07-27 12:56:14.637473+0900 MyApp[7337:5614666] 8.3.0 - [Firebase/Analytics][I-ACS023105] Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: screen_view (_vs), {
    ga_debug (_dbg) = 1;
    ga_event_origin (_o) = auto;
    ga_previous_class (_pc) = UnityDefaultViewController;
    ga_previous_id (_pi) = 2128142597798667993;
    ga_realtime (_r) = 1;
    ga_screen_class (_sc) = UnityDefaultViewController;
    ga_screen_id (_si) = 3272484657612831647;
}

Here's my c# code and it starts first after app run. I've tried many different ways changing parameters **FirebaseAnalytics.LogEvent** but it doesn't show on Firebase DebugView and Dashboard either. Only shows automatically  created screen_view events and user_engagement.

```cs
            var task = FirebaseApp.CheckDependenciesAsync();
            var dependencyStatus = task.Result;

            Debug.Log($"dependencyStatus - {dependencyStatus}");

            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                app = FirebaseApp.DefaultInstance;

                (new UnityEvent()).Invoke();

                FirebaseMessaging.TokenReceived += OnTokenReceived;
                FirebaseMessaging.MessageReceived += OnMessageReceived;
                FirebaseMessaging.SubscribeAsync("all");


                // FirebaseAnalytics.SetCurrentScreen("test", "hello");
                FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
                // FirebaseAnalytics.SetCurrentScreen("test", "hello2");
                FirebaseAnalytics.LogEvent("test");


            } else
            {
                Debug.LogError($"dependencyStatus - {dependencyStatus}");
            }
```
> 2021-07-27 12:56:14.830245+0900 MyApp[7337:5614664] 8.3.0 - [Firebase/Analytics][I-ACS023044] Successful upload. Got network response. Code, size: 204, -1
2021-07-27 12:56:14.832612+0900 MyApp[7337:5614666] 8.3.0 - [Firebase/Analytics][I-ACS002002] Measurement timer scheduled to fire in approx. (s): -1.790298938751221
2021-07-27 12:56:14.834944+0900 MyApp[7337:5614666] 8.3.0 - [Firebase/Analytics][I-ACS002003] Measurement timer canceled

`Measurement timer canceled` there's no events after that message.

**Comment by zkunsang** [comment]
I've also tried several version 7.0.0, 7.1.0, 8.1.0 but it still doesn't work. any one help?

**Comment by jordanmuraskin** [comment]
> I've also tried several version 7.0.0, 7.1.0, 8.1.0 but it still doesn't work. any one help?

I have the same issue. Works fine on Android builds but on iOS only the automatically collected events are sent. 

using Unity 202.2.11f1 with latest Firebase build 8.1.0
