### ISSUE TITLE
[Bug] Storage namespace missing when importing tgz file

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1101]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.9f1
  * Firebase Unity SDK version: 8.0.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Storage
  * Other Firebase Components in use: Auth, Firestore, Crashlytics, RemoteConfig
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Desktop (Windows)
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

After importing the Storage SDK through the Package Manager via tgz, the namespace is not available in Visual Studio. I already removed and added the SDK again, restarted Visual Studio and the Unity Editor, with no change.

Adding the unitypackage of the Storage SDK works correctly, so this seems to be an issue with the tgz file.

**Comment by paulinon** [comment]
Hi @Nyankoo,

Could you try updating your Unity editor and Firebase SDK to their latest versions (2020.3.15f1 for the editor and 8.1.0 for the SDK) and see if the issue persists? If it does, please provide the complete steps you've taken before facing this behavior so we can identify what's causing this.
