### ISSUE TITLE
[Bug] App crash when clicking notification Reopen #1070

### ISSUE THREAD

**Issue by adityathoutam** [firebase/quickstart-unity#1102]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.15f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: unitypackage 
  * Problematic Firebase Component: Messaging 
  * Other Firebase Components in use: Auth, Database, Storage etc 
  * Additional SDKs you are using: None 
  * Platform you are using the Unity editor on: Mac 
  * Platform you are targeting: Android 
  * Scripting Runtime: IL2CPP 

### [REQUIRED] Please describe the issue here:
When app is running, it will crash when user taps a push notification from the app in the notification tray. (When the app is not open, behaviour is normal: tapping a push notification will open the app).

Please refer issue 1070 for more details

Steps to reproduce
Open the app
Minimize it
Send a notification from Firebase Cloud Message
Tap on the notification
Notice that the app crashes if there's no BIND_JOB_SERVICE permission added.

Where in the documentation or in the release notes does it say to add android:permission="android.permission.BIND_JOB_SERVICE" android:exported="true"/> ?

Issue is reproducible in latest 8.1.0 SDK

**Comment by vimanyu** [comment]
Hi @adityathoutam,
Thank you for creating this ticket. We have updated the quickstart examples along with documentation for this.
https://firebase.google.com/docs/cloud-messaging/cpp/client
https://github.com/firebase/quickstart-cpp/pull/99
https://github.com/firebase/quickstart-unity/pull/1113
