### ISSUE TITLE
[Question] iOS build does not send analytics events

### ISSUE THREAD

**Issue by equizo** [firebase/quickstart-unity#1110]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version 2018.4.28
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: _Analytics
  * Other Firebase Components in use: –
  * Additional SDKs you are using: IronSource, Adjust
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP)

### [REQUIRED] Please describe the question here:
ios Build does not send custom analytics events:
Pods are downloaded OK. Android build sends events OK;

`    
```
private void Awake()
    {
        CheckFirebase();
    }
```

    private FirebaseApp App { get; set; }

    private void CheckFirebase()
    {
        FirebaseApp.CheckAndFixDependenciesAsync()
            .ContinueWith(task => {
                var dependencyStatus = task.Result;
                if (dependencyStatus == DependencyStatus.Available) {
                    OnDependenciesSuccess();
                }
                else {
                    Debug.LogError($"Could not resolve all Firebase dependencies: {dependencyStatus}");
                }
            });
    }

    private void OnDependenciesSuccess()
    {
        print("Firebase init OK");
        App = FirebaseApp.DefaultInstance;
        FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
    }

```
 public void fb_GameFail(int id)
    {
        string eventName = "level_fail_" + num;
        Debug.Log("FIREBASE EVENT: "     + eventName);
        FirebaseAnalytics.LogEvent(eventName);
    }`
```

Logs:
[cs-max-4-debug.txt](https://github.com/firebase/quickstart-unity/files/6957809/cs-max-4-debug.txt)

At some point it says:
2021-08-06 14:46:55.138278+0300 colourspin[1380:348216] 8.3.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App 

Docs do not mention any iOS required configuration though.

**Comment by paulinon** [comment]
Hi @equizo,

In order to identify the cause of this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps taken before facing this issue?

**Comment by jordanmuraskin** [comment]
Im having the same issue. Events send on Android but not on iOS.

**Comment by equizo** [comment]
> ken before facing this issue?

Here you go:
https://drive.google.com/file/d/16--dV9o-FIYlb1TZ8gRDdg0wCis4ssX_/view?usp=sharing

**Comment by paulinon** [comment]
Hi @equizo,

I'm facing some errors with the minimal repro you provided. It would be great if you could provide additional steps I could perform in replicating the issue.

<img width="1392" alt="Screen Shot 2021-08-16 at 5 24 49 PM" src="https://user-images.githubusercontent.com/58971522/129541665-1b4f9467-5e8e-464a-8d17-6f874989ca06.png">

Additionally, could you confirm if you're facing the same behavior when using our quickstart?

**Comment by equizo** [comment]
I followed the documentation and created another project from scratch. Still no data for iOS. Please find the source files attached as well as Xcode console log
https://drive.google.com/drive/folders/1k6pb6oKmsYYOATSBOLDI4rjGbn-PfbWe?usp=sharing
![image](https://user-images.githubusercontent.com/6953056/131930370-85986b89-3f42-4469-bc49-48445f290af2.png)

**Comment by paulinon** [comment]
Hi @equizo,

Based on my analysis, issues like this aren't usually caused by the SDK. You may reach out to [Firebase Support](https://firebase.google.com/support) for this issue.

You can make use of [DebugView](https://firebase.google.com/docs/analytics/debugview#ios) so that you can make sure that your raw event data is logged by your app.
