### ISSUE TITLE
[Bug] Remote Config: Setting MinimumFetchInternalInMilliseconds does not work as expected

### ISSUE THREAD

**Issue by micsnz** [firebase/quickstart-unity#1112]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.5f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: installed via unitypackage
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Analytics, Messaging, Auth, Crashlytics
  * Additional SDKs you are using: Facebook, IronSource
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP (.NET 4.x)

### [REQUIRED] Please describe the issue here:

Setting `MinimumFetchInternalInMilliseconds` does not seem to work as expected. For example, if it is set to 120000 (2 minutes), remote values are never fetched even after 2 minutes have elapsed. It seems as though the cached values never expire.

#### Steps to reproduce:

1.) Import Firebase packages (Analytics, Messaging, Remote Config, Crashlytics, Auth)
2.) Test Remote Config by setting `MinimumFetchInternalInMilliseconds `to 120000 (2 minutes)
3.) Call `FirebaseRemoteConfig.DefaultInstance.FetchAsync();`. It completes successfully but remote values are never fetched even after 2 minutes have elapsed (as indicated by `info.FetchTime`).

#### Relevant Code:

```c#
// this example assumes that the dependency status check was successful (this.dependencyStatus == DependencyStatus.Available)

private void InitRemoteConfig()
{
	Dictionary<string, object> defaults = new Dictionary<string, object>();
	defaults.Add("level_time", 300);
	defaults.Add("default_coins", 50);

	FirebaseRemoteConfig.DefaultInstance.SetDefaultsAsync(defaults).ContinueWithOnMainThread(task =>
	{
		var configSettings = new ConfigSettings();
		configSettings.MinimumFetchInternalInMilliseconds = 120000;
		FirebaseRemoteConfig.DefaultInstance.SetConfigSettingsAsync(configSettings).ContinueWithOnMainThread(task =>
		{
		    this.FetchRemoteData();
		});
	});
}

private Task FetchRemoteData()
{
	Task fetchTask = FirebaseRemoteConfig.DefaultInstance.FetchAsync();
	return fetchTask.ContinueWithOnMainThread(this.RemoteDataFetchComplete);
}

private void RemoteDataFetchComplete(Task fetchTask)
{
	if (fetchTask.IsCanceled)
	{
	    print("FirebaseRemoteConfig fetch canceled");
	}
	else if (fetchTask.IsFaulted)
	{
	    print("FirebaseRemoteConfig fetch encountered an error.");
	}
	else if (fetchTask.IsCompleted)
	{
	    print("FirebaseRemoteConfig fetch completed successfully!");
	}

	var info = FirebaseRemoteConfig.DefaultInstance.Info;
	switch (info.LastFetchStatus)
	{
		case LastFetchStatus.Success:
			FirebaseRemoteConfig.DefaultInstance.ActivateAsync().ContinueWithOnMainThread(task =>
			{
				// this part of the code is reached successfully but info.FetchTime never seems to update, even after more than 2 minutes have elapsed 
				print($"FirebaseRemoteConfig Remote data loaded and ready (last fetch time {info.FetchTime}).");
			});
			break;
		case LastFetchStatus.Failure:
			switch (info.LastFetchFailureReason)
			{
				case FetchFailureReason.Error:
					print("FirebaseRemoteConfig Fetch failed for unknown reason");
					break;
				case FetchFailureReason.Throttled:
					print("FirebaseRemoteConfig Fetch throttled until " + info.ThrottledEndTime);
					break;
			}
			break;
		case LastFetchStatus.Pending:
			print("FirebaseRemoteConfig Latest Fetch call still pending.");
			break;
	}
}
```

**Comment by paulinon** [comment]
Hi @micsnz,

Thanks for reporting this. So far, I haven't been able to replicate this issue with the information you provided. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps taken before facing this issue? This way, we can identify what's causing this behavior.
