### ISSUE TITLE
[Bug] Firebase loads local copy of database instead of server version

### ISSUE THREAD

**Issue by ORibn-dev** [firebase/quickstart-unity#1114]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.16f
  * Firebase Unity SDK version: Version 8.1.0 - July 19, 2021
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Database, Storage, RemoteConfig, Firestore;
  * Additional SDKs you are using:Facebook, Appodeal
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Does anyone have this issue? When I load data from Firebase Database for whatever reason it loads data from the local copy of database instead of server, so if I change elements in database outside Unity and start Unity scene again it won't load updated version, only local copy. But at the same time when I save data in Unity it works and changes data on the server as well, so it probably doesn't have connection issues. I use only FirebaseDatabase.DefaultInstance.RootReference line to load database and its URL is listed in google-services json file.

It might not be a bug, maybe it loads a local copy by default and requires an extra line or two to load it from server instead, but initialization/installation docs didn't mention anything like that. Any help would be very appreciated.

#### Relevant Code:

```
FirebaseDatabase.DefaultInstance.RootReference;
```

**Comment by ORibn-dev** [comment]
Alright, looks like this issue is present only in Editor, but in Standalone Android build it loads from the server. Is there any way to do the same in Editor?

**Comment by paulinon** [comment]
Hi @ORibn-dev,

I've tried to retrieve data using the editor, and it shows the updated data. With that, could you try a different network connection and see if it makes any difference?

**Comment by ORibn-dev** [comment]
> Hi @ORibn-dev,
> 
> I've tried to retrieve data using the editor, and it shows the updated data. With that, could you try a different network connection and see if it makes any difference?

Hi, paulinon! I'll try, but I suspect the issue is probably different.

**Comment by ORibn-dev** [comment]
Hi, @paulinon ! Is there any way to disable loading data from the local copy and load only from the server? Theoretically it should be somewhere. I just don't understand why Editor and Android build work in different ways with the same code. It can't be internet issue.

**Comment by paulinon** [comment]
Hi @ORibn-dev, 

The data is always being read from a local copy which is then updated by the server when it's available. 

Let me know if using a different network connection makes a difference.
