### ISSUE TITLE
[Bug] google-services.xml not regenerated unless changing google-services.json

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#1117]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: tgz
  * Problematic Firebase Component: App Core
  * Other Firebase Components in use: Auth, Firestore, Analytics, Crashlytics, DynamicLinks
  * Additional SDKs you are using: Facebook, GoogleAds, Onesignals
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

In my project I would not upload `res/values/google-services.xml` file into git repository and sometime remove it from the local because I expect that it would always regenerated from `google-services.json` if the xml was missing

But recently I see that was not the case anymore. It seem firebase would only look for the changed of the file `google-services.json` for generating the xml. Deleting the xml and build the project now not triggering the regeneration of xml from json

I have expectation that at the build time, firebase sdk would check for existence of `google-services.xml` and regenerate the xml file before building `.aab`. There was `IPreprocessBuildWithReport.OnPreprocessBuild` that we can hook for in unity editor

#### Steps to reproduce:

- place `google-services.json` into the project
- delete `google-services.xml` that would be generated
- try to build the project

What happened? How can we make the problem occur?
- No `Generated Firebase Android Resources file` logged in the console. Unless try tweaking `google-services.json`

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
- Not sure. The test project don't even auto generate xml at all

What's the issue repro rate?
- 100%

#### Relevant Code:

ps. I found out that I could manually call `Firebase.Editor.GenerateXmlFromGoogleServicesJson.ForceJsonUpdate()` in the pre build hook by myself. Is it require to manually call by ourselves from now on or is this issue actually a bug somewhere and would be fix?

Actually, could you expose the rule about triggering the xml generator in unity?

Would you please just open source the firebase unity sdk?

**Comment by paulinon** [comment]
Hi @Thaina,

Thanks for reporting this issue. While I try to replicate this, could you confirm if this behavior persists using an LTS version of the editor (the latest LTS Release is version 2020.3.16f1)?

**Comment by Thaina** [comment]
Actually it could be able to run normally in 2021.1.10f

So I think maybe it was the same problem as
https://forum.unity.com/threads/google-iosresolver-will-not-be-loaded-in-2021-1-11f1-and-later.1128617/
and
https://github.com/googlesamples/unity-jar-resolver/issues/441

**Comment by paulinon** [comment]
Glad to hear that you found a workaround, @Thaina. 

With that, I'll be closing this ticket for now. You may follow the thread you provided for more updates. 

Let me know if a new issue arises.

**Comment by Thaina** [comment]
Thank you very much
