### ISSUE TITLE
[Question] What does "Secret lookup failed. Error 2: The name org.freedesktop.secrets was not provided by any .service files" mean? Is there anything I have to do?

### ISSUE THREAD

**Issue by dginovker** [firebase/quickstart-unity#1119]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.16
  * Firebase Unity SDK version: 8.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth, Database
  * Additional SDKs you are using: Mopub
  * Platform you are using the Unity editor on: Linux
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

I tried Googling for this, but there were no hits.

When running my game, I get the warning `Secret lookup failed. Error 2: The name org.freedesktop.secrets was not provided by any .service files`. I have no idea what this means and I didn't see this on my Mac (which I used to use for development). Is this a warning I should pay close attention to?

Thanks

**Comment by paulinon** [comment]
Hi @dginovker,

This is a rather unusual issue. In order to identify what's causing this, could you verify if the issue persists without the Firebase SDK in your implementation? If not, kindly provide the complete steps needed to replicate the issue.
