### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by Kunruedee1993** [firebase/quickstart-unity#1120]
### [READ] Guidelines

When filing a feature request please make sure the issue title starts with "[FR]".

A good feature request ideally
* is either immediately obvious (i.e. "Add Sign in with Apple support"), or
* starts with a use case that is not achievable with the existing Firebase API and
  includes an API proposal that would make the use case possible. The proposed API
  change does not need to be very specific.

Once you've read this section, please delete it and fill out the rest of the template.

### Feature proposal

* Firebase Component: _____ (Auth, Core, Database, Firestore, Messaging, Storage, etc)

Describe your use case and/or feature request here.

**Comment by paulinon** [comment]
Hi @Kunruedee1993,

I see that you've filed a ticket with just the issue template. With that, I'll be closing this along with #1121 and #1122. 

If you're facing an issue with the Firebase SDK on your Unity platform or if you have a feature that you want implemented, kindly include the necessary information in a new ticket.
