### ISSUE TITLE
[Question] How to create FirebaseApp with AppOptions different from options at "Assets/google-services.json"?

### ISSUE THREAD

**Issue by Glongooo** [firebase/quickstart-unity#1123]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.13f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: FirebaseApp, Firestore
  * Other Firebase Components in use: Auth, Analytics
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the question here:

Hello, in my project I've separated Firebase applications for different build environments (dev/release). I want to create some editor tool to transfer data between applications. According to scripting reference i wrote following code:
`var appOptions = AppOptions.LoadFromJsonConfig(configString); // configString - google-services.json contents different from Assets/google-services.json
var app = FirebaseApp.Create(appOptions);
`
After execution of this code app.Options contains data from "Assets/google-services.json" not from config string. What is a right way for multiple application initialization?

**Comment by paulinon** [comment]
Hi @Glongooo,

While you got the right idea of storing Firebase options in a variable, you need to make use of the API Key, Google App ID, and the project ID. Here's how to do it:

```
Firebase.AppOptions secondaryAppOptions = new Firebase.AppOptions {
  ApiKey = "<API_KEY>",
  AppId = "<GOOGLE_APP_ID>",
  ProjectId = "<PROJECT_ID>"
};
```

You may refer to our [documentation](https://firebase.google.com/docs/projects/multiprojects#unity) for more information.

I'll be closing this for now. Let me know if the solution I provided doesn't fit your use case.
