### ISSUE TITLE
[Question] How to upload Android symbols to Crashlytics for symbolicated crashes

### ISSUE THREAD

**Issue by deighvyd2** [firebase/quickstart-unity#1124]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.17f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Mac & Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

Hi,

I have integrated Crashlytics and Analytics into our Unity app and the integration appears to be working correctly:
- crashes come though to the dashboard
- Analytics events are being show on the dashboard

However crashes from C++/NDK land are not getting symbolicated so I am attempting to upload the symbols but the correct process for doing this is eluding me.

I have the unstripped symbols from zip file output by the build process and have located the stripped symbols in the Temp/gradleOut folder but I cannot work out how to upload them.

I have tried integrating the instructions here https://firebase.google.com/docs/crashlytics/ndk-reports into the Unity Gradle build but this generates other errors such as not being able to find the correct plugins)

https://github.com/firebase/quickstart-unity/issues/879 outlines a similar issues and one of the responses seems to indicate that the upload of the symbols should be handled by the Crashlytics Editor plugin, but I cannot find any reference in any documentation that confirms or denies this.

Quickly summarizing my questions are:
1) Should the Crashlytics Unity plugin upload generated symbols automatically
    - if so what approaches can I use to debug why it is not working?
2) Is there a recommended way to upload the generated symbols post build?
3) Is there any documentation that describes how to perform the symbol uploading

**Comment by deighvyd2** [comment]
Exporting the project to and then building it in Android studio shows that no upload task is executed

`Executing tasks: [:launcher:assembleRelease] in project C:\temp\Mona.build


> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources
> Task :unityLibrary:generateReleaseBuildConfig
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:generateReleaseResources
> Task :launcher:mainApkListPersistenceRelease
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources
> Task :launcher:prepareLintJar
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseResources
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources
> Task :unityLibrary:packageReleaseResources
> Task :launcher:mergeReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:extractDeepLinksRelease
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksRelease
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish
> Task :unityLibrary:compileReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseShaders
> Task :unityLibrary:generateReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibResRelease
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols
> Task :unityLibrary:FirebaseCrashlytics.androidlib:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile
> Task :unityLibrary:FirebaseCrashlytics.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:prepareLintJarForPublish
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseCrashlytics.androidlib:stripReleaseDebugSymbols
> Task :unityLibrary:FirebaseCrashlytics.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseRFile
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibRuntimeRelease
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :launcher:compileReleaseShaders
> Task :launcher:generateReleaseAssets
> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:validateSigningRelease
> Task :launcher:desugarReleaseFileDependencies

> Task :unityLibrary:BuildIl2CppTask
Running il2cpp.exe in server GC mode.
Building libil2cpp.so with AndroidToolChain
	Output directory: C:\temp\Mona.build\unityLibrary\src\main\jniLibs\arm64-v8a
	Cache directory: C:\temp\Mona.build\unityLibrary\build\il2cpp_arm64-v8a_Release\il2cpp_cache
ObjectFiles: 238 of which compiled: 0
Total compilation time: 380 milliseconds.

> Task :launcher:mergeReleaseResources
> Task :launcher:mergeExtDexRelease

> Task :unityLibrary:BuildIl2CppTask
Cleaned up 0 object files.

> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:bundleLibResRelease
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:generateReleaseRFile
> Task :launcher:processReleaseManifest
> Task :launcher:processReleaseResources

> Task :unityLibrary:compileReleaseJavaWithJavac
Note: C:\temp\Mona.build\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :launcher:mergeReleaseJavaResource
> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :unityLibrary:bundleLibCompileRelease
> Task :launcher:javaPreCompileRelease
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:compileReleaseSources
> Task :launcher:lintVitalRelease
> Task :launcher:dexBuilderRelease
> Task :launcher:mergeReleaseNativeLibs
> Task :launcher:stripReleaseDebugSymbols
> Task :launcher:mergeDexRelease
> Task :launcher:packageRelease
> Task :launcher:assembleRelease

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 33s
90 actionable tasks: 90 executed`

**Comment by deighvyd2** [comment]
When building from within Unity the log shows that it is generating/executing a task called "Performance Reporting Symbol Upload" but it is not clear if this is uploading the symbols I am interested in

```
Android PostProcess task "Creating staging area" took 1.1777 ms
Android PostProcess task "Generating Build Id" took 0.1694 ms
Android PostProcess task "Preparing Unity resources" took 100.8551 ms
Android PostProcess task "Managed Stripping: (Mono)" took 0.3912 ms
Android PostProcess task "Preparing Managed resources" took 743.4143 ms
Android PostProcess task "Splitting assets" took 1186.8907 ms
Android PostProcess task "Processing OBB assets" took 0.1868 ms
Android PostProcess task "Preparing Unity libraries" took 102.7898 ms
Android PostProcess task "Processing resources" took 0.5814 ms
Android PostProcess task "Preparing APK resources" took 57.4366 ms
Android PostProcess task "Processing plugins" took 389.7 ms
Android PostProcess task "Processing Android libraries" took 4.1611 ms
Android PostProcess task "Checking Graphics API compatibility" took 1.3258 ms
Android PostProcess task "Creating Android manifest" took 52.7882 ms
Android PostProcess task "Compiling resources" took 19.8643 ms
Android PostProcess task "GenerateIl2cppPlatformProviders" took 1.3895 ms
Invoking UnityLinker with response file. response.rsp contents: -out=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/tempStrip -x=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/../platform_native_link.xml -x=C:/Users/dbray/AppData/Local/Temp/5/tmp4ac94987.tmp -x=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/TypesInScenes.xml -x=C:/dev/bluemonkey.unity/Assets/link.xml -x=C:/dev/bluemonkey.unity/Assets/Firebase/Plugins/Crashlytics/link.xml -d=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed --include-unity-root-assembly=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/Assembly-CSharp.dll --include-unity-root-assembly=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/Unity.RenderPipelines.Core.Runtime.dll --include-unity-root-assembly=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/UnityEngine.UI.dll --dotnetruntime=il2cpp --dotnetprofile=unityaot --use-editor-options --include-directory=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed --editor-settings-flag=Development --rule-set=Conservative --editor-data-file=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed/EditorToUnityLinkerData.json --platform=Android --enable-engine-module-stripping --engine-modules-asset-file="C:/Program Files/Unity/Hub/Editor/2020.1.17f1/Editor/Data/PlaybackEngines/AndroidPlayer/Whitelists/../modules.asset"
C:\Program Files\Unity\Hub\Editor\2020.1.17f1\Editor\Data\il2cpp\build/deploy/net471/UnityLinker.exe exited after 5262 ms.
C:\Program Files\Unity\Hub\Editor\2020.1.17f1\Editor\Data\Tools/InternalCallRegistrationWriter/InternalCallRegistrationWriter.exe exited after 253 ms.
Invoking il2cpp with arguments: --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARM64" --configuration="Release" --outputpath="C:\dev\bluemonkey.unity\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a\libil2cpp.so" --cachedirectory="C:\dev\bluemonkey.unity\Assets\..\Library\il2cpp_android_arm64-v8a/il2cpp_cache" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2020.1.17f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:/Program Files/Unity/Hub/Editor/2020.1.17f1/Editor/Data/PlaybackEngines/AndroidPlayer/Tools\libil2cpp/include" --baselib-directory="C:/Program Files/Unity/Hub/Editor/2020.1.17f1/Editor/Data/PlaybackEngines/AndroidPlayer\Variations\il2cpp\Release\StaticLibs\arm64-v8a" --avoid-dynamic-library-copy --tool-chain-path="C:/Program Files/Unity/Hub/Editor/2020.1.17f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK" --profiler-report --map-file-parser="C:/Program Files/Unity/Hub/Editor/2020.1.17f1/Editor/Data/Tools/MapFileParser/MapFileParser.exe" --directory=C:/dev/bluemonkey.unity/Temp/StagingArea/assets/bin/Data/Managed --generatedcppdir=C:/dev/bluemonkey.unity/Temp/StagingArea/Il2Cpp/il2cppOutput 
C:\Program Files\Unity\Hub\Editor\2020.1.17f1\Editor\Data\il2cpp/build/deploy/netcoreapp3.0/il2cpp.exe exited after 20409 ms.
Android PostProcess task "IL2CPP" took 31117.1405 ms
Android PostProcess task "Build native Unity binary" took 7881.5695 ms
Android PostProcess task "Zipping symbols" took 926.5253 ms
Android PostProcess task "Performance Reporting Symbol Upload" took 0.3277 ms
Android PostProcess task "Preparing streaming assets" took 75.1488 ms
Android PostProcess task "Creating APK expansion package (OBB)" took 0.13 ms
```

**Comment by paulinon** [comment]
HI @deighvyd2,

Unfortunately, NDK + Unity implementation is not yet officially supported. While you might be able to configure your own solution if you follow the NDK integration information directly in the exported Android Studio project, there’s no guarantee it will work.

Let me know if this is a feature you want implemented.

**Comment by deighvyd2** [comment]
Hi,
I was looking into manually uploading the symbols however I have had to put that aside for a while

This would be a feature that I would like implemented as it would save a great deal of time and it is supported out of the box on iOS

**Comment by paulinon** [comment]
Hi @deighvyd2,

As of version [8.6.0](https://firebase.google.com/support/release-notes/unity#version_860_-_november_8_2021) of the SDK, you may now upload symbol files for your builds so that the symbolicated IL2CPP stack traces can be displayed in the Crashlytics console.
