### ISSUE TITLE
[Bug] ANR Caused By executing service com.xcompany.game/com.google.firebase.messaging.cpp.RegistrationIntentService

### ISSUE THREAD

**Issue by SamiSdd** [firebase/quickstart-unity#1125]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.29f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: TGZ
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Analytics, Crashlytics, Dynamic Link
  * Additional SDKs you are using: Facebook, IronSource, AdMob, Unity, AppsFlyer
  * Platform you are using the Unity editor on: Mac & Windows
  * Platform you are targeting: iOS & Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Here is a log of ANR we are seeing 
ANR
 executing service com.company.game/com.google.firebase.messaging.cpp.RegistrationIntentService

    [vdso]:1592 __kernel_rt_sigreturn
    /apex/com.android.runtime/lib64/bionic/libc.so:768680 nanosleep
    libil2cpp GC_lock
    libil2cpp GC_register_my_thread
    libil2cpp il2cpp::gc::GarbageCollector::RegisterThread(void*)
    libil2cpp il2cpp::vm::Thread::Attach(Il2CppDomain*)
    /data/app/com.company.game-TCJCc7-zMlobTrLrCWX9Lw==/lib/arm64/libunity.so:6095740 
    /data/app/com.company.game-TCJCc7-zMlobTrLrCWX9Lw==/lib/arm64/libunity.so:2719668 
    /data/app/com.company.game-TCJCc7-zMlobTrLrCWX9Lw==/lib/arm64/libunity.so:2719436 
    /data/app/com.company.game-TCJCc7-zMlobTrLrCWX9Lw==/oat/arm64/base.odex:369236 
    Unknown:-2 com.unity3d.player.ReflectionHelper.nativeProxyInvoke
    Unknown com.unity3d.player.ReflectionHelper.a
    Unknown:31 com.unity3d.player.ReflectionHelper$1.invoke
    Proxy.java:1006 java.lang.reflect.Proxy.invoke
    Unknown:-1 $Proxy14.onResult
    TokenPendingResult.java:135 com.google.games.bridge.TokenPendingResult.setStatus
    SignInRequest.java:249 com.google.games.bridge.SignInRequest.setFailure
    SignInRequest.java:184 com.google.games.bridge.SignInRequest$2.onFailure
    com.google.android.gms:play-services-tasks@@17.2.1:1 com.google.android.gms.tasks.zzk.run
    Handler.java:900 android.os.Handler.handleCallback
    Handler.java:103 android.os.Handler.dispatchMessage
    Looper.java:219 android.os.Looper.loop
    ActivityThread.java:8393 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:513 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1055 com.android.internal.os.ZygoteInit.main
![image](https://user-images.githubusercontent.com/1784844/131026330-895c4c73-0d24-4f1a-ad8d-d9057cae7d7e.png)
![image](https://user-images.githubusercontent.com/1784844/131026516-e54cbeea-51a9-4122-bdff-a1007d33798c.png)
![image](https://user-images.githubusercontent.com/1784844/131026585-c0424d57-8a8b-4ec6-9121-dcdf20a019e4.png)

**Comment by SamiSdd** [comment]
@paulinon We were not able to reproduce this on our end but we are seeing a lot of our production users are seeing this ANR

**Comment by paulinon** [comment]
Hi @SamiSdd,

There's a possibility that this is related to #939. In order to identify what's causing your behavior, could you provide any stack traces related to the issue?

**Comment by SamiSdd** [comment]
Hi @paulinon, 

We have already tried the fix mentioned in #939 but the ANR didn't get fixed. Our AndroidManifest.xml has the following line
```
    <service android:name="com.google.firebase.messaging.MessageForwardingService"
      android:permission="android.permission.BIND_JOB_SERVICE"
      android:exported="false" >
    </service>
```

Here are stack traces of all threads
[bugsnag_error_stacktrace_ANR_event_612e6e39007fa389cdc70000.txt](https://github.com/firebase/quickstart-unity/files/7086346/bugsnag_error_stacktrace_ANR_event_612e6e39007fa389cdc70000.txt)

**Comment by paulinon** [comment]
Thanks for the additional information, @SamiSdd. While we analyze this, could you confirm if this behavior persists using our quickstart project?

**Comment by SamiSdd** [comment]
@paulinon Thanks, I have a theory by looking at the stack trace, I haven't seen code for Firebase or Google Play Games so I'm not sure about this, Maybe this will help. 

In the stack trace, I've posted. There are 2 threads that seem to be calling the GPS signing at the same time. 

**Thread 1 - main**:
```
    Unknown:-2 com.unity3d.player.ReflectionHelper.nativeProxyInvoke
    Unknown com.unity3d.player.ReflectionHelper.a
    Unknown:31 com.unity3d.player.ReflectionHelper$1.invoke
    Proxy.java:1006 java.lang.reflect.Proxy.invoke
    Unknown:-1 $Proxy14.onResult
    TokenPendingResult.java:135 com.google.games.bridge.TokenPendingResult.setStatus
    SignInRequest.java:257 com.google.games.bridge.SignInRequest.setSuccess
    SignInRequest.java:25 com.google.games.bridge.SignInRequest.access$000
    SignInRequest.java:162 com.google.games.bridge.SignInRequest$3.onSuccess
    SignInRequest.java:158 com.google.games.bridge.SignInRequest$3.onSuccess
    com.google.android.gms:play-services-tasks@@17.2.1:1 com.google.android.gms.tasks.zzm.run
    Handler.java:900 android.os.Handler.handleCallback
    Handler.java:103 android.os.Handler.dispatchMessage
    Looper.java:219 android.os.Looper.loop
    ActivityThread.java:8393 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:513 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1055 com.android.internal.os.ZygoteInit.main
```
**Thread 2668 - Thread-41**
```
    [vdso]:1592 __kernel_rt_sigreturn
    /apex/com.android.runtime/lib64/bionic/libc.so:768680 nanosleep
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libil2cpp.so:28172732 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libil2cpp.so:28223196 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libil2cpp.so:28288344 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libil2cpp.so:28045420 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libunity.so:6095740 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libunity.so:2719668 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/lib/arm64/libunity.so:2719436 
    /data/app/com.xcompany.xgame-a0vfrJYOjIfIrqcnIJJ0mg==/oat/arm64/base.odex:959060 
    Unknown:-2 com.unity3d.player.ReflectionHelper.nativeProxyInvoke
    Unknown com.unity3d.player.ReflectionHelper.a
    Unknown:31 com.unity3d.player.ReflectionHelper$1.invoke
    Proxy.java:1006 java.lang.reflect.Proxy.invoke
    Unknown:-1 $Proxy14.onResult
    TokenPendingResult.java:135 com.google.games.bridge.TokenPendingResult.setStatus
    SignInRequest.java:257 com.google.games.bridge.SignInRequest.setSuccess
    SignInRequest.java:25 com.google.games.bridge.SignInRequest.access$000
    SignInRequest.java:162 com.google.games.bridge.SignInRequest$3.onSuccess
    SignInRequest.java:158 com.google.games.bridge.SignInRequest$3.onSuccess
    com.google.android.gms:play-services-tasks@@17.2.1:1 com.google.android.gms.tasks.zzm.run
    Handler.java:900 android.os.Handler.handleCallback
    Handler.java:103 android.os.Handler.dispatchMessage
    Looper.java:219 android.os.Looper.loop
    ActivityThread.java:8393 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:513 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1055 com.android.internal.os.ZygoteInit.main
```
So I think (**Thread 1 - main**) is our code trying to signing user to Google Play Games, and the other one (**Thread 2668 - Thread 41**) is Firebase. So I think the following configuration could help.

**Comment by SamiSdd** [comment]
Update: So far by making sure the Firebase doesn't initialize at the same time as Google Play Game, We are seeing fewer ANRs. I will post a comprehensive report once I'm sure every thing is working fine
