### ISSUE TITLE
[Bug] Symbol not found because IOSResolver.dll does not load in Unity 2021.1.10

### ISSUE THREAD

**Issue by starburst997** [firebase/quickstart-unity#1134]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1.20f1
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: Unity Package Manager (.tgz)
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I'm having a compile issue when targeting iOS with Crashlytics enabled, it is complaining about a missing symbol. If I remove firebase, then I have no issue, if I use an older version of Unity (ex: 2020.3.18f1) then I have no issue (works perfectly and can see crash logs in firebase console).

I noticed the issue started happening around Unity 2021.1.10

Here's the log:

```
5599: ▸       objc-class-ref in libCrashlyticsiOSWrapper.a(CrashlyticsiOSWrapper.o)
5600: ▸   "_FIRCLSUserLoggingRecordInternalKeyValue", referenced from:
5601: ▸       _CLUSetInternalKeyValue in libCrashlyticsiOSWrapper.a(CrashlyticsiOSWrapper.o)
5602: ▸ ld: symbol(s) not found for architecture arm64
5603: ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Other potential relevant info from the log:

```
919: [Unity] Assembly 'Packages/com.google.firebase.crashlytics/Firebase/Editor/Firebase.Crashlytics.Editor.dll' will not be loaded due to errors:
920: [Unity] Reference has errors 'Firebase.Editor'.
921: [Unity] Assembly 'Packages/com.google.firebase.app/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
922: [Unity] Reference has errors 'Google.IOSResolver'.
923: [Unity] Assembly 'Packages/com.google.external-dependency-manager/ExternalDependencyManager/Editor/Google.IOSResolver_v1.2.166.dll' will not be loaded due to errors:
924: [Unity] Assembly name 'Google.IOSResolver' does not match file name 'Google.IOSResolver_v1.2.166'
```

I'm using Unity Cloud Build since I don't have access to a Mac to build iOS.

#### Steps to reproduce:

- Use Unity 2021.1.20f1
- Use .tgz for firebase crashlytics / analytics / core / dependency manager
- Compile for iOS

#### Relevant Code:

No code necessary

**Comment by starburst997** [comment]
### Fix

After seeing that last bit of log `'Google.IOSResolver' does not match file name 'Google.IOSResolver_v1.2.166'` I went and renamed all the files inside `com.google.external-dependency-manager-1.2.166.tgz` that were ending with `_v1.2.166`. It now compiles successfully and as far as I can see, everything looks fine.

**Comment by paulinon** [comment]
Hi @starburst997,

I'm glad that you're able to resolve the issue on your own. I was unable to replicate the issue with the information you have given me so far.

I'll be closing this for now. Let me know if another issue arises.

**Comment by starburst997** [comment]
@paulinon I think the issue is pretty clear from the error log, `'Google.IOSResolver' does not match file name 'Google.IOSResolver_v1.2.166'` and a quick google search seems to indicate that others are having the same issue. Why not fix the issue, especially when the fix is so simple?

Are you sure you used Unity *2021.1.20f1* ? This issue didn't exists prior to 2021.1.11f1 and just to makes sure I wasn't crazy, I created a new empty project using Unity 2021.1.20f1, imported `FirebaseCrashlytics.unitypackage` (the latest at the time) and the first things I'm greeted with is

```
Assembly 'Assets/ExternalDependencyManager/Editor/Google.IOSResolver_v1.2.166.dll' will not be loaded due to errors:
Assembly name 'Google.IOSResolver' does not match file name 'Google.IOSResolver_v1.2.166'
```

How can this be ignored?

**Comment by chkuang-g** [comment]
@starburst997 

The issue with `IOSResolver.dll` is documented here.
https://github.com/googlesamples/unity-jar-resolver/issues/441#issuecomment-915690686

I'll keep this bug opened until we have a better workaround in EDM4U side (so that you do not need to rename all those libraries in `.tgz` :( )

Allow me to change the title

**Comment by chkuang-g** [comment]
EDM4U `1.2.167` is released and should be included in the next Firebase Unity release.

If you need it right away, you can get the either `.unitypackage` version or `.tgz` version on [Google API for Unity page](https://developers.google.com/unity/archive#external_dependency_manager_for_unity).

I'll keep this open until next Firebase SDK is released.
