### ISSUE TITLE
Firebase/AnalyticsWithoutAdIdSupport pod not found in latest Unity Analytics package

### ISSUE THREAD

**Issue by dioniguerra** [firebase/quickstart-unity#1135]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.428f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the question here:

Hi guys, The Firebase Analytics SDK Integration documentation states to use Firebase/AnalyticsWithoutAdIdSupport instead of Firebase/Analytics to work without IDFA collection, however, on adding com.google.firebase.analytics-8.1.0.tgz package and modifying the AnalyticsDependencies.xml, from: 

`<iosPod name="Firebase/Analytics" version="8.3.0" minTargetSdk="9.0">`

to

` <iosPod name="Firebase/AnalyticsWithoutAdIdSupport" version="8.3.0" minTargetSdk="9.0">`

I get the following error at build time:

iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/AnalyticsWithoutAdIdSupport":
  In Podfile:
    Firebase/AnalyticsWithoutAdIdSupport (= 8.3.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/AnalyticsWithoutAdIdSupport (= 8.3.0).

How can correctly modify the pod dependency, to use Firebase/AnalyticsWithoutAdIdSupport? Or is this part of the another package? Please advice

Dioni

**Comment by paulinon** [comment]
Hi @dioniguerra,

Thanks for reporting this issue. Version 8.2.0 of the SDK has been released recently. Could you verify if the issue persists there as well?

**Comment by dioniguerra** [comment]
Hi @paulinon 

Thanks for getting back to me. I have downloaded the latest 8.2.0 packages, and still getting the same issue. As above, my steps were as follows:

* Download latests 8.2.0 tgz package from https://developers.google.com/unity/archive
* Unzip the package and modify the `com.google.firebase.analytics-8.2.0\Firebase\Editor\AnalyticsDependencies.xml` file with the following:

`<iosPod name="Firebase/AnalyticsWithoutAdIdSupport" version="8.6.0" minTargetSdk="9.0">`

* Load Unity with the latest changes, and build iOS
* Result: Same Error:  

[!] CocoaPods could not find compatible versions for pod "Firebase/AnalyticsWithoutAdIdSupport":
In Podfile:
Firebase/AnalyticsWithoutAdIdSupport (= 8.6.0)

NOTE that on unzipping the latest 8.2.0 tgz package, the FirebaseAnalytics_version-8.2.0-manifest.txt does not mention AnalyticsWithoutAdIdSupport dependency, 

Assets/Firebase/Editor/AnalyticsDependencies.xml
Assets/Firebase/Plugins/Firebase.Analytics.dll
Assets/Firebase/Plugins/Firebase.Analytics.dll.mdb
Assets/Firebase/Plugins/iOS/Firebase.Analytics.dll
Assets/Firebase/Plugins/iOS/Firebase.Analytics.dll.mdb
Assets/Firebase/Plugins/x86_64/FirebaseCppAnalytics.bundle
Assets/Firebase/Plugins/x86_64/FirebaseCppAnalytics.dll
Assets/Firebase/Plugins/x86_64/FirebaseCppAnalytics.so
Assets/Firebase/m2repository/com/google/firebase/firebase-analytics-unity/8.2.0/firebase-analytics-unity-8.2.0.pom
Assets/Firebase/m2repository/com/google/firebase/firebase-analytics-unity/8.2.0/firebase-analytics-unity-8.2.0.srcaar
Assets/Firebase/m2repository/com/google/firebase/firebase-analytics-unity/maven-metadata.xml
Assets/Plugins/iOS/Firebase/libFirebaseCppAnalytics.a
Assets/package.json

Please advise how to best proceed?
Dioni

**Comment by paulinon** [comment]
Hi @dioniguerra,

I wasn't able to replicate your issue, but I want to point out that I made use of version 2020.3.15.f2 of the Unity editor. Could you try if updating your Unity editor makes a difference? The latest LTS version of Unity as of writing is 2020.3.18f1.

**Comment by dioniguerra** [comment]
Hi @paulinon Thanks for attempting to repro the issue. I have also tried (with an empty project) on 2020 LTS version of Unity and seems to work there. However, upgrading our commercial project to higher version is a massive undertaking, if it can be avoided then we should consider it. 

What is the dependency on Unity 2020? Is there anything I can do with my current version of Unity to overcome this issue?

Dioni

**Comment by dioniguerra** [comment]
Hi @paulinon I found the issue. The problem is not Unity, but rather a conflict on dependencies in one of my xml files, I manually have InAppMessageDependencies.xml to include the InAppMessage pod, but this had conflict with the packages.

`<iosPod name="Firebase/InAppMessaging" version="7.5.0" minTargetSdk="8.0">`

Removing version and minTargetSdk from this line resolves the dependency with pods. 

Thanks for the help. This is working as expected

**Comment by paulinon** [comment]
Glad that you've found a way to resolve the issue, @dioniguerra. With that, I'll be closing this for now. Let me know if a new issue arises or if you have any other questions..
