### ISSUE TITLE
[Bug] Unity editor silent crash while playing on windows at random time but not crash on android or ubuntu.

### ISSUE THREAD

**Issue by gputhread** [firebase/quickstart-unity#1136]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.17
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Crashalytics, Messaging, Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob, Google Sign in, google In app review, unity iap (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows(Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

The windows editor crashes without any error while using firebase product with huge usage if realtime database and auth.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

call functions related to rapidly multiple times (realtime database and auth ).

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @gputhread,

Thanks for reporting this issue. Version 8.2.0 of the SDK has been released recently. Could you confirm if the issue persists there as well? If it does, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project.

**Comment by gputhread** [comment]
Event Viewer Report:

Faulting application name: Unity.exe, version: 2020.3.17.21367, time stamp: 0x611aeff0
Faulting module name: FirebaseCppApp-8_1_0.dll, version: 0.0.0.0, time stamp: 0x60f4a817
Exception code: 0xc0000409
Fault offset: 0x000000000000c894
Faulting process id: 0x19f4
Faulting application start time: 0x01d7a94cd0f7cfc2
Faulting application path: C:\CustomApps\UnityEngine\2020.3.17f1\Editor\Unity.exe
Faulting module path: K:\Flaanaa\Projects\2 Online Game\Unity\2D Based\Assets\Firebase\Plugins\x86_64\FirebaseCppApp-8_1_0.dll
Report Id: f0b3000e-00a7-47ae-9be1-9008876dfec3
Faulting package full name: 
Faulting package-relative application ID:

**Comment by gputhread** [comment]
Event Viewer Report:

Faulting application name: Unity.exe, version: 2020.3.17.21367, time stamp: 0x611aeff0
Faulting module name: FirebaseCppApp-8_1_0.dll, version: 0.0.0.0, time stamp: 0x60f4a817
Exception code: 0xc0000409
Fault offset: 0x000000000000c894
Faulting process id: 0x19f4
Faulting application start time: 0x01d7a94cd0f7cfc2
Faulting application path: C:\CustomApps\UnityEngine\2020.3.17f1\Editor\Unity.exe
Faulting module path: K:\Company\Projects\2 Online Game\Unity\2D Based\Assets\Firebase\Plugins\x86_64\FirebaseCppApp-8_1_0.dll
Report Id: f0b3000e-00a7-47ae-9be1-9008876dfec3
Faulting package full name:
Faulting package-relative application ID:

**Comment by gputhread** [comment]
I just got crash log after updating to firebase 8.2 with unity 2020.3.18, i usally get crash log very rarelly! it is mostly silent crash.

FirebaseCppApp-8_2_0.dll caused an Access Violation (0xc0000005)
  in module FirebaseCppApp-8_2_0.dll at 0033:2713ff00.

[https://pastebin.com/B3RGheR3]

**Comment by paulinon** [comment]
Thanks for the confirmation, @gputhread. It would be more helpful if you could provide a sample project that caused this crash so that we can identify what's causing this behavior.

**Comment by gputhread** [comment]
i have dmp file , will it work ?

**Comment by paulinon** [comment]
Hi @gputhread,

You may upload a repo containing your sample project here on GitHub and add me as a collaborator.

Additionally, could you confirm if using version 2020.3.18f1 of the Unity editor makes a difference?

**Comment by gputhread** [comment]
Ubuntu

Caught fatal signal - signo:11 code:128 errno:0 addr:(nil)
Obtained 16 stack frames.
#0  0x007f4d36409520 in __sigaction
#1  0x007f4b58b4a3c8 in __llvm_libc::memcpy(void*, void const*, unsigned long)
#2  0x007f4b58bb7674 in bool std::__u::__function::__policy_invoker<bool ()>::__call_impl<std::__u::__function::__default_alloc_func<firebase::database::internal::SyncTree::ApplyListenComplete(firebase::Path const&)::$_5, bool ()> >(std::__u::__function::__policy_storage const*)
#3  0x007f4b58be6d73 in firebase::database::internal::NoopPersistenceManager::RunInTransaction(std::__u::function<bool ()>)
#4  0x007f4b58bb176a in firebase::database::internal::SyncTree::ApplyListenComplete(firebase::Path const&)
#5  0x007f4b58bc0ba3 in firebase::database::internal::WebSocketListenProvider::StartListening(firebase::database::internal::QuerySpec const&, firebase::Optional<long> const&, firebase::database::internal::View const*)::$_0::__invoke(firebase::SharedPtr<firebase::database::internal::connection::Response> const&)
#6  0x007f4b58b911c7 in firebase::database::internal::connection::PersistentConnection::HandleListenResponse(firebase::Variant const&, firebase::SharedPtr<firebase::database::internal::connection::Response> const&, unsigned long)
#7  0x007f4b58b8b65b in firebase::database::internal::connection::PersistentConnection::OnDataMessage(firebase::Variant const&)
#8  0x007f4b58b85b10 in firebase::database::internal::connection::Connection::ProcessMessage(char const*)
#9  0x007f4b58b85177 in firebase::database::internal::connection::Connection::OnMessage(char const*)
#10 0x007f4b58b98ac0 in firebase::database::internal::connection::WebSocketClientImpl::OnMessage(uWS::WebSocket<false>*, char*, unsigned long, uWS::OpCode)::$_5::__invoke(firebase::internal::SafeReference<firebase::database::internal::connection::WebSocketClientImpl>, std::__u::basic_string<char, std::__u::char_traits<char>, std::__u::allocator<char> >)
#11 0x007f4b58b98f3d in firebase::callback::CallbackValue2<firebase::internal::SafeReference<firebase::database::internal::connection::WebSocketClientImpl>, std::__u::basic_string<char, std::__u::char_traits<char>, std::__u::allocator<char> > >::Run()
#12 0x007f4b5a540531 in firebase::scheduler::Scheduler::WorkerThreadRoutine(void*)
#13 0x007f4b58df30c7 in void* std::__u::__thread_proxy<std::__u::tuple<std::__u::unique_ptr<std::__u::__thread_struct, std::__u::default_delete<std::__u::__thread_struct> >, void (*)(void*), void*> >(void*)
#14 0x007f4d3645b927 in pthread_condattr_setpshared
#15 0x007f4d364eb9e4 in clone
Launching bug reporter
Refresh completed in 0.075694 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 75.641ms
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QObject(0x1a53c80), parent's thread is QThread(0x13de3d0), current thread is Thread(0x1a61600)
Refresh completed in 0.058841 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 58.776ms
Refresh completed in 0.063762 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 63.729ms
Refresh completed in 0.085330 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 85.255ms
Refresh completed in 0.082207 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 82.121ms
Refresh completed in 0.088551 seconds.
RefreshInfo: RefreshV2(AllowForceSynchronousImport) scanfilter: 
RefreshProfiler: Total: 88.506ms
