### ISSUE TITLE
[Bug] Remote Config is not updating server values

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1137]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.18f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Firestore, Crashlytics, Auth
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android (Unity Editor is also affected)
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

When changing values in the Remote Config dashboard, the changes are not available on the client's side, even after more than 12 hours after publishing the new values on the dashboard.

#### Relevant Code:

```
await FirebaseRemoteConfig.DefaultInstance.FetchAsync();

var remoteConfigInfo = FirebaseRemoteConfig.DefaultInstance.Info;
if(remoteConfigInfo.LastFetchStatus == LastFetchStatus.Success)
{
       await FirebaseRemoteConfig.DefaultInstance.ActivateAsync();
}
```

**Comment by paulinon** [comment]
Hi @Nyankoo,

Thanks for reporting this issue. Version 8.2.0 of the SDK has been released recently. Could you verify if the issue persists there as well? If it does, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate this behavior.

**Comment by Nyankoo** [comment]
@paulinon Did something in Version 8.2.0 change related to Remote Config? The changelog doesn't mention anything.

**Comment by paulinon** [comment]
Hi @Nyankoo,

While the release notes don't mention anything related to Remote Config, this is to ensure that the issue persists even with the latest updates and fixes.

I look forward to your findings.
