### ISSUE TITLE
[Question] - Android: What to do about 3rd party play stores where users don't have Google Play Services?

### ISSUE THREAD

**Issue by dginovker** [firebase/quickstart-unity#1139]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.28f1
  * Firebase Unity SDK version: 8.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth, Database, Messaging
  * Other Firebase Components in use: Auth, Database, Messaging
  * Additional SDKs you are using: Mopub
  * Platform you are using the Unity editor on: Mac, Linux
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

When looking at the Unity Dashboard crashes and exceptions, I'm seeing a lot of

```
InitializationException: Firebase modules failed to initialize: messaging (missing dependency)
```

What's interesting is all of them have install mods of either ApkPure or Aurora Store (not the official Play Store).

Based on the answers in SO posts [here](https://stackoverflow.com/questions/55661428/how-to-resolve-missing-dependency-error-with-firebase-and-unity3d) and [here](https://stackoverflow.com/questions/43273647/firebase-modules-failed-to-initialize-remote-config-missing-dependency), it seems like these are **Android devices without Google Play Services** (either emulators or maybe from countries with play services banned?). There's also a snippet in [this SO post](https://stackoverflow.com/questions/32721499/how-to-detect-if-google-play-services-is-installed-from-unity) showing how to detect Google Play Services.

**As a developer,** what steps are appropriate here?

* Is there a party of the Unity Firebase package that handles this?
* Can I package the Google Play Services API in my game?
* Am I allowed to suggest methods to install Google Play Services?

If none of the above, I can also inform the user their device is unsupported and exit.

I know this is a bit off-topic for Firebase Unity, but wasn't sure where else to get help. I also tried to include a few key strings so this issue comes up in the search engines and no other devs have to go through debugging this..

**Comment by DellaBitta** [comment]
Hi @dginvoker,

There are indeed utility methods in the SDK that allow you to [check if required dependencies](https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#checkdependenciesasync) are installed, and to [fix the problem if so](https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#fixdependenciesasync).  You can also do [both in one step](https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#class_firebase_1_1_firebase_app_1a330d32bf55497c14bb1393a0a8936868).

Are you currently using these methods and there's still an issue?  If so let us know!
