### ISSUE TITLE
One or more Firebase dependencies are not present.

### ISSUE THREAD

**Issue by rpassareti** [firebase/quickstart-unity#114]
Hello

I'm studying the implementation of firebase on unity, but everytime I got an error.
First, on the editor, in the Auth project, for some reason I can't use my firebase, it seems that is using a fictional one, because every email, or name, it works, even for a login without creating a new one, and on the site, it didn't appear;create too.

So I tried build to my android, and even starting a new project from zero, it gives me an error:
"One or more Firebase dependencies are not present.
Current dependency status: UnavailabelOther"

Tried to "Resolve Client Jar" but no results.

Unity 5.5.0f3
Mobile: Samsung S7
Android Version: 7.0

**Comment by stewartmiles** [comment]
@rpassareti the Firebase Auth desktop / auth implementation is a stub.  See https://firebase.google.com/docs/unity/setup#stub_implementations_for_the_editor

For your Android build try pulling in the latest https://github.com/googlesamples/unity-jar-resolver we recently fixed a race condition when running resolution.  If you're still running into problems it would be useful to turn on verbose logging under "Assets > Play Services Resolver > Android Resolver > Settings" and share the logs with us.

**Comment by rpassareti** [comment]
Ok... I deleted everything on the project, library folder, try a new version of unity (2017.1.0f3) and it works!
thanks for the support stewartmiles

but, there is any way to try in the editor the firebase? or only sending to the mobile?

**Comment by stewartmiles** [comment]
@rpassareti we only support mobile at the moment.  If you file a feature request to firebase support, you never know if we get enough requests we may be able to carve out time to work on it ;)
