### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by RadekMikulkaAG** [firebase/quickstart-unity#1140]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.7
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: tgz file referenced by UPM 
  * Problematic Firebase Component: RealtimeDb, RemoteConfig
  * Other Firebase Components in use: RealtimeDb, RemoteConfig 
  * Additional SDKs you are using: Ironsource, Facebook, GooglePlay 
  * Platform you are using the Unity editor on: Windows 
  * Platform you are targeting: iOS + Android
  * Scripting Runtime: il2cpp 

Unity editor is freezing - https://tinyurl.com/yzcsghe9 This happens every 2nd attemp of starting playmode. 1st run is ok - but second (sometimes 3th) attemp will freeze unity forever. I made example script how to test it. Only think you need to do is put this script to any gameobject and press play -> turn on play mode -> start play mode again -> and Application.Reload dialog will appear and you have to kill Unity process to stop it. I found that it is happening only when I use parameter "TimeSpan.Zero" while fetching remote config (setting TimeSpan.Zero is necessary for us for testing purposes).

Possible walkaround what I found is use this, but it is not solution because it will kill ale firebase functions in editor and you have to restart unity to make them work again:
`
private void OnApplicationQuit()
        {
            FirebaseApp.DefaultInstance.Dispose();
            FirebaseDatabase.DefaultInstance.App.Dispose();
            FirebaseRemoteConfig.DefaultInstance.App.Dispose();
        }
`

Here is example code:

`void Start()
    {
        Test();
    }

    async void Test()
    {
        await FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
            
        });
        
        DatabaseReference reference = FirebaseDatabase.DefaultInstance.RootReference;
        await reference.GetValueAsync().ContinueWithOnMainThread(task =>
        {
            
        });
        
        FirebaseRemoteConfig reference2 = FirebaseRemoteConfig.DefaultInstance;
        await reference2.FetchAsync(TimeSpan.Zero).ContinueWithOnMainThread(task =>
        {
            FirebaseRemoteConfig.DefaultInstance.ActivateAsync();
        });
    }`

**Comment by paulinon** [comment]
Thanks for letting us know, @RadekMikulkaAG. The latest LTS version of the Unity editor is version 2020.3.18f1. Could you confirm if the issue persists there as well?

**Comment by RadekMikulkaAG** [comment]
I can confirm that unity no longer freezes in Unity 2020.3.18f1 - but there s still error 

`fetching failure: http code 400
UnityEngine.Debug:LogError (object)
Firebase.Platform.FirebaseLogger:LogMessage (Firebase.Platform.PlatformLogLevel,string) (at Z:/tmp/tmp.xDmPRxPPw2/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:95)
Firebase.LogUtil:LogMessage (Firebase.LogLevel,string) (at Z:/tmp/tmp.Ti0ckjuoMn/firebase/app/client/unity/proxy/LogUtil.cs:69)
Firebase.LogUtil:LogMessageFromCallback (Firebase.LogLevel,string) (at Z:/tmp/tmp.Ti0ckjuoMn/firebase/app/client/unity/proxy/LogUtil.cs:77)
Firebase.AppUtil:PollCallbacks () (at Z:/tmp/tmp.Ti0ckjuoMn/firebase/app/client/unity/proxy/AppUtil.cs:32)
Firebase.Platform.FirebaseAppUtils:PollCallbacks () (at Z:/tmp/tmp.Ti0ckjuoMn/firebase/app/client/unity/proxy/FirebaseAppUtils.cs:33)
Firebase.Platform.FirebaseHandler:Update () (at Z:/tmp/tmp.xDmPRxPPw2/firebase/app/client/unity/src/Unity/FirebaseHandler.cs:208)
Firebase.Platform.FirebaseMonoBehaviour:Update () (at Z:/tmp/tmp.xDmPRxPPw2/firebase/app/client/unity/src/Unity/FirebaseMonoBehaviour.cs:45)
`

and value of FirebaseRemoteConfig.DefaultInstance.Info.LastFetchStatus is "Failure"

**Comment by paulinon** [comment]
Hi @RadekMikulkaAG, 

I can't seem to replicate your issue with the information you've provided so far. In order to identify what's causing your issue, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate this behavior.
