### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by soup-soup605** [firebase/quickstart-unity#1142]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1.18f1
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Storage (Auth, Database, etc.)
  * Other Firebase Components in use: Auth,Database,Firestore (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:

Why does not finish?
```
await storageReference.Child(firebasePath).GetFileAsync(downloadPath,null,cancellationTokenSource.Token).ConfigureAwait(false);
```

How can I wait for finishing "GetFileAsync"?

Code:

```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;
using Firebase.Storage;

public class StorageManager
{
    private static StorageReference storageReference;
    private static CancellationTokenSource cancellationTokenSource;
    
    public static void init()
    {
        storageReference = FirebaseStorage.DefaultInstance.GetReferenceFromUrl("gs://********.appspot.com");
        cancellationTokenSource = new CancellationTokenSource();
    }
    
    public static void getData(string firebasePath,string downloadPath)
    {
        DownloadFile(firebasePath,Uri.UriSchemeFile + "://" + downloadPath).Wait();
    }
    
    private static async Task DownloadFile(string firebasePath,string downloadPath)
    {
        Debug.Log(String.Format("Download {0} to {1}",firebasePath,downloadPath));
        await storageReference.Child(firebasePath).GetFileAsync(downloadPath,null,cancellationTokenSource.Token).ConfigureAwait(false);
        Debug.Log(String.Format("FinishGetFileAsync {0}",firebasePath));
    }
}
```

Log:
```
unity           | Download (firebasePath) to (downloadPath)
NetworkRequest  | No App Check token for request.
```

**Comment by paulinon** [comment]
Hi @soup-soup605,

Usually, this makes use of the `ContinueWIthOnMainThread` method where you can check the result of your `GetFileAsync` function as seen [here](https://firebase.google.com/docs/storage/unity/download-files#download_to_a_local_file). 

Could you confirm if the code in the documentation applies to your use case? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate the issue.
