### ISSUE TITLE
Unity Firebase SDK 8.2.0: build failed. Couldn't resolve dependencies.

### ISSUE THREAD

**Issue by YuriiZhuk** [firebase/quickstart-unity#1143]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.30f
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: _____ Unity Package Manager (tgz)
  * Problematic Firebase Component: _____ (Remote Config)
  * Other Firebase Components in use: _____ (Analytics; Crashlytics;)
  * Additional SDKs you are using: _____ (Playfab; Facebook; AppsFlyer; Enhance)
  * Platform you are using the Unity editor on: _____ (Mac and Windows)
  * Platform you are targeting: _____ (Android and iOS)
  * Scripting Runtime: _____ (IL2CPP)

### [REQUIRED] Please describe the question here:

I'm trying to build an Android target. Build fails after updating Firebase SDK from 7.0.2 to 8.2.0. I'm using a custom Gradle template. Also, I updated the SDK using the "tgz" file type. The dependency resolver manager is on the 1.2.166 version. 
Packages manifest looks like:
`    "com.google.external-dependency-manager": "file:com.google.external-dependency-manager-1.2.166.tgz",
    "com.google.firebase.analytics": "file:com.google.firebase.analytics-8.2.0.tgz",
`
The log says:
`Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all task dependencies for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-config-unity:8.2.0.
     Required by:
         project :launcher > project :unityLibrary
      > Could not resolve com.google.firebase:firebase-config-unity:8.2.0.
         > Could not get resource 'https://jcenter.bintray.com/com/google/firebase/firebase-config-unity/8.2.0/firebase-config-unity-8.2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/firebase/firebase-config-unity/8.2.0/firebase-config-unity-8.2.0.pom'.
               > Read timed out`

**Comment by paulinon** [comment]
Hi @YuriiZhuk,

Could you try if going to Assets > External Dependency Manager > Android Resolver > Force Resolve makes a difference with your issue? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your issue so we can identify what's causing this behavior.

**Comment by YuriiZhuk** [comment]
> Hi @YuriiZhuk,
> 
> Could you try if going to Assets > External Dependency Manager > Android Resolver > Force Resolve makes a difference with your issue? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your issue so we can identify what's causing this behavior.

Hi, @paulinon 

I don't know how, but I've just run the force resolving and it helped me(I'd tried force resolving before but it didn't help me). Thank you.
