### ISSUE TITLE
is firebase auth plan to be supported in editor?

### ISSUE THREAD

**Issue by xyx2011** [firebase/quickstart-unity#115]
I implemented firebase auth in login screen via unity. it can only work after I build the app but does not work in editor. Is there a plan that firebase will firebase auth in editor eventually?

Thanks in advance

**Comment by stewartmiles** [comment]
We currently only support auth on mobile I'm afraid.  We have a load of feature requests always rolling in, if you add your voice to the folks who contact https://firebase.google.com/support/ describing your use case (it's really handy for us to understand how you would use this) then we may be able to prioritize it if we have enough requests.

Cheers,
Stewart
