### ISSUE TITLE
[Question] Unity standalone build puts google-services-desktop in StreamingAssets

### ISSUE THREAD

**Issue by ezzatmoussa** [firebase/quickstart-unity#1159]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.1.4
  * Firebase Unity SDK version: 11.0.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: google-services-desktop.json
  * Other Firebase Components in use: Auth/Database
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the question here:
Hello,

We are working on a windows standalone application, in which we are using Firebase.
And the issue we are facing is that the google-services-desktop.json file, which contains all Firebase configuration info, is easily accessible in the StreamingAssets folder.

Is there a solution to read it from another location or maybe hard code it?

I appreciate your help.

**Comment by AUEzzat** [comment]
Thanks, @DellaBitta I will try that out.
