### ISSUE TITLE
[FR] Make it possible to send an array of items in a parameter

### ISSUE THREAD

**Issue by revolt3r** [firebase/quickstart-unity#1167]
### Feature proposal

* Firebase Component: Analytics

Make it possible to send an array of items in a parameter (for example to handle Economy Transaction Events inside a game - so that one could specify the item Ids and the amount of items, in addition to transaction price and other data)

**Comment by nindim** [comment]
This would likely resolve this other ticket which has bene open for over 3 years: https://github.com/firebase/quickstart-unity/issues/713

**Comment by WitchK1ng** [comment]
I Would also love to see this feature land!

**Comment by argzdev** [comment]
Hi folks, to keep a single line of communication. I'll go ahead and close this thread. Feel free to continue your report on the prior quickstart thread #713. I'll reply back on that thread as soon as I get updates to share. Thanks!
