### ISSUE TITLE
Firebase Analytics not collect ARPU ARPPU

### ISSUE THREAD

**Issue by echeg** [firebase/quickstart-unity#117]
We integrate Firebase Analytics and Invites.
[Screenshot Unity/Plugins/Android](https://www.dropbox.com/s/u8lnkecxslnrnz3/Unity_2017-10-19_17-48-06.png?dl=0)

On Firebase WebConsole I see 387.000 active users, but zero ARPU, ARPPU, LTV etc.
[Screenshot from Console](https://www.dropbox.com/s/fdqdw81klynwtnl/chrome_2017-10-19_17-49-39.png?dl=0)  
What could be the reason that iap are not registered?(we have hundreds of purchases)

P.S. Manual events like Firebase.Analytics.FirebaseAnalytics.LogEvent("custom_progress_event", "percent", 0.4f) works fine.

**Comment by stewartmiles** [comment]
https://support.google.com/firebase/answer/6317517?hl=en

Yes, it sounds like IAP is not being tracked for your users.  If you open up a query with our support team on firebase.google.com/support they can help dig into this for you.

Cheers,
Stewart

**Comment by echeg** [comment]
https://support.google.com/firebase/answer/6392038?hl=en&ref_topic=6317497
