### ISSUE TITLE
[Bug] Crashlytics requiring iOS build support when usingAndroid platform

### ISSUE THREAD

**Issue by snorrsi** [firebase/quickstart-unity#1173]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.21f1
  * Firebase Unity SDK version: 8.3.0
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: Auth,Database, (Auth, Database, etc.)
  * Additional SDKs you are using: none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

When loading unity with Crashlytics package installed (generated from .tgz file) I get this error when I don't have iOS enabled build support enabled which should not be required.

For Android platform, iOS build support should not really be required.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
Error: Could not load signature of Firebase.Crashlytics.Editor.iOSPostBuild:SetupGUIDForSymbolUploads due to: Could not load file or assembly 'UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>

#### Relevant Code:

None needed. Just try to open Unity with Crashlytics package installed.

**Comment by paulinon** [comment]
Hi @snorrsi,

In order to use Crashlytics in your project, you have to import the .tgz files for both the External Dependency Manager and Firebase App as seen [here](https://developers.google.com/unity/archive#firebase_crashlytics). Could you verify if you have you have imported these files as well?

**Comment by snorrsi** [comment]
@paulinon apologies for late reply.. but yes, everything was included.
What I mean is that Crashlytics seems to be referencing Unity iOS specific classes which requires iOS build support in Unity even if building for Android project.
I was saving space on my device and was trying to skip installing iOS build support as building for Android and then up came this error.

**Comment by MephestoKhaan** [comment]
I am experiencing the same issue. Building something for Quest, I dont have iOS support installed (why would I need it) with this Unity instance
