### ISSUE TITLE
[Question] Deleted collection with "allow delete: if false"

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1175]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.18f1
  * Firebase Unity SDK version: 8.3.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Remote Config, Crashlytics, Auth
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

We got a user report that parts of his data vanished from one day to another. After checking his account-collection (holds all data related to a user) in the Firestore dashboard, I noticed that one collection was missing. This collection gets created on the first start of our app and users can't delete it through the app (security rule: `allow delete: if false;`).

I'm still trying to figure this out, but any input would be appreciated.

**Comment by paulinon** [comment]
Hi @Nyankoo,

So sorry to hear about this. It appears that is more related to the Firebase backend. You may raise this to [Firebase Support](https://firebase.google.com/support) where an agent can help you out.

With that, I'll be closing this for now.
