### ISSUE TITLE
[Bug] Notifications not received on app first starts after deleting and reinstalling on iOS device.

### ISSUE THREAD

**Issue by william821114** [firebase/quickstart-unity#1176]
### Please fill in the following fields:

  * Unity editor version: 2020.3.19f1
  * Firebase Unity SDK version: 8.5.0
  * Source you installed the SDK: .tgz
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Core, Analytics
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Windows, Mac
  * Platform you are targeting: **iOS**, Android (issues happening on iOS)
  * Scripting Runtime: IL2CPP

### Please describe the issue here:
The issue #820 still persists.
`FirebaseMessaging.TokenReceived` is being called twice on first launch after reinstalling app. In that case, app is not receiving notification. You have to hard close and re-open the app.
It is not happening, when this is first ever install on the particular device.

#### Steps to reproduce:

1. Run app on device which never install the same app before. `FirebaseMessaging.TokenReceived` is called once with token.
2. Send a test notification to the FCM Token via Firebase console. Notification received as expected.
3. Uninstall app and then reinstall it.
4. Run app, this time `FirebaseMessaging.TokenReceived` is called twice. First time with the token from previous installation. And a second later, `FirebaseMessaging.TokenReceived` called again with new token.
5. Send a test notification to the second FCM Token via Firebase console. No notification received.
6. Force quit the app and then re-open it. `FirebaseMessaging.TokenReceived` is called once and everything works fine. (Notification received)

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes. It can be reproduced from [cloud messaging quickstart](https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs).

What's the issue repro rate?
100%

#### Relevant Code:
[Sample project](https://github.com/william821114/FCM-Unity-sample) almost the same as [cloud messaging quickstart](https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs).

**Comment by paulinon** [comment]
Hi @william821114,

Thanks for reporting this. I was also able to replicate this issue as well using the quickstart, and I also noticed that `FirebaseMessaging.TokenReceived` was called twice after reinstalling the app. Let me consult this with the team.

**Comment by mahgo** [comment]
Any update on this? Do we know what the last version without this issue was?

**Comment by paulinon** [comment]
Hi @mahgo,

Version 8.8.0 of the Unity SDK points to [version 8.11.0 of the Apple SDK](https://firebase.google.com/support/release-notes/ios#fcm_1) which includes the fix for this issue. That being said, I'll be closing this issue.
