### ISSUE TITLE
[Bug] Analytics does not work on iOS if frameworks are not statically linked

### ISSUE THREAD

**Issue by p-lindberg** [firebase/quickstart-unity#1178]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.18f1
  * Firebase Unity SDK version: 8.6.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
  * Cocoapods version: 1.11.2
  * Xcode version: 13.1
  * MacOS version: 11.6

### [REQUIRED] Please describe the issue here:

After integrating Firebase Analytics into a project I'm working on, I discovered the following issues on iOS:
- No user-defined events gets reported, whereas the auto-reported events (session_start, user_engagement, etc) work fine. By user-defined events I mean those events that I am logging using `FirebaseAnalytics.LogEvent()`.
- `FirebaseAnalytics.SetUserId` and `FirebaseAnalytics.SetUserProperty` does not work.

The above was verified by:
- Using the DebugView in Firebase to view incoming events: only auto-reported events show up.
- Exporting all events to BigQuery and querying for distinct event names as well as user ids: only auto-reported event names are present, and all user ids are null.
- Checking the device logs while running the app in Xcode: absolutely _nothing_ is logged by Firebase when any of the above mentioned methods are called.

I then noticed that when the app starts, about 150 warnings of the following kind are printed to the log:

```
objc[2852]: Class FIRAAdExposureReporter is implemented in both /private/var/containers/Bundle/Application/2FDF37A0-448E-4A64-8018-80ECA33CF1D6/Test.app/Test (0x1023d9358) and /private/var/containers/Bundle/Application/2FDF37A0-448E-4A64-8018-80ECA33CF1D6/Test.app/Frameworks/UnityFramework.framework/UnityFramework (0x1061d9c00). One of the two will be used. Which one is undefined.
```

I found that enabling the option "Link frameworks statically" in the EDM4U iOS Resolver fixes both the warnings and the issues with Firebase Analytics. I can see how static linking resolves the duplicate implementation issue, but I'm uncertain as to why this is necessary, since the Firebase pods are only added to the UnityFramework target in the podfile. The podfile looks like this before applying the option:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '8.9.1'
  pod 'Firebase/Core', '8.9.1'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

And with "Link frameworks statically" the last line is updated to
```
use_frameworks! :linkage => :static
```

Now, I'm reporting this as a bug because the Firebase Unity SDK is ostensibly broken out-of-the-box because of this. As far as I can tell, there is no indication in any setup instructions or guides that this option needs to be enabled for things to work - and the option is disabled by default. Even worse, the SDK will build just fine and everything _seems_ to work until you notice that your custom events do not get reported on iOS.

I have verified that the exact same result is achieved when setting up the quickstart project according to the instructions given, so this is not specific to my project.

#### Steps to reproduce:

- Pull the quick-start repo
- Launch the analytics testapp
- Follow the instructions to add the Firebase SDK
- Build for iOS
- Observe that auto-reported events gets logged
- Observe that custom events do **not** get logged
- Toggle _Link frameworks statically_ on in iOS Resolver settings and rebuild
- Observe how everything works as expected.

**Comment by chkuang-g** [comment]
Though it is recommended to link pods statically, I think it is not a requirement.
https://firebase.google.com/docs/ios/link-firebase-static-dynamic

Perhaps something changed at iOS SDK level.  Let me consult with internal team about this.

**Comment by chkuang-g** [comment]
OK. I found an internal bug (b/196153528) about this matter. 

Simply put, to link pods statically by default, you will also need to generate a `dummy.swift` file like the following, or the Xcode project generated by Unity may not link other 3rd party libraries, ex. Facebook, properly.
```
import Foundation
```

This seems to be a feature request for EDM4U side.

On the other hand, I need to consult with iOS team to understand why dynamic linkage failed in this case.

**Comment by DaveMariner** [comment]
As an addendum - this also affects SDKs as far back as 7.1.0. 

Somewhat interestingly, there's at least one of our products where everything works just fine and we're (I believe) not linking statically - at least, not through the Podfile. Got more digging to do tomorrow.

**Comment by DaveMariner** [comment]
I did some more digging. It seems that adding '-ObjC' to 'OTHER_LDFLAGS' fixes the issue. We currently do this with a [PostProcessBuild] Editor script. 

@p-lindberg: If this is still an issue for you, this is our minimal standalone fix. 
@chkuang-g: Is something like this suitable for EDM? 


```
using UnityEditor;
using UnityEditor.Callbacks;
using System.IO;

#if UNITY_IOS
using UnityEditor.iOS.Xcode;
#endif

public static class PostBuild
{
    [PostProcessBuild]
    public static void OnPostprocessBuild(BuildTarget buildTarget, string path)
    {
#if UNITY_IOS
        string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";

        PBXProject proj = new PBXProject();
        proj.ReadFromString(File.ReadAllText(projPath));

        string target = proj.GetUnityMainTargetGuid();
        string projectGuid = proj.ProjectGuid();

        // Set a custom link flag
        proj.AddBuildProperty(target, "OTHER_LDFLAGS", "-ObjC");
#endif
    }
}

```

**Comment by nostek** [comment]
@DaveMariner 's solution worked for us, example code is missing a ''File.WriteAllText(projPath, proj.WriteToString());" in the end.

@p-lindberg thanks for reporting :)

**Comment by DaveMariner** [comment]
@nostek: Good catch - have added that into the example code for anyone else with the same issue. Glad it helped!

**Comment by abcjjy** [comment]
> I did some more digging. It seems that adding '-ObjC' to 'OTHER_LDFLAGS' fixes the issue. We currently do this with a [PostProcessBuild] Editor script.
> 
> @p-lindberg: If this is still an issue for you, this is our minimal standalone fix. @chkuang-g: Is something like this suitable for EDM?
> 
> ```
> using UnityEditor;
> using UnityEditor.Callbacks;
> using System.IO;
> 
> #if UNITY_IOS
> using UnityEditor.iOS.Xcode;
> #endif
> 
> public static class PostBuild
> {
>     [PostProcessBuild]
>     public static void OnPostprocessBuild(BuildTarget buildTarget, string path)
>     {
> #if UNITY_IOS
>         string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";
> 
>         PBXProject proj = new PBXProject();
>         proj.ReadFromString(File.ReadAllText(projPath));
> 
>         string target = proj.GetUnityMainTargetGuid();
>         string projectGuid = proj.ProjectGuid();
> 
>         // Set a custom link flag
>         proj.AddBuildProperty(target, "OTHER_LDFLAGS", "-ObjC");
>         File.WriteAllText(projPath, proj.WriteToString());
> #endif
>     }
> }
> ```

I'm experencing this issue today. The -ObjC flag doesn't help. 

Unity 2019.4.36
Firebase 8.8.0

**Comment by y-kamiya** [comment]
I has experienced this issue with
- Unity 2020.3.13
- firebase unity sdk 8.8.0

In my case,  event logs are triggered correctly only by removing other linker flag of `-framework FirebaseAnalytics` on Unity-iPhone target. 

```
proj.AddBuildProperty(target, "OTHER_LDFLAGS", "-ObjC");
```
I found that this leads to remove `$(inherited)` of other linker flag, so `-framework FirebaseAnalytics` is not inherited from xcconfig defined by Pods.

**Comment by albert-pixel** [comment]
Hi,

I have the same problem, and adding the -ObjC flag doesn't help.
I'm using the latest version of the SDK 8.10.1, and Unity 2019.4.38.

Predefined events are working fine.
Anyone still with the problem? Thanks!

**Comment by albert-pixel** [comment]
> > I did some more digging. It seems that adding '-ObjC' to 'OTHER_LDFLAGS' fixes the issue. We currently do this with a [PostProcessBuild] Editor script.
> > @p-lindberg: If this is still an issue for you, this is our minimal standalone fix. @chkuang-g: Is something like this suitable for EDM?
> > ```
> > using UnityEditor;
> > using UnityEditor.Callbacks;
> > using System.IO;
> > 
> > #if UNITY_IOS
> > using UnityEditor.iOS.Xcode;
> > #endif
> > 
> > public static class PostBuild
> > {
> >     [PostProcessBuild]
> >     public static void OnPostprocessBuild(BuildTarget buildTarget, string path)
> >     {
> > #if UNITY_IOS
> >         string projPath = path + "/Unity-iPhone.xcodeproj/project.pbxproj";
> > 
> >         PBXProject proj = new PBXProject();
> >         proj.ReadFromString(File.ReadAllText(projPath));
> > 
> >         string target = proj.GetUnityMainTargetGuid();
> >         string projectGuid = proj.ProjectGuid();
> > 
> >         // Set a custom link flag
> >         proj.AddBuildProperty(target, "OTHER_LDFLAGS", "-ObjC");
> >         File.WriteAllText(projPath, proj.WriteToString());
> > #endif
> >     }
> > }
> > ```
> 
> I'm experencing this issue today. The -ObjC flag doesn't help.
> 
> Unity 2019.4.36 Firebase 8.8.0

Did you find a fix?

**Comment by chkuang-g** [comment]
This should be fixed in the later version of Firebase SDK. I will close this for now.
