### ISSUE TITLE
Java class com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk not found

### ISSUE THREAD

**Issue by DavidVecorekAG** [firebase/quickstart-unity#1179]
### [REQUIRED] Please fill in the following fields:

* Unity editor version: 2020.3.20f1
* Firebase Unity SDK version: 8.6.1
* Source you installed the SDK: Unity Package Manager, .tgz from here http://developers.google.com/unity/archive
* Problematic Firebase Component: Crashlytics
* Other Firebase Components in use: Analytics, RemoteConfig, Firestore, Messaging
* Additional SDKs you are using: Facebook, GPGS, IronSource
* Platform you are using the Unity editor on: Windows
* Platform you are targeting: Android
* Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Iam getting error (and crash) at start of app:
"Java class com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk not found.  Please verify the AAR which contains the com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk class is included in your app."

I have com.google.firebase.firebase-crashlytics-ndk-18.2.4.aar in my project,
<package>com.google.firebase:firebase-crashlytics-ndk:18.2.4</package> and <file>Assets/Plugins/Android/com.google.firebase.firebase-crashlytics-ndk-18.2.4.aar</file> in my AndroidResolverDependencies

I think it has something to do with this because there is no error without Minify
https://firebase.google.com/support/release-notes/android#crashlytics-ndk_v18-2-4

**Comment by paulinon** [comment]
HI @DavidVecorekAG,

Thanks for reporting this issue. Could you provide the steps needed in order to replicate this issue so that we can identify what's causing this?

**Comment by pedro15** [comment]
Same issue here
Unity 2020.3.16f1 
Firebase SDK 8.6.1
Build success but error in console as soon as the sdk initializes

**Comment by pedro15** [comment]
> 
> 
> HI @DavidVecorekAG,
> 
> Thanks for reporting this issue. Could you provide the steps needed in order to replicate this issue so that we can identify what's causing this?

I have the same problem, you only have to setup & initialize firebase with Firebase analytics and firebase crashlytics.

1. Import Firebase Analytics, and firebase crashlytics, and setup a test project.
2. Resolve android dependencies using the External dependency manager.
3. Create a script and initialize the SDK using CheckAndFixDependenciesAsync:
`
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
            {
                var dependencyStatus = task.Result;
                if (dependencyStatus == Firebase.DependencyStatus.Available)
                {
                    FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
                    Debug.LogFormat("<color=cyan>[OK] Firebase Init completed | Crashlytics Enabled: {0}</color>", Crashlytics.IsCrashlyticsCollectionEnabled);
                }
                else
                {
                    Debug.LogError(System.String.Format(
                      "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                }
            });
`
4. Attach it to a empty game object and save the scene, and add it to the build settings.
5. Build & run the game (attach the unity console to the player):
Expected result:
No errors at all.
Actual result:
Error thrown as described in this post.

**Comment by DavidVecorekAG** [comment]
> > HI @DavidVecorekAG,
> > Thanks for reporting this issue. Could you provide the steps needed in order to replicate this issue so that we can identify what's causing this?
> 
> I have the same problem, you only have to setup & initialize firebase with Firebase analytics and firebase crashlytics.
> 
> 1. Import Firebase Analytics, and firebase crashlytics, and setup a test project.
> 2. Resolve android dependencies using the External dependency manager.
> 3. Create a script and initialize the SDK using CheckAndFixDependenciesAsync (you can use the sample code from the google website: https://firebase.google.com/docs/unity/setup)
> 4. Attach it to a empty game object and save the scene, and add it to the build settings.
> 5. Build & run the game (attach the unity console to the player):
>    Expected result:
>    No errors at all.
>    Actual result:
>    Error thrown as described in this post.

Are you able to replicate the issue based on this?

**Comment by paulinon** [comment]
Hi @DavidVecorekAG,

I haven't been able to replicate the issue using the provided steps, but I should point out that I'm using [version 8.6.2](https://firebase.google.com/support/release-notes/unity#version_862_-_november_19_2021) of the SDK. Could you try if the issue persists using that version?

**Comment by nvdg** [comment]
I received the same issue after upgrading from 7.2 to 8.6.2.
Adding this to the proguard-user.txt file fixed it for me:

-keep class com.google.firebase.crashlytics.ndk.** { *; }

**Comment by anskuratov** [comment]
Faced the same problem upgrading to 8.6.2 version.

That works for me, thanks! 👍 

> I received the same issue after upgrading from 7.2 to 8.6.2. Adding this to the proguard-user.txt file fixed it for me:
> 
> -keep class com.google.firebase.crashlytics.ndk.** { *; }
