### ISSUE TITLE
[Bug] FirebaseAuth Offline Issue

### ISSUE THREAD

**Issue by henry-dreamo** [firebase/quickstart-unity#1180]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.16f1
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: CloudFunctions, Analytics, Crashlytics, Installation, Storage
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android,iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I apologize in advance for my poor English skills.

Reproduced in both the Unity editor and iOS builds.
After Firebase.FirebaseApp.CheckAndFixDependenciesAsync() ended, Auth initialization started when dependencyStatus is Firebase.DependencyStatus.Available.
If there is no Firebase.Auth.FirebaseAuth.DefaultInstance.CurrentUser, user information is obtained through Firebase.Auth.FirebaseAuth.DefaultInstance.SignInAnonymouslyAsync, and if CurrentUser is present, user information is obtained by determining that the user is logged in.

At first execution, if you try to log in while offline, an exception occurs and you cannot log in properly. So I compared Application.internetReachability and modified it to try to log in while online and it seemed to work.

"Unauthenticated or Permission Denied" error occurs when calling Storage and Cloud Function intermittently while offline.

The security rules for Storage and Cloud Function are as follows.
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read: if false;
      allow write: if request.auth != null;
    }
  }
}

The problem is that after intermittently failing offline, closing the app and restarting it works fine.

What appears to be a similar issue (https://github.com/firebase/quickstart-unity/issues/914) has been closed for further information.

#### Steps to reproduce:

After Auth authentication offline at the first execution, upload to Storage or call CloudFunction's method.
issue repro rate : 10%(sometimes)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Thanks for reporting this, @henry-dreamo. 

Firebase functionalities aren't usually expected to work without an internet connection. In order to identify what's causing your issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps needed to replicate this behavior?

**Comment by henry-dreamo** [comment]
@paulinon 
I originally thought that firebase was designed to work even when there is no internet connection.
Due to the difficulty of providing project information, I will close this issue.
