### ISSUE TITLE
[FR] - Allow for custom suffix when generating a short link

### ISSUE THREAD

**Issue by chris-o3h** [firebase/quickstart-unity#1182]
<!-- DO NOT DELETE
validate_template=true
template_path=.github/ISSUE_TEMPLATE/feature-request.md
->

### Feature proposal

* Firebase Component: Dynamic Link (generation)
Describe your use case and/or feature request here.

After reading https://firebase.googleblog.com/2018/06/3-ways-to-customize-your-firebase.html 

I would like to generate a short dynamic link by providing the suffix myself.

For example, instead of this to deep link to a particular user in my social app named _StackOverFlo_
https://mygame.page.link/B7vVu

I would like to be able to provide a custom suffix to the API that generates the link. For example:
https://mygame.page.link/StackOverFlo

(So long as _StackOverFlo_ is unique of course).

Forgive me if I do not see how to currently do this, I would have expected the `DynamicLinkComponents` class to expose this.
Thanks!

**Comment by chris-o3h** [comment]
### Feature proposal

* Firebase Component: Dynamic Link (generation)
Describe your use case and/or feature request here.

After reading https://firebase.googleblog.com/2018/06/3-ways-to-customize-your-firebase.html 

I would like to generate a short dynamic link by providing the suffix myself.

For example, instead of this to deep link to a particular user in my social app named _StackOverFlo_
https://mygame.page.link/B7vVu

I would like to be able to provide a custom suffix to the API that generates the link. For example:
https://mygame.page.link/StackOverFlo

(So long as _StackOverFlo_ is unique of course).

Forgive me if I do not see how to currently do this, I would have expected the `DynamicLinkComponents` class to expose this.
Thanks!

**Comment by paulinon** [comment]
Hi @chris-o3h,

In order to achieve this, you can [set up a custom domain](https://firebase.google.com/docs/dynamic-links/custom-domains) for your dynamic links so that you can have control over your links' branding. Could you confirm if this solution works for you? If not, please provide a detailed use case for this feature you have in mind.

**Comment by chris-o3h** [comment]
@paulinon Good to know. Thanks. We are planning on custom domain support in an upcoming sprint.

However I'm concerned that this won't give us a fully qualified URL rather, just some custom prefixes. I guess we will see when we test drive it.
Cheer.s

**Comment by paulinon** [comment]
Thanks for letting us know, @chris-o3h. With that, I'll be closing this for now. 

If setting up custom domains isn't suitable for your case, let us know by leaving a comment so that we can reopen this ticket.
