### ISSUE TITLE
Dynamic Links opens both app and webpage, focus on webpage and app in the background

### ISSUE THREAD

**Issue by dioniguerra** [firebase/quickstart-unity#1183]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.28f1
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Dynamic Links
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Hi, I have create a simple URL link via Dynamic Links in Firebase Console and added the associated domain to my iOS app, however, when tapping the link in my test device, where I have my app installed (via Test Flight), the link opens my app and also Safari under a new tab which brings me to the App Store to download my app. My app is now in the background. 

I am wondering whether this is a side effect of Test Flight, or expected behaviour? I fear not. The desired behaviour is the link to open the app ONLY if is already installed. Can you please clarify?

**Comment by paulinon** [comment]
Hi @dioniguerra,

Thanks for reporting this. In order to identify what's causing this, could you provide the complete steps you performed before facing this issue? Could you also confirm if this behavior persists when the app is built directly from Xcode?

**Comment by dioniguerra** [comment]
Hi @paulinon Thanks for coming back to us, and actually on further review, this issue is not an artefact of Firebase. Dynamic Links is working as expected. Sorry for for the spam. This issue can be closed
