### ISSUE TITLE
[Firestore crash 100% on iOS] 

### ISSUE THREAD

**Issue by tamngonesv030** [firebase/quickstart-unity#1186]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _2019.3.2f1
  * Firebase Unity SDK version: ___8.5.0__
  * XCode: 12.0
  

### [REQUIRED] Please describe the issue here:
I alway crash when run on iOS device.
I receive the code native crash on: 

UnityFramework`firebase::firestore::DocumentSnapshotInternal::ConvertObject:
    0x104588a84 <+0>:   sub    sp, sp, #0xc0             ; =0xc0 
    0x104588a88 <+4>:   stp    x24, x23, [sp, #0x80]
    0x104588a8c <+8>:   stp    x22, x21, [sp, #0x90]
    0x104588a90 <+12>:  stp    x20, x19, [sp, #0xa0]
    0x104588a94 <+16>:  stp    x29, x30, [sp, #0xb0]
    0x104588a98 <+20>:  add    x29, sp, #0xb0            ; =0xb0 
    0x104588a9c <+24>:  mov    x19, x8
    0x104588aa0 <+28>:  movi.16b v0, #0x0
    0x104588aa4 <+32>:  stp    q0, q0, [sp, #0x50]
    0x104588aa8 <+36>:  mov    w11, #0x3f800000
    0x104588aac <+40>:  str    w11, [sp, #0x70]
    0x104588ab0 <+44>:  ldr    w8, [x1]
    0x104588ab4 <+48>:  cbz    w8, 0x104588b48           ; <+196>
    0x104588ab8 <+52>:  mov    x20, x2
    0x104588abc <+56>:  mov    x21, x1
    0x104588ac0 <+60>:  mov    x22, x0
    0x104588ac4 <+64>:  mov    x23, #0x0
    0x104588ac8 <+68>:  mov    x24, #0x0
    0x104588acc <+72>:  ldr    x8, [x21, #0x8]
->  0x104588ad0 <+76>:  ldr    x0, [x8, x23]
    0x104588ad4 <+80>:  add    x8, sp, #0x38             ; =0x38 
    0x104588ad8 <+84>:  bl     0x104aa26f0               ; symbol stub for: firebase::firestore::nanopb::MakeString(pb_bytes_array_s const*)

**Comment by paulinon** [comment]
Hi @tamngonesv030,

In order to identify what's causing this, could you provide the complete steps to replicate the issue?

Additionally, version 8.8.0 of the Unity SDK hasn't been released as of writing. Could you try our latest SDK version ([8.6.2](https://firebase.google.com/support/release-notes/unity#version_862_-_november_19_2021)) and see if the issue persists?

**Comment by tamngonesv030** [comment]
> Hi @tamngonesv030,
> 
> In order to identify what's causing this, could you provide the complete steps to replicate the issue?
> 
> Additionally, version 8.8.0 of the Unity SDK hasn't been released as of writing. Could you try our latest SDK version ([8.6.2](https://firebase.google.com/support/release-notes/unity#version_862_-_november_19_2021)) and see if the issue persists?

Sorry...this problem on Firebase Unity SDK 8.5.0
And on version 8.6.2, it was fixed. 
Thank u so much.

**Comment by tamngonesv030** [comment]
> Hi @tamngonesv030,
> 
> In order to identify what's causing this, could you provide the complete steps to replicate the issue?
> 
> Additionally, version 8.8.0 of the Unity SDK hasn't been released as of writing. Could you try our latest SDK version ([8.6.2](https://firebase.google.com/support/release-notes/unity#version_862_-_november_19_2021)) and see if the issue persists?

Sorry...this problem on Firebase Unity SDK 8.5.0
And on version 8.6.2, it was fixed.
Thank u so much.
