### ISSUE TITLE
Firebase Analytics and Google Ads not reporting campaign events

### ISSUE THREAD

**Issue by dioniguerra** [firebase/quickstart-unity#1187]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.28f1
  * Firebase Unity SDK version: 8.2.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: DyamicLinks, InAppMessaging, FCM, RemoteConfig
  * Additional SDKs you are using: Node
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

Hi,

We have recently integrated Firebase SDK into our apps. However, we have an outstanding issue where as Google Ads campaigns are not showing at all on the Google Ads side, nor we see campaign events in the Firebase analytics dashboard. 

We are hoping you can help us troubleshoot this issue from the Firebase SDK integration side.

Simple overview of our integration as follow:

Since we work in the kids space, as per Apple guidelines, we cannot use any frameworks where the IDFA is exposed, so we integrate Firebase Analytics using 

`pod 'Firebase/AnalyticsWithoutAdIdSupport'`

We enable data collection as per documentation, as follow

`[FIRAnalytics setAnalyticsCollectionEnabled:YES];`

Also, it is worth noting we do not embed the AdSupport.framework for the same reason. Saying that, we expect attribution for Google Ad campaign still work, as per your recommendation, via `SKAdNetwork`. Given your documentation SKAdNetwork should be automatically enabled, as per this configuration in my `Info.plist` file:

`GOOGLE_ANALYTICS_REGISTRATION_WITH_AD_NETWORK_ENABLED YES`

However, there is no way for me to verify this on my end. Perhaps we can start there?

Bellow is a copy of my Unity iOS Pod file for your reference:

```source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/AnalyticsWithoutAdIdSupport', '8.6.0'
  pod 'Firebase/DynamicLinks', '8.6.0'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Messaging', '8.6.0'
  pod 'Firebase/RemoteConfig', '8.6.0'
end

**Comment by paulinon** [comment]
Hi @dioniguerra,

Upon analysis, it appears that you would like to confirm how the backend behaves while handling your Google Ad campaigns. For issues like this, you may reach out to [Firebase Support](https://firebase.google.com/support) where a support agent can help you out. That being said, I'll be closing this for now.
