### ISSUE TITLE
[Bug] google-services.json is not found

### ISSUE THREAD

**Issue by IgorGalimski** [firebase/quickstart-unity#1188]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.20f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: Core 
  * Other Firebase Components in use: Analytics, Config, Crashlytics, Installation
  * Additional SDKs you are using: Admob, Facebook, Appsflyer
  * Platform you are using the Unity editor on: Mac 
  * Platform you are targeting: Android, iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
 Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly

JSON is located in Assets directory and in the project
<img width="437" alt="Screenshot 2021-11-23 at 4 56 44 PM" src="https://user-images.githubusercontent.com/19680568/143048008-28c9bcc4-681b-4662-93a4-1e8514660952.png">

Also, the issue doesn't appear on the previous version 7.2.0

**Comment by paulinon** [comment]
Hi @IgorGalimski,

Thanks for reporting this. I see that you provided a screenshot of an Android Studio project hierarchy. Does this mean that you're building for Android?

Additionally, could you confirm if this issue is reproducible when using our [quickstart](https://github.com/firebase/quickstart-unity)?

**Comment by IgorGalimski** [comment]
Hi, @paulinon
Thanks for the fast reply
Yes, this issue appears only for Android
I've tried, but all these sample projects don't contain Firebase API
<img width="715" alt="Screenshot 2021-11-23 at 8 14 28 PM" src="https://user-images.githubusercontent.com/19680568/143081127-995c61b7-14a8-47e0-afd3-7f828cc9695f.png">

**Comment by IgorGalimski** [comment]
@paulinon 
Hi!
I've tried to create a new unity project, import FirebaseCrashlytics_8.6.2.unitypackage, and start Firebase. And I see the same error, regardless of google-services.json is in streaming assets Unity's directory
I continue using Unity2020.3.20f1 and build for Android. Please, check out the attached file. I removed the json from the project for security reasons

https://www.dropbox.com/s/rshtb0nq5k88k7q/Archive.zip?dl=0

![Screenshot 2021-11-24 at 10 47 08 AM](https://user-images.githubusercontent.com/19680568/143205142-8f6171ef-e6eb-442a-88bd-38c05727535c.png)

**Comment by paulinon** [comment]
Hi @IgorGalimski,

After downloading the `google-services.json` for your app, it should be placed under the `Assets` folder of your Unity project, not `StreamingAssets`. Once this is done, a desktop version of your config file will be generated which can be found in `Assets` > `StreamingAssets`.

Here's our [documentation](https://firebase.google.com/docs/unity/setup#add-config-file) for reference. I look forward to your results.

**Comment by IgorGalimski** [comment]
@paulinon 
Yes, I did this. But anyway I see the exception that google-services.json not found

**Comment by paulinon** [comment]
Hi @IgorGalimski,

I haven't been able to replicate your issue so far. Here are the steps I performed with the sample project you provided:
1. Download the `google-services.json` file and place it in the Assets folder.
2. Go to `Assets` > `Scenes` > `SampleScene` and press Play (Error message is not present in the Unity console).
3. Export Unity project to be imported in Android Studio.
4. Run the app (Error message is not present in the logcat).

Are there any steps that I've missed? Additionally, could you try these steps and see if you're facing the issue?

**Comment by IgorGalimski** [comment]
Hi @paulinon 

I did the same, but still see the issue

<img width="695" alt="Screenshot 2021-11-24 at 12 27 39 PM" src="https://user-images.githubusercontent.com/19680568/143221233-6f8db23c-c359-4100-a6f3-2465eca4c2c3.png">

![Screenshot 2021-11-24 at 12 28 29 PM](https://user-images.githubusercontent.com/19680568/143221457-5236f2bc-ec9b-4fe6-9486-7f712eff1489.png)

**Comment by paulinon** [comment]
Hi @IgorGalimski,

This behavior seems unusual. Could you confirm if you're facing the same error message in the Unity editor?

Could you also make use of our quickstart and see if the issue persists there as well? You simply need to add your `google-services.json` file and the appropriate Firebase SDK which can be found [here](https://firebase.google.com/download/unity).

**Comment by IgorGalimski** [comment]
Hi @paulinon 
I've tried to take a package from dotnet4 folder, but still face the same issue
Is it possible to initialize Firebase without this json? I've tried using AppOptions, but it didn't help

**Comment by paulinon** [comment]
Hi @IgorGalimski,

The `google-services.json` file is an essential part of your project for you to use Firebase. I have found a [thread](https://forum.unity.com/threads/failed-to-read-firebase-options-from-the-apps-resources.833944/) that talks about this issue, and some developers resolved this by adding a few lines of code in their `mainTemplate.gradle` file or renaming their Assets/Plugins/Android/Firebase folder to Assets/Plugins/Android/Firebase.androidlib. Could you try if either solution works for you?

**Comment by IgorGalimski** [comment]
Hi @paulinon 
I don't have googleservices.xml file

**Comment by paulinon** [comment]
Hi @IgorGalimski,

I can see that in the thread I provided, and it's possible that the author meant `google-services.xml`. Do you have this file in your implementation? 

Have you tried modifying the `mainTemplate.gradle` file or renaming the Firebase folder like I previously mentioned? If so, has either of these resolved the issue?

**Comment by Guidanel** [comment]
One thing that may seem stupid but that actually solved the problem for me was to restart Unity. After restarting inside Assets/Plugins/Android a new folder FirebaseApp.androidlib was created and then the "google-services.json is not found" issue was fixed.
