### ISSUE TITLE
[Question] How to Enable developer mode in the latest RemoteConfig?

### ISSUE THREAD

**Issue by revolt3r** [firebase/quickstart-unity#1192]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.21f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: .tgz files in Packages folder
  * Problematic Firebase Component: RemoteConfig
  * Other Firebase Components in use: A bunch of them
  * Additional SDKs you are using: not important
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:
From documentation:
`To enable developer mode, which can be used to disable throttling during development, you can use the FirebaseRemoteConfig.Setting property, setting a new ConfigSettings with IsDeveloperMode set to true.`
This doesn't seem to exist anymore. What's the new way to do this? Would be cool if you could update the documentation or/and the example.

**Comment by paulinon** [comment]
Hi @revolt3r,

Thanks for bringing this to our attention. According to this [blog post](https://firebase.googleblog.com/2021/03/migrating-to-new-remote-config-for-games-sdk.html), `IsDeveloperMode` has no effect. This can be omitted, and `MinimumFetchInternalInMilliseconds` should be adjusted instead.

I'll be marking this as a bug for now. We'll get back to you as soon as we have updates.

**Comment by cynthiajoan** [comment]
Hi @revolt3r, we are getting rid of the IsDeveloperMode property and using MinimumFetchInternalInMilliseconds is the approach going forward. We will update the documentation to clarify the intended behavior. Thanks!

**Comment by revolt3r** [comment]
Got it, thanks!
