### ISSUE TITLE
[Question]  CI best practices

### ISSUE THREAD

**Issue by MephestoKhaan** [firebase/quickstart-unity#1195]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.4.12f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK:  Unity Package Manager
  * Problematic Firebase Component: None
  * Other Firebase Components in use: Auth, Firestore, Analytics, Crashlytics
  * Additional SDKs you are using: Oculus SDK
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android (Quest)
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the question here:

Creating a Oculus Quest project with  Firebase (specially interested in  Auth, Firestore, Analytics & Crashlytics.
The project will be built in a MAc machine using Jenkins and it is stored in Github.
I already saw that the way forward for me was to use .tgz  as the .unitypackage had some massive files that won't go into the GitHub repo. 
My question is: Can I ignore everything generated by the "Resolver" and REplicate it somewhoe in the Jenkins machine when doing a build, really want to keep the repo as clean as possible but I am not sure about the best practice here.

PS: Also having problems since I don't have iOS support installed and it complains in some dlls, but that is a different story

**Comment by paulinon** [comment]
Hi @MephestoKhaan,

For your implementation, I would recommend a process similar to the quickstart. Specifically, you exclude the Firebase SDK in your repository, and you only import this once you're in your Jenkins machine and you're about to build your app.

I'll be closing this for now. Let me know if an issue arises or if this solution isn't suitable for your use case.

**Comment by a-maurice** [comment]
For some additional info, you can look at https://github.com/firebase/firebase-unity-sdk/blob/main/scripts/gha/build_testapps.py which is the logic we are using to automate building Unity testapps, which requires installing the built unitypackages.
