### ISSUE TITLE
[Bug] DllNotFoundException: Unable to load DLL 'FirebaseCppApp-8_6_2'

### ISSUE THREAD

**Issue by jjy40130** [firebase/quickstart-unity#1199]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.21f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: App and Auth (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows 11 (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

Sry, I couldn't understand because i'm not good at english. 

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Programs that work well on Windows but when i run it on android it throws an error.

```
2021/12/05 17:11:16.894 18783 1712 Error Unity DllNotFoundException: Unable to load DLL 'FirebaseCppApp-8_6_2': The specified module could not be found.
2021/12/05 17:11:16.894 18783 1712 Error Unity   at Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate applicationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate arithmeticDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate divideByZeroDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate indexOutOfRangeDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidCastDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate invalidOperationDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate ioDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate nullReferenceDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate outOfMemoryDelegate, Firebase.AppUtilPINVOKE+SWIGExceptionHelper+ExceptionDelegate overflowDelegate,
2021/12/05 17:11:16.918 18783 1724 Error Unity DllNotFoundException: Unable to load DLL 'FirebaseCppApp-8_6_2': The specified module could not be found.
2021/12/05 17:11:16.918 18783 1724 Error Unity   at Firebase.AppUtilPINVOKE.SetLogFunction (Firebase.LogUtil+LogMessageDelegate jarg1) [0x00000] in <00000000000000000000000000000000>:0 
2021/12/05 17:11:16.918 18783 1724 Error Unity   at Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) [0x00000] in <00000000000000000000000000000000>:0 
2021/12/05 17:11:16.918 18783 1724 Error Unity   at Firebase.LogUtil.Finalize () [0x00000] in <00000000000000000000000000000000>:0 
2021/12/05 17:11:16.918 18783 1724 Error Unity System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
2021/12/05 17:11:16.918 18783 1724 Error Unity 
```

And /Assets/Plugins/IOS/Firebase/ has libFirebaseCppApp.a and libFirebaseCppAUth.a, but there is no lib file in /Assets/Plugin/Android/Firebase/ so i thought that EDM -> Android Resolver -> Force Resolve would solve the problem, but when I Force Resolve, it fails with the message 'Your application will not run, see the log for details.'

```
Extracting Assets/Plugins/Android/com.google.firebase.firebase-installations-interop-17.0.0.aar () to C:\Project\UnityGames\SCP-ML\Temp\0amn9e3a.9a0\com.google.firebase.firebase-installations-interop-17.0.0
Processing Assets/Plugins/Android/com.google.firebase.firebase-measurement-connector-19.0.0.aar
ProcessAar Assets/Plugins/Android/com.google.firebase.firebase-measurement-connector-19.0.0.aar
Extracting Assets/Plugins/Android/com.google.firebase.firebase-measurement-connector-19.0.0.aar () to C:\Project\UnityGames\SCP-ML\Temp\edvaw7tt.j6b\com.google.firebase.firebase-measurement-connector-19.0.0
Reporting analytics data: /androidresolver/resolve/gradle/processaars/success?numPackages=50&unityVersion=2020.3.21f1&unityPlatform=WindowsEditor&installSource=unitypackage&version=1.2.167&scope= 'Android Resolver: Gradle Resolve: Process AARs Succeeded'
```

anyone help me..

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

Sry i can't share my project

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
private void Awake() => _auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
```

**Comment by paulinon** [comment]
Hi @jjy40130,

Thanks for reporting this issue. In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project? If that's not possible, could you verify if this can be replicated using the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp)?

**Comment by jjy40130** [comment]
Thanks for Answer.

I confirmed that it works well in the minimal, reproducible example. There seems to be a problem with my project.
I gonna find problem with my project.
