### ISSUE TITLE
Firebase 4.2.1 can't work on android.

### ISSUE THREAD

**Issue by newaxekub** [firebase/quickstart-unity#120]
I use Unity 2017.2.0f3 it work when run on PC, But when I build it to apk it not work.

> void SetupDatabase()
    {
        showText.text = "A";
        FirebaseApp app = FirebaseApp.DefaultInstance;
        showText.text = "B";
        app.SetEditorDatabaseUrl("https://........firebaseio.com/"); // my url
        showText.text = "C";
        if (app.Options.DatabaseUrl != null)
        {
            showText.text = "D";
            app.SetEditorDatabaseUrl(app.Options.DatabaseUrl);
            showText.text = "E";
        }
        showText.text = "F";
    }

I used this code to check it, On PC showText can show "F", but on android showText stop at "A"
I think something wrong with "FirebaseApp app = FirebaseApp.DefaultInstance;"

**Comment by PathToLife** [comment]
We need some more information.

Please watch some youtube videos on how to get debug logs on an android device

"adb logcat -s unity"

**Comment by danielenriquez** [comment]
Hi guys, dot the same problem Unity3d 2017.2.0f3 (64bit) and Firebase 4.2.1.

My code:
FirebaseApp.DefaultInstance.SetEditorP12FileName("xxxxxxxxxxxxxxx-admin-sdk.p12");        FirebaseApp.DefaultInstance.SetEditorServiceAccountEmail("xxxxxxxxxxxxxxx.iam.gserviceaccount.com");
        FirebaseApp.DefaultInstance.SetEditorP12Password("notasecret");
        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available) {
                InitializeFirebase();
            } else {
                Debug.LogError(
                  "Could not resolve all Firebase dependencies: " + dependencyStatus);
            }
        });

I'm using service account to connect, It works perfect on Unity Editor when I run the app. But when I generate the APK and install it on the android device, when I run the app the LogCat give me this error:

11-22 21:23:58.819: E/Unity(5835): Firebase.Database.Internal.Core.ValueEventRegistration:FireCancelEvent(DatabaseError)
11-22 21:23:58.819: E/Unity(5835): Firebase.Database.Internal.Core.View.CancelEvent:Fire()
11-22 21:23:58.819: E/Unity(5835): Firebase.Database.Internal.Core.View.Runnable30:Run()

Thanks in advance....

**Comment by stewartmiles** [comment]
The editor URL will override the settings in AppOptions.

See
https://github.com/firebase/quickstart-unity/blob/master/database/testapp/Assets/TestApp/UIHandler.cs#L70

So you should only use the editor methods just in the editor.

Cheers,
Stewart

**Comment by danielenriquez** [comment]
Hi Stewart.
Thanks for you reply. Your right don't need the editor methods on devise release.
But also I had couple mistakes, finally I fixed.
For some reason it is not enough have setting up the service account on you project to read/write data from Firebase Real-time Database. It works on Unity Editor when you run the game. But when you isntall the APK on mobile device (Android), App(Game) has to authenticate a valid Firebase user. 

I created a user signing method EMAIL/PASSWORD on Firebase console. then I did the authentication on may app using Firabase Authetication Unity Package, and Boila...it works.
When user is been authenticate on Firebase, the Firebase system automatically change the RealTime database rules to TRUE
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
} 
https://firebase.google.com/docs/database/unity/start

My working code, even on Unity Editor and on mobile device:

    void Awake() {
        //Using Firebase SDK
        //This is needed only for the unity editor
        FirebaseApp.DefaultInstance.SetEditorP12FileName("xxxxxxxxxxxxxxxxxxx-admin-sdk.p12");
        FirebaseApp.DefaultInstance.SetEditorServiceAccountEmail("xxxxxxxxxxxxxxxx@yyyyyyyyyyyyyyyyy.gserviceaccount.com");
        FirebaseApp.DefaultInstance.SetEditorP12Password("notasecret");
        //--------------------------------------

        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
            dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available) {
                InitializeFirebase();
            } else {
                Debug.LogError(
                  "Could not resolve all Firebase dependencies: " + dependencyStatus);
            }
        });
    }
    // Initialize the Firebase database:
    protected virtual void InitializeFirebase() {
        FirebaseApp app = FirebaseApp.DefaultInstance;
        // NOTE: You'll need to replace this url with your Firebase App's database
        // path in order for the database connection to work correctly in editor

        //This is needed only for the unity editor
        app.SetEditorDatabaseUrl("https://xxxx.yyyyyyyyy.com/");
        if (app.Options.DatabaseUrl != null) app.SetEditorDatabaseUrl(app.Options.DatabaseUrl);
        //--------------------------------------
        Firebase.Auth.FirebaseAuth auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
        auth.SignInWithEmailAndPasswordAsync("mail@mail.com", "strongpasswrod").ContinueWith(task => {
            if (task.IsCanceled) {
                Debug.LogError("SignInWithEmailAndPasswordAsync was canceled.");
                return;
            }
            if (task.IsFaulted) {
                Debug.LogError("SignInWithEmailAndPasswordAsync encountered an error: " + task.Exception);
                return;
            }
            Firebase.Auth.FirebaseUser newUser = task.Result;
            Debug.LogFormat("User signed in successfully: {0} ({1})",
                newUser.DisplayName, newUser.UserId);
            //Getting client id for FB using device id
            FirebaseDatabase.DefaultInstance.GetReference("node1").Child(node2).Child("node3")
            .ValueChanged += HandleChanged;
        });
    }
Note: password should be strong.
Don't forget do a sign out on destroy method, otherwise you will get and error next time you try to connect.

auth.SignOut();

**Comment by mkotajny** [comment]
Solution works perfect !

After another update of Unity Firebase SDK (into version 5.3.0) I was having exactly the same issue.
(Connection into Firebase was working fine on the Unity Editor, but was crashing on Android).

I don't know why, but everything started to works fine, after I've implemented final part of your solution above: auth.SignInWithEmailAndPasswordAsync (didn't mentioned here https://firebase.google.com/docs/database/unity/start).  

Respect for your suggestion @danielenriquez  !

(thank you)
