### ISSUE TITLE
[Bug] fetching failure: http code 400 in Unity Editor

### ISSUE THREAD

**Issue by ORibn-dev** [firebase/quickstart-unity#1202]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.16f1, 2019.4.33f1
  * Firebase Unity SDK version: 8.1.0, 8.6.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Analytics, Database, Storage, Firestore
  * Additional SDKs you are using: Facebook, Appodeal
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

This issue was never fixed:
(https://github.com/firebase/quickstart-unity/issues/1127)
I also reported it some time ago, other folks also experienced it and reported it on issuetracker, but still no solution, nothing.

I managed to fix editor freeze after **fetch error 400** by updating Unity to 2019.4.33f1 version because Unity stated they fixed this freeze in other versions, but **fetch error 400** is still present  in most cases when I initialize Firebase in Editor Play mode. Remote Config works on Android build without problems so far, sometimes it works once in 10 or so attempts in Unity Editor, but because it mostly doesn't work in Unity Editor it's impossible to test it there. I tried to reinstall Firebase with the latest version, tried both Unity 2019.4.16f1 and 2019.4.33f1, the issue is still there. 

Is there any way to fix this?

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
90%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Install Remote Config, Analytics, Database, Storage, Firestore, use code below to initialize Firebase and play.

Fetch result in 9 attempts or so out of 10:

fetching failure: http code 400
UnityEngine.Debug:LogError (object)
Firebase.Platform.FirebaseLogger:LogMessage (Firebase.Platform.PlatformLogLevel,string)
Firebase.LogUtil:LogMessage (Firebase.LogLevel,string)
Firebase.LogUtil:LogMessageFromCallback (Firebase.LogLevel,string)
Firebase.AppUtil:PollCallbacks ()
Firebase.Platform.FirebaseAppUtils:PollCallbacks ()
Firebase.Platform.FirebaseHandler:Update ()
Firebase.Platform.FirebaseMonoBehaviour:Update ()

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

Firebase initialization code:

public class FirebaseInit : MonoBehaviour
    {
        DependencyStatus dependencyStatus = DependencyStatus.UnavailableOther;
        protected bool isFirebaseInitialized = false;

        public void Init()
        {
               FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
                {
                    dependencyStatus = task.Result;

                    if (dependencyStatus == DependencyStatus.Available)
                    {
                        InitializeFirebase();
                    }
                    else Debug.LogError("Could not resolve all Firebase dependencies: " + dependencyStatus);
                });
        }

        private void InitializeFirebase()
        {
            // [START set_defaults]
            Dictionary<string, object> defaults = new Dictionary<string, object>();

            // These are the values that are used if we haven't fetched data from the
            // server
            // yet, or if we ask for values that the server doesn't have:
            defaults.Add("config_test_string", "default local string");
            defaults.Add("config_test_int", 1);
            defaults.Add("config_test_float", 1.0);
            defaults.Add("config_test_bool", false);

            FirebaseRemoteConfig.DefaultInstance.SetDefaultsAsync(defaults)
              .ContinueWithOnMainThread(task =>
              {
              // [END set_defaults]
              Debug.Log("RemoteConfig configured and ready!");
                  isFirebaseInitialized = true;
                  FetchDataAsync();
              });
        }

        private Task FetchDataAsync()
        {
            Debug.Log("Fetching data...");
            Task fetchTask = FirebaseRemoteConfig.DefaultInstance.FetchAsync(TimeSpan.Zero);
            return fetchTask.ContinueWithOnMainThread(FetchComplete);
        }
        //[END fetch_async]

        private void FetchComplete(Task fetchTask)
        {
            if (fetchTask.IsCanceled)
            {
                Debug.Log("Fetch canceled.");
            }
            else if (fetchTask.IsFaulted)
            {
                Debug.Log("Fetch encountered an error.");
            }
            else if (fetchTask.IsCompleted)
            {
                Debug.Log("Fetch completed successfully!");
            }

            var info = FirebaseRemoteConfig.DefaultInstance.Info;

            switch (info.LastFetchStatus)
            {
                case LastFetchStatus.Success:
                    FirebaseRemoteConfig.DefaultInstance.ActivateAsync()
                    .ContinueWithOnMainThread(task =>
                    {
                          Debug.Log("Success");
                    });
                    break;
                case LastFetchStatus.Failure:
                    switch (info.LastFetchFailureReason)
                    {
                        case FetchFailureReason.Error: Debug.Log("Error"); break;
                        case FetchFailureReason.Throttled:
                            Debug.Log("Fetch throttled until " + info.ThrottledEndTime);
                            break;
                    }
                    break;
                case LastFetchStatus.Pending:
                    Debug.Log("Latest Fetch call still pending.");
                    break;
            }
        }
    }
```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @ORibn-dev,

Thanks for reporting this. Are there any other steps I should perform in order to try and replicate your issue? So far, I haven't encountered an error with the code you provided.

**Comment by ORibn-dev** [comment]
Hi @paulinon !
Besides those steps I also did this when I first installed Firebase:
https://github.com/firebase/quickstart-unity/issues/540#issuecomment-572671145
Because the project started on PC with Windows 7 x64, I had this issue with "Generation of the Firebase Android resource file failed" and used that solution in the link to fix it, but as far as I remember Remote Config worked fine in Editor after that, all the listed issues with freezes and fetching error 400 showed up months later and I didn't change any related code. Could Windows 7 or modified "generate_xml_from_google_services_json" be the potential reason of random fetch error 400?

**Comment by paulinon** [comment]
Hi @ORibn-dev, 

I don't believe that this is what's causing the issue considering that the error is a response from the server. 

In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation? If that's not possible, could you verify if this behavior can be replicated using our [quickstart](https://github.com/firebase/quickstart-unity/tree/master/remote_config/testapp)?

**Comment by ORibn-dev** [comment]
I'll check later today and post the result or reproducible piece.

**Comment by RocksteadyDog** [comment]
When working with multiple projects in the same project, I have to delete the file "remote_config_data", then when you start the project you get an error:

fetching failure: http code 400

UnityEngine.Debug:LogError (object)
Firebase.Platform.FirebaseLogger:LogMessage (Firebase.Platform.PlatformLogLevel,string) (at Z:/tmp/tmp.cEjnms3lS8/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:95)
Firebase.LogUtil:LogMessage (Firebase.LogLevel,string) (at Z:/tmp/tmp.uQUresKAQs/firebase/app/client/unity/proxy/LogUtil.cs:69)
Firebase.LogUtil:LogMessageFromCallback (Firebase.LogLevel,string) (at Z:/tmp/tmp.uQUresKAQs/firebase/app/client/unity/proxy/LogUtil.cs:77)
Firebase.AppUtil:PollCallbacks () (at Z:/tmp/tmp.uQUresKAQs/firebase/app/client/unity/proxy/AppUtil.cs:32)
Firebase.Platform.FirebaseAppUtils:PollCallbacks () (at Z:/tmp/tmp.uQUresKAQs/firebase/app/client/unity/proxy/FirebaseAppUtils.cs:33)
Firebase.Platform.FirebaseHandler:Update () (at Z:/tmp/tmp.cEjnms3lS8/firebase/app/client/unity/src/Unity/FirebaseHandler.cs:208)
Firebase.Platform.FirebaseMonoBehaviour:Update () (at Z:/tmp/tmp.cEjnms3lS8/firebase/app/client/unity/src/Unity/FirebaseMonoBehaviour.cs:45)

**Comment by ORibn-dev** [comment]
Interesting, in my case I have to 2 related sub-projects as one, but only one uses remote config and I didn't touch "remote_config_data".

https://i.imgur.com/UESIx3k.png
I just downloaded quickstart, opened in 2019.4.16f1, installed remote config, added configs and fetch works without any errors. Also installed Database, Storage, Firestore, Analytics, Auth and checked after every installation, also restarted Unity and it still worked all those actions. I wonder what could be the issue then.

**Comment by ORibn-dev** [comment]
It would be really complicated because I'm under NDA and the project is pretty big to remove everything not related to this issue and clean private stuff. But I just tested more and noticed that if I remove "remote_config_data" file inside root folder of the project and start Unity, fetching works fine only once, but when I click Play again it shows this fetching error 400 again and in Unity 2019.4.16f1 also freezes Editor, but if I close Editor, remove "remote_config_data" again and restart Editor, it works only once, again, and then error/freeze after second Play. I tried to remove "remote_config_data" while in Editor, after successful fetch, but it doesn't work and shows the same error and freezes, only closing Editor, removing  "remote_config_data" file before Editor restart and then restart gives me one successful fetch. What could be the issue in this case?

**Comment by ORibn-dev** [comment]
Another update, this is getting insane. Quickstart scene works without issues in the same project where I experience this error and freeze. I literally just copied Sample folder inside Firebase folder with one scene and script. But for whatever reason when I copypasted the same initialization in a script in my scene and it still shows error and freeze Editor. Even better, I actually removed my inititalization script copied that single script that worked in sample scene and it shows the same error in my scene! So the same script, the same file doesn't work in a different scene in my project folder.

**Comment by RocksteadyDog** [comment]
> Thanks for the info, @ORibn-dev and @RocksteadyDog. Since the issue couldn't be replicated in the quickstart, it's likely that the cause of this behavior lies in your project. At this point, it would be helpful if you could provide a minimal, reproducible example of your project.

Download 
https://github.com/firebase/quickstart-unity/tree/master/remote_config/testapp

1. Enter Play Mode  - Ok 👌
1a. Exit Play Mode  - Ok 👌

2. Delete the file "remote_config_data" in the Assets folder

3. Enter Play Mode  - Ok 👌
3a. Enter Play Mode Again - Error 👌
3b. Enter Play Mode Again - Error 👌
3c. Enter Play Mode Again - Error 👌
3... 

4. Close Unity
5. Open Unity and Enter Play Mode  - Ok 👌

**Comment by paulinon** [comment]
@ORibn-dev If that's not possible right now, could you try if the issue could be replicated from a blank Unity project? If so, please provide the complete steps to do so

@RocksteadyDog I've used the quickstart, but I haven't encountered a `remote_config_data` file in my project after exiting Play mode. Are there any other steps that have to be taken into account?

**Comment by ORibn-dev** [comment]
> @ORibn-dev If that's not possible right now, could you try if the issue could be replicated from a blank Unity project? If so, please provide the complete steps to do so
I'll try.

**Comment by RocksteadyDog** [comment]
Hello!

I could not reproduce the error "fetching failure: http code 400"

But i reproduced the error "fetching failure: http code 0"

1. Create New Unity Poject (2020.3.23f1)
  - Switch to Android
  - Set IL2cpp (Net 4)
  - Add packages
    "com.google.android.appbundle": "1.6.0",
    "com.google.external-dependency-manager": "1.2.168",
    "com.google.firebase.analytics": "8.7.0",
    "com.google.firebase.app": "8.7.0",
    "com.google.firebase.crashlytics": "8.7.0",
    "com.google.firebase.remote-config": "8.7.0"

2. Add Monebehaviour and attach to MainCamera
[code.txt](https://github.com/firebase/quickstart-unity/files/7749972/code.txt)
3. Enter Play Mode, Exit Play Mode
4. Delete the file "remote_config_data"
![Screenshot_4](https://user-images.githubusercontent.com/29661837/146879875-f022808b-7696-45c7-a8f8-659d113f0f87.png)
5. Disable Internet
6. Enter Play Mode
7. Now there will always be an annoying error "fetching failure: http code 0"
8. Enable Internet 
9, The error has disappeared

**Comment by ORibn-dev** [comment]
I'll try to check this week, too busy right now.
