### ISSUE TITLE
[Question] Possible to check if Google Services is installed?

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1203]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.23f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Firebase
  * Other Firebase Components in use: Auth, Firestore, Crashlytics, RemoteConfig
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android, iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Some of our users apparently don't have Google Services installed, which is probably the cause of Crashlytics reporting `FirebaseException : SERVICE_NOT_AVAILABLE`.

Is there a way in Firebase to check if Google Services is installed?

**Comment by paulinon** [comment]
Hi @Nyankoo,

Take note that Google Play Services is required by the SDK. As seen in our [documentation](https://firebase.google.com/docs/unity/setup#confirm-google-play-version), you can add the following code in your `Start()` method to check for Google Play Services before calling any other Firebase methods:

```
Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
  var dependencyStatus = task.Result;
  if (dependencyStatus == Firebase.DependencyStatus.Available) {
    // Create and hold a reference to your FirebaseApp,
    // where app is a Firebase.FirebaseApp property of your application class.
       app = Firebase.FirebaseApp.DefaultInstance;

    // Set a flag here to indicate whether Firebase is ready to use by your app.
  } else {
    UnityEngine.Debug.LogError(System.String.Format(
      "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
    // Firebase Unity SDK is not safe to use here.
  }
});
```

With that, I'll be closing this ticket. Let me know if an issue arises with this solution.

**Comment by Nyankoo** [comment]
@paulinon Does this check fail when only one dependency isn't present?

From what I can see in Crashlytics, users that get the exception I mentioned above are still able to use our app, which should not be possible when `dependencyStatus != Firebase.DependencyStatus.Available` (as we're showing an error message and the app doesn't continue).

**Comment by paulinon** [comment]
Hi @Nyankoo, the check will fail in that scenario, and the SDK isn't recommended to be used. Additionally, the Firebase products you mentioned [don't require Google Play services](https://firebase.google.com/docs/android/android-play-services#google_play_services_not_required) to work, so this shouldn't affect your users unless you have something like Dynamic Links in your implementation.

**Comment by Nyankoo** [comment]
@paulinon Ah sorry, forgot to add Cloud Messaging to the list. This is where the exception happens.

We're calling `FirebaseMessaging.TokenReceived += onTokenReceived;` and `FirebaseMessaging.MessageReceived += onMessageReceived;` AFTER we called `CheckAndFixDependenciesAsync`

**Comment by paulinon** [comment]
Thanks for mentioning this, @Nyankoo. In that case, Google Play services is needed for Cloud Messaging to function.

**Comment by Nyankoo** [comment]
@paulinon Which indicates that `CheckAndFixDependenciesAsync` is maybe not catching this, as users can use our app and Firebase services that don't need Play Services, expect Cloud Messaging.

**Comment by Nyankoo** [comment]
@paulinon Any update on this?

**Comment by paulinon** [comment]
Hi @Nyankoo,

I forgot to mention that the function attempts to fix the necessary dependencies for Firebase if they aren't present on the system or in the necessary state, so this would allow a Firebase instance to be created and your app to use Firebase. With that, you can find the list of Firebase products that require the Google Play services [here](https://firebase.google.com/docs/android/android-play-services#google_play_services_required_or_recommended).
