### ISSUE TITLE
[Bug] firebase crash

### ISSUE THREAD

**Issue by yingnierxiao** [firebase/quickstart-unity#1204]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.04
  * Firebase Unity SDK version: com.google.firebase.firebase-app-unity-8.0.0.aar
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

on firebase web admin

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
libc.abort (abort:164)
libart.art::Runtime::Abort(char const*) (Abort:2308)
libbase.0x13978
libbase.android::base::LogMessage::~LogMessage() (~LogMessage:320)
libart.art::IndirectReferenceTable::AbortIfNoCheckJNI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (AbortIfNoCheckJNI:224)
libart.art::IndirectReferenceTable::GetChecked(void*) const (GetChecked:444)
libart.art::JavaVMExt::DecodeGlobal(void*) (DecodeGlobal:24)
libart.art::Thread::DecodeJObject(_jobject*) const (DecodeJObject:144)
libart.art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list) (ArtMethod*>:72)
libart.art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list) (InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>:92)
libart.art::JNI<false>::CallObjectMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list) (CallObjectMethodV:656)
libFirebaseCppApp-8_0_0._JNIEnv::CallObjectMethod(_jobject*, _jmethodID*, ...) (CallObjectMethod:96)
libFirebaseCppApp-8_0_0.firebase::auth::GetUserProperty(firebase::auth::AuthData*, _jobject*, firebase::auth::userinfo::Method, firebase::auth::PropertyType) (GetUserProperty:60)
libFirebaseCppApp-8_0_0.Firebase_Auth_CSharp_FirebaseUser_ProviderId_get (Firebase_Auth_CSharp_FirebaseUser_ProviderId_get:32)
```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @yingnierxiao,

Could you try updating to version 8.6.2 of the SDK and see if the issue persists? If it does, please provide the complete steps needed in order to replicate the issue along with the other details you may have missed in the template.

**Comment by yingnierxiao** [comment]
update   8.7
Date/Time:           2021-12-17 13:49:19.1418 +0800
Launch Time:         2021-12-17 13:49:16.2291 +0800
OS Version:          iPhone OS 15.1 (19B74)
Release Type:        User
Baseband Version:    7.02.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes: 0x0000000000000001, 0x0000000000000010
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4362944496
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   1040d4000-1040dc000 [   32K] r-x/r-x SM=COW  ...berpunkMobile
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL; [11]
Terminating Process: exc handler [65269]

Terminating Process: exc handler [65269]
Triggered by Thread:  0

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   UnityFramework                	       0x10c4a38d4 0x10c21c000 + 2652372
1   UnityFramework                	       0x10c4a38cc 0x10c21c000 + 2652364
2   CoreFoundation                	       0x1851c0c4c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
3   CoreFoundation                	       0x185255554 ___CFXRegistrationPost_block_invoke + 48
4   CoreFoundation                	       0x18522ab34 _CFXRegistrationPost + 416
5   CoreFoundation                	       0x1851d5754 _CFXNotificationPost + 696
6   Foundation                    	       0x1868f0138 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
7   UnityFramework                	       0x10c230cd0 0x10c21c000 + 85200
8   UnityFramework                	       0x10c230dac 0x10c21c000 + 85420
9   UnityFramework                	       0x10dad507c 0x10c21c000 + 25923708
10  GoogleUtilities               	       0x1068ebb68 -[GULAppDelegateSwizzler application:donor_didRegisterForRemoteNotificationsWithDeviceToken:] + 264
11  UIKitCore                     	       0x18839c43c __63-[UIApplication pushRegistry:didUpdatePushCredentials:forType:]_block_invoke + 108
12  libdispatch.dylib             	       0x184ef5194 _dispatch_call_block_and_release + 24
13  libdispatch.dylib             	       0x184ef6198 _dispatch_client_callout + 16
14  libdispatch.dylib             	       0x184ed74a8 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 908
15  CoreFoundation                	       0x1851e57e8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
16  CoreFoundation                	       0x1851a30e8 __CFRunLoopRun + 2528
17  CoreFoundation                	       0x1851b5d7c CFRunLoopRunSpecific + 572
18  GraphicsServices              	       0x19f42a9a0 GSEventRunModal + 160
19  UIKitCore                     	       0x1879e805c -[UIApplication _run] + 1080
20  UIKitCore                     	       0x18777dce0 UIApplicationMain + 2028
21  UnityFramework                	       0x10c235c34 0x10c21c000 + 105524
22  CyberpunkMobile               	       0x1040dbe00 0x1040d4000 + 32256
23  dyld                          	       0x1043b4190 start + 444

**Comment by paulinon** [comment]
Hi @yingnierxiao,

It would be helpful if you could provide a sample project along with the complete steps to replicate the issue so we can analyze what's causing this. If that's not possible, could you verify if this behavior persists using our [quickstart](https://github.com/firebase/quickstart-unity)?

**Comment by yingnierxiao** [comment]
build with Xcode 13.2,run on iOS 15.

**Comment by paulinon** [comment]
Hi @yingnierxiao,

I still need more information from you in order to begin my investigation. A sample project such as a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project would be great to have so that we can identify the cause of this behavior. You may upload this to your GitHub repository and add me as a collaborator so I could check it out.

You can also provide the complete steps to replicate the issue if you were able to encounter this on a separate blank project.

I look forward to hearing from you again soon.

**Comment by yingnierxiao** [comment]
build with Xcode 13.2,run on iOS 15. will crash ,on start app ,100%,8.7  8.6.2version

**Comment by paulinon** [comment]
Hi @yingnierxiao,

I am unable to begin with my investigation because a sample project is needed for me to proceed. As I've said before, you may do this by uploading a GitHub repository containing a minimal, reproducible example of your implementation or providing the complete steps to replicate the issue if you were able to encounter this on a separate blank project.

I look forward to resolving this issue with you soon.
