### ISSUE TITLE
[Bug] Undefined Symbols in version 8.7.0

### ISSUE THREAD

**Issue by LauraLaureus** [firebase/quickstart-unity#1208]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.14f1 LTS
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Unknown (Added all while investigating)
  * Additional SDKs you are using: none relevant. 
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Cannot run the project due to the following error:

(Warning) Arm64 funtion not4-byte aligned: _unwind_tester from <project path>/Libraries/libiPhone-lib.a (unwind_test_arm64.o)
(Error) Undefined symbol: _OBJ_CLASS_$_FIRMessaging
(Error) Undefined symbol: firebase:ReferenceCountedFutureImpl::CompleteHandle(unsigned long)
(Error) Undefined symbol: firebase:ReferenceCountedFutureImpl:ReleaseMutexAndRunCallback(unsigned long)
(Error) Undefined symbol: firebase;util::ClassMethodImplementationCache::ReplaceOrAddMethod(objc_class*,objc_selector*,objc_object* (*)(objc_object*,objc_selector*,...), objc_class*,bool)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Not Tested with the Quickstart

What's the issue repro rate? 100%

What happened? How can we make the problem occur? Just export a project with Auth and Databse modules with the latest version of the SDK

Error log written in the Description section

**Comment by rizafran** [comment]
Thanks for reporting, @LauraLaureus. Could you share the detailed steps in reproducing the issue as well as the complete stack trace?

**Comment by LauraLaureus** [comment]
Hi @rizafran 
We go through a deeper research today and we found that and additional libMessaging.a was added to the XCode BuildPhase. By removing the error disappeared. Maybe it was a bug in the CocoaPod or some garbage from the previous version of the SDK. 
Sorry for the waste of time.

**Comment by paulinon** [comment]
Thanks for letting us know, @LauraLaureus. That being said, I'll be closing this ticket for now.
