### ISSUE TITLE
[Bug] Firebase Databse Fails to download data when needed in between other similar operations in app! "System.Collections.Generic.Dictionary`2[System.String,System.Object]"

### ISSUE THREAD

**Issue by gputhread** [firebase/quickstart-unity#1209]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database (Auth, Database, etc.)
  * Other Firebase Components in use: Auth,Crshylicts, Messaging, Analytics, PerformanceTuner (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob, Google SignIn, GPG, AppleSignIN (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Firebase Cannot take do new GetValueASync sometimes in middle of similar operations of app and throws System.Collections.Generic.Dictionary`2[System.String,System.Object] as a snapshot value!

#### Steps to reproduce:

Setup any unity project with realtime databse perform non stop multiple times : 
                                                                     .GetValueAsync().ContinueWithOnMainThread(task =>
then you will get value as System.Collections.Generic.Dictionary`2[System.String,System.Object] instead of any child/key/database value!
              

#### Relevant Code:

`public void aaaa()
    {
        Reference.Child("Users").OrderByChild("About/XP").StartAt(1).LimitToFirst(12).GetValueAsync().ContinueWithOnMainThread(task =>
              {
                  if (task.IsFaulted)
                  {

                      return;
                  }
                  else if (task.IsCompleted)
                  {
                      DataSnapshot Snapshot = task.Result;
                      if (Snapshot != null)
                          Debug.Log(Snapshot.Value);
                      return;
                  }
                  return;

              });
    }`

**Comment by paulinon** [comment]
Hi @gputhread,

Thanks for reporting this issue. Could you provide some sample data I could use for my database? I haven't been able to replicate the issue using the code you provided so far.
