### ISSUE TITLE
i want to login with google and facebook using firebase sdk for unity please help me 

### ISSUE THREAD

**Issue by rajan995** [firebase/quickstart-unity#121]
i want to login with google and facebook using firebase sdk in unity please help me 
in google sign in 
how to get googleIdToken, googleAccessToken

in facebook 
how to get accessToken

in twitter 
how to get accessToken, secret

please help me

**Comment by stewartmiles** [comment]
@rajan995 FYI this is not general support, in general it's much nicer for the community to post to firebase-talk@googlegroups.com

Google token:
https://github.com/googlesamples/google-signin-unity

Facebook token:
https://github.com/facebook/facebook-sdk-for-unity

Twitter
https://dev.twitter.com/twitterkit/unity/overview

Cheers,
Stewart
