### ISSUE TITLE
Google Analytics for Firebase has not been created. Please, configure Firebase by calling [FIRApp configure]

### ISSUE THREAD

**Issue by MuhammadSafyan** [firebase/quickstart-unity#1212]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.18
  * Firebase Unity SDK version: 8.9.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: __no___ (Auth, Database, etc.)
  * Other Firebase Components in use: __no___ (Auth, Database, etc.)
  * Additional SDKs you are using: ___no__ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: ___mac__ (Mac, Windows, or Linux)
  * Platform you are targeting: ___ios__ (iOS, Android, and/or desktop)
  * Scripting Runtime: ___IL2CPP__ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
I followed this setup : https://firebase.google.com/download/unity
and added in the main screen
      FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
        dependencyStatus = task.Result;
        if (dependencyStatus == DependencyStatus.Available) {
          DebugLog("Enabling data collection.");
      FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);

      DebugLog("Set user properties.");
      // Set the user's sign up method.
      FirebaseAnalytics.SetUserProperty(
        FirebaseAnalytics.UserPropertySignUpMethod,
        "Google");
      // Set the user ID.
      FirebaseAnalytics.SetUserId("uber_user_510");
      // Set default session duration values.
      FirebaseAnalytics.SetSessionTimeoutDuration(new TimeSpan(0, 30, 0));
      firebaseInitialized = true;
        } else {
          Debug.LogError(
            "Could not resolve all Firebase dependencies: " + dependencyStatus);
        }
When i build for Xcode following errors
![Screenshot 2021-12-22 at 10 51 51 AM](https://user-images.githubusercontent.com/85476537/147042635-54d3af03-0cb4-4183-bd67-f840f84fbd9e.png)

When i Build for android every thing is OK and i can see events in Debug view as well as dashboard

**Comment by MuhammadSafyan** [comment]
I then noticed that when the app starts, about 150 warnings of the following kind are printed to the log:

![Screenshot 2021-12-22 at 12 00 44 PM](https://user-images.githubusercontent.com/85476537/147049601-40fb0162-9ae1-48df-a43f-0f2dcd70a300.png)

**Comment by MuhammadSafyan** [comment]
I have salved the problem by Enableing the static link library in 
Assets=>ExternalDependaymanager=>IOSResolver=>Setting then check link static labrary

**Comment by paulinon** [comment]
Hi @MuhammadSafyan,

Thanks for sharing your solution. I'll be closing this ticket for now. Let me know if a new issue arises.
