### ISSUE TITLE
[CRASH]  RCNConfigFetch.m - Line 113

### ISSUE THREAD

**Issue by ygttiramisu** [firebase/quickstart-unity#1215]
* Unity editor version: 2020.3.13f1
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: RemoteConfig (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics,RemoteConfig,Messaging,Crashlytics
  * Additional SDKs you are using:Facebook,Facebook Audience Network, Admost Mediation
  * Platform you are using the Unity editor on: Mac 
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

Crashlytics crash details;

Crashed: IL2CPP Threadpool worker
0  libobjc.A.dylib                0x2840 objc_retain + 16
1  libsystem_blocks.dylib         0x197c _Block_object_assign + 240
2  libsystem_blocks.dylib         0x175c _Block_copy + 252
3  libdispatch.dylib              0x632b8 _dispatch_Block_copy + 28
4  libdispatch.dylib              0x7cbc dispatch_async$VARIANT$mp + 52
5  CFNetwork                      0x15ce0 CFHTTPCookieCopyName + 2348
6  FirebaseRemoteConfig           0x11f7c -[RCNConfigFetch recreateNetworkSession] + 113 (RCNConfigFetch.m:113)
7  FirebaseRemoteConfig           0x9d70 -[FIRRemoteConfig configSettings] + 545 (FIRRemoteConfig.m:545)
8  UnityFramework                 0x1d0a674 firebase::remote_config::internal::RemoteConfigInternal::GetConfigSettings() const + 40
9  UnityFramework                 0x1d0ddb8 Firebase_RemoteConfig_FirebaseRemoteConfigInternal_GetConfigSettings + 20
10 UnityFramework                 0x21d03a0 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4427793312
11 UnityFramework                 0x21d0330 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4427793200
12 UnityFramework                 0x20032b4 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4425904820
13 UnityFramework                 0xeb08c RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**) + 44728 (Il2CppInvokerTable.cpp:44728)
14 UnityFramework                 0x1ce8820 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 76156
15 UnityFramework                 0x14eda64 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) + 2350092
16 UnityFramework                 0x14f881c ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 2394564
17 UnityFramework                 0x150479c MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingExceptionPtr*) + 2443588
18 UnityFramework                 0x1504a1c MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) + 2444228
19 UnityFramework                 0x14f9564 Scripting::SendScriptingMessage(GameObject&, char const*, ScriptingObjectPtr) + 2397964
20 UnityFramework                 0x14f9298 Scripting::BroadcastScriptingMessage(GameObject&, char const*, ScriptingObjectPtr) + 2397248
21 UnityFramework                 0x1563518 GameObject_CUSTOM_BroadcastMessage(ScriptingBackendNativeObjectPtrOpaque*, ScriptingBackendNativeStringPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*, int) + 2832064
22 UnityFramework                 0x230b5e8 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4429084136
23 UnityFramework                 0x2e89b4c flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4441135948
24 UnityFramework                 0x2ee3028 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4441501736
25 UnityFramework                 0x2f81440 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4442149952
26 UnityFramework                 0x2e8a1f0 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4441137648
27 UnityFramework                 0x2e8a02c flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4441137196
28 UnityFramework                 0x2e99a78 flatbuffers::IDLOptions::IDLOptions() (.cold.1) + 4441201272
29 UnityFramework                 0xeb6e0 RuntimeInvoker_FalseSByte_t928712DD662DC29BA4FAAE8CE2230AFB23447F0B(void (*)(), MethodInfo const*, void*, void**) + 44909 (Il2CppInvokerTable.cpp:44909)
30 UnityFramework                 0x1cb7760 worker_thread(void*) + 2596
31 UnityFramework                 0x1cde8ec il2cpp::vm::ThreadStart(void*) + 35400
32 UnityFramework                 0x1cb8f8c il2cpp::os::Thread::RunWrapper(void*) + 8784
33 UnityFramework                 0x1cbb820 il2cpp::os::ThreadImpl::ThreadStartWrapper(void*) + 19172
34 libsystem_pthread.dylib        0x2458 _pthread_start + 116
35 libsystem_pthread.dylib        0xab0 thread_start + 8

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
-Open the game and crash.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? %50 

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
As soon as you open the app screen goes gray and after 10 seconds shuts down.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by argzdev** [comment]
Hi @ygttiramisu, thanks for reporting. We'll try to investigate and see what we can find.

**Comment by ygttiramisu** [comment]
Hi @argzdev! Is there any update about the issue?

**Comment by paulinon** [comment]
Hi @ygttiramisu,

In order to identify what's causing this issue, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate this behavior?

**Comment by paulb777** [comment]
See https://github.com/firebase/firebase-ios-sdk/issues/14449
