### ISSUE TITLE
Recieve Custom FCM In Unity 

### ISSUE THREAD

**Issue by black-knight** [firebase/quickstart-unity#122]
I integrated Firebase Cloud Messaging with Unity successfully and I can receive usual messages when I send them from Firebase Console, but I need some extra things.

1 - How I can send my notification as a URL? I mean I want that when user touch notification it opens my URL that I put in value in FireBase Console.

2 - How I can send and show a picture and a custom icon in notification?

Unfortunately I can't find any thing in internet and official documents confused me.

Is there any way to gain these request only with FireBase SDK?

Thank you.

**Comment by stewartmiles** [comment]
@black-knight, FYI firebase-talk@googlegroups.com is a better forum for these sort of questions.

1) https://stackoverflow.com/questions/41321947/i-want-to-send-specific-link-inside-notifications-send-through-firebase-push-not
2) If you want to customize the Icon you can do so on Android by customizing the manifest https://firebase.google.com/docs/cloud-messaging/android/topic-messaging#edit-the-app-manifest

Cheers,
Stewart
