### ISSUE TITLE
[Bug] ANR in com.google.firebase.MessagingUnityPlayerActivity

### ISSUE THREAD

**Issue by adibacco** [firebase/quickstart-unity#1221]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.19.f1
  * Firebase Unity SDK version: 8.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging
  * Other Firebase Components in use: Analytics, Crashlytics, Firestore
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

In last 30 days, I got several ANRs (no stack trace) showing com.google.firebase.MessagingUnityPlayerActivity as the cuplrit (see image). ANRs are increasing and I already overcome the 0.47% google play threshold.

_**ANR details
Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 11. Wait queue head age: 7975.8ms.)
com.google.firebase.MessagingUnityPlayerActivity**_

See attachment.

I didn't change the app but ANRs are increasing anyway and I'm not sending any cloud message to the app.

**Occurrences
112
Last 30 days
Total occurrences
168
Lifetime
Impacted users
114
Lifetime
Last occurred
14 hours ago**

#### Steps to reproduce:

No known steps

**Comment by paulinon** [comment]
Hi @adibacco,

I see that this issue is similar to #1151. The fix for this is included in SDK version 8.6.0, so it's best that you update the SDK to its latest version (8.7.0 as of writing). 

I'll be closing this for now. Let me know if a new issue arises.

**Comment by adibacco** [comment]
Updated to SDK 8.7.0, now I see multiple ANRs always related to com.google.firebase.MessagingUnityPlayerActivity
but with SDK 8.7.0 there are multiple rows in the "Crashes and ANR" table in Google Play.

![image](https://user-images.githubusercontent.com/2692833/151246555-5d8331e0-7b99-42cb-8177-83c7c31ef2ad.png)

**Comment by adibacco** [comment]
Dear @paulinon ,

ANRs are increasing and some of those that point to MessagingUnityPlayerActivity have also an hex number in the descritption (see below). 

![image](https://user-images.githubusercontent.com/2692833/151693447-d3d22142-93c5-48b1-b59c-bc5cc7ed7b10.png)

**Comment by paulinon** [comment]
Hi @adibacco,

Thanks for bringing this to our attention. Could you provide a complete stack trace that's being returned after the app crashes so that we can identify what's causing the issue?

**Comment by adibacco** [comment]
Dear @paulinon,

the most frequent ANR (the first one in the table) has no associated stack trace. The second one has a stack trace that I'm attaching. 
[Crash details _ ABC Kids - trace letters, preschool learning games.pdf](https://github.com/firebase/quickstart-unity/files/7973938/Crash.details._.ABC.Kids.-.trace.letters.preschool.learning.games.pdf)

**Comment by paulinon** [comment]
Thanks for this, @adibacco. Version 8.8.0 of the SDK has been released recently. Could you try this version and see if this fixes your issue? If it doesn't, please provide a new complete stack trace so that we can analyze this behavior.

**Comment by adibacco** [comment]
I also tried version 8.8.0 with no luck, I simply imported the messaging lib but I didn't even use it.

**Comment by paulinon** [comment]
Thanks for the update, @adibacco. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the latest stack trace so that we can try to isolate the root cause of the issue?

**Comment by adibacco** [comment]
@paulinon , I removed the firebase messaging and the ANR went away. I highlight that I was not using at all the firebase messaging library, simply importing the package caused the problem then I think you reproduce it easily. I’m using latest LTS 2020 version for Unity

**Comment by paulinon** [comment]
Hi @adibacco, 

I've used the quickstart to try and replicate the issue, but I haven't encountered any ANRs. It would be helpful if you could provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation so we can see how the SDK is supposedly causing the crashes.
