### ISSUE TITLE
[Question] DllNotFoundException: FirebaseCppApp on the editor

### ISSUE THREAD

**Issue by metamoru00** [firebase/quickstart-unity#1222]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.31f1
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: messaging (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac High Sierra 10.13.6 (Mac, Windows, or Linux)
  * Platform you are targeting: Android and iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
I am not good at English, so I have described it in google translate.

Hello.
I installed firebase, but the error cannot be resolved.

Steps to reproduce:
Import dotnet4's FirebaseMessaging.unitypackage into Firebase Unity quickstarts.
When I play UnityEditor, DllNotFoundException: FirebaseCppApp-8_7_0 is displayed on the console.

Assets / Firebase / Plugins / x86_64 has FirebaseCppApp.bundle, FirebaseCppApp.dll, FirebaseCppApp.so, but I get a DllNotFoundException.

Plugin placement:
<img width="400" alt="スクリーンショット 2022-01-19 19 48 33" src="https://user-images.githubusercontent.com/98017472/150115636-b98f7e70-df2a-4e56-9820-d2b5399e05e5.png">

ImportSetting:
<img width="487" alt="スクリーンショット 2022-01-19 19 53 56" src="https://user-images.githubusercontent.com/98017472/150117723-642a4f9e-8f7a-4087-a675-f01c0bdb9bf7.png">

ErrorLog:
```
DllNotFoundException: FirebaseCppApp-8_7_0
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.uX3mTvNLXM/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:117)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.uX3mTvNLXM/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:137)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.uX3mTvNLXM/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.uX3mTvNLXM/firebase/app/client/unity/proxy/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.uX3mTvNLXM/firebase/app/client/unity/proxy/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.uX3mTvNLXM/firebase/app/client/unity/proxy/FirebaseApp.cs:67)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Messaging.UIHandler.Start () (at Assets/Firebase/Sample/Messaging/UIHandler.cs:65)
```
I removed the library and re-imported FirebaseMessaging.unitypackage and still got the same error.
Versions 8.3.0 and 8.4.0 did not get a DllNotFoundException, but from version 8.5.0 I got this error.
Do I need to make any other settings?

Many thanks for any help

**Comment by paulinon** [comment]
Hi @metamoru00, 

Thanks for reporting this. I'd like you to try going to your Mac’s `System Preferences > Security & Privacy` then Click `Allow Anyway`. It should look something like this:

<img width="671" alt="Screen Shot 2022-01-12 at 11 08 17 PM" src="https://user-images.githubusercontent.com/58971522/150170042-f4ebc35d-dd37-4327-9559-bc32f58fe3ba.png">

Let me know if this solution worked for you. Otherwise, please provide the complete steps you performed before facing this issue.

**Comment by metamoru00** [comment]
Hi @paulinon 
Thanks for your answer.
`Allow Anyway` wasn't showing up in `Security & Privacy`.

<img width="683" alt="スクリーンショット 2022-01-20 10 25 26" src="https://user-images.githubusercontent.com/98017472/150247601-09816c60-dc2c-4059-8e72-104f2b6cf617.png">

>Otherwise, please provide the complete steps you performed before facing this issue.

Here are the steps I took:
Step1: Download quickstart from git
Step2: Open the messaging testapp project in Unity
Step3: Select yes.
<img width="425" alt="スクリーンショット 2022-01-20 11 03 15" src="https://user-images.githubusercontent.com/98017472/150260125-3fdb460e-f6f9-46bf-bafa-c849f044be7a.png">

Step4: Select to continue
<img width="427" alt="スクリーンショット 2022-01-20 11 06 44" src="https://user-images.githubusercontent.com/98017472/150261074-77b535a4-9954-4356-b181-912fb4b7c90b.png">

Step5: Change platform to android.
Step6: Import dotnet4's FirebaseMessaging.unitypackage.
Step7: Select disable.
<img width="406" alt="スクリーンショット 2022-01-20 11 40 53" src="https://user-images.githubusercontent.com/98017472/150262459-8eb8ef9d-b507-4d9e-94e9-7861ab4f67b3.png">

Step8: Play Unity.

DllNotFoundException is displayed by the above procedure.
Do I need to run `Android Resolver>Forece Resolve` before playing in the editor?

**Comment by paulinon** [comment]
Hi @metamoru00, 

Running `Force Resolve` isn't usually necessary. Could you try this out and see if it makes a difference?

Additionally, are you getting an alert like this when playing the scene?

<img width="260" alt="Screen Shot 2022-01-12 at 11 05 27 PM" src="https://user-images.githubusercontent.com/58971522/150324716-28b840b5-d744-4765-b07e-852f2a4c5ed3.png">
 
If so, click `Cancel` so that the `Allow Anyway` can appear.

**Comment by metamoru00** [comment]
Hi @paulinon 
`Force Resolve` does not change the result.

>Additionally, are you getting an alert like this when playing the scene?

I didn't see such an alert when I played the scene.

Apparently, project members other than myself haven't got any errors.
I tried reinstalling Unity because there seems to be a problem with the local environment, but the result did not change.

**Comment by paulinon** [comment]
Hi @metamoru00,

When you reinstalled Unity, did you maintain the same version as the one you indicated (2019.4.31f1)? Could you try if updating the editor makes a difference (The latest LTS release is version 2020.3.26f1)?

**Comment by metamoru00** [comment]
>When you reinstalled Unity, did you maintain the same version as the one you indicated (2019.4.31f1)?

Yes. I installed the same version, but the results did not change.
I also installed version 2020.3.26f1 and imported Firebase Messaging in a new Firebase quickstart project, but I got a DllNotFoundException.

**Comment by metamoru00** [comment]
I will try to upgrade MacOS.
`High Sierra 10.13.6` → `Big Sur 11.6.2`
We will notify you when the update is complete.

**Comment by paulinon** [comment]
Thanks for the update, @metamoru00. Let me know if the software update makes any difference.

**Comment by metamoru00** [comment]
Hi @paulinon .

I have a good report.
When I play a scene after upgrading MacOS, the alert I told you before is now displayed.
https://github.com/firebase/quickstart-unity/issues/1222#issuecomment-1017362861
After clicking `Allow Anyway` in `System Preferences> Security & Privacy`, I played the scene again and it worked fine.

I don't know if this bug is specific to High Sierra, but it seems that older OS needs to be upgraded.
I hope this issue helps someone.

Thank you for your help!
