### ISSUE TITLE
Sign in With Apple Not Found in Firebase Unity SDK

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#1223]
Hi All 

I am working in unity 2019.4.30. In my project i have to use Sign In With Apple through Firebase. I have enabled Sign in with Apple option in Firebase console. While I am using Firebase unity Auth Project. Sign in with apple option is not found in this sample project. But  other option  Microsoft,Yahoo Found. 

 I have to work in Sign in With Apple. How can i make  Sign in with Apple through Firebase?

**Comment by paulinon** [comment]
Hi @CLOUDFIRE91,

While Sign in With Apple isn't available in the quickstart, this feature is included in the SDK. A prerequisite for this is joining the [Apple Developer Program](https://developer.apple.com/programs/) to configure Sign In With Apple for your build. You may check out our [documentation](https://firebase.google.com/docs/auth/unity/apple) for more detailed information.

I'll be closing this for now. Let me know if an issue arises.
