### ISSUE TITLE
Unity Editor App Engine default service account doesn't have permission for rule "auth.uid" == $uid

### ISSUE THREAD

**Issue by bellicapax** [firebase/quickstart-unity#123]
Windows 10
Unity 2017.2.f3

Steps
1. Login via Unity Editor using service account and .p12 file with email/password as service account email and "notasecret" 
2. Try to get a value from a route at any valid userId (from my Authentication tab in the Firebase console) with rule "$uid": { ".read": "auth.uid == $uid", ".write": "auth.uid == $uid"}

What is the expected result?
Be able to get the values. (this seems possible via the simulator)

What happens instead of that?
Fail to get value and instead get warning
"11/18/2017 12:24:36 AM [Warn] SyncTree: Listen at /path/[userID] failed: DatabaseError: Permission denied"

As you can see, I'm using the correct kind of service account and it has Editor authority. I'm not sure what else I would need to access that information.

![2017-11-17 18_30_59-iam admin - incantation](https://user-images.githubusercontent.com/3947103/32974660-8b04eb0a-cbc5-11e7-84a4-8c07cb6ca36b.png)
![2017-11-17 18_31_12-iam - incantation](https://user-images.githubusercontent.com/3947103/32974663-8d8a5054-cbc5-11e7-8c26-2721a4b74d01.png)

**Comment by a-maurice** [comment]
Hi there,

One thing that stands out to me is that the path it is trying to listen at is /path/[userID], which seems incorrect.  Just to confirm, have you set the Auth User Id the editor should be impersonating with the extension method FirebaseApp.SetEditorAuthUserId(string uid) ?

The code should look something along the lines of:
FirebaseApp.DefaultInstance.SetEditorDatabaseUrl("https://YOUR-FIREBASE-APP.firebaseio.com/");
FirebaseApp.DefaultInstance.SetEditorP12FileName("YOUR-FIREBASE-APP-P12.p12");
FirebaseApp.DefaultInstance.SetEditorServiceAccountEmail("SERVICE-ACCOUNT-ID@YOUR-FIREBASE-APP.iam.gserviceaccount.com");
FirebaseApp.DefaultInstance.SetEditorP12Password("notasecret");
FirebaseApp.DefaultInstance.SetEditorAuthUserId("myUserId");
var reference = FirebaseDatabase.DefaultInstance.GetReference("myUserId");

Hopefully that helps!

**Comment by bellicapax** [comment]
@a-maurice  Thank you!


1. My problem was two-fold: I didn't realize the SetEditorAuthUserId(userId) function existed
2. I was also using FirebaseAuth to login via email & password which I suppose overwrote this Editor functionality.
