### ISSUE TITLE
[Bug] Firebase.Storage.StorageException: The server did not return a valid JSON response

### ISSUE THREAD

**Issue by Skinzart** [firebase/quickstart-unity#1230]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.35f1
  * Firebase Unity SDK version: 8.3.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Storage
  * Other Firebase Components in use: Firestore, Storage
  * Additional SDKs you are using:
  * Platform you are using the Unity editor on: Windows 10
  * Platform you are targeting: Desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

I am getting this error on random devices especially on Windows 7 and windows 11, but this error has not been found on windows 10,
This problem makes the application like it is not getting a connection to the internet, even though the internet on the device is running fine, there is no antivirus or anything that is blocking the application connection.

#### Relevant Code:

```
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Setting up 2 worker threads for Enlighten.
  Thread -> id: b8c -> priority: 1 
  Thread -> id: 24e8 -> priority: 1 
System.AggregateException: One or more errors occurred. ---> Firebase.Storage.StorageException: The server did not return a valid JSON response.  Contact Firebase support if this issue persists.
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.Storage.StorageException: The server did not return a valid JSON response.  Contact Firebase support if this issue persists.<---
 ServerStatus.json
```

**Comment by paulinon** [comment]
Hi @Skinzart,

Thanks for reporting this issue. Desktop support from the Firebase Unity SDK is currently in beta, but let's see what could be done for this case. In order to identify what's causing this, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the complete steps to replicate the issue?

**Comment by Skinzart** [comment]
hi @paulinon , Thanks for the response, unfortunately i still can't reproduce the bug, i have tried to install windows with the same version and specifications as the user is using, but i don't find the error, i'm very confused, because not all windows 7 devices, this might happen only 1:10 on users who use windows 7 / 11, and what I found from user device player.log was only the error I gave above

**Comment by Skinzart** [comment]
ah ok thanks, I'll try to make a minimal app with that version, and maybe I'll try it on PC users who have the problem I mentioned above
