### ISSUE TITLE
SMS is not receiving in Android 

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#1231]
Hi All 

I am using  unity quick start master. I have dowloaded  latest firebase unity version. I have enabled phone verification method, and 
i have added SHA1, SHA256 method in firebase and also i have enabled  safety check method also.

I have dowload the  googleservices.json also. I have download the unity quick start master and run the auth file in unity..

when i add phone number and  click the Authenticate Phone number.  

SMS is not receiving... No Error message displayed... 

Whats wrong ???

**Comment by paulinon** [comment]
Hi @CLOUDFIRE91,

It appears that you're facing a backend issue that's preventing you from receiving an SMS. You may report this to [Firebase Support](https://firebase.google.com/support/troubleshooter/auth/phone) where one of our agents can analyze this issue. That being said, I'll close this for now.
