### ISSUE TITLE
Firebase AARs being changed after every change in project's package/product name, any way to spare the change?

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [firebase/quickstart-unity#1234]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.25f1
  * Firebase Unity SDK version: 8.7
  * Source you installed the SDK: .unitypackage.
  * Problematic Firebase Component: .
  * Other Firebase Components in use: analytics, app-unity, common, crashlytics-ndk, crashlytics-unity, installations-unity.
  * Additional SDKs you are using: google.android.appbundle-1.6.0, google.play.appupdate-1.6.0, google.play.assetdelivery-1.6.0, google.play.billing-3.2.1, google.play.instant-1.6.0, google-play-plugins-1.6.0.
  * Platform you are using the Unity editor on: Linux.
  * Platform you are targeting: Android.
  * Scripting Runtime: IL2CPP.

### [REQUIRED] Please describe the question here:
I'm using **one** Unity project to create **multiple** apps (each with its unique flavor, but based on the same code), each with different package/product name that published as separate app at Google Play Store. I need to switch between the flavors of the app often, and each time Android Resolver scanning everything and the following firebase files are changed:
>com.google.firebase.firebase-analytics-unity-8.7.0.aar
>com.google.firebase.firebase-app-unity-8.7.0.aar
>com.google.firebase.firebase-common-20.0.0.aar
>com.google.firebase.firebase-crashlytics-ndk-18.2.5.aar
>com.google.firebase.firebase-crashlytics-unity-8.7.0.aar
>com.google.firebase.firebase-installations-unity-8.7.0.aar

Each flavor has its unique firebase configuration file, but they all use the same firebase packages. I don't know why these files keep being change after each Android Resolve run after package name change. Is there a way to spare this changes, or they include an injection of package name that forces them to be updated?

**Comment by paulinon** [comment]
Hi @a-l-e-x-d-s-9,

I see that you've filed a similar ticket in the resolver queue as seen [here](https://github.com/googlesamples/unity-jar-resolver/issues/504). Let's continue our discussion there so that our conversation is contained in one thread. That being said, I'll close this issue.
