### ISSUE TITLE
[FR] Support list API on StorageReference in Unity SDK as with iOS/Android/Web

### ISSUE THREAD

**Issue by ferretnt** [firebase/quickstart-unity#1237]
### Feature proposal

* Firebase Component: Storage

Firebase Unity SDK should expose the List/ListAll APIs identically to its underlying iOS/Android SDKs. 

(I searched and couldn't find an open issue here if this is the official channel, although https://github.com/firebase/firebase-unity-sdk/issues/104 and https://github.com/firebase/firebase-unity-sdk/issues/98 appear to be equivalent issues in the repo that is not considered an official feature request channel.) 

(OSSBOT says this doesn't follow the template, but I'm not sure how, and I tried to favour a short and obvious report, per guidelines.)

**Comment by paulinon** [comment]
Hi @ferretnt,

Thanks for filing this ticket. This would make a great feature as this is present in other platforms. That being said, I've taken note of this and marked this as a feature request. We'll be sharing updates via this thread.

**Comment by chkuang-g** [comment]
For management purpose, let me use https://github.com/firebase/firebase-unity-sdk/issues/98 as the main feature request post since it is the oldest (and the age of the FR matters :))

Please upvote that post if you consider it important to your team. 

Thank you!
