### ISSUE TITLE
How to send Messages into a topic

### ISSUE THREAD

**Issue by mole84** [firebase/quickstart-unity#124]
Hi everybody,

the messaging example works fine so far but there is no example how to send a message to a topic?
Someone has an example or idea howto?

I dont know how to send the http post request and which authkey i have to take.

Please help.

**Comment by stewartmiles** [comment]
@mole84 

https://firebase.google.com/docs/cloud-messaging/android/topic-messaging
scroll down to "Topic HTTP POST request"

It looks like the C++ and Unity docs have managed to get mangled, I've poked our tech writers to fix it.

Cheers,
Stewart

**Comment by mole84** [comment]
Hi stewartmiles,
thank you, but what means "Bearer" and how to get the Key after "Bearer"?
"Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA"

Best regards
Mole

**Comment by stewartmiles** [comment]
https://security.stackexchange.com/questions/108662/why-is-bearer-required-before-the-token-in-authorization-header-in-a-http-re

The token is accessible by:
- Opening the Firebase Console
- Click the gear next to `Project Overview`
- Click `Project Settings`
- Click the `Cloud Messaging` tab
- Find the `Server Key` field, that's the authorization key you need to use.

I recommend testing with the curl command line first (following the example).  If you're sending messages from your C# project, I hope that's from your backend.  If you embed your server key in your mobile application other developers could unpack your app, steal your auth token and send messages to your users.

**Comment by mole84** [comment]
thx, i got it!
It works now, i put a php script to my server and send the pushNotification by curl!
