### ISSUE TITLE
[Question] Game Center authentication

### ISSUE THREAD

**Issue by MartinVavrek** [firebase/quickstart-unity#1240]
After linking game center provider to firebase account, providerData contains provider gc.apple.com with UserId.
This UserId does not match teamPlayerId nor gamePlayerId which should be accessible via Unity Social API like this:

`UnityEngine.SocialPlatforms.Impl.UserProfile) Social.localUser).gameId;`
`UnityEngine.SocialPlatforms.Impl.UserProfile) Social.localUser).id;`

UserId from firebase is most probably legacy playerId, which is deprecated by iOS. How can we pair logged game center user with provider data from firebase account? 

Here is old issue where no answer was provided:
https://github.com/firebase/quickstart-unity/issues/586

Thanks

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.30f1
  * Firebase Unity SDK version: 8.4.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Auth,
  * Other Firebase Components in use:
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

**Comment by paulinon** [comment]
Hi @MartinVavrek, 

Thanks for the report. Based on your description, it seems that the issue falls outside the Unity SDK as it talks about the backend. Kindly reach out to [Firebase Support](https://firebase.google.com/support) where one of our agents can handle this. That being said, I'll close this for now.
