### ISSUE TITLE
[Question] Crashlytics not reporting all non-fatal bugs to firebase after unity 2020

### ISSUE THREAD

**Issue by Diogo-Queiroz** [firebase/quickstart-unity#1245]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.26f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics, Installations, Messaging
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows, Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:
All were working till unity 2019.4 and after updating to 2020.3.26f1 only a few non-fatal bugs are being reported, those that we manually get and report to Firebase Crashlytics and actual crashes. Those non-fatal bugs like the Null Reference Exception or FormatException are not being reported anymore.

**Comment by paulinon** [comment]
Hi @Diogo-Queiroz,

Thanks for reporting this. I noticed that you're using an old version of the SDK. Could you try using its latest version and see if it makes a difference? If it doesn't, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so that we can identify the cause of this behavior.

**Comment by Diogo-Queiroz** [comment]
Hi, @paulinon I will do that. I will first try to use the updated SDK version, which I believe is 8.8.0. 
Also, in this manner of updating the SDK, I would be able to get those new Unity Metadata information? Just asking.
![image](https://user-images.githubusercontent.com/5124139/159745114-f7e2937f-63b3-45a1-a8be-64c9cc4eafab.png)

**Comment by paulinon** [comment]
Hi @Diogo-Queiroz, you should be able to retrieve the metadata after the SDK update. I look forward to your results.

**Comment by Diogo-Queiroz** [comment]
Hi @paulinon, another quick question. In order to update the SDK to 8.8.0, I just simply download the zip file from the [Getting Started](https://firebase.google.com/docs/crashlytics/get-started?platform=unity#add-sdk) page and add all the packages we use via Import Custom Package (Crashlytics, Analytics, Installations, Messaging) or some settings need to be updated as well? I noticed that after importing, the package finds old version of documents and ask to remove them.

**Comment by Diogo-Queiroz** [comment]
Hi @paulinon, using the [Getting Started](https://firebase.google.com/docs/crashlytics/get-started?platform=unity#initialize-crashlytics) tutorial to initialize Crashlytics the `FirebaseApp.CheckAndFixDependenciesAsync()` is throwing an exception. Which causes the Firebase to not initialize. 

`Debug.LogError($"{_className} [FirebaseEnabled] :: Could not resolve all Firebase dependencies: {dependencyStatus}");`
![image](https://user-images.githubusercontent.com/5124139/160206012-faa78775-92ef-4ae8-94d1-fad763b45e3b.png)

The error log also said that FirebaseCppApp_8_8_0 could not be found. 
![image](https://user-images.githubusercontent.com/5124139/160206269-2daab1d4-aeac-4532-a60b-6aca28612c85.png)

Any suggestions?

**Comment by paulinon** [comment]
Thanks for the update, @Diogo-Queiroz. Before I try to replicate this issue, I have a few questions:
- Does this issue persist on both Windows and Mac? 
- Were the steps you shared performed in an empty Unity project? 
- Are you able to encounter this issue on both the app build and the Unity editor?

It would be great if you provide additional context about this behavior.

**Comment by Diogo-Queiroz** [comment]
Hi @paulino.
> * Does this issue persist on both Windows and Mac?
I didn't test on Mac yet. Was tested on Windows. 

> * Are you able to encounter this issue on both the app build and the Unity editor?
Firebase is enabled in Editor. 
the `task.Result` returned _Available_.
![image](https://user-images.githubusercontent.com/5124139/160456265-3a70e056-9236-439e-9b28-7051d54e87cd.png)

> * Were the steps you shared performed in an empty Unity project?
It wasn't on an empty project. I updated our main project with it.

Thanks for your help.

**Comment by paulinon** [comment]
Hi @Diogo-Queiroz, 

It would be helpful if you could provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps to reproduce the issue so that we can analyze this behavior you're facing.

I look forward to hearing from you soon.
