### ISSUE TITLE
[Bug] Crash on iOS 15 within FIRMessaging

### ISSUE THREAD

**Issue by x-henry-tian** [firebase/quickstart-unity#1247]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.26f LTS
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Messaging (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics, App (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac/Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS 15 (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2Cpp (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Full Call stack of the crash reported on iOS device, Firebase 8.7.0 is not handling the Quit smoothly enough for us to get statistics issue:

[ 00 ] <redacted>
[ 01 ] _objc_exception_throw
[ 02 ] <redacted>
[ 03 ] -[FIRInstallations initWithAppOptions:appName:installationsIDController:prefetchAuthToken:]
[ 04 ] -[FIRInstallations initWitAppOptions:appName:]
[ 05 ] -[FIRInstallations initWithApp:]
[ 06 ] __40+[FIRInstallations componentsToRegister]_block_invoke
[ 07 ] -[FIRComponentContainer instantiateInstanceForProtocol:withBlock:]
[ 08 ] -[FIRComponentContainer instanceForProtocol:]
[ 09 ] +[FIRInstallations installationsWithApp:]
[ 10 ] +[FIRInstallations installations]
[ 11 ] -[FIRMessagingTokenManager init]
[ 12 ] -[FIRMessaging start]
[ 13 ] __36+[FIRMessaging componentsToRegister]_block_invoke
[ 14 ] -[FIRComponentContainer instantiateInstanceForProtocol:withBlock:]
[ 15 ] -[FIRComponentContainer instanceForProtocol:]
[ 16 ] +[FIRMessaging messaging]
[ 17 ] firebase::messaging::Initialize(firebase::App const&, firebase::messaging::Listener*, firebase::messaging::MessagingOptions const&)
[ 18 ] firebase::messaging::Initialize(firebase::App const&, firebase::messaging::Listener*)
[ 19 ] firebase::AppCallback::NotifyAllAppCreated(firebase::App*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, firebase::InitResult, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, firebase::InitResult> > >*)
[ 20 ] firebase::app_common::AddApp(firebase::App*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, firebase::InitResult, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, firebase::InitResult> > >*)
[ 21 ] firebase::App::Create(firebase::AppOptions const&, char const*)
[ 22 ] firebase::App::Create()
[ 23 ] firebase::AppGetOrCreateInstance(firebase::AppOptions const*, char const*)
[ 24 ] FirebaseApp_CreateInternal_m7C9DA4F992AD0B435BE57A04D5BE3537AB2A0233
[ 25 ] CreateDelegate_Invoke_m9FC551133A4F9301FB4F107B90F7C98A66F95BE9
[ 26 ] FirebaseApp_CreateAndTrack_m7FC684DE29AF92053981EB1323B38DBC4D34AC26
[ 27 ] AAAAAAAGameComponent_OnApplicationQuit_m8E6CB4AEC4CC60B2BE5CDC524C71FF4D7177CCA8
[ 28 ] RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**)
[ 29 ] il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**)
[ 30 ] scripting_method_invoke
[ 31 ] Invoke
[ 32 ] HandleNotifications
[ 33 ] SendMessageAny
[ 34 ] SendMessageToEveryone
[ 35 ] NotifyPlayerQuit
[ 36 ] PlayerCleanup
[ 37 ] UnityCleanup
[ 38 ] -[UnityAppController applicationWillTerminate:]
[ 39 ] -[AAAAAAAAppController applicationWillTerminate:]
[ 40 ] <redacted>
[ 41 ] <redacted>
[ 42 ] <redacted>
[ 43 ] <redacted>
[ 44 ] <redacted>
[ 45 ] <redacted>
[ 46 ] <redacted>
[ 47 ] <redacted>
[ 48 ] <redacted>
[ 49 ] <redacted>
[ 50 ] <redacted>
[ 51 ] <redacted>
[ 52 ] <redacted>
[ 53 ] <redacted>
[ 54 ] <redacted>
[ 55 ] <redacted>
[ 56 ] _CFRunLoopRunSpecific
[ 57 ] _GSEventRunModal
[ 58 ] <redacted>
[ 59 ] _UIApplicationMain
[ 60 ] -[UnityFramework runUIApplicationMainWithArgc:argv:]
[ 61 ] main
[ 62 ] 0x103265ce4

**Comment by paulinon** [comment]
Hi @x-henry-tian,

Thanks for reporting this. In order to identify the cause of this behavior, could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps to reproduce the issue?
