### ISSUE TITLE
[Bug] Firebase not work with GoogleSignIn SDK

### ISSUE THREAD

**Issue by gabry90** [firebase/quickstart-unity#1248]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.31f1
  * Firebase Unity SDK version: 8.8.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database (Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Additional SDKs you are using: GoogleSignIn-Unity (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? 
no

What's the issue repro rate? (eg 100%, 1/5 etc) 
100%

What happened? How can we make the problem occur?

I have implemented GoogleSignIn-Unity for authentication via google as a provider on Firebase.

I removed the Unity.Compat.dll and Unity.Task.dll files inside the Parse / Plugins root because the GoogleSignIn SDK for Unity was giving me the incompatibility error with the Tasks. The two dlls were already disabled but this was obviously not enough, I had to remove them. And here we have two strange problems:

1) Since I removed the two dlls in the root (obviously leaving those inside the dontnet45 folder enabled) Firebase uses the mscorlib tasks instead of the Firebase ones (and in fact all the Tasks magically become awaitable), and I have absolutely no idea of ​​why it does so but above all how to make it re-point to the Firebase Tasks. The only way seems to put the two Net 3.5 dlls back in the root (disabled) but of course I can't do that as GoogleSignIn breaks ...

2) In the built Android (.apk) version any call I make to FirebaseDatabase be it a GetValueAsync (), a SetValueAsync () or any other operation block at that point! (This problem for example does not occur with FirebaseAuth). Even doing a development build i saw that it doesn't even enter the ContinueWithOnMainThread. In the Editor, however, everything works.

It is useless to say that in this way it is not possible to work, remove two dlls because otherwise nothing works, but removing them generates other problems. So what's the solution?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

Example project with Google SignIn + FirebaseAuth + FirebaseDatabase:
https://we.tl/t-yiRfKZ12pT

The project has only the dotnet45 dlls inside the Parse / Plugins folder, but by opening the TestFirebaseTask script you can see that the methods of both GoogleSignIn and FirebaseApp are pointing to mscorlib tasks instead of Unity.Task and this causes all the problems mentioned above

See this attachment and you can see in visual studio popup Task referenced to mscorlib instead Unity.Task
[https://ibb.co/kmRYtTD](url)

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @gabry90,

Thanks for the information you provided. In order to identify what's causing this behavior, could you provide the complete steps needed to replicate the issue? I've downloaded the sample project you provided, but I couldn't seem to find a scene for the build.

Additionally, could you provide the error logs resulted from the incompatibility with the tasks as you've mentioned?

**Comment by gabry90** [comment]
There is no scene for the build because it is not needed. Just open the TestFirebaseTaskClass script to see that the GoogleSingIn and Firebase tasks are pointing to those of mscorlib and not to those of Unity.Task.

Re-adding the two .Net 3.5 dlls, disabled, in the root of Parse\Plugins the console does not generate errors, and this is strange, but inside GoogleSignIn Visual Studio highlights the conflict error. In fact, intellisense cannot identify the correct return type if you try to ignore the error.

Here is the link to the error screen: [https://ibb.co/Tc9q2Yx](https://ibb.co/Tc9q2Yx)

As for the second problem I can no longer find it, I honestly do not know why the calls to Firebase Database were pending without entering the callbacks. It would be advisable, whatever the circumstances, to always call the callbacks avoiding silent errors and leave the execution of the code pending without the possibility of resuming it.

**Comment by paulinon** [comment]
Hi @gabry90,

I looked at the error message you provided which apparently is in the `GoogleSignIn.cs` file, and it doesn't seem to occur on my end, regardless if the .dll files were disabled or not.

Also, does the `TestFirebaseTaskClass.cs` file look like this in your implementation? 
<img width="509" alt="Screen Shot 2022-04-07 at 9 40 38 PM" src="https://user-images.githubusercontent.com/58971522/162212551-5f3bffeb-5d49-4f66-8afc-a60d7c1b1406.png">

Please provide more context on how the tasks are "pointing to those of mscorlib".

Additionally, [version 8.9.0](https://firebase.google.com/support/release-notes/unity#version_890_-_april_6_2022) of the SDK has been released recently. Could you try it out and see if it makes a difference?

**Comment by gabry90** [comment]
tried to update firebase SDK to version 8.9.0 but the problem is the same. I attach 2 screenshots:

1) [https://ibb.co/pPyPj9D](https://ibb.co/pPyPj9D): Unity.Task.dll and Unity.Compat.dll (.Net 3.5) present but disabled.

2) [https://ibb.co/pPyPj9D](https://ibb.co/pPyPj9D): Unity.Task.dll and Unity.Compat.dll (.Net 3.5) removed. Error gone but the ContinueWithOnMainThread method extension points to mscorlib instead of Unity.Task. Without this extension the Firebase Tasks will correctly point to Unity.Task.

**Comment by a-maurice** [comment]
That is very odd that you are seeing different behavior when it is present but disabled, vs removed.  It should be the same, where Unity is just not aware of that file.  Is it possible that it is still enabled, I know the UI for enabling/disabling is a bit complicated, with the one checkbox changing what all the other checkboxes do.

The two dlls under the dotnet45 folder are there to pass along the definitions to the underlying System.Threading.Tasks.Task, which was not present in older versions of Unity, but is now present.

When you added the Firebase SDKs, did you add the ones from the dotnet4 folder?  As those should be the ones with the correct settings.

**Comment by gabry90** [comment]
> That is very odd that you are seeing different behavior when it is present but disabled, vs removed. It should be the same, where Unity is just not aware of that file. Is it possible that it is still enabled, I know the UI for enabling/disabling is a bit complicated, with the one checkbox changing what all the other checkboxes do.
> 
> The two dlls under the dotnet45 folder are there to pass along the definitions to the underlying System.Threading.Tasks.Task, which was not present in older versions of Unity, but is now present.
> 
> When you added the Firebase SDKs, did you add the ones from the dotnet4 folder? As those should be the ones with the correct settings.

I know how dll imports work, I have also worked with asmdef in much more complicated contexts, finding myself also managing any conflicts. I have already tried different solutions and combinations and the error looks like that. As long as the Net 3.5 dlls exist (disabled) everything works, when I go to remove them, however, it seems that the Net 4.5 dlls alone are not enough. I also came to think that it is a Visaul Studio intellisense problem or something related more to the development FE than to Unity ... at the point I don't know what to think anymore ...

**Comment by DellaBitta** [comment]
Hi @gabry90,

I'm sorry to say that we cannot reproduce this here and the issue seems to be in the behavior of the editor, which doesn't seem to be correctly disabling or enabling the libraries.  If there's something that you can provide that we can easily reproduce then we welcome it and we can investigate further.  Otherwise I recommend reaching out to Unity support to determine why the editor doesn't properly honor the disable / enable operations.
