### ISSUE TITLE
[Bug] Firebase App (Core) 8.9.0 - Internal build system error. Backend exited with code 2.

### ISSUE THREAD

**Issue by AAulicino** [firebase/quickstart-unity#1252]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.2.19f1
  * Firebase Unity SDK version: 8.9.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: App (Core)
  * Other Firebase Components in use: Any
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: macOS Monterey 12.3.1 
  * Platform you are targeting: Any
  * Scripting Runtime: Any

### [REQUIRED] Please describe the issue here:

Unity 2021.2.19f1 is unable to compile when using Firebase 8.9.0.  Unity 2020.3.32f1 works fine.

> Internal build system error. Backend exited with code 2.
> STDOUT:
> Finished compiling graph: 107 nodes, 362 flattened edges (362 ToBuild, 0 ToUse), maximum node priority 13
> STDERR:
> tundra: error: Unexpected stdin

#### Steps to reproduce:

OS: macOS Monterey 12.3.1

1. Download [External Dependency Manager for Unity 1.2.170.tgz](https://dl.google.com/games/registry/unity/com.google.external-dependency-manager/com.google.external-dependency-manager-1.2.170.tgz).
2. Download [Firebase App (Core) 8.9.0.tgz](https://dl.google.com/games/registry/unity/com.google.firebase.app/com.google.firebase.app-8.9.0.tgz).
3. Create an empty Unity Project using Unity 2021.2.19f1
4. In package manager import both External Dependency Manager and Firebase App (Core) tarballs.
5. Add either of `Assets/Firebase/google-services.json` or `Assets/Firebase/GoogleService-Info.plist` file to the project.
6. If unity hasn't already, reimport or create any C# script to trigger a recompile.
7. Unity compiler is now dead.
 
> Internal build system error. Backend exited with code 2.
> tundra: error: Unexpected stdin

Unable to reproduce using unity 2020.3.32f1.

#### [Sample project](https://drive.google.com/file/d/1OFJsZjuXfWJwFoxyoH0r0Y9aYD_iV06T/view?usp=sharing) repro:

1. Open Project using unity 2021.2.19f1
2. Reimport `NewBehaviourScript.cs`

#### What's the issue repro rate?
100%

**Comment by paulinon** [comment]
Hi @AAulicino,

Thanks for bringing this to our attention. I was able to observe this behavior on my end as well, even after removing a C# script.

That being said, I've relayed this issue to the team. You may refer to this thread for updates.
