### ISSUE TITLE
[Question] dynamic link did not open app store when app is not installed

### ISSUE THREAD

**Issue by SonmezYigithan** [firebase/quickstart-unity#1253]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.29f1
  * Firebase Unity SDK version: 8.8.0
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Dynamic Links 
  * Other Firebase Components in use: Auth, Database 
  * Additional SDKs you are using: Facebook 
  * Platform you are using the Unity editor on: Mac 
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:

I want to generate short dynamic links inside the app for every user. I managed to do it for android users but in iOS the short links launch website instead of app store page. 

Heres my code

` // CREATES LONG DYNAMIC LINK
            var components = new Firebase.DynamicLinks.DynamicLinkComponents(
                // The base Link.
                new System.Uri("https://example.com/?"),
                // The dynamic link URI prefix.
                "https://example.page.link")
            {
                IOSParameters = new Firebase.DynamicLinks.IOSParameters("com.Example.Example"),
                AndroidParameters = new Firebase.DynamicLinks.AndroidParameters("com.Example.ExampleApp"),
            };
            var options = new Firebase.DynamicLinks.DynamicLinkOptions
            {
                PathLength = DynamicLinkPathLength.Short,
            }; `

I found [this post](https://stackoverflow.com/questions/51211069/dynamic-link-firebase-did-not-open-app-store-when-app-uninstalled#:~:text=You%20need%20to%20add%20the%20isi%20param%20to%20your%20URL,following%20your%20app%20store%20ID.) but couldn't figure out how to add isi parameter to my uri

**Comment by paulinon** [comment]
Hi @SonmezYigithan,

According to our [documentation](https://firebase.google.com/docs/dynamic-links/create-manually#parameters), the `isi` parameter corresponds to the App Store ID. To add this as a dynamic link component, you can add something like this after declaring your `components` variable:

`components.IOSParameters.AppStoreId = "<app-store-id>";`

I'll be closing this for now. Let me know if an issue arises with this solution.

**Comment by SonmezYigithan** [comment]
That solved the issue. The link is now directing iOS users to the app store. But now I can't receive the dynamic link after user opened the app from the app store. It works fine on the android side.

**Comment by paulinon** [comment]
Hi @SonmezYigithan,

I'd like you to verify a few things:

1. Check the app's bundle ID against the `ibi` parameter of the dynamic link and confirm that they match.
2. If you have the optional `ius` parameter added to the Dynamic Link, the custom scheme URL with matching value must be set in the app.
3. In the Capabilities tab of your app's Xcode project, verify `Associated Domains` is enabled and add the following to the `Associated Domains` list: `applinks:{your_dynamic_links_domain}`. Check out this [guide](https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app) for more details.
4. Verify if `https://{your_dynamic_links_domain}/apple-app-site-association` contains an entry for your app and if `{team-id}.{bundle-id}` values are correct for your app.

**Comment by SonmezYigithan** [comment]
Hello @paulinon 

1. I checked the ibi parameter and it matches with my app bundle ID
2. I don't use ius parameter
3. I enabled the Associated Domains in Xcode.

I don't understand the 4th step. can you clarify? 
here's whats inside the link
`{"applinks":{"apps":[],"details":[{"appID":"4********Z.com.Example.Example","paths":["NOT /_/*","/*"]}]}}`

**Comment by paulinon** [comment]
Thanks for clarifying, @SonmezYigithan.

Version 8.9.0 of the SDK has been released recently. Could you check if this makes any difference? If not, I'd like to verify a few more things regarding your implementation:

1. Check the [OAuth 2.0 Client IDs](https://console.cloud.google.com/apis/credentials?project_) in Google Cloud Console, make sure that your iOS app doesn't have a duplicate Bundle ID.
2. Make sure that your [debug view](https://firebase.google.com/docs/dynamic-links/debug) doesn’t have any warning or errors as this could affect the link's behavior.
3. When you long tap the FDL and select "Open in Safari" option, it will disable the Universal Links in the device for your domain. FDL is using iOS Universal Links under the hood and FDL will not work correctly if it's disabled. To re-enable the Universal Links, you'll need to long tap the FDL and select the "Open in App" option.
4. Enabling the app preview page on custom Dynamic Link is not required. However, it's recommended that you enable the app preview page to guarantee unique matches from Dynamic Links on iOS. The app preview page also more reliably sends users to the most appropriate destination (such as your app) by minimizing unnecessary system dialog and enabling users to navigate out of in-app browsers. You could check our docs [here](https://firebase.google.com/docs/dynamic-links/link-previews#app_preview_pages) for more details regarding iOS app preview pages.

**Comment by SonmezYigithan** [comment]
Hey I solved the issue

Heres how I solved:
1. I had 3 duplicates at [OAuth 2.0 Client IDs](https://console.cloud.google.com/apis/credentials?project_) for iOS created by google. Deleted the duplicates.
2. I had an error at debug view saying there's no app bundle ID. I added app bundle ID as a new parameter in the dynamic link
3. I added Associated Domains in Xcode.
