### ISSUE TITLE
[Question] Firebase Database many errors in build.

### ISSUE THREAD

**Issue by JellyBean180** [firebase/quickstart-unity#1254]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____ 2020.3.25f1
  * Firebase Unity SDK version: _____Unknown, the latest.
  * Source you installed the SDK: _____ .unitypackage
  * Problematic Firebase Component: _____Database
  * Other Firebase Components in use: _____ Database
  * Additional SDKs you are using: _____Google Play Services from GitHub
  * Platform you are using the Unity editor on: _____ Windows
  * Platform you are targeting: _____Android
  * Scripting Runtime: _____ IL2CPP (Google wont allow any other to be uploaded)

### [REQUIRED] Please describe the question here:

Hello,
I'm trying to get Firebase to work with Google Play Services. Google is working. Although I'm not getting the Google Play login popup. I'm trying to save to Firebase Database. When the game Builds and Runs I get this error

I've added the google-services.json from my Firebase project to the Assets folder.

2022/04/11 15:15:57.056 10039 10057 Error firebase Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly.
2022/04/11 15:15:57.060 10039 10057 Error Unity InitializationException:  Firebase app creation failed.
2022/04/11 15:15:57.060 10039 10057 Error Unity   at Firebase.FirebaseApp.CreateAndTrack (Firebase.FirebaseApp+CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) [0x00000] in <00000000000000000000000000000000>:0 
2022/04/11 15:15:57.060 10039 10057 Error Unity   at Firebase.Database.FirebaseDatabase.get_DefaultInstance () [0x00000] in <00000000000000000000000000000000>:0 
2022/04/11 15:15:57.060 10039 10057 Error Unity   at DatabaseMaster.Start () [0x00000] in <00000000000000000000000000000000>:0 
2022/04/11 15:15:57.060 10039 10057 Error Unity

**Comment by paulinon** [comment]
Hi @JellyBean180,

I noticed that you're using a 2020 version of the Unity editor. Are your Android resources contained in a directory with a `.androidlib` suffix? If not and a `Assets/Plugins/Android/Firebase` directory is found instead, rename this to `Assets/Plugins/Android/Firebase.androidlib` and make sure it contains these files:
- `AndroidManifest.xml `
- `project.properties`
- `res/values/google-services.xml`

I'll be closing this for now. Let me know if an issue arises with this solution.

**Comment by JellyBean180** [comment]
> Assets/Plugins/Android/Firebase

I changed the folder from Assets/Plugins/Android/FirebaseApp.androidlib to Firebase.androidlib and tried to build and run again. It failed to finish. I removed the Firebase.androidlib folder since the FirebaseApp.androidlib folder was re-built and it all works now. Not sure what it changed but it's saved to the Database.

Thank you for helping.
