### ISSUE TITLE
[Question] iOS Dynamic Linking not working with Messaging - Issue with our setup?

### ISSUE THREAD

**Issue by HarrisonShort** [firebase/quickstart-unity#1256]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.2.14f1
  * Firebase Unity SDK version: 8.8.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Messaging, Dynamic Links
  * Other Firebase Components in use: Analytics, Auth, Storage
  * Additional SDKs you are using: Facebook, (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows, Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

We are in the process of implementing Dynamic Links and our app is heavily dependent on notifications via Firebase Messaging. We are finding an issue in our set up where depending on the status of the boolean `FirebaseAppDelegateProxyEnabled` in the Info.plist file, Firebase Messaging and Dynamic Links are fully functional somewhat mutually exclusive of each other.

If `FirebaseAppDelegateProxyEnabled` is set to true/1:
- Notifications can be received as per usual.
- Dynamic Links will not open the app, but instead just open the App Store to our app's store page.

If `FirebaseAppDelegateProxyEnabled` is set to false/0:
- Notifications are not received. I believe this is correct functionality, as [this](https://firebase.google.com/docs/cloud-messaging/ios/client) page states not to disable method swizzling when using Firebase Unity SDK on iOS, as it causes issues with FCM token handling.
- Dynamic Links open the app and trigger functionality as expected. We initially tested this out due to finding [this](https://stackoverflow.com/questions/70574110/firebase-dynamic-links-on-unity-ios-says-deep-link-does-not-contain-valid-requi) StackOverflow question, which made the change in a post-build process.

Other things we have done:
- Added `FirebaseDynamicLinksCustomDomains` array to our Info.plist, with our URL as an element of this array.
- Added Associated Domains capability in Xcode, with "applinks:<URL>" as an element (Dynamic Links were working before this change, as long as `FirebaseAppDelegateProxyEnabled` was set to false).
- Checked the apple-app-site-association page, which correctly lists our Team ID and Bundle ID.

It is likely that we have done something incorrectly in our set up, but we are just wondering what it could be. Hope someone will have some idea of where we've gone wrong! Thank you in advance. (:

**Comment by paulinon** [comment]
Hi @HarrisonShort,

Thanks for reporting this issue. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps to replicate the issue so that we can identify what's causing this behavior?

**Comment by HarrisonShort** [comment]
> Hi @HarrisonShort,
>
> Thanks for reporting this issue. Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps to replicate the issue so that we can identify what's causing this behavior?

Thanks for your reply @paulinon.
Interestingly, I was trying to recreate this using the Firebase Quickstart projects, and it worked fine, whether I had included FirebaseAppDelegateProxyEnabled in the Info.plist, or not. So I'm going to have to do some further testing with our actual app project, to see if its actually something else that's causing the behaviour.

**Comment by HarrisonShort** [comment]
Have just confirmed that the initial issue is not appearing. I believe it was actually something to do with our set up, perhaps related to adding the Associated Domains and Keychain Sharing capabilities that were outlined in the Dynamic Links Quickstart guide. 

Thanks for your attention! (:
