### ISSUE TITLE
[Bug] DllNotFoundException - Apple Intel

### ISSUE THREAD

**Issue by vincentkrp** [firebase/quickstart-unity#1263]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.1f1
  * Firebase Unity SDK version: 8.9.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: none
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Mac / MacBookAir (2017, Intel Core i5)
  * Platform you are targeting: desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

After importing the FireBaseAuth package into a new Unity project and initializing it with

auth = FirebaseAuth.DefaultInstance

My issue is that when entering play mode I get an error as follows:

DllNotFoundException: FirebaseCppApp-8_9_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:117)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:137)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/FirebaseApp.cs:67)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
AuthManager.Awake () (at Assets/Scripts/AuthManager.cs:34)

Around line 34 which the exception points to I'm executing following code (line 34 in detail is "FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>"):
`    private void Awake()
    {
        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
            dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available)
            {
                //If availabel initialize FireBase
                InitializeFirebase();
            }
            else
            {
                Debug.LogError("Couldn't resolve all Firebase dependencies: " + dependencyStatus);
            }
        });
    }`

**At first it may look like it's the same issue as firebase/firebase-unity-sdk#278 , but as far as I've read the issue there was specifically for Apple Silicon (M1) and Intel seemed to work just fine (according to most of the descriptions in that thread)**

Additionally I don't get a popup about an untrusted developer for FirebaseCppApp-8_9_0.bundle as it normally should be the case, unless I try to open it manually with the Terminal or Console through Finder.

#### Steps to reproduce:

I've also tried it out for the **quickstart-unity/auth/testapp project** and also when entering play-mode I get **following error-message in the console**:

DllNotFoundException: FirebaseCppApp-8_9_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:117)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:137)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.GOobKx5vLv/firebase/app/client/unity/proxy/FirebaseApp.cs:67)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Auth.UIHandler.Start () (at Assets/Firebase/Sample/Auth/UIHandler.cs:80)

**Additionally the message on the game-screen puts out:** 

One or more firebase dependencies are not present.
Current dependency status: UnavailableOther

I've also tried out a different FirebaseAuth version (8.8.0) but still getting the same error.

**Comment by paulinon** [comment]
Hi @vincentkrp,

Thanks for reporting this. When you've encountered the alert saying that Firebase "cannot be opened because the developer cannot be verified",  I'd like you to go to your Mac’s `System Preferences` > `Security & Privacy` then Click `Allow Anyway` corresponding to the Firebase bundle file. 

Let me know if this solution worked for you. Otherwise, please provide the complete steps you performed before facing this issue.

**Comment by vincentkrp** [comment]
Like I said before, I don't even get that message in my Security Settings hust through entering play mode. I can only get said message about an unverified developer when navigating to the FirebaseCppApp-8_9_0.bundle file through Finder and the trying to open it via Terminal or Console.
And even after allowing this file to be opened anyways it doesn't solve the problem.

**As for the steps for encoutering this in the quickstart testproject:**

1. I created and set up a project in the FirebaseConsole for the unity quickstart auth testapp
2. I downloaded the google-services.json and the firebase unity sdk
3. I downloaded quickstart-unity-master and added the /auth/testapp/ to my unity-hub
4. I opened the project and navigated to the Main Scene
5. I imported the dotnet4/FirebaseAuth.unitypackage through Assets > Import Package > Custom Package
6. I added the google-services.json to Assets/Firebase/Sample/Auth
7. I then tried to build for Desktop macOS
8. The Build was completed and executed and it just showed the following on the screen: One or more firebase dependencies are not present.
Current dependency status: UnavailableOther
9. I closed the build and tried it out in Play-Mode in the Unity-Editor when the DllNotFoundException was presented to me in the Unity-Console

**Comment by paulinon** [comment]
Thanks for the clarification, @vincentkrp. [Version 8.10.0](https://firebase.google.com/support/release-notes/unity#version_8100_-_may_2_2022) of the SDK has been released recently. Could you try it out and see if the issue persists?

**Comment by steffen-roemer** [comment]
same issue for me with 8.10.0

**Comment by vincentkrp** [comment]
I've tried it with Version 8.10.0 but I still got the same Exception in the Unity-Console

**Comment by vincentkrp** [comment]
Update: 
I've re-imported the Firebase SDK and now and tried to unlock `FirebaseCppApp-8_10_1.bundle`
through `usr/bin/xattr -d com.apple.quarantine path/to/project/Assets/Firebase/Plugins/x86_64/FirebaseCppApp-8_10_1.bundle` through terminal (didn't throw an error). I also did the corresponding process for `FirebaseCppAuth.bundle`
Then when i tried to enter Play-Mode i first got the Error: `Backend produced unparsable log entry eIndex":4}`
I closed the unity-project and Editor and reopened them. At that point I didn't get the previous Error but again the DllNotFoundException.
I thought I'd give this update as it may help figuring out the problem

**Comment by vincentkrp** [comment]
Another thing I've noticed is that the DllNotFound Exception differs from the one I initially got and stated in my original BugReport.
So here's the current one:
`DllNotFoundException: FirebaseCppApp-8_10_1 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/linux_unity/app/swig/Firebase.App_fixed.cs:3842)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/linux_unity/app/swig/Firebase.App_fixed.cs:3862)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/linux_unity/app/swig/Firebase.App_fixed.cs:4569)
Firebase.LogUtil..ctor () (at /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/app/src/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at /home/runner/work/firebase-unity-sdk/firebase-unity-sdk/linux_unity/app/swig/Firebase.App_fixed.cs:1852)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Auth.UIHandler.Start () (at Assets/Firebase/Sample/Auth/UIHandler.cs:80)`
(It's from the **quickstart-unity/auth/testapp project** not from my Project where I had the AuthManager-Script)

**Comment by vincentkrp** [comment]
When I check the `load on startup` option though I am prompted with the following Warning:
`Plugins: Couldn't open Assets/Firebase/Plugins/x86_64/FirebaseCppApp-8_10_1.bundle, error: dlopen(Assets/Firebase/Plugins/x86_64/FirebaseCppApp-8_10_1.bundle, 2): Symbol not found: _OBJC_CLASS_$_NSConstantIntegerNumber
  Referenced from: Assets/Firebase/Plugins/x86_64/FirebaseCppApp-8_10_1.bundle (which was built for Mac OS X 11.6)
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 in Assets/Firebase/Plugins/x86_64/FirebaseCppApp-8_10_1.bundle
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

**Comment by vincentkrp** [comment]
There's also no such file as `Foundation.framework` in the `/System/Library/Frameworks/`-directory. Is this normal?

**Comment by luckin403** [comment]
I encountered a similar problem. Do you have any new information on this issue?
