### ISSUE TITLE
[Bug] Not able to build for Android

### ISSUE THREAD

**Issue by calinpavel787** [firebase/quickstart-unity#1269]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.29f1
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: .unitypackeage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: Crashlytics, DynamicLinks (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

#### Steps to reproduce:

Open Unity > Insert keystore password > Build for Android

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Didn't test with the quick start

What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
CommandInvokationFailure: Gradle build failed. 
/Applications/Unity/Hub/Editor/2020.3.29f1/PlaybackEngines/AndroidPlayer/OpenJDK/bin/java -classpath "/Applications/Unity/Hub/Editor/2020.3.29f1/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
]
stdout[

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

> Task :unityLibrary:FirebaseCrashlytics.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:extractDeepLinksRelease
> Task :launcher:checkReleaseDuplicateClasses UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseLibraryResources
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseRFile
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileToJarRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeToJarRelease
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibRuntimeToJarRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibCompileToJarRelease
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseCrashlytics.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:packageReleaseAssets

> Task :launcher:processReleaseManifest
/Volumes/Macintosh HD/{unity project}/Temp/gradleOut/launcher/src/main/AndroidManifest.xml:4:2-98 Warning:
	uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:4 to replace another declaration but no other declaration present

> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :launcher:processReleaseResources
> Task :launcher:compileReleaseJavaWithJavac UP-TO-DATE
> Task :launcher:compileReleaseSources UP-TO-DATE
> Task :launcher:lintVitalRelease
> Task :launcher:dexBuilderRelease
> Task :launcher:desugarReleaseFileDependencies UP-TO-DATE
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseJavaResource UP-TO-DATE
> Task :launcher:collectReleaseDependencies UP-TO-DATE
> Task :launcher:sdkReleaseDependencyData UP-TO-DATE
> Task :launcher:mergeReleaseJniLibFolders UP-TO-DATE
> Task :launcher:validateSigningRelease UP-TO-DATE
> Task :launcher:mergeReleaseNativeLibs FAILED
> Task :launcher:mergeExtDexRelease
78 actionable tasks: 43 executed, 35 up-to-date
]
exit code: 1

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
None
```

**Comment by paulinon** [comment]
Thanks for reporting this, @calinpavel787. Using the information you provided, I haven't been able to reproduce the issue so far. Could you try if updating your Unity editor to its latest version (2021.3.2f1 is the latest LTS version) makes any difference? I've used version 2021.3.1f1, so it's possible that an update is needed.

**Comment by calinpavel787** [comment]
> Thanks for reporting this, @calinpavel787. Using the information you provided, I haven't been able to reproduce the issue so far. Could you try if updating your Unity editor to its latest version (2021.3.2f1 is the latest LTS version) makes any difference? I've used version 2021.3.1f1, so it's possible that an update is needed.

Thank you @paulinon for the support. I updated the project to the version you indicated, but I'm still not able to create an Android build.

```
CommandInvokationFailure: Gradle build failed. 
/Applications/Unity/Hub/Editor/2021.3.2f1/PlaybackEngines/AndroidPlayer/OpenJDK/bin/java -classpath "/Applications/Unity/Hub/Editor/2021.3.2f1/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Note: /Volumes/Macintosh HD/{user project}/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/java/com/unity3d/player/UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
]
stdout[
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

> Task :unityLibrary:FirebaseCrashlytics.androidlib:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResValues
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources
> Task :unityLibrary:generateReleaseResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseResources
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseResources
> Task :launcher:extractDeepLinksRelease
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:extractDeepLinksRelease
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseManifest
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources
> Task :unityLibrary:FirebaseCrashlytics.androidlib:parseReleaseLocalResources
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish
> Task :unityLibrary:FirebaseCrashlytics.androidlib:prepareLintJarForPublish
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseShaders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseCrashlytics.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:FirebaseCrashlytics.androidlib:generateReleaseRFile
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:generateReleaseRFile

> Task :launcher:processReleaseManifest
/Volumes/Macintosh HD/{user project}/Library/Bee/Android/Prj/IL2CPP/Gradle/launcher/src/main/AndroidManifest.xml:4:2-98 Warning:
	uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:4 to replace another declaration but no other declaration present

> Task :launcher:prepareLintJar
> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:FirebaseCrashlytics.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs
> Task :launcher:javaPreCompileRelease
> Task :launcher:mergeReleaseShaders
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibCompileToJarRelease
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileToJarRelease
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:bundleLibRuntimeToJarRelease
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeToJarRelease
> Task :unityLibrary:FirebaseCrashlytics.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseCrashlytics.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:FirebaseCrashlytics.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:stripReleaseDebugSymbols
> Task :launcher:mergeReleaseResources
> Task :launcher:processReleaseResources
> Task :launcher:generateReleaseAssets UP-TO-DATE

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:collectReleaseDependencies
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:bundleLibRuntimeToJarRelease
> Task :unityLibrary:bundleLibCompileToJarRelease
> Task :launcher:sdkReleaseDependencyData
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:mergeReleaseJavaResource
> Task :launcher:compileReleaseSources
> Task :launcher:lintVitalRelease
> Task :launcher:dexBuilderRelease
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:desugarReleaseFileDependencies
> Task :launcher:validateSigningRelease
> Task :launcher:mergeReleaseNativeLibs FAILED
> Task :launcher:mergeExtDexRelease
78 actionable tasks: 78 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action`1[T] progress) (at <cf82a25f0a8443eb910fd35454292555>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action`1[T] progress) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <cf82a25f0a8443eb910fd35454292555>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, AndroidPlayerBuildProgram.Data.AndroidPlayerBuildProgramOutput buildProgramOutput) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <cf82a25f0a8443eb910fd35454292555>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:370)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189) 
```

**Comment by calinpavel787** [comment]
Hello, I'm coming back with some good news:

Mainly I think was my fault being very messy with the project: I changed multiple times the branches, updated the Firebase twice, and probably that was it. But I'm glad to let everyone know how I managed to solve this issue:
1. Roll back to 2020.3.29f1
2. Discard all the modifications and open a clean git without unstashed changes
3. Update the Firebase to the latest version (8.10.1 in my case)
4. Restart the Unity Editor and try to build.

Tested building for Android & iOS and everything is fine. If you need further information, I will let this issue open for investigation if needed. 

Thanks @paulinon once more for your help once more.

**Comment by paulinon** [comment]
Glad to hear that you've resolved the issue, @calinpavel787. That being said, I'll be closing this ticket. Let me know if an issue arises.
