### ISSUE TITLE
How can I fix this? - Unity 2017.1.2.p4

### ISSUE THREAD

**Issue by faiguago** [firebase/quickstart-unity#127]
IOException: Win32 IO returned ERROR_BROKEN_PIPE. Path: D:\_UnityProjects\_Work\PortalProject\[Unknown]
System.IO.FileStream.FlushBuffer (System.IO.Stream st) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:1040)
System.IO.FileStream.FlushBuffer () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:1054)
System.IO.FileStream.Flush () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileStream.cs:859)
System.IO.StreamWriter.Flush () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/StreamWriter.cs:191)
System.IO.StreamWriter.Dispose (Boolean disposing) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/StreamWriter.cs:162)
UnityEditor.HostView:OnGUI()

**Comment by stewartmiles** [comment]
Do you have any more context, what are you doing?

Cheers,
Stewart

**Comment by stewartmiles** [comment]
Since we have no additional information, I'm closing this issue.  Let us know if you can provide additional information about your problem.
