### ISSUE TITLE
[Question] Crashlytics won't build for iOS: Arm64 function not 4-byte aligned

### ISSUE THREAD

**Issue by equizo** [firebase/quickstart-unity#1270]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.10
  * Firebase Unity SDK version: 8.0.0
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Auth, Database
  * Additional SDKs you are using: –
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:
Can't make iOS build with imported Crashlytics from cocoaPods.
![photo_2022-05-11_13-45-49](https://user-images.githubusercontent.com/6953056/167833319-83631906-5606-49f5-bcbd-89ca1a18b573.jpg)

**Comment by paulinon** [comment]
Hi @equizo,

Could you try if this issue persists using the latest version ([8.10.1](https://firebase.google.com/support/release-notes/unity#version_8101_-_may_4_2022))? If so, please provide the complete steps taken to reproduce this issue so that we can identify what's causing this behavior.

**Comment by equizo** [comment]
> Hi @equizo,
> 
> Could you try if this issue persists using the latest version ([8.10.1](https://firebase.google.com/support/release-notes/unity#version_8101_-_may_4_2022))? If so, please provide the complete steps taken to reproduce this issue so that we can identify what's causing this behavior.

That's solved the problem, thx!

**Comment by paulinon** [comment]
Glad to hear this, @equizo. I'll be closing this for now. Let me know if a new issue arises.
