### ISSUE TITLE
[Bug] Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found

### ISSUE THREAD

**Issue by revolt3r** [firebase/quickstart-unity#1274]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.34
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: .tgz with Unity Package Manager
  * Problematic Firebase Component: Messaging?
  * Other Firebase Components in use: Auth, Database, Firestore, Functions, Messaging, RemoteConfig, Analytics
  * Additional SDKs you are using: I think that's not relevant for this issue
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
Building fails with the following error:

Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.0.1-runtime.jar (com.google.firebase:firebase-iid:20.0.1) and jetified-firebase-messaging-23.0.3-runtime.jar (com.google.firebase:firebase-messaging:23.0.3)

**Comment by paulinon** [comment]
Hi @revolt3r,

Thanks for reporting this issue. Could you try these steps and see if they help resolve the issue:

1. Enable `Custom Gradle Properties Template` under `Player Settings` > `Settings for Android` > `Publishing Settings`
2. Make sure these lines of code are present in your `gradleTemplate.properties` file:
```
android.useAndroidX = true
android.enableJetifier = true
```
3. Select `Force Resolve` under `Assets` > `External Dependency Manager` > `Android Resolver`

I'm looking forward to your results.

**Comment by paulinon** [comment]
Thanks for the additional details, folks. I haven't encountered the error message yet. Could you provide the complete steps you've taken in replicating this issue?

**Comment by revolt3r** [comment]
There are no specific steps, it's just failing during a normal build.
With Firebase 8.6.2 the build finished with no issues.
After updating all Firebase libs to 8.10.1, the build started failing with this error.

It seems like the Messaging module is conflicting with the core Firebase (at least that's what it looks like from the error)
@paulinon did you try to make a build with this mix of modules and it succeeds with no issues?

**Comment by mrtrizer** [comment]
I'm updating Firebase for the first time. This is how I did this:
1. Downloaded Firebase 8.10.1 archive
2. Deleted `Firebase` directory from `Assets` (kept only `google-services.json` and `GoogleService-Info`)
3. Imported new packages one by one (Auth, Messaging, Functions, Firestore, Functions, Database, Analytics, Storage)
4. Restored `google-services` and `GoogleService-Info` in `Firebase` dir
5. Made Force Reload in External Dependency Manager
6. Tried to build as usually via `BuildPipeline.BuildPlayer` function

I also tried `Library` and `obj` dirs removal, didn't helped.

**Comment by paulinon** [comment]
Thanks for the additional context, folks. I was able to replicate this issue when multiple Firebase products are in the Unity project as you described. I'll relay my findings to the team.

That being said, I'll be marking this as a bug for now. You may refer to this thread for any updates.

**Comment by mrtrizer** [comment]
Btw looks like a duplicate or at least related problem [https://github.com/firebase/quickstart-unity/issues/1093](https://github.com/firebase/quickstart-unity/issues/1093)

The line `<androidPackage spec="com.google.firebase:firebase-iid:21.1.0"> </androidPackage>` has disapeared from MessagingDependencies.xml according to diff.

**Comment by a-maurice** [comment]
We've released a new version of the Firebase for Unity SDK, 9.0.0, available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0, that includes the fix for this. Thanks again for flagging it.
