### ISSUE TITLE
[Question] When do you plan to include iOS Firebase 9.0.0 in the Unity SDK?

### ISSUE THREAD

**Issue by jsvitek** [firebase/quickstart-unity#1276]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.0f1
  * Firebase Unity SDK version: 8.10.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the question here:
It is my understanding that the current version of Unity SDK 8.10.1 (May 4, 2022) includes iOS Firebase pods 8.11.0 (January 18, 2022). When do you plan to include latest iOS pods 9.0.0?

**Comment by paulinon** [comment]
Hi @jsvitek,

While we don't have a timeline that we can share, I got in touch with the team, and they said that this feature will be included in the next release. That being said, I'll be closing this for now.

**Comment by a-maurice** [comment]
FYI, the Firebase for Unity SDK version 9.0.0 is now out, which links against the iOS Firebase 9.0.0 SDKs.  It is available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0
