### ISSUE TITLE
Failing to connect to FCM on iOS using Unity 5.6

### ISSUE THREAD

**Issue by artourky** [firebase/quickstart-unity#128]
I've been using Firebase Messaging in my Game for the past couple of months (I can't remember the version of Firebase) but I use it for sending _notifications messages_ and _data messages_.

On Android, everything works smooth but for a couple of tries now iOS hasn't been working fully right.

The following is the requests we send, and they both work fine for Android.
but sometimes Data messages don't get received on iOS devices.

```csharp
string notificationMsg = "{ \"notification\" : " +
 "{ \"body\" : \"" + message + "\"," +
 " \"sound\" : \"default\"," +
 " \"icon\" : \"myicon\"" + " }," +
 " \"to\" : \"" + friendToken + "\" }";

string dataMsg = "{ \"data\" : " +
 "{ \"AmITheMaster\" : \"" + true + "\"," +
 " \"HaveIJoinedRoom\" : \"" + true + "\"," +
 " \"R U Online\" : \"" + message + "\"," +
 " \"SenderToken\" : \"" + myToken + "\"" +
 " \"SenderFBID\" : \"" + myFbId + "\"" + " }," +
 " \"to\" : \"" + friendToken + "\" }";
```

I traced and logged everything and I found that the problem has to do with Firebase.

The first run of the app on any iPhone or iPad there's a log message that says
`FCM: Connected to FCM`
but when I try to run the app a second time this log doesn't show again until I switch apps and return back to the game again.

So I've NOT tried to add a 'priority' or 'content_available' fields since I don't believe they will fix anything.

by the way, the notification works fine. Only **data messages don't get received**

Any help?

**Comment by artourky** [comment]
Okay, I've added **priority** & **content_available** fields to my **dataMsg** so it became like this:
```csharp
string dataMsg = "{ \"data\" : " +
 "{ \"AmITheMaster\" : \"" + true + "\"," +
 " \"HaveIJoinedRoom\" : \"" + true + "\"," +
 " \"R U Online\" : \"" + message + "\"," +
 " \"SenderToken\" : \"" + myToken + "\"" +
 " \"SenderFBID\" : \"" + myFbId + "\"" + " }," +
 " \"to\" : \"" + friendToken + "\"," +
 " \"content_available\" : " + true.ToString().ToLower() + "," +
 " \"priority\" : \"high\" }";
```
Now iOS app receive **dataMsg** through APNs according to Firebase docs and that's great.

but, The app still produces an error if I double press the home button and return to the app again it says that "_FIRMessaging is already connected_" so for now that fixed my issue.

If someone can fix the _FIRMessaging_ issue that would be great.

**Comment by artourky** [comment]
I couldn't for sure find something to tell me the Firebase SDK we've been using but I think It might be **3.0.1**

**Comment by stewartmiles** [comment]
@artourky did you intend to close this issue?

**Comment by artourky** [comment]
@stewartmiles yeah, since I found a way to solve my issue but if you have more info that can explain why that error might have happened that would great. Thanks

**Comment by stewartmiles** [comment]
Ah ok.  @artourky to clarify it looks like adding **priority** & **content_available** fields to your message solved your issue when sending data messages to iOS devices is that correct?  Also, was it the case that you intermittently saw issues or did iOS devices never receive data messages without these fields set?

**Comment by artourky** [comment]
@stewartmiles Yes, adding **priority** & **content_available** fields were the solution before that, iOS devices were not able to receive any data messages at all. Also, iOS devices didn't receive any data messages at all **unless** I double press the **Home** button to start switching apps & go back to the game. When I looked at the logs there was a log from FCM saying something like **"FCM: Connected to FCM Server."** and then It would receive the data Messages as normal.

I remember trying to send a data Message from the Firebase Console and iOS devices would receive it (that was before adding **priority** & **content_available** fields) so normally I thought there was an error in my code but Android Phones sent & received both notifications & data messages using that same code, so I tried a couple of things and adding **priority** & **content_available** did the trick.

I'd like to add that this was an old project so I thought it might be a problem with an older Firebase SDK so I upgraded the SDK and that seemed to solve that

> "FIRMessaging is already connected"

that I mentioned in my first post but **"FCM: Connected to FCM Server."** still only appeared after trying to switch apps and coming back to the game again.

**Comment by artourky** [comment]
Closing this since I've already solved my issue

**Comment by stewartmiles** [comment]
@artourky thanks for the additional details 👍
