### ISSUE TITLE
Getting UnavailableInvalid when getting FirebaseApp Dependencies

### ISSUE THREAD

**Issue by kultie** [firebase/quickstart-unity#1281]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.11f1(LTS)
  * Firebase Unity SDK version: 8.7.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Crashlytics, Analytics, Messaging
  * Additional SDKs you are using: Facebook, Google Sign In, Other SDK
  * Platform you are using the Unity editor on: Window
  * Platform you are targeting: Android, iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Calling `FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread` got DependencyStatus.UnavailableInvalid on some device

#### Steps to reproduce:
Got some log about the error in logging service (Record on 1 devices resulting that device cannot sign in using firebase auth)
Still could not reproduce on development environment and staging environment

#### Relevant Code:

```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(t =>
                {
                    var status = t.Result;
                    if (status == DependencyStatus.Available)
                    {
                        FirebaseApp app = FirebaseApp.DefaultInstance;
                        FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
                        isInitialized = true;
                        auth = FirebaseAuth.DefaultInstance;
                        FirebaseMessaging.SubscribeAsync(PortalSettings.GetPackageName()).ContinueWithOnMainThread(OnSubscribe);
                    }
                    else
                    {
                        Debug.LogError("Could not resolve all Firebase dependencies: " + status + "\n" + t.Exception);
                    }
                });
```

**Comment by kultie** [comment]
Hi @paulinon 
Thanks for the reply, I'll try to update the version 9.0.0
As for device detail It's come from our custom logging service
We got logging for
Device Model: Mi 8 UD (So Xiaomi note 8 Pro)
Running MIUI version 12.5.2
Android version 11

**Comment by 261232139** [comment]
I have the same problem, and I had updated the version 9.0.0
Device Modal:Huawei NOVA 9
Running Harmony OS 2.0.1

**Comment by kultie** [comment]
Still same issue with version 9.0.0.
The facebook and google auth function cause crash on the target device

**Comment by paulinon** [comment]
Hi @kultie,

Does this mean that `FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread` no longer causes the crash? It would be helpful if you provide a [minimal, reproducible example](FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread) of your implementation along with the complete steps to replicate the issue in order to analyze this behavior.

**Comment by kultie** [comment]
I can't really sure. Our client report that they still experiencing the crash after I deployed the build with version 9.0.0 (They confirmed that the crash also happen on the previous build)
Still have log DependencyStatus.UnavailableInvalid.
Since the firebase cannot initialized I can't have any log from the crashlytics report to identify what make the application crash

**Comment by paulinon** [comment]
Hi @kultie,

Could you provide the crash logs received by your client so that we can determine what's causing the issue?

**Comment by kultie** [comment]
![image](https://user-images.githubusercontent.com/20599099/172591931-eb884561-6b7a-48c1-9b1f-aca7ad26b9bd.png)
So far this is only thing I got from my client

**Comment by DellaBitta** [comment]
Hi @kultie and @261232139,

Google Play Services is required from many of the Firebase SDKs running on Android and I believe the problem you've encountered stems from [Google Play Services support](https://support.google.com/googleplay/answer/1727131?hl=en) on the phones you're reporting.

- I don't see `Huawei NOVA 9` in the supported devices list.
- I believe that the `Xiaomi note 8 Pro` is supported but Google Play Services does not come pre-installed on those devices, and the automatic installation of the services isn't supported.  Google Play Services must be installed manually by the user.

I'd recommend reaching out to the user, if possible, or adding information to the app to instruct users to install Google Play Services if CheckAndFixDependencies fails in this way.

I hope this helps!
