### ISSUE TITLE
Firebase Storage Error with SDK 9.0.0 and Xcode 13.0- "Concurrency is only available in ios 15.0.0"

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#1282]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
  * Firebase Unity SDK version: 9.0.0
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Firebase Storage(Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

I update Firebase SDK to 9.0.0,  and tried to build my project on Xcode 13.0 and I'm getting 10 errors about Firebase Storage-
"Concurrency is only available in ios 15.0.0 or newer"
It seems like the Firebase already had a fix for it for ios users, but what about Unity users?
Here- https://github.com/firebase/firebase-ios-sdk/issues/8685

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @shlighter,

Thanks for reporting this. I was able to reproduce this behavior on my end using the quickstart, and I'll relay my observations to the team.

I'll be marking this as a bug for now. You may refer to this thread for updates.

**Comment by chkuang-g** [comment]
@shlighter 
https://github.com/firebase/firebase-ios-sdk/issues/8685 should definitely be included in the latest release: It's been fixed in Sep 2021 and staged in `8.8.0`. The latest Unity SDK is using pod `9.1.0`. So you issue might not related to that.

I am able to reproduce the same thing by just adding Storage pod. My current Xcode version is `13.1`

According to this post, this seems requires Xcode `13.2` and above.  Could you try and see if upgrading Xcode works for you?

**Comment by chkuang-g** [comment]
@paulb777 Do you have some insight about this?

**Comment by paulb777** [comment]
Yes. It's an Xcode 13.2 issue. Firebase Apple SDK 9.x requires at least 13.3.1. See the release notes: https://firebase.google.com/support/release-notes/ios

**Comment by chkuang-g** [comment]
@paulb777 Thank you for the response.

@shlighter Unity SDK `9.0.0` is considered as a breaking change release. We also documented this in [Unity release note](https://firebase.google.com/support/release-notes/unity#version_900_-_may_19_2022).  Unfortunately if you need to use Xcode `13.0`, the best solution is to downgrade Unity SDK to `8.10.1`.

You should be able to find the older version here.
https://developers.google.com/unity/archive#firebase

Make sure you remove ALL Firebase libraries in your project before importing the older version.

Hope this answer your quesiton!
