### ISSUE TITLE
FIRESTORE INTERNAL ASSERTION FAILED crash 

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#1285]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.1
  * Firebase Unity SDK version: 8.8.0
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using:AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS(iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

'm trying to run the following code in my app. Unity's editor crashes when running it. And on the iPhone the app freezes. What am I doing wrong? Firebase SDK 8.8.0.

Error- ERROR: FIRESTORE INTERNAL ASSERTION FAILED: z:\build\work\006fabbe3c788f8159e582ced9f367dd4f3a\google3\third_party\firebase\ios\Releases\FirebaseFirestore\core\src\local\leveldb_transaction.cc(76) void _cdecl firebase::firestore::local::LevelDbTransaction::Iterator::Seek(const class std::basic_string<char,struct std::char_traits,class std::allocator > &): leveldb iterator reported an error: Corruption: corrupted compressed block contents (expected db_iter->status().ok())

#### Steps to reproduce:

My code is- 
 FirebaseFirestore db = FirebaseFirestore.DefaultInstance;
        DocumentReference docRef = db.Collection("posts").Document("656");
        Dictionary<string, object> uuu = new Dictionary<string, object>
                     {
                        { "text", "hello" }
                     };
        docRef.SetAsync(uuu);
    }

```
// TODO(you): code here to reproduce the problem
```

**Comment by shlighter** [comment]
Closing the issue-  I reinstalled the SDK (updated to 8.10)

**Comment by dconeybe** [comment]
This was a known issue with "Snappy" compression support, and was fixed recently (Googlers see b/227782613). I didn't realize we actually released the bug though. In any case, it's definitely fixed now. See https://github.com/firebase/firebase-cpp-sdk/pull/885 for details.
