### ISSUE TITLE
Xcode build crash after implementing firebase realtime database

### ISSUE THREAD

**Issue by RastyBasic** [firebase/quickstart-unity#1288]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.4f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: https://firebase.google.com/download/unity
  * Problematic Firebase Component: Realtime database
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
running in Xcode 13.2

after implementing firebase and starting compiling in xcode, this message appeared to me running from UnityFramework
```
ld: malformed universal file: slice extends beyond end of file '.../Libraries/Plugins/iOS/Firebase/libFirebaseCppApp.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
already tried some settings under iOS resolver, like changin some of the cocoapods settings

iam new in apple developing soo i dont have much experiences with it
I will be grateful for any help and sorry for my bad english

#### Steps to reproduce:

simly import firebase realtime database into project

**Comment by paulinon** [comment]
Hi @RastyBasic,

The minimum Xcode version required to use Firebase for iOS builds from Unity is Xcode 13.3.1. Could you try updating this and see if the issue persists?

**Comment by RastyBasic** [comment]
Hi thank you for your fast response now i have version 13.4.1 but issue still persist :/

**Comment by RastyBasic** [comment]
There is full error in UnityFramework

``
Ld /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework normal (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/krystofrichtermoc/Desktop/Ujo
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/lib/swift -L/Users/krystofrichtermoc/Desktop/Ujo/Libraries -L/Users/krystofrichtermoc/Desktop/Ujo/Libraries/Plugins/iOS/Firebase -L/Users/krystofrichtermoc/Desktop/Ujo/Libraries/Plugins/iOS -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FirebaseAuth -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FirebaseCore -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FirebaseCoreDiagnostics -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FirebaseCoreInternal -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FirebaseDatabase -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FirebaseInstallations -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/GTMSessionFetcher -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/GoogleDataTransport -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/GoogleUtilities -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/PromisesObjC -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/leveldb-library -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/nanopb -F/Users/krystofrichtermoc/Desktop/Ujo/Pods/FirebaseAnalytics/Frameworks -F/Users/krystofrichtermoc/Desktop/Ujo/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current -F/Users/krystofrichtermoc/Desktop/Ujo/Pods/GoogleAppMeasurement/Frameworks -F/Users/krystofrichtermoc/Desktop/Ujo/Pods/GoogleUserMessagingPlatform/Frameworks/Release -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/Google-Mobile-Ads-SDK -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/AdIdSupport -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport -F/Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleUserMessagingPlatform -filelist /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework.swiftmodule -ObjC -lc++ -licucore -lsqlite3 -lz -framework AVFoundation -framework AudioToolbox -framework CFNetwork -framework CoreGraphics -framework CoreMedia -framework CoreTelephony -framework CoreVideo -framework FBLPromises -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseCoreInternal -framework FirebaseDatabase -framework FirebaseInstallations -framework Foundation -framework GTMSessionFetcher -framework GoogleAppMeasurement -framework GoogleAppMeasurementIdentitySupport -framework GoogleDataTransport -framework GoogleMobileAds -framework GoogleUtilities -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework UserMessagingPlatform -framework WebKit -framework leveldb -framework nanopb -weak_framework AdSupport -weak_framework JavaScriptCore -weak_framework SafariServices -weak_framework WebKit -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Metal -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp /Users/krystofrichtermoc/Desktop/Ujo/Libraries/baselib.a -lFirebaseCppDatabase -lFirebaseCppApp -lFirebaseCppAuth /Users/krystofrichtermoc/Desktop/Ujo/Libraries/Plugins/iOS/unity-plugin-library.a -weak_framework GameController -framework Pods_UnityFramework -Xlinker -dependency_info -Xlinker /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/UnityFramework.build/Objects-normal/arm64/UnityFramework_dependency_info.dat -o /Users/krystofrichtermoc/Library/Developer/Xcode/DerivedData/Unity-iPhone-fhxiorucbspjaogbkltwefwmobzh/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UnityFramework.framework/UnityFramework
``

**Comment by paulinon** [comment]
Hi @RastyBasic,

I haven't replicated the issue yet. Was importing the Firebase SDK the only step you took before facing the error message? Have you added your `GoogleService-Info.plist` file in your implementation? It would be helpful if you share the complete steps you've taken before facing the issue.

**Comment by RastyBasic** [comment]
No @paulinon  but i have `google-services.json`. Is `GoogleSevice-Info.plist` needed ?

**Comment by paulinon** [comment]
Hi @RastyBasic,

Given that you're building for iOS, the [`GoogleSevice-Info.plist` file](https://firebase.google.com/docs/unity/setup#add-config-file) is the needed config file for you to utilize your Firebase project. You could have both files if you intend to build for both iOS and Android platforms. Additionally, could you verify if this issue occurs with just the Firebase SDK in your Unity implementation?

**Comment by RastyBasic** [comment]
Yesss, thanks @paulinon issue was solved

i created new project and import firebase database from dotnet45 (there was build fine), in next step i deleted everything what was in new project(firebase imported assets) from my project also i deleted admob after this step i imported first firebase package and than admob. So conclusion is "order of importing packages matter". Again am sorry for my english

**Comment by paulinon** [comment]
Glad to hear that you've resolved the issue, @RastyBasic. I'll be closing this ticket for now. Let me know if an issue arises.
