### ISSUE TITLE
Win Editor: Could not find a working python interpreter

### ISSUE THREAD

**Issue by Incont** [firebase/quickstart-unity#1289]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)
Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:
  * Unity editor version: Unity2019.4.17f1
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Crashlytics
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS and Android
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the issue here:
I have error on every compiling:
"Could not find a working python interpreter. Please make sure one of the following is in your PATH: python3 python3.8 python3.7 python2.7 python2 python"

#### Steps to reproduce:
Update any cs script.

I saw sources. Firebase App don't use python interpritater on windows platform. Firebase App use binaries: generate_xml_from_google_services_json.exe
network_request.exe
Please remove this error message for windows platform.

**Comment by AlmostMatt** [comment]
It looks like you are correct - an exe should be used instead of python on windows, but it seems that the current logic is such that it is performing the check to find python even though it is not required.

As a temporary workaround until this is fixed, you can either install python locally, or try an older version of the SDK (8.8.1 or older, I think)

**Comment by Incont** [comment]
This error message don't affect building. But we have many team members who panic when see any errors.
