### ISSUE TITLE
Cannot upload debug symbols for Android to crashlytics

### ISSUE THREAD

**Issue by nioan** [firebase/quickstart-unity#1298]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.37f1
  * Firebase Unity SDK version: 9.4.0
  * Source you installed the SDK: unitypackage(.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: firebase cli (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: none(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: linux ci, windows dev(Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

Cannot upload symbols with firebase cli. The original symbols file is 2.7GB. Following some advice on unity forums, I removed dbg.so files and re-zipped the symbols. The result is a symbols file slightly over 300MB.

This all is happening in a ruby image in docker. I don't see any java binary installed, but this probably is bundled with the firebase cli.

I tried to upload with the following command:
firebase crashlytics:symbols:upload --app=<app_id> --token='<firebase_token>' ./<build-name>symbols.zip

I get the following error:

i  Generating symbols for ./Fantastic_Battles-1.0-v3873.symbols.zip
⚠  An unknown error occurred

Error: java command failed with args: -jar,/root/.cache/firebase/crashlytics/buildtools/crashlytics-buildtools-2.9.1.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,/tmp/crashlytics-8bfa47d0-5ad7-4a44-940d-801203314456/nativeSymbols/1-768264781817-android-d20c4070873c6fabe38728/breakpad,-verbose,-generateNativeSymbols,-unstrippedLibrary,./<build-name>.symbols.zip,-clientName,firebase-cli;crashlytics-buildtools

The error occurs with both the original 2.7GB symbols file as well as the 300MB version I created (maximum zip, no dbg.so files).

#### Steps to reproduce:
Not sure how you can reproduce on your side.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

What happened? How can we make the problem occur?

Not sure how you can reproduce on your side. Happy to send the symbols file in a private message.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by paulinon** [comment]
Hi @nioan,

This issue appears to be more related to the Firebase CLI rather than the SDK, but the cause of this behavior could be related to the command you're using. Take note that the command for uploading symbols is

`firebase crashlytics:symbols:upload --app=<FIREBASE_APP_ID> <PATH/TO/SYMBOLS>`

You may refer to our [documentation](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=unity) for more information. If the issue persists after making changes to your command, you may raise this to the [Firebase CLI GitHub repository](https://github.com/firebase/firebase-tools/issues). Feel free to include any relevant information such as CLI version and latest error logs.
