### ISSUE TITLE
Can't get crash log from emulator

### ISSUE THREAD

**Issue by AOEGame** [firebase/quickstart-unity#1299]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.27f
  * Firebase Unity SDK version: 9.1.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics, CloundMessing
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I can't get crash log from emulator. 
MUMU Emulator
Android version:
6.0.1

#### Steps to reproduce:
use code:
UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.AccessViolation);
or
UnityEngine.Diagnostics.Utils.ForceCrash(UnityEngine.Diagnostics.ForcedCrashCategory.Abort);

Force Crash.

I can't get crash log from emulator. (MUMU Emulator).

I can get crash log from android phone.

**Comment by paulinon** [comment]
Hi @AOEGame,

Thanks for reporting this issue. While I try to replicate this on my end, I'd like you to perform a few tests:
- Could you verify if the issue persists using SDK version 9.4.0?
- Are you able to receive crash logs from other MuMu emulators with a higher Android version? If not, please specify the Android versions used.
- Is the behavior reproducible using other emulators (like ones from [Android Studio](https://developer.android.com/studio/run/managing-avds))?

I look forward to your results.
