### ISSUE TITLE
iOS Sample apps failing during linking process

### ISSUE THREAD

**Issue by ToddKerpelman** [firebase/quickstart-unity#13]
I'm sure this is a case of "Todd forgetting some simple step" here, but I'm having issues running the sample apps on an actual iOS device -- the apps fail on the linker step.

I'll use the `remote-config` one as an example. I've imported the RemoteConfig.unitypackage and added the appropriate info.plist file to the sample app. I've selected iOS as the platform; built and run. 

The generated Xcode project opens okay, but during the linking process fails with:

> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_FIROptions", referenced from:
>       objc-class-ref in libApp.a(app_ios_c76c7d869e568a9b561ea55e25a7dcc0.o)
>   "_OBJC_CLASS_$_FIRRemoteConfigSettings", referenced from:
>       objc-class-ref in libRemoteConfig.a(remote_config_ios_53531e292e202c8e07f4ebe5b73bbec1.o)
>   "_OBJC_CLASS_$_FIRRemoteConfig", referenced from:
>       objc-class-ref in libRemoteConfig.a(remote_config_ios_53531e292e202c8e07f4ebe5b73bbec1.o)
>   "_OBJC_CLASS_$_FIRApp", referenced from:
>       objc-class-ref in libApp.a(app_ios_c76c7d869e568a9b561ea55e25a7dcc0.o)
>   "_FIRRemoteConfigThrottledEndTimeInSecondsKey", referenced from:
>       ____ZN8firebase13remote_config5FetchEy_block_invoke in libRemoteConfig.a(remote_config_ios_53531e292e202c8e07f4ebe5b73bbec1.o)
> 

I can see both `libApp.a` and `libRemoteConfig.a` in my Build Phases > Link Binary with Libraries step. And it appears as though the pod install has run, although I don't see a generated workspace -- I'm assuming that's intentional due to integrate_targets being false.

So I'm guessing this is probably a case of something simple not being added or some flag not being set. Any ideas?

**Comment by ToddKerpelman** [comment]
Further information I probably should have noticed earlier: On exporting, I do get an error about Unity being unable to parse my PBX project. This is with Unity 5.4.2 and Xcode 8.1. I'll update my Unity to 5.4.3 and see if that fixes the issue... 

```
Exception: Invalid PBX project (parsing line 0)
UnityEditor.iOS.Xcode.PBX.Parser.ParseTree () (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBX/Parser.cs:114)
UnityEditor.iOS.Xcode.PBXProjectData.ParseContent (System.String content) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:451)
UnityEditor.iOS.Xcode.PBXProjectData.ReadFromStream (System.IO.TextReader sr) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:458)
UnityEditor.iOS.Xcode.PBXProject.ReadFromStream (System.IO.TextReader sr) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:868)
UnityEditor.iOS.Xcode.PBXProject.ReadFromString (System.String src) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:863)
Google.IOSResolver.OnPostProcessUpdateProjectDeps (BuildTarget buildTarget, System.String pathToBuiltProject)
UnityEditor.HostView:OnGUI()
```

**Comment by ToddKerpelman** [comment]
Just confirming that I still get this ParseTree() error even when I update to Unity 5.4.3f1. Hmmm....

**Comment by stewartmiles** [comment]
Looking at the example project ToddKerpelman shared with me, it's possible that this is due to an out of date Cocoapods install which is causing https://github.com/CocoaPods/CocoaPods/issues/1275 .  Essentially when "pod install" is executed it generates an XML Xcode project which can't be read by the xcodeapi in Unity.   We have better reporting lined up for the next release.

**Comment by stewartmiles** [comment]
Todd confirmed that updating to Cocoapods 1.1.x resolved the issue.  He was using 1.0.0 before which resulted in the generate Pods.xcproject to be written out in XML format which can't be read by Unity.

**Comment by ToddKerpelman** [comment]
Yep. For anybody else who encounters this problem, please update your version of Cocoapods.
