### ISSUE TITLE
Firebase plugin error: Could not find TLS Provider: `Mono.AppleTls.AppleTlsProvider'.

### ISSUE THREAD

**Issue by omrip30** [firebase/quickstart-unity#130]
Hi :) 
After building a unity firebase project to iOS and trying to get a record (async) I get the following exception: "System.NotSupportedException: TLS Support not available. ---> System.NotSupportedException: Could not find TLS Provider: `Mono.AppleTls.AppleTlsProvider'. at Mono.Net.Security.MonoTlsProviderFactory.LookupProviderType (System.String name, System.Boolean throwOnError) [0x00000] in :0 "

I also tried this with a test project - one that includes the plugin and a simple script that connects to the database and retrieves a record. The exception occurs when trying to retrieve the record Also, I added the plist file, installed cocoa pods and have the latest plugin.

I'm using: Unity version: 2017.2.0f3 
xcode version : 9.1 
Firebase sdk: 4.4.0 
.net 4.6

The project works correctly in Android by the way. This is very urgent to us, we have an upcoming release...

Thanks :) 
Omri Perl

**Comment by omrip30** [comment]
Forgot to mention I'm, using ios 10.1.1.
Also, is this related?
https://forum.unity.com/threads/unity-2017-1-tls-1-2-still-not-working-with-net-4-6.487415/

**Comment by stewartmiles** [comment]
Hey @a-maurice any chance you could take a look into this?

**Comment by a-maurice** [comment]
Hi Omri,

I was able to reproduce your problem locally using 2017.2, so thanks for providing that information.  It seems as though Unity has fixed the issue on their end with 2017.3 (a similar issue tracker is seen here: https://issuetracker.unity3d.com/issues/mobile-il2cpp-dot-net-4-dot-6-argumentnullexception-when-running-azure-storage-sdk), so if possible, it seems like the best solution would be upgrading your project to use 2017.3, as it is something on their end causing the problem.

If that isn't possible, let us know, and I can see if there is some way to workaround the issue, though some initial research isn't finding anything great.

-Anthony

**Comment by omrip30** [comment]
Hi Anthony,
First of all thanks for the quick and helpful answer!
I need to check and see if it's possible for us to upgrade to 2017.3.
Will update you :)

**Comment by a-maurice** [comment]
Great, good to hear.
