### ISSUE TITLE
Google Cloud Architecture Framework: System design

### ISSUE THREAD

**Issue by Helix-DB3** [firebase/quickstart-unity#1301]
https://cloud.google.com/architecture

**Comment by Helix-DB3** [comment]
•https://github.com/Helix-DB3/  matrix.org/releases/new/security.txt
•App: 144.6 (null) betaRelease; Manifest: N/A; Build Override: N/A; Device: a12u (SM-A125U1) OS 30;
•https://github.com/login?return_to=https%3A%2F%2Fgist.github.com%2Fpaulmillr%2Fcb3ad3b9cd4ac849eb1def3634f93421
•hey come check out Discord with me https://discord.gg/j6hw9SmFbD
•https://discord.com/invite/pewdiepie
°https://photos.app.goo.gl/Uhv2mtv6p2L5Ceb27
°https://crowdin.com/profile/helix-db3
°https://softgateon.herokuapp.com/directlink/#
°https://www.uhive.com/m/101041264626622
°0x9813D58D7CFA8E9Ee47f4d13A29cCcc59E14BBeF
°100.67.249.48
°I'm using Gboard to type in Alphabet (QWERTY). You can try it at: https://gboard.app.goo.gl/2k1h6

**Comment by rizafran** [comment]
Closing this ticket since the issue stated seems unrelated to Firebase SDK.
