### ISSUE TITLE
[Bug] fetching failure: http code 400 in Unity Editor

### ISSUE THREAD

**Issue by KhaCong85** [firebase/quickstart-unity#1306]
Handle:
- Check file google-services.json in your project 
- Check its name "google-services.json". 
- Example: (1: "google-service.json" -> fall; 2: "google-servi.json" -> fall; 3: "google-services.json" -> true)

**Comment by paulinon** [comment]
Hi @KhaCong85,

The `google-services.json` file contains information about your Firebase configuration. It's important that the file be named properly in order to avoid fetching issues. 

That being said, I'll be closing this for now.
