### ISSUE TITLE
DllNotFoundException on MacOS

### ISSUE THREAD

**Issue by letuantam96** [firebase/quickstart-unity#1308]
Unity editor version: 2020.3.25f1
Firebase Unity SDK version: 9.5.0
Source you installed the SDK: 
Problematic Firebase Component: 
Platform you are using the Unity editor on: MacOS Big Sur version 11.6
Platform you are targeting: iOS
Scripting Runtime: IL2CPP

Hi, my project works well on Window when built for Android. But when I clone it to Mac and open in Editor, it show the bellow error whenever I hit Run:

`DllNotFoundException: FirebaseCppApp-9_5_0
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at <e689ebc7a3ba409eb3646ba40edd9f94>:0)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at <e689ebc7a3ba409eb3646ba40edd9f94>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at <e689ebc7a3ba409eb3646ba40edd9f94>:0)
Firebase.LogUtil..ctor () (at <e689ebc7a3ba409eb3646ba40edd9f94>:0)
Firebase.LogUtil..cctor () (at <e689ebc7a3ba409eb3646ba40edd9f94>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at <e689ebc7a3ba409eb3646ba40edd9f94>:0)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
FirebaseManager.Setup () (at Assets/Scripts/FirebaseManager.cs:15)
TrackingManager.Setup () (at Assets/Scripts/TrackingManager.cs:14)
GameManager+<Start>d__18.MoveNext () (at Assets/Scripts/Core/GameManager.cs:31)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Assets/Third Party Packages/UniTask/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.ExceptionResultSource:Finalize() (at Assets/Third Party Packages/UniTask/Runtime/UniTask.Factory.cs:233)`

The code that fire that error:
`        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
        });`

Please help fix this. Thank you!!

**Comment by paulinon** [comment]
Hi @letuantam96,

Thanks for reporting this. Are you facing an alert saying that Firebase cannot be verified when playing the scene? If so, I'd like you to try going to your Mac’s System Preferences > Security & Privacy then Click Allow Anyway corresponding to Firebase.

Let me know if this solution made a difference.

**Comment by letuantam96** [comment]
> 

Hi paulinon,
Thank for response. Unfortunately, I dont facing the arlet you mention. I tried:
- Re-clone project form git.
- Delete and re-build Library folder.
- Upgrade macOS to 12.6.1 Moterey.
But no luck happen.

**Comment by letuantam96** [comment]
Update: I fixed it. This is what I did:
- Download same version Firebase package from Firebase homepage.
- Re-import it to project.
- The arlet @paulinon mention above is now appearing.
- Then I follow https://github.com/firebase/quickstart-unity/issues/1222 to fix it.

**Comment by paulinon** [comment]
Good to hear that you've resolved the issue, @letuantam96. That being said, I'll be closing this for now. Let me know if any issue arises.
