### ISSUE TITLE
[FR] `Please` Provide Package via UPM

### ISSUE THREAD

**Issue by CodeMasterYi** [firebase/quickstart-unity#1309]
as The Title.
`Please` provide(put back) `Game Package Registry by Google` for unity packages.
https://github.com/firebase/quickstart-unity/issues/1052
https://github.com/firebase/quickstart-unity/issues/1030
https://github.com/firebase/quickstart-unity/issues/1028
https://github.com/firebase/quickstart-unity/issues/990

**Comment by paulinon** [comment]
Hi @CodeMasterYi,

Our team is still working on this feature, and we don't have a definite timeline for this. For now, let me bring this to their attention.

I'll be closing this for now. You may refer to the [original feature request](https://github.com/firebase/quickstart-unity/issues/1052) for any updates.
