### ISSUE TITLE
DllNotFoundException in Firebase when trying to run an Android project exported from Unity

### ISSUE THREAD

**Issue by dushyantkumawat** [firebase/quickstart-unity#131]
I'm exporting an Android project from Unity (target API 25) and integrating it into another Android project. This native app invokes the project exported from Unity.

The Unity app uses Firebase database. As soon as the Initialization code runs, I get a DllNotFoundException. I just get the following log on loop:

01-10 22:26:16.256 12625 13402 E Unity : DllNotFoundException: App 
01-10 22:26:16.256 12625 13402 E Unity : at (wrapper managed-to-native) Firebase.AppUtilPINVOKE/SWIGExceptionHelper:SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)

    01-10 22:26:16.256 12625 13402 E Unity : at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x00000] in :0 01-10 22:26:16.256 12625 13402 E Unity : Rethrow as TypeInitializationException: An exception was thrown by the type initializer for SWIGExcepti

Already looked at [#53](https://github.com/firebase/quickstart-unity/issues/53)

Using Unity 2017.2.0f3 and firebase_unity_sdk_4.2.1

**Comment by stewartmiles** [comment]
You're missing the Android specific dependencies (AARs and JARs).
Perhaps you got into a state when Android Resolution was aborted mid way through so you have a subset of dependencies in your project.  Try following:
https://groups.google.com/d/msg/firebase-talk/2mVSyxwpdvc/HsLHFHLVBAAJ

**Comment by dushyantkumawat** [comment]
Hi Stewart,
Are you sure it's that? Because when the apk is exported directly from unity, everything works perfectly.

**Comment by stewartmiles** [comment]
@dushyantkumawat you didn't mention that when you build normally everything works correctly :)

You need to make sure libApp.so is present in the app you're merging your Unity project into.  If the final built APK doesn't include this DLL for the architecture you're targeting, things are not going to work.

**Comment by dushyantkumawat** [comment]
@stewartmiles Sorry about that.
Is this file generated from Unity?

**Comment by stewartmiles** [comment]
It's part of the firebase-app-unity-*.aar library if I remember correctly.  We redistribute it as firebase-app-unity-VERSION.srcaar in the Assets/Firebase/m2repository directory in each plugin which the Android Resolver unpacks into Assets/Plugins/Android/ depending upon your build options, Unity version etc.

**Comment by dushyantkumawat** [comment]
This is weird. I can find this file in the apk, but not in the exported project. Any suggestion for this?

**Comment by stewartmiles** [comment]
How are you exporting the project from Unity?  Is this a gradle project that you're exporting or something else?

**Comment by dushyantkumawat** [comment]
It is a gradle project, with "Export Project" checked in the build popup.

**Comment by dushyantkumawat** [comment]
We are importing this project as aar in Android Studio. This project also uses Firebase database. Are there any chances of any kind of clash between the libraries?

**Comment by stewartmiles** [comment]
You can include multiple Firebase plugins in a project and the export *should* just work.  To determine whether AAR exploding (required for the internal Android build system) is causing a problem you could try disabling AAR explosion in the Android Resolver settings https://github.com/googlesamples/unity-jar-resolver#android-manifest-variable-processing this will just add all AARs to the exported project instead but will break building with Unity's internal build system.

**Comment by dushyantkumawat** [comment]
I just tried that and all AAR files were added to the "libs" folder. Even with the explode option enabled, the result was same.

**Comment by stewartmiles** [comment]
Right, so if they're in the libs folder it's possible your exported build.gradle file is missing references to them.  You need to validate that each AAR present is being included in the gradle project.  Any chance you could upload your exported Android Studio project somewhere for inspection?

**Comment by dushyantkumawat** [comment]
Hello Stewart. Could you share your email so I can share the project?

**Comment by stewartmiles** [comment]
If it's a project you can't share publicly it's best for you to open an issue with https://firebase.google.com/support/contact/troubleshooting/ if you mention this is a Unity issue our first line responders will be able to either diagnose the issues themselves or escalate to the engineering team including myself :)

**Comment by stewartmiles** [comment]
@dushyantkumawat we haven't heard from you in a while so I'll assume this issue is resolved.

**Comment by dushyantkumawat** [comment]
We never got this to work. The idea was scrapped and built directly into
native. Sorry.

**Comment by kisanzxy** [comment]
@stewartmiles @dushyantkumawat  @LasseBman   Hi, I have the same issue there, Could anyone tell me how to solve this?

**Comment by dushyantkumawat** [comment]
Sorry Luisa, unfortunately we never got this to work

**Comment by kisanzxy** [comment]
@dushyantkumawat 
We just found another way to circumvent this issue. Instead of using the Unity Project as ARR. We add new activity classes in the Unity Android Project, that is we didn't start another android project but only create new activities and layouts. In this way, the whole project works just fine because you won't need to worry about the dependency issues.

**Comment by dushyantkumawat** [comment]
That's an interesting approach, thanks for the workaround!

**Comment by vilsonfp** [comment]
Hello, I know that this post is already closed, but I would like to pass on my experience, I had the same problem, and I was able to solve it as follows.
After you export the Unity3d project to Android Studio, convert it to module
"@stewartmiles
Removing the project's applicationId in build.gradle
Changing com.android.application to com.android.library in build.gradle "

1 - Copy the .aar files from the .libs folder of the module project, if the master project does not already have them
2 - include the .aar files in build.gradle
dependencies {
implementation fileTree (include: ['* .jar', '* .ar'], dir: 'libs')
implementation project (': ModuleApp')
-------
} `

3 - Copy the file "google-services.xml" to the res / values / google-services.xml folder of the master project
4 - Ready, Firebase will work with the sources of the module exported from Unity

Sorry for my bad english

**Comment by Soorya-S** [comment]
> Hello, I know that this post is already closed, but I would like to pass on my experience, I had the same problem, and I was able to solve it as follows.
> After you export the Unity3d project to Android Studio, convert it to module
> 
> "@stewartmiles
> Removing the project's applicationId in build.gradle
> Changing com.android.application to com.android.library in build.gradle "
> 
> 1 - Copy the .aar files from the .libs folder of the module project, if the master project does not already have them
> 2 - include the .aar files in build.gradle
> dependencies {
> implementation fileTree (include: ['* .jar', '* .aar'], dir: 'libs')
> implementation project (': ModuleApp')
> -------
> }
> 
> 3 - Copy the file "google-services.xml" to the res / values / google-services.xml folder of the master project
> 4 - Ready, Firebase will work with the sources of the module exported from Unity
> 
> Sorry for my bad english

Where to find the file  "google-services.xml"?

**Comment by vilsonfp** [comment]
@Soorya-S 
Hi, you can get the same "google-services.xml" file that was downloaded from the firebase console!

**Comment by Soorya-S** [comment]
> @Soorya-S
> Hi, you can get the same "google-services.xml" file that was downloaded from the firebase console!

are you saying about "google-services.json" ?

**Comment by vilsonfp** [comment]
@Soorya-S I think I mentioned information on my part, "google-services.xml" is generated inside the "Firebase" directory when exporting the Unity project for Android Project
After you export the project to Android Studio, a directory (module) Firebase
![Sem título](https://user-images.githubusercontent.com/11746702/57232064-385e8c80-6ff2-11e9-8c9d-e2caf2fc8f5d.png)

\Firebase\res\values
![Sem título](https://user-images.githubusercontent.com/11746702/57231888-de5dc700-6ff1-11e9-8bc8-e2614af0c75b.png)
