### ISSUE TITLE
Firebase Auth: On Google logout, sign in back to Anonymous account? 

### ISSUE THREAD

**Issue by JaineshPathak** [firebase/quickstart-unity#1317]
**[REQUIRED] Please fill in the following fields:**
Unity editor version: 2021.3.16f1
Firebase Unity SDK version: 8.2.0
Source you installed the SDK: .unitypackage
Problematic Firebase Component: Auth
Other Firebase Components in use: Database, Remote Config, Firestore
Additional SDKs you are using: Facebook, Ironsrc
Platform you are using the Unity editor on: Windows
Platform you are targeting: Android
Scripting Runtime: IL2CPP

**[REQUIRED] Please describe the question here:**

Hello.

I am using anonymous account sign in when a new user installs the app and in-game currencies are stored in that account using firestore. I have given user option to login with their Google account. This works fine.

My questions are:
1. What happens to that anonymous account when the user decides to login/logout with his Google account? 
2. Also after Google logout, is it possible to sign in back to that anonymous account so that I can retrieve the in-game currencies stored in the anonymous account? If yes how?

Thank you.

**Comment by AlmostMatt** [comment]
You might find this page helpful:
https://firebase.google.com/docs/auth/unity/account-linking

The recommended flow is that:
- the user is signed in with an anonymous account
- you ask the user to authenticate with a google account (or other authentication method) to get a credential
- while still signed into the anonymous account, call auth.CurrentUser.LinkWithCredentialAsync(credential)

The expectation is that one firebase user can have multiple associated authentication methods. It should still be the same firebase account.

**Comment by JaineshPathak** [comment]
Thank you for replying.
If I understood correctly, LinkWithCredentialAsync() will link google account and anonymous account together, so that means Current User ID won't change and will remain the same when given by anonymous account. Correct?

What if user uninstalls the app and later decides to reinstall. He will be signed in with a new fresh anonymous account and if he tries to link his same Google account, it will be linked with the recent newly anonymous account and not old ones right? 

So he won't be able to get old in-game currencies back previously stored in google account and will be overwritten by in-game currency values stored in new anonymous account.

**Comment by AlmostMatt** [comment]
> If I understood correctly, LinkWithCredentialAsync() will link google account and anonymous account together, so that means Current User ID won't change and will remain the same when given by anonymous account. Correct?

Yes, this is correct.

> What if user uninstalls the app and later decides to reinstall. He will be signed in with a new fresh anonymous account and if he tries to link his same Google account, it will be linked with the recent newly anonymous account and not old ones right?
> 
> So he won't be able to get old in-game currencies back previously stored in google account and will be overwritten by in-game currency values stored in new anonymous account.

If the user previously linked a google account to their account, then in the future they should choose to sign in using the google account instead of trying to link it again.

I'm not sure exactly what would happen if the user tried to link the same google account to multiple different accounts, but I suspect that the second attempt to link would fail.
