### ISSUE TITLE
Can't unsubscribe from events?

### ISSUE THREAD

**Issue by yogev2255** [firebase/quickstart-unity#1319]
[REQUIRED] Please fill in the following fields:
Unity editor version: 2021.3.15f1
Firebase Unity SDK version: 10.3.0
Source you installed the SDK: ___.unitypackage __ (.unitypackage or Unity Package Manager)
Problematic Firebase Component: database___ (Auth, Database, etc.)
Other Firebase Components in use: non_ (Auth, Database, etc.)
Additional SDKs you are using: GooglePlay_ (Facebook, AdMob, etc.)
Platform you are using the Unity editor on: _windows (Mac, Windows, or Linux)
Platform you are targeting: _android (iOS, Android, and/or desktop)
Scripting Runtime: IL2CPP_ (Mono, and/or IL2CPP)
[REQUIRED] Please describe the issue here:

Hello, 

I use firebase real-time database and I am subscribing to events on start and a few other places and is working fine 

but when I am trying to unsubscribe from them 
in OnDisable the user still receives updates from firebase why? 
I get this on 2 different scripts

I tested with
`[ContextMenu("disable")]
    void RemoveEvents()
    {
        db.Child("Users").Child(GameManager.instance.pinCode.ToString()).ChildAdded -= AddPlayerToList;
        db.Child("Users").Child(GameManager.instance.pinCode.ToString()).ChildRemoved -= RemovePlayerList;
        db.Child("Servers").Child(GameManager.instance.pinCode.ToString()).ChildChanged -= OnServerChagne;
        Application.quitting -= UserQuitTheGame;
        StopAllCoroutines();
        Debug.Log("disable lobby");
    }
`
but I still receive events

**Comment by jonsimantov** [comment]
Hi,

I've managed to [reproduce this issue](https://github.com/firebase/firebase-unity-sdk/pull/618) when unsubscribing events from a new DatabaseReference created with the same path as the old DatabaseReference.

As a workaround, if you hold onto the actual DatabaseReference instances that you registered the events on, you should be able to unsubscribe from them.
