### ISSUE TITLE
DLLNOTFOUNDEXCEPTION

### ISSUE THREAD

**Issue by Sonhokko** [firebase/quickstart-unity#1321]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.3f1
  * Firebase Unity SDK version: 10.2.0
  * Source you installed the SDK: auth (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _admob, facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: windows (Mac, Windows, or Linux)
  * Platform you are targeting: IOS/Android(iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

When i try to run my app in playmode Unity i have error

DllNotFoundException: FirebaseCppApp-10_2_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at /Users/runner/work/firebase-unity-sdk/firebase-unity-sdk/macos_unity/x86_64/app/swig/Firebase.App_fixed.cs:4072)

Why i have MACOS error if i used Windows?) And my device Lenovo.
I try reimport all firebase in my project, try force resolve, try open project in other version, try delete Library. Without result

i try find path which me send error, i no have this path in my PC

#### Steps to reproduce:
Open unity, click on play mode
#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by cynthiajoan** [comment]
close this one since the same issue tracked in https://github.com/firebase/firebase-unity-sdk/issues/625
