### ISSUE TITLE
unity editor crash when read data on firestore

### ISSUE THREAD

**Issue by amir1387aht** [firebase/quickstart-unity#1325]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.21f1
  * Firebase Unity SDK version: 10.6.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: firestore
  * Other Firebase Components in use: Auth, Messaging, Storage, Analysic
  * Additional SDKs you are using: nothing
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

hello,
i want use firestore for my app chat
i impelented firebase sdk, Resolved android dep, and...
now when i want to read\write data from firestore, unity editor gets crash(15 crash today!)
other package work find(but auth get me error that i fix later)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
samples code on firebase docs have get me crash too,
100%

What happened? How can we make the problem occur?
consol not show anything, it just crash and clode unity

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
 ```
    public virtual void Start()
    {
        app = FirebaseApp.Create(new AppOptions
        {
            DatabaseUrl = new Uri("i hide it"),
            ProjectId = "i hide it",
            ApiKey = "i hide it",
            AppId = "i hide it"
        });

        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
        {
            dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available)
            {
                InitializeFirebase();
            }
            else
            {
                Debug.LogError(
                  "Could not resolve all Firebase dependencies: " + dependencyStatus);
            }
        });
    }

    protected void InitializeFirebase()
    {
        auth = FirebaseAuth.GetAuth(app);
        db = FirebaseFirestore.GetInstance(app);

        StartCoroutine("get-chats");
    }

   public IEnumerator get-chats()
    {
        var doc = db.Document("1.2");
        var getTask = doc.GetSnapshotAsync(Source.Cache);
        yield return AwaitCompletion(getTask);
        getTask.ContinueWithOnMainThread(task =>
        {
            Dictionary<string, object> d = task.Result.ToDictionary();
            print(d["user-chat"]);
        });
    }

    public static IEnumerator AwaitCompletion(Task t)
    {
        yield return new WaitUntil((() => t.IsCompleted));
    }

```

**Comment by milaGGL** [comment]
Hi @amir1387aht, I have a suspicion that this is related to the known issue with the unity SDK when creating multiple instances of the app. This might be a related issue. https://github.com/firebase/quickstart-unity/issues/1284

Could you please try the code below, and see if it resolves the issue?
```
#if UNITY_EDITOR
db = FirebaseFirestore.DefaultInstance;
db.Settings.PersistenceEnabled = false;
#endif
```

**Comment by amir1387aht** [comment]
hi @milaGGL ,
thanks for your help,
but can you write full code? i dont know fir android what i need to do(beacuse this code is for Unity Editor, right?)

**Comment by milaGGL** [comment]
My pleasure to help. I am closing this ticket, but please feel free to re-open it or create a new one if you have further questions.
