### ISSUE TITLE
gRPC-C++ error build

### ISSUE THREAD

**Issue by tamngonesv030** [firebase/quickstart-unity#1327]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.29f1
  * Firebase Unity SDK version: lasted
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: firestore (Auth, Database, etc.)
  * Other Firebase Components in use: auth,analytics (Auth, Database, etc.)
  * Additional SDKs you are using: admod (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: ios (iOS, Android, and/or desktop)
  * Scripting Runtime: c# visual (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
<img width="860" alt="Screen Shot 2023-04-10 at 11 07 27 AM" src="https://user-images.githubusercontent.com/46778245/230823870-6d471f87-3374-4cf0-9415-219d6f3849ac.png">
<img width="133" alt="Screen Shot 2023-04-10 at 11 07 57 AM" src="https://user-images.githubusercontent.com/46778245/230823933-0255bbb1-3e23-4538-89d6-fc6eb1875558.png">

I'm use Xcode 14.1 and macos 12.6.4. 
I can't delete gRPC because firestore using it. 
I can use other version??

**Comment by a-maurice** [comment]
Hi @tamngonesv030 

Unfortunately, I'm not sure what the problem might be, I'm guessing something is wrong with the pods configuration.  In the folder with your iOS build, what does the Podfile and Podfile.lock look like?  If you do a build without Firestore, does it work properly?

**Comment by tamngonesv030** [comment]
> 

I was change all build setting with bitcode = false in project and sign in for gRPC-C++. 
-> problem was fixed. 
thanks.
