### ISSUE TITLE
FirebaseMessaging.MessageReceived triggers multiple times on receiving single push notification

### ISSUE THREAD

**Issue by Grimshady** [firebase/quickstart-unity#1339]
**[REQUIRED] Please fill in the following fields:**

- Unity editor version: 2020.3.43f1
- Firebase Unity SDK version: 11.0.0
- Source you installed the SDK: Unity Package Manager
- Problematic Firebase Component: Cloud Messaging
- Other Firebase Components in use: App (Core)
- Additional SDKs you are using: None
- Platform you are using the Unity editor on: iOS
- Platform you are targeting: iOS
- Scripting Runtime: IL2CPP

**[REQUIRED] Please describe the issue here:**

When triggering a push notification through POSTMAN having the following payload with the app in foreground, the `FirebaseMessaging.MessageReceived` event apparently fires 4 times.

The same is observed when app is in background and notification is tapped to resume the app.

```
{
    "data": {
        "typ": 13,
        "s_typ": 1,
        "cid": 1000,
        "pid": "payload_id"
    },
    "notification":
    {
      "title":"NotifTitleTest1",
      "body":"NotifBodyTest1"
    },
    "content_available": true,
    "mutable_content": true,
    "to": "czCPSW2Ar0Lwrf2D9CCz1w:APA91bFQg1Fgadw71fWx9WJo6WzfqFZ-81s8_Ff5_-dQwE7w9Fu2E96cciW49BMTU3vu4hJqFZDm5SuU_ettSKURRC0rdg7TTaHaIUO-vE_WKj_rfrI03ODklUz61TTiBmdrurBD-TTK"
}
```
I have double checked for multiple Monobehavior instances and subscriptions and all seems fine on this regard. I am even unsubscribing wherever I am subscribing to the events. 

Attached screenshot where I am logging MessageID. Logs are printed multiple times with the same MessageID:
![Screenshot 2023-06-19 at 6 04 33 PM](https://github.com/firebase/quickstart-unity/assets/30383078/938769ce-5a75-4a87-a2e9-8d19190cc13e)

**Steps to reproduce:**

- Build for iOS
- Deploy to Xcode and build
- Use generated token to send notifications via POSTMAN while app is in foreground
- MessageReceived event triggers multiple times

**Relevant Code:**
Attached main FCM helper script:
[RemoteNotificationReceiver.cs.zip](https://github.com/firebase/quickstart-unity/files/11788490/RemoteNotificationReceiver.cs.zip)

**Comment by inigoLlamosasConneqtech** [comment]
Hello, any update on this subject? I am experiencing this issue on iOS 17 beta

**Comment by Grimshady** [comment]
For now I'm using a workaround to run my code only on the first trigger

```
 private void OnFirebaseMessageReceived (object sender, MessageReceivedEventArgs inFirebaseArgs)
        {
            string messageID = inFirebaseArgs.Message.MessageId;
            if (!m_ReceivedPushIDs.Contains (messageID))
            {
                m_ReceivedPushIDs.Add (messageID);
                // Your logic here
            }
        }
```

**Comment by inigoLlamosasConneqtech** [comment]
Hello. Thanks for the snippet. However, my problem is happening on testing Firebase push notifications on our apps on iOS 17 Beta. We are getting 6 push notifications per notification, where it works fine on current iOS 16. This is the only issue I have found with a similar problem. If you know any update please let us know.

**Comment by Grimshady** [comment]
> @Grimshady Can you confirm whether or not you are testing on a device using iOS 17, similar to inigoLlamosas above?
> 
> That would be helpful for us to determine whether this is a change of behaviour when using iOS 17 or if it is an issue with the firebase SDK regardless of iOS version. (iOS 17 is currently associated with XCode 15)

Hey no, this was observed on an iOS 15 device
