### ISSUE TITLE
Dependency Error : Dll not found exception

### ISSUE THREAD

**Issue by subhradeepc** [firebase/quickstart-unity#134]
Hello,
Im using Unity 2017.2.1f1 , with firebase 4.3.0/4.4.0/4.4.1 for analytics and push messages. 
(All these 3 versions are giving the same issue)
The build is android, not internal build but a gradle build. 

I get these errors when i run the apk -

01-29 20:06:17.437: E/Unity(9314): local_class
01-29 20:06:17.437: E/Unity(9314): UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
01-29 20:06:17.437: E/Unity(9314): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
01-29 20:06:17.437: E/Unity(9314): UnityEngine.Logger:Log(LogType, Object)
01-29 20:06:17.437: E/Unity(9314): UnityEngine.Debug:LogError(Object)
01-29 20:06:17.437: E/Unity(9314): Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String)
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:LogMessage(LogLevel, String)
01-29 20:06:17.437: E/Unity(9314): Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternal__SWIG_0()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:CreateInternal()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:<Create>m__1()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:CreateAndTrack(CreateDelegate)
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:Create()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:get_DefaultInstance()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:CheckDependenciesInternal()
01-29 20:06:17.437: E/Unity(9314): Firebase.<CheckDependencies>c__AnonStorey5:<>m__0()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:TranslateDllNotFoundException(Action)
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:CheckDependencies()
01-29 20:06:17.437: E/Unity(9314): Firebase.FirebaseApp:<CheckDependenciesAsync>m__2()
01-29 20:06:17.437: E/Unity(9314): System.Threading.Tasks.<StartNew>c__AnonStorey0`1:<>m__0()
01-29 20:06:17.437: E/Unity(9314): System.Threading.Tasks.<Post>c__AnonStorey0:<>m__0(Object)
01-29 20:06:17.437: E/Unity(9314):  
01-29 20:06:17.437: E/Unity(9314): (Filename: ./artifacts/generated/common/runt

Now just to be frank **the sdk, quickstart unity works if i create a sample project**
I resolved the aar/jars using Play Service resolver in my project. But no help. And yes, the apk does have the required ".so" files in it. 

I've tried everything for a week now.
Any help what is causing this ?

**Comment by subhradeepc** [comment]
@stewartmiles  Any idea on this ?

**Comment by stewartmiles** [comment]
@subhradeepc we haven't heard from you in a couple of weeks so I'll assume your issue is resolved.
