### ISSUE TITLE
clang: error: -fobjc-weak is not supported on the current deployment target

### ISSUE THREAD

**Issue by nlattessi** [firebase/quickstart-unity#135]
Hello,
I´m using Unity 5.6.4f1 with latest firebase version (4.8.1) for analytics. After building this testapp for iOS and opening the XCode workspace, I have this issue when building for a device:

Showing Recent Issues
CompileC /Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/Objects-normal/arm64/nanopb-dummy.o Target\ Support\ Files/nanopb/nanopb-dummy.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path=/Users/nlattessi/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/nlattessi/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_RELEASE_FOR_RUNNING=1 -DCOCOAPODS=1 -DPOD_CONFIGURATION_RELEASE_FOR_RUNNING=1 -DPB_FIELD_32BIT=1 -DPB_NO_PACKED_STRUCTS=1 -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=4.3 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wunguarded-availability -fembed-bitcode-marker -iquote /Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/nanopb-generated-files.hmap -I/Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/nanopb-own-target-headers.hmap -I/Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/nanopb-all-target-headers.hmap -iquote /Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/nanopb-project-headers.hmap -I/Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Products/ReleaseForRunning-iphoneos/nanopb/include -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Private -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Private/nanopb -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public/Firebase -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public/FirebaseAnalytics -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public/FirebaseCore -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public/FirebaseInstanceID -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public/GoogleToolboxForMac -I/Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Headers/Public/nanopb -I/Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/DerivedSources/arm64 -I/Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/DerivedSources -F/Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Products/ReleaseForRunning-iphoneos/nanopb -include /Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Target\ Support\ Files/nanopb/nanopb-prefix.pch -MMD -MT dependencies -MF /Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/Objects-normal/arm64/nanopb-dummy.d --serialize-diagnostics /Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/Objects-normal/arm64/nanopb-dummy.dia -c /Users/nlattessi/Work/quickstart-unity/analytics/testapp/ios/Pods/Target\ Support\ Files/nanopb/nanopb-dummy.m -o /Users/nlattessi/Library/Developer/Xcode/DerivedData/Unity-iPhone-ekunofzbhhrzvvcnznmiqsxohcmn/Build/Intermediates.noindex/Pods.build/ReleaseForRunning-iphoneos/nanopb.build/Objects-normal/arm64/nanopb-dummy.o

clang: error: -fobjc-weak is not supported on the current deployment target

I´m facing this issue starting with a Unity blank project and adding Firebase Unity SDK without doing anything else. Also facing the same issue with this quickstart-unity...

Any help with this issue? Thanks!

**Comment by stewartmiles** [comment]
@nlattessi did you resolve your issue?

Perhaps this could be related to https://github.com/nanopb/nanopb/issues/307 which is used by Firebase?  Anything else you can share about how to reproduce your failure, deployment target, Xcode version etc.?

**Comment by souryu1217** [comment]
Dear nlattessi,

Which version of the Firebase Unity SDK are you using?
In version 4.4.1, there was a problem that Cocoapod dependency could not be resolved, so Version 4.4.2 which resolved the above problem was released on February 5, 2018.
Updating the Firebase Unity SDK may fix the problem.

**Comment by nlattessi** [comment]
Hi @souryu1217,

Yes, updating Firebase Unity SDK fix the problem. Using actual version 4.4.3 I don't have the issue building for iOS anymore.

Thank you for the help!
