### ISSUE TITLE
iOS push notifications for topics not working with 4.4.2

### ISSUE THREAD

**Issue by tomerpeled** [firebase/quickstart-unity#137]
Hi,

We've just upgraded our Firebase from 4.3.0 to 4.4.2.
Before the upgrade we used succeed to get notifications for both Android and iOS when subscribing to topics.
Now, after the upgrade, the Android is works as expected.
But the iOS only works with specific message via token. When trying to work with topic on the iOS, the message isn't received and no errors are shown...

Anyone else encounter with this?

This is our registration code:
```
Firebase.Messaging.FirebaseMessaging.Subscribe("/topics/all");
Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
```

**Comment by stewartmiles** [comment]
@tomerpeled are you still experiencing the issue?  As far as we can tell nothing changed in the Unity SDK, C++ SDK (used by the Unity SDK) or the iOS SDK (used by the C++ SDK).

**Comment by tomerpeled** [comment]
Unfortunately I'm still experiencing this.

On the Android everything is working as expected.
On iOS,  specific notifications works,  but topics not working.

**Comment by alexames** [comment]
I'm going to go ahead and close this out. If you still have issues or have more information about the issue you were seeing feel free to reopen.
