### ISSUE TITLE
v 4.4.2 crashes with .NET 4.6

### ISSUE THREAD

**Issue by criistii** [firebase/quickstart-unity#138]
Hi,
I recently updated to Firebase 4.4.2 on a Unity project I am working on. The project uses .NET 4.6 under Unity 2017.3.1f1.

As soon as I call FirebaseApp.DefaultInstance, the editor crashes. I was able to reproduce the bug in a blank project. If the project is .NET 4.6 the editor crashes. If the project is .NET 3.5, everything is fine.

Please advice.

Thanks,

**Comment by criistii** [comment]
The proposed option did not work. I compiled the project both debug and released, and tried both versions of the dll. The editor is still crashing.
I am attaching the log file in case it helps.
In the meantime, can you point me to where I can get an older version of Firebase, so I can continue working?
[Editor.log](https://github.com/firebase/quickstart-unity/files/1728754/Editor.log)

**Comment by stewartmiles** [comment]
@a-maurice the stack trace is pointing at some code you was poking at recently, ring any bells?

@criistii thanks for reporting.

All prior releases are available from

https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_VERSION.zip

e.g

https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_4.4.0.zip

4.4.1 was broken due to the iOS SDK it depends upon being revoked.

**Comment by criistii** [comment]
Small update: I spent most of the day today trying to fix this. I tied different Unity versions and different Firebase versions (as low as 4.2.1). All of them are crashing in .NET 4.6 mode. Not sure how to fix this.

**Comment by stewartmiles** [comment]
@criistii there must be something "different" with your machine vs. our test environments.  What's the host operating system, Windows, OSX, Linux?  Anything else you can share?

**Comment by criistii** [comment]
I am working under MacOS 10.13.3. I did several clean installs of unity (moved the app to Trash). In case there are any caches I am not aware of, please let me know.
If you need more information, I would gladly help. Just let me know what you need.

Thansk,

**Comment by stewartmiles** [comment]
@criistii, @patrickhoh patched the Unity SDK in [4.0.3](https://firebase.google.com/support/release-notes/unity#4.0.3) to workaround a Unity bug that broke certificate installation on OSX, essentially breaking the real-time database in the editor.  However, Unity have fixed their bug and now our workaround is bringing down the editor.  We have a patch internally which we're running through QA so expect a release to be posted next week.

In the meantime, I've attached a patched Firebase.Platform.dll (it's zipped) which you can use to replace `Assets/Firebase/Plugins/Firebase.Platform.dll` in the latest release of the SDK to workaround this issue.

[Firebase.Platform.dll.zip](https://github.com/firebase/quickstart-unity/files/1733244/Firebase.Platform.dll.zip)

**Comment by johnb003** [comment]
We just released a fix for this in Firebase Unity 4.4.3. https://firebase.google.com/support/release-notes/unity#4.4.3
