### ISSUE TITLE
Can Firebase Unity SDK's Analytics and Crashlytics be used on devices without Google Play? We are developing on Oculus.

### ISSUE THREAD

**Issue by ayamzh** [firebase/quickstart-unity#1385]
Can Firebase Unity SDK's Analytics and Crashlytics be used on devices without Google Play? We are developing on Oculus.

**Comment by argzdev** [comment]
Hey @ayamzh, thanks for reaching out. According to our [documentations](https://firebase.google.com/docs/android/android-play-services#play-services-required-summary):

> Firebase SDKs can be divided into three categories:
> 
> **Play services required** — These SDKs require Google Play services, otherwise they have no functionality.
> **Play services recommended** — These SDKs require Google Play services to have full functionality, but they still offer most functionality even without Google Play services.
> **Play services not required** — These SDKS do not require Google Play services to have full functionality.

In this case, Google Analytics **recommends** having Google Play services. Additionally, The Firebase SDK for Google Analytics can send events on any device, but some automatic insights such as demographics are only available on devices with Google Play services.

Firebase Crashlytics on the other hand, does not require Google Play services to work. That said, I believe this answers the question. I'll go ahead and close this thread.
