### ISSUE TITLE
I can't get data after login.

### ISSUE THREAD

**Issue by TriflesGames** [firebase/quickstart-unity#14]
Hi everyone, 
I am using Firebase on 7-10 days and it is life saver but i have a little problem.

I can GET and SAVE data. It's working. But when i login...
Firebase database rules,
`{
  "rules": 
 {
    ".read": true,
    ".write": true
  }
}`

( I know i know it's looks terrible but i am testing on firebase. )

I was used Facebook Login and Email login. I am login succesfully and i am getting display name ...etc.
But when i use childAdded or GetValueAsync methods it's not working. I want get /questions/Mat/

IMPORTANT: I am login successfull and now pressing button "Get Data" and waiting. 10 seconds after i am pressing "Signout Button" = Signout Successfull and coming data... Working childAdded. It's very interesting, isn't ?

Thanks for all and sorry for my English :)

**Comment by benwulfe** [comment]
Sorry for the delay.  Are you using the database quickstart as it is or have you made any other changes?
And the problem you see is that when you enable Auth by signing in, there is a problem?  One thing you should be aware of is that Firebase Authentication is not currently supported in the Unity Editor.  So if you can provide where you are running the same (editor/android/ios) that would help as well.

**Comment by stewartmiles** [comment]
No response for a few months, closing.  Please reopen if you still have a problem.
