### ISSUE TITLE
Download File

### ISSUE THREAD

**Issue by alvincrisuy** [firebase/quickstart-unity#140]
The download file is successful.

But it has a delay when starting to download.

**Comment by stewartmiles** [comment]
Hi @alvincrisuy could you describe in more detail the issue that you're having?

If you're seeing a delay downloading a file with Firebase Storage perhaps this is related to your network conditions?

Cheers,
Stewart

**Comment by alvincrisuy** [comment]
My internet was ok. I will try to review it and give feedback 😄

because i noticed that it takes 1 ~ 10 secs before it starts to download a single file...

**Comment by cluetivity** [comment]
Hi, I have also problems with downloading. does not matter if I user GetFileAsync() or GetStreamAsync(). The Download starts and completes fine, but the progress handling gets fired after or at the end of the download. 

So it feels like nothing happens (no progress gets logged) and after the file has been downloaded it logs all the progress messages at once. I need the progress to get updated "live".
Is this a bug? Please help

**Comment by stewartmiles** [comment]
We replaced the Firebase Storage implementation in 4.5.0 (see https://firebase.google.com/support/release-notes/unity#4.5.0) which should resolve these issues.

**Comment by alexames** [comment]
Here is an example of how you download a file in our sample app:

https://github.com/firebase/quickstart-unity/blob/master/storage/testapp/Assets/TestApp/UIHandler.cs#L331

The documentation for that function can be found here:

[User guide](https://firebase.google.com/docs/storage/unity/download-files)  
[Reference page
](https://firebase.google.com/docs/reference/unity/class/firebase/storage/storage-reference#class_firebase_1_1_storage_1_1_storage_reference_1a508211331c961b5af65c6da8132ef59a)
