### ISSUE TITLE
Simultaneous connection number is too high !?

### ISSUE THREAD

**Issue by MERTKIRKALI** [firebase/quickstart-unity#142]
Hi,

I am the only user on my real-time database. But sometimes my database simultaneous connection number is going 8. Am i need to close connection or something in my codes ?

Best regards.

**Comment by stewartmiles** [comment]
Hi @MERTKIRKALI could you describe in more detail the issue you're seeing?  Is the SDK reporting an unexpected error?  Do you have any example code that can reproduce the issue?

Cheers,
Stewart

**Comment by stewartmiles** [comment]
Haven't heard from you in a while, closing this out.
