### ISSUE TITLE
StorageProgress does not get fired while downloading? urgent!

### ISSUE THREAD

**Issue by cluetivity** [firebase/quickstart-unity#144]
Hi,

I am downloading a file with GetFileAsync() or GetStreamAsync() and pass a handler for handling the progress. The download starts immediatly but there is no progress update while downloading. All the progress updates are fired at once when the download finishes. My console gets spammed with all my progress logs at once. 

I thought I have an issue in my code but I tried the sample Project here and the same is happening. Is this a bug in firebase sdk? One cannot build a progress bar.

When downloading a video file, it looks as if nothing happens for 20 seconds and then my progress bar is handling hundrets of updates at once.

please help us if there is a workaround.

**Comment by stewartmiles** [comment]
@cluetivity we have a fix for this internally and expect to have this out shortly.  In the meantime all you can do is fake download progress or use GetBytesAsync().

Cheers,
Stewart

**Comment by stewartmiles** [comment]
@cluetivity in our 4.5.0 update this should be resolved.  https://firebase.google.com/support/release-notes/unity#4.5.0 .  The storage API is now backed by a C++ implementation on desktop and the Android and iOS SDKs on mobile.
