### ISSUE TITLE
Does GetValueAsync() Timeout ?

### ISSUE THREAD

**Issue by rvlietstra** [firebase/quickstart-unity#145]
Hi.
Is there a way to timeout GetValueAsync() ? If I login, then disable my wifi and then do a GetValueAsync() it blocks indefinitely. I'm running the following code inside a Task.Run(() => {})

    static public bool Exists(string something)
    {
        bool exists = false;
        DatabaseReference db = FirebaseDatabase.DefaultInstance.RootReference;
        db.Child("Something").OrderByChild("SomeProperty").EqualTo(something).GetValueAsync().ContinueWith(s =>
        {
            if (s.IsFaulted || s.IsCanceled)
            {
                throw new SomeException();
                return; 
            }
            exists = true;
        }).Wait();

        return exists;
    }

Should I be checking for the existence of a child in some other way ?

Thanks!

**Comment by rival07** [comment]
ok

**Comment by stewartmiles** [comment]
@rvlietstra you need to perform your own network detection I'm afraid.  The API is designed to complete a transaction when the network becomes available.

**Comment by rvlietstra** [comment]
Hi @stewartmiles.

Ok, so I guess  `Application.internetReachability == NetworkReachability.NotReachable` is what I need to check before I do anything with firebase. 

There does then seem to be a race condition where I could check for connectivity which is then dropped before I execute the code. The mobile's awareness of connectivity could probably also be delayed by seconds.

It seems I cannot do the simplest data operation, checking if a value exists, without possibly hanging my app. Is there a way to cancel the task if it takes too long ? I'm using .net 3.5. There really needs to be an example for this (Maybe I'm just missing it)

Thanks for the reply!

**Comment by stewartmiles** [comment]
@rvlietstra there is an example here https://github.com/firebase/quickstart-unity/blob/master/database/testapp/Assets/TestApp/UIHandler.cs#L77 that shows how you could respond to changes from the server.

If you're setting values and want to ensure they're sent, you'll need to check connectivity for the duration of the transaction.  In your example, you're blocking on sending the value but you can poll tasks as well (e.g turning the task into a coroutine https://github.com/firebase/quickstart-unity/blob/master/storage/testapp/Assets/TestApp/UIHandler.cs#L116).

**Comment by rvlietstra** [comment]
@stewartmiles ok, by polling the task's completion and throwing a TimeoutException I believe I'm getting what I expect. The task still runs when connectivity is reestablished, but its just setting a local variable, so no harm.  It really feels like GetValueAsync() should throw a timeout exception itself. I would be interested in any comment on this code, how do I make this better ?

Thanks!

```
static public bool Exists(string somePropertyValue, CancellationToken cancellationToken)
    {
        // Get the root reference location of the database.
        DatabaseReference db = FirebaseDatabase.DefaultInstance.RootReference;

        // Check if we already have an entry for this post
        bool exists = false;
        Task task = db.Child("Something").OrderByChild("SomeChildProperty")
                           .EqualTo(somePropertyValue).GetValueAsync().ContinueWith(t =>
        {
            exists = t.Result.Exists;
        });

        // Poll the task's status
        DateTime startTime = DateTime.Now;
        while(!task.IsCompleted)
        {
            // Check if we are waiting too long o
            if ((DateTime.Now - startTime).TotalSeconds > TimeoutSeconds)
                throw new TimeoutException();

            // Check if a cancelation has been requested
            cancellationToken.ThrowIfCancellationRequested();

            // Wait a bit more
            Thread.Sleep(100);
        }

        // Check if the task is faulted
        if (task.IsFaulted)
            throw task.Exception;

        //
        return exists;
    }
```
