### ISSUE TITLE
Firebase Crashlytics Not Available for Unity

### ISSUE THREAD

**Issue by JamieCorkhill** [firebase/quickstart-unity#147]
In another issuse, someone raised the point that Crashlytics was not available for Unity.

I was able to use Crashlytics with Unity by setting up Crashlytics first with Fabric, and then linking that to Firebase. It is just a C# wrapper around the native Android and IOS crash handlers.

Will Firebase Crashlytics ever have official Google Firebase support?

**Comment by DevJoseWeb** [comment]
Where is your project?

**Comment by JamieCorkhill** [comment]
@DevJoseWeb I don't understand what you mean, My project is on Firebase, but I have to set up Crashlytics through Firebase and then link the two. Even after doing this, I don't get Crash Free Statistics, etc., in the console.

**Comment by TKBurner** [comment]
Thanks! Todd from Crashlytics here. Right now we don't offer Crashlytics for Unity on Firebase like we do in Fabric, but rest assured we are working on it and will roll it out as soon as it's available.

Thanks again! 👍

**Comment by Mitnainartinarian** [comment]
I'm interested in Crashlytics for Unity as well. If I implement it with Fabric now will it be easy to switch over to Firebase once it becomes available? Do you have an estimated time frame for it?

**Comment by JamieCorkhill** [comment]
@Mitnainartinarian I asked a Google Developer Advocate the same question over at this link: https://groups.google.com/forum/#!topic/firebase-talk/IpEOzmRMyPI 
and he said he could not provide a timeline. I don't know if @TKBurner can provide any more information.

**Comment by TKBurner** [comment]
Timeline is still vague on our end but the team is excited to take on this change. The big obstacle is that we currently use the Fabric plugin to onboard apps for Unity. However, if you follow the steps to onboard at Fabric first and then link to an existing Firebase project it may work today. 😀

**Comment by jhclaura** [comment]
@TKBurner do you know if Fabric Crashlytics works for Unity desktop standalone application? Or it's just for mobile? Thanks!

**Comment by TKBurner** [comment]
Thanks. Crashlytics only works for iOS and Android targets. Firebase is
only supported through a linking flow at this time.

**Comment by Kmess** [comment]
Is there any update regarding the timeline of the Unity plugin? Anxiously waiting to implement it :)

**Comment by nightrise** [comment]
Hey folks, with Google deprecating Fabric in favor of Firebase, this is going to be have a big impact on Unity Crashlytics users. Is there a timeline on when we can expect Crashlytics for Firebase in Unity? 

https://venturebeat.com/2018/09/14/google-is-killing-fabric-in-mid-2019-pushes-developers-to-firebase/

**Comment by AlesKriz** [comment]
Still no release?

**Comment by buihuuloc** [comment]
Any news ???

**Comment by JamieCorkhill** [comment]
I still don't have any news. For the time being, monitor the release notes.

https://firebase.google.com/support/releases

**Comment by cmlewis89** [comment]
+1 - any news?

**Comment by buihuuloc** [comment]
I think they are working on supporting for Unity. 
Hopefully, It will be available soon

**Comment by JamieCorkhill** [comment]
I believe Google Firebase has acquired Fabric. The transition roadmap on Fabric's website states that Crashlytics support for Unity is in progress:

https://get.fabric.io/roadmap#transition-plan

**Comment by henriqueranj** [comment]
Given that the Firebase Crashlytics SDK will be released "Mid 2019", are there any plans to maintain the Fabric SDK until then?

As with Unity 2018.3 for iOS there are some changes required for a build to happen. If anyone also faces this issue here is what I did to fix it:

1. Change all Fabric related files under `Plugins/Android/`  to support only Android platform in the Inspector - instead of Any Platform.
2. Change PostBuildiOS.cs variable `fabricPluginsPath `to be empty: `protected static readonly string fabricPluginsPath = "";`

**Comment by a-maurice** [comment]
Hi all,

We are still working on getting it ready, and hope to have it available as soon as possible for you all to use.

**Comment by buihuuloc** [comment]
Hey,
Do you have any ETA for that?

**Comment by Leuconoe** [comment]
bump, How is it going?

**Comment by anisabboud** [comment]
https://firebase.google.com/support/release-notes/unity
https://firebase.google.com/docs/crashlytics/get-started#unity

![image](https://user-images.githubusercontent.com/5672108/53095763-47bb5700-3526-11e9-998d-1aa80db8295e.png)

**Comment by TKBurner** [comment]
There is now Unity support available in Firebase Crashlytics. Please reach out via the Firebase support channel if you run into any issues getting started :)

**Comment by Kingkong302** [comment]
i am trying to implement firebase crashkytics  from previour 2 days.i have many other sdks already in my project,when i import firebase crashlytics sdk,it gives error when i try to create build in unity,here is the import screen where some files are going to change
![import screen](https://user-images.githubusercontent.com/39819701/53934468-d1d9f280-40c4-11e9-9ac6-498f76ce8a0f.png)
And when i try to build it gives error

**\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-17.0.5\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)**

and the 2nd error is 
 @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.android.support.support-compat-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.android.support.support-fragment-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.android.support.support-v4-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\com.google.firebase.firebase-analytics-impl-16.3.0\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\mopub\AndroidManifest.xml:12] Skipping identical /manifest/application/activity[@name=com.google.android.gms.ads.AdActivity] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\mopub\AndroidManifest.xml:22] Skipping identical /manifest/application/activity[@name=com.adcolony.sdk.AdColonyInterstitialActivity] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Irfan\Desktop\JA\Temp\StagingArea\android-libraries\mopub\AndroidManifest.xml:23] Skipping identical /manifest/application/activity[@name=com.adcolony.sdk.AdColonyAdViewActivity] element.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)

Please help me.
Thankyou

**Comment by stewartmiles** [comment]
@Kingkong302 you need to update your Android SDK.  See https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826
