### ISSUE TITLE
[Firebase SDK 4.5.0] : When signing in with Play Games then FirebaseUser.PhotoUrl is null

### ISSUE THREAD

**Issue by aditya2** [firebase/quickstart-unity#148]
I'm pretty new to firebase and somehow I managed to authenticate with firebase and everything works fine when I authenticate using Google SignIn. If I use Play Games SignIn as my provider, it perfectly authenticates me, but when I'm trying to fetch the profile picture of user using FirebaseUser.PhotoUrl method, it returns null, I'm not using Play Games Services plugin for unity for this purpose and made my own signin plugin with android studio which is working all fine and returning me a valid ServerAuthCode and I even used requestProfile() while bulding GoogleSignInOptions

**Comment by DevJoseWeb** [comment]
Where is your project?

**Comment by aditya2** [comment]
i don't know what you mean by project but below is the code i m using currently

Below is handleFirebase class which is taking care of firebase part
[handleFirebase.cs](https://pastebin.com/0AgbM11G)

Below is the android plugin i made to login to play services and bring back the serverAuthCode
[signInActivity.java](https://pastebin.com/6gjDiAhJ)

**Comment by stewartmiles** [comment]
@aditya2 did you resolve your issue?  I recommend trying the official Play Games Services plugin, if you continue to run into issues open a ticket via our support channel on http://firebase.google.com/support
