### ISSUE TITLE
SDK 4.5.0

### ISSUE THREAD

**Issue by mmvlad** [firebase/quickstart-unity#153]
Hi,
I am looking really hard trying to find SDK 4.5.0, as newer sdk wont work in my project because of play services 12+.

Where can I find it? 

Thank you

**Comment by stewartmiles** [comment]
You can always download prior releases using the URL https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_${version}.zip

For example:
https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_4.5.0.zip

Why can't you use 4.5.1 in your project?  It should upgrade to the latest Google Play Services instead.

**Comment by mmvlad** [comment]
Thanks, you should really make that link more obvious, like a archive page. 
Some of the plugins I am using work correctly only with 11.8 version of Play Services. As soon as they update to the latest, I will update to 4.5.1

**Comment by stewartmiles** [comment]
@mmvlad FYI I think 4.5.1 will still work with Play Services 11.8 as we adopted no new API surface in the Android SDK.  You'll just need to change the referenced version number in the Dependencies.xml files (see https://github.com/googlesamples/unity-jar-resolver#usage)
