### ISSUE TITLE
Showing FCM push notification in tray when app is in foreground

### ISSUE THREAD

**Issue by Mitnainartinarian** [firebase/quickstart-unity#155]
When my Unity app is in the foreground and I receive a push notification I get a callback to  FirebaseMessaging.MessageReceived. Instead I want the notification to show up in the tray, just as it does when the app is either closed or in the background. Is there a good way to do this in Unity with Firebase? Do I need to use a native plugin to recreate the notification as a local notification? I also need this behavior on iOS, and I want the new notification to be identical to the one for a closed or background app. What would all the cases be that I need to reproduce to make it identical? (ie. for audio, images, title, body, etc).

**Comment by stewartmiles** [comment]
@Mitnainartinarian at the moment you have to redirect this to a local notification manually, the behavior is similar on Android.  We've found most folks want to pop up an in-app notification rather than having stuff show up on the tray since it keeps users in the experience.  Is there anything else you could share about your use case?

**Comment by Mitnainartinarian** [comment]
Are there plans to make it possible to allow push notifications to show up
in the tray even when the app is in the foreground? This was available in
the previous push notifications platform I was using. There are many
reasons why I would want this. I won't go over them in this message, but
part of it is due to consistency as well as having fewer cases to deal with
in synching the push notifications along with my own messaging system
within the app.

**Comment by stewartmiles** [comment]
Hi @Mitnainartinarian 

Thank you for the interesting feature request.

We discussed this internally with our product management and have decided to not add this functionality to the SDK at the moment.  If we receive enough requests for this (you're the first) then we may consider it in future.

In the meantime:
* On iOS you could signal a local notification manually https://docs.unity3d.com/ScriptReference/iOS.LocalNotification.html
* On Android you'll need to plumb in some Java to do this https://answers.unity.com/questions/398209/android-notification-in-a-plugin.html

Cheers,
Stewart
