### ISSUE TITLE
Firebase 4.5.1 - Out of sync error when signing in

### ISSUE THREAD

**Issue by erikhoj** [firebase/quickstart-unity#157]
After succesfully signing in using FirebaseAuth.DefaultInstance.SignInWithCredentialsAsync(googleCredentials) i'm getting the following error on Android:

`04-24 13:54:44.788: E/Unity(31574): InvalidOperationException: out of sync
04-24 13:54:44.788: E/Unity(31574):   at System.Collections.Generic.Dictionary`2+Enumerator[System.IntPtr,Firebase.Unity.FirebaseAuthService+UserRefreshState].VerifyState () [0x00000] in <filename unknown>:0 
04-24 13:54:44.788: E/Unity(31574):   at System.Collections.Generic.Dictionary`2+Enumerator[System.IntPtr,Firebase.Unity.FirebaseAuthService+UserRefreshState].MoveNext () [0x00000] in <filename unknown>:0 
04-24 13:54:44.788: E/Unity(31574):   at Firebase.Unity.FirebaseAuthService.RefreshExpiredTokens (System.Object sender, System.EventArgs eventArgs) [0x00000] in <filename unknown>:0 
04-24 13:54:44.788: E/Unity(31574):   at Firebase.Platform.FirebaseHandler.Update () [0x00000] in <filename unknown>:0 
04-24 13:54:44.788: E/Unity(31574):   at Firebase.Platform.FirebaseMonoBehaviour.Update () [0x00000] in <filename unknown>:0 
04-24 13:54:44.788: E/Unity(31574):  
04-24 13:54:44.788: E/Unity(31574): (Filename:  Line: -1)
`

Afterwards, the firebase database disconnects. The error occurs independent on whether i use Google sign-in or Facebook sign-in.

I'm also having issues with Permission Denied errors when i try to read from the database after logging in. My rules can be seen below.

{
  "rules": {
    "shop": {
      ".read": true
    },
    "users": {
      "$uid": {
        ".read": "auth != null && $uid === auth.uid",
        ".write": "auth != null && $uid === auth.uid"
      }
    }
  }
}

When reading, i access /users/USER_ID, where USER_ID = FirebaseAuth.DefaultInstance.CurrentUser.UserId

**Comment by stewartmiles** [comment]
Hi @erikhoj , thanks for the bug report.  We just released a patch for this in 4.5.2 https://firebase.google.com/support/release-notes/unity#4.5.2 .

Cheers,
Stewart

**Comment by FoxtailGames** [comment]
I'm seeing this same issue in Unity 2018.1.3f1 with Auth v. 5.2. It occurs what seems to be randomly during sign in/log in flow.

Same error too I believe:

InvalidOperationException: out of sync
System.Collections.Generic.Dictionary`2+Enumerator[System.IntPtr,Firebase.Unity.FirebaseAuthService+UserRefreshState].VerifyState () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:912)
System.Collections.Generic.Dictionary`2+Enumerator[System.IntPtr,Firebase.Unity.FirebaseAuthService+UserRefreshState].MoveNext ()
Firebase.Unity.FirebaseAuthService.RefreshExpiredTokens (System.Object sender, System.EventArgs eventArgs)
Firebase.Platform.FirebaseHandler.Update ()
Firebase.Platform.FirebaseMonoBehaviour.Update ()
