### ISSUE TITLE
iOS Dynamic Links Issue Unity 2018.1b13

### ISSUE THREAD

**Issue by TeddyMathias** [firebase/quickstart-unity#158]
I’ve got a weird issue going on with a Dynamic Links and wondering if anyone else has had the same problem. When I build directly to device in XCode (using both 9.2 and 9.3) Dynamic Links work perfectly. However, when I archive the build or submit to TestFlight, the links always take me to Safari, even if the app is installed. I’m on iOS 11.3.

**Comment by stewartmiles** [comment]
If you haven't already, @TeddyMathias I recommend opening up a ticket with https://firebase.google.com/support/ and they can help you through your configuration issues.
