### ISSUE TITLE
WebSocketException on 2018.1 with .NET 4.6

### ISSUE THREAD

**Issue by seep** [firebase/quickstart-unity#162]
I'm getting WebSocketExceptions with the [database test app](https://github.com/firebase/quickstart-unity/tree/master/database/testapp) when using the .NET 4.x Equivalent scripting runtime with Unity 2018.1 on MacOS. Steps to reproduce:

1. Open the test project.
2. Import `FirebaseDatabase.unitypackage`
3. Switch the scripting runtime to .NET 4.x equivalent and restart.
4. Replace `Unity.Compat` and `Unity.Tasks` with the 4.x versions.

Starting the app results in this error:
```
5/16/2018 2:54:10 PM [Error] WebSocket: ws_0 - could not connect
System.Net.Sockets.SocketException (0x80004005): No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <02438dbdf7944a1dbd1e6659c57b6168>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <02438dbdf7944a1dbd1e6659c57b6168>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000f3] in <60689ba4405e464088a14ab575aa386b>:0 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception)
Firebase.Database.Internal.TubeSock.WebSocket:CreateSocket()
Firebase.Database.Internal.TubeSock.WebSocket:RunReader()
Firebase.Database.Internal.TubeSock.Runnable101:Run()
Google.Sharpen.Thread:InternalRun()
System.Threading.ThreadHelper:ThreadStart()
```

The test app works fine in the same environment with the .NET 3.x scripting runtime.

**Comment by asarazan** [comment]
+1 to this. It also happens for me on Android builds. I had things working on 2017 and then made the dumb decision to try an upgrade.

**Comment by NBaron** [comment]
Same thing for me using Unity 2018.1.0f2 on Android.
There is no problem on Galaxy Note 8 and S8 which manage to connect correctly.
But, on some devices like Galaxy S7, OnePlus 5 and Nexus 6P there is an error regarding Kernel32.dll... on Android!
It's like the runtime try to locate Windows specific DLL without knowing it is on Android platform.

> 05-31 22:43:59.530 28652 28751 E Unity   : Unable to find Kernel32
05-31 22:43:59.805 28652 28751 E Unity   : 05/31/2018 20:43:59 [Error] WebSocket: ws_0 - could not connect
05-31 22:43:59.805 28652 28751 E Unity   : System.Net.Sockets.SocketException (0x80004005): Network is unreachable
05-31 22:43:59.805 28652 28751 E Unity   :   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <02438dbdf7944a1dbd1e6659c57b6168>:0
05-31 22:43:59.805 28652 28751 E Unity   :   at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <02438dbdf7944a1dbd1e6659c57b6168>:0
05-31 22:43:59.805 28652 28751 E Unity   :   at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000f3] in <60689ba4405e464088a14ab575aa386b>:0
05-31 22:43:59.805 28652 28751 E Unity   :
05-31 22:43:59.805 28652 28751 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
05-31 22:43:59.805 28652 28751 E Unity   :


> 05-31 22:43:59.807 28652 28751 E Unity   : 05/31/2018 20:43:59 [Error] WebSocket: ws_0 - WebSocketException during handshake
05-31 22:43:59.807 28652 28751 E Unity   : Firebase.Database.Internal.TubeSock.WebSocketException: unknown host: swarms-tcp.firebaseio.com ---> System.Net.Sockets.SocketException: Network is unreachable
05-31 22:43:59.807 28652 28751 E Unity   :   at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <02438dbdf7944a1dbd1e6659c57b6168>:0
05-31 22:43:59.807 28652 28751 E Unity   :   at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <02438dbdf7944a1dbd1e6659c57b6168>:0
05-31 22:43:59.807 28652 28751 E Unity   :   at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000f3] in <60689ba4405e464088a14ab575aa386b>:0
05-31 22:43:59.807 28652 28751 E Unity   :    --- End of inner exception stack trace ---
05-31 22:43:59.807 28652 28751 E Unity   :   at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x0011e] in <60689ba4405e464088a14ab575aa386b>:0
05-31 22:43:59.807 28652 28751 E Unity   :   at Firebase.Database.Internal.TubeSock.WebSocket.RunReader () [0x0001b] in <60689ba4405e464088a14ab575aa386b>:0
05-31 22:43:59.807 28652 28751 E Unity   :
05-31 22:43:59.807 28652 28751 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)

**Comment by stewartmiles** [comment]
This is a duplicate issue to #162 we've had multiple reports of problems with the RT DB (which is the last plugin to use Unity's network stack and a conversion of https://github.com/firebase/TubeSock to C#).  We're migrating the RT DB plugin to the native implementations on each platform.  We're *hoping* our next release following 5.0.0 will have a new implementation for mobile to mitigate these issues.   I'll close this issue out, feel free to continue discussion on #162.

**Comment by seep** [comment]
@stewartmiles thanks for the update. Did you mean to link another issue? This is issue #162.

**Comment by PCoelho** [comment]
He might have meant #106

**Comment by douglas-martins** [comment]
I'm using the 5.0.0 sdk version and the error still happen.
Anyone here can give me some light?

**Comment by seep** [comment]
@douglas-martins they're hoping to resolve this in the next release after 5.0.0.

**Comment by yalfers** [comment]
Are there any updates on this? I've come across this recently as well...

**Comment by stewartmiles** [comment]
@yalfers as described on https://github.com/firebase/quickstart-unity/issues/106 (this issue is a duplicate) 5.1.0 migrated the real-time database to the native Android and iOS SDKs, we're still working on migrating the desktop implementation.  If you're running into issues on Android or iOS with 5.1.0, please post the details to https://github.com/firebase/quickstart-unity/issues/106 .

**Comment by eladleb** [comment]
@stewartmiles will you update here once the desktop implementation ships as well, most of the work we do is on the editor so I guess I'm staying at .net 3.5 for the time being.

**Comment by stewartmiles** [comment]
Yep apologies, we'll be updating #106 when we ship the SDK that replaces RT DB in the editor with the C++ desktop implementation.  Closing this out again, feel free to follow along on #106
