### ISSUE TITLE
https:// URL referencing not working

### ISSUE THREAD

**Issue by alvincrisuy** [firebase/quickstart-unity#168]
In the tutorial https://firebase.google.com/docs/storage/unity/download-files

```
Firebase.Storage.StorageReference https_reference = storage.GetReferenceFromUrl("https://firebasestorage.googleapis.com/b/bucket/o/images%20stars.jpg");
```

Using this one does not work anymore.
```
StorageReference reference = FirebaseStorage.DefaultInstance.GetReferenceFromUrl(path);
```
ERROR: Unable to create StorageReference from URL https://firebasestorage.googleapis.com/v0/b/omniscope-mobile.appspot.com/o/Target.mov. URL specifies a different bucket (firebasestorage.googleapis.com) than this instance (omniscope-mobile.appspot.com)

In the latest version, this functionality does not work anymore. Though in version 4.4.3 it is working

**Comment by stewartmiles** [comment]
It looks like we're incorrectly using the domain part of the URL to validate the bucket which is unfortunate.  To workaround this you can use a gs:// scheme URL instead of https://, it will still connect with https under the hood.

**Comment by stewartmiles** [comment]
@alvincrisuy which platform did you see this behavior on?  I'm assuming desktop?

**Comment by alvincrisuy** [comment]
@stewartmiles I'm deploying it on iOS. I'm not sure on other platforms if this also occurs.

**Comment by stewartmiles** [comment]
The 5.1.0 release of the Firebase Unity SDK resolves this issue:
Release notes: https://firebase.google.com/support/release-notes/unity#5.1.0
Download: https://firebase.google.com/docs/unity/setup
