### ISSUE TITLE
Exception in AuthStateChanged iOS

### ISSUE THREAD

**Issue by HsanBenJobrane** [firebase/quickstart-unity#169]
When I try to sign in with Facebook and continue to login with Firebase, this exception is logged in Xcode

2018-06-06 01:32:49.534572+0100 [1258:91581] ERROR: ret == 0 || ret == 22
ApplicationException: ret == 0 || ret == 22
  at Firebase.Auth.FirebaseAuth.get_CurrentUserInternal () [0x00000] in <filename unknown>:0 
  at Firebase.Auth.FirebaseAuth.get_CurrentUser () [0x00000] in <filename unknown>:0 
  at Firebase.Unity.FirebaseAuthService.OnIdTokenChanged (Firebase.Auth.FirebaseAuth auth) [0x00000] in <filename unknown>:0 
  at Firebase.Auth.FirebaseAuth.ForwardStateChange (IntPtr appCPtr, System.Action`1 stateChangeClosure) [0x00000] in <filename unknown>:0 
  at Firebase.AppUtil.PollCallbacks () [0x00000] in <filename unknown>:0 
  at Firebase.Platform.FirebaseHandler.Update () [0x00000] in <filename unknown>:0

**Comment by stewartmiles** [comment]
@HsanBenJobrane any more details about this would be useful.

**Comment by HsanBenJobrane** [comment]
Sorry for the late response, I inspected the returned value after a user signup and it seems I get a null reference in the user.PhotoUrl.AbsoluteUri which is very odd.

```C#
FirebaseUser user = task.Result;

string photoUrl = "https://graph.facebook.com/" + aToken.UserId + "/picture?height=500";

User aUser = new User
{
    UID = user.UserId,
    NAME = user.DisplayName,
    PHOTO = user.PhotoUrl.AbsoluteUri // this was null on iOS after signup with Facebook
};
```

So eventually I constructed it like this

```C#
FirebaseUser user = task.Result;

string photoUrl = "https://graph.facebook.com/" + aToken.UserId + "/picture?height=500";

User aUser = new User
{
    UID = user.UserId,
    NAME = user.DisplayName,
    PHOTO = photoUrl
};
```

**Comment by stewartmiles** [comment]
Hi @HsanBenJobrane thanks for the response.  It sounds like the missing Facebook PhotoUrl is a separate issue that I'm glad you found a workaround for.  Any addition information on reproducing the exception you saw when signing in?

**Comment by stewartmiles** [comment]
Also, @HsanBenJobrane if you could share the code you was using to login with Facebook that caused the assert it would really help.

**Comment by HsanBenJobrane** [comment]
Here's the code for the login with Facebook method

```C#
FB.LogInWithReadPermissions(permissions, (result) => {
    if (FB.IsLoggedIn)
    {
        var aToken = Facebook.Unity.AccessToken.CurrentAccessToken;

        Credential credential = Firebase.Auth.FacebookAuthProvider.GetCredential(aToken.TokenString);

        FirebaseAuth.DefaultInstance.SignInWithCredentialAsync(credential).ContinueWith(task => {
            
            if (task.IsCanceled)
            {
                Debug.Log("Auth With Facebook Cancelled");

                Failed("Firebase Cancel");

                return;
            }

            if (task.IsFaulted)
            {
                Debug.Log("Task is Faulted : " + task.Exception.Message);

                Failed(task.Exception.Message);

                return;
            }				

            FirebaseUser user = task.Result;

            Debug.Log("User logged in " + user.DisplayName);

            User aUser = new User
            {
                UID = user.UserId,
                NAME = user.DisplayName,
                PHOTO = user.PhotoUrl.AbsoluteUri
            };

            Success(aUser);
        });
    } else
    {
        Debug.Log("User cancelled login");
        Failed("Facebook Cancel");
    }
});
```

**Comment by stewartmiles** [comment]
@HsanBenJobrane user.PhotoUrl can be null so your code is strictly wrong.  That said, we did find a bug which resulted in the PhotoUrl not being set on iOS that is now fixed and should be published in a release in the next couple of days.

**Comment by stewartmiles** [comment]
The 5.1.0 release of the Firebase Unity SDK resolves this issue:
Release notes: https://firebase.google.com/support/release-notes/unity#5.1.0
Download: https://firebase.google.com/docs/unity/setup
