### ISSUE TITLE
problem when using both FirebaseAuth and FirebaseDatabase

### ISSUE THREAD

**Issue by duclong2301** [firebase/quickstart-unity#17]
I single use FirebaseAuth(use facebook token) or FirebaseDatabase(realtime database)  it work perfectly (Android).
But I use both of them, my app freeze after login. Folow:
1. Connect database (nothing happen, if push data, it work)
2.Login with facebook sdk to get token.(still work)
3. Login with FirebaseAuth use facebook token..... ->> app freeze. (or not freeze  but cannot push data with FirebaseDatabase plugin)
Sr, my English.

**Comment by stewartmiles** [comment]
Any chance you could share a modified sample application that demonstrates this?

**Comment by duclong2301** [comment]
I detected , if not logout firebase auth, can't push data.
[Here ](http://www.mediafire.com/file/zzhwjoxdbr66mc7/FirebaseDemoProject.rar)my demo project.
Thanks for help!

**Comment by mxkacsa** [comment]
I have same issue but i use only FirebaseAuth in the project.
Create user works fine, but throw exception on android (Galaxy S7)
When I sign in or delete user the application always freeze, but only when return with completed.

[image screenshot from android with exception](https://goo.gl/photos/WbjfCqLbtjeZM4zz8)

**Comment by stewartmiles** [comment]
Are you sure you have your database rules configured so that the logged in user can push to the database?  If you can't share specific information on this public thread could you contact support@firebase.google.com and we can discuss this further there ?

**Comment by mxkacsa** [comment]
I installed 1.1.0 sdk and now works fine! :)

**Comment by alehkudrevich** [comment]
Same problem here. When I login with Facebook token and try to get data from database, my editor freeze or crash without stacktrace information.
I think facebook auth does not work properly.

**Comment by stewartmiles** [comment]
@alehkudrevich any chance you have any more information about this?  We discovered a problem with Auth that could lead to a hang when signing in but I don't believe we've seen the error you're describing.

You mention your editor freeze / crashes, are you running in the editor?  If so, we don't really support Firebase Authentication in the editor at the moment as we only provide a stub implementation.

**Comment by stewartmiles** [comment]
This should be resolved in version 1.1.1
https://firebase.google.com/support/release-notes/unity#1.1.1
