### ISSUE TITLE
Firebase SDK 5.0 Download error in iOS

### ISSUE THREAD

**Issue by alvincrisuy** [firebase/quickstart-unity#171]
Cannot download file in iOS

shows this message after debugging a lot.

(Filename: /Users/builduser/buildslave/unity/build/Runtime/Export/Debug.bindings.h Line: 43)

ERROR1: System.AggregateException: Exception of type 'System.AggregateException' was thrown.
-----------------
Firebase.Storage.StorageException: An unknown error occurred

Omniscope.<DownloadSingleFile>c__AnonStorey2:<>m__0(Task)
System.Threading.Tasks.<ContinueWith>c__AnonStorey2:<>m__0(Task)
System.Threading.Tasks.<ContinueWith>c__AnonStorey1:<>m__0()
System.Threading.Tasks.Task:<immediateExecutor>m__1(Action)
System.Threading.Tasks.Task`1:RunContinuations()

The download was finished but IsFaulted remains true. I don't know why is this happening. Before it was working in 4.5.2. Seems weird. Need to implement this ASAP.

**Comment by stewartmiles** [comment]
@alvincrisuy does this happen in the sample application?  If not, I recommend opening a ticket on https://firebase.google.com/support/

**Comment by stewartmiles** [comment]
@alvincrisuy any update on this?

**Comment by stewartmiles** [comment]
@alvincrisuy I'll assume you resolved your problem, let us know if you're still running into issues with the sample project.
