### ISSUE TITLE
Can not setting PhotoUrl in UserProfile

### ISSUE THREAD

**Issue by popeyaho** [firebase/quickstart-unity#173]
I'm setting the DisplayName and PhotoUrl properties of a new account. 
Example code in MechHasmter, i was customized
```c#
                            Firebase.Auth.UserProfile profile = new Firebase.Auth.UserProfile();
                            profile.DisplayName = dialogComponent.DisplayName.text;
                            System.Uri urlphoto = new System.Uri(dialogComponent.DisplayUrl.text);
                            profile.PhotoUrl = urlphoto;
                            auth.CurrentUser.UpdateUserProfileAsync(profile);
```

after Update profile aka create new acc, I did Debug.Log() for get DisplayName and PhotoUrl agains. This code returns the username and Uri in Android build, DisplayName has been set correctly, but PhotoUrl is Null:
```c#
Debug.LogError(auth.CurrentUser.Email + " " + auth.CurrentUser.DisplayName + " " + auth.CurrentUser.PhotoUrl);
```
so what i was mistaken, can you help, thanks so much!

**Comment by stewartmiles** [comment]
We've confirmed this is a bug, the fix is lined up for our next release which should be published in a few days.

**Comment by stewartmiles** [comment]
The 5.1.0 release of the Firebase Unity SDK resolves this issue:
Release notes: https://firebase.google.com/support/release-notes/unity#5.1.0
Download: https://firebase.google.com/docs/unity/setup
