### ISSUE TITLE
[Unity2017.2][Messaging]can't receive message when app is functioning

### ISSUE THREAD

**Issue by gooddereklu** [firebase/quickstart-unity#174]
Hi Guys!

I tried to use the firebase messaging function in Unity and so far it wasn't very well!!

I don't know which part went wrong and this is really bothering me!!

Here's the following steps! 

1.create a project from Unity 2017.2.0
2.drag the "FirebaseMessaging.unitypackage" into the project.
3.download my specific "google-services.json" file into the project
4.create a script and put it into the scene
the script is like below

public void Start() {
  Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
  Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
}
public void OnTokenReceived(object sender, Firebase.Messaging.TokenReceivedEventArgs token) {
  DebugText.text = "Received Registration Token: " + token.Token;
}
public void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e) {
  DebugText.text = "Received a new message from: " + e.Message.From;
}

5.build it into app and install it

result : everything worked well when the app is run in background. I can receive message soon after I send the message from Firebase, but when I turn on the app it just won't receive message anymore!
and not even the OnTokenReceived or OnMessageReceived gets called. any sugession?

**Comment by alexames** [comment]
The code you wrote there looks reasonable to me. I tried downloading the lastest SDK and running it in the quickstart app and I was able to receive messages when the app was in the foreground and when the app was in the background. 
 
How have you verified that your callbacks aren't getting called at all? I'm not sure what DebugText.text is supposed to do. Have you tried printing logs? Does it work when you run the Unity Messaging testapp?

**Comment by gooddereklu** [comment]
Hi Alex!
DebugText.text is just a simple UI Text object on the screen
I just use it to print log in a more Unity way.
I just tried the MainScene in testApp form messaging
I got the result of 

    "One or more Firebase dependencies are not present. Current dependency status: UnavailableOther"

could this be the reason that doesn't work?

**Comment by alexames** [comment]
Yeah, that would definitely be it. That can happen if you didn't have the necessary SDK's for Android set up in Unity before you imported Firebase plugin (I'm referring here to the Android SDK, the Android NDK, and the Java runtime). Without those set up, there can be errors when the plugin is installed. There might be other ways to cause this, but one way I know for sure you can cause that error. You might try deleting and re-importing the Firebase plugin. I think that will fix the issue.

**Comment by gooddereklu** [comment]
android SDK : 16 to 28
java jdk version : 1.8.0.171
ndk version: r13b

so far from my understanding I think these are all latest. Is there any situation that may cause this rather then SDK version?

p.s I also try the Force Resolve button, It didn't work, Resolve though does, the error message says "grandle failed to fetch dependency"

**Comment by alexames** [comment]
Are there any other errors or warnings that show up in the Unity console after you see that error?

**Comment by gooddereklu** [comment]
Resolution failed

Failed to fetch the following dependencies:
com.google.android.gms:play-services-base:15.0.1
com.google.firebase:firebase-common:16.0.0
com.google.firebase:firebase-core:16.0.0
com.google.firebase:firebase-app-unity:5.0.0
com.google.firebase:firebase-messaging:17.0.0
com.google.firebase:firebase-messaging-unity:5.0.0

I also got this

**Comment by stewartmiles** [comment]
@gooddereklu the second error message describes what you need to do.

```
JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

From Oracle (Java folks):
https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/

From Unity developers:
https://forum.unity.com/threads/android-unable-to-build-jdk-error-unable-to-find-jdk.193318/

From a person with a step by step guide:
https://koprowski.it/2017/unity-android-config/

**Comment by stewartmiles** [comment]
@gooddereklu if you continue to have issues setting up Unity please open a ticket with https://firebase.google.com/support/ and they can help you through the process.

**Comment by gooddereklu** [comment]
fter a few days of study I finally have it work on my phone. 
Basically you have to set your enviroment right to achieve your goal of "Getting Message from Firebase with your Unity App"
here is setup you need
1.Install NDK and setup from Preference
	Download the NDK compressed file and unzip it to the location you want
	Go to Unity > Edit > Preference > External Tools and set the NDK location to where you unzip it.
	**WARNING: THE NDK VERSION MUST ABOVE R10!!!**

2.Set up your JAVA_HOME Enviroment 
	If you don't have jdk, go to Oracle website and download JDK (version 1.8.0_171 is recomanded)
	http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
	If you already have jdk installed, then follow the instructions from the video below
	https://www.youtube.com/watch?v=Y6LT5lgOj0Y

3.Make sure you have .aar file in your (UnityProjectName)/Assets/Plugins/Android 
	If you don't have those file, go to Assets > Play Services Resolver > Android Resolver > Force Resolve.
	It should help you get all those .arr file, if there's error coming out says "Grandle failed" then means you have finish the previous steps

4.Set your Unity Build Settings > Build System to "Grandle" and also setup Player Settings > Publishing Settings > Build System to grandle as well
5.Generate a new keystore
6.Build Your App at last!!!!!
