### ISSUE TITLE
Error: more than one library with package name 'com.google.games.bridge'

### ISSUE THREAD

**Issue by MarcoSchneider123** [firebase/quickstart-unity#176]
I wanted to set up Firebase Analytics in my Unity Project. I downloaded the newest version, but i think it conflicts with another library (Maybe GooglePlayServices), but i can't find the reason. Any help is appreciated. It is an Android Project.

I read in the internet, that i should check the Assets/

Plugins/Android folder, but i couldn't find duplicates. I will attach the folder to analyse.

The following is the error.

UnityEditor.BuildPlayerWindow+BuildMethodException: Build failed with errors.
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x001b9] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:162 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEditor.HostView:OnGUI()

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_111\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> Error: more than one library with package name 'com.google.games.bridge'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:compileReleaseNdk UP-TO-DATE
:Firebase:compileLint
:Firebase:copyReleaseLint UP-TO-DATE
:Firebase:mergeReleaseProguardFiles
:Firebase:packageReleaseRenderscript UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:prepareReleaseDependencies
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:Firebase:compileReleaseAidl
:Firebase:generateReleaseBuildConfig
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:mergeReleaseAssets
:Firebase:processReleaseManifest
:Firebase:processReleaseResources
:Firebase:generateReleaseSources
:Firebase:incrementalReleaseJavaCompilationSafeguard
:Firebase:compileReleaseJavaWithJavac
:Firebase:processReleaseJavaRes UP-TO-DATE
:Firebase:transformResourcesWithMergeJavaResForRelease
:Firebase:transformClassesAndResourcesWithSyncLibJarsForRelease
:Firebase:mergeReleaseJniLibFolders
:Firebase:transformNative_libsWithMergeJniLibsForRelease
:Firebase:transformNative_libsWithSyncJniLibsForRelease
:Firebase:bundleRelease
:GoogleMobileAdsPlugin:preBuild UP-TO-DATE
:GoogleMobileAdsPlugin:preReleaseBuild UP-TO-DATE
:GoogleMobileAdsPlugin:compileReleaseNdk UP-TO-DATE
:GoogleMobileAdsPlugin:compileLint
:GoogleMobileAdsPlugin:copyReleaseLint UP-TO-DATE
:GoogleMobileAdsPlugin:mergeReleaseProguardFiles
:GoogleMobileAdsPlugin:packageReleaseRenderscript UP-TO-DATE
:GoogleMobileAdsPlugin:checkReleaseManifest
:GoogleMobileAdsPlugin:prepareReleaseDependencies
:GoogleMobileAdsPlugin:compileReleaseRenderscript
:GoogleMobileAdsPlugin:generateReleaseResValues
:GoogleMobileAdsPlugin:generateReleaseResources
:GoogleMobileAdsPlugin:packageReleaseResources
:GoogleMobileAdsPlugin:compileReleaseAidl
:GoogleMobileAdsPlugin:generateReleaseBuildConfig
:GoogleMobileAdsPlugin:mergeReleaseShaders
:GoogleMobileAdsPlugin:compileReleaseShaders
:GoogleMobileAdsPlugin:generateReleaseAssets
:GoogleMobileAdsPlugin:mergeReleaseAssets
:GoogleMobileAdsPlugin:processReleaseManifest
:GoogleMobileAdsPlugin:processReleaseResources
:GoogleMobileAdsPlugin:generateReleaseSources
:GoogleMobileAdsPlugin:incrementalReleaseJavaCompilationSafeguard
:GoogleMobileAdsPlugin:compileReleaseJavaWithJavac
:GoogleMobileAdsPlugin:processReleaseJavaRes UP-TO-DATE
:GoogleMobileAdsPlugin:transformResourcesWithMergeJavaResForRelease
:GoogleMobileAdsPlugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GoogleMobileAdsPlugin:mergeReleaseJniLibFolders
:GoogleMobileAdsPlugin:transformNative_libsWithMergeJniLibsForRelease
:GoogleMobileAdsPlugin:transformNative_libsWithSyncJniLibsForRelease
:GoogleMobileAdsPlugin:bundleRelease
:GooglePlayGamesManifest.plugin:preBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:preReleaseBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:compileReleaseNdk UP-TO-DATE
:GooglePlayGamesManifest.plugin:compileLint
:GooglePlayGamesManifest.plugin:copyReleaseLint UP-TO-DATE
:GooglePlayGamesManifest.plugin:mergeReleaseProguardFiles
:GooglePlayGamesManifest.plugin:packageReleaseRenderscript UP-TO-DATE
:GooglePlayGamesManifest.plugin:checkReleaseManifest
:GooglePlayGamesManifest.plugin:prepareReleaseDependencies
:GooglePlayGamesManifest.plugin:compileReleaseRenderscript
:GooglePlayGamesManifest.plugin:generateReleaseResValues
:GooglePlayGamesManifest.plugin:generateReleaseResources
:GooglePlayGamesManifest.plugin:packageReleaseResources
:GooglePlayGamesManifest.plugin:compileReleaseAidl
:GooglePlayGamesManifest.plugin:generateReleaseBuildConfig
:GooglePlayGamesManifest.plugin:mergeReleaseShaders
:GooglePlayGamesManifest.plugin:compileReleaseShaders
:GooglePlayGamesManifest.plugin:generateReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseAssets
:GooglePlayGamesManifest.plugin:processReleaseManifest
:GooglePlayGamesManifest.plugin:processReleaseResources
:GooglePlayGamesManifest.plugin:generateReleaseSources
:GooglePlayGamesManifest.plugin:incrementalReleaseJavaCompilationSafeguard
:GooglePlayGamesManifest.plugin:compileReleaseJavaWithJavac
:GooglePlayGamesManifest.plugin:processReleaseJavaRes UP-TO-DATE
:GooglePlayGamesManifest.plugin:transformResourcesWithMergeJavaResForRelease
:GooglePlayGamesManifest.plugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GooglePlayGamesManifest.plugin:mergeReleaseJniLibFolders
:GooglePlayGamesManifest.plugin:transformNative_libsWithMergeJniLibsForRelease
:GooglePlayGamesManifest.plugin:transformNative_libsWithSyncJniLibsForRelease
:GooglePlayGamesManifest.plugin:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareComGoogleAndroidGmsPlayServicesAds1180Library
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1501Library
:prepareComGoogleAndroidGmsPlayServicesAdsLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesAdsLite1180Library
:prepareComGoogleAndroidGmsPlayServicesAdsLiteLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesAuth1180Library
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1180Library
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhoneLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesAuthBase1180Library
:prepareComGoogleAndroidGmsPlayServicesAuthBaseLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesBase1501Library
:prepareComGoogleAndroidGmsPlayServicesBasement1501Library
:prepareComGoogleAndroidGmsPlayServicesDrive1180Library
:prepareComGoogleAndroidGmsPlayServicesDriveLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesGames1180Library
:prepareComGoogleAndroidGmsPlayServicesGamesLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesGass1180Library
:prepareComGoogleAndroidGmsPlayServicesGassLicense1180Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementBase1600Library
:prepareComGoogleAndroidGmsPlayServicesNearby1501Library
:prepareComGoogleAndroidGmsPlayServicesStats1501Library
:prepareComGoogleAndroidGmsPlayServicesTasks1501Library
:prepareComGoogleFirebaseFirebaseAnalytics1601Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1611Library
:prepareComGoogleFirebaseFirebaseAnalyticsUnity500Library
:prepareComGoogleFirebaseFirebaseAppUnity500Library
:prepareComGoogleFirebaseFirebaseCommon1600Library
:prepareComGoogleFirebaseFirebaseCore1601Library
:prepareComGoogleFirebaseFirebaseIid1600Library
:prepareComGoogleFirebaseFirebaseIidInterop1600Library
:prepareComGoogleFirebaseFirebaseMeasurementConnector1700Library
:prepareComGoogleFirebaseFirebaseMeasurementConnectorImpl1601Library
:prepareComGoogleGamesGpgsPluginSupport0942Library
:prepareGpgsPluginSupport0942Library
:prepareGradleOutFirebaseUnspecifiedLibrary
:prepareGradleOutGoogleMobileAdsPluginUnspecifiedLibrary
:prepareGradleOutGooglePlayGamesManifestPluginUnspecifiedLibrary
:preparePlayServicesAds1180Library
:preparePlayServicesAdsLicense1180Library
:preparePlayServicesAdsLite1180Library
:preparePlayServicesAdsLiteLicense1180Library
:preparePlayServicesAuth1180Library
:preparePlayServicesAuthBase1180Library
:preparePlayServicesBase1180Library
:preparePlayServicesBasement1180Library
:preparePlayServicesBasementLicense1180Library
:preparePlayServicesDrive1180Library
:preparePlayServicesGames1180Library
:preparePlayServicesGass1180Library
:preparePlayServicesGassLicense1180Library
:preparePlayServicesNearby1180Library
:preparePlayServicesTasks1180Library
:prepareSupportCompat2520Library
:prepareSupportCoreUi2520Library
:prepareSupportCoreUtils2520Library
:prepareSupportFragment2520Library
:prepareSupportMediaCompat2520Library
:prepareSupportV42520Library
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:mergeReleaseShaders
:compileReleaseShaders
:generateReleaseAssets
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources FAILED

BUILD FAILED

Total time: 2 mins 11.436 secs
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)

**Comment by MarcoSchneider123** [comment]
[Android.zip](https://github.com/firebase/quickstart-unity/files/2125151/Android.zip)

**Comment by MarcoSchneider123** [comment]
I tried it, but still same error. Force Resolve was kinda useful, because it fixed some dependencies. In the comment before you i uploaded the Plugins/Android folder.

**Comment by stewartmiles** [comment]
@MarcoSchneider123 this sounds like a problem specific to your project.  I recommend opening up a support ticket on http://firebase.google.com/support where you can share your project and have staff help you debug the issue.
