### ISSUE TITLE
CurrentUser (Firebase Autentication) still cached after logging out?

### ISSUE THREAD

**Issue by jonavuka** [firebase/quickstart-unity#178]
Just a question, if a person logs in with google sign in and then logs out (by calling firebase logout) what happens to "CurrentUser" member in the Firebase.Auth.FirebaseAuth class? Does it reset to null?

**Comment by stewartmiles** [comment]
Yes, see
https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/TestApp/UIHandler.cs#L217
https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-auth#currentuser

**Comment by jonavuka** [comment]
I am confused here, so the workflow in my app is the following:
1) login using google sign in (google sign in pop up)
2) Obtain credentials login to firebase
3) Log out
4) Log in again, bot

**Comment by stewartmiles** [comment]
Have you been able to reproduce this behavior with our sample application?

As I mentioned,
https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/TestApp/UIHandler.cs#L217
should indicate the user has signed out with a null CurrentUser.

**Comment by jonavuka** [comment]
So wait do I also have to separately sign out in my google sign in plugin? Or firebase will do this for me when I call Firebase.Auth.FirebaseAuth.Signout function?

**Comment by stewartmiles** [comment]
Firebase just signs out the Firebase user, you'll also need to sign out of Google Sign-in separately.

**Comment by jonavuka** [comment]
And CurrentUser gets cached for how long? If I login and close the app it still remains correct? Or is it only per session

**Comment by jonavuka** [comment]
That's also independent of internet connection right? If they close the app after logging in and open it afterwards and they don't have any internet connection it will still have CurrentUser cached?

**Comment by stewartmiles** [comment]
@jonavuka yes if they log-in, disconnect, close the app, reopen the app CurrentUser will be present as the auth token is cached.
