### ISSUE TITLE
firebase invites example 

### ISSUE THREAD

**Issue by byleese** [firebase/quickstart-unity#189]
The example is perfect. Android APK was built.

I sent an invitation message from my test device.

And I received the SMS: [https: //.app.goo.gl/xxxx-xxxx-xxxxx](url)

Link received via SMS. That link was not working.

I guess that [https: //<app_code>.app.goo.gl/xxxx-xxxx-xxxxx](url) is right.

But  <app_code> place,subdomain is empty. How can I fix it?

Firebase Unity SDK 5.1.1
Unity3D 5.6.6f2

**Comment by a-maurice** [comment]
Hi there,

Unfortunately I haven't had any luck reproducing this problem locally.  Just to confirm that you have everything set up correctly:
In the Firebase console, did you configure it with the SHA-1 certificate you are using?
In the Firebase console, if you select "Dynamic Links" on the left banner, do you get a page that includes https://<app_code>.app.goo.gl at the top?
Do you have the google-services.json that you downloaded from your project in the Console under your Unity projects Assets folder (or a subfolder)?
Finally, if you send the invite to an email address, do you get the same behavior?

**Comment by byleese** [comment]
In the Firebase console, did you configure it with the SHA-1 certificate you are using?
**=> yes. I did.  added All(debug,release sha-1, sha-256)**

In the Firebase console, if you select "Dynamic Links" on the left banner, do you get a page that includes https://<app_code>.app.goo.gl at the top?
**=> no, https://<myapp>.page.link**


Do you have the google-services.json that you downloaded from your project in the Console under your Unity projects Assets folder (or a subfolder)?
**=>yes, i did in the example manual.**


Finally, if you send the invite to an email address, do you get the same behavior?
**=> yes. it's same.**


this is received mail html contents.

`<table border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="padding: 5px 0px;"><a href="https://.app.goo.gl/i/710533674080-95a53f97-c6d9-4c7b-afd3-bbf8c20eb331" target="_blank" rel="noreferrer noopener"><table class="blueButton" style='border-radius: 2px; text-align: center; color: rgb(68, 68, 68); line-height: 19px; clear: both; font-family: "Roboto", Arial, Helvetica, sans-serif; font-size: 14px; font-weight: 400; border-collapse: collapse; -ms-text-size-adjust: 100%; background-color: rgb(70, 136, 241); mso-table-lspace: 0pt; mso-table-rspace: 0pt; -webkit-text-size-adjust: 100%; -khtml-border-radius: 2px; -moz-border-radius: 2px; -ms-border-radius: 2px; -o-border-radius: 2px; -premailer-cellpadding: 0; -premailer-cellspacing: 0; -webkit-border-radius: 2px;' bgcolor="#4688f1" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td align="center" valign="middle" style="padding: 8px 27px; border-collapse: collapse; -ms-text-size-adjust: 100%; background-color: rgb(70, 136, 241); mso-table-lspace: 0pt; mso-table-rspace: 0pt; -webkit-text-size-adjust: 100%;" bgcolor="#4688f1"><span style="color: rgb(255, 255, 255); font-size: 12px; font-weight: 400; text-decoration: none; -ms-text-size-adjust: 100%; background-color: rgb(70, 136, 241); -webkit-text-size-adjust: 100%;"> Download it for FREE</span></td></tr></tbody></table></a></td></tr></tbody></table>`

**Comment by a-maurice** [comment]
Hmm, it sounds like something is incorrect with your Firebase project, as the "Dynamic Links" page should have a link.  Could you file a support ticket at https://firebase.google.com/support/contact/?category=troubleshooting, which can allow us to look more into what the problem might be?

**Comment by byleese** [comment]
Hi.

Today I upload my app at google play store for inner test release.

And I sent a invite and received the mail included a link.

The received url is `https://myappcode.page.link/i/710533674080-a9a3eb78-616f-4ec9-9dee-5b1df26d4ecc`


That webpage was 400 error.

this is my invite code.

`var invite = new Firebase.Invites.Invite()
                {
                    TitleText = "invite title",
                    MessageText = "invite message",
                    CallToActionText = "download",
                    DeepLinkUrl = new System.Uri("http://google.com/abc"),
                };
                FirebaseInvites.SendInviteAsync(invite).ContinueWith(HandleSentInvite);`

**Comment by a-maurice** [comment]
Did you file a support ticket?  It seems like something is wrong with your Firebase project, which we should be able to resolve if you go through https://firebase.google.com/support/contact/?category=troubleshooting.

**Comment by stewartmiles** [comment]
@byleese any update on this?

**Comment by stewartmiles** [comment]
@byleese I recommend you contact our support team to work through your issue.  It sounds like you're having problems following our setup process and also how to configure dynamic links which is specific to your application.
