### ISSUE TITLE
The caller does not have permission. 403

### ISSUE THREAD

**Issue by Mihail5412** [firebase/quickstart-unity#190]
Hello. I need your help to understand how I can access my Cloud Storage.I use Unity, and read the documentation (I confess, not all).I do not have problems with upload the file to storage. I save audio files there, for recognition with Google Cloud Speech Api, using the HTTP request https://speech.googleapis.com/v1/speech:longrunningrecognize?key= + MySpeechApiKey

I am trying to send this:"{"config":{"encoding":"LINEAR16","sampleRateHertz":44100,"languageCode":"ru-RU","maxAlternatives":1,"profanityFilter":false,"speechContexts":[{"phrases":[""]}],"enableWordTimeOffsets":false},"audio":{"uri":"gs://calm-vine-195513.appspot.com/2018.7.28_10_1_16_382.flac"}}"

And i get request:

{

"error": {

"code": 403,

"message": "The caller does not have permission",

"status": "PERMISSION_DENIED"

}

}

It is worth considering that in the Firebase I made a rule:

service firebase.storage {

match /b/{bucket}/o {

match /{allPaths=**} {

allow read, write;

}

}

}

I found a couple of tips that say that I need some kind of service account. And if I understood correctly that i need to connect autentification. Or I need in request URI to add some key?

**Comment by stewartmiles** [comment]
@Mihail5412 if you haven't figured out how to configure Firebase Rules yet I recommend contacting our support team via http://firebase.google.com/support
