### ISSUE TITLE
Code Sent is not triggered in Unity 2018 

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#193]
Hi all 

I am  doing Sending Sms Through Unity.  I am using Below Code..

          Firebase.Auth.FirebaseAuth auth;	
	void Awake()
	{
		
		auth=Firebase.Auth.FirebaseAuth.DefaultInstance;
	}

    public void PhoneNumberFunction()
{
PhoneAuthProvider provider = PhoneAuthProvider.GetInstance(firebaseAuth);
provider.VerifyPhoneNumber("+919092080955",1000, null,
  verificationCompleted: (credential) => {

  },
  verificationFailed: (error) => {
   Debug.Log("Error");
  },
  codeSent: (id, token) => {
   Debug.Log("Code Sent");
  },
  codeAutoRetrievalTimeout: (id) => {
    // Called when the auto-sms-retrieval has timed out, based on the given
    // timeout parameter.
    // `id` contains the verification id of the request that timed out.
  });
}
}

I have tested in Android Mobile. The Code sent is not triggered  or error is also not triggered. 

I have downloaded the latest google services.json. and i have enabled phoneauth + sha1 signature also enabled. I have also enabled phone number  for testing also.

But the Sms is also  Not Sent............

Whats wrong in my code........

**Comment by a-maurice** [comment]
Hi,

That code definitely seems like it should work, as it is essentially the same as the quickstart does.  The primary case that can happen where a code is not sent is that auto-verification occurred, where it automatically handles sending and receiving the code, and instead the verificationCompleted callback is used, where it returns a credential that can be used to authenticate the user, similar to if provider.GetCredential(id, code) was used.

Can you verify if either verificationCompleted or codeAutoRetrievalTimeout are being called?

**Comment by anthonype927** [comment]
What this ever solved? I am having the same issue.

**Comment by stewartmiles** [comment]
@anthonype927 if you're seeing an issue I recommend verifying it's reproducible with our quickstart application and if it is please file a bug report.  We closed this out as we were unable to reproduce the issue described and the developer was unresponsive.

**Comment by CLOUDFIRE91** [comment]
Hi Anthonype and stewartmiles..  For Note : Many peoples think that the above code  will send  sms to the Mobile No . It is wrong. We have to  add many things. Actually i  am posting  my working code. it is taken from  Unity Quick Start. I have edited the code. This will help ful to you..


﻿using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;





public class FirebaseSms : MonoBehaviour
{

    protected Firebase.Auth.FirebaseAuth auth;
    protected Firebase.Auth.FirebaseAuth otherAuth;
    protected Dictionary<string, Firebase.Auth.FirebaseUser> userByAuth =
    new Dictionary<string, Firebase.Auth.FirebaseUser>();

    protected bool signInAndFetchProfile = false;

    private uint phoneAuthTimeoutMs = 60 * 1000;

    private string phoneAuthVerificationId;

    public Button Button3;
    public InputField inp1,inp2;
    public GameObject inGameToggle;
    public GameObject SpriteReplaced;
    public Sprite Sprite1;
    public SpriteRenderer spriteR;
    public GameObject GoldOn, Goldoff;
    public GameObject AuthorizationCode;
    public GameObject EmailActivation,PhoneVerificationOff;
    public Image img1;
    public GameObject VerifiedSymbo1,VerifiedTick;
    Firebase.DependencyStatus dependencyStatus = Firebase.DependencyStatus.UnavailableOther;
    private TouchScreenKeyboard keyboard;
    public Toggle musicToggle;
    public Material GreyScaleOn;
    public bool mobilecodecansent = false;

    public virtual void Start()
    {

        keyboard = TouchScreenKeyboard.Open("", TouchScreenKeyboardType.NumbersAndPunctuation);
        Screen.orientation = ScreenOrientation.Portrait;
       // spriteR = SpriteReplaced.GetComponent<SpriteRenderer>();
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
            dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                InitializeFirebase();
            }
            else
            {
                Debug.LogError(
                "Could not resolve all Firebase dependencies: " + dependencyStatus);
            }
        });
    }


    public void SetMusic()
    {
        if (musicToggle.isOn)
        {
            GoldOn.GetComponent<Image>().material = null;
            mobilecodecansent = true;
            Debug.Log("I am ON");
        }
        else
        {
            GoldOn.GetComponent<Image>().material = GreyScaleOn;
            mobilecodecansent = false;
            Debug.Log("I am Off");
            // Set music Off
        }
    }




    protected void InitializeFirebase()
    {

        auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
        img1.fillAmount = 0;
    }

  




    protected bool LogTaskCompletion(Task task, string operation)
    {
        bool complete = false;
        if (task.IsCanceled)
        {
        //   Button3.GetComponentInChildren<Text>().text = "Cancelled";

        }
        else if (task.IsFaulted)
        {
        //    Button3.GetComponentInChildren<Text>().text = "Error";

            foreach (Exception exception in task.Exception.Flatten().InnerExceptions)
            {
                string authErrorCode = "";
                Firebase.FirebaseException firebaseEx = exception as Firebase.FirebaseException;
                if (firebaseEx != null)
                {
                //    Button3.GetComponentInChildren<Text>().text = "AuthError";
                    authErrorCode = String.Format("AuthError.{0}: ",
                    ((Firebase.Auth.AuthError)firebaseEx.ErrorCode).ToString());
                }

            }
        }
        else if (task.IsCompleted)
        {
            VerifiedTick.SetActive(true);
            //PhoneVerificationOff.SetActive(false);
            //EmailActivation.SetActive(true);
            img1.fillAmount = 0.5f;
          
             
             Button3.GetComponentInChildren<Text>().text = "Verified";
            Invoke("EmailActivation1", 4f);
            complete = true;
        }
        return complete;
    }

    public void EmailActivation1()
    {
        PhoneVerificationOff.SetActive(false);
        EmailActivation.SetActive(true);
        img1.fillAmount = 0.418f;


    }
   

    // Called when a sign-in without fetching profile data completes.
    void HandleSignInWithUser(Task<Firebase.Auth.FirebaseUser> task)
    {

        if (LogTaskCompletion(task, "Sign-in"))
        {

        }
    }

    // Called when a sign-in with profile data completes.
    void HandleSignInWithSignInResult(Task<Firebase.Auth.SignInResult> task)
    {

        if (LogTaskCompletion(task, "Sign-in"))
        {

        }
    }



    // Sign out the current user.
    protected void SignOut()
    {

        auth.SignOut();
    }

    public void VerifyPhoneNumber2()
    {
        if (mobilecodecansent == true)
        {

            string k2 = inp1.text.ToString();
            string k = "+91" + k2;
            Debug.Log("The Verify No is " + k);
            var phoneAuthProvider = Firebase.Auth.PhoneAuthProvider.GetInstance(auth);
            phoneAuthProvider.VerifyPhoneNumber(k, phoneAuthTimeoutMs, null,
            verificationCompleted: (cred) =>
            {
            //    Button3.GetComponentInChildren<Text>().text = "verificationcompleted";


            if (signInAndFetchProfile)
                {
                    auth.SignInAndRetrieveDataWithCredentialAsync(cred).ContinueWith(
            HandleSignInWithSignInResult);
                }
                else
                {
                    auth.SignInWithCredentialAsync(cred).ContinueWith(HandleSignInWithUser);
                }
            },
            verificationFailed: (error) =>
            {
            //  Button3.GetComponentInChildren<Text>().text = "error";

        },
            codeSent: (id, token) =>
            {
                phoneAuthVerificationId = id;
            //   Button3.GetComponentInChildren<Text>().text = "CodeSent";
            Invoke("Time", 3f);

            },
            codeAutoRetrievalTimeOut: (id) =>
            {
            // Button3.GetComponentInChildren<Text>().text = "Timeout";

        });
        
        }
      
    }

    public void Time()
    {
        GoldOn.SetActive(false);
        AuthorizationCode.SetActive(true);
        VerifiedSymbo1.SetActive(true);
        GoldOn.SetActive(false);
    
    }







    public void VerifyReceivedPhoneCode2()
    {
        var phoneAuthProvider = Firebase.Auth.PhoneAuthProvider.GetInstance(auth);
        // receivedCode should have been input by the user.

        string k = inp2.text.ToString();
        Debug.Log("The Code for verification is" + k);
        var cred = phoneAuthProvider.GetCredential(phoneAuthVerificationId, k);
        if (signInAndFetchProfile)
        {
            auth.SignInAndRetrieveDataWithCredentialAsync(cred).ContinueWith(
            HandleSignInWithSignInResult);
        }
        else
        {
            auth.SignInWithCredentialAsync(cred).ContinueWith(HandleSignInWithUser);
        }
    }




}

**Comment by CLOUDFIRE91** [comment]
Kindly note. i have posted my project code. So many  game objects are unwanted to you. so kindly remove it. or assign it. the code is perfectly working..
