### ISSUE TITLE
FCM doesn't support aspect ratio 2.1

### ISSUE THREAD

**Issue by PetrKarbula** [firebase/quickstart-unity#194]
In Unity 2018.2 there is settings for android devices with aspect ratio higher than 1.8. Which basically puts `<meta-data android:name="android.max_aspect" android:value="2.1" />` in AndroidManifest.
It forces the app to be in fullscreen on Samsung Galaxy S8 and LG G6 devices. 
Firebase messaging with its own main activity doesn't conform to that setting and the app is cropped.

**Comment by stewartmiles** [comment]
We provide an `AndroidManifest.xml` as part of the Firebase messaging plugin that you're free to customize, (see below):

````
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="${applicationId}"
          android:versionCode="1"
          android:versionName="1.0">
  <application android:label="@string/app_name"
               android:icon="@drawable/app_icon">
    <!-- The MessagingUnityPlayerActivity is a class that extends
         UnityPlayerActivity to work around a known issue when receiving
         notification data payloads in the background. -->
    <activity android:name="com.google.firebase.MessagingUnityPlayerActivity"
              android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    <service android:name="com.google.firebase.messaging.MessageForwardingService"
             android:exported="false"/>
  </application>
</manifest>
```

Are you suggesting that we add `<meta-data android:name="android.max_aspect" android:value="2.1" />` as a default value in our activity for all applications?

**Comment by stewartmiles** [comment]
@PetrKarbula we override the Unity activity by shipping an AndroidManifest with the plugin that references our activity.  The setting is in the manifest XML not the activity code AFAIK.

**Comment by stewartmiles** [comment]
For more information see https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity

**Comment by PetrKarbula** [comment]
@stewartmiles sorry i might have explained myself badly. What i meant is when using FCM plugin it doesn't matter if i use your AndroidManifest or custom one (both having added meta-data with aspect ratio). The app won't be fullscreen. There must be something wrong inside activity code.

**Comment by stewartmiles** [comment]
@PetrKarbula the activity doesn't do anything associated with the aspect ratio, it simply routes messages to the SDK.  I've attached the code, it should be very uncontroversial.

[MessagingUnityPlayerActivity.java.zip](https://github.com/firebase/quickstart-unity/files/2307389/MessagingUnityPlayerActivity.java.zip)

Have you asked Unity support about this issue?
i.e some folks appear to be having problems with this https://answers.unity.com/questions/1307153/using-the-androidmax-aspect-in-the-android-manifes.html
