### ISSUE TITLE
Gradle Build Error in Firebase Auth 

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#196]
Hi All 

I am using Firebase Auth.I am working in unity 2018.I have dowloaded  Quickstart-unity-Master.In that i am working Auth Section. I have download the latest googlservices.json file also. But when i try to build the Firebase auth in android. It shows the error 

Gradle build Error. 

I have searched in Forum it Says  Java greater 8 is not supported. I am using  jdk1.8.0_171.

I  have donwloaded varrious unity packages 2017 Versions. 

I Installed 10 Different versions. In that one versions First time it builds and apk produced. But second time i build it shows the error. Gradle Build failed. 

HOw can i solve the gradle Error. 

Thanks and Regads
![gradleerror1](https://user-images.githubusercontent.com/39626423/44028828-cc8f8004-9f18-11e8-9281-85c621f1fbb4.png)

**Comment by stewartmiles** [comment]
Can you build any Android application (i.e not Firebase) successfully?

**Comment by CLOUDFIRE91** [comment]
Hi Stewartmiles. I have succesffuly compiled other projects and the apk is produced. i have tested with 2-3 systems. When i add firebase it shows error...When i change the build option gradle to internal. It also shows error...

What i have to do for clean build???

**Comment by stewartmiles** [comment]
@CLOUDFIRE91 could you share your Unity log https://docs.unity3d.com/Manual/LogFiles.html from a failure Firebase sample build?
