### ISSUE TITLE
System.AggregateException is thrown when sending invite

### ISSUE THREAD

**Issue by exzizt** [firebase/quickstart-unity#199]
Sounds like this was an issue (#5) in 2016 as well.

I just installed the Invites package and set everything up as per the guide. I am getting this exception, and my application is signed. I've tried Build & Run in Unity, and also build, upload app and test as an Alpha release.

> 08-19 16:16:02.309 15572 15572 E Unity :
> 08-19 16:16:02.309 15572 15572 E Unity : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 16:16:02.309 15572 15572 E Unity :
> 08-19 16:16:02.322 15572 15599 I Unity : Invitation encountered an error:
> 08-19 16:16:02.322 15572 15599 I Unity :
> 08-19 16:16:02.322 15572 15599 I Unity : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 16:16:02.322 15572 15599 I Unity :
> 08-19 16:16:02.322 15572 15599 I Unity : System.AggregateException: Exception of type 'System.AggregateException' was thrown.
> 08-19 16:16:02.322 15572 15599 I Unity : -----------------
> 08-19 16:16:02.322 15572 15599 I Unity : Firebase.FirebaseException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
> 08-19 16:16:02.322 15572 15599 I Unity :
> 08-19 16:16:02.322 15572 15599 I Unity :
> 08-19 16:16:02.322 15572 15599 I Unity : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
> 08-19 16:16:02.322 15572 15599 I Unity :

**Comment by exzizt** [comment]
I figured it out. I had "AndroidMinimumVersionCode = 19" in the Invite initializer. This caused the above error. 😕

**Comment by jonsimantov** [comment]
Hi,

Thanks for the bug report! We've identified the error and have a fix for it, which should be included in the next release. (I'll reply here when that happens.)

Jon

**Comment by MurtazaSadikot** [comment]
@jonsimantov, any update on when are you releasing the version with the fix ?

**Comment by stewartmiles** [comment]
This is fixed in the 5.3.1 SDK https://firebase.google.com/support/release-notes/unity#5.3.1
