### ISSUE TITLE
Firebase Messaging sdk deletes my icon on Unity 5.5.0f3 Android

### ISSUE THREAD

**Issue by ceceomer** [firebase/quickstart-unity#20]
I integrated the firebase messaging sdk to my game for android project. After that I made a build but there is no app icon. There was a bug and it deleted my icon after build.

**Comment by stewartmiles** [comment]
Yep, we're aware of the issue and have staged a fix for the next release.

For the moment you can modify the Android Manifest
(Plugins/Android/AndroidManifest.xml) we provide by replacing it with the
attached one.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart

**Comment by BuKuSiShen** [comment]
@stewartmiles yeah.Thank you for having solved the two issues.Now I have found the other issue that I can't receive the fcm push notification when EXIT the game,only receive fcm push notification when the unity app is active.

**Comment by stewartmiles** [comment]
See https://github.com/firebase/quickstart-unity/issues/25
