### ISSUE TITLE
FirebaseStorage (and database) work in editor but not in device

### ISSUE THREAD

**Issue by Athomield** [firebase/quickstart-unity#202]
Signing in in android 4.4.2 works but whenever I try to upload a file it does not work at all ! In the editor I was able to upload a file but on android the taks does not seem to get achieved, not even to the point where it gives a failure (aka -- if (task.IsFaulted || task.IsCanceled) ). It simply stops at PutBytesAsync/PutFilesAsync... I change scenes after I log in, would that cause me to log out ?
Note that in editor I had to change to experimental .Net 4.6 where in android the .Net 4.6 crashes the app so I had to go back to .Net 3.0

**Comment by jonsimantov** [comment]
What version of Unity are you using? It shouldn't crash in .NET 4.6. Have you tried the most recent version of the Firebase Unity SDK, [5.2.1](https://firebase.google.com/support/release-notes/unity#5.2.1)?

A few suggestions: Can you make sure that you have set up your [development key SHA-1 or SHA-256](https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application) for your project in Firebase Console? You'll need to redownload google-services.json after that.

If that doesn't work, could you try keeping a reference to Firebase.FirebaseApp.DefaultInstance before changing scenes? It's possible that the reference might be getting destroyed during the scene transition. (If this is happening it would be a bug, but holding onto the reference would be a workaround for now.)

**Comment by stewartmiles** [comment]
We haven't heard from you in a *long* time.  I recommend reproducing your failure with our sample applications and getting back to us.
