### ISSUE TITLE
How do I prevent users from logging on on multiple devices at the same time?

### ISSUE THREAD

**Issue by exzizt** [firebase/quickstart-unity#206]
I've looked around for a bit and can't find out how to do this in Unity using Firebase. Is there any proper way to manage sessions/ensure that a user can only be "logged in" and "playing the game" on one device at a time? E.g., if they are signed in on their phone playing the game, they shouldn't be allowed to grab their tablet and log into the game on that same account.

**Comment by Thaina** [comment]
If you could find deviceID by any means. You could do that system by yourself using the realtime database

Simply put. You would have your client set a database with there userID paired with deviceID. After that, any interaction with your system must also checking with the only one deviceID of that user, else reject it

**Comment by exzizt** [comment]
@Thaina Thanks for the post. Unfortunately, this wouldn't quite do the trick. Because what if the user doesn't log out on their one device but doesn't have the app open, or, for example, the app crashes while they're playing and they couldn't log out of the app. They would be forced to open up the app on their old device, manually log out, and only then they would be able to play on their new device. What you suggest could be done with setting a simple "isOnline" flag in the database when they boot up the app, but in the case, they don't manually log out of the app and I send an "isOnline = false" they would NOT be able to log in on their other device. I'm sure you see the issue.

**Comment by Thaina** [comment]
@exzizt There are 2 ways, one is, instead of trying to protect logged in from multiple device, you just logged out every device when any device logged in. That would be easier

Second is having timestamp and let it able to changed after some timeframe, 1 minute for example, and having your device periodically change timestamp

**Comment by exzizt** [comment]
@Thaina Unfortunately these two approaches also won't work.
1. Nearly all apps I can think of don't use this approach because it is unfair to boot a device from playing just because another device wants to sign in. This can cause a "booting battle" if people share the same account. Again, the proper and desired approach is to **deny** the user from logging in if they are already playing the game on a different device--**not** booting the player off who is playing minding their own business just so the person who wants to sign in can play.
2. The only annoying issue with this approach is even if one device turns off, the second device will not be able to log in until say the minute has passed, even though the other user stopped playing.

**Comment by Thaina** [comment]
@exzizt 1st approach, you wrong. I have seen so many online game do that. Any double logged in will result in both failure from trying to cheat. And if you got this double logged in you should contact provider

2nd approach, I know and that why I write the 3rd solution. It more complicate than 2 though so it's up to you

**Comment by exzizt** [comment]
@Thaina What do you mean contact provider? Sure I guess some do implement this--however it shouldn't be thought of as "cheating" automatically. It could be a harmless mistake and have no "cheating" impact on the game, e.g., one sibling is playing the game on their iPhone while their younger brother tries to sign in and play on the same account on his iPad. It's just a harmless mistake, and the person currently playing should take priority (i.e., they are not booted).

What's your third solution?

If there's no API for figuring this out via Google Play Services/Firebase I guess the best "roll-your-own" approach would be to do something with timestamp checking.
