### ISSUE TITLE
Firebase-demo/Analytics NoClassDefFoundError exception when built with Gradle

### ISSUE THREAD

**Issue by donuthole20** [firebase/quickstart-unity#208]
I am having a NoClassDefFoundError exception when I added Firebase analytics on my game that is built with gradle so I tried it on this demo project of firebase and got the same error but with different class. All I did was just change the build settings to gradle, I didnt change any gradle configuration with the demo project.

My version of unity is 5.6.3f1. I am using firebase_unity_sdk_5.2.1 plugin.

This is the error from the Analytics Quickstart demo:

09-02 16:21:42.621  2968  2968 E AndroidRuntime: FATAL EXCEPTION: main<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime: Process: com.DefaultCompany.DefaultProject, PID: 2968<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/measurement/AppMeasurement;<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(Unknown Source:23)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.analytics.connector.internal.zzb.create(Unknown Source:8)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.components.zzh.zza(com.google.firebase:firebase-common@@16.0.1:29)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.components.zzi.get(Unknown Source:4)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.components.zzh.get(com.google.firebase:firebase-common@@16.0.1:40)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.components.ComponentContainer$$CC.get(com.google.firebase:firebase-common@@16.0.1:15)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.components.zzd.get(Unknown Source:0)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.components.zzd.zza(com.google.firebase:firebase-common@@16.0.1:68)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.FirebaseApp.zze(com.google.firebase:firebase-common@@16.0.1:716)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.1:329)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.1:295)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.1:282)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.1:37)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1925)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1900)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.1:31)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurement" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.DefaultProject-KmqojsTcbAmAFIe0mAe1NA==/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.DefaultProject-KmqojsTcbAmAFIe0mAe1NA==/lib/arm, /data/app/com.DefaultCompany.DefaultProject-KmqojsTcbAmAFIe0mAe1NA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)<br>
09-02 16:21:42.621  2968  2968 E AndroidRuntime:        ... 27 more<br>

This is from my game:

09-02 15:12:24.259 29752 29752 E AndroidRuntime: FATAL EXCEPTION: main<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime: Process: com.DefaultCompany.DefaultProject, PID: 29752<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/Preconditions;<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.1:1050)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6578)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6133)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6043)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.Preconditions" on path: DexPathList[[zip file "/data/app/com.DefaultCompany.DefaultProject-5mnEepmltZFu956Rz8DGDQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.DefaultCompany.DefaultProject-5mnEepmltZFu956Rz8DGDQ==/lib/arm, /data/app/com.DefaultCompany.DefaultProject-5mnEepmltZFu956Rz8DGDQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)<br>
09-02 15:12:24.259 29752 29752 E AndroidRuntime:        ... 12 more<br>

Thank you for the help!

**Comment by stewartmiles** [comment]
@donuthole20 any chance you've disabled auto-resolution in the Android Resolver?  You need to resolve the Android dependencies when changing the build type.  See https://github.com/googlesamples/unity-jar-resolver#android-resolver-usage for more info

**Comment by stewartmiles** [comment]
I'll assume you've solved your problem by enabling the Android Resolver.
