### ISSUE TITLE
iOS - Xcode: linker command failed with exit code 1

### ISSUE THREAD

**Issue by demanzonderjas** [firebase/quickstart-unity#209]
Operating system: macOS 
Operating system version: High Sierra 10.13.6
Unity version: 2018.1.4f1
Xcode: 10.0 beta 2

What steps will reproduce the problem:
1. Follow the exact steps from the quickstart-unity guide for the realtime database
2. Build in Xcode

What is the expected result?
Working build on iOS device (v12)

What happens instead of that?
Error: linker command failed with exit code 1

Full Error Report via Xcode > View > Navigators > Show Report Navigator:

Ld /Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/unityfirebase.app/unityfirebase normal arm64 (in target: Unity-iPhone)
    cd /Users/daan/unity/projects/quickstart-unity/database/testapp/v1
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode-beta-10.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode-beta-10.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/FirebaseAuth -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/FirebaseCore -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/FirebaseDatabase -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/GTMSessionFetcher -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/GoogleUtilities -L/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/leveldb-library -L/Users/daan/unity/projects/quickstart-unity/database/testapp/v1 -L/Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Libraries -L/Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Libraries/Plugins/iOS/Firebase -F/Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos -F/Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Pods/FirebaseAnalytics/Frameworks -F/Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Pods/FirebaseInstanceID/Frameworks -F/Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Pods/GoogleAppMeasurement/Frameworks -filelist /Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/unityfirebase.LinkFileList -Xlinker -map -Xlinker /Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/unityfirebase-LinkMap-normal-arm64.txt -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/unityfirebase_lto.o -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -ObjC -lFirebaseAuth -lFirebaseCore -lFirebaseDatabase -lGTMSessionFetcher -lGoogleUtilities -lc++ -licucore -lleveldb-library -lsqlite3 -lz -framework CFNetwork -framework FirebaseAnalytics -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework Foundation -framework GoogleAppMeasurement -framework MeasurementNanoPB -framework Security -framework StoreKit -framework SystemConfiguration -weak_framework CoreMotion -weak-lSystem -framework Security -framework MediaToolbox -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -lFirebaseCppAuth -lFirebaseCppDatabase -lFirebaseCppApp -weak_framework Metal -lPods-Unity-iPhone -Xlinker -dependency_info -Xlinker /Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/unityfirebase_dependency_info.dat -o /Users/daan/Library/Developer/Xcode/DerivedData/Unity-iPhone-fgiewqurghtweggpkvkkypekdzgm/Build/Products/ReleaseForRunning-iphoneos/unityfirebase.app/unityfirebase

ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/daan/unity/projects/quickstart-unity/database/testapp/v1/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_pb_ostream_from_buffer", referenced from:
      _nano_two_pass_encoding in MeasurementNanoPB(encoder_common_94707f6dbc3bb39365a230b2b30fe541.o)
  "_pb_encode", referenced from:
      _nano_two_pass_encoding in MeasurementNanoPB(encoder_common_94707f6dbc3bb39365a230b2b30fe541.o)
  "_pb_encode_varint", referenced from:
      _nano_encode_repeated_uint64 in MeasurementNanoPB(encoder_common_94707f6dbc3bb39365a230b2b30fe541.o)
  "_pb_decode_varint", referenced from:
      _nano_decode_repeated_uint64 in MeasurementNanoPB(decoder_common_0e5e3ec9db731058136e2bff5713eb23.o)
  "_pb_encode_tag_for_field", referenced from:
      _apmpb_encode_repeated_audience in GoogleAppMeasurement(apmpb_audience_encoder_26e8a7365a5778d20daeb516ba95f758.o)
      _apmpb_encode_repeated_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_encoder_6bac2ac59634a1ebb6290327c6f77d04.o)
      _apmpb_encode_repeated_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_encoder_0dd554d842117c42faad353b5fb71162.o)
      _apmpb_encode_repeated_event in GoogleAppMeasurement(apmpb_event_encoder_42cbc4e928402a9af9ef4a4b0e61823a.o)
      _apmpb_encode_repeated_event_config in GoogleAppMeasurement(apmpb_event_config_encoder_8690e9cfd2589e6bcbeb0050efb58ca2.o)
      _apmpb_encode_repeated_event_filter in GoogleAppMeasurement(apmpb_event_filter_encoder_9eec9efca534df4c63be0a3cea16864d.o)
      _apmpb_encode_repeated_event_param in GoogleAppMeasurement(apmpb_event_param_encoder_66e940c2dab360ee4ca91f2db28161bc.o)
      ...
  "_pb_read", referenced from:
      _apmpb_decode_repeated_audience in GoogleAppMeasurement(apmpb_audience_decoder_b61bcebd321814b3677c8fdd479847c4.o)
      _apmpb_decode_repeated_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_decoder_79cb1fe9ff2e4ed180b98672e29b9367.o)
      _apmpb_decode_repeated_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_decoder_dddf3418128728210f52916335b1f5d5.o)
      _apmpb_decode_repeated_event in GoogleAppMeasurement(apmpb_event_decoder_6147601448907ef11a87c8ed08a088a1.o)
      _apmpb_decode_repeated_event_config in GoogleAppMeasurement(apmpb_event_config_decoder_16190a1acf5bacf22694ada704856f5a.o)
      _apmpb_decode_repeated_event_filter in GoogleAppMeasurement(apmpb_event_filter_decoder_a612946f40c7e482807f2d74923e219d.o)
      _apmpb_decode_repeated_event_param in GoogleAppMeasurement(apmpb_event_param_decoder_fc15a947c63cb2ee134daf3f878502a8.o)
      ...
  "_pb_istream_from_buffer", referenced from:
      _apmpb_decode_audience in GoogleAppMeasurement(apmpb_audience_decoder_b61bcebd321814b3677c8fdd479847c4.o)
      _apmpb_decode_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_decoder_79cb1fe9ff2e4ed180b98672e29b9367.o)
      _apmpb_decode_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_decoder_dddf3418128728210f52916335b1f5d5.o)
      _apmpb_decode_event in GoogleAppMeasurement(apmpb_event_decoder_6147601448907ef11a87c8ed08a088a1.o)
      _apmpb_decode_event_config in GoogleAppMeasurement(apmpb_event_config_decoder_16190a1acf5bacf22694ada704856f5a.o)
      _apmpb_decode_event_filter in GoogleAppMeasurement(apmpb_event_filter_decoder_a612946f40c7e482807f2d74923e219d.o)
      _apmpb_decode_event_param in GoogleAppMeasurement(apmpb_event_param_decoder_fc15a947c63cb2ee134daf3f878502a8.o)
      ...
  "_pb_encode_string", referenced from:
      _nano_encode_string in MeasurementNanoPB(encoder_common_94707f6dbc3bb39365a230b2b30fe541.o)
  "_pb_encode_submessage", referenced from:
      _apmpb_encode_repeated_audience in GoogleAppMeasurement(apmpb_audience_encoder_26e8a7365a5778d20daeb516ba95f758.o)
      _apmpb_encode_repeated_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_encoder_6bac2ac59634a1ebb6290327c6f77d04.o)
      _apmpb_encode_repeated_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_encoder_0dd554d842117c42faad353b5fb71162.o)
      _apmpb_encode_repeated_event in GoogleAppMeasurement(apmpb_event_encoder_42cbc4e928402a9af9ef4a4b0e61823a.o)
      _apmpb_encode_repeated_event_config in GoogleAppMeasurement(apmpb_event_config_encoder_8690e9cfd2589e6bcbeb0050efb58ca2.o)
      _apmpb_encode_repeated_event_filter in GoogleAppMeasurement(apmpb_event_filter_encoder_9eec9efca534df4c63be0a3cea16864d.o)
      _apmpb_encode_repeated_event_param in GoogleAppMeasurement(apmpb_event_param_encoder_66e940c2dab360ee4ca91f2db28161bc.o)
      ...
  "_pb_decode", referenced from:
      _apmpb_decode_audience in GoogleAppMeasurement(apmpb_audience_decoder_b61bcebd321814b3677c8fdd479847c4.o)
      _apmpb_decode_audience_leaf_filter_result in GoogleAppMeasurement(apmpb_audience_leaf_filter_result_decoder_79cb1fe9ff2e4ed180b98672e29b9367.o)
      _apmpb_decode_dynamic_filter_result_timestamp in GoogleAppMeasurement(apmpb_dynamic_filter_result_timestamp_decoder_dddf3418128728210f52916335b1f5d5.o)
      _apmpb_decode_event in GoogleAppMeasurement(apmpb_event_decoder_6147601448907ef11a87c8ed08a088a1.o)
      _apmpb_decode_event_config in GoogleAppMeasurement(apmpb_event_config_decoder_16190a1acf5bacf22694ada704856f5a.o)
      _apmpb_decode_event_filter in GoogleAppMeasurement(apmpb_event_filter_decoder_a612946f40c7e482807f2d74923e219d.o)
      _apmpb_decode_event_param in GoogleAppMeasurement(apmpb_event_param_decoder_fc15a947c63cb2ee134daf3f878502a8.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas on how to fix this?

**Comment by augie09** [comment]
this won't help solve your issue, but we are also seeing issues in past few days related to GoogleUtilities Pod, specifically Bitcode errors pointing to a binary compiled in Xcode 9.4.  Only change to our project was running pod update. 

exact error during Archive process: 
 ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '902.0.39.2_0' Reader: '900.0.39.2_0')', using libLTO version 'LLVM version 9.0.0, (clang-900.0.39.2)' for architecture arm64

**Comment by stewartmiles** [comment]
We fixed the issue with the GoogleUtilities pod in the 5.3.1 release, please give that a try.
https://firebase.google.com/support/release-notes/unity#5.3.1
