### ISSUE TITLE
Can't get sms when use phone number Auth ?

### ISSUE THREAD

**Issue by uokivan** [firebase/quickstart-unity#217]
I use the quickstart's sample c# code into a new unity project， I have the following problems:

1.it can't use the Phone No. Auth to register a new phone number(sign up)?

2. When I use the phone number which create on firebase console， I can get the log: "phone auth code sent" , but I can't get any real sms from my phone?

**Comment by stewartmiles** [comment]
@uokivan I recommend opening up a support request on http://firebase.google.com/support .  Folks will be able to work through the issue with you there with access to your Firebase project.
