### ISSUE TITLE
 SWIGRegisterExceptionCallbacks_DatabaseInternal

### ISSUE THREAD

**Issue by HarrieDaPothead** [firebase/quickstart-unity#219]
Hello I have been having trouble lately with the Firebase database.

So I recently(23 hours ago) installed Firebase Auth to Unity, and it works as well as the others(Storage, Analytics, etc) except Database.

At first I kept getting the error 
**"[Error] WebSocket: ws_0 - WebSocketException during handshake
 [Error] WebSocket: ws_0 - could not connect"**
But I fixed it with the answer from this [post](https://stackoverflow.com/questions/50651865/unityfirebase-databaseerror-websocket-ws-0-could-not-connect)

However I reverted the player settings back to(I changed it back since the Firebase.database.dll used .NET 3.5 (and not .NET 4x) so I thought it was the most logical option to revert it).
**scripting Runtime .NET 3.5
scripting backend Mono
API Level .NET 2.0**
(Note : I still got the same error below before it was reverted from
**scripting Runtime 4.x
scripting backend IL2CPP
API Level 4.x**)

Which now leaves me to this error
**"EntryPointNotFoundException: SWIGRegisterExceptionCallbacks_DatabaseInternal"**
which is caused when trying to get the reference to the firebase database.
My database rules are set to
`{
  "rules": {
    ".read": true,
    ".write": true
  }
}`
so I do have access to read and write.

(Note : when I run "Debug.Log(FirebaseApp.DefaultInstance.Options.DatabaseUrl);" in the Test.cs
it returns my firebase url, meaning I'm not getting a null databaseUrl)

(I'm using Firebase SDK 5.3.0, Unity 2018.2.10f1, and the quickstart-unity)
here is my project files to replicate the problem : https://www.dropbox.com/s/nc4tyi37puutzz2/Project%20Files.rar?dl=0
(In the MainScene.scene, the UIHandler gameobject has the Test.cs attached to it(for debug purposes), simply remove it and add the UIHandler.cs on to it instead(you'll obviously still get the same error) if you want to see how the quickstart example preformed. )

Full error log of  SWIGRegisterExceptionCallbacks_DatabaseInternal
`EntryPointNotFoundException: SWIGRegisterExceptionCallbacks_DatabaseInternal
Firebase.Database.Internal.DatabaseInternalPINVOKE+SWIGExceptionHelper..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for SWIGExceptionHelper
Firebase.Database.Internal.DatabaseInternalPINVOKE..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Firebase.Database.Internal.DatabaseInternalPINVOKE
Firebase.Database.Internal.InternalFirebaseDatabase.GetInstance (Firebase.FirebaseApp app, System.String url)
Firebase.Database.FirebaseDatabase.GetInstance (Firebase.FirebaseApp app, System.String url)
Firebase.Database.FirebaseDatabase.GetInstance (Firebase.FirebaseApp app)
Firebase.Database.FirebaseDatabase.get_DefaultInstance ()
Test.Start () (at Assets/Test.cs:14)`

_________________________________________________________________________________________________
here is another [thread ](https://stackoverflow.com/questions/52559803/unable-to-write-data-to-firebase-database-via-unity?noredirect=1#comment92062341_52559803)I posted on stackoverflow, explaining the same thing.

**Comment by HarrieDaPothead** [comment]
So just figured out, if I don't do the fix on this error
"[Error] WebSocket: ws_0 - WebSocketException during handshake
[Error] WebSocket: ws_0 - could not connect"
obviously I still get the error however when I build it(android) and run it on an android device I'm able to write and read data on my firebase database. So it only seems to be something wrong with the editor.

**Comment by HarrieDaPothead** [comment]
Okay, so I built the .apk then I ran it on the Android Studio Emulator, and it works.
So it is not a router problem which PathToLife **"I can confirm that this issue is tied into network problems related with routers.."** on thread #106.

**Comment by HarrieDaPothead** [comment]
@Whenami It's something to do with the handshake connection from Unity to Firebase.

Since I do not have another Internet connection in my area nor do I have an Android Device, so my only work around is to build the apk's and run them on the Android Studio Emulator until the issue is fixed.

**Comment by Whenami** [comment]
You run ASE to see what was going on these codes and to debug.Because you dont have android device then you created a virtual one on ASE and this was best solution for you. i got it ,as far as i know ,ASE doesnt fix any error ,so how did u fix it this error then?What was your solution ?did you change any code or did u realize what causes this problem?i would like to know the magic touch there.i ve been searching this issue for 3 days and still got this error and this makes me mad.

**Comment by chkuang-g** [comment]
@HarrieDaPothead I assumes you run on Windows.

So first of all, the WebSocketException is caused by the old C# implementation, which seems pretty picky to the network environment.  We've changed to utilize native Android/iOS implementation but not for desktop yet.

And unfortunately the solution described in https://github.com/firebase/quickstart-unity/issues/106#issuecomment-421110341 does not work for you because we excluded the C++ Windows library, which causes the Editor to freeze.  Note that this solution is NOT intended anyway.

Therefore, your best bet right now is to try to develop under different network environment, or try to change your router/wifi setting.  I'll see what we can provide in short term.

Shawn

**Comment by Whenami** [comment]
Firstly , thanks for your answers

the right thing to do now is changing wifi settings but i dont know what settings i have to change.In Zxhn modems(neighbors modem),it seems this issue doesnt come out.I am using Huawei and if anybody knew what i need to change in modem , i'd be grateful to hear.

**Comment by HarrieDaPothead** [comment]
@Whenami I used Log viewer on the [Asset Store](https://assetstore.unity.com/packages/tools/log-viewer-12047) to Fix and to monitor my errors(inApp) and debug.log(s) on an Android build.

**Comment by Whenami** [comment]
Thanks Harrie , i'll try

**Comment by HarrieDaPothead** [comment]
Thanks for your reply @chkuang-g.

**Comment by stewartmiles** [comment]
Ok I'll assume that things are as good as they're going to get until we've finished migration of the Realtime Database to our C++ implementation on desktop.  https://github.com/firebase/quickstart-unity/issues/106 is tracking desktop Realtime Database networking issues.

**Comment by kantagara** [comment]
Hello, what's the situation with this? I'm still getting this error :(

**Comment by alexames** [comment]
@kantagara: We're aware of the issue but don't have a fix for it yet. Have you looked at #106? You may be able to configure your wifi settings to work around the issue.

**Comment by kantagara** [comment]
@alexames yes but I can't use wifi, and also I'd like to support the desktop platform as well, so I decided to write a small backend for that purpose, instead of using firebase.
