### ISSUE TITLE
Unity app with Facebook integration failed to build on iOS

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#22]
We didn't recall this issue on Unity 5.4.x, but recently we updated to Unity 5.5 and our app failed to build. After isolating the issue, we figured that our app starts to fail to build on iOS after adding Firebase to the project. It failed to find the framework that facebook included. We we guessing that Firebase replaces framework path instead of appending framework path to the iOS project. We are actually not sure whether this is a Unity bug or Firebase bug.

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

This *may* resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart

**Comment by comtaler** [comment]
Yes, the update fixes the problem. Thanks
