### ISSUE TITLE
Firebase 5.3.0 error : method_ids[i] || method.optional

### ISSUE THREAD

**Issue by ramioooz** [firebase/quickstart-unity#222]
I just updated to firebase 5.3.0

my project has these packages :
firebase analytics
firebase dynamic links
firebase messaging
firebase remote config

I am getting there errors in log: 
10-04 20:09:14.045 21130 21388 I Unity   : Firebase Analytics API Initializing
10-04 20:09:14.046 21130 21388 E Unity   : method_ids[i] || method.optional
10-04 20:09:14.046 21130 21388 E Unity   :
10-04 20:09:14.046 21130 21388 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-04 20:09:14.046 21130 21388 E Unity   :
10-04 20:09:14.066 21130 21388 I Unity   : Dynamic Links API Initialized
10-04 20:09:14.067 21130 21388 E Unity   : method_ids[i] || method.optional
10-04 20:09:14.067 21130 21388 E Unity   :
10-04 20:09:14.067 21130 21388 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-04 20:09:14.067 21130 21388 E Unity   :
10-04 20:09:14.067 21130 21388 E Unity   : Failed to initialize messaging
10-04 20:09:14.067 21130 21388 E Unity   :
10-04 20:09:14.067 21130 21388 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-04 20:09:14.067 21130 21388 E Unity   :
10-04 20:09:14.069 21130 21388 I Unity   : Remote Config API Initialized
10-04 20:09:14.069 21130 21388 W Unity   : analytics API already shut down
10-04 20:09:14.069 21130 21388 W Unity   :
10-04 20:09:14.069 21130 21388 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-04 20:09:14.069 21130 21388 W Unity   :
10-04 20:09:14.069 21130 21388 E Unity   : Messaging already shut down.
10-04 20:09:14.069 21130 21388 E Unity   :
10-04 20:09:14.069 21130 21388 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-04 20:09:14.069 21130 21388 E Unity   : 

any solution...
Thank you

**Comment by alexames** [comment]
Can you show me the code you are using to initialize the libraries?

**Comment by stewartmiles** [comment]
@ramioooz since we haven't heard from you I'll assume you've resolved your issue.
