### ISSUE TITLE
Unity Firebase Database - Find the branch without knowing the parent child branch

### ISSUE THREAD

**Issue by Whenami** [firebase/quickstart-unity#225]
Guys i make a Json tree 

At the top i have AllClasses root and it seperates into some classes(like 1-A) and also these classes seperate into some numbers(0-1-2-3) and lastly,these numbers seperated into names,surnames and numbers of students and i can easily catch any student info in this way:

FirebaseDatabase.DefaultInstance.GetReference("AllClasses").Child("1-A").Child("3").GetValueAsync().ContinueWith(task => etc....

what i am tryin to do is to find the parent child branches.For ex. I know Joe Marshall No:53 and i need to find which class this student is in and what is the order of this student in Firebase.Is there any method to find out ?

**Comment by Whenami** [comment]
ok guys i found the solution.
SnapShot.Reference.Parent.Parent.Key works.
You can close the issue

**Comment by stewartmiles** [comment]
From @Whenami 

"
ok guys i found the solution.
SnapShot.Reference.Parent.Parent.Key works.
You can close the issue
"
