### ISSUE TITLE
Dynamic Links breaks iOS Unity Cloud Build

### ISSUE THREAD

**Issue by eladleb** [firebase/quickstart-unity#228]
After upgrading firebase from Firebase Unity SDK version 5.2.1 to any of the above versions, the iOS project will fail during archive with the error:
`
/Pods/FirebaseDynamicLinks/Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m:19:9: 'DynamicLinks/FDLURLComponents/FDLURLComponents+Private.h' file not found`

Android is built successfully with the above versions.

The project builds fine when locally after a pod update / install but will never build in Unity's cloud build. When going back to SDK version 5.2.1 it will build successfully again.

Is there a missing dependency when Unity Cloud Build runs? A repo that isn't updated?
This blocks us from upgrading to future versions of the SDK.

**Comment by stewartmiles** [comment]
It looks like `Xcode project` integration in the [iOS Resolver](https://github.com/googlesamples/unity-jar-resolver#ios-resolver-usage) appears to not be adding the correct set of include paths for the [Firebase/DynamicLinks](https://cocoapods.org/pods/FirebaseDynamicLinks) Cocoapod.  In particular, it looks like we're not adding to `HEADER_SEARCH_PATHS` from [here](https://github.com/CocoaPods/Specs/blob/master/Specs/6/e/5/FirebaseDynamicLinks/3.1.0/FirebaseDynamicLinks.podspec.json#L47) correctly.

**Comment by stewartmiles** [comment]
Digging through the logs the include path is being added but Xcode is ignoring it...
```
Applying build setting 'HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/FirebaseDynamicLinks" "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/FirebaseAnalytics" "${PODS_ROOT}/Headers/Public/FirebaseAnalyticsInterop" "${PODS_ROOT}/Headers/Public/FirebaseCore" "${PODS_ROOT}/Headers/Public/FirebaseDynamicLinks" "${PODS_ROOT}/Headers/Public/FirebaseInstanceID" "${PODS_ROOT}/Headers/Public/GoogleUtilities" "${PODS_ROOT}/Headers/Public/nanopb" "${PODS_TARGET_SRCROOT}"/Firebase' to build config Debug (1D6058940D05DD3E006BFB54)
UnityEngine.Debug:Log(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.40FKqscNsW/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:83)
Google.IOSResolver:Log(String, Boolean, LogLevel) (at Z:/tmp/tmp.jkgKDeCCv7/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:806)
Google.IOSResolver:UpdateProjectDeps(BuildTarget, String) (at Z:/tmp/tmp.jkgKDeCCv7/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:2375)
Google.IOSResolver:OnPostProcessUpdateProjectDeps(BuildTarget, String) (at Z:/tmp/tmp.jkgKDeCCv7/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:2047)
UnityEditor.HostView:OnGUI()
```

Perhaps `PODS_TARGET_SRCROOT` isn't set?

**Comment by stewartmiles** [comment]
Well it turns out `PODS_TARGET_SRCROOT` isn't set and is actually set per pod project which means that we'll need to expand this in the iOS Resolver.

Changing the include path to `"${PODS_ROOT}"/FirebaseDynamicLinks/Firebase` fixes the include issue but turns up a compile error in the Dynamic Links pod.

**Comment by stewartmiles** [comment]
@eladleb as you can see from some of these updates we have some patches to the iOS SDK to build with Unity's default C compiler settings (C99) that fixes compile errors.  In addition, I have a patch lined up to the iOS resolver internally that I should be able to release publicly very shortly that will fix the Dynamic Links source pod integration into the Xcode project that is required for Unity Cloud Build.  Once the new iOS SDK is released along with the new iOS resolver we'll post the workaround to apply to the Unity SDK until we have a new release (likely next week).

**Comment by stewartmiles** [comment]
Play Services Resolver 1.2.94 contains a fix for building source pods like Dynamic Links
https://github.com/googlesamples/unity-jar-resolver/raw/master/play-services-resolver-1.2.94.0.unitypackage

However, the Dynamic Links pod still won't compile in the Unity generated project as it's using `typeof()` rather than `__typeof__()`.  If you *really* need this to work right now you'll need to write a build step to patch the Xcode project to change the C compiler language dialect from C99 to GNU99.

**Comment by eladleb** [comment]
Hey @stewartmiles, thank you so much for your prompt and thorough investigation, it looks great! 
I'll hang tight for the updated Unity SDK or a workaround which doesn't involve an additional build step in Xcode.

**Comment by eladleb** [comment]
I just integrated Unity SDK 5.4.2 and it seems to build correctly in cloud build, thank you so much!
