### ISSUE TITLE
App crashes after FirebaseAuth auth = FirebaseAuth.DefaultInstance

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#229]
I use FireBase authentication with a simple function that signs up a new user, it works great on the Unity Editor, but when I build it on my Android, it crashes the second it starts FirebaseAuth auth = FirebaseAuth.DefaultInstance
This is the error I get before it crashes- 

> Java class com/google/firebase/auth/FirebaseAuthWebException not found. Please verify the AAR which contains the com/google/firebase/auth/FirebaseAuthWebException class is included in your app.

Why do I even get the Firebase-AuthWeb-Exception ?
Why can't it find that exception? (I tried to resolve jar files, and to re-import auth SDK but it didn't solve the issue
My app is simple- there's a SignUp button that calls this function-

`public void SignUp()
 {
    FirebaseAuth auth = FirebaseAuth.DefaultInstance;  //The error is after this line

}`

**Comment by stewartmiles** [comment]
The `FirebaseAuthWebException` error message is non-fatal and unfortunately expected behavior see  https://github.com/firebase/quickstart-unity/issues/224#issuecomment-432287386 .

Could you post the stack trace from the crash?

Are you sure you've run the [Android Resolver](https://github.com/googlesamples/unity-jar-resolver#android-resolver-usage) to install the Android libraries required?

**Comment by shlighter** [comment]
Not sure how to get the stack trace, I'll check it up.  
Yes- I tried Android resolver- Force resolve

**Comment by stewartmiles** [comment]
Since you're targeting Android we'll need `adb logcat` output to see what's going on.
https://developer.android.com/studio/command-line/logcat
https://developer.android.com/studio/debug/am-logcat

**Comment by shlighter** [comment]
I copied my error from the adb logcat output, it doesn't tell much-

10-23 14:03:17.169  9554  9606 I Unity   :
10-23 14:03:17.169  9554  9606 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-23 14:03:17.169  9554  9606 I Unity   :
10-23 14:03:17.429  9554  9606 I Unity   : Firebase App initializing app com.game.gamey (default 1).
10-23 14:03:17.429  9554  9606 I Unity   :
10-23 14:03:17.429  9554  9606 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-23 14:03:17.429  9554  9606 I Unity   :
10-23 14:03:17.479  9554  9606 E Unity   : Java class com/google/firebase/auth/FirebaseAuthWebException not found.  Please verify the AAR which contains the com/google/firebase/auth/FirebaseAuthWebException class is included in your app.
10-23 14:03:17.479  9554  9606 E Unity   :
10-23 14:03:17.479  9554  9606 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
10-23 14:03:17.479  9554  9606 E Unity   :
10-23 14:06:42.029 12955 13007 E Unity   : [EGL] Failed to create window surface: EGL_BAD_ALLOC: EGL failed to allocate resources for the requested operation.
10-23 14:06:42.029 12955 13007 E Unity   :
10-23 14:06:42.029 12955 13007 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 149)
10-23 14:06:42.029 12955 13007 E Unity   :
10-23 14:06:42.029 12955 13007 I Unity   : Skipped rendering frame because GfxDevice is in invalid state (device lost)
10-23 14:06:42.029 12955 13007 I Unity   :
10-23 14:06:42.029 12955 13007 I Unity   : (Filename:  Line: 810)
10-23 14:06:42.029 12955 13007 I Unity   :
10-23 14:06:42.059 12955 13007 E Unity   : [EGL] Failed to create window surface: EGL_BAD_ALLOC: EGL failed to allocate resources for the requested operation.
10-23 14:06:42.059 12955 13007 E Unity   :
10-23 14:06:42.059 12955 13007 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 149)
10-23 14:06:42.059 12955 13007 E Unity   :
10-23 14:06:42.059 12955 13007 I Unity   : Skipped rendering frame because GfxDevice is in invalid state (device lost)
10-23 14:06:42.059 12955 13007 I Unity   :
10-23 14:06:42.059 12955 13007 I Unity   : (Filename:  Line: 810)
10-23 14:06:42.059 12955 13007 I Unity   :
10-23 14:06:42.089 12955 13007 E Unity   : [EGL] Failed to create window surface: EGL_BAD_ALLOC: EGL failed to allocate resources for the requested operation.
10-23 14:06:42.089 12955 13007 E Unity   :
10-23 14:06:42.089 12955 13007 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 149)
10-23 14:06:42.089 12955 13007 E Unity   :
10-23 14:06:42.089 12955 13007 I Unity   : Skipped rendering frame because GfxDevice is in invalid state (device lost)
10-23 14:06:42.089 12955 13007 I Unity   :
10-23 14:06:42.089 12955 13007 I Unity   : (Filename:  Line: 810)

**Comment by shlighter** [comment]
OK I'll do it. I have another update- just added some dubug.log to my function- to catch the exact problematic line:

 public void SignUp()
{
        Debug.Log("a");
        FirebaseAuth auth = FirebaseAuth.DefaultInstance;
        Debug.Log("b");
        auth.CreateUserWithEmailAndPasswordAsync(email.text, password.text).ContinueWith(task =>
        {
            Debug.Log("c");
            if (task.IsCanceled)
            {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync was canceled.");
                return;
            }
            if (task.IsFaulted)
            {
                Debug.LogError("CreateUserWithEmailAndPasswordAsync encountered an error: " + task.Exception);
                return;
            }
            // Firebase user has been created.
            Firebase.Auth.FirebaseUser newUser = task.Result;
            Debug.LogFormat("Firebase user created successfully: {0} ({1})",
            newUser.DisplayName, newUser.UserId);
        });
        Debug.Log("d");
    }

The final output is "a" "b" "d" and then crush. Which means the error happens during the task:
` auth.CreateUserWithEmailAndPasswordAsync(email.text, password.text).ContinueWith(task =>`

So my title of this issue isn't correct

**Comment by stewartmiles** [comment]
Ok so this _is_ missing the Android authentication library, see....

```
10-23 15:17:48.979  2516  2516 D AndroidRuntime: Shutting down VM
10-23 15:17:48.979  2516  2516 E AndroidRuntime: FATAL EXCEPTION: main
10-23 15:17:48.979  2516  2516 E AndroidRuntime: Process: com.game.gamey, PID: 2516
10-23 15:17:48.979  2516  2516 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [main]
10-23 15:17:48.979  2516  2516 E AndroidRuntime: Unity version     : 2018.2.12f1
10-23 15:17:48.979  2516  2516 E AndroidRuntime: Device model      : samsung SM-G920P
10-23 15:17:48.979  2516  2516 E AndroidRuntime: Device fingerprint: samsung/zerofltespr/zerofltespr:6.0.1/MMB29K/G920PVPS4CPI3:user/release-keys
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 
10-23 15:17:48.979  2516  2516 E AndroidRuntime: Caused by: java.lang.AbstractMethodError: abstract method "void com.google.firebase.auth.FirebaseAuth$AuthStateListener.a(com.google.firebase.auth.FirebaseAuth)"
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at com.google.firebase.auth.p.run(Unknown Source)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at com.google.android.gms.internal.firebase_auth.ce.dispatchMessage(Unknown Source)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7237)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
10-23 15:17:48.979  2516  2516 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
10-23 15:17:48.979  3525  5270 W ActivityManager:   Force finishing activity com.game.gamey/com.unity3d.player.UnityPlayerActivity
10-23 15:17:48.989  3525  5270 D FocusedStackFrame: Set to : 0
```

Since `void com.google.firebase.auth.FirebaseAuth$AuthStateListener.a(com.google.firebase.auth.FirebaseAuth)` that suggests the *Android Resolver* failed to add the firebase-auth libraries to your project. 

Have you tried to reproduce the failure with our auth quickstart sample in this repo?

**Comment by shlighter** [comment]
Unfourntly I couldn't reproduce the failure- it's something that has to do with my project, I already removed all plugins in it and I get the same error. How can I make Android Resolver to add it to my project, Why Isn't force resolve enough?

**Comment by stewartmiles** [comment]
You should probably enable verbose logging in the Android Resolver settings then resolve with your project save Unity's log file https://docs.unity3d.com/Manual/LogFiles.html , open the working project and Android force resolve with that then save that log file.  If you compare the two, perhaps the problem with pop out at you.  If you're still having issues I recommend opening up a support ticket with firebase.google.com/support and they can help debug this with you.

**Comment by shlighter** [comment]
Yeah I already opened, it takes time...  What's the difference between the log files? resolve and force resolve? What should I look for?

**Comment by shlighter** [comment]
It seems like this guy got the same error that you mentioned but his game works fine with it-  https://github.com/googlesamples/unity-jar-resolver/issues/95#issue-282201960

**Comment by shlighter** [comment]
I finally fixed it! It was a problem with the dependencies but was impossible to solve, even though I tried Androd-resolve so many times.

-I removed all Firebase files (didn't help before)
-I removed Library folder (under project folder) 
-I removed AndroidResolverDependencies (under projectsettings folder)
-I removed unity folder in C:\Users*\AppData\Local and C:\Users***\AppData\Roaming
-Installed the Firebase package again 
-Android resolve

That's it.

**Comment by stewartmiles** [comment]
@shlighter I'm glad you got this figured out.  It does make me wonder how you got into this state though.  I'm guessing that the resolver should possibly provide a way to (re)label assets it manages since the warning you reported points at missing labels in the asset metadata for Android libraries.

**Comment by shlighter** [comment]
Yeah, but it has nothing to do with the warnings, I still get them, same as the guy from issue #95, but we both can build the game without issues. The crash was something else...

**Comment by Thaina** [comment]
I am using firebase 5.4.2 in unity 2018.3 and still got this error

```
11-20 18:28:43.827 19901 19901 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.google.firebase.auth.FirebaseAuth$AuthStateListener.a(com.google.firebase.auth.FirebaseAuth)"
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at com.google.firebase.auth.p.run(Unknown Source:4)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:898)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at com.google.android.gms.internal.firebase_auth.ce.dispatchMessage(Unknown Source:0)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:198)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6716)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-20 18:28:43.827 19901 19901 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-20 18:28:43.834  1734  2951 W ActivityManager:   Force finishing activity com.MyCompany.MyGame/com.unity3d.player.UnityPlayerActivity
```

Is this related that because I was upgrading this project from old to new version? I try to delete many things and it did not work. Stuck here for days

**Comment by stewartmiles** [comment]
@Thaina are you able to reproduce the failure with our auth sample?  As I mentioned in https://github.com/firebase/quickstart-unity/issues/229#issuecomment-432448375 it sounds like you're missing the Firebase Android SDK Auth library.

**Comment by Thaina** [comment]
@stewartmiles My point is, how can I miss `Firebase Android SDK Auth library` when I import `FirebaseAuth.unitypackage` into my project

What is the problem that it not come into my project after `force resolve` shouldn't it be a bug in play service resolver or should we have firebase android resolver function for this problem?

**Comment by stewartmiles** [comment]
If you're running `Force Resolve` in the `Android Resolver` and it completes successfully without adding the Firebase Auth AAR to your project then yeah it sounds like something is going wrong.  To help diagnose I recommend starting out with the auth sample project, seeing whether that works, if it does work it's a problem in your game project. In which case you should contact https://firebase.google.com/support so that you can share the project and have folks debug it.

If the auth sample doesn't work, enable verbose logging in the `Android Resolver` settings and post the results here so we can take a look at what is going wrong.

**Comment by Thaina** [comment]
@stewartmiles If by the library you mean `.aar` then it's here and always there after `force resolve`

![image](https://user-images.githubusercontent.com/1042507/48815536-5ea8ac80-ed71-11e8-9d82-67739c85fbd7.png)

**Comment by bensalcie** [comment]
Got also the same issue once connected app to firebase whe i check using auth if current user exists, it crushes

**Comment by stewartmiles** [comment]
@bensalcie I recommend opening a new bug that describes in more detail how your failure is occurring and how it can be reproduced with our sample application.

**Comment by bensalcie** [comment]
@stewartmiles Thanks it worked, I had to add firebase to my  Android studio the manual way and it worked, i think it was an issue with adding the firebase functionality using firebase tool kit, it didnt work with firebase 16.1.0, its working now...thanks
