### ISSUE TITLE
Firebase Cloud Messaging - игра выключается при повторном запуске с ярлыка, после сворачивания игры.

### ISSUE THREAD

**Issue by Hyper00** [firebase/quickstart-unity#23]
Firebase Cloud Messaging - игра выключается при повторном запуске с ярлыка, после сворачивания игры.

1. запустил игру.
2. свернул игру
3. запустил с ярлыка - Ошибка, игра закрывается.
3.б. запустит свернутую игру не используя ярлык - работает все нормально.

У всех остальных та же ошибка?

**Comment by stewartmiles** [comment]
I translated your comment via Google Translate so I'm not sure whether I'm understanding you correctly.

it sounds like your app is crashing on startup after integrating Firebase Messaging on Android.  There are a few things to try to diagnose this:

- Verify you're able to build and run the Firebase Messaging sample from this github repository.
- Make sure you're checking for and updating Google Play Services on the device see https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#class_firebase_1_1_firebase_app_1a3cdbb6dc40eaa7a1c07813c59f18e6d2 and https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#class_firebase_1_1_firebase_app_1ac590e3e129eec9a2ac1ebc6dca231271
- If you have customized your app's AndroidManifest.xml make sure you follow the instructions in https://firebase.google.com/docs/cloud-messaging/unity/client#note_for_android

Cheers,
Stewart

**Comment by Hyper00** [comment]
после обновления firebase компонента пошло все нормально.
Теперь после сворачивания и повторного открытия приложения(игры), все работает верно!

просто пришлось поудалять за пределами Папки "Assets" остаточные файлы... или возможно сыграло роль обновления Java JDK. А так никаких кодов недописываю и даже без их работает все отлично.

Спасибо. Я учту вашу дополнительную информацию, в дальнейших разработках.

**Comment by stewartmiles** [comment]
Ok great, I'm glad it's working now.
