### ISSUE TITLE
Firebase crash on Nox emulator

### ISSUE THREAD

**Issue by vanlecs09** [firebase/quickstart-unity#231]
i am using unity 2018.2.6, and latest firebase. Its crash in beginning. Here is the crash log.  

I/dalvikvm( 2397): Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.android.gms.common.wrappers.PackageManagerWrapper.isCallerInstantApp
W/dalvikvm( 2397): VFY: unable to resolve virtual method 662: Landroid/content/pm/PackageManager;.isInstantApp (Ljava/lang/String;)Z
D/dalvikvm( 2397): VFY: replacing opcode 0x6e at 0x002d
W/dalvikvm( 2397): threadid=1: thread exiting with uncaught exception (group=0x94d02b20). 

How can i solve this problem?  Thanks

**Comment by stewartmiles** [comment]
We'll need the whole crash log.  The context you've referenced doesn't look like it's related to Firebase.

Is it possible the emulator doesn't have Google Play Services installed?

**Comment by vanlecs09** [comment]
I have solve problem "android manifest" after upgrade android sdk tool. Here is new logcat. 


I/dalvikvm( 2497): Could not find method android.content.Context.createDeviceProtectedStorageContext, referenced from method android.support.v4.content.ContextCompat.createDeviceProtectedStorageContext
W/dalvikvm( 2497): VFY: unable to resolve virtual method 573: Landroid/content/Context;.createDeviceProtectedStorageContext ()Landroid/content/Context;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.getCodeCacheDir, referenced from method android.support.v4.content.ContextCompat.getCodeCacheDir
W/dalvikvm( 2497): VFY: unable to resolve virtual method 581: Landroid/content/Context;.getCodeCacheDir ()Ljava/io/File;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.getColor, referenced from method android.support.v4.content.ContextCompat.getColor
W/dalvikvm( 2497): VFY: unable to resolve virtual method 582: Landroid/content/Context;.getColor (I)I
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.getColorStateList, referenced from method android.support.v4.content.ContextCompat.getColorStateList
W/dalvikvm( 2497): VFY: unable to resolve virtual method 583: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.getDataDir, referenced from method android.support.v4.content.ContextCompat.getDataDir
W/dalvikvm( 2497): VFY: unable to resolve virtual method 585: Landroid/content/Context;.getDataDir ()Ljava/io/File;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.getDrawable, referenced from method android.support.v4.content.ContextCompat.getDrawable
W/dalvikvm( 2497): VFY: unable to resolve virtual method 588: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.getNoBackupFilesDir, referenced from method android.support.v4.content.ContextCompat.getNoBackupFilesDir
W/dalvikvm( 2497): VFY: unable to resolve virtual method 595: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.isDeviceProtectedStorage, referenced from method android.support.v4.content.ContextCompat.isDeviceProtectedStorage
W/dalvikvm( 2497): VFY: unable to resolve virtual method 606: Landroid/content/Context;.isDeviceProtectedStorage ()Z
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.startForegroundService, referenced from method android.support.v4.content.ContextCompat.startForegroundService
W/dalvikvm( 2497): VFY: unable to resolve virtual method 623: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0006
I/dalvikvm( 2497): Could not find method android.content.Context.isDeviceProtectedStorage, referenced from method com.google.android.gms.internal.measurement.zzsl.init
W/dalvikvm( 2497): VFY: unable to resolve virtual method 606: Landroid/content/Context;.isDeviceProtectedStorage ()Z
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0009
I/dalvikvm( 2497): Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.android.gms.common.wrappers.PackageManagerWrapper.isCallerInstantApp
W/dalvikvm( 2497): VFY: unable to resolve virtual method 758: Landroid/content/pm/PackageManager;.isInstantApp (Ljava/lang/String;)Z
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x002d
W/dalvikvm( 2497): threadid=1: thread exiting with uncaught exception (group=0x94c6cb20)
D/dalvikvm( 2497): JIT code cache reset in 0 ms (0 bytes 1/0)
D/dalvikvm( 2497): GC_CONCURRENT freed 304K, 11% free 2975K/3332K, paused 3ms+1ms, total 13ms
W/ActivityManager(  469):   Force finishing activity com.ugame.vn/com.unity3d.player.UnityPlayerActivity
I/dalvikvm( 2497): Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.android.gms.common.wrappers.InstantApps.isInstantApp
W/dalvikvm( 2497): VFY: unable to resolve virtual method 757: Landroid/content/pm/PackageManager;.isInstantApp ()Z
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0028
D/dalvikvm(  469): GC_FOR_ALLOC freed 498K, 17% free 9126K/10888K, paused 21ms, total 21ms
I/dalvikvm( 2497): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtilLight.isUninstalledAppPossiblyUpdating
W/dalvikvm( 2497): VFY: unable to resolve virtual method 750: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm( 2497): VFY: replacing opcode 0x6e at 0x0012
D/dalvikvm( 2497): GC_CONCURRENT freed 308K, 11% free 3052K/3420K, paused 3ms+0ms, total 5ms
W/ActivityManager(  469): Activity pause timeout for ActivityRecord{4aa3cb74 u0 com.ugame.vn/com.unity3d.player.UnityPlayerActivity t9 f}
W/ActivityManager(  469): Activity destroy timeout for ActivityRecord{4aa3cb74 u0 com.ugame.vn/com.unity3d.player.UnityPlayerActivity t9 f}

**Comment by stewartmiles** [comment]
@vanlecs09 I don't see the root cause of the crash in your log.  Did you reproduce the issue with one of our sample applications in this repository?  If so which Firebase Unity SDK version are you using and which Unity version are you using?  Does the crash happen if you don't use Firebase in a project?

The logs really do look like point to the wrong version of Google Play Services being installed in the emulator.
