### ISSUE TITLE
Android Build Errors

### ISSUE THREAD

**Issue by veevoogames** [firebase/quickstart-unity#233]
I saw that this issue came up on forums before, but I followed everything and still get these errors. I am on the latest versions of Unity and Android SDK.

First Error:
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-17.0.2\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Second Error:
CommandInvokationFailure: Unable to merge android manifests. 
C:/Program Files/Java/jdk1.8.0_191\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Henil_2/Documents/Android SDK\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-17.0.2\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
++    <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\com.google.firebase.firebase-analytics-impl-16.2.2\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\GoogleMobileAdsTapjoyMediation\AndroidManifest.xml:7] Skipping identical /manifest/application/activity[@name=com.tapjoy.TJAdUnitActivity] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\GoogleMobileAdsTapjoyMediation\AndroidManifest.xml:9] Skipping identical /manifest/application/activity[@name=com.tapjoy.mraid.view.ActionHandler] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\GoogleMobileAdsTapjoyMediation\AndroidManifest.xml:11] Skipping identical /manifest/application/activity[@name=com.tapjoy.mraid.view.Browser] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Henil_2\Desktop\Box Drop\BoxDrop\Temp\StagingArea\android-libraries\GoogleMobileAdsTapjoyMediation\AndroidManifest.xml:13] Skipping identical /manifest/application/activity[@name=com.tapjoy.TJContentActivity] element.
]
exit code: 1
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg, System.Int32 memoryMB) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.AndroidSDKTools.RunCommand (UnityEditor.Android.AndroidJavaTools javaTools, System.String[] sdkToolCommand, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.AndroidSDKTools.MergeManifests (UnityEditor.Android.AndroidJavaTools javaTools, System.String target, System.String mainManifest, System.String[] libraryManifests, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.MergeManifests (UnityEditor.Android.PostProcessor.PostProcessorContext context, System.String mainManifest, System.String targetManifest) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.PostProcessor.Tasks.GenerateManifest.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by stewartmiles** [comment]
See https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826
