### ISSUE TITLE
Android Gradle build error

### ISSUE THREAD

**Issue by veevoogames** [firebase/quickstart-unity#234]
I made a custom gradle template and fixed the issue where jcenter() was on top of google (). Now I get this issue regarding firebase. 

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_191\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':Firebase'.
> Could not resolve all files for configuration ':Firebase:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <66646f1b0dc04247b2706b7775074ac9>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <66646f1b0dc04247b2706b7775074ac9>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by stewartmiles** [comment]
@veevoogames this sounds very specific to your build.  I recommend opening up an issue with firebase.google.com/support .

**Comment by veevoogames** [comment]
Hey, so i figured it out, it is an issue with unity and they are working on a fix. 

https://forum.unity.com/threads/builds-started-failing-in-2-projects-ive-been-changing-with-could-not-find-intellij-core-jar.573055/
