### ISSUE TITLE
Firebase timestamp in Unity

### ISSUE THREAD

**Issue by bacabrother** [firebase/quickstart-unity#24]
I want to get the timestamp of realtime database of Firebase in Unity, is this possible?
And to create a child with a timestamp in realtime database? how do I do?

Thankz

**Comment by stewartmiles** [comment]
You can use Firebase.Database.ServerValue.TimeStamp when writing to the Database 
https://firebase.google.com/docs/reference/unity/class/firebase/database/server-value#timestamp

This stackoverflow post describes the general flow although with the Android API
http://stackoverflow.com/questions/37864974/how-to-use-the-firebase-server-timestamp-to-generate-date-created
