### ISSUE TITLE
Firebase Unity iOS issue

### ISSUE THREAD

**Issue by luszukpawel** [firebase/quickstart-unity#243]
Hi, currently i'm developing app using firebase and i'm having issues with iOS. The android vesion works great, but after changing to iOS we couldn't even build it.

After hours of fighting with documentation 
https://firebase.google.com/docs/unity/setup?authuser=1#add-the-sdk-ios

I've builded it (Only build and run worked) but we couldn't establish connection to firebase.

Xcode 10.1 for iOS 12.1
Xcode console showed this output :

` 2018-11-05 16:03:54.829080+0100 dzienstrategii[628:96003] ERROR: Unable to configure Firebase services: Google Analytics for Firebase version (50200000) does not match with Google App Measurement (50300000) version. Please update.
 Unable to configure Firebase services: Google Analytics for Firebase version (50200000) does not match with Google App Measurement (50300000) version. Please update.`

Of course i'have updated it, but nothing changed. Any ideas?

**Comment by jonsimantov** [comment]
We have released a new version with this issue fixed, version 5.4.1.
https://firebase.google.com/support/release-notes/unity#5.4.1
