### ISSUE TITLE
Built Issue in Unity with Firebase Remote Config

### ISSUE THREAD

**Issue by GIxXx3R** [firebase/quickstart-unity#245]
CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_162\bin\java.exe -classpath "D:\Softwares\Installed\Unity 2018.2.8\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateReleaseBuildConfig'.
> Failed to create D:\Unity Projects\Fire Balls 3D\Temp\gradleOut\build\generated\source\buildConfig\release\con\firebase\testing

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
]
stdout[
:preBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:processReleaseManifest
:preReleaseBuild UP-TO-DATE
:Firebase:compileReleaseAidl
:compileReleaseAidl UP-TO-DATE
:Firebase:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig FAILED
8 actionable tasks: 4 executed, 4 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <91b96cb8c6094741ab392e072fa8b17d>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by a-maurice** [comment]
Hi @GIxXx3R,

What version of Unity are you using?  And I assume this is with the Gradle build system?

Are you using anything beyond the Firebase Remote Config SDK?

Thanks

**Comment by GIxXx3R** [comment]
Unity 2018.2.4, is its Gradle Build

**Comment by a-maurice** [comment]
Hmm, still having problems reproducing it on our end.  Have you seen this problem when running just the remote config quickstart?  It is likely a bad interaction with another SDK that you're including.

**Comment by GIxXx3R** [comment]
Yes I tried with remote config quickstart project, getting same issue.
 Can the space between name be an issue?

**Comment by stewartmiles** [comment]
@GIxXx3R I've just tried this out as well with Unity 2018 & Firebase Unity SDK 5.4.3, I renamed the remote config sample directory to add whitespace in the name and I was unable to reproduce the issue.  Did you try changing the path of the sample on your machine?  Also, you never mentioned the SDK version you're using.

**Comment by stewartmiles** [comment]
@GIxXx3R since we haven't heard from you I'll assume you resolved your issue.
