### ISSUE TITLE
How to show image on notification from custom data ?

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [firebase/quickstart-unity#247]
how to show an image from notification custom data on unity FCM? I don't have knowledge of android and ios native.

**Comment by FaiyazMdAbdul** [comment]
No.I am looking for an entire image .
something like this [https://www.androidtutorialpoint.com/material-design/android-notification-example-progress-bar-big-picture-direct-reply/](url)

**Comment by alexames** [comment]
FCM is somewhat limited in how it will display notifications in the tray be default. To set up customized notifications you're going to have to add some native code to both the iOS and Android versions of your app. If you're not familiar with doing native development on each platform this might be tricky.

The way you would go about doing this on android is to override the default ListenerService that comes bundled with the plugin in your AndroidManifest.xml with a custom listener service that can build a custom notification. The new notification should use the [BigPictureStyle](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.BigPictureStyle) style.

**Comment by FaiyazMdAbdul** [comment]
> FCM is somewhat limited in how it will display notifications in the tray be default. To set up customized notifications you're going to have to add some native code to both the iOS and Android versions of your app. If you're not familiar with doing native development on each platform this might be tricky.
> 
> The way you would go about doing this on android is to override the default ListenerService that comes bundled with the plugin in your AndroidManifest.xml with a custom listener service that can build a custom notification. The new notification should use the [BigPictureStyle](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.BigPictureStyle) style.

Thanks for the clarification. I will look into it.
