### ISSUE TITLE
iOS Requires Additional Setup

### ISSUE THREAD

**Issue by bklooster** [firebase/quickstart-unity#248]
According to the quickstart page: https://firebase.google.com/docs/analytics/unity/start?authuser=0

"Initialize the SDK
The Firebase Unity SDK **on Android** requires Google Play services, which must be up-to-date before the SDK can be used. The following code should be added at the start of your application to check for and optionally update Google Play services to the version required by the Firebase Unity SDK before calling any other methods in the SDK."

The problem is that this is NOT correct and there is additional work that needs to be done on iOS in order to get the events to send on iOS. 

First, the .plist file download from the dashboard will always flag Analytics enabled as "False" which I don't think is required, but doesn't seem correct and caused me much confusion.

Second, you need to follow the process that was setup in your example code for both iOS and Android. As you need to initialize and then callback with FirebaseAnalytics.SetAnalyticsCollectionEnabled(true); callback. This is not what the documentation states, and it should be updated to match the example code in the project. 

Thanks!

**Comment by alexames** [comment]
Hi bklooster, 

The intended behavior is that you should not need to call `SetAnalyticsCollectionEnabled`. It's supposed to be enabled by default. If that's not the case then there's a bug we need to fix. The documentation is describing the intended behavior. 

The call to `CheckAndFixDependenciesAsync` shouldn't be required on iOS. In fact, on iOS that call is a no-op. It's probably a good practice to include it anyway so your code will also work on Android in case your app is cross platform. If you're seeing that it is actually needed on iOS then that seems odd and isn't the intended behavior.

I'll investigate the .plist file you mention. I'm not sure what might be happening there and let you know what I find.

**Comment by a-maurice** [comment]
Hi @bklooster,

Just to follow up up on what Alex said, one thing I'm wondering is, before you had added the call to `SetAnalyticsCollectionEnabled`, were you creating a FirebaseApp object, or calling any other Analytics functions?  It should initialize itself as soon as you do one or the other, but if that is missing, it would not initialize, which would make the Analytics events not be collected properly.  Clearly there is some confusion going on with this, so if we can resolve it, and improve any documentation about it, that'd be for the best.

**Comment by bklooster** [comment]
Hello, thanks for the quick responses. I was not creating a FirebaseApp, I was seeing log statements for initializing the Analytics on iOS once I did send an event, but still nothing showed up on the analytics website for the device. After much frustration, I tried another test device and it worked without a problem. So for some reason my test device that I was working on was not sending any analytics data. I will still probably keep the initialization code similar to what you have in your quick-start example for both platforms since I did the work to add a basic backlog queue that will be processed after initialization is completed. 

I'll close this, but if you could investigate the .plist problem from the dashboard that would be appreciated.

**Comment by WTF-Grinch** [comment]
@alexames Using Latest Firebase analytics SDK + Unity 2018.3.x on ios YOU ARE FORCE TO CALL             Firebase.Analytics.FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
in other cases Dashboard is dead :( so anyone who will face this king of thing just use this :) thanks
