### ISSUE TITLE
firebase storage working in the unity editor but no in the device

### ISSUE THREAD

**Issue by Rudieri34** [firebase/quickstart-unity#250]
I am making a system for storing 3d objects online using firebase, for this I am uploading the file through the application, however the system is not sending the file to the storage after being compiled, when I do the tests in the editor of the process unity occurs normally and successfully.

I'm using firebase for the first time for this project, so I may be making some grotesque mistake, all the help is welcome.

below is the code I'm using to send the file.

public void Send () {
        FirebaseStorage storage = FirebaseStorage.DefaultInstance;
        StorageReference storage_ref = storage.GetReferenceFromUrl ("gs: //-------.appspot.com");

        string local_file = local;
        name = name.text + ".obj";
        string URL;
        

        StorageReference rivers_ref = storage_ref.Child (nomearc);
        rivers_ref.PutFileAsync (local_file, null,
            new Firebase.Storage.StorageProgress <UploadState> (state => {
                // called periodically during the upload
                Debug.Log (System.String.Format ("Progress: {0} of {1} bytes transferred.",
                                   state.BytesTransferred, state.TotalByteCount));
                debug.text = FileBrowser.Result + (System.String.Format ("Progress: {0} of {1} bytes transferred.",
                                   state.BytesTransferred, state.TotalByteCount));
            })) ContinueWith ((Task <StorageMetadata> task) => {
            if (! task.IsFaulted &&! task.IsCanceled)
            {

                StorageReference path_reference =
                storage.GetReference (name);

                path_reference.GetDownloadUrlAsync () ContinueWith (task1 => {
                    if (! task1.IsFaulted &&! task1.IsCanceled)
                    {
                        Debug.Log ("Download URL:" + task1.Result);
                        URL = "" + task1.Result;
                        writeNewUser (URL, filename, description.text, category.text);
                    }
                });

                Debug.Log ("Finished uploading ...");
                 
               debug.text + = "Finished uploading ...";
            }
            });
    }

private void writeNewUser (string URL, string name, string description, string category)
    {
        FirebaseApp.DefaultInstance.SetEditorDatabaseUrl ("https://-------------.firebaseio.com/");
        DatabaseReference reference = FirebaseDatabase.DefaultInstance.RootReference;
        Objects user = new Objects (name, URL, description, category);

        string json = JsonUtility.ToJson (user);

        reference.Child (URL) .SetRawJsonValueAsync (json);

    }

**Comment by stewartmiles** [comment]
@Rudieri34 did you get this to work?  Perhaps you could try out what you're doing with the storage sample application in this repository?

**Comment by stewartmiles** [comment]
@Rudieri34 we'll assume you figured this out.  Please let us know if you still have issues.
