### ISSUE TITLE
How to "Zero" / Clear the  iOS notifications badge counter on app icon by unity c# ?

### ISSUE THREAD

**Issue by uokivan** [firebase/quickstart-unity#252]
How to "Zero" / Clear the  iOS notifications badge counter on app icon by unity c# ?

**Comment by stewartmiles** [comment]
This is a system level API, we don't expose this in Firebase Cloud Messaging.
See https://stackoverflow.com/questions/14038680/how-to-clear-push-notification-badge-count-in-ios

**Comment by liszto** [comment]
So it must be cleared by your system when we open the notification through the notification panel or through the app ? 
Cause currently we have issue with uncleared notification :/ or ghost badge during opening/reducing transition

**Comment by RavinderEmilence** [comment]
Hi is there any solution for this ?
How to clear the push notification from notification bar after some time.

**Comment by giliwerner** [comment]
We are looking for a solution for this as well...
