### ISSUE TITLE
Auth: Have to log in each time i run the app in editor?

### ISSUE THREAD

**Issue by rakkarage** [firebase/quickstart-unity#253]
sorry could not fund the bug for this but i read in another bug that this is not supported yet? even tho the readme says auth in editor is supported...

"We don't support auth in the editor at the moment I'm afraid. We don't have a workaround for user authentication in the editor."

**Comment by jonsimantov** [comment]
Hi,

Firebase Unity _does_ support Auth in the Unity editor for workflow testing only. However, as you've seen, it does not currently persist credentials on disk when testing on desktop.

If persisting credentials on desktop is a workflow that would help you, please [add your voice here](https://firebase.google.com/support/contact/) and describe your use case - this helps our team keep aware of what the community is looking for and prioritize features.

Thanks,

Jon

**Comment by cynthiajoan** [comment]
Persisting credential on desktop is now supported in 6.1.0. Please see release notes here:
https://firebase.google.com/support/release-notes/unity#authentication
