### ISSUE TITLE
How to deal with multiple scenes ?

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [firebase/quickstart-unity#254]
I am redirecting a user to the scene say "SCENE A" on OnReceive method.  In case I am already on Scene A and app is in the background, when I click on notification, the on receive message gets called like 20+ times. and the scene keeps reloading. How to fix?

**Comment by stewartmiles** [comment]
@FaiyazMdAbdul I'm afraid we can't debug your application for you here.  If you want someone to take a look open an issue on http://firebase.google.com/support though it does sound very application specific.  Perhaps it's worth trying to reproduce the problem with our Cloud Messaging sample (in this repo) then opening up an issue with the reproduction so someone can take a look?
