### ISSUE TITLE
Unloading broken assembly - unity 2018.2.17f1 and firebase 5.4.2

### ISSUE THREAD

**Issue by michaeleconomy** [firebase/quickstart-unity#256]
I just tried importing this package and it's not working.

Unloading broken assembly Assets/Firebase/Plugins/Firebase.App.dll, this assembly can cause crashes in the runtime
Unloading broken assembly Assets/Firebase/Plugins/Firebase.Analytics.dll, this assembly can cause crashes in the runtime
Unloading broken assembly Assets/Firebase/Plugins/Firebase.Platform.dll, this assembly can cause crashes in the runtime

there seems to be some bug in unity preventing a more detailed error message:
https://issuetracker.unity3d.com/issues/unloading-broken-assembly-error-message-provides-insufficient-information

**Comment by michaeleconomy** [comment]
guessing it's not just me:
https://stackoverflow.com/questions/53519283/when-installing-firebase-on-unity-i-get-an-error-unloading-broken-assembly
https://stackoverflow.com/questions/53401204/unloading-broken-assembly-assets-firebase-plugins-mono-firebase-database-dll-th

**Comment by 0bytedna** [comment]
I got the same error after importing Facebook SDK. The dependencies were resolved. Created APK. But, the APK refused to get installed.

**Comment by ColorTwist** [comment]
In my case APK crashed instantly with that version, had to move back to older Firebase version and wasted a full day and got a bonus headache on this.. Don't they test before releasing???

**Comment by stewartmiles** [comment]
All "Unloading the assembly" does is unload the DLL from the app domain (i.e Unity's process) then disable the platform targeting options.  So what you'll need to do is select the unloaded DLL(s) and in the plugin inspector tick the platform check boxes to re-enable them for the appropriate platform.

We typically follow the pattern to enable target platforms:

- Firebase/*.dll : Target Android, Editor, Standalone - with the exception of FIrebase.Database.dll
- Firebase/Firebase.Database.dll : Target Android-only
- Firebase/iOS/*.dll : Target iOS
- Firebase/Mono/Firebase.Database.dll : Target Editor, Standalone

**Comment by angielle** [comment]
I re-enable the target platforms as stated but it did not work.

**Comment by rahat10120141** [comment]
I have the same problem.. Any one find the solution?

**Comment by stewartmiles** [comment]
Any updates on this?  Did anyone manage to reproduce the failure?

**Comment by michaeleconomy** [comment]
Sorry for not following up.  UNfortunately i just used unity-analytics instead for my project.


However, on a seperate project, with a seperate library i ran into a simular issue with unity 2018.2.17

this was in the patch notes for 2018.2.18:
Editor: Fixed issue with precompiled managed assemblies (.dlls) in the Assets folder getting loaded twice on startup, causing two InitializeOnLoad calls where Unity API calls such as AssetDatabase.LoadAssetAtPath would fail in the first InitializeOnLoad. Now there is only one first InitializeOnLoad call and Unity APIs work as expected. (1060352)


Could be related?


Thanks for investigating Stewart, sorry for the lack of followthrough.

**Comment by deertwigarts** [comment]
Selected Firebase/Sample/Database/MainScene.unity

Where to find this?

**Comment by tomkillen** [comment]
I think people are encountering this issue because they are mismatching their Unity c# scripting backend and the dotnet version of the Firebase package.

If Unity's scripting backend is set to 3.x, you need to use the packages within the dotnet3 folder.

If Unity's backend is 4.x, then you can use the dotnet4 folder.

The steps listed on the Firebase setup instructions indicate that you can use the dotnet4 folder with Unity 2017, which is true only if you set the scripting backend to 4.x (experimental). If you want to keep using the 3.x backend, then you have to use dotnet3 packages.

**Comment by bookjunkie93** [comment]
Hey tomkillen, I had the same issue and re-importing the Firebase package using dotnet3 resolved my issue. Thanks for catching that!

**Comment by brunomonteirosud** [comment]
> I think people are encountering this issue because they are mismatching their Unity c# scripting backend and the dotnet version of the Firebase package.
> 
> If Unity's scripting backend is set to 3.x, you need to use the packages within the dotnet3 folder.
> 
> If Unity's backend is 4.x, then you can use the dotnet4 folder.
> 
> The steps listed on the Firebase setup instructions indicate that you can use the dotnet4 folder with Unity 2017, which is true only if you set the scripting backend to 4.x (experimental). If you want to keep using the 3.x backend, then you have to use dotnet3 packages.

This fixed the issue for me as well. See this post for more info: https://stackoverflow.com/a/54029970/6080254
