### ISSUE TITLE
Latest Firebase and Facebook SDK won't work together

### ISSUE THREAD

**Issue by 0bytedna** [firebase/quickstart-unity#258]
Steps to Reproduce
1. Import Firebase Auth, Resolve Dependencies.
2. Import Firebase Database, Resolve Dependencies.
3. Import Firebase Analytics, Resolve Dependencies.
4. Build & Run. Works fine.
5. Import Facebook SDK. Resolve Dependencies. Conflicts found (check attachment)
6. Builds fine. But, fails to install (check attachment)

Version
Unity 2018.2.10f1 Personal
Facebook SDK 7.14.0
Firebase SDK 5.4.2
![build](https://user-images.githubusercontent.com/7030200/49271801-2e5dbe00-f495-11e8-8188-355696d3ac50.PNG)
![conflicts](https://user-images.githubusercontent.com/7030200/49271802-2e5dbe00-f495-11e8-9e6d-15d9d1a7cae4.PNG)
![failed to install](https://user-images.githubusercontent.com/7030200/49271861-6f55d280-f495-11e8-95dc-ad1ed49f382f.jpg)

**Comment by stewartmiles** [comment]
@0bytedna you solved your issue?  If so, any chance you could explain how for other developers?

**Comment by 0bytedna** [comment]
@stewartmiles it was a stupid mistake. I was using a different package name on Facebook page and firebase console. Hence, the apk refused to install.
