### ISSUE TITLE
An assembly with the same name `Firebase.Analytics' has already been imported

### ISSUE THREAD

**Issue by adrean1980** [firebase/quickstart-unity#259]
hello
i got this error when i import the Analytics plugin :

error CS1704: An assembly with the same name `Firebase.Analytics' has already been imported. Consider removing one of the references or sign the assembly
Assets/Firebase/Plugins/Firebase.Analytics.dll 
Assets/Firebase/Plugins/iOS/Firebase.Analytics.dll

error CS1704: An assembly with the same name `Firebase.App' has already been imported. Consider removing one of the references or sign the assembly
Assets/Firebase/Plugins/Firebase.App.dll
Assets/Firebase/Plugins/iOS/Firebase.App.dll

I tested with a fresh new project on the latest version of firebase analytics.
also used the resolver update to fix the issue but the same problem

Unity : 2018.2.15
Firebase Analytics : 5.4.2
Framework NET 4.x
Mac OS

thanks

**Comment by ColorTwist** [comment]
I believe best method before upgrading is deleting 'Firebase' folder in assets

**Comment by adrean1980** [comment]
thank you so much for your answer, i didn't upgrade the firebase plugin, i used the latest version directly, also every dll is for specific platform, the only solution i found is target ios platform in dll settings for those iOS/Firebase dll's, but if i switch the platform from android to iOS from unity menu, the firebase was inaccessible in the scripts for that platform, i need a solution to make those dlls working for two platforms android/ios.
thanks

**Comment by ColorTwist** [comment]
I do not use Mac, but try to delete Firebase folder in assets, and reinstalling firebase.
Look for if you have duplicate files, if you do, remove the duplicate.

**Comment by a-maurice** [comment]
Hi @adrean1980 

So, just to clarify, you are seeing this with a brand new project, that has not imported anything prior?

When you are importing the Firebase plugins, are you using the ones located in the dotnet4 folder?

If you look in your Assets/Firebase/Plugins/ folder, you should presumably have:
  Firebase.Analytics.dll
  Firebase.Analytics.dll.mdb
  Firebase.App.dll
  Firebase.App.dll.mdb
  Firebase.Platform.dll
  Firebase.Platform.dll.mdb
  Google.MiniJson.dll
  link.xml
and a folder iOS, with:
  Firebase.Analytics.dll
  Firebase.Analytics.dll.mdb
  Firebase.App.dll
  Firebase.App.dll.mdb

Are any of those files missing, or do you have any other files in there then the ones I listed?

And finally, if you inspect the dlls in the Unity editor, the ones not in the iOS folder should have Editor, Standalone, and Android checked.  Meanwhile, the ones in the iOS folder should only have iOS checked.
