### ISSUE TITLE
How can I get notifications with the closed app in Unity?

### ISSUE THREAD

**Issue by leynier** [firebase/quickstart-unity#262]
Please, can you tell me how to receive notifications with the closed app in Unity?

**Comment by a-maurice** [comment]
Hi @leynier 

Just to clarify, I assume you want to be able to send push notifications to the user while the app is not running?  You can do that with Firebase Cloud Messaging, https://firebase.google.com/docs/cloud-messaging/unity/client.  Once you've subscribed to messaging by initializing it the first time, users will receive notifications that you send out the application.

**Comment by leynier** [comment]
@a-maurice thanks!
