### ISSUE TITLE
My Unity application receives notifications with the application closed on some devices and NOT on others

### ISSUE THREAD

**Issue by leynier** [firebase/quickstart-unity#263]
Notifications are received with the app closed on a **Huawai Y6** with **Android 8** and are not received on a **Huawai Y5** with **Android 6**

**Comment by a-maurice** [comment]
Just to clarify, I assume you are sending notifications through the firebase console for your project?  Are you sending to the specific device via the token, sending via a topic, or just sending to the application?

If the app is running, do you see the messages coming through then?

**Comment by a-maurice** [comment]
As an update, I've contacted some of the folks that might have a better understanding of why this might occur, as it is likely not a Unity specific issue.  Apparently there have been some problems similar to this with Huawai devices in the past that have to do with battery optimization preventing messages from going through, which might be the cause of your problems.

**Comment by stewartmiles** [comment]
For context, there is a description of this here https://stackoverflow.com/questions/38016196/firebase-cloud-messaging-not-received-when-app-in-background
