### ISSUE TITLE
Auth: Error of AccountExistsWithDifferentCredentials not returning ErrorCode on android

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#265]
While with Unity Editor it works and ErrorCode returns value of 6, on Android it returns -1 with the correct error name :

>  "An account already exists with the same email address but different sign-in credentials ......"  

 Using code from Auth example to handle error:
```
/ Log the result of the specified task, returning true if the task
    // completed successfully, false otherwise.
    protected bool LogTaskCompletion(Task task, string operation) {
      bool complete = false;
      if (task.IsCanceled) {
        DebugLog(operation + " canceled.");
      } else if (task.IsFaulted) {
        DebugLog(operation + " encounted an error.");
        foreach (Exception exception in task.Exception.Flatten().InnerExceptions) {
          string authErrorCode = "";
          Firebase.FirebaseException firebaseEx = exception as Firebase.FirebaseException;
          if (firebaseEx != null) {
            authErrorCode = String.Format("AuthError.{0}: ",
              ((Firebase.Auth.AuthError)firebaseEx.ErrorCode).ToString());
          }
          DebugLog(authErrorCode + exception.ToString());
        }
      } else if (task.IsCompleted) {
        DebugLog(operation + " completed");
        complete = true;
      }
      return complete;
    }
```

**Comment by chkuang-g** [comment]
Hi @ColorTwist 
I tried it with Firebase 5.4.3 but I cannot reproduce this.

Here is what I tried to do
- Enter Email and Password for a new account and click "Create User"
- Exit the app/editor and relaunch/replay it.
- Enter the email but the wrong password.
- Click on "Sign In With Email" => Error Code 12 WrongPassword for both Editor and Android
- Click on "Sign In With Email Credential" => Error Code 12 WrongPassword for both Editor and Android.

Could you try the latest SDK and see if it resolve the issue?  If not, could you provide the reproduction steps?

Thank you!
Shawn

**Comment by ColorTwist** [comment]
Thanks for the test.
I did a few tests.
Also on my test WrongPassword with Error Code 12 shows correctly, both Editor and Android.

Instead of AccountExistsWithDifferentCredentials which requires more steps, you can try MissingPassword.

1. Write any email (no matter which)
2. Place empty string in password

I place unity UI "Input Field" component into these fields.
Like TextUserInputPassword.text and TextUserInputEmail.text

While if TextUserInputPassword.text has a blank string (User did not place a password at all)  it receives blank "" by default in Unity.

On Editor your will receive: Error Code 38  MissingPassword.
On Android you will receive: Error Code  -1 Unimplemented

**Comment by chkuang-g** [comment]
Got it.
I am able to reproduce this using blank password and "Sign In With Email Credential".
I have created an internal task to track this and will keep you updated.

At the meantime, you probably need to do some temporary work-around to check password field when the error code is -1.

Sorry for the inconvenience and thanks for reporting!

Shawn

**Comment by ColorTwist** [comment]
Glad to assist 👍 
Workaround is to wait for a fix, or validate field myself. Bigger issue that It can happen with other AuthError's enums like AccountExistsWithDifferentCredentials  and i can remember there are even a few more, but at least with AccountExistsWithDifferentCredentials  its shows the error description but with Error Code -1 Unimplemented. 
I can  "parse" the error text.

**Comment by ColorTwist** [comment]
When are you planning to release a fix for all those AuthError?

**Comment by chkuang-g** [comment]
Sorry, I cannot give you a timeline.  But will keep you posted when the fix is ready in a new release.

**Comment by ColorTwist** [comment]
Great, hope to see it soon,  please note that it happens with different AuthError's than the ones I already mentioned on Android.

**Comment by chkuang-g** [comment]
No need to close the thread.  We'll close once the fix is ready.  :)

**Comment by patm1987** [comment]
This should have made it into the 6.1.0 release. Let us know if the issue still persists!
