### ISSUE TITLE
Firebase Auth error in unity 2018.2.17f1

### ISSUE THREAD

**Issue by thanhtoan88** [firebase/quickstart-unity#269]
when create new user!
"User Creation encounted an error."
my call
` public void Start() {
        instance = this;
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
          dependencyStatus = task.Result;
          if (dependencyStatus == Firebase.DependencyStatus.Available) {
            InitializeFirebase();
          } else {
            Debug.LogError(
              "Could not resolve all Firebase dependencies: " + dependencyStatus);
          }
        });
  }
    private void Update()
    {
        if (Input.GetKeyDown("up"))
        {
            email = "nguyenthanhtoan@d.com";
            password = "12340566";
            displayName = "thanhtoan";
            CreateUserAsync();
        }
    }`
please!..

**Comment by chkuang-g** [comment]
Hi @thanhtoan88 
Could you shared a bit more about the error?  Ex.
- What is the full error message?
- Was there any exception thrown?
- Is CreateUserAsync() called after InitializeFirebase() is called?
- Which platform does this occur on?

Thank you,
Shawn

**Comment by thanhtoan88** [comment]
> Hi @thanhtoan88
> Could you shared a bit more about the error? Ex.
> 
> * What is the full error message?
> * Was there any exception thrown?
> * Is CreateUserAsync() called after InitializeFirebase() is called?
> * Which platform does this occur on?
> 
> Thank you,
> Shawn

`public void Start() {
        instance = this;
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
          dependencyStatus = task.Result;
          if (dependencyStatus == Firebase.DependencyStatus.Available) {
            InitializeFirebase();
                email = "nguyenthanhtoan@d.com";
                password = "12340566";
                displayName = "thanhtoan";
                CreateUserAsync();
            } else {
            Debug.LogError(
              "Could not resolve all Firebase dependencies: " + dependencyStatus);
          }
        });
  }`
------------------error----------------------
`User Creation encounted an error.
UnityEngine.Debug:Log(Object)
LoginHandler:DebugLog(String) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:98)
LoginHandler:LogTaskCompletion(Task, String) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:178)
LoginHandler:HandleCreateUserAsync(Task`1, String) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:213)
<CreateUserAsync>c__AnonStorey0:<>m__0(Task`1) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:207)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()`
--------------------------------------------
`AuthError.Failure: Firebase.FirebaseException: An internal error has occurred.
UnityEngine.Debug:Log(Object)
LoginHandler:DebugLog(String) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:98)
LoginHandler:LogTaskCompletion(Task, String) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:189)
LoginHandler:HandleCreateUserAsync(Task`1, String) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:213)
<CreateUserAsync>c__AnonStorey0:<>m__0(Task`1) (at Assets/1 My Game/2 Scripts/LoginHandler.cs:207)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
`
=================.unitypackage======================
FirebaseAnalytics.
FirebaseDatabase.
FirebaseMessaging.
GoogleMobileAds.
FirebaseAuth.
==================platform================
windown pc.
android.
----------------------------------
:D

**Comment by chkuang-g** [comment]
Got it.

I would recommend you to get the error code from that FirebaseException, like the following sample.  This should give you more insight about what went wrong.
https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs#L246

You can find all the error code here.
https://firebase.google.com/docs/reference/unity/namespace/firebase/auth

**Comment by stewartmiles** [comment]
@thanhtoan88 did you managed to get the data from the exception you're seeing?

**Comment by stewartmiles** [comment]
@thanhtoan88 since we haven't heard from you I'll assume you've resolved your issue.
