### ISSUE TITLE
How properly receive messages when app is killed?

### ISSUE THREAD

**Issue by foritari** [firebase/quickstart-unity#272]
Hi, I'm not where good in java, but I need somehow receive messages from firebase when unity app is killed.
I override ListenerService, for test:
```
public class MyListenerService extends ListenerService {
    @Override
    public void onMessageReceived(RemoteMessage message) {
        showBrowser();
    }
    protected void showBrowser(){

        String url = "http://www.google.com";
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setData(Uri.parse(url));
        i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        this.startActivity(i);
    }
}
```
But as I see it's only working in background and foreground, but when app is killed it's not working.
So how can I do it? As I understand I need to use my own activity as mention here https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity but I don't really understand what should I do, and how?
Should I override MessagingUnityPlayerActivity and add there service that live forever or what? Could you pls help me and give an advice?

**Comment by stewartmiles** [comment]
https://stackoverflow.com/questions/3606596/android-start-activity-from-service

In general, starting a foreground activity from a service is pretty bad from a user experience point of view.  We really only expose the listener service so that you can customize how the message is displayed.  If the user clicks on the notification then FCM will by default launch your application with the appropriate information for you to open the message in the application.

**Comment by foritari** [comment]
I don't really want to start a new activity from service I just what to clarify and understand how can I receive messages from firebase in unity project when it killed. I tried to do it by overeating listener service, but as I see it doesn't work when app is killed, and I can't receive a message through it. 
So my question how can I do it? Should override unity activity and somehow determine there how should I receive message from firebase, or what?

**Comment by stewartmiles** [comment]
@foritari when the app is killed you can't receive messages via the service at all.

**Comment by foritari** [comment]
ok, any other way to receive it when unity app is killed?

**Comment by stewartmiles** [comment]
Ah ok, I misunderstood your question.
 
See https://firebase.google.com/docs/cloud-messaging/android/receive#backgrounded
And clarification in here: https://stackoverflow.com/questions/37358462/firebase-onmessagereceived-not-called-when-app-in-background/37395785

The other thing you're likely running into is that if you start a service from the app, then when the app is killed the service will also be killed as it's run in the same process.  Instead you could start the service in another process or kick off the service again when the activity is stopped:
https://stackoverflow.com/questions/22514373/start-a-service-in-a-separate-process-android
https://stackoverflow.com/questions/30525784/android-keep-service-running-when-app-is-killed

**Comment by foritari** [comment]
Ok, thanks, so for clarification:
If when unity app is started, I create service, that lives even if app is killed, and it will help me receive this message from firebase. 
And here some questions, sorry for this but I'm not really good in android, should I somehow store, or create an instance of this listener service, in this always living service? Or because it's living all the time this listener service will also work and receive messages?

**Comment by stewartmiles** [comment]
If the app is killed and your service is killed Firebase Cloud Messaging will pop up any notifications in the notification center.  If you want to keep the service running to receive messages, I think you'll be trying to do something we don't officially support (again see https://stackoverflow.com/questions/37358462/firebase-onmessagereceived-not-called-when-app-in-background/37395785 ).  If you still want to persist to see whether you can get this to work, you could try following https://stackoverflow.com/questions/30525784/android-keep-service-running-when-app-is-killed to keep your service running to receive messages .. no guarantee it's going to work though.

**Comment by foritari** [comment]
@stewartmiles that for help, I have found how can I work with this.
