### ISSUE TITLE
Firebase Analytics: Custom Event not shows in Dashboard

### ISSUE THREAD

**Issue by geekfarmer** [firebase/quickstart-unity#274]
Hi,
I added firebase analytics to my unity game. I created some custom events. But even after 24 hours it not showed in my firbase dashboard.

**Comment by stewartmiles** [comment]
@geekfarmer please open an issue on the Firebase support page, you'll be able to share your project with our support staff who can help you with this.  You should probably provide more information up front as well, like SDK version, target platform etc.

**Comment by stewartmiles** [comment]
http://firebase.google.com/support
