### ISSUE TITLE
Real time database constant errors when offline

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#277]
```
   // Set up the Editor before calling into the realtime database.
            FirebaseApp.DefaultInstance.SetEditorDatabaseUrl("https://api-project-123456789.firebaseio.com/");

            // Get the root reference location of the database.
            reference = FirebaseDatabase.DefaultInstance.RootReference;
```

When executed offline (no internet)
you receive this constant error:

> 22/12/2018 15:22:02 [Error] WebSocket: ws_6 - WebSocketException during handshake
> Firebase.Database.Internal.TubeSock.WebSocketException: unknown host: api-project-123456789.firebaseio.com ---> System.Net.Sockets.SocketException: Could not resolve host 'api-project-123456789.firebaseio.com'

I understand it tries to connect but can't, but it seems i can't control or catch this error, or can i?

While testing game in Unity editor while Internet offline, it just **pause** the editor like every second.
How to handle such situation ?

**Comment by Nolanlemahn** [comment]
> While testing game in Unity editor while Internet offline, it just pause the editor like every second.
How to handle such situation ?

As far as this bit goes, it's possible that you have `Error Pause` turned on. (A Unity feature.) Make sure that it is off if you don't want that functionality.

[image](https://user-images.githubusercontent.com/8920847/50426034-087bcd00-0839-11e9-8aea-447429def5a4.png)

**Comment by ColorTwist** [comment]
True, my `Error Pause` is enabled, however, i want it to be that way. Thanks for rising this in case i'll want to disable it.
All i want is to be able to catch these error or at least detect somehow that Firebase database can't reach destination to pop up a proper message to player.

**Comment by stewartmiles** [comment]
@ColorTwist that error is coming from the desktop implementation of database which doesn't handle offline very well.  I would advise that you test on device (Android & iOS) to test this behavior at the moment.  In terms of the error, it's actually just noise that is coming from an internal thread that is continually trying to reconnect to the database.
