### ISSUE TITLE
Failed to rename asset Assets/Plugins/x86_64/Firebase/libFirebaseCppApp-5.4.3.so to Assets\Plugins\x86_64\Firebase\libFirebaseCppApp-5.4.3.so (The source asset could not be found)

### ISSUE THREAD

**Issue by chenhuo** [firebase/quickstart-unity#282]
1.Create New Unity Project     Unity2018.1.16
2. Switch .Net4.x
3.Import dotnet4/FirebaseStorage.FirebaseStorage.unitypackage
4.Failed to rename asset Assets/Plugins/x86_64/Firebase/libFirebaseCppApp-5.4.3.so to Assets\Plugins\x86_64\Firebase\libFirebaseCppApp-5.4.3.so (The source asset could not be found)
Failed to rename asset Assets/Plugins/x86_64/Firebase/libFirebaseCppAuth.so to Assets\Plugins\x86_64\Firebase\libFirebaseCppAuth.so (The source asset could not be found)
Failed to rename asset Assets/Plugins/x86_64/Firebase/libFirebaseCppStorage.so to Assets\Plugins\x86_64\Firebase\libFirebaseCppStorage.so (The source asset could not be found)

**Comment by Ahmed-YehiaGPEL** [comment]
Experiencing this issue as well, Unity version: 2018.2.1f1

**Comment by fractalfrenzy** [comment]
Seeing this as well. Unity 2018.2.5f1

**Comment by fractalfrenzy** [comment]
Reimporting the package seems to have corrected.

**Comment by stewartmiles** [comment]
This was fixed in
https://github.com/googlesamples/unity-jar-resolver/commit/4de0916e60a8d6e41da8c3c12cebad86c22b3e0b
and release in Play Services Resolver version 1.2.97 (
https://github.com/googlesamples/unity-jar-resolver/blob/master/play-services-resolver-1.2.97.0.unitypackage
).  This fix will be integrated into the next Firebase Unity SDK release.

Cheers,
Stewart

**Comment by rohantalesara** [comment]
Is it possible to somehow integrate this fix in Unity 2018.3.0f2? I don't think I have enough time on hand to wait for the next Firebase SDK release. I'm facing the same issue with Firebaseauth.unitypackage.
Thanks in advance.

**Comment by rohantalesara** [comment]
> @rohantalesara install the latest Play Services Resolver over the Firebase Unity SDK. Each plugin in the Firebase Unity SDK simply includes the Play Services Resolver plugin, that's all there is to the integration.

@stewartmiles This  works, thanks!

**Comment by a-maurice** [comment]
We've released a new version of the Unity SDK that has the version of the Play Services Resolver with this fixed.
https://firebase.google.com/support/release-notes/unity#5.4.4
