### ISSUE TITLE
After registering the OnTokenReceived and OnMessageReceived callbacks, no more code works

### ISSUE THREAD

**Issue by leynier** [firebase/quickstart-unity#286]
```
public void Start()
{
        // This line is executed
	Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
	Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
        // This line is NOT executed
}
```

**Comment by jonsimantov** [comment]
Hi,

Could you please share what platform you are running this on (iOS, Android, or in the Unity editor) and which version of Unity are you using?

If this is on iOS or Android, are you seeing any errors in the device log? (adb logcat for Android, or Xcode device log for iOS).

Thanks!

**Comment by leynier** [comment]
I'm testing it on Android and in the Editor. In Android happens what I mention, in the editor does not happen.

Version 2018.2.10f1

Thanks in advance

**Comment by jonsimantov** [comment]
Do you see any errors come up in adb logcat?

**Comment by leynier** [comment]
Sorry, no

**Comment by a-maurice** [comment]
Hi @leynier 

A couple things to try to get more information, you can change the log level of Firebase via:
`Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug`
which might give more information.

Also, could you wrap the TokenReceived registration in a try catch block, and see if maybe an exception is coming up that Unity is not being logged.

Finally, does it seem to hang or crash, or is it just not calling any code in that particular function?

**Comment by stewartmiles** [comment]
@leynier since we haven't heard from you I'll assume you've resolved your issue.  It would be great to let us know if you still have a problem or how you fixed the problem so that we and other folks in the community can learn from this.
