### ISSUE TITLE
Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element

### ISSUE THREAD

**Issue by FancisLuo** [firebase/quickstart-unity#287]
Env:
Unity 2017.4.11f1
Firebase SDK 5.4.3

the issue: 
CommandInvokationFailure: Unable to merge android manifests. 
C:/Program Files/Java/jdk1.8.0_131\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="F:/adt-bundle-windows/adt-bundle-windows/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-17.0.4\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=**com.google.firebase.components.ComponentDiscoveryService]** element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
++    <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.android.support.support-fragment-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.android.support.support-v4-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml:15, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-auth-16.0.1\AndroidManifest.xml:6] Skipping identical /manifest/application/activity[@name=com.google.android.gms.auth.api.signin.internal.SignInHubActivity] element.
[Temp\StagingArea\AndroidManifest-main.xml:17, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-auth-16.0.1\AndroidManifest.xml:9] Skipping identical /manifest/application/service[@name=com.google.android.gms.auth.api.signin.RevocationBoundService] element.
[Temp\StagingArea\AndroidManifest-main.xml:18, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-base-16.0.1\AndroidManifest.xml:6] Skipping identical /manifest/application/activity[@name=com.google.android.gms.common.api.GoogleApiActivity] element.
[Temp\StagingArea\AndroidManifest-main.xml:19, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-basement-16.0.1\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.version] element.
[Temp\StagingArea\AndroidManifest-main.xml, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\com.google.firebase.firebase-analytics-impl-16.2.4\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
[Temp\StagingArea\AndroidManifest-main.xml:20, D:\WorkSpace\Survival2\client\SVL\Temp\StagingArea\android-libraries\GooglePlayGamesManifest.plugin\AndroidManifest.xml:12] Skipping identical /manifest/application/meta-data[@name=com.google.android.gms.games.APP_ID] element.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I've tried building the demo, analytics/testapp, it worked fine. but when do it with my own project, it reported the error as above. My own project integrated Google Play services for authentication(play-games-plugin-for unity), so I wonder if this will have effect on this issue. Then I tried to integrate google play services into the demo, it still worked fine. But this solution is not worked on my project, still. So, could someone have good solution for this issue.

And also, i have a strange issue, the libraries as below will be removed after resolved.(Assets/Play Services Resolver/Android Resolver/Force Resolve)
![image](https://user-images.githubusercontent.com/10607925/50686817-d1d45c80-1059-11e9-8f2d-c9d5a5272de0.png)

**Comment by stewartmiles** [comment]
Did you try upgrading your Android SDK?
See my response here for more information: https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826

**Comment by FancisLuo** [comment]
> Did you try upgrading your Android SDK?
> See my response here for more information: [#192 (comment)](https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826)
sorry for replaying you later, i'll try your suggestion. and let you know then.   thanks you very much

**Comment by FancisLuo** [comment]
@stewartmiles   sorry for the late feedback. I tried the solution you provided, it worked.  Thank you very much
