### ISSUE TITLE
App initializer database not found, failed to enable.

### ISSUE THREAD

**Issue by JustinSchneider** [firebase/quickstart-unity#288]
Using Unity 2018.3.0f2 with .NET 4.6 and IL2CPP, running on Windows 10.

I'm using Firebase's Auth, Database, and Functions for my project. I started with Auth and got that running. Then I added Database and got that working. I recently added Functions, which seem to be working, but in the process, looks like I somehow broke my Database plugin. While I could previously make calls to the database to save data, My DatabaseReference started throwing a null ref.

With my LogLevel set to Verbose, I notice the following console message during initialization:

> App initializer database not found, failed to enable.
UnityEngine.Debug:Log(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.yzDDfMNvim/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:13)
Firebase.FirebaseApp:LogMessage(LogLevel, String) (at Z:/tmp/tmp.E9TpPRk4XO/firebase/app/client/unity/proxy/FirebaseApp.cs:90)
Firebase.AppUtilPINVOKE:SetEnabledAppCallbackByName()
Firebase.AppUtil:SetEnabledAppCallbackByName(String, Boolean) (at Z:/tmp/tmp.E9TpPRk4XO/firebase/app/client/unity/proxy/AppUtil.cs:34)
Firebase.FirebaseApp:InitializeAppUtilCallbacks() (at Z:/tmp/tmp.E9TpPRk4XO/firebase/app/client/unity/proxy/FirebaseApp.cs:407)
Firebase.FirebaseApp:CheckDependenciesAsync() (at Z:/tmp/tmp.E9TpPRk4XO/firebase/app/client/unity/proxy/FirebaseApp.cs:710)
Firebase.FirebaseApp:CheckAndFixDependenciesAsync() (at Z:/tmp/tmp.E9TpPRk4XO/firebase/app/client/unity/proxy/FirebaseApp.cs:766)
FirebaseManager:Awake() (at Assets/Scripts/Managers/FirebaseManager.cs:45)
UnityEngine.GameObject:AddComponent()
Singleton`1:get_Instance() (at Assets/Scripts/Classes/Singleton.cs:19)
MainMenu:OnEnable() (at Assets/MenuSystem/MenuScripts/MainMenu.cs:14)
UnityEngine.Object:Instantiate(MainMenu, Transform)
MenuManager:CreateInstance() (at Assets/MenuSystem/MenuManager.cs:39)
Menu`1:Open() (at Assets/MenuSystem/Menu.cs:17)
MainMenu:Show() (at Assets/MenuSystem/MenuScripts/MainMenu.cs:31)
MenuManager:Start() (at Assets/MenuSystem/MenuManager.cs:27)

The relevant parts of my code are as follows:
```
using System.Collections;
using System.Collections.Generic;
using System.Threading.Tasks;
using Firebase;
using Firebase.Auth;
using Firebase.Database;
using Firebase.Functions;
using Firebase.Unity.Editor;
using UnityEngine;

public class FirebaseManager : Singleton<FirebaseManager> {
    private FirebaseApp app;
    private bool firebaseReady;
    private FirebaseAuth auth;
    private FirebaseUser user;
    private FirebaseFunctions functions;
    private DatabaseReference db;
    private ThreadDispatcher dispatch;

    public delegate void AuthHandler(FirebaseUser user);
    public delegate void ResponseHandler(Response response);
    public event AuthHandler OnUserSignedIn;
    public event AuthHandler OnUserSignedOut;
    public event ResponseHandler OnError;
    public event ResponseHandler OnSuccess;

    protected override void Awake() {
        base.Awake();
        dispatch = new ThreadDispatcher();

        if (!firebaseReady) {
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(InitializeFirebase, TaskScheduler.FromCurrentSynchronizationContext());
        }
    }

    private void InitializeFirebase(Task<DependencyStatus> status) {
        var dependencyStatus = status.Result;
        if (dependencyStatus == Firebase.DependencyStatus.Available) {
            app = Firebase.FirebaseApp.DefaultInstance;
            FirebaseApp.LogLevel = LogLevel.Verbose;

            // Auth
            Debug.Log ("Setting up Firebase Auth");
            auth = Firebase.Auth.FirebaseAuth.DefaultInstance;
            auth.StateChanged += AuthStateChanged;

            // Database
            FirebaseApp.DefaultInstance.SetEditorDatabaseUrl("https://circuit-shuffle.firebaseio.com/");
            FirebaseApp.DefaultInstance.SetEditorP12FileName("circuit-shuffle-4c5ec21c8dd5.p12");
            FirebaseApp.DefaultInstance.SetEditorServiceAccountEmail("unity-editor@circuit-shuffle.iam.gserviceaccount.com");
            FirebaseApp.DefaultInstance.SetEditorP12Password("notasecret");

            db = FirebaseDatabase.DefaultInstance.RootReference;

            // Functions
            functions = FirebaseFunctions.DefaultInstance;

            firebaseReady = true;
            Debug.Log("Firebase is now ready to use");
        } else {
            // Firebase Unity SDK is not safe to use here.
            Debug.LogError(System.String.Format("Could not resolve all Firebase dependencies: {0}", dependencyStatus));
        }
    }
}
```

It may be worth noting that while Auth (initialized before Database) and Functions (initialized after Database) work correctly, the final Debug.Log of my Initialize method "Firebase is now ready to use" doesn't get called now. I thought it may be an issue with threading -- as I was running into a lot of that before -- but the other Debug.Log _does_ get called.

**Comment by a-maurice** [comment]
Hi @JustinSchneider 

It sounds like one of the libraries was disabled or deleted from your project, but I'm having trouble duplicating this on my side to find which one it could be.

Could you verify that in your project, in Assets > Plugins > x86_64 > Firebase, that FirebaseCppDatabase.dll is present, and has Editor and Standalone selected.  Also, I assume you are seeing this when running in the editor?

**Comment by JustinSchneider** [comment]
@a-maurice I think I broke something when I was trying to resolve the web socket issue I was running into from #162. I re-imported the Firebase Database plugin, disabled the Mono plugin, and restarted Unity a few times, and this issue seems to be gone now.

Please consider this issue resolved. Thanks for checking in!
