### ISSUE TITLE
How to unregist token?

### ISSUE THREAD

**Issue by AllenKwon** [firebase/quickstart-unity#29]
I'm migrating GCM to FCM.

This SDK is very good to use!

But I have two problem.

One problem is app freezing in IOS.

When app returns from background, the app is always frozen. 

I tested quickstart-unity sample and sdk 1.1.0.

Another problem is I could not find unregist function in FCM.

I want to use the function when I don't receive notification from all topics any more.

I know "FirebaseInstanceId.getInstance().deleteInstanceId();" function in Android.

Is there unregist function for Unity?

**Comment by stewartmiles** [comment]
Hi,

We're looking into the freezing issue at the moment.

Regarding unregistration, it's possible to unregister from a set of topics but not complete disconnect from FCM while the app is running using the Unity SDK at the moment.

If you want to unsubscribe users you use subscription / unsubscription from topics to manage how users are notified by your application.

If you want to give users the ability to completely disable notifications when restarting the app, if you do not touch the Firebase.Messaging.FirebaseMessaging object the static initializer will not be executed and the service will not be started by the SDK.

Cheers,
Stewart

**Comment by AllenKwon** [comment]
Thanks for quick reply, stewartmiles.

That is helpful for me.

Thanks again.

**Comment by stewartmiles** [comment]
FYI The freezing issue is being tracked in #33 , feel free to follow along there.

**Comment by johnb003** [comment]
@AllenKwon Are all of your issues raised here resolved? I'm closing this bug under the assumption they are, we can reopen if that's not the case.
