### ISSUE TITLE
Freeze with Analytics + Messaging in IL2CPP/.NET4.X Unity 2018.2.5.f1

### ISSUE THREAD

**Issue by rkelling** [firebase/quickstart-unity#290]
I have a similar problem, like: [this thread](https://github.com/firebase/quickstart-unity/issues/184) Messaging+ Analytics in IL2CPP mode. The app freeze on Splash Screen. No error, nothing in LogCat. When i remove Analytics and build new only with Messaging then everything works like a charm.

- Firebase: 5.4.3
- Unity: 2018.2.5.f1
- Scripting Runtime Version: .NET 4.X Equivilant
- API Compatibility Level: .NET Standard 2.0
- Scripting Backend: IL2CPP
- C++ Compiler Configuration: Release
- Target Architecture: ARMv7, X86

**Comment by a-maurice** [comment]
Hi @rkelling 

Just to clarify, how are you initializing the Firebase libraries (as that was the cause of the problem in the thread that you mentioned)?

Also, you can change the log level via:
`Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug`
which might help reveal what the problem could be.

**Comment by rkelling** [comment]
Hello,

first thx for the quick response. The app doesn't come to the point of initialization because if i remove all firebase code and only compile the libraries into the project the freeze happens also.

**Comment by a-maurice** [comment]
Gotcha.  I'm having problems reproducing this on my end, unfortunately.  Have you been able to reproduce this in an empty project (or for example the Messaging testapp here)?

And I take it there are no errors in the editor logs the build or anything?  Another thing to try is from the toolbar, Assets > Play Services Resolver > Settings, and make sure you are on the defaults, and then from that same toolbar location, Force Resolve.  It's possible something got into a bad state somehow, and that might help.

**Comment by stewartmiles** [comment]
@rkelling any update here?

Did you reproduce the problem with our sample project?

**Comment by rkelling** [comment]
Sorry,

had no time to test it yet. I try it this week and give u an update.

**Comment by stewartmiles** [comment]
@rkelling if you're still having an issue, I recommend you share a project with our support team via http://firebase.google.com/support
