### ISSUE TITLE
iOS: The Default Firebase app has not yet been configured

### ISSUE THREAD

**Issue by arthuronoszko** [firebase/quickstart-unity#292]
Hello!

I am trying to add Firebase Analytics to my app, and I do not quite understand it.

I have added the SDK by importing FirebaseAnalytics.unitypackage (dotnet3) into my project, that is configured as below:

Unity version: 2017.4.17f1
Firebase SDK version: 5.4.3
Scripting Runtime Version: .NET 3.5
Scripting Backend: IL2CCP

So, I can add the package, and build. Then when I run on a device, I get this message in the Xcode console:

```
019-01-11 09:45:12.598794+0100 mamborado-pro[5619:551756] 5.12.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```

If I add a custom event by adding `FirebaseAnalytics.LogEvent("map_start")` somewhere in the code, I get these messages in the Xcode console:

```
2019-01-11 10:08:51.456530+0100 mamborado-pro[5715:555690]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2019-01-11 10:08:53.311801+0100 mamborado-pro[5715:555709] 5.12.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2019-01-11 10:08:57.631687+0100 mamborado-pro[5715:555729] 5.12.0 - [Firebase/Core][I-COR000001] Configuring the default app.
```

It seems like the custom event triggers the app to configure, but it does not happen without logging an event. For now, I just want to log the standard events (`first_open` specifically).
Have I done something wrong for the App not to configure properly? Anyone else have the same issue?

**EDIT:** I have tried with an empty new project, where I do not get the message ```The default Firebase app has not yet been configured...```, but there as well, no standard events are emitted until I actually trigger a custom event.

**EDIT2:** It seems like this error message comes from Fabric/Crashlytics packages that I also use. Removing Fabric/Crashlytics removes the message ```The default Firebase app has not yet been configured...``` So the question now is if there is something I need to to in order to get this to work? And why are not for example `first_open` not triggered when opening the app?

**EDIT3:** Do you need to run ```FirebaseApp.CheckAndFixDependenciesAsync()``` in order to configure the app? I guess it should be run as early as possible when the app starts, is it best to create a script that runs that line and set the Script Execution Order of that script to something very early? Or what is the proper way of Configuring the app?

BR
Arthur

**Comment by a-maurice** [comment]
Hi @arthuronoszko 

I'd recommend starting with one of the quickstart apps that we provide here, like the Analytics one, to make sure that you are setting it all up correctly.  There are also step by step instructions, such as downloading the GoogleServices-Info.plist, which that can walk you through.

Analytics needs to be initialized by calling basically any function in it.  I'd recommend `FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);`

And yeah, if you look in the examples, you can see how to properly use `FirebaseApp.CheckAndFixDependenciesAsync()`, which should be called before using Firebase features, as it will guarantee that all the device requirements are configured correctly (for example, on Android it guarantees that Google Play Services are up to date).

**Comment by arthuronoszko** [comment]
Hi @a-maurice !

Thank you very much for your response!

I missed the part where you needed `FirebaseApp.CheckAndFixDependenciesAsync()`, and saw it after looking at the sample apps. I could not see it anywhere in the "tutorials" where to put that code, (such as in this one https://firebase.google.com/docs/unity/setup), and got confused whether the SDK did that for me somehow, like swizzling it in when building an iOS app. Now I understand more how it should be used, so thank you :)

Do you recommend to run it before everything else? Like setting the `Script Execution Order` to very early? I was afraid that it could lead to a late initialisation after reading this https://firebase.google.com/docs/projects/multiprojects#reliable-analytics, but maybe I have misunderstood?

BR
Arthur

**Comment by a-maurice** [comment]
You should be fine as long as your run it before using other Firebase calls, and while setting the Script Execution Order might help, it's shouldn't be necessary.  One thing though is in order to initialize Analytics you do need to make a call to at least one function on the `FirebaseAnalytics` class (it initializes with a static constructor), so I would recommending doing that on the `ContinueWith(...)` of `FirebaseApp.CheckAndFixDependenciesAsync()`, as we do in the Analytics sample here.

**Comment by arthuronoszko** [comment]
Okey thank you :)

Yeah, I looked at the Analytics sample, and did `FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);` in the completion block.

Thank you for your help and I think I have a better understanding now of how Firebase works with Unity.

BR
Arthur
