### ISSUE TITLE
Admob jar files are not included if Proguard is turned on!

### ISSUE THREAD

**Issue by xtrecoolx** [firebase/quickstart-unity#296]
Hi,
In Unity player settings, I turned on proguard minification because I thought a smaller APK would be better before I release my game to play store. However, I had no clue that it would mess up Admob. 
It took me several hours to figure out what was wrong and the only error message I was getting was:

AndroidJavaException: java.lang.ClassNotFoundException: com.google.unity.ads.UnityAdListener

**Please talk about Proguard and write it to your integration guideline. It should be turned off** 

I thought the resolver got messed up but it was actually Proguard's fault.

**Comment by stewartmiles** [comment]
@xtrecoolx you should report this to https://github.com/googleads/googleads-mobile-unity which contains the folks who maintain the AdMob Unity plugin.  It sounds like the AAR they have does not include a .proguard file to keep Java classes & methods referenced by the C# bindings.

**Comment by xtrecoolx** [comment]
Yeah sorry my mistake. I thought I was at their page :-) Last time I reported a Firebase issue here,  turned out to be related to Admob again :-)
