### ISSUE TITLE
Unity Firebase Authentication Example

### ISSUE THREAD

**Issue by acher249** [firebase/quickstart-unity#297]
hello,

I have a constructive criticism for the Firebase Unity Authentication Example Scene. I really do like Firebase Auth's simplicity and use it a lot for web, but it is much less usable out of the box within Unity.

There is a huge need for simple and robust authentication solutions for Unity applications.

If you want more adoption of Firebase Authentication within Unity you should provide an example scene that is using actual canvas and UI elements as is typical in responsive Unity App development. Using the hard coded GUI system just makes everyone need to take the initial time themselves to dive deep and re-wire the system into a usable responsive UI. That also opens up the possibility of debilitating bugs right off the bat (which you know better than I) can kill projects before they start.

I appreciate all the good work :)

**Comment by stewartmiles** [comment]
@acher249 thanks for the feedback.

I'm wondering whether you're asking for us to build the equivalent of AuthUI for Unity?  If so, which UI framework would we use to build this?  Different games / Unity applications use different frameworks, how would you imagine this would work?

BTW: We have the https://github.com/firebaseextended/unity-solutions for these sort of things, I could imagine if we had a reasonable idea of what we would build we could collaborate with folks like yourself to get something up for others to use.

Cheers,
Stewart

**Comment by acher249** [comment]
@stewartmiles No problem and thanks for getting back to me.

Also to answer your first question, exactly! If you have the equivalent of AuthUI for Unity that would be infinitely useful to the community. My opinion would be to not use a framework at all but use the out of the box unity UI/Canvas/Prefab system to do this. This would allow the most flexibility for Unity developers to run with, however they so choose, with confidence.

Also currently I think your Unity Auth Example Scene is only using login with Email and Password, where it would be great to have the option to use Google, Twitter, Facebook ,etc as your AuthUI does. (could just stat with Email and password to start). 

I would be happy to collaborate, and setup a wire-frame if you are interested. 

Cheers,
Adam

**Comment by stewartmiles** [comment]
@acher249 we intentionally didn't add support for auth options other than the system defaults in the public sample.  Setting up each auth provider can be a pain and in some cases the Unity bindings either aren't present or pretty poor.

w.r.t the UI framework, I can see how it would be useful it's also quite a project to maintain.  TBH you're the first Unity developer to ask us for this, if we had more interest it may be something we could look at.  At the moment though, unless you want to pioneer the effort, I'm afraid this is going to sit in this idea bucket for the moment.

**Comment by acher249** [comment]
@stewartmiles interesting and surprising! I'm sure setting up each provider is a pain and time consuming, but I thought that you guys would have it consistent with the rest of your services. Just curious and maybe you can't share but do you have a lot of people using your Auth for Unity? As there is no other simple Auth system available I think you guys could take market share pretty easily if you made it a bit more accessible. I could be wrong and maybe there isn't a need. I think that many companies, development shops, creative agencies, etc would use this. Especially with the growth projections in the Games/VR/AR space. 

If we build anything worth while I'll let you know.

Cheers,
Adam

**Comment by stewartmiles** [comment]
@acher249 we can't share numbers, but we have a lot of users.  Some of our partners are highlighted on http://firebase.google.com/games

Sure if you build something let us know how it goes.

**Comment by acher249** [comment]
Again, I'm just talking about Auth, not realtime db or storage or anything, all that has been great in Unity.
