### ISSUE TITLE
how do i get the current activity of the firebase

### ISSUE THREAD

**Issue by chamemaine** [firebase/quickstart-unity#299]
Hello sir,
am currently working on the app that need a beacons, i make my own beacon plugin using android studio, at first it was working well but after i import the firebase it start to crash.
here my code in calling the beacons plugins

unityClass = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
        unityActivity = unityClass.GetStatic<AndroidJavaObject>("currentActivity");
        customClass = new AndroidJavaClass(packageName);
        customClass.CallStatic("receiveActivityInstance", unityActivity);

i find out that i need to change com.unity3d.player.UnityPlayer to MessagingUnityPlayerActivity but i also need to change the "currentActivity" but i didn't know how to find it.

**Comment by stewartmiles** [comment]
@chamemaine see https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity

I'm not sure what you mean by "currentActivity" in Unity projects there is typically only one Android activity.
