### ISSUE TITLE
Sing in Anonymously AggregateException

### ISSUE THREAD

**Issue by sezeregrek** [firebase/quickstart-unity#3]
"System.AggregateException: Exception of type 'System.AggregateException' was thrown." I am getting this error whenever I try to sign in Firebase from unity editor. I did all the necessary things.

**Comment by stewartmiles** [comment]
We do not support authentication in the Unity Editor (see https://firebase.google.com/docs/unity/setup#stub_implementations_for_the_editor) we do intend to change the current behavior of the stub implementation though such that sign-ins from the editor always succeed.
