### ISSUE TITLE
Firebase Messaging SDK With no To, From, RawData information

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#303]
Unity editor version: 2017.4.17f1
Firebase Unity SDK version: 5.4.4
Additional SDKs you are using (Facebook, AdMob, etc.): No
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

Steps:
1- Created new project
2- Import Firebase Messaging SDK v.5.4.4 Downloaded from [Here](https://firebase.google.com/docs/cloud-messaging/unity/client)
3- Already created Firebase App
4- Downloaded GoogleService-Info.plist and imported inside Assets folder
5- Import Messaging Folder from [Here](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp/Assets/Firebase/Sample) and GUISkin
5- Build Application
6- Open Application and register device. Registration succeed.
7- Go background
8- Sent a push from Firebase Console
9- Received Push correctly
10- Application is opened via Notification
11- **From**, **To** and **RawData** are empty from FirebaseMessage object. (**Data**, **Id**, **Notification** objects have values)

What would I expected?
From: some kind of id or name
To: device token
RawData: json of data sent

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes

**Comment by a-maurice** [comment]
Thanks for the detailed bug report, we will look into this problem and try to get back to you soon about it.

**Comment by stewartmiles** [comment]
Well, I just took a look at the message receiving code in the Android component of the C++ SDK and this is indeed a bug, the fields are not being populated in the message structure that is forwarded to the C++ layer of the library.  I've filed an internal issue to get this resolved.

**Comment by MartinGonzalez** [comment]
> Well, I just took a look at the message receiving code in the Android component of the C++ SDK and this is indeed a bug, the fields are not being populated in the message structure that is forwarded to the C++ layer of the library. I've filed an internal issue to get this resolved.

Nice! I'll wait anxiously :D

**Comment by stewartmiles** [comment]
We fixed this in 5.6.0 even though it looks like it didn't make it into the release notes.

*RawData* isn't populated on any platform in the message payload from the server.  So it looks like something we should potentially remove from the API surface.
