### ISSUE TITLE
Firebase Analytics , missing events and cached events.

### ISSUE THREAD

**Issue by NeoTT** [firebase/quickstart-unity#305]
## Please fill in the following fields:
Unity editor version:  2018.1.6f1
Firebase Unity SDK version: 5.4.2
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
* The issue is very random , but for happens sometimes for sure. Our game is supposed to work in both offline and online scenarios. 
* Not all Analytics event are captured by big query. And some times very old cached analytic event is fired.
* There is no specific steps , as most of the times it works fine.But there are some events which are not fired and sometimes fired much later specially in offline scenarios.

## Please answer the following, if applicable:
No.

**Comment by a-maurice** [comment]
Hi @NeoTT 

So, I know sometimes events are cached and sent up in bulk to save on bandwidth, which might explain some of what you are seeing.  Is there any pattern on the types of events that you see are missing?  About how big of a delay are you seeing, in terms of minutes/hours/days/etc?

**Comment by stewartmiles** [comment]
@NeoTT since we haven't heard from you I'll assume @a-maurice's response solved your issue.  As he mentioned, Analytics will buffer events until the network is back up on a device.
