### ISSUE TITLE
Clearing Firebase instances on App Quit (Android)

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#306]
Unity editor version:  2018.3.4
Firebase Unity SDK version:  5.4.4

Hello,
I am using for while Firebase, I encounter a bizarre issue that when exiting the app on Android and return back like 2 seconds after the app could crash, also on exit (less common)
From the error log, I see it might be related to the Firebase database.

I am using a Firebase Real-time database,
Analytics, 
and Authentication 
My question is, on App exit (on Android) Do you clear/Destroy Firebase instances, if so how?

**Comment by a-maurice** [comment]
Hi @ColorTwist 

Across all platforms for destruction we rely on the garbage collector running when all references to the App (or Database) are gone.  Based on the situation you are describing, it might possibly be getting queued for deletion by the garbage collector, but then getting a reference to the underlying C++ instance of the database, and then the garbage collector is running.  What runtime are you using?

**Comment by ColorTwist** [comment]
4.x capability.

**Comment by a-maurice** [comment]
Yes, you can force it to clear by removing the references to it, and calling garbage collection yourself as you said, which might work around your issue.  We will keep trying to track down this problem on our end as well.

**Comment by ColorTwist** [comment]
I see, 
To what should i remove reference? Should I remove reference to `FirebaseApp`? (set it to Null)

**Comment by a-maurice** [comment]
I'd recommend removing references to `FirebaseApp` and `FirebaseDatabase` (since the Database instances hold references to the `FirebaseApp`.

**Comment by ColorTwist** [comment]
Do you mean 'DatabaseReference' for FirebaseDatabase?
To set them to null?

**Comment by chkuang-g** [comment]
Hi @ColorTwist,

Could you share the log?  Or at least the callstack, if it is availabe (using "adb logcat")?

Thank you!
Shawn

**Comment by ColorTwist** [comment]
Sorry for later reply.
I appreciate your support.

Actually, I added the following code when quitting the game and it seems to solve the nasty crashes that can happen:

```
 FirebaseDatabase.DefaultInstance.App.Dispose();
 app.Dispose(); //this is   private FirebaseApp app;
```

**Comment by stewartmiles** [comment]
@ColorTwist explicitly doing Dispose() indeed solves the issue.  When destroying the app we clean up everything that uses it - which is pretty much all of Firebase.

**Comment by stewartmiles** [comment]
@ColorTwist what is rather odd here is that the GC should be cleaning up correctly anyway.  If you have a stack trace for the crash it would be appreciated.

**Comment by chkuang-g** [comment]
@ColorTwist 
It does not make sense for you to call Dispose() to fix the issue.  But this is a reasonable workaround at the moment to unblock you.

However, I would really like to learn if there is more information (ex. logs!) so that we can fix the root cause.

Thank you!

**Comment by ColorTwist** [comment]
What happens now is that if I remove the dispose of Firebase.
1. Open game
2. Exit game (Exit to android os)
3. Open game again
4. UI get stuck (i see it), i hear music, but cannot click anything. no error in log file. Need to forcibly close game.

When I return the dispose code to 'QUIT' game function this does **NOT** happen.

It's truly OMG :)

**Comment by chkuang-g** [comment]
@ColorTwist 
If you are able to reproduce this issue, it would be really helpful to read the log and see if any crash or exception occurred.  You should be able to retrieve logs from your Android device using **adb**.  It is fairly simple. 

- If you don't have adb (check this by type in "adb" in your terminal/console/Command Line), you can download it [here](https://developer.android.com/studio/releases/platform-tools).
- Once adb is available, bring up your terminal and type
    adb logcat 
  This outputs all log available from your Android device.  If you want to clean all log, you can use 
    adb logcat -c

More info can be found [here](https://developer.android.com/studio/command-line/adb#logcat).  

Thank you.

**Comment by ColorTwist** [comment]
Yeah, I did check the logs to provide more information.
adb logcat -s Unity ActivityManager PackageManager AndroidRuntime dalvikvm DEBUG

No errors, just stuck as I explained. pretty hard to track issue like that :\

**Comment by patm1987** [comment]
Hi @ColorTwist:

Do you still experience this issue, and have you noticed any errors in your logcat? We've cleaned up a number of issues since February and would love to know if we caught yours in the mix!

--Patrick

**Comment by ColorTwist** [comment]
If i'll see anything i'll update.

**Comment by stewartmiles** [comment]
Since we haven't heard anything, we'll assume this is resolved.
