### ISSUE TITLE
I can insert data into the database just by running through unity.

### ISSUE THREAD

**Issue by H4rdG4m3** [firebase/quickstart-unity#307]
## Please fill in the following fields:
Unity editor version: 2018.3.5f1
Firebase Unity SDK version: 5.4.4
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): Android

I can not insert the data in the database by android, it fails to execute the line of code that needs to use Firebase, but when I run by the unit works perfectly, when I do the build and use in the android mobile does not execute, has refiz the project 3x from scratch, step by step, but only works within the own unity, I use a very simple project to test, a button that adds the data.
help, I can not take it anymore.

the quick start project is giving this error, I can not test with it.

Unable to load options for default app ([D:/Programas para Unity e C#/quickstart-unity-master/database/testapp/Assets/StreamingAssets\google-services-desktop.json, D:/Programas para Unity e C#/quickstart-unity-master/database/testapp/Assets/StreamingAssets\google-services.json] are missing or malformed)
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.4oHf4jn9P6/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.FirebaseApp:LogMessage(LogLevel, String) (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:90)
Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternal__SWIG_0()
Firebase.FirebaseApp:CreateInternal() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:976)
Firebase.FirebaseApp:<Create>m__0() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:144)
Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp) (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:537)
Firebase.FirebaseApp:Create() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:144)
Firebase.FirebaseApp:get_DefaultInstance() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:116)
Firebase.Database.FirebaseDatabase:get_DefaultInstance() (at Z:/tmp/tmp.CfMemjIYQK/firebase/database/client/mono/Database/FirebaseDatabase.cs:76)
Firebase.Sample.Database.DataB:StartListener() (at Assets/Sample/Database/DataB.cs:55)
Firebase.Sample.Database.DataB:InitializeFirebase() (at Assets/Sample/Database/DataB.cs:47)
Firebase.Sample.Database.DataB:<Start>b__1_0(Task`1) (at Assets/Sample/Database/DataB.cs:26)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

**Comment by a-maurice** [comment]
Just to confirm, are you generating a project in the Firebase console, downloading the google-services.json  from that project, and placing it in your Assets folder?

**Comment by H4rdG4m3** [comment]
yes, everything perfectly, I can send print if you want, from the folders, it works very well inside the unity, the data is immediate to the database, but when I do the build in android, it does not work, I already tested in mobile and in the emulator .
