### ISSUE TITLE
Can't use "await" with function.CallAsync

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#309]
I can't use "await" in async methods before Callable functions.
I get the follower error- "Task does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'Task' could be found (are you missing a using directive or an assembly reference?)"

Note that I can use await and async methods with other firebase tasks like 
 " await FirebaseDatabase.DefaultInstance.GetReference(path).GetValueAsync().ContinueWith(....."
but not with 
" await function.CallAsync(data).ContinueWith.."
Should I use yield+IEnumerator instead? I simply want to wait till my task is done/fails before continuing, no need to return any value.
Firebase Unity SDK version: 5.4.0 .NET 3.5
`   
      
         private async Task BuyItem(string text)

       {

        // Create the arguments to the callable function.
        var data = new Dictionary<string, object>();
        data["text"] = text;
        data["push"] = true;

       //Call the function and extract the operation from the result.
        var function = functions.GetHttpsCallable("buyItem");
        await function.CallAsync(data).ContinueWith((task) => {
            if (task.IsFaulted || task.IsCanceled)
            {
                Debug.Log("");
                return;
            }
 
            int money = (int)task.Result.Data;
            userMoney = money;
            return;
        });
    }`

private async void Awake()
  {
    Debug.Log("before");
     await BuyItem("hat");
 //I want it to wait for task to be done before printing "after"
    Debug.Log("after");
   }

The error I get- [picture](https://ibb.co/ngF5gL2)

**Comment by a-maurice** [comment]
Hi @shlighter,

async/await was added with .NET 4.5, and won't work with older runtimes, unfortunately.  So one possible solution would be to update to the newer runtime.

Another option is to use ContinueWith, as you are before, like:
```
private void Awake() {
  Debug.Log("before");
  BuyItem("hat").ContinueWith(t => {
    Debug.Log("after");
  });
}
```
