### ISSUE TITLE
Invalid Path error is not shown on android device

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#310]
## Please fill in the following fields:
Unity editor version: 2018.2.1f
Firebase Unity SDK version: firebase_unity_sdk_5.4.0
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Window
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
1. use UpdateAsynce() function with invalid PathID ( "user.name") - '.' is invalid for pathID
2. editor show error "DatabaseException: Invalid key: GPA.111-22-333. Keys must not contain '/', '.', '#', '$', '[', or ']'"
3. but no error is shown on android device.

important thing is i'm calling UpdateAsynce() in callback of destReference.GetValueAsync().ContinueWith()

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
upload data with call UpdateAsynce() function with invalid path id ( "user.name");

**Comment by a-maurice** [comment]
Thanks for the bug report.  We will investigate it, and see if we can get a fix out soon.

**Comment by stewartmiles** [comment]
@jonsimantov & @alexames any update here?

**Comment by a-maurice** [comment]
Hi there.  We've released a new version of the Firebase Unity SDK, 5.6.0, which should contain the fix for this issue.  Thanks again for bringing it to our attention.
