### ISSUE TITLE
Firebase Cloud Messaging with Unity Local Mobile Notification package - no callbacks on remote while app is running 

### ISSUE THREAD

**Issue by studentutu** [firebase/quickstart-unity#311]
## Please fill in the following fields:
Unity editor version:  Unity 2018.2.20f1
Firebase Unity SDK version:  5.4.4
Additional SDKs you are using (Facebook, AdMob, etc.):  Unity Mobile Notification 1.0.0 - preview 9
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac, Windows
Platform you are targeting (iOS, Android, and/or desktop):  IOS, Android

### Issue
  When FCM used alongside with Unity Mobile Notifications - no callbacks are propagated into FCM Firebase.Messaging.FirebaseMessaging.MessageReceived while the app is running or in background mode (not fully closed).

FCM still works perfectly fine  when app is fully closed and we have sent the Push notification from Firebase Console. FCM will still get the right notification and will fire the  Firebase.Messaging.FirebaseMessaging.MessageReceived. Also, nowhere in the docs specified that the Firebase.Messaging.FirebaseMessaging.MessageReceived is a separate thread call ( when used Unity specific calls like new GameObject or anything  from UnityEngine.UI - will results in a crash on IOS and silent error on Android,Unity 2018.2.20f1 dotnet 4.x ) 

### (Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

1. Install unity mobile Notification  - 1.0.0 preview 9
2. Install Firebase Cloud Messaging  5.4.4, dotnet 4.x
3. Inside the unity mobile Notification  settings for IOS - enable everything except for gps/geolocation service
4. Inside your script - initialize Unity  mobile Notificatio first - 
     Android :
                     create customChanel new AndroidNotificationChannel()
                      AndroidNotificationCenter.RegisterNotificationChannel(customChanel );, 
                       AndroidNotificationCenter.OnNotificationReceived += OnReceiveNot;  // register receiving callback

IOS : 

        public override void Init()
        {
            mynotHolder.StartCoroutine(waitCoroutine());
        }
        private IEnumerator waitCoroutine()
        {
         #if UNITY_IOS 

            using (var req = new AuthorizationRequest(AuthorizationOption.AuthorizationOptionAlert | AuthorizationOption.AuthorizationOptionBadge, true))
            {
                while (!req.IsFinished)
                {
                    yield return null;
                };
                granted = string.IsNullOrEmpty(req.Error) ? req.Granted : false;
                deviceToken = req.DeviceToken;

                string res = "\n RequestAuthorization: \n";
                res += "\n finished: " + req.IsFinished;
                res += "\n granted :  " + req.Granted;
                res += "\n error:  " + req.Error;
                res += "\n deviceToken:  " + req.DeviceToken;
                UnityEngine.Debug.Log(res);
                
            }

            iOSNotificationCenter.OnNotificationReceived += OnReceiveNot;
           #else
            yield return null;
          #endif
        }

5. Test if scripts are working properly - no FCM yet! only imported plugin. IOS/Android should work properly with custom Local Mobile Notification  

6. FCM :  Inside your scripts -
     1. init Unity Mobile Notificiation init  
     2. wait for 5 seconds
     3.  initialize FCM init  
    
            public async void Init()
        {
          #if FIREBASE_REMOTE_NOTIFICATIONS // also please provide list of Firebase defines in your docs so that we can use them as a preprocessor macros to know if the plug-in is in there!

            var task = Firebase.FirebaseApp.CheckAndFixDependenciesAsync();
            // task.Start();
            var async = await task;
            var dependencyStatus = async;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                //   app = Firebase.FirebaseApp.DefaultInstance;

                // Set a flag here to indicate whether Firebase is ready to use by your app.
                SetupFirebaseTokenAndMessages();
            }
            else
            {
                UnityEngine.Debug.LogError(System.String.Format(
                  "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
           #endif

        }

        // This will be run on Main Thread (if used inside continue with - will be run in a separate thread!)
        public
        void SetupFirebaseTokenAndMessages()
        {
          #if FIREBASE_REMOTE_NOTIFICATIONS

            Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;  // not really needed in the release build
            // get all of the Alive notification from Tray and even make a request to Firebase!
            Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived; // also please specify in docs that OnMessageReceived will be run in a thread! (Unity specific methods are not thread safe, so if used with them - IOS app will crash on receiving!)
         #endif
            GameObject.CreatePrimitive(PrimitiveType.Cube); // check - IOS should not crash here!
            Debug.Log(" End with initialization");
        }

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes.

**Comment by a-maurice** [comment]
Thanks for the detailed reproduction notes.  We will take a look into this, and see if there is a solution available.

**Comment by stewartmiles** [comment]
I worked through what you described and everything appears to work.

Here's the patched sample...

https://github.com/stewartmiles/quickstart-unity/commit/af42bc92cd6828160edefddee5d0aa70fac4a3e6

If you can reproduce, could you share a fork of the sample that reproduces the issue?

**Comment by studentutu** [comment]
@stewartmiles  sure will do it now, if it still persists, I will notify you

**Comment by Extrawurst** [comment]
@stewartmiles I actually encounter the opposite, that scheduled local notifications are not opening up the app anymore when firebase is in the project aswell. any ideas?

**Comment by stewartmiles** [comment]
@Extrawurst I recommend opening up a new issue with a reproducible case based upon our sample.  As I mentioned before I tried this in https://github.com/stewartmiles/quickstart-unity/commit/af42bc92cd6828160edefddee5d0aa70fac4a3e6 and it worked fine.  Perhaps Unity's plugin has regressed?

**Comment by re-cheid** [comment]
I have the same problem as @studentutu on iOS only the MessageReceived method is never called when the app is running (foreground or background).
