### ISSUE TITLE
GetValueAsync Crashes Unity

### ISSUE THREAD

**Issue by mimminito** [firebase/quickstart-unity#312]
## Please fill in the following fields:
Unity editor version: 2018.3.5f1
Firebase Unity SDK version: 5.4.4
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android (Editor)

## Please describe the issue here:
Every second time we run our application in the Unity Editor (targeting Android build platform) the editor crashes. After debugging it is when we call GetValueAsync on a DatabaseReference. To re-iterate this only crashes the second time we run the app in the editor, the first time (after we restart Unity from a crash) it works fine and we get through. We have tried switching to C# async/await calls instead of the ContinueWith callbacks, but it is crashing at the GetValueAsync call which means we do not even get a chance to perform any actions after the call.
The sample projects are what they need to be, samples, but they use Unity's old IMGUI system and not the new Unity UI system, meaning the interactions between the main thread and any background threads are not present. It would be good to get clarification from the Firebase team which methods need to be called "on the background thread" and when it is safe to return to the main thread, and a sample of this would be handy as well.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes, every second time we start the testapp it crashes.

**Comment by a-maurice** [comment]
Do you have a callstack with the crash?

As for the threading issue, it is unfortunately a bit complicated, and we are working on a solution to simplify it.  For the most part, any time you are interacting with anything in the UnityEngine, it needs to be handled on the main Unity thread, otherwise a background thread can be used.

**Comment by stewartmiles** [comment]
@mimminito any chance you have a callstack for the crash?

w.r.t to calling Unity methods, we recommend calling everything possible from the main thread.  In .NET 3.x we redirected all task completions to the main thread with our own Task library.  In .NET 4.x task completions are run on a background thread which means you'll need to either wrap the Task in a coroutine, use await or do something similar to what we have internally by setting up a MonoBehavior that polls for all outstanding task completion and calls closures when they're complete.

**Comment by mimminito** [comment]
@stewartmiles Thanks for the reply. Here is a log from the editor when we run the app:
[https://pastebin.com/M0v1KcxM](url)

**Comment by stewartmiles** [comment]
@mimminito it looks like you've applied the "hack" to workaround your network blocking websockets.  See my response here https://github.com/firebase/quickstart-unity/issues/304#issuecomment-468399842 .

**Comment by mimminito** [comment]
@stewartmiles All we have done is import the standard firebase SDK and started using it, not applied (knowingly) any hacks at all. Could you explain in more detail what you think we have done?

**Comment by mimminito** [comment]
@stewartmiles Sorry, I had spoken with my colleague and I see we did in fact do the DLL "hack" to enable the SDK to work in the editor. However without this, it will not run?

**Comment by stewartmiles** [comment]
@mimminito as I mentioned the "hack" to workaround your network isn't supported.  Instead you should import the RT DB plugin with the default options and ideally disable any proxies that could be affecting websocket traffic on your network.
