### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation) in ios - xcode

### ISSUE THREAD

**Issue by Gokulanathan29** [firebase/quickstart-unity#314]
while running the build button in xcode. it showing a error as 

> Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRComponent", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
  "_OBJC_CLASS_$_FIRComponentType", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
  "_OBJC_CLASS_$_FIRComponentContainer", referenced from:
      objc-class-ref in FirebaseAuth(FIRAuth.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chkuang-g** [comment]
Looks like it cannot find the Firebase iOS library, which is downloaded through Cocoapods.
It would be really helpful if you can follow the "[Firebase Unity SDK issue](https://github.com/firebase/quickstart-unity/issues/new?assignees=&labels=new&template=firebase-unity-sdk-issue.md&title=)" template and provide some more detail, but let's try to trouble shooting based on what we have.

1. In your Xcode editor Project Navigator tab, do you see "Pods" below "Unity-iPhone"?  If so, can you find FirebaseAuth folder in it?
  * If any of these is no, then try to delete your xcode project and rebuild it agian.
2. See if there is any error message in your Unity log windows.  It may provide more more detail for you.
3. In your Unity Editor, Assets > Play Services Resolver > iOS Resolver > Settings, what is your setting here (a screenshot can be helpful)? You can also check "Verbose Logging", build Xcode project again and see if anything goes wrong during the Xcode project build in the log.

Shawn

**Comment by stewartmiles** [comment]
Since we haven't heard from you, we'll assume that you fixed the issue by including the correct Cocoapods after enabling the iOS resolver.

**Comment by DiglDixon** [comment]
Just for anyone else who comes to this thread, my issue was running the build through the "Unity-iPhone.xcodeproj" file. By default, Firebase puts its stuff under the workspace file, "Unity-iPhone.xcworkspace". Opening the workspace file and building from there worked for me.
