### ISSUE TITLE
Gradle build failed, when I use FirebaseMessaging

### ISSUE THREAD

**Issue by uokivan** [firebase/quickstart-unity#317]
Unity editor version:                 2018.2.8f1
Firebase Unity SDK version:    5.5  (FirebaseMessaging only)
Additional SDKs are using :     NativeToolkit
Using the Unity editor on :       Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android

on iOS all ok , but on android have a problem,

CommandInvokationFailure: Gradle build failed. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

please help
![screen shot 2019-02-22 at 11 47 28 am](https://user-images.githubusercontent.com/23480211/53218919-00a1a300-3699-11e9-9099-afe2b8acaeb6.png)

**Comment by uokivan** [comment]
Today , I use back the Firebase Unity SDK version: 5.4.4, 
everything is ok, can build all the Platform (iOS & android)

**Comment by stewartmiles** [comment]
@uokivan the error suggests that you have multiple Android modules that are pulling in different versions of the Android support library.  If you're using other middleware try adding Firebase 5.5 to the messaging sample project (in this repo) then add the other middleware to the project progressively until it breaks.

**Comment by stewartmiles** [comment]
@uokivan have you tried what I suggested yet?

**Comment by uokivan** [comment]
I tried different versions of the Android support library , but not work , now I use the Firebase Unity SDK version: 5.4.4 to fix my problem

**Comment by cynthiajoan** [comment]
Hi @uokivan,

I'd close the issue for now as 5.4.4 works on your case. If you've been run through the same issue after upgrading the SDK, feel free to reopen it, and try what @stewartmiles suggested, to add other middlewares in our sample project one by one, to identify which one cause the issue.
