### ISSUE TITLE
iOS version of game hangs on startup randomly

### ISSUE THREAD

**Issue by ataafarin** [firebase/quickstart-unity#319]
Hi,
i migrated my game from android to ios and it usually hangs when unity is fading out but sometimes starts successfully.I tested without firebase,it starts well.
I also enabled debug mode of firebase but there is no error.
android version works well.
I am using unity 2018.3.0f2 and firebase unity_sdk_5.4.4 and xcode 9.2.

**Comment by ataafarin** [comment]
i comment these lines and the game started successfully:
`
 Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
 Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;`

so what is the problem?
Thanks

**Comment by stewartmiles** [comment]
@ataafarin could you share
* A stack trace of when the hang occurs?
* The code you're using to initialize Firebase?

If you're unable to via a public forum please open an issue with our support team on http://firebase.google.com/support and we'll take a look.

**Comment by stewartmiles** [comment]
Oh also, it would be useful to let us know if you're using any other middleware.  Firebase messaging uses swizzling to hook the AppDelegate which may be broken if other middleware overrides our logic.

**Comment by stewartmiles** [comment]
@ataafarin any more information on this?

**Comment by cynthiajoan** [comment]
Close the issue for now. If there is more information please feel free to add and reopen the issue.
