### ISSUE TITLE
Problem with Facebook SDK and Invites SDK

### ISSUE THREAD

**Issue by AIGameStudio** [firebase/quickstart-unity#32]
Hi @stewartmiles 

I was using facebook sdk for unity and everything was working fine but when imported Invites SDK the facebook login stopped to work. Feels like issue with Google SignIn required in Invites SDK.
Check here https://code.google.com/p/google-plus-platform/issues/detail?id=900

When i am removing Invites SDK, Facebook Login starts to work again.

You should make Google SignIn optional, in case if people dont want to share the Dynamic Link with Default Invite Share which requires Google SignIn.

**Comment by AIGameStudio** [comment]
@stewartmiles ,
Please can you help us

**Comment by stewartmiles** [comment]
What doesn't work exactly?  Facebook login just starts to fail?  Are there any other details you can share?

**Comment by AIGameStudio** [comment]
Looks like this issue
https://github.com/firebase/quickstart-unity/issues/19

Whats happening is when i login with facebook and after the login is successful the view is still stuck on facebook login view and not going back to the app.
When i am removing the Invites SDK things are working back.
Somehow is feel the handle open url is not handled properly

**Comment by stewartmiles** [comment]
Yeah feels like the same issue as #33 and #19  which we believe we have a fix for.  Will update the bug when we've cut a release.

**Comment by stewartmiles** [comment]
This should be resolved in the 1.1.1 release (see https://firebase.google.com/support/release-notes/unity#1.1.1) will assume this is resolved now.  Please reopen if you still have an issue.
