### ISSUE TITLE
Build failed when I use Firebase Messaging version 5.2.1 on Android

### ISSUE THREAD

**Issue by izibazi** [firebase/quickstart-unity#321]
## Environment 
Unity editor version: 2017.2.2p2
Firebase Unity SDK version: 5.2.1
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android

## Issue
Build failed when I use Firebase Messaging version 5.2.1 on Android.
I was successful until about last week.
It seems to be caused by Maven repository' aar being updated?
On iOS all ok, but on android have a problem.
If I use firebase version 4.2.1, success on android.

## Step
1. Create empty unity project. Set SCRIPT BACKEND: IL2CPP.
2. Import Package > Custom Package > firebase_unity_sdk/FirebaseMessaging.unitypackage
3. Assets > Play Services Resolver > Version Handler > Update
[ Result ]
Google Version Handler 
Update complete.

4. Assets > Play Services Resolver > Android > Resolve 
[ Result ]
Android Dependencies 
Resolution Succeeded

5. Set build system > Gradle(new)
6. Select build
7. Build failure

```
com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process See the Console for details.
```

```
CommandInvokationFailure: Gradle build failed. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-2.14.jar" org.gradle.launcher.GradleMain "assembleRelease"

stderr[
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Exception parsing classes
    	at com.android.dx.command.dexer.Main.processClass(Main.java:761)
    	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:727)
    	at com.android.dx.command.dexer.Main.access$1200(Main.java:87)
    	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1655)
    	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    	at com.android.dx.command.dexer.Main.processOne(Main.java:681)
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:578)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:315)
    	at com.android.dx.command.dexer.Main.run(Main.java:286)
    	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:52)
    	at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1511)
    	at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1507)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    	at com.android.dx.command.dexer.Main.parseClass(Main.java:773)
    	at com.android.dx.command.dexer.Main.access$1600(Main.java:87)
    	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1694)
    	at com.android.dx.command.dexer.Main.processClass(Main.java:758)
    	... 17 more
    
1 error; aborting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
]
stdout[
Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location '/Applications/AndroidSDK/adt-bundle-mac-x86_64-20140702/sdk/add-ons/addon-google_apis-google-23-1' (Expected '/Applications/AndroidSDK/adt-bundle-mac-x86_64-20140702/sdk/add-ons/addon-google_apis-google-23')
Observed package id 'build-tools;20.0.0' in inconsistent location '/Applications/AndroidSDK/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W' (Expected '/Applications/AndroidSDK/adt-bundle-mac-x86_64-20140702/sdk/build-tools/20.0.0')
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:compileReleaseNdk UP-TO-DATE
:Firebase:compileLint
:Firebase:copyReleaseLint UP-TO-DATE
:Firebase:mergeReleaseProguardFiles
:Firebase:packageReleaseRenderscript UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:prepareReleaseDependencies
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:Firebase:compileReleaseAidl
:Firebase:generateReleaseBuildConfig
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:mergeReleaseAssets
:Firebase:processReleaseManifest
:Firebase:processReleaseResources
:Firebase:generateReleaseSources
:Firebase:incrementalReleaseJavaCompilationSafeguard
:Firebase:compileReleaseJavaWithJavac
:Firebase:processReleaseJavaRes UP-TO-DATE
:Firebase:transformResourcesWithMergeJavaResForRelease
:Firebase:transformClassesAndResourcesWithSyncLibJarsForRelease
:Firebase:mergeReleaseJniLibFolders
:Firebase:transformNative_libsWithMergeJniLibsForRelease
:Firebase:transformNative_libsWithSyncJniLibsForRelease
:Firebase:bundleRelease
:prepareAndroidArchLifecycleRuntime100Library
:prepareComAndroidSupportSupportCompat2610Library
:prepareComAndroidSupportSupportCoreUi2610Library
:prepareComAndroidSupportSupportCoreUtils2610Library
:prepareComAndroidSupportSupportFragment2610Library
:prepareComAndroidSupportSupportMediaCompat2610Library
:prepareComAndroidSupportSupportV42610Library
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1600Library
:prepareComGoogleAndroidGmsPlayServicesBase1601Library
:prepareComGoogleAndroidGmsPlayServicesBasement1601Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementApi1630Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementBase1630Library
:prepareComGoogleAndroidGmsPlayServicesStats1601Library
:prepareComGoogleAndroidGmsPlayServicesTasks1601Library
:prepareComGoogleFirebaseFirebaseAnalytics1630Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1630Library
:prepareComGoogleFirebaseFirebaseAppUnity521Library
:prepareComGoogleFirebaseFirebaseCommon1610Library
:prepareComGoogleFirebaseFirebaseCore1607Library
:prepareComGoogleFirebaseFirebaseIid1710Library
:prepareComGoogleFirebaseFirebaseIidInterop1601Library
:prepareComGoogleFirebaseFirebaseMeasurementConnector1701Library
:prepareComGoogleFirebaseFirebaseMeasurementConnectorImpl1705Library
:prepareComGoogleFirebaseFirebaseMessaging1740Library
:prepareComGoogleFirebaseFirebaseMessagingUnity521Library
:prepareGradleOutFirebaseUnspecifiedLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:compileReleaseJavaWithJavac
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:lintVitalRelease
:prePackageMarkerForRelease
:transformClassesWithDexForRelease FAILED

BUILD FAILED

Total time: 15.891 secs
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.RunJava (System.String args, System.String workingdir, UnityEditor.Android.Progress progress)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, UnityEditor.Android.Progress progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by stewartmiles** [comment]
Is it possible that you need to update your Android SDK's build tools component?  See [this](https://stackoverflow.com/questions/37020413/android-dex-cannot-parse-version-52-byte-code).

Are you able to reproduce this with our sample project(s) (in this repo)?

**Comment by izibazi** [comment]
Thank you for response.
I had this problem on other unity project.
Today success on Android after I updated Google play game service  plugin from 0.9.5 to 0.9.62.
Because this plugin updated 3 days ago.
https://github.com/playgameservices/play-games-plugin-for-unity

Added `Assets/Plugins/Android/com.google.firebase.firebase-iid-17.0.4.aar`
Deleted `Assets/Plugins/Android/com.google.firebase.firebase-iid-17.1.0.aar`

This is one of diff after android resolve.

**Comment by wei-jiaxing** [comment]
It used to work fine but this week I'm having the same issue.
I was able to build my project, but now it failed when I clicked 「Android Resolver」 => 「Resolve」and built.
Then when I revert those diff, it succeeded again.

I will list the diff below:
(I just clicked「Resolve」button and didn't change any dependencies.xml files)

before|after
---|---
 `<file>Assets/Plugins/Android/com.google.firebase.firebase-common-16.0.4</file>`<br>`<file>Assets/Plugins/Android/com.google.firebase.firebase-iid-17.0.4.aar</file>`<br>`<file>Assets/Plugins/Android/com.google.firebase.firebase-messaging-17.3.4.aar</file>`|`<file>Assets/Plugins/Android/com.google.auto.value.auto-value-annotations-1.6.jar</file>`<br>`<file>Assets/Plugins/Android/com.google.firebase.firebase-common-16.1.0</file>`<br>`<file>Assets/Plugins/Android/com.google.firebase.firebase-iid-17.1.0.aar</file>`<br>`<file>Assets/Plugins/Android/com.google.firebase.firebase-messaging-17.4.0.aar</file>`<br>

I guess it's not caused by Firebase Messaging Plugin For Unity,  but I want to report this here to see if they come up with solutions.
Also, I will try to update build tools on our build machine tomorrow.

Here is my environment info:
Unity 5.3.6p4
Firebase Messaging version 5.4.4
Google.JarResolver_v1.2.98.0
Build System: Gradle

**Comment by alexames** [comment]
@wei-jiaxing, I think your guess is probably right. There's probably a conflict between the versions of Firebase you're trying to use and the dependencies that some other library is expecting. 

Can you try to reproduce this in the quickstart app? If you can get the quickstart app to run, try adding the other libraries you're using one at a time until the build breaks again. That way you can diagnose where the conflict is coming from.

**Comment by wei-jiaxing** [comment]
Thank you for advice.
When there are Firebase's dependencies.xml files only, it resolves the library version I write in [`before` column](https://github.com/firebase/quickstart-unity/issues/321#issuecomment-469238735) and works.
But when I add `com.google.android.gms:play-services-xxx`, the conflict has occurred and it resolves the library version I write in [`after` column](https://github.com/firebase/quickstart-unity/issues/321#issuecomment-469238735) then build become failed.

Here is the conflicting dependencies infomation.
```
Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.android.gms:play-services-basement:9.4.0 --> com.google.android.gms:play-services-basement:9+
com.google.android.gms:play-services-location:9.4.0 --> com.google.android.gms:play-services-location:+
com.google.firebase:firebase-auth:16.1.0 --> com.google.firebase:firebase-auth:+
com.google.firebase:firebase-common:16.0.4 --> com.google.firebase:firebase-common:16+
com.google.firebase:firebase-core:16.0.6 --> com.google.firebase:firebase-core:+
com.google.firebase:firebase-iid:17.0.4 --> com.google.firebase:firebase-iid:+
com.google.firebase:firebase-iid:[17.0.4] --> com.google.firebase:firebase-iid:+
com.google.firebase:firebase-messaging:17.3.4 --> com.google.firebase:firebase-messaging:+
```

I don't know why the `com.google.android.gms:play-services-xxx` affects the firebase's library version.
But the problem was solved when I changed
-  `com.google.android.gms:play-services-basement:9.4.0` --> `com.google.android.gms:play-services-basement:16.0.1`(the com.google.android.gms:play-services-basement.aar version in Plugin/Androids)
- `com.google.android.gms:play-services-location:9.4.0` --> `com.google.android.gms:play-services-location: 16.0.0`(com.google.android.gms:play-services-location.aar version in Plugin/Androids)

---
Back to the error `Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.`

It seems that one of the file was been compiled using Java 8 or above and cannot be built by unity.
I will temporarily change the version as I wrote above before resolved 
```
<file>Assets/Plugins/Android/com.google.auto.value.auto-value-annotations-1.6.jar</file>
<file>Assets/Plugins/Android/com.google.firebase.firebase-common-16.1.0</file>
<file>Assets/Plugins/Android/com.google.firebase.firebase-iid-17.1.0.aar</file>
<file>Assets/Plugins/Android/com.google.firebase.firebase-messaging-17.4.0.aar</file>
```

**Comment by alexames** [comment]
I don't think you should need to add `play-services` to the `dependencies.xml` file. In fact, I don't think you need to manually edit that file at all. Is there a reason you're manually adding that?

**Comment by wei-jiaxing** [comment]
Oh, I forgot to say that play-services is used by other plugins in my project

**Comment by porori** [comment]
play services resolver is importing 'com.google.auto.value.auto-value-annotations-1.6.jar', this is compiled by Java8(1.8). 
but auto value annotation 1.6.3 is compiled by Java7. so, to avoid the error,  use 1.6.3.
e.g. add new dependency file 'FooBarDependencies.xml' and write
`
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.auto.value:auto-value-annotations:1.6.3">
    </androidPackage>
  </androidPackages>
</dependencies>
`
then resolve and build.

**Comment by cynthiajoan** [comment]
Hi @izibazi, would like to double check if your issue has been resolved.

**Comment by izibazi** [comment]
Thank you. My issue has been resolved by upgrade google-play-services plugins.
https://github.com/firebase/quickstart-unity/issues/321#issuecomment-469234259
