### ISSUE TITLE
Unity Android Unable to check Google Play services availablity 

### ISSUE THREAD

**Issue by farzinp7** [firebase/quickstart-unity#322]
Unable to check Google Play services availablity as the com.google.android.gms.common.GoogleApiAvailability class is not present in this application.

UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.4oHf4jn9P6/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.FirebaseApp:LogMessage(LogLevel, String) (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:90)
Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternalSWIG_0()
Firebase.FirebaseApp:CreateInternal() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:976)
Firebase.FirebaseApp:<Create>m0() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:144)
Firebase.FirebaseApp:CreateAndTrack(CreateDelegate, FirebaseApp) (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:537)
Firebase.FirebaseApp:Create() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:144)
Firebase.FirebaseApp:get_DefaultInstance() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:116)
Firebase.FirebaseApp:CheckDependenciesInternal() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:810)
Firebase.<CheckDependencies>cAnonStorey2:<>m0() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:794)
Firebase.FirebaseApp:TranslateDllNotFoundException(Action) (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:98)
Firebase.FirebaseApp:CheckDependencies() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:793)
Firebase.FirebaseApp:<CheckDependenciesAsync>m__2() (at Z:/tmp/tmp.n6hJS53AxW/firebase/app/client/unity/proxy/FirebaseApp.cs:716)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

**Comment by alexames** [comment]
Hi farzinp7

It looks like you might be missing Google Play Services. Did you follow the setup instructions here?

https://firebase.google.com/docs/unity/setup#confirm_google_play_version

**Comment by chkuang-g** [comment]
Hi farzinp7,

Does the suggestion from @alexames fix your problem?

Shawn

**Comment by patm1987** [comment]
Hi @farzinp7 !

Please re-open this bug if you're still experiencing this issue.

--Patrick
