### ISSUE TITLE
#Unable to update database when testing on android device

### ISSUE THREAD

**Issue by kisanzxy** [firebase/quickstart-unity#327]
## Please fill in the following fields:
Unity editor version: 2018.3.1f
Firebase Unity SDK version: 5.5.0
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I'm working on my android game project
when testing on Unity Editor, It can successfully update new score to user-specific path, and the database did update
![image](https://user-images.githubusercontent.com/24818440/53896788-c0301680-4002-11e9-9fa1-d55f0494837d.png)

when build the apk and test on an android devic, it stuck at a certain step.  and fail to update:
![image](https://user-images.githubusercontent.com/24818440/53896867-ebb30100-4002-11e9-9b17-68046bba4a74.png)
it won't go into the task.isComplete block

here is my implementation:
![image](https://user-images.githubusercontent.com/24818440/53896993-35035080-4003-11e9-94f7-fa1e51cbf5cd.png)

public void AddNewScoreToUser() {
        DatabaseReference mDatabaseRef = mDatabase.GetReference("user_Maxscore");
        Dictionary<string, object> entryValues = new Dictionary<string, object>();
        entryValues["score"] = score;
        entryValues["email"] = email;
        entryValues["time"] = System.DateTime.UtcNow.ToString("HH:mm dd MMMM, yyyy");
        Dictionary<string, object> childUpdates = new Dictionary<string, object>();

        Debug.Log(mDatabaseRef.Child(uid));
            mDatabaseRef.Child(uid).GetValueAsync().ContinueWith(task =>
            {
                Debug.Log("continue");
                if (task.IsFaulted)
                {
                    Debug.Log("error get child at user_Maxscore");
                    return;
                }
                else if (task.IsCompleted)
                {
                    snapshot = task.Result;
                    //Debug.Log(snapshot.GetValue(false));
                    Dictionary<string, object> result = snapshot.GetValue(false) as Dictionary<string, object>;
                    Debug.Log(result);
                    if (result == null)
                    {
                        Debug.Log("add New user score");
                        childUpdates[uid] = entryValues;
                        mDatabaseRef.UpdateChildrenAsync(childUpdates);
                    }
                    else
                    {
                        Debug.Log("update user score");
                        long childScore = (long)result["score"];
                        if (childScore < score)
                            mDatabaseRef.Child(uid).Child("score").SetValueAsync(score);
                    }
                }

            });
    }

    TransactionResult AddScoreTransaction(MutableData mutableData)
    {
        List<object> user_scores = mutableData.Value as List<object>;
        if (user_scores == null)
            user_scores = new List<object>();
        else if (mutableData.ChildrenCount >= MaxScores)
        {
            long minScore = long.MaxValue;
            object minVal = null;
            
            foreach (var child in user_scores)
            {
                if (!(child is Dictionary<string, object>))
                    continue;
                long childScore = (long)((Dictionary<string, object>)child)["score"];
                if (childScore < minScore)
                {
                    minScore = childScore;
                    minVal = child;
                }
            }

            if (minScore > score)
            {
                return TransactionResult.Abort();
            }

            user_scores.Remove(minVal);

        }
        Dictionary<string, object> newScoreMap = new Dictionary<string, object>();
        
        newScoreMap["score"] = score;
        newScoreMap["email"] = email;
        newScoreMap["time"] = System.DateTime.UtcNow.ToString("HH:mm dd MMMM, yyyy");
        user_scores.Add(newScoreMap);
        mutableData.Value = user_scores;
        return TransactionResult.Success(mutableData);
    }

    public void AddScore()
    {
        if (score == 0 || string.IsNullOrEmpty(email))
        {
            Debug.Log("invalid score or email.");
            return;
        }
        Debug.LogFormat("Attempting to add score {0} {1}",
          email, score.ToString());

        //DatabaseReference reference = FirebaseDatabase.DefaultInstance.GetReference("scores");
        DatabaseReference reference = mDatabase.GetReference("leaders");
        Debug.Log("Running Transaction...");
        // Use a transaction to ensure that we do not encounter issues with
        // simultaneous updates that otherwise might create more than MaxScores top scores.
        reference.RunTransaction(AddScoreTransaction)
          .ContinueWith(task => {
              if (task.Exception != null)
              {
                  Debug.Log(task.Exception.ToString());
              }
              else if (task.IsCompleted)
              {
                  Debug.Log("Transaction complete.");
              }
          });
    }

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No

**Comment by kisanzxy** [comment]
firebase initialize successfully both on editor and android. and I do check dependency first

**Comment by alexames** [comment]
It's hard to debug this just by looking through the code provided. Can you try creating a minimal, verifiable example of the problem? Simplify your code down to just the bare minimum lines necessary that demonstrate your bug. Hopefully, the issue will become more obvious once you can do that.

**Comment by kisanzxy** [comment]
I tried to narrow down to the minimal bug code. Here is what I found. The problem occurs when I used GetValueAsync() to retrieve data and update value at a specific path. This method works well on Unity Editor but not for an Android device after building the apk. I modified the updating by using RunTransaction(). Like the updating leaderboard example. And it works for both UNity editor and android phone. Does anyone have any ideas about why this happened?

 mDatabaseRef.Child(uid).GetValueAsync().ContinueWith(task =>
        {
            Debug.Log("continue"); // did show this in Logcat
            if (task.IsFaulted)
            {// do something, never reach
            }
            else if (task.IsCompleted)
            {
                 // do something, but never run into this block
            }
});

**Comment by alexames** [comment]
Can you try running this and see what happens?

```
mDatabaseRef.Child(uid).GetValueAsync().ContinueWith(task =>
        {
            Debug.Log("Starting Task");
            Debug.Log(task.IsCompleted);
            Debug.Log(task.IsFaulted);
            Debug.Log(task.IsCanceled);
            Debug.Log(task.Exception);
            Debug.Log("Finishing Task");
});
```

This should let you know what state the task is in when the ContinueWith runs, and if there was an error it should print out. Have you verified in your database rules that you have permission to get or write to the location in the database you're trying to write to?

**Comment by chkuang-g** [comment]
Hi @kisanzxy 
Are you still having the same issue?

**Comment by patm1987** [comment]
Hi @kisanzxy 
Please re-open this if you're still having this issue, and if you have debug output as per @alexames 's sample!

--Patrick
