### ISSUE TITLE
Firebase setup and pods

### ISSUE THREAD

**Issue by mercem** [firebase/quickstart-unity#329]
Unity editor version: 2018.2.0f2
Firebase Unity SDK version: 5.5.0
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

Hi,
I followed this 'https://firebase.google.com/docs/unity/setup' document to setup firebase in unity. It worked as expected but when I decided to change my bundle identifier I removed all the firebase files from unity project and started from scratch. This time it does not generate Pod files and consequently I get linker error in xcode.

**Comment by alexames** [comment]
Can you give me a little more detail on what steps you followed exactly? You removed the firebase files and changed the bundle ID and it no longer generated the pod files - did you add Firebase plugin back in before doing that? Or are you trying to build your app without firebase, it's not quite clear fro your description.

**Comment by chkuang-g** [comment]
Hi @mercem 
Are you still experiencing this issue?  If so, could you provide some more information?

Thank you,

**Comment by mercem** [comment]
Sorry everybody, I completely forgot about this issue. I solved this problem but I really don't remember how.
