### ISSUE TITLE
Firebase Messaging Game Stuck on iOS

### ISSUE THREAD

**Issue by AIGameStudio** [firebase/quickstart-unity#33]
Hi @stewartmiles 

I am using Firebase Messaging SDK in unity app. After the pop up comes to allow notifications the game is totally stuck and i select any of the options the game is completely stuck. Infact its happening for anytime the app goes in background. Here are the last logs which i can see. 

-> applicationWillResignActive()
2016-12-30 15:37:27.326132 pokersquare[27637:1515918] FCM: Connected to FCM
2016-12-30 15:37:27.327797 pokersquare[27637:1515918] You are using download over http. Currently unity adds NSAllowsArbitraryLoads to Info.plist to simplify transition, but it will be removed soon. Please consider updating to https.
FCM: Connected to FCM
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

2016-12-30 15:37:28.684: <FIRInstanceID/WARNING> APNS Environment in profile: development
WARNING -> applicationDidReceiveMemoryWarning()

Please Help. I can see same issue here 
http://stackoverflow.com/questions/41177624/firebase-unity-sdk-100-hang-on-ios-when-the-application-resumes

**Comment by stewartmiles** [comment]
We're investigating this issue at the moment.  We'll keep you posted.

**Comment by AIGameStudio** [comment]
@stewartmiles  any update on by when we can have a fix for it.

**Comment by stewartmiles** [comment]
We're investigating the issue at the moment.  We're hoping very soon.

**Comment by handcircus** [comment]
Experiencing the same issue - started happening once we integrated FCM, now getting a complete freeze and no frame-advancement any time the app is re-opened after leaving (can be for as little as a few seconds).

We're not creating our own App Controller. The only other major component that might be interfering that I can think of is the Facebook SDK.

Obviously would be great to get a fix.

**Comment by tomnewton** [comment]
We're seeing the same. Major issue in that is blocking a release.

**Comment by stewartmiles** [comment]
Yep, we're still working on it.  At the moment we suspect our method
swizzling is causing problems. Will let you know when we have a fix.

**Comment by stewartmiles** [comment]
We found the problem, it's an interesting interaction between the Firebase Analytics App Delegate Proxy class (which swizzles the App Delegate's ISA) and the C++ library's caching of swizzled App Delegate methods.  We have a fix which we're testing now, will update the bug when we have cut a release with the fix.

**Comment by handcircus** [comment]
Hey - great that you've found the problem. Wondered if there's an ETA on a fix? Thanks.

**Comment by stewartmiles** [comment]
We're running through QA right now, worst case a couple of days.

**Comment by jonsimantov** [comment]
We have released version 1.1.1 of the Firebase Unity SDK, which fixes this issue. You can view the [release notes](https://firebase.google.com/support/release-notes/unity) and download the new version from http://firebase.google.com/docs/unity/setup.

**Comment by JangT** [comment]
I am using the Firebase Unity SDK.
Topic works well for AOS but not for iOS Topic.
In iOS, if send a bundle, you will receive a notification. If send it to Topic, it will not be received.

Can not subscribe to topic: / topics / *** with token: (null)
like this

Firebase-unity version : 3.0.1
Unity version : 5.5.1f

**Comment by stewartmiles** [comment]
@JangT are you able to reproduce this problem with the sample application?  Also, which iOS version are you targeting?

I just tried this out with Xcode 8, Firebase Unity 3.0.1 and Unity 5.6.0b11 and everything works fine (Unity version in this case really shouldn't matter since the meat of the code is all Obj-C / C++).

**Comment by JangT** [comment]
@stewartmiles 
I used the iOS 9.x version. And this issue happens every time.

**Comment by stewartmiles** [comment]
@JangT to confirm you used the sample application?

Also, did you run through the sample application setup instructions (see https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/readme.md)?Specifically you need to enable push notifications and remote notifications.
