### ISSUE TITLE
Bug in unsubscribe method

### ISSUE THREAD

**Issue by Temka193** [firebase/quickstart-unity#331]
In Unsubscribe method used "Subscribe" realisation.
![image](https://user-images.githubusercontent.com/11135702/54345158-88088380-4653-11e9-815f-3e0cc0a152fc.png)

**Comment by alexames** [comment]
This issue is fixed as of the 5.6.0 release, though it looks like it wasn't mentioned in the patch notes. Sorry for that, that was an oversight on my part.
