### ISSUE TITLE
Bug with Firebase 5.6.0

### ISSUE THREAD

**Issue by BielBG** [firebase/quickstart-unity#333]
## Please fill in the following fields:
Unity editor version: 2018.3.9
Unity Scripting Runtime Version: .NET 4.x Equivalent
Firebase Unity SDK version: 5.6.0 (from the dotNet4 folder)
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, GoogleSignIn (https://github.com/googlesamples/google-signin-unity/releases)
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Firebase Services used: Analytics, Auth, Realtime Database, Storage and Messaging
XCode version: 10.1 (10B61)
Cocoapods version: 1.6.1
Podfile:
------------------------------------------------------
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :integrate_targets => false
platform :ios, '9.0'

target 'Unity-iPhone' do
pod 'Firebase/Analytics', '5.18.0'
pod 'Firebase/Auth', '5.18.0'
pod 'Firebase/Core', '5.18.0'
pod 'Firebase/Database', '5.18.0'
pod 'Firebase/Messaging', '5.18.0'
pod 'Firebase/Storage', '5.18.0'
pod 'GoogleSignIn', '>= 4.0.2'
end
-----------------------------------------------------

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
1.- Build the project.
2.- Open it XCode.
3.- Analyze
4.- Error pops

ERROR: 
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GKLocalPlayer", referenced from:
      objc-class-ref in libFirebaseCppAuth.a(credential_ios_e00102e1d7b7fbda5ca81044db487adf.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

SOLUTION:
Adding GameKit.framework in Unity-iPhone (Target) -> General -> Linked Frameworks and Libraries.

I'm just saying this so you can fix the missing framework reference from whatever it is supposed to be added, because it is missing. This (I ASSUME) happened with the newest feature addition in Firebase SDK 5.6.0: Added Game Center authentication (https://firebase.google.com/support/release-notes/unity), which, again, I assume that makes a reference to the GameKit framework in some part of the code, but it has not been added I guess.

Could you confirm that?

Thanks!

**Comment by ryanmeier** [comment]
Thanks for the report!  That does sound like it's likely related to the Game Center integration added in the 5.6.0 version of the SDK.  Would you be willing to provide a bit more information to help us track down this issue:
- Do you encounter the same error when building the [Unity Auth Quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) project?
- If not, is the project in which you're seeing this error using any Game Center/Game Kit functionality (Firebase or otherwise)?

**Comment by patm1987** [comment]
Hi @BielBG 
Let us know if you're still experiencing the bug and if you have any information to follow up with @ryanmeier 

Thanks,
--Patrick
