### ISSUE TITLE
Unable to download thumbnails from bucket

### ISSUE THREAD

**Issue by barleymalt** [firebase/quickstart-unity#334]
## Specs:
```
Unity editor version: 2018.2.8f1
Firebase Unity SDK version: 5.5.0
Additional SDKs: SimpleFirebaseUnity
Developing on: Mac
Export Platform: Android
```

## Issue

I'm having troubles setting up a system to download pictures from storage. I'm not an expert in databases, but I wanted to give it try, just to learn how it is done. I found Firebase very useful to store metadata on the real-time database and easy to approach even for an entry level programmer like me.

The problem is that I'm trying to download a .png file from a folder in storage, but I can't manage to find if the file is actually downloaded or if it's just lost in the process. I don't get any errors in the console, but when I open the folder in which the files should be, it's empty.

Thanks
Filippo

## Code
Here's my code:

```csharp
    private SimpleFirebaseUnity.Firebase firebaseDatabase;
    private FirebaseQueue firebaseQueue;
    private FirebaseStorage firebaseStorage;
    private StorageReference m_storage_ref;

    // Setup refernece to database and storage
    void SetupReferences()
    {
        // Get a reference to the database service, using SimpleFirebase plugin
        firebaseDatabase = SimpleFirebaseUnity.Firebase.CreateNew(FIREBASE_LINK, FIREBASE_SECRET);

        // Get a reference to the storage service, using the default Firebase App
        firebaseStorage = FirebaseStorage.DefaultInstance;

        // Create a storage reference from our storage service
        m_storage_ref = firebaseStorage.GetReferenceFromUrl(STORAGE_LINK);

        // Create a queue, using SimpleFirebase
        firebaseQueue = new FirebaseQueue(true, 3, 1f);
    }

// ...

    IEnumerator DownloadImage(string address, string fileName)
    {
        var local_path = Application.persistentDataPath + THUMBNAILS_PATH;
        var content_ref = m_storage_ref.Child(THUMBNAILS_PATH + fileName + ".png");

        content_ref.GetFileAsync(local_path).ContinueWith(task => {
            if (!task.IsFaulted && !task.IsCanceled)
            {
                Debug.Log("File downloaded.");
            }
        });
        
        yield return null;
    }

**Comment by alexames** [comment]
Just to be sure it's not something silly, have you verified that the files have been uploaded to Firebase Storage, and that the permissions are set up so that you have access to the file? I believe you would get an error if one of those were the issue, but it's good to double check. 

Have you double checked that it's going into the directory you expect it to? Can you try using [GetBytesAsync](https://firebase.google.com/docs/storage/unity/download-files#download_to_a_byte_array) to see if you can get the file to load into memory?

**Comment by barleymalt** [comment]
> Just to be sure it's not something silly, have you verified that the files have been uploaded to Firebase Storage, and that the permissions are set up so that you have access to the file? I believe you would get an error if one of those were the issue, but it's good to double check.

Thanks for the reply. I've checked and, yes, the files are uploaded on the storage correctly.
About the rules this is how I set them:

```
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write;
    }
  }
}
```

> 
> Have you double checked that it's going into the directory you expect it to? Can you try using [GetBytesAsync](https://firebase.google.com/docs/storage/unity/download-files#download_to_a_byte_array) to see if you can get the file to load into memory?

I tried like you said and it seems like the path is working, since _Debug.Log(fileContents.Length);_ returns a number higher than zero (but perhaps I'm mistaken and it's not actually downloading the right file).
If this is the case, it could be a solution to the problem, so now I'm trying to figure out how to translate the bytes into a texture, but the instructions coming after _GetBytesAsync_, inside the coroutine, are not being executed.

```c#
        const long maxAllowedSize = 1 * 1024 * 1024;
        byte[] fileContents = new byte[0];

        content_ref.GetBytesAsync(maxAllowedSize).ContinueWith((Task<byte[]> task) => {
            if (task.IsFaulted || task.IsCanceled)
            {
                Debug.Log(task.Exception.ToString());
                // Uh-oh, an error occurred!
            }
            else
            {
                fileContents = task.Result;

                Debug.Log(fileContents.Length);
                Debug.Log("Finished downloading!");
            }
        });

        if (fileContents.Length > 0)
        {
            ConvertByteToTexture(fileContents);
            print(fileContents);
        }

        yield return null;

**Comment by chkuang-g** [comment]
Hi @barleymalt 
Using GetBytesAsync() seems to fix your problem.  My guess is that you did not have permission to write to local_path.  You can find more info online about how to save a file to Android device.

About converting bytes to texture, here is a quick search result for you.  Might work for your case.
https://docs.unity3d.com/ScriptReference/Texture2D.LoadRawTextureData.html
