### ISSUE TITLE
Firebase Auth Problem

### ISSUE THREAD

**Issue by johnnyboiii3020** [firebase/quickstart-unity#339]
## Please fill in the following fields:
Unity editor version: latest
Firebase Unity SDK version: latest
Additional SDKs you are using (Facebook, AdMob, etc.): Email and password
Platform you are using the Unity editor on (Mac, Windows, or Linux): windows
Platform you are targeting (iOS, Android, and/or desktop): android

## Please describe the issue here:
```Auth object 0x47ab7fe0 should be deleted before the App 0x6b755810 it depends upon.
UnityEngine.Debug:LogWarning(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.ZuzGwZSFEs/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:16)
Firebase.FirebaseApp:LogMessage(LogLevel, String) (at Z:/tmp/tmp.AKg9cuw0I4/firebase/app/client/unity/proxy/FirebaseApp.cs:93)
Firebase.AppUtilPINVOKE:FirebaseApp_ReleaseReferenceInternal()
Firebase.FirebaseApp:ReleaseReferenceInternal(FirebaseApp) (at Z:/tmp/tmp.AKg9cuw0I4/firebase/app/client/unity/proxy/FirebaseApp.cs:1000)
Firebase.FirebaseApp:RemoveReference() (at Z:/tmp/tmp.AKg9cuw0I4/firebase/app/client/unity/proxy/FirebaseApp.cs:296)
Firebase.FirebaseApp:Dispose() (at Z:/tmp/tmp.AKg9cuw0I4/firebase/app/client/unity/proxy/FirebaseApp.cs:51)
Firebase.FirebaseApp:Finalize() (at Z:/tmp/tmp.AKg9cuw0I4/firebase/app/client/unity/proxy/FirebaseApp.cs:47)
```
## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

**Comment by johnnyboiii3020** [comment]
I really need help here plss tell me how to solve this issue

**Comment by chkuang-g** [comment]
Hi @johnnyboiii3020 

The warning in your original title (Auth object 0x47ab7fe0 should be deleted before the App) is normal. 
This is due to that C# GC can finalize any object in any order and from any thread.
Second thought, we probably should make it as a debug log.

About the stack trace in your edited post, is it a crash or just for the warning log?

Please let us know.  Thank you.

**Comment by patm1987** [comment]
Hi @johnnyboiii3020 , please let us know if this is still an issue.

--Patrick
