### ISSUE TITLE
Unity firebase messaging crashes

### ISSUE THREAD

**Issue by mostafaashraf92** [firebase/quickstart-unity#34]
Hi everyone,
I used quick master example included in FCM docs as an example and i initialized FCM properly but when i build and run on android it crashes.Thanks

**Comment by stewartmiles** [comment]
What is the crash that you see?  Could you share some logs?

**Comment by stewartmiles** [comment]
We've reproduced a crash on iOS 10 and think we have a fix.  We'll be cutting a release soon and will keep you posted.

**Comment by stewartmiles** [comment]
This should be resolved in version 1.1.1
https://firebase.google.com/support/release-notes/unity#1.1.1
