### ISSUE TITLE
GameCenter LinkWithCredentialAsync

### ISSUE THREAD

**Issue by MichaelPageArtrix** [firebase/quickstart-unity#344]
## Please fill in the following fields:
Unity editor version: 2018.3.8
Firebase Unity SDK version: 5.6.0
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, GoogleSignIn, GooglePlayServices
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

If you try to link a GameCenter account when that GameCenter account is already in use by another firebase account, the error returned is AuthError.Failure (1). 

In other instances this would result in the error AuthError.CredentialAlreadyInUse(10).

Is this the intended behaviour / error code ? because it makes handling this case somewhat difficult.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes it always happens.

**Comment by chkuang-g** [comment]
@MichaelPageArtrix 
This does not sound right.

To help us identify the problem sooner, I'd like to learn more about this inconsistent behavior.
- By different instance, you mean different devices or different link attempts on the same device?
- When you stated "Yes it always happens." with Firebase Unity quickstarts, does it always response with one or another AuthError with no specific pattern?
- Are you trying to link the same GameCenter account, or different GameCenter accounts?
- Please provide more information about those instances.

Thank you.

**Comment by MichaelPageArtrix** [comment]
Hi,

By different instances I mean different providers so if you link a set of Google credentials to an account and then try to link those same credentials to another account, you get the error 
AuthError.CredentialAlreadyInUse(10).

When I try to link the game center credentials to an account, if those credentials are linked to another account it **always** returns AuthError.Failure (1).

I was trying to link a set of game center credentials to an account but those credentials were in use by another account and it returned the error noted. So basically my flow is,

* start game.
* create account A.
* link game center account Bob to this account A.
* successful link.
* exit game.
* create a new account B.
* try to link game center account Bob to this account B.
* receive error AuthError.Failure (1) not AuthError.CredentialAlreadyInUse(10).

**Comment by ryanmeier** [comment]
@MichaelPageArtrix 
It looks like this issue should be fixed on the backend, so if you try again you should be receiving the CredentialAlreadyInUse error.  Feel free to let us know if you run into any more issues.
