### ISSUE TITLE
Firebase works in Unity Editor not on Device / APK build

### ISSUE THREAD

**Issue by acoale** [firebase/quickstart-unity#345]
## Please fill in the following fields:
Unity editor version: **2018.3.11f1**
Firebase Unity SDK version: **5.4.4**
Additional SDKs you are using (Facebook, AdMob, etc.): **N/A**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows**
Platform you are targeting (iOS, Android, and/or desktop): **Android**

## Please describe the issue here:
Using the Firebase Auth and Realtime Database. I am able to send data via the Unity Editor, but when I create the build to test it on a device and click the Register Button, it doesn't create a new user. 

Everything is a fresh install. I haven't moved any files.

**Comment by chkuang-g** [comment]
@acoale 
Are you able to reproduce this with Auth quickstart?
https://github.com/firebase/quickstart-unity/tree/master/auth/testapp

Also, you can use view the log on your Android device using the following command.
  adb logcat
The log may show you more information about the problem.

**Comment by acoale** [comment]
So I resolved the issue on my own, I need better debugging messages. I feel stupid. 

Here have a good laugh...
04-04 15:17:07.044 32047 32073 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
04-04 15:17:07.044 32047 32073 I Unity   :
04-04 15:17:07.335 32047 32073 E Unity   : CreateUserWithEmailAndPasswordAsync encountered an error: System.AggregateException: Exception of type 'System.AggregateException' was thrown.
04-04 15:17:07.335 32047 32073 E Unity   : -----------------
04-04 15:17:07.335 32047 32073 E Unity   : Firebase.FirebaseException: The email address is badly formatted.
04-04 15:17:07.335 32047 32073 E Unity   :
04-04 15:17:07.335 32047 32073 E Unity   :
04-04 15:17:07.335 32047 32073 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

**Comment by chkuang-g** [comment]
No problem.  Glad it is resolved!
