### ISSUE TITLE
Unable to find FirebaseCppApp

### ISSUE THREAD

**Issue by zackloveyezi** [firebase/quickstart-unity#346]
04-12 13:49:02.424: E/Unity(17502): Unable to find FirebaseCppApp-5.6.1
04-12 13:49:02.544: E/Unity(17502): DllNotFoundException: FirebaseCppApp-5.6.1
04-12 13:49:02.544: E/Unity(17502):   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)

**Comment by zackloveyezi** [comment]
I have already been solved
I went back into unity, ran the PlayServicesResolver tools which fixed most of my issues
unity——Assets——PlayServicesResolve——androidResolve——resolves

**Comment by cynthiajoan** [comment]
Hi @zackloveyezi, 
Glad to learn you already figured it out. In this case I will close the issue for now, if you have follow up problems, feel free to reopen it and add.
