### ISSUE TITLE
FCM: Disconnect FCM Service

### ISSUE THREAD

**Issue by TonyaGitHub** [firebase/quickstart-unity#347]
## Please fill in the following fields:
Unity editor version: 2018.3.11
Firebase Unity SDK version: 5.6.1 (latest)
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, Database, Storage & Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Google SignIn Plugin (https://github.com/googlesamples/google-signin-unity)
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
We successfully initializated the FCM service with a token and subscribed to a topic to recieve notifications. It worked when the app was opened and in the screen, but when we pressed the home button on the ios device (app opened, but in background), the XCode logs showed that the FCM service disconnected. We tried to send a notification and it didn't recieve it. When we pressed the icon app again and opened it, the FCM service started again and recieved the message it was meant to recieve, logs here:

(WE PRESS THE HOME BUTTON ON THE IPAD)
> applicationWillResignActive()
-> applicationDidEnterBackground()
2019-04-12 17:37:37.630200+0200 iOSUnPuzzle[353:22292] FCM: Disconnect FCM service
FCM: Disconnect FCM service
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

(WE PRESS THE APP ICON TO OPEN IT)
2019-04-12 17:37:37.942058+0200 iOSUnPuzzle[353:22292] Cannot snapshot view (<UIKeyboardImpl: 0x16dc0600; frame = (0 0; 768 313); layer = <CALayer: 0x4256a660>>) with afterScreenUpdates:NO, because the view is not in a window. Use afterScreenUpdates:YES.
-> applicationWillEnterForeground()
2019-04-12 17:38:32.158606+0200 iOSUnPuzzle[353:22292] FCM: Connected to FCM
FCM: Connected to FCM
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

-> applicationDidBecomeActive()
2019-04-12 17:38:32.622785+0200 iOSUnPuzzle[353:22292] FCM: Received message
FCM: Received message
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)

Any idea of what could be happening? Thanks

**Comment by cynthiajoan** [comment]
Hi @TonyaGitHub, you can refer to this [doc](https://firebase.google.com/docs/cloud-messaging/unity/client#enable_push_notifications) to enable push notification on iOS when app is in background.

**Comment by TonyaGitHub** [comment]
We already did all the steps mentioned in the document, we have been doing for over a year, and the remote notifications is enabled. That's why I post this here, because it appears to be a bug, something that is meant to work, doesn't.

**Comment by ryanmeier** [comment]
Hi @TonyaGitHub!  Sorry to hear that you're running into issues with FCM.  To help us track down the problem - could you try to reproduce the issue using the Messaging testapp (https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) and let us know what happens?

**Comment by legendbone** [comment]
Same problem! I run the testapp only with the bundle id and firebase config file changed to my project.I do all the step the doc tells. It works well on android,but not work on ios. I received the token, but can't receive message in background. When I back to the app, I receive the message. Unity version:2018.2.19f1

**Comment by TonyaGitHub** [comment]
@ryanmeier Just now I tried to build the sample app, and it throws an error in XCode when trying to run the app on an iPad.
The error is the following:
**ld: Assertion failed: (memberIndex != 0), function makeObjectFileForMember, file /Library/Caches/com.apple.xbs/Sources/ld64_Fall2018/ld64-409.12/src/ld/parsers/archive_file.cpp, line 383.
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Note that I upgraded the Unity version to 2018.3.11 (our project version aswell) and added the Firebase 5.6.1 packages (dotNet4).

**Comment by ryanmeier** [comment]
Thanks for the additional information @TonyaGitHub  and @legendbone - we'll take a look and see if we can figure out what's causing the issues you're seeing.

**Comment by TonyaGitHub** [comment]
Ah, @ryanmeier , another thing is that inside the Unity Editor, it couldn't start Firebase because it was also looking for google-services.json file (which is needed for Android, and we are building for iOS). After creating "StreamingAssets" folder and putting there both google-services.json & GoogleService-Info.plist, it finally worked in the Unity Editor.

The error was this one:

**Unable to load options for default app ([/Users/.../ Coding AR Demo/Assets/StreamingAssets/google-services-desktop.json, /Users/.../Assets/StreamingAssets/google-services.json] are missing or malformed)

Firebase app creation failed. Firebase.FirebaseApp.CreateAndTrack (Firebase.CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) Firebase.FirebaseApp.Create ()**

**Comment by ryanmeier** [comment]
Interesting.  Out of curiosity - did you have the build platform set to iOS (in File -> Build Settings), and if so - was that set before or after you added your GoogleService-Info.plist file to the project?

Also - does this mean you've been able to successfully build the FCM test app and run it on device?  
If so - are you seeing the same issues with not receiving messages in the background?

**Comment by TonyaGitHub** [comment]
The iOS platform was set from the start, when opening the project with Unity Hub (it allows you to select which Target Platform you want).

No, what I've been able to do is to press Play on Unity Editor and that it throws no errors. I then do Build and open the project in XCode. There, I try to Run on an iPad, and the error that I've specified before (trying to run the testapp) is thrown. I've not been able to build it to a device.

**Comment by ryanmeier** [comment]
Thanks for the clarifications!  I'm pretty sure the editor issue you were seeing is a result of a known issue with those files not getting generated in some cases based on the target build platform (which we should hopefully have a fix for in the next few weeks).

As for the FCM issue - we'll continue to look into it and update you here when we have more information.

**Comment by ryanmeier** [comment]
@TonyaGitHub 

When you saw the above error while trying to build for iPad - were you building from the Unity-iPhone **.xcworkspace** file?  

The build folder that Unity produces should contain both a **.xcodeproj** file and a **.xcworkspace** file - if you try to build from the **.xcodeproj** file directly, it isn't able to access the libraries via the Podfiles, which will cause errors like the ones you're seeing.

**Comment by TonyaGitHub** [comment]
I am building from Unity-iPhone.xcodeproj. Sorry to disagree with you, but you are not right: 

![asd](https://user-images.githubusercontent.com/46561817/56579020-57f7bd00-65cf-11e9-8f91-17ff7ccc21f2.png)

As you can see, in Assets -> Play Services Resolver -> iOS Resolver -> Settings, this Window appears, and it lets you specify if the libraries contained in the Pods (or specified in the Podfile) are integrated on workspace or project. 
When we started our app development more than 1 year ago and integrated Firebase, we tested both options, and the .xcworkspace ALWAYS threw a lot of errors that we couldn't solve, and since the start we use the option to integrate with .xcodeproj and encountered no errors.

Also, the Firebase Quickstart TestApp came with this configuration aswell (with "XCode project" option selected).

**Comment by patm1987** [comment]
Hi @TonyaGitHub,

I'm so sorry that you're having these issues. I did note that even in the 5.7.0 SDK, there seem to be some issues "Xcode Project."

"Xcode Workspace" should work though. As I reach out for more information, would you mind trying out "Xcode Workspace" and letting us know what issues you run into as well?

--Patrick

**Comment by TonyaGitHub** [comment]
Alright, I will try to integrate with workspace, aswell as upgrading Firebase SDK from 5.6.1 to 5.7.0.

Whenever I have the results I will post it here.

**Comment by TonyaGitHub** [comment]
Hello, I have switched to .workspace instead of .xcproj. 
First, I was able to run the TestApp on a device, and it worked. Then I did the same for our app, and it worked aswell. 
So, from now on, I will be integrating & building with workspace instead of project. Thank you so much for your feedback & answers!

Note: Why is there the possibility to chose between workspace/project? What's the difference?

**Comment by stewartmiles** [comment]
Folks I just took a look at this issue and verified that when the app is in the background even when building with the Xcode project integration a notification is received correctly and displayed as a system notification if the "Push Notifications" capability is enabled and the user accepts push notifications from the application.

@TonyaGitHub we have the option of Xcode project vs. Xcode workspace integration to support Unity < 5.5 where it doesn't open up Xcode workspaces if they're present.  Also, some folks prefer everything integrated into a project rather than the workspace.

**Comment by djock** [comment]
Hello.
I still have this issue on Unity 2018.4.0 and firebase messaging 5.7.0.
I've tried building with **.xcworkspace**  and **.xcodeproj** but the same result: FCM: Disconnect FCM service.

The error from the server: `messaging/registration-token-not-registered` 
The weird thing is that with the same xcode build on an iPhone 7 - iOS 12.2 it worked and on an iPhone 6 - iOS 12.1 it did not work.
