### ISSUE TITLE
[bug report] UpdateAsync don't fire any callback at sometimes.

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#350]
using firebase_unity_sdk_5.4.0

if UpdateAsync function called many times at small term, it doesn't fire any callback.

if Unity API function called at this time, the app is crashing.
I think it is the cause of UpdateAsync's tread is not the main thread.

**Comment by patm1987** [comment]
Hi @green4you, thanks for reporting an issue!

For the first bug, can I have you verify two things?
1) sometimes tasks may fail silently if an exception occurs off the main thread. Try wrapping the body of your ContinueWith with `try{}catch(Exception e){}` to see if you get anything in there.
2) if you're still failing and there's no exception being logged, can you update to the [latest Firebase SDK (right now 5.7.0)](https://firebase.google.com/support/release-notes/unity) and verify that you're still experiencing the issue?
If the problem persists, it would help me a ton to know:
which Firebase products you're using (I assume Realtime Database)
what version of Unity you're building for
your target platforms (iOS/Android/both)
which scripting backend you're using (IL2CPP or mono)
instructions on reproducing your issue on one of our quickstart projects

For the main thread issue: Unity 4.6's implementation of Task doesn't give us much control over which worker thread your logic executes on. You can work around this in a number of ways:
1) switching to .NET 3.5 will cause you to use a Task implementation that always dispatches on the main thread.
2) If you want compatibility between .NET 3.5 and 4.6, you can queue up [actions](https://docs.microsoft.com/en-us/dotnet/api/system.action-1?view=netframework-4.8) to occur on the main thread via a MonoBehaviour's update loop. I would recommend looking at [this implementation](https://github.com/firebase/quickstart-unity/issues/261#issuecomment-443896396).
3) [ContinueWith](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.continuewith?view=netframework-4.7.2#System_Threading_Tasks_Task_ContinueWith_System_Action_System_Threading_Tasks_Task_System_Object__System_Object_System_Threading_Tasks_TaskScheduler_) can take a TaskScheduler. If you're wholly on board with .NET 4.6, you can call [TaskScheduler.FromCurrentSynchronizationContext](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.fromcurrentsynchronizationcontext?view=netframework-4.7.2) to pass in your current context.

Please let me know if these help at all, and thanks again for taking the time to help us out!
--Patrick

**Comment by green4you** [comment]
> Hi @green4you, thanks for reporting an issue!
> 
> For the first bug, can I have you verify two things?
> 
> 1. sometimes tasks may fail silently if an exception occurs off the main thread. Try wrapping the body of your ContinueWith with `try{}catch(Exception e){}` to see if you get anything in there.
> 2. if you're still failing and there's no exception being logged, can you update to the [latest Firebase SDK (right now 5.7.0)](https://firebase.google.com/support/release-notes/unity) and verify that you're still experiencing the issue?
>    If the problem persists, it would help me a ton to know:
>    which Firebase products you're using (I assume Realtime Database)
>    what version of Unity you're building for
>    your target platforms (iOS/Android/both)
>    which scripting backend you're using (IL2CPP or mono)
>    instructions on reproducing your issue on one of our quickstart projects
> 
> For the main thread issue: Unity 4.6's implementation of Task doesn't give us much control over which worker thread your logic executes on. You can work around this in a number of ways:
> 
> 1. switching to .NET 3.5 will cause you to use a Task implementation that always dispatches on the main thread.
> 2. If you want compatibility between .NET 3.5 and 4.6, you can queue up [actions](https://docs.microsoft.com/en-us/dotnet/api/system.action-1?view=netframework-4.8) to occur on the main thread via a MonoBehaviour's update loop. I would recommend looking at [this implementation](https://github.com/firebase/quickstart-unity/issues/261#issuecomment-443896396).
> 3. [ContinueWith](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.continuewith?view=netframework-4.7.2#System_Threading_Tasks_Task_ContinueWith_System_Action_System_Threading_Tasks_Task_System_Object__System_Object_System_Threading_Tasks_TaskScheduler_) can take a TaskScheduler. If you're wholly on board with .NET 4.6, you can call [TaskScheduler.FromCurrentSynchronizationContext](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.fromcurrentsynchronizationcontext?view=netframework-4.7.2) to pass in your current context.
> 
> Please let me know if these help at all, and thanks again for taking the time to help us out!
> --Patrick

Thank you!
I'm checking this link in ur answer.
https://github.com/firebase/quickstart-unity/issues/261#issuecomment-443896396

I'm using .NET 3.5 plugin, and my unity setting is also using .NET 3.5
Can I use that implementation on my .NET 3.5 setting?

**Comment by patm1987** [comment]
Absolutely!
The trick is that you're just throwing Actions into a queue that's serviced in some MonoBehaviour's Update loop, so it's just like any other function you'd call there.

**Comment by stewartmiles** [comment]
@green4you did @patm1987 solve your problem(s)?

**Comment by green4you** [comment]
I'm testing now, but all trying has failed(nothing changed before update firebase SDK).

**Comment by green4you** [comment]
@patm1987

**Comment by green4you** [comment]
@patm1987 
I can't solve this issue, so sharing my state.

-Unity Version
Unity 2018.2.10f1 (64-bit)
- Resolver
play-services-resolver-1.2.95.0
- Firebase SDK
firebase_unity_sdk_5.4.0
or
firebase_unity_sdk_5.7.0

code sample
``RunOnMainThread(() =>
            {
                
                Dictionary<string, object> dicDataToUpload = new Dictionary<string, object>();
                for (int i = 0; i < _pathAndValueListToUpload.Count; ++i)
                {
                    
                    string path = _pathAndValueListToUpload[i].path_;
                    object value = _pathAndValueListToUpload[i].value_;
                    dicDataToUpload[path] = value;
                    Debug.LogWarningFormat("UpdateChildrenAsync() - index : {0}, path : {1}, value : {2}", i, path, value.ToString());
                }
                          
                
                Debug.LogWarningFormat("UpdateChildrenAsync() - call Firebase rootReference.UpdateChildrenAsync()");
                GoOnline();
               
                DatabaseReference rootReference = FirebaseDatabase.DefaultInstance.RootReference;
                rootReference.UpdateChildrenAsync(dicDataToUpload).ContinueWith(task =>
                {
                    
                    RunOnMainThread(() =>
                    {
                        GoOffline();
                        if (task.Exception != null)
                        {
                            Debug.Log("task.Exception");
                        }
                        else
                        {
                            
                            FirebaseDBResult result = FirebaseDBResult.None;
                            try
                            {
                                if (task.IsFaulted)
                                {
                                    Debug.LogWarningFormat("<color=red>UpdateChildrenAsync - IsFaulted : {0}</color>", task.Exception.ToString());
                                    result = FirebaseDBResult.Faulted;
                                }
                                else if (task.IsCanceled)
                                {
                                    Debug.LogWarningFormat("<color=red>UpdateChildrenAsync - IsCanceled : {0}</color>", task.Exception.ToString());
                                    result = FirebaseDBResult.Canceld;
                                }
                                else if (task.IsCompleted)
                                {
                                    Debug.LogWarningFormat("<color=red>UpdateChildrenAsync - IsCompleted</color>");
                                    result = FirebaseDBResult.Completed;
                                }
                            }
                            catch
                            {
                            }
                            _onEnd(result);
                        }
                    });
                });
            });``

**Comment by green4you** [comment]
I found another issue on testing with firebase_unity_sdk_5.7.0

firebase_unity_sdk_5.4.0 didn't heat device. 
but firebase_unity_sdk_5.7.0 did even if i didn't use firebase database.

**Comment by chkuang-g** [comment]
@green4you 

It's been awhile.  I wonder if [later version of Firebase SDK](https://firebase.google.com/download/unity) resolve your issue.  If not, I wonder if you see any exception thrown in the log.

I also saw you were using RunOnMainThread() to forward continuation function to main thread.  I would recommend you to try-catch your `myDispatcher_.PollJobs();` as well since the exception can be thrown over there.

Also, we just introduce an extension method Task.ContinueWithOnMainThread().  This can handler the exception thrown during continuation function a bit better.
https://firebase.google.com/docs/reference/unity/class/firebase/extensions/task-extension
(Tip: you should add `using Firebase.Extensions;` to enable these extension methods)

It is a bit hard to reproduce this from our end.  If possible, could you try to reproduce this using [Unity quickstart](https://github.com/firebase/quickstart-unity/tree/master/database/testapp)?

Thank you

**Comment by stewartmiles** [comment]
Hi @green4you I just spent some time reassembling your code snippet http://colorscripter.com/s/YWQcrcp into our database sample and tried it out on macOS, iOS & Android in all cases I'm able to hammer the problematic method with no problems at all.

Since we haven't heard from you with a minimal reproducible case that uses our database sample I'm going to assume that this is something broken in your application.  Let us know if you can come up with a reproducible case and we'll take a look.

**Comment by Thomas-6freedom** [comment]
Thank you for the "ContinueWithOnMainThread" with using Firebase.Extensions; !!! 
It saved me !!
