### ISSUE TITLE
libFirebaseCppApp-5.com::google::firebase::messaging::cpp::SerializedEvent::event_type() const

### ISSUE THREAD

**Issue by HeeChangJung** [firebase/quickstart-unity#351]
## Please fill in the following fields:
Unity editor version: 5.6.4p2
Firebase Unity SDK version: 5.2.1
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Messaging, RemoteConfig
Additional SDKs you are using (Facebook, AdMob, etc.): Admob, Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android and iOS

## Please describe the issue here:
Here is our stacktrace. I'm sorry for that I couldn't reproduce. I already did insert code about check CheckAndFixDependenciesAsync before using firebase module.

Fatal Exception: java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 19a9022f
Build fingerprint: 'samsung/goyave3gub/goyave3gsea:4.4.4/KTU84P/T116BUUBU0ARE1:user/release-keys'
Revision: '4'
pid: 2134, tid: 2899, name: GC_start_routin  >>> com.bitmango.go.lollipopmatch3 <<<
    r0 72fe6c9c  r1 19a9022f  r2 00000000  r3 75554aa4
    r4 72fe6c9c  r5 400b6e34  r6 75554b38  r7 72fe6be0
    r8 75554b19  r9 000000a7  sl 74d28790  fp 72fe6c08
    ip 0b534001  sp 75554ab0  lr 74c6aa45  pc 74c6ba56  cpsr 55544b2f

       at libFirebaseCppApp-5.com::google::firebase::messaging::cpp::SerializedEvent::event_type() const(libFirebaseCppApp-5.java:3)
       at libFirebaseCppApp-5.firebase::messaging::ProcessMessages()(libFirebaseCppApp-5.java:1660)
       at libFirebaseCppApp-5.firebase::messaging::MessageProcessingThread(void*)(libFirebaseCppApp-5.java:124)
       at libc.__thread_entry(libc.java:72)
       at libc.pthread_create(libc.java:240)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? I could no. Sorry.

**Comment by stewartmiles** [comment]
Hi @HeeChangJung this was fixed in Unity SDK `5.6.0` (see https://github.com/firebase/quickstart-unity/issues/294 ).  There was a bug where it was possible for a corrupted message cache file to cause the application to segfault when it starts up.  Please give `5.6.0` or newer a try and please reopen if this is still an issue.
