### ISSUE TITLE
Firebase Cloud Messaging - Open a link instead of app from push notification in Unity

### ISSUE THREAD

**Issue by emaadgh** [firebase/quickstart-unity#353]
I'm using FireBase Cloud Messaging in Unity. I want to just open a link when the user clicks on the arrived message from FireBase Cloud Messaging.

In Firebase panel I set custom data "click_action" with a URL value to message, and I receive it when clicking on the notification in OnMessageReceived method like :

`public void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e)
{}`

When I add following line: 

`Application.OpenURL(e.Message.Data["click_action"]);`

in OnMessageReceived, then try to test the push notification and click on the arrived message, the main Scene of the application will be open and then it calls the link to be open.

How can open a link instead of the app from a push notification in Unity?

I know it can be done in Android native by ACTION_VIEW intent, is there any way to make it work in Unity projects that uses Firebase Unity plugin?

Thanks.

**Comment by stewartmiles** [comment]
You can customize how messages are handled and rendered as a notification by replacing the default message listener service.

I know the docs aren't clear here but the Android & C++ SDKs are used by the Unity SDK.  The C++ SDK implements a default message listener service that can be overriden using the instructions here https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android .  You'll need to implement your own service to display a custom notification. From the custom notification you can customize the action (e.g start activity) https://developer.android.com/training/notify-user/navigation

**Comment by saeedaliakbari** [comment]
> I'm using FireBase Cloud Messaging in Unity. I want to just open a link when the user clicks on the arrived message from FireBase Cloud Messaging.
> 
> In Firebase panel I set custom data "click_action" with a URL value to message, and I receive it when clicking on the notification in OnMessageReceived method like :
> 
> `public void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e) {}`
> 
> When I add following line:
> 
> `Application.OpenURL(e.Message.Data["click_action"]);`
> 
> in OnMessageReceived, then try to test the push notification and click on the arrived message, the main Scene of the application will be open and then it calls the link to be open.
> 
> How can open a link instead of the app from a push notification in Unity?
> 
> I know it can be done in Android native by ACTION_VIEW intent, is there any way to make it work in Unity projects that uses Firebase Unity plugin?
> 
> Thanks.

hello , are you solve this ?! please help me 
email: saliakbari6603@gmail.com
telegram: @devc1992
