### ISSUE TITLE
Firebase not working after converting the unity exported project(gradle) into library (aar).

### ISSUE THREAD

**Issue by Soorya-S** [firebase/quickstart-unity#357]
## Please fill in the following fields:
Unity editor version:  2018.0.3f
Target platform: Android

I have exported the unity project into an android studio project. I followed [this](https://medium.com/@randive.rishiraj/7-steps-to-integrate-google-arcore-unity-project-to-a-native-android-app-d85793ba0b37) tutorial (I'm trying to integrate the unity project with my existing android studio project).

I'm using firebase inside my unity project. 
After converting the android studio project into a library, I'm getting this error 

`E/firebase: strlen(app_options->app_id()) && strlen(app_options->api_key())
E/Unity: strlen(app_options->app_id()) && strlen(app_options->api_key())
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
E/firebase: Failed to read Firebase options from the app's resources.  You'll need to either at least set App ID and API key or include google-services.json your app's resources.
W/firebase: Failed to set AppOption: ApiKey must be set.
W/Unity: Failed to set AppOption: ApiKey must be set.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
E/firebase: Could not initialize Firebase App Options: ApplicationId must be set.
E/Unity: Could not initialize Firebase App Options: ApplicationId must be set.
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
E/firebase: new_app
E/Unity: new_app
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
E/firebase: Failed to initialize the default Firebase App.
E/Unity: InitializationException:  Firebase app creation failed.
      at Firebase.FirebaseApp.CreateAndTrack (Firebase.FirebaseApp+CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) [0x000e3] in <c6dce82e4cd542afa5ff22c61c7d8569>:0 
      at Firebase.FirebaseApp.Create () [0x00027] in <c6dce82e4cd542afa5ff22c61c7d8569>:0 
      at Firebase.FirebaseApp.get_DefaultInstance () [0x00017] in <c6dce82e4cd542afa5ff22c61c7d8569>:0 
      at Firebase.Database.FirebaseDatabase.get_DefaultInstance () [0x00000] in <8d83e0dcc85a4cc9a239a8de8571696d>:0 
      at AssetDownloader.getFirebaseData () [0x00000] in <22418c26a38447b09c44d7b2eb12e0a2>:0 
      at AssetDownloader.Start () [0x0009b] in <22418c26a38447b09c44d7b2eb12e0a2>:0 
     
    (Filename: <c6dce82e4cd542afa5ff22c61c7d8569> Line: 0)
E/Unity: NullReferenceException: Object reference not set to an instance of an object
      at ARController.updatePlacementPose () [0x00014] in <22418c26a38447b09c44d7b2eb12e0a2>:0 
      at ARController.Update () [0x00006] in <22418c26a38447b09c44d7b2eb12e0a2>:0 
     
    (Filename: <22418c26a38447b09c44d7b2eb12e0a2> Line: 0)`

**Comment by stewartmiles** [comment]
@Soorya-S 

"E/firebase: Failed to read Firebase options from the app's resources. You'll need to either at least set App ID and API key or include google-services.json your app's resources."

describes the error, you're missing the Firebase configuration file.

"E/firebase: Failed to initialize the default Firebase App.
E/Unity: InitializationException: Firebase app creation failed."

Is because the Firebase configuration wasn't present so the app couldn't be created.

**Comment by Soorya-S** [comment]
> @Soorya-S
> 
> "E/firebase: Failed to read Firebase options from the app's resources. You'll need to either at least set App ID and API key or include google-services.json your app's resources."
> 
> describes the error, you're missing the Firebase configuration file.
> 
> "E/firebase: Failed to initialize the default Firebase App.
> E/Unity: InitializationException: Firebase app creation failed."
> 
> Is because the Firebase configuration wasn't present so the app couldn't be created.

Thanks. Now I figured out why this occurred. after converting the android studio project into the library, the application ID will be removed from the project.  So, I need a way to connect to firebase from library project.

**Comment by Soorya-S** [comment]
Finally fixed!
Just registered my master android project with same bundle id as my unity project to firebase and the magic happened!

**Comment by umeshiscreative** [comment]
@Soorya-S ,
Thank for this but I am still getting issue, When I am adding my _"google-service.json"_ in to root of android project but still facing same error.

![Screenshot 2019-05-08 at 1 50 13 AM](https://user-images.githubusercontent.com/36879900/57330506-e02fa380-7133-11e9-8e3f-d4544612ce29.png)
