### ISSUE TITLE
Unable to find Method com/google/firebase/auth/FirebaseAuth.fetchProvidersForEmail

### ISSUE THREAD

**Issue by nextvern** [firebase/quickstart-unity#359]
## Please fill in the following fields:
Unity editor version: Unity 2018.3.5
Firebase Unity SDK version: 5.7.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, Functions, Messaging, Storage, Crashlytics, DynamicLinks, Database, RemoteConfig
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook SDK, AdMob SDK, FAN Mediation, Appsflyer
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac and Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Hello~ I have got a problem.
I have released the app before. Then it worked perfectly.

The build(.net 4.x and IL2CPP ) and Android resolver were successful. But I run my app got an Error Message.

I found previous build app dependencies used firebase-auth 16.2.1 and firebase-auth-interop 16.0.1
I don't use function FirebaseAuth.FetchProvidersForEmail() anywhere.
This is my Logcat message. 

```
05-07 17:15:05.123 4568-4645/com.cannon.bomber W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/auth/FirebaseAuth;.fetchProvidersForEmail(Ljava/lang/String;)Lcom/google/android/gms/tasks/Task;"
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:395)
        at android.os.Looper.loop(Looper.java:181)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
05-07 17:15:05.123 4568-4645/com.cannon.bomber E/firebase: method_ids[i] || (method.optional == kMethodOptional)
05-07 17:15:05.124 4568-4645/com.cannon.bomber E/Unity: method_ids[i] || (method.optional == kMethodOptional)
    UnityEngine.Logger:Log(LogType, Object)
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
05-07 17:15:05.124 4568-4645/com.cannon.bomber E/firebase: Unable to find Method com/google/firebase/auth/FirebaseAuth.fetchProvidersForEmail (signature '(Ljava/lang/String;)Lcom/google/android/gms/tasks/Task;', instance).  Please verify the AAR which contains the com/google/firebase/auth/FirebaseAuth class is included in your app.
05-07 17:15:05.124 4568-4645/com.cannon.bomber D/Unity: SendMessage: object AppsFlyerTrackerCallbacks not found!
05-07 17:15:05.136 4568-4645/com.cannon.bomber D/Unity: Uploading Crash Report
05-07 17:15:05.139 4568-4683/com.cannon.bomber I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
    (HTTPLog)-Static: isSBSettingEnabled false
05-07 17:15:05.189 4568-4645/com.cannon.bomber E/Unity: ApplicationException: Unable to find Method com/google/firebase/auth/FirebaseAuth.fetchProvidersForEmail (signature '(Ljava/lang/String;)Lcom/google/android/gms/tasks/Task;', instance).  Please verify the AAR which contains the com/google/firebase/auth/FirebaseAuth class is included in your app.
      at Firebase.Auth.FirebaseAuth.GetAuthInternal (Firebase.FirebaseApp app, Firebase.InitResult& init_result_out) [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.Auth.FirebaseAuth+<GetAuth>c__AnonStorey1.<>m__0 () [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.FirebaseApp.TranslateDllNotFoundException (System.Action closureToExecute) [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.Auth.FirebaseAuth.GetAuth (Firebase.FirebaseApp app) [0x00000] in <00000000000000000000000000000000>:0 
      at Platform.Auth..ctor () [0x00000] in <00000000000000000000000000000000>:0 
      at FirebaseManager.OnFirebaseAppInitializedSuccess () [0x00000] in <00000000000000000000000000000000>:0 
     
05-07 17:15:05.245 4568-4645/com.cannon.bomber E/Unity: ApplicationException: Unable to find Method com/google/firebase/auth/FirebaseAuth.fetchProvidersForEmail (signature '(Ljava/lang/String;)Lcom/google/android/gms/tasks/Task;', instance).  Please verify the AAR which contains the com/google/firebase/auth/FirebaseAuth class is included in your app.
      at Firebase.Auth.FirebaseAuth.GetAuthInternal (Firebase.FirebaseApp app, Firebase.InitResult& init_result_out) [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.Auth.FirebaseAuth+<GetAuth>c__AnonStorey1.<>m__0 () [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.FirebaseApp.TranslateDllNotFoundException (System.Action closureToExecute) [0x00000] in <00000000000000000000000000000000>:0 
      at Firebase.Auth.FirebaseAuth.GetAuth (Firebase.FirebaseApp app) [0x00000] in <00000000000000000000000000000000>:0 
      at Platform.Auth..ctor () [0x00000] in <00000000000000000000000000000000>:0 
      at FirebaseManager.OnFirebaseAppInitializedSuccess () [0x00000] in <00000000000000000000000000000000>:0 
```

**Comment by jonsimantov** [comment]
We just released version [6.0.0](https://firebase.google.com/support/release-notes/unity#6.0.0) of the Firebase Unity SDK, which supports breaking changes in Firebase for Android (including FirebaseAuth.fetchProvidersForEmail as you mentioned) and addresses this issue.

You can download the latest Firebase Unity SDK at [https://firebase.google.com/docs/unity/setup#add_sdk](https://firebase.google.com/docs/unity/setup#add_sdk).

**Comment by tianzexin** [comment]
I get the 6.2.2 version。but，when i import to the Unity 2018.3.14f1 (64-bit)，is failed。the error：
======================================================
Gradle failed to fetch dependencies.

Failed to run 'C:\Work\small_1-1_client\trunk_skin\Temp\PlayServicesResolverGradle\gradlew.bat -b "C:\Work\small_1-1_client\trunk_skin\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" --no-daemon "-PANDROID_HOME=H:/tools/android-sdk-windows" "-PTARGET_DIR=C:\Work\small_1-1_client\trunk_skin\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///C:/Work/small_1-1_client/trunk_skin/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.android.support:support-v4:25.3.1;com.android.support:appcompat-v7:25.3.1;com.android.support:cardview-v7:25.3.1;com.android.support:customtabs:25.3.1;com.google.firebase:firebase-analytics:16.5.0;com.google.firebase:firebase-core:16.0.9;com.google.firebase:firebase-iid:[17.1.2];com.google.firebase:firebase-analytics-unity:5.6.0;com.google.firebase:firebase-common:18.0.0;com.google.firebase:firebase-analytics:17.0.0;com.google.firebase:firebase-app-unity:6.2.2;com.google.firebase:firebase-auth:18.0.0;com.google.firebase:firebase-auth-unity:6.2.2;com.google.firebase:firebase-database:17.0.0;com.google.firebase:firebase-database-unity:5.6.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.2.0"'
stdout:
Unzipping C:\Users\Tzx\.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn\gradle-5.1.1-bin.zip to C:\Users\Tzx\.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn

stderr:
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

exit code: 1

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:103)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:929)
GooglePlayServices.<GradleResolution>c__AnonStorey1:<>m__4(Result) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:878)
GooglePlayServices.<GradleResolution>c__AnonStorey3:<>m__0() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:995)
Google.RunOnMainThread:ExecuteNext() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
Google.RunOnMainThread:Run(Action, Boolean) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:363)
GooglePlayServices.<GradleResolution>c__AnonStorey1:<>m__5(Result) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:995)
GooglePlayServices.ProgressReporter:SignalComplete() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:116)
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/CommandLineDialog.cs:107)
GooglePlayServices.<RunAsync>c__AnonStorey1:<>m__0() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/CommandLine.cs:136)
Google.RunOnMainThread:ExecuteNext() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.MFNLcXgkvt/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
======================================
what can i do

**Comment by stewartmiles** [comment]
@tianzexin 

This is an issue with the Gradle wrapper, some examples: 
https://www.bountysource.com/issues/50071257-exception-in-thread-main-java-util-zip-zipexception-error-in-opening-zip-file
https://stackoverflow.com/questions/32535930/cordova-build-gradle-error-while-opening-extracting-zip-file
https://github.com/NativeScript/NativeScript/issues/3930

Basically, it looks like `C:\Users\Tzx.gradle\wrapper\dists\gradle-5.1.1-bin\90y9l8txxfw1s2o6ctiqeruwn\gradle-5.1.1-bin.zip` is corrupt on your machine, you should probably delete the whole directory `C:\Users\Tzx.gradle\wrapper\dists\gradle-5.1.1-bin` and let the wrapper download Gradle again.

**Comment by tianzexin** [comment]
Thanks very much!
