### ISSUE TITLE
"FirebaseApp not found" and crash

### ISSUE THREAD

**Issue by Sakura777** [firebase/quickstart-unity#36]
Unity 5.4.4f1
SO-02E Android 4.4.2

Execution procedure
1. I downloaded "quickstart-unity" zip file and opened messeging project with Unity.
2. I downloaded "firebase unity sdk" and imported it to Unity. (All files)
(Download from https://firebase.google.com/docs/unity/setup today)
3. I imported "google-services.json" to unity.
4. I built an application.
5. After launching the application, the Unity logo will be displayed.
  But then the screen will turn white and the application will crash.

The logs of the crash are as follows.
```
01-10 17:19:23.664: E/Unity(17292): local_class
01-10 17:19:23.664: E/Unity(17292):  
01-10 17:19:23.664: E/Unity(17292): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
01-10 17:19:23.664: E/firebase(17292): Class com/google/firebase/FirebaseApp not found
01-10 17:19:23.674: E/firebase(17292): global_class
01-10 17:19:23.674: A/libc(17292): Fatal signal 11 (SIGSEGV) at 0x0000002c (code=1), thread 17314 (UnityMain)
```

Is there any missing step to do?
I would like you to help me.

**Comment by stewartmiles** [comment]
It looks like you're missing the Android dependencies of the library.

Verify the Android Resolver is enabled under the menu option "Assets --> Play Services Resolver --> Android Resolver --> Settings" , Enable Background Resolution should be checked.

If "Enable Background Resolution" is enabled, try manually running the tool using "Assets --> Play Services Resolver --> Android Resolver --> Resolve Client Jars" it should result in a load of aar files being copied into Assets/Plugins/Android/firebase-*.aar a couple of folders may be created in the same directory from expanded AARs.

Once you have the AARs present, rebuild your app and run.

**Comment by Sakura777** [comment]
Thank you for your response.
I got a message successfully as you directed.
