### ISSUE TITLE
Websocket error TextMeshPro downgrade DotNet3.x

### ISSUE THREAD

**Issue by spinteractive** [firebase/quickstart-unity#360]
## Please fill in the following fields:
Unity editor version: 2019.1.1f1
Firebase Unity SDK version: 5.7.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS/Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Hello, I am trying to debug database using Unity Editor on 2019.1.1f1. I get a websocket error using DotNet4 runtime - so I switch to 3.x runtime this works... but for it to work I have to delete the TextMeshPro package in Unity. The problem is my project is completely dependent on the TextMeshPro so I cannot downgrade the runtime for editor debug. 
What do I do from here?

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project) YES

**Comment by jonsimantov** [comment]
What's the websocket error you get? Could you provide a device log?

**Comment by spinteractive** [comment]
Hi thanks for responding. The 2 errors:

5/8/2019 11:50:30 PM [Error] WebSocket: ws_0 - could not connect
System.Net.Sockets.SocketException (0x80004005): No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000ea] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:323 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/UnityLoggingService.cs:13)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:68)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:32)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/LogWrapper.cs:36)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:143)
Firebase.Database.Internal.TubeSock.WebSocket:CreateSocket() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:325)
Firebase.Database.Internal.TubeSock.WebSocket:RunReader() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:386)
Firebase.Database.Internal.TubeSock.Runnable101:Run() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:516)
Google.Sharpen.Thread:InternalRun() (at Z:/tmp/tmp.vANha6D0V6/third_party/dotnet_src/sharpen/Sharpen/Thread.cs:80)
System.Threading.ThreadHelper:ThreadStart()

——————

5/8/2019 11:50:30 PM [Error] WebSocket: ws_0 - WebSocketException during handshake
Firebase.Database.Internal.TubeSock.WebSocketException: unknown host: yellows.firebaseio.com ---> System.Net.Sockets.SocketException: No route to host
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at System.Net.Sockets.TcpClient.Connect (System.Net.IPEndPoint remoteEP) [0x00033] in <c9226b2f33b7421e85bb391f94075e49>:0 
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x000ea] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:323 
   --- End of inner exception stack trace ---
  at Firebase.Database.Internal.TubeSock.WebSocket.CreateSocket () [0x0010c] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:327 
  at Firebase.Database.Internal.TubeSock.WebSocket.RunReader () [0x0001b] in Z:\tmp\tmp.UJsYTuiaFJ\firebase\database\client\mono\Database\Internal\TubeSock\WebSocket.cs:386 
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/FirebaseLogger.cs:19)
Firebase.Unity.UnityLoggingService:LogMessage(PlatformLogLevel, String) (at Z:/tmp/tmp.lznH2AxwEU/firebase/app/client/unity/src/Unity/UnityLoggingService.cs:13)
Firebase.Database.Internal.Logging.DefaultLogger:Error(String, String) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:68)
Firebase.Database.Internal.Logging.DefaultLogger:OnLogMessage(Level, String, String, Int64) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/DefaultLogger.cs:32)
Firebase.Database.Internal.Logging.LogWrapper:Error(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/Logging/LogWrapper.cs:36)
Firebase.Database.Internal.TubeSock.WebSocket:LogError(String, Exception) (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:143)
Firebase.Database.Internal.TubeSock.WebSocket:RunReader() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:468)
Firebase.Database.Internal.TubeSock.Runnable101:Run() (at Z:/tmp/tmp.UJsYTuiaFJ/firebase/database/client/mono/Database/Internal/TubeSock/WebSocket.cs:516)
Google.Sharpen.Thread:InternalRun() (at Z:/tmp/tmp.vANha6D0V6/third_party/dotnet_src/sharpen/Sharpen/Thread.cs:80)
System.Threading.ThreadHelper:ThreadStart()

**Comment by TonyaGitHub** [comment]
Keep the 4.X, this has been a common issue, here's the solution/workaround:

**To resolve the compilation error, if you're using .NET 4.x:
Remove or disable the following DLLs for all platforms:
Parse/Plugins/Unity.Compat.dll
Parse/Plugins/Unity.Tasks.dll
Enable the following DLLs for all platforms:
Parse/Plugins/dotNet45/Unity.Compat.dll
Parse/Plugins/dotNet45/Unity.Tasks.dll**

_From: https://firebase.google.com/docs/unity/setup#net_compatibility_when_using_unity_2017x_and_later_

**Comment by spinteractive** [comment]
Hi, I’ve done that, I still get the same error.

**Comment by jonsimantov** [comment]
Hi all,

The C# implementation of Firebase Realtime Database on desktop has this issue as well as many others. We are working hard to finish our native C++ desktop implementation, which should fundamentally fix these sorts of issues in Firebase RTDB desktop in Unity as well.

Please bear with us as we finish the implementation (we are getting very close), and will do so when we are sure it is ready for use.

**Comment by jonsimantov** [comment]
See https://github.com/firebase/quickstart-unity/issues/106 for more information.

**Comment by spinteractive** [comment]
OK thanks for your help.

Alex
