### ISSUE TITLE
Question: Parameter of LoadFromJsonConfig() function

### ISSUE THREAD

**Issue by dreyZZ** [firebase/quickstart-unity#361]
Hi, perhaps asking this question here is wrong but i could not get any information on from anywhere and it is a very simple question. I asked it on [Stackoverflow ](https://stackoverflow.com/questions/56039332/how-to-load-app-config-from-json-file-in-unity-firebase-sdk) but no interest is given.

Thanks for your understanding.

**Comment by jonsimantov** [comment]
Apologies - LoadFromJsonConfig() takes the JSON data in a string, not the filename, as its parameter. This looks like an error in the documentation. You'll need to read the JSON file into a string first, and then pass that string of JSON into AppOptions.LoadFromJsonConfig().

Sorry for the confusion! I'll make sure those docs get corrected and close this bug once that happens.

**Comment by ryanmeier** [comment]
The documentation for AppOptions.LoadFromJsonConfig should now be updated in the [6.1.0 Release](https://firebase.google.com/download/unity) of the SDK.
