### ISSUE TITLE
DllNotFoundException on Android

### ISSUE THREAD

**Issue by fractalfrenzy** [firebase/quickstart-unity#362]
Hello,

I have ran into an error using the SDK for Android.  I follow these steps to reproduce this issue:

1. Open Unity 2018.3.9f1
2. Import Firebase Unity SDK 5.7.0 dotnet4 FirebaseAnalytics.unitypackage
3. Copy google-services.json into Assets directory.
4. Add the initilization code found in Step 6 here https://firebase.google.com/docs/unity/setup to the Awake Method of a component and add it to the scene
5. Switch the project to Android
6. Make a build

In the console I see the following:

> 05-10 11:43:27.293 23710 23735 E Unity   : Unable to find FirebaseCppApp-5.7.0
> 05-10 11:43:27.503 23710 23735 E Unity   : DllNotFoundException: FirebaseCppApp-5.7.0
> 05-10 11:43:27.503 23710 23735 E Unity   :   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
> 05-10 11:43:27.503 23710 23735 E Unity   :   at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <c6dce82e4cd542afa5ff22c61c7d8569>:0
> 05-10 11:43:27.503 23710 23735 E Unity   : Rethrow as TypeInitializationException: The type initializer for 'SWIGE

Thank you for your assistance in resolving this issue.

**Comment by jonsimantov** [comment]
Hi,

I believe the issue is that you need to run the Android Resolver prior to building. In the Unity menu, navigate the menu to Assets ->Play Services Resolver -> Android Resolver -> Resolve. If you continue to get an error, you can turn on the debug log in Android Resolver -> Settings and paste in the log here for further analysis.

Also, we've released version 6.0.0 of the SDK which fixes some resolver issues, so if you continue to have problems, delete all the Firebase files from your project and install 6.0.0 instead.

**Comment by chkuang-g** [comment]
Hi @fractalfrenzy

Is the issued resolved from your side?

Shawn

**Comment by demskiy** [comment]
Same error here, Unity 2019.3.0a4, DllNotFoundException: FirebaseCppApp-6.0.0, .NET 4.x mode.

**Comment by fractalfrenzy** [comment]
@chkuang-g Running the Android resolver fixed it for me. Thanks.

**Comment by patm1987** [comment]
@demskiy : do the steps mentioned by @jonsimantov and @chkuang-g resolve the issue for you as well?

**Comment by stewartmiles** [comment]
@demskiy since we haven't heard from you we'll assume you've resolved your issue.
