### ISSUE TITLE
how to detect message is received from clicked on push notification?

### ISSUE THREAD

**Issue by longvannguyendx** [firebase/quickstart-unity#364]
Unity editor version: 
Firebase Unity SDK version: 5.7.0
Firebase plugins in use (Auth, Database, etc.): FirebaseMessaging 
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop):  Android

I have a question, how to detect message is received from clicked on push notification?
Thank you so much and have a nice day

**Comment by TonyaGitHub** [comment]
When you recieve a new message, you can check the property 'NotificationOpened', if it returns true, it means that the message was opened by clicking on the notification.

Hope it helps!

**Comment by a-maurice** [comment]
Yep, as TonyaGitHub said, you can check the 'NotificationOpened' property, which you can read about here: https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-message.html#notificationopened
