### ISSUE TITLE
Turn off Push Notifications at System Level

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#365]
Unity editor version: 2018.3.11
Firebase Unity SDK version: 5.4.4
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS & Android

I want to turn off push notification at system level, is there any method available?
What  I mean is that I want to have a toggle to turn on/off system notifications for my app.

Is it possible with Firebase Messaging?

**Comment by a-maurice** [comment]
Hi @MartinGonzalez 

You can disable the Firebase messages by both disabling the token registration (https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-messaging#tokenregistrationoninitenabled), and if an id was already received, deleting it via https://firebase.google.com/docs/reference/unity/class/firebase/instance-id/firebase-instance-id#deleteidasync.

Note that will disable all Firebase messages from being received, not just Push Notifications.

**Comment by TwitRco** [comment]
Not sure

**Comment by chkuang-g** [comment]
@MartinGonzalez 
I think you would need to look into native Android or iOS SDK to do so.  I do not think Firebase SDK has the permission to toggle system level push notification.
