### ISSUE TITLE
Is it possible to integrate Firebase Messaging in a project with Facebook SDK?

### ISSUE THREAD

**Issue by goshki** [firebase/quickstart-unity#37]
I have a project that uses Facebook SDK and I override the default starting activity with Facebook's `FBUnityDeepLinkingActivity`. On the other hand, Firebase Messaging requires `MessagingUnityPlayerActivity` as a workaround to a bug when a message is sent containing both a Data and Notification payload (as explained [here](https://firebase.google.com/docs/cloud-messaging/unity/client)).

I need `FBUnityDeepLinkingActivity` to monitor Facebook campaign installs so I was wondering how should one go about integrating functionality of both of these activities?

**Comment by johnb003** [comment]
Hi goshki, sorry for taking so long to get back to you on this.

The docs for this are a little ambiguous. I've filed an internal bug to address that.

The MessagingUnityPlayerActivity is not a required base class. It's simply a convenience. The code that's listed on that page you linked at the bottom actually contains all of the code that's in that base class, so you can include it even if you're not able to derive from one of the base classes that has that code.

So you should be able to use the facebook activity and add the necessary code for messaging.

**Comment by johnb003** [comment]
I think this addresses your specific issue so I'm closing this, if you have additional problems with getting this to work with facebook feel free to re-open the issue.
