### ISSUE TITLE
Messaging (iOS): Prevent push notification in tray when app is in foreground when using OneSignal

### ISSUE THREAD

**Issue by giliwerner** [firebase/quickstart-unity#372]
## Please fill in the following fields:
Unity editor version: 2018.4.1f
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): OneSignal, Facebook, Google Sign-In, Heyzap, Unity Ads, Vungle, AppLovin
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android

## Please describe the issue here:
When the app is in the foreground and a push notification is received, you always see the notification popping down from the top of the screen. 
When the app is active, we don't want the notification to be visible to the user. We just want to get the in-app callback to handle it silently. We only want this notification to be visible when the app is either in the background or closed. 

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes

**Comment by alexames** [comment]
I am having trouble reproducing the issue. The outcome you want is the intended behavior of the SDK, but it's also what I observe when I test with the quickstart app locally. Can you give us a little more detail? 

Here is what I observe when running a clean quickstart app: 

- Install the quickstart app
- Open it
- Send a message. 
    - The app will consume the message and display the output in the app without displaying the notification popup. 
- Put the app in the background
- Send a message. 
    - A notification will appear in my system tray

Is that not what you're observing? Are you doing anything different?

**Comment by giliwerner** [comment]
Ok, so I managed to narrow down the cause of this issue.
We are using Unity's Mobile Notifications package (preview version 1.0.0.21), and it is causing this unexpected behaviour. 
When I added this package to the Firebase quickstart app, I got the same buggy result, where the notification popped up while the app was in the foreground. 
You can see the code of this package here:
https://bintray.com/unity/unity-staging/com.unity.mobile.notifications

Any idea why this package is changing the firebase behaviour? Is there anything I can do to fix it?
Thanks!

**Comment by ryanmeier** [comment]
@giliwerner Which platforms are you seeing this behavior in the Firebase Quickstart app (+ OneSignal SDK) on (iOS, Android, or Both)?

**Comment by giliwerner** [comment]
Only on iOS it occurs. On Android it works as expected.

**Comment by stewartmiles** [comment]
@giliwerner I had a dig around OneSignal's source and it looks like this is the default behavior when it receives a notification...

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/9271672bd77326df1063393451948b456ed9cbea/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1881

It looks like you can customize the in-focus behavior using kOSSettingsKeyInFocusDisplayOption on initialization:
https://github.com/OneSignal/OneSignal-iOS-SDK/blob/6c775875e07eba1ada782c1f502604ade9c62c53/Examples/ObjectiveCExample/OneSignalDemo/AppDelegate.m#L88

**Comment by chkuang-g** [comment]
@giliwerner 
I'm closing this issue since there is no response in a month.
Please let us know if you still have issue.
