### ISSUE TITLE
Messaging (Android): Don't get a Notification when Firebase message contains both notification and data payloads.

### ISSUE THREAD

**Issue by Sekaiichi4** [firebase/quickstart-unity#373]
## Please fill in the following fields:
Unity editor version: 2018.3.6f1
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Twilio, Google Maps
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
When I send a test message through the Firebase Console, I do get a native Android notification, as no Data is included. However when I send a Firebase message through my server that except for the notification part, also includes data, I am not getting a notification when the app is closed nor open. When I look at the logs through Androids Logcat however, I see that the Firebase messages do come through, and they get queued so that the data can be handled through the C# onMessageReceived method inside of the Unity app.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes, even if I make a build of the Firebase Unity quickstarts project with the right setup for my server, I only get the data when opening the app afterwards, and no Android notification when the message data get's queued. 

If I however make a native android app, without the use of the Unity Firebase SDK, but just the Android Firebase SDK, I am able to receive notifications even if it is a combined with data payloads.

**Comment by Sekaiichi4** [comment]
I guess it's impossible?

**Comment by ryanmeier** [comment]
Hi @Sekaiichi4 - sorry to hear you're having trouble with the Firebase Unity SDK, and apologies that no one was able to get back to you sooner.  We'll look into this issue and get back to you here when we have more information!

**Comment by stewartmiles** [comment]
@Sekaiichi4 I'm trying to understand what you're describing here.  From what I can tell:
- If you send a notification, you see a notification pop up when the app is and isn't running.
- If you send a message with data without a notification, you do not see a notification pop up.

It sounds like what you're describing is the behavior we have documented here:
https://firebase.google.com/docs/cloud-messaging/unity/client#note_about_message_delivery_on_android

I just tried this out with the messaging sample application using the old REST API and it works as expected...

```
curl -i -H 'Content-type: application/json' -H 'Authorization: key=MY_KEY' -X POST https://fcm.googleapis.com/fcm/send -d '{ "to": "/topics/TestTopic", "notification": { "body": "Hello from CURL", "title": "CURL says..." }, "data": { "foo": "bar", "bish": "bosh" } }'
```

When the app is in the foreground it receives the notification without displaying in the system tray.
When the app in the background the notification is displayed in the system tray, tapping on it opens the application.

Are you seeing different behavior.

**Comment by Sekaiichi4** [comment]
Thank you for your response, it made me debug everything once again and then I figured out that with the following similar curl I managed to get both a notification and the data.

`curl -X POST --header "Authorization: key=MY_FCM_SERVER_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"to\":\"/topics/MY_TOPIC\",\"notification\":{\"body\":\"{MESSAGE}\"},\"data\":{\"content\":\"{Data Content}\"},\"priority\":10}"`

The problem lied in the way I send the message and data from my server, as everyone online kept telling me that I should only send the "data" part and not the "notification" part, as that would rather not show a notification at all in the case of the Unity Firebase SDK. But apparently, this is false information as when I un-commented my 

`"notification": {
             "title": title, 
             "body": body
            },`

section on my server, everything worked as it should!

**Comment by stewartmiles** [comment]
@Sekaiichi4 great news!
