### ISSUE TITLE
Build failure (Android)

### ISSUE THREAD

**Issue by pparreno** [firebase/quickstart-unity#382]
Unity editor version: v2019.1.0f2
Firebase Unity SDK version: firebase_unity_sdk_6.0.0
Firebase plugins in use (Auth, Database, etc.): Auth & Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Gamesparks
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac & Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS & Android

iOS builds just fine but Android build process fails:
![Screen Shot 2019-06-10 at 6](https://user-images.githubusercontent.com/1787467/59191736-e4c3fd80-8bb2-11e9-86f5-4556c9335795.png)

**Comment by cynthiajoan** [comment]
Hi @pparreno, have you tried the same setup with our quick start test app
https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp
https://github.com/firebase/quickstart-unity/tree/master/auth/testapp
to see if they have the same issue in case of 1) no additional sdk and 2) add additionals sdks separately, to narrow down the cause?

**Comment by stewartmiles** [comment]
@pparreno since we haven't heard from you I'm closing this issue.  Let us know if you were still having issues.
