### ISSUE TITLE
Error when Fetching RC data from Editor with no Internet Connection.

### ISSUE THREAD

**Issue by Mecze** [firebase/quickstart-unity#389]
## Please fill in the following fields:
Unity editor version: Unity 2017.4.28f1
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): **RemoteConfig**, Crashlytics, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.):  Admob, Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop): Android. The thing happens in Editor

## Please describe the issue here:
Just disconnected my Desktop from Wifi, because I wanted the game to use the default values of RemoteConfig and got this Error:
![image](https://user-images.githubusercontent.com/21218454/59594901-0bbf8980-90f5-11e9-9acd-cec0e68f2b6d.png)

**NOTE:** 
Also, This part of the log bugs me out:

![image](https://user-images.githubusercontent.com/21218454/59596451-03b51900-90f8-11e9-8e1e-dde385e07177.png)

It refers to a "Z:" Drive
I actually use a Z: for our external network storage.
I guess it's a happy coindence since not such route exists in our network storage

## Please answer the following, if applicable:
- Create a new Unity Project (Android)
- Import RemoteConfig 6.0.0
- import a google-services.json and write script to check dependencies and update values on Start
- Disconnect from WIFI / Internet
- Hit Play

**Comment by patm1987** [comment]
Hi Mecze,

RemoteConfig should fail to fetch if you're not on the network. Are you mostly concerned about the log line? This is likely an artifact from the build environment where the Firebase dll's were built (I see similar source paths on my on apple laptop, which doesn't have the concept of a drive letter).

--Patrick
