### ISSUE TITLE
Building for android fails on OSX. (Could not find firebase-app-unity.jar (com.google.firebase:firebase-app-unity:6.0.0))

### ISSUE THREAD

**Issue by gabetoth-dgh** [firebase/quickstart-unity#390]
## Please fill in the following fields:
Unity editor version: 2018.2.21f1
Firebase Unity SDK version: 6.0.0
Firebase plugins in use (Auth, Database, etc.): Auth, Messaging, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): IronSource
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Using Play Services Resolver v 1.2.117. Build fails with the following:
`CommandInvokationFailure: Gradle build failed. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -classpath "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-4.2.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"
stderr[
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':releaseCompileClasspath'.
> Could not find firebase-app-unity.jar (com.google.firebase:firebase-app-unity:6.0.0).
  Searched in the following locations:
      file:/[...]/Assets/Firebase/m2repository/com/google/firebase/firebase-app-unity/6.0.0/firebase-app-unity-6.0.0.jar
> Could not find firebase-auth-unity.jar (com.google.firebase:firebase-auth-unity:6.0.0).
  Searched in the following locations:
      file:/[...]/Assets/Firebase/m2repository/com/google/firebase/firebase-auth-unity/6.0.0/firebase-auth-unity-6.0.0.jar
> Could not find firebase-crashlytics-unity.jar (com.google.firebase:firebase-crashlytics-unity:6.0.0).
  Searched in the following locations:
      file:/[...]/Assets/Firebase/m2repository/com/google/firebase/firebase-crashlytics-unity/6.0.0/firebase-crashlytics-unity-6.0.0.jar
> Could not find firebase-messaging-unity.jar (com.google.firebase:firebase-messaging-unity:6.0.0).
  Searched in the following locations:
      file:/[...]/Assets/Firebase/m2repository/com/google/firebase/firebase-messaging-unity/6.0.0/firebase-messaging-unity-6.0.0.jar
> Could not find gpgs-plugin-support.jar (com.google.games:gpgs-plugin-support:0.9.62).
  Searched in the following locations:
      file:/[...]/Assets/GooglePlayGames/Editor/m2repository/com/google/games/gpgs-plugin-support/0.9.62/gpgs-plugin-support-0.9.62.jar
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s
]
stdout[
:preBuild UP-TO-DATE
:Firebase:preBuild UP-TO-DATE
:Firebase:preReleaseBuild UP-TO-DATE
:Firebase:checkReleaseManifest
:Firebase:processReleaseManifest
:GooglePlayGamesManifest.plugin:preBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:preReleaseBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:checkReleaseManifest
:GooglePlayGamesManifest.plugin:processReleaseManifest
:IronSource:preBuild UP-TO-DATE
:IronSource:preReleaseBuild UP-TO-DATE
:IronSource:checkReleaseManifest
:IronSource:processReleaseManifest
:unity-android-resources:preBuild UP-TO-DATE
:unity-android-resources:preReleaseBuild UP-TO-DATE
:unity-android-resources:checkReleaseManifest
:unity-android-resources:processReleaseManifest
:preReleaseBuild UP-TO-DATE
:Firebase:compileReleaseAidl
:GooglePlayGamesManifest.plugin:compileReleaseAidl
:IronSource:compileReleaseAidl
:unity-android-resources:compileReleaseAidl
:compileReleaseAidl UP-TO-DATE
:Firebase:packageReleaseRenderscript NO-SOURCE
:GooglePlayGamesManifest.plugin:packageReleaseRenderscript NO-SOURCE
:IronSource:packageReleaseRenderscript NO-SOURCE
:unity-android-resources:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:Firebase:compileReleaseRenderscript
:Firebase:generateReleaseResValues
:Firebase:generateReleaseResources
:Firebase:packageReleaseResources
:GooglePlayGamesManifest.plugin:compileReleaseRenderscript
:GooglePlayGamesManifest.plugin:generateReleaseResValues
:GooglePlayGamesManifest.plugin:generateReleaseResources
:GooglePlayGamesManifest.plugin:packageReleaseResources
:IronSource:compileReleaseRenderscript
:IronSource:generateReleaseResValues
:IronSource:generateReleaseResources
:IronSource:packageReleaseResources
:unity-android-resources:compileReleaseRenderscript
:unity-android-resources:generateReleaseResValues
:unity-android-resources:generateReleaseResources
:unity-android-resources:packageReleaseResources
:mergeReleaseResources
:createReleaseCompatibleScreenManifests UP-TO-DATE
:processReleaseManifest
/[...]/Temp/gradleOut/src/main/AndroidManifest.xml:24:9-31:50 Warning:
    activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present
:splitsDiscoveryTaskRelease UP-TO-DATE
:Firebase:platformAttrExtractor
:GooglePlayGamesManifest.plugin:platformAttrExtractor
:IronSource:platformAttrExtractor
:unity-android-resources:platformAttrExtractor
:Firebase:generateReleaseBuildConfig
:Firebase:prepareLintJar UP-TO-DATE
:Firebase:javaPreCompileRelease
:Firebase:processReleaseJavaRes NO-SOURCE
:GooglePlayGamesManifest.plugin:generateReleaseBuildConfig
:GooglePlayGamesManifest.plugin:prepareLintJar UP-TO-DATE
:GooglePlayGamesManifest.plugin:javaPreCompileRelease
:GooglePlayGamesManifest.plugin:processReleaseJavaRes NO-SOURCE
:IronSource:generateReleaseBuildConfig
:IronSource:prepareLintJar UP-TO-DATE
:IronSource:javaPreCompileRelease
:IronSource:processReleaseJavaRes NO-SOURCE
:unity-android-resources:generateReleaseBuildConfig
:unity-android-resources:prepareLintJar UP-TO-DATE
:unity-android-resources:javaPreCompileRelease
:unity-android-resources:processReleaseJavaRes NO-SOURCE
:compileReleaseNdk NO-SOURCE
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:Firebase:mergeReleaseShaders
:Firebase:compileReleaseShaders
:Firebase:generateReleaseAssets
:Firebase:mergeReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseShaders
:GooglePlayGamesManifest.plugin:compileReleaseShaders
:GooglePlayGamesManifest.plugin:generateReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseAssets
:IronSource:mergeReleaseShaders
:IronSource:compileReleaseShaders
:IronSource:generateReleaseAssets
:IronSource:mergeReleaseAssets
:unity-android-resources:mergeReleaseShaders
:unity-android-resources:compileReleaseShaders
:unity-android-resources:generateReleaseAssets
:unity-android-resources:mergeReleaseAssets
:mergeReleaseAssets
:mergeReleaseJniLibFolders UP-TO-DATE
:Firebase:compileReleaseNdk NO-SOURCE
:Firebase:mergeReleaseJniLibFolders
:Firebase:transformNativeLibsWithMergeJniLibsForRelease
:Firebase:transformNativeLibsWithStripDebugSymbolForRelease
:Firebase:transformNativeLibsWithIntermediateJniLibsForRelease
:GooglePlayGamesManifest.plugin:compileReleaseNdk NO-SOURCE
:GooglePlayGamesManifest.plugin:mergeReleaseJniLibFolders
:GooglePlayGamesManifest.plugin:transformNativeLibsWithMergeJniLibsForRelease
:GooglePlayGamesManifest.plugin:transformNativeLibsWithStripDebugSymbolForRelease
:GooglePlayGamesManifest.plugin:transformNativeLibsWithIntermediateJniLibsForRelease
:IronSource:compileReleaseNdk NO-SOURCE
:IronSource:mergeReleaseJniLibFolders
:IronSource:transformNativeLibsWithMergeJniLibsForRelease
:IronSource:transformNativeLibsWithStripDebugSymbolForRelease
:IronSource:transformNativeLibsWithIntermediateJniLibsForRelease
:unity-android-resources:compileReleaseNdk NO-SOURCE
:unity-android-resources:mergeReleaseJniLibFolders
:unity-android-resources:transformNativeLibsWithMergeJniLibsForRelease
:unity-android-resources:transformNativeLibsWithStripDebugSymbolForRelease
:unity-android-resources:transformNativeLibsWithIntermediateJniLibsForRelease
:processReleaseJavaRes NO-SOURCE
:validateSigningRelease
:Firebase:mergeReleaseConsumerProguardFiles UP-TO-DATE
:Firebase:transformNativeLibsWithSyncJniLibsForRelease
:Firebase:mergeReleaseResources
:Firebase:verifyReleaseResources
:GooglePlayGamesManifest.plugin:mergeReleaseConsumerProguardFiles UP-TO-DATE
:GooglePlayGamesManifest.plugin:transformNativeLibsWithSyncJniLibsForRelease
:GooglePlayGamesManifest.plugin:mergeReleaseResources
:GooglePlayGamesManifest.plugin:verifyReleaseResources
:IronSource:mergeReleaseConsumerProguardFiles UP-TO-DATE
:IronSource:transformNativeLibsWithSyncJniLibsForRelease
:IronSource:mergeReleaseResources
:IronSource:verifyReleaseResources
:unity-android-resources:mergeReleaseConsumerProguardFiles UP-TO-DATE
:unity-android-resources:transformNativeLibsWithSyncJniLibsForRelease
:unity-android-resources:mergeReleaseResources
:unity-android-resources:verifyReleaseResources
:unity-android-resources:processReleaseResources
:unity-android-resources:generateReleaseSources
:unity-android-resources:compileReleaseJavaWithJavac
:unity-android-resources:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:unity-android-resources:extractReleaseAnnotations
:unity-android-resources:transformResourcesWithMergeJavaResForRelease
:unity-android-resources:transformClassesAndResourcesWithSyncLibJarsForRelease
:unity-android-resources:bundleRelease
:unity-android-resources:compileReleaseSources
:unity-android-resources:assembleRelease
:Firebase:processReleaseResources
:Firebase:generateReleaseSources
:Firebase:compileReleaseJavaWithJavac
:Firebase:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:Firebase:extractReleaseAnnotations
:Firebase:transformResourcesWithMergeJavaResForRelease
:Firebase:transformClassesAndResourcesWithSyncLibJarsForRelease
:Firebase:bundleRelease
:Firebase:compileReleaseSources
:Firebase:assembleRelease
:IronSource:processReleaseResources
:IronSource:generateReleaseSources
:IronSource:compileReleaseJavaWithJavac
:IronSource:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:IronSource:extractReleaseAnnotations
:IronSource:transformResourcesWithMergeJavaResForRelease
:IronSource:transformClassesAndResourcesWithSyncLibJarsForRelease
:IronSource:bundleRelease
:IronSource:compileReleaseSources
:IronSource:assembleRelease
:GooglePlayGamesManifest.plugin:processReleaseResources
:processReleaseResources
:generateReleaseSources
:GooglePlayGamesManifest.plugin:generateReleaseSources
:GooglePlayGamesManifest.plugin:compileReleaseJavaWithJavac
:GooglePlayGamesManifest.plugin:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease FAILED
126 actionable tasks: 106 executed, 20 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <2e1ceb8be418466c8b86169240ad22b1>:0)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions)
BuildControl:BuildPlatform(String[], String, BuildTargetGroup, BuildTarget, BuildOptions) (at Assets/Scripts/Editor/[...]/Build/BuildControl.cs:307)
BuildControl:BuildAndroidAdHoc() (at Assets/Scripts/Editor/[...]/Build/BuildControl.cs:97)`

**Comment by patm1987** [comment]
Hi @gabetoth-dgh,

Thanks for reporting this issue! Can you tell me if you're using a custom gradle template?

Also, a couple things to try off the bat:
1) can you try manually resolving your android dependencies vis the play services resolver
2) can you upgrade to the latest plugin (currently 6.1.1)
3) are you able to reproduce this issue in one of the sample apps?

--Patrick

**Comment by gabetoth-dgh** [comment]
Hi @patm1987,

Yes, I am using custom gradle template. But, as it turns out we had something messed up in our project, after reimporting everything the issue fixed itself.
