### ISSUE TITLE
HTTP connections via NSAllowsArbitraryLoads are broken in Unity

### ISSUE THREAD

**Issue by dustinkerstein** [firebase/quickstart-unity#397]
_I believe this is an issue in the Unity iOS Firebase SDK but didn't know where to post bugs for that as there doesn't seem to be an official repo specifically for the current Unity Firebase SDK._ 

I just upgraded to Firebase Unity 6.1.1 (from 4.1.0 version) and noticed that I was no longer able to access insecure HTTP content when using the NSAllowsArbitraryLoads key in info.plist (which Unity adds by default and I am dependent upon). I noticed that the `NSAllowsArbitraryLoadsInWebContent` key was being added and set `true`. It looks like this key may have been added recently based on the package's /Assets/Firebase/Editor/readme.md:

`General (iOS): Fixed an issue where connections via NSURLSession (used internally by the iOS SDK) can be prematurely closed by the client if NSAppTransportSecurity is set to YES in the Info.plist and NSAllowsArbitraryLoadsInWebContent is not set. This can be fixed by setting NSAllowsArbitraryLoadsInWebContent to the same value as NSAppTransportSecurity.`

And in practice I see that with the older Unity Firebase 4.1.1 my info.plist looked like:

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true />
</dict>
```

And in Unity Firebase 6.1.1 it looks like:

```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true />
  <key>NSAllowsArbitraryLoadsInWebContent</key>
  <true />
</dict>
```

Removing the `NSAllowsArbitraryLoadsInWebContent` key gets http connections working again so I do have a viable workaround. Is this a bug or is this the designed behavior?

  * Xcode version 10.2.1 (10E1001)
  * Firebase SDK version: Unity 6.1.1
  * Firebase Component: Core
  * Component version: NA

**Comment by stewartmiles** [comment]
After a load of investigation we found that if `NSAllowsArbitraryLoadsInWebContent` is not set and `NSAllowsArbitraryLoads` is true, on some iOS versions HTTP connections via NSURLSession will randomly fail.  This would vary across different devices and different iOS versions which is obviously very bad indeed.

So instead I recommend whitelisting domains that don't support TLS/SSL
https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsexceptiondomains?language=objc

**Comment by dustinkerstein** [comment]
Awesome, thanks! 

If anyone is curious as to how to automate this from Unity, feel free to use the following code (modified from [here](https://stackoverflow.com/questions/54370336/from-unity-to-ios-how-to-perfectly-automate-frameworks-settings-and-plist/54370793#54370793)):

```
using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;
using System.Collections;
using System.IO;
#if UNITY_IOS
using UnityEditor.iOS.Xcode;

public class BuildPostProcessor : MonoBehaviour {

	[PostProcessBuild]
	public static void ChangeXcodePlist(BuildTarget buildTarget, string path) {

		if (buildTarget == BuildTarget.iOS) {
			string plistPath = path + "/Info.plist";
			PlistDocument plist = new PlistDocument();
			plist.ReadFromFile(plistPath);

			PlistElementDict rootDict = plist.root;

		        if (rootDict ["NSAppTransportSecurity"] == null) {
				rootDict.CreateDict ("NSAppTransportSecurity");
			}

			rootDict ["NSAppTransportSecurity"].AsDict ().SetBoolean ("NSAllowsArbitraryLoads", true);
			rootDict ["NSAppTransportSecurity"].AsDict ().SetBoolean ("NSAllowsArbitraryLoadsInWebContent", true);

			var exceptionDomains = rootDict ["NSAppTransportSecurity"].AsDict().CreateDict ("NSExceptionDomains");
			var domain = exceptionDomains.CreateDict ("YOURDOMAIN.com");

			domain.SetBoolean ("NSExceptionAllowsInsecureHTTPLoads", true);
			domain.SetBoolean ("NSIncludesSubdomains", true);

			File.WriteAllText(plistPath, plist.WriteToString());
		}
	}

}
#endif
```
