### ISSUE TITLE
[SOLVED]com.google.firebase.auth.firebaseauth is not linked. skipping initialization

### ISSUE THREAD

**Issue by erkerkiii** [firebase/quickstart-unity#399]
## Please fill in the following fields:
Unity editor version: 2019.1.7f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.): Auth and Database
Additional SDKs you are using (Facebook, AdMob, etc.):  AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Auth does not work. I see this message in the logcat: com.google.firebase.auth.firebaseauth is not linked. skipping initialization

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

**Comment by alexames** [comment]
Have you tried running the Unity quickstart testapp, and if so, does the problem occur there? What steps did you follow to set up the Firebase libraries (desktop and auth)?

**Comment by erkerkiii** [comment]
> Have you tried running the Unity quickstart testapp, and if so, does the problem occur there? What steps did you follow to set up the Firebase libraries (desktop and auth)?

i didn't tried running the testapp, first i installed admob then i installed auth and database

**Comment by alexames** [comment]
Can you give me some more detail on the steps you followed to install the plugins? Can you show me your logcat output? Can you reproduce the issue in the quickstart app?

**Comment by erkerkiii** [comment]
`07-04 16:47:56.155: E/JavaBinder(28055): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
07-04 16:47:56.155: E/JavaBinder(28055): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
07-04 16:47:56.158: E/AndroidRuntime(28055): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
07-04 16:47:56.158: E/AndroidRuntime(28055): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
`

here is the logcat and i couldnt reproduce it

**Comment by a-maurice** [comment]
If sounds like maybe something is happening with the jar resolver.  What do you have in the 'Plugins/Android' folder?  If from the toolbar, you go to Assets > Play Services Resolver > Android Resolver > Display Libraries, is Auth being included?

Also, there is a newer version of the Unity SDK available, which might help resolve this.

**Comment by erkerkiii** [comment]
dependencies {
    implementation 'com.google.android.gms:play-services-ads:18.0.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.auto.value:auto-value-annotations:1.6.3' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-analytics:16.5.0' // Assets/Firebase/Editor/DatabaseDependencies.xml:15
    implementation 'com.google.firebase:firebase-app-unity:6.1.1' // Assets/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.firebase:firebase-auth:17.0.0' // Assets/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:6.1.1' // Assets/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:17.1.0' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-database:17.0.0' // Assets/Firebase/Editor/DatabaseDependencies.xml:13
    implementation 'com.google.firebase:firebase-database-unity:6.1.1' // Assets/Firebase/Editor/DatabaseDependencies.xml:20
}

Yes its included, i will look into the other SDK after im back from my vacation

**Comment by erkerkiii** [comment]
still no solutions

**Comment by erkerkiii** [comment]
Problem solved, new SDK did the trick
