### ISSUE TITLE
403 forbidden on sdk links

### ISSUE THREAD

**Issue by rad-ed** [firebase/quickstart-unity#4]
The links in the readme.md that go to the sdk (https://dev-partners.googlesource.com/unity-firebase/+archive/zip.tar.gz) are forbidden to be accessed.

Furthermore, the current package on the official unity SDK site does not have the FirebaseApp.unitypackage in it. The source for these files is (https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_1.0.0.zip), as listed on https://firebase.google.com/docs/unity/setup.

**Comment by stewartmiles** [comment]
Fixed with 5ea23daf60ef6478a62c71cad07a9f90d6d13a55
