### ISSUE TITLE
The database only works when I sign out or when i'm without auth.

### ISSUE THREAD

**Issue by bacabrother** [firebase/quickstart-unity#40]
The database only works when I sign out, so the changes I make are released as soon as the signout occurs.

 ```
  public void AddInfo(string value) {
        db.GetReference("test1").Child(userId).SetValueAsync(value);
    }
```
the child appear in the database only when I'm signout.

I also noticed that when I send something to the database without authenticating, when I try to authenticate after this, some error occurs

   ```
public void OnlineList() {
        db.GetReference("WhoIsOnline").Child(fbAuth.userId).SetValueAsync("");    
        db.GetReference("WhoIsOnline").Child(fbAuth.userId).OnDisconnect().RemoveValue();
    }
```

When I use this in the Start(), and then I try to auth the app crash, but seems that the auth works because when I restart the app the auth isnt null

**Comment by stewartmiles** [comment]
You mentioned an error occurs, could you share the log output (e.g logcat on Android?).

Also, you mention a crash, again could you share a log of the crash so we can diagnose?

**Comment by bacabrother** [comment]
Ok, and the first part, is it a known issue or is it just me?
I got the bug report, I do not understand much but it seems to be this part:

`01-18 08:06:01.599   985   999 W ActivityManager:   Force finishing activity com.xBarba.FirebaseTest/com.google.firebase.MessagingUnityPlayerActivity
01-18 08:06:01.612  1231  4164 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
01-18 08:06:01.614   985   999 I ActivityManager: Killing 16577:com.xBarba.FirebaseTest/u0a266 (adj 0): user request after error
01-18 08:06:01.620  1231  4164 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.ProcessKillTrigger.sendTrigger:147 com.motorola.motocare.internal.frameworkevents.ProcessKillTrigger.handleFrameworkEvent:164 
01-18 08:06:01.651   260   677 I SFPerfTracer:      triggers: (rate: 0:17) (124853 sw vsyncs) (0 skipped) (404:1087335 vsyncs) (406:1255072)
01-18 08:06:01.681   985  1021 W InputDispatcher: channel '42411858 com.xBarba.FirebaseTest/com.google.firebase.MessagingUnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0xd
01-18 08:06:01.681   985  1021 E InputDispatcher: channel '42411858 com.xBarba.FirebaseTest/com.google.firebase.MessagingUnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-18 08:06:01.682   985  1498 I WindowState: WIN DEATH: Window{42411858 u0 com.xBarba.FirebaseTest/com.google.firebase.MessagingUnityPlayerActivity}
01-18 08:06:01.682   985  1498 W InputDispatcher: Attempted to unregister already unregistered input channel '42411858 com.xBarba.FirebaseTest/com.google.firebase.MessagingUnityPlayerActivity (server)'
01-18 08:06:01.684   985  1480 W MediaFocusControl:   AudioFocus   audio focus client died
01-18 08:06:01.684   985  1480 I MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@41b62148
01-18 08:06:01.696   985  1500 I WindowState: WIN DEATH: Window{42422f98 u0 SurfaceView}
01-18 08:06:01.720  1231  4164 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 android.content.ContextWrapper.sendBroadcast:365 com.motorola.motocare.util.TriggerHelper$TriggerBuilder.send:76 com.motorola.motocare.internal.frameworkevents.PauseResumeTrigger.handleFrameworkEvent:53 com.motorola.motocare.internal.frameworkevents.FwEventMonitor$FrameworkListener.processFrameworkEvent:114 
01-18 08:06:01.957   985  1294 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 16577 uid 10266
01-18 08:06:01.960  1168  1179 W Binder  : Caught a RuntimeException from the binder stub implementation.
01-18 08:06:01.960  1168  1179 W Binder  : java.lang.NullPointerException
01-18 08:06:01.960  1168  1179 W Binder  : 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
01-18 08:06:01.960  1168  1179 W Binder  : 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
01-18 08:06:01.960  1168  1179 W Binder  : 	at android.os.Binder.execTransact(Binder.java:404)
01-18 08:06:01.960  1168  1179 W Binder  : 	at dalvik.system.NativeStart.run(Native Method)
01-18 08:06:01.998   985   998 I LaunchCheckinHandler: cleanup(): cleared. Last call was 56136 ms ago`

**Comment by benwulfe** [comment]
Can you show what your database rules are?

Also I see you are using onDisconnect().  Could it be that the pending changes you are looking for are being written as an ondisconnect?

Have you tried running the plain vanilla database quickstart?  Does that work for you?
