### ISSUE TITLE
Properties of IUserInfo object change after FirebaseUser.UnlinkAsync

### ISSUE THREAD

**Issue by essoperagma** [firebase/quickstart-unity#400]
Unity editor version: 2018.3.14f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, Crashlytics, Messaging, RemoteConfigs
Additional SDKs you are using (Facebook, AdMob, etc.): FacebookSDK, GoogleMobileAds, GooglePlayGames
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10 Home
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android

**Issue:**
Fields of an IUserInfo object acquired by accessing FirebaseUser.ProviderData changes after unlinking the provider.
Steps to reproduce the problem:
1. Signin to a firebase account which has a Play Games account linked.
2. Acquire IUserInfo object of the PlayGames account from FirebaseUser using FirebaseUser.ProviderData.
3. Store "ProviderId" and "UserId" properties of IUserInfo object for later comparison.
4. Unlink PlayGames account from FirebaseUser by calling FirebaseUser.UnlinkAsync instance method.
5. Observe "ProviderId" and "UserId" fields of previously acquired IUserInfo object.

**Expected result:**
"ProviderId" and "UserId" fields at the step 5 should be the same as previously stored values in step 3.

**Observed result:**
"ProviderId" becomes "firebase" and "UserId" becomes the id of the firebase account that we called UnlinkAsync method on.

**Comment by alexames** [comment]
Hi essoperagma, 

This is a known issue that we don't have a solution for yet. It's related to issue #378. Once you unlink an IUserInfo the object is invalid and can change out from under you. We have this on our todo list, but I don't have a timeline right now for when the fix will go out.
