### ISSUE TITLE
[FR] Please add NativeStoreAuthProvider.GetCredential for mobile

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#401]
## Please fill in the following fields:
Firebase Unity SDK version : 6.1.1
Platform : iOS, Android 

## Please describe the issue here:
For unity sdk that could build for both platforms. I think firebase sdk should contain additional API that wrap GooglePlayGames and GameCenterAuth into one for getting credential. And if possible, whenever firebase could support more store provider, it should try to get the store that most suited for user's device

I don't know it could be possible but, I wish that if in the future, firebase support amazon appstore as credential and the instance of my app was downloaded from amazon store, then it would use amazon store userid for credential. Same go for any other supported store in the future. Or the new apple signin

**Comment by alexames** [comment]
Hi Thaina, 

Thanks for the feedback. For requests like these, it helps to fill out our feature request form (which you can find here: https://firebase.google.com/support/) so that we can have the Firebase team evaluate the feature.
