### ISSUE TITLE
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#402]
Is there a reason why i am getting this error (app crash on restart) when installing on android.
 Using Firebase 6.2 (upgraded from 6.0)

Log:

> 07-03 16:21:56.524 15217 15217 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at com.facebook.internal.BoltsMeasurementEventListener.open(BoltsMeasurementEventListener.java:54)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at com.facebook.internal.BoltsMeasurementEventListener.getInstance(BoltsMeasurementEventListener.java:70)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:313)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:42)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1927)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:1902)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:6572)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6127)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.app.ActivityThread.-wrap1(Unknown Source:0)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6938)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.test.game-nZTsXjjfRiMHbLTag7FVOA==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.game-nZTsXjjfRiMHbLTag7FVOA==/lib/arm, /data/app/com.test.game-nZTsXjjfRiMHbLTag7FVOA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 07-03 16:21:56.524 15217 15217 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by stewartmiles** [comment]
`android.support.v4.content` is a legacy Android support library.  Since Google Play Services now uses Jetpack (AndroidX) it's now incompatible with that component.  The Jetifier integration in the Android Resolver should be rewriting references to the legacy Android support library to AndroidX except for cases where a plugin developer has just dropped an aar or jar in the project.

See https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-505036511

We're working on a solution to also patch Android libraries that are not hosted on Maven with the Jetifier but it's not there yet.  You could potentially do this manually using https://developer.android.com/studio/command-line/jetifier

**Comment by ColorTwist** [comment]
I see, thanks.
Your second option in the link is "Upgrade the resolver to 1.2.119, enable the AndroidX build option", 
I do have resolver 1.2.122 and Jetifier enabled. 
Does it mean other than Firebase aar or jar is causing this?

**Comment by stewartmiles** [comment]
Firebase depends upon Google Play Services, Google Play Services moved to Jetpack (AndroidX) in the latest release.  Since - AFAIK - AndroidX can no longer interoperate with the legacy Android support library in the same application this requires the Jetifier to migrate components to AndroidX from the legacy Android support library.

**Comment by stewartmiles** [comment]
In terms of options, all you can do is roll back to an earlier version of the Firebase Android libraries i.e to the release before June 17th https://firebase.google.com/support/release-notes/android#update_-_june_17_2019 .

**Comment by ColorTwist** [comment]
Okay, thanks for the explanation!
Hopefully, we'll see resolver update soon for that.

**Comment by CConstantinou** [comment]
Hello guys, Do we have any news about this issue?

**Comment by fedsbm** [comment]
We are still having this problem with latest firebase, is this case not solved?

**Comment by JustAguiar** [comment]
Somewhere I found that 'implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0' solves this issues.
