### ISSUE TITLE
Emojis are being displayed incorrectly in notifications on Android 4.4.2 - Lenovo Tab 2

### ISSUE THREAD

**Issue by JabluszkoPL** [firebase/quickstart-unity#404]
Description:
Emojis are displayed as random special characters - possible error
![Screenshot](https://user-images.githubusercontent.com/10673669/60668268-dabcb400-9e6b-11e9-90ff-6f32a911aa70.png)

Firebase SDK version: 
6.0.0

Device: 
Lenovo Tab 2 A7-10F 
Android 4.4.2

How to reproduce:
1) Launch the app
2) Close app
3) Create a notification with emojis
4) Send and view the notification

Expected:
Emojis should be displayed correctly.

**Comment by a-maurice** [comment]
Hi @JabluszkoPL,

We will look into this issue.  In the meantime, what version of Unity are you using?

**Comment by JabluszkoPL** [comment]
Hi @a-maurice ,
I'm using 2018.3 and 2019.1

**Comment by alexames** [comment]
Can you give an example message here that have emojis that aren't showing up? I tried this locally just now and the emojis seemed to go through without an issue. If I can get a known repro case we can investigate easier.

**Comment by JabluszkoPL** [comment]
I just tested on LG devices (2) with 4.4.2 android 
Notification Title😙😚😝👻🎁🏬🏨

![Screenshot_2019-07-26-13-55-33](https://user-images.githubusercontent.com/10673669/61952026-0b979100-afb3-11e9-835c-fd24f550b660.png)
![Screenshot_2019-07-26-13-56-01](https://user-images.githubusercontent.com/10673669/61952027-0b979100-afb3-11e9-8e81-227d272de2f7.png)

**Comment by JabluszkoPL** [comment]
Just checked on 2 LG with android 4.4.2
Notification text is: Notification Title😙😚😝👻🎁🏬🏨
![Screenshot_2019-07-26-13-56-01](https://user-images.githubusercontent.com/10673669/61954345-f4f43880-afb8-11e9-8f88-ac1050a8c3d2.png)
![Screenshot_2019-07-26-13-55-33](https://user-images.githubusercontent.com/10673669/61954346-f4f43880-afb8-11e9-90d2-676548eace83.png)

**Comment by ciarand** [comment]
Hi @JabluszkoPL, we're going to need a little more detail to help diagnose this. All our local tests are displaying emoji notifications correctly.

How are you sending the message? Is it via the Firebase console or are you using one of our admin SDKs or the cURL command in the README?

**Comment by chkuang-g** [comment]
@JabluszkoPL 
I'm closing the issue since it's been 3 weeks with no response.
Please let us know if this still happens to you and provide us more information.

Shawn
