### ISSUE TITLE
Crashlytics is shut down, LogException failed

### ISSUE THREAD

**Issue by epsmarkh** [firebase/quickstart-unity#406]
## Please fill in the following fields:
Unity editor version: 2019.1.8f1
Firebase Unity SDK version: 6.2.0
Firebase plugins in use (Auth, Database, etc.): Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): none
Platform you are using the Unity editor on (Mac, Windows, or Linux): windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
All crashlytics functions report "Crashlytics is shut down, LogException failed"

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

Yes, the quickstart crashlytics project does this too. Extract log made using the sample project:

07-04 14:57:33.150: I/Unity(21730): Causing a platform crash.
07-04 14:57:33.150: I/Unity(21730): UnityEngine.Logger:Log(LogType, Object)
07-04 14:57:33.150: I/Unity(21730): Firebase.Sample.Crashlytics.UIHandler:DebugLog(String)
07-04 14:57:33.150: I/Unity(21730): Firebase.Sample.Crashlytics.UIHandler:ThrowUncaughtException()
07-04 14:57:33.150: I/Unity(21730): Firebase.Sample.Crashlytics.UIHandler:GUIDisplayControls()
07-04 14:57:33.150: I/Unity(21730): Firebase.Sample.Crashlytics.UIHandler:OnGUI()
07-04 14:57:33.150: I/Unity(21730):  
07-04 14:57:33.150: I/Unity(21730): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
07-04 14:57:33.170: W/Unity(21730): Crashlytics is shut down, LogException failed
07-04 14:57:33.170: W/Unity(21730): UnityEngine.Logger:Log(LogType, Object)
07-04 14:57:33.170: W/Unity(21730): UnityEngine.LogCallback:Invoke(String, String, LogType)
07-04 14:57:33.170: W/Unity(21730): UnityEngine.Application:CallLogCallback(String, String, LogType, Boolean)
07-04 14:57:33.170: W/Unity(21730):  
07-04 14:57:33.170: W/Unity(21730): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
07-04 14:57:33.170: E/Unity(21730): InvalidOperationException: Uncaught exception created from UI.
07-04 14:57:33.170: E/Unity(21730):   at Firebase.Sample.Crashlytics.UIHandler.ThrowUncaughtException () [0x00000] in <00000000000000000000000000000000>:0 
07-04 14:57:33.170: E/Unity(21730):   at Firebase.Sample.Crashlytics.UIHandler.GUIDisplayControls () [0x00000] in <00000000000000000000000000000000>:0 
07-04 14:57:33.170: E/Unity(21730):   at Firebase.Sample.Crashlytics.UIHandler.OnGUI () [0x00000] in <00000000000000000000000000000000>:0 
07-04 14:57:33.170: E/Unity(21730):  
07-04 14:57:33.170: E/Unity(21730): (Filename: currently not available on il2cpp Line: -1)

**Comment by alperki** [comment]
We are also experiencing the same issue with the new firebase sdk (6.2.0) . All static method calls of Crashlytics ends up with warning message : Crashlytics is shut down, X failed.

**Comment by zbyhoo** [comment]
Same here. I was trying to update Fabric Crashlytics SDK to newest Firebase Crashlytics 6.2.0.

**Comment by vinters768** [comment]
Same here.. @zbyhoo @alperki are you getting any reports to Firebase Console?

**Comment by Unarmed1000** [comment]
Same issue here after updating to 6.2

**Comment by zbyhoo** [comment]
@vinters768 after this error I reverted SDK to Fabric and I'm waiting for resolution of this issue.

**Comment by a-maurice** [comment]
Hi all, we are looking into it, and will keep you updated.  As a workaround, you can try using the previous version, available at https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_6.1.1.zip

**Comment by a-maurice** [comment]
Hey all,

I believe we have tracked down the problem, and will have a new version of the SDK available with the fix shortly.  In the meantime, if you would like to try it, you can unzip the following file: 
[Firebase.Crashlytics.dll.zip](https://github.com/firebase/quickstart-unity/files/3375053/Firebase.Crashlytics.dll.zip), and replace the Firebase.Crashlytics.dll file that should be in Assets/Firebase/Plugins with it.

**Comment by vinters768** [comment]
after replacing the .dll not seeing the error anymore, it looks like crashlytics is being initialized correctly now, thanks again!

**Comment by rudragesota** [comment]
replacing did not work for IL2CPP Settings. please, can you help us with that?
Crashing on start. Thanks

**Comment by malyawka** [comment]
> Hey all,
> 
> I believe we have tracked down the problem, and will have a new version of the SDK available with the fix shortly. In the meantime, if you would like to try it, you can unzip the following file:
> [Firebase.Crashlytics.dll.zip](https://github.com/firebase/quickstart-unity/files/3375053/Firebase.Crashlytics.dll.zip), and replace the Firebase.Crashlytics.dll file that should be in Assets/Firebase/Plugins with it.

`Mono.CompilerServices.SymbolWriter.MonoSymbolFileException: Symbol file Assets/Firebase/Plugins/Firebase.Crashlytics.dll.mdb does not match assembly`

@a-maurice ,  this not critical?

**Comment by a-maurice** [comment]
A hotfix, version 6.2.1, is now available which should have this fixed, which is available [here](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_6.2.1.zip).

And sorry about missing the mdb file, I'll make sure that if we need to share Dlls like this in the future we include that as well.
