### ISSUE TITLE
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.

### ISSUE THREAD

**Issue by ajinkyapuar** [firebase/quickstart-unity#407]
## Please fill in the following fields:

Unity editor version: **2019.1.0f2**
Firebase Unity SDK version: **6.2.0**
Firebase plugins in use (Auth, Database, etc.): **Auth**
Additional SDKs you are using (Facebook, AdMob, etc.): **NA**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Mac**
Platform you are targeting (iOS, Android, and/or desktop): **Android & iOS**
Misc Unity Package in use : [Mobile Media Picker](https://assetstore.unity.com/packages/tools/integration/mobile-media-picker-complete-template-122031)

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

> D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

> Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.

> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/0.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/1.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/2.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/4.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/5.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/6.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/7.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/8.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/9.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/10.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/11.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/12.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/13.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/14.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/15.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/17.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/18.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/19.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/20.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/21.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/22.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/23.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/24.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/25.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/26.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/27.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/28.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/29.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/31.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/33.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/34.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/35.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/36.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/37.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/38.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/39.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/40.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/41.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/42.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/43.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/44.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/45.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/46.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/48.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/49.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/50.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/51.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/53.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/54.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/55.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/56.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/57.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/58.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/59.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/60.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/61.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/62.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/63.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/66.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/67.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/68.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/69.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/70.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/71.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/75.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/76.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/77.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/78.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/80.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/81.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/83.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/85.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/86.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/87.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/88.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/89.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/90.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/91.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/92.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/93.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/94.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/95.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/97.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/98.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/99.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/101.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/102.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/103.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/104.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/105.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/106.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/107.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/108.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/109.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/110.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/111.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/112.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/113.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/114.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/115.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/116.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/117.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/118.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/119.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/120.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/121.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/122.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/123.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/124.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/125.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/126.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/127.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/128.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/129.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/130.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/131.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/132.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/133.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/134.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/135.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/136.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/137.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/138.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/139.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/140.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/141.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/142.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/143.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/144.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/145.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/146.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/147.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/148.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/149.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/150.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/151.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/152.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/153.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/154.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/155.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/156.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/157.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/158.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/159.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/160.jar, /Users/ajinkyapuar/Desktop/mobile-app/Temp/gradleOut/build/inter<message truncated>

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
**No**

**Comment by a-maurice** [comment]
Hi @ajinkyapuar 

The Android libraries have recently been updated which changes where base dependencies are defined, which seems to be the problem you are running into.  If you could try to reproduce this in the quickstarts, that might help us narrow down what exactly is causing your issue.  Thanks

**Comment by chkuang-g** [comment]
@ajinkyapuar 
Closing this issue since there is no response for 2 weeks.
Please let us know if you are still having issue with it.

**Comment by mhaji1375** [comment]
I have the same issue? so what did he do to solve the problem?

**Comment by chkuang-g** [comment]
@mhaji1375 
We do not know since @ajinkyapuar never responded.

This issue is closed.  If similar issue occurs to you, please file a new issue and fill up the template.

Thank you,
Shawn
