### ISSUE TITLE
Can't create Build for iOS - Firebase.Editor.XcodeProjectPatcher.ApplyNsUrlSessionWorkaround => PlistParser.cs (InvalidCastException)

### ISSUE THREAD

**Issue by juaxma** [firebase/quickstart-unity#408]
## Please fill in the following fields:
Unity editor version: 2018.3.14f / 2018.4.3f1
Unity Scripting Runtime version: .NET 4.x Equivalent
Firebase Unity SDK version: 6.3.0 / 6.2.0 / 6.1.1
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, Database
Additional SDKs you are using (Facebook, AdMob, etc.): GoogleMobileAds
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
1.- Build to an Xcode project

> InvalidCastException: Specified cast is not valid.
UnityEditor.iOS.Xcode.PlistElement.AsBoolean () (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PlistParser.cs:22)
Firebase.Editor.XcodeProjectPatcher.ApplyNsUrlSessionWorkaround (UnityEditor.BuildTarget buildTarget, System.String pathToBuiltProject) (at <02ccfbc47d26479eba09972331d0433d>:0)
Firebase.Editor.XcodeProjectPatcher.OnPostProcessPatchProject (UnityEditor.BuildTarget buildTarget, System.String pathToBuiltProject) (at <02ccfbc47d26479eba09972331d0433d>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:158)
UnityEditor.Build.BuildPipelineInterfaces+<OnBuildPostProcess>c__AnonStorey2.<>m__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:398)
UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:356)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by juaxma** [comment]
Removing all Firebase files and reimporting again to 6.2.0 everything seems to be ok

**Comment by juaxma** [comment]
... and it’s happening again

I just reimported the play services for unity because it was not generating a podfile, and now I can’t create a build... same problem on unity editor

**Comment by a-maurice** [comment]
Looking at the relevant code, that would be happening because in the Info.plist file, it defines NSAppTransportSecurity, and in that dictionary NSAllowsArbitraryLoadsInWebContent is defined, but not parsing as a boolean.

Can you look at your Info.plist, and see if those values are being defined, and if so what are they being defined as?

**Comment by chkuang-g** [comment]
Closing this issue for being inactive for 2 weeks.
Please let us know if you tried what @a-maurice mentioned and still having the issue.

**Comment by novavision** [comment]
> Looking at the relevant code, that would be happening because in the Info.plist file, it defines NSAppTransportSecurity, and in that dictionary NSAllowsArbitraryLoadsInWebContent is defined, but not parsing as a boolean.
> 
> Can you look at your Info.plist, and see if those values are being defined, and if so what are they being defined as?

I got the same issue using Dynamic Links only on latest sdk v.6.2.2 (same happens on 6.2.0)
Unity 2019.1

I have checked .plist and it does contains NSAppTransportSecurity set tot YES and there is no NSAllowsArbitraryLoadsInWebContent key. Any suggestions?

**Comment by stewartmiles** [comment]
@novavision

**Comment by stewartmiles** [comment]
@novavision could you share your Info.plist it sounds like we're running into an issue with Unity's Xcode API (we're using that to parse the plist).  It should be interpreting the existing key as a boolean if the XML tag is `<true/>` or `<false/>` see https://bitbucket.org/Unity-Technologies/xcodeapi/src/fbd0cb184b437b751ac0e2213779c310aaba0952/Xcode/PlistParser.cs#lines-296 . 

We will change our code to check for an exception when trying to convert the `NSAllowsArbitraryLoads` key to a boolean value but it would be great to understand how your Info.plist is causing this to happen.

**Comment by novavision** [comment]
Here it is.

`<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>CADisableMinimumFrameDuration</key>
    <false />
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>Pinart</string>
    <key>CFBundleExecutable</key>
    <string>${EXECUTABLE_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>io.pinart.${PRODUCT_NAME}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${PRODUCT_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0.3</string>
    <key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>google</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>com.googleusercontent.apps.722850757791-3a6urqftkk0d3qtg324i7hndub146eoh</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>io.pinart.app</string>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>io.pinart.app</string>
        </array>
      </dict>
    </array>
    <key>CFBundleVersion</key>
    <string>0</string>
    <key>ITSAppUsesNonExemptEncryption</key>
    <false />
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>whatsapp</string>
      <string>fb</string>
      <string>twitter</string>
    </array>
    <key>LSRequiresIPhoneOS</key>
    <true />
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <string>True</string>
    </dict>
    <key>NSCameraUsageDescription</key>
    <string>Allow camera access to enjoy the AR experience</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Allow tracking for general preformace improvement</string>
    <key>NSPhotoLibraryAddUsageDescription</key>
    <string>$(PRODUCT_NAME) saves images to photo library</string>
    <key>NSPhotoLibraryUsageDescription</key>
    <string>$(PRODUCT_NAME) uses photo library</string>
    <key>UIApplicationExitsOnSuspend</key>
    <false />
    <key>UILaunchStoryboardName~ipad</key>
    <string>LaunchScreen-iPad</string>
    <key>UILaunchStoryboardName~iphone</key>
    <string>LaunchScreen-iPhone</string>
    <key>UILaunchStoryboardName~ipod</key>
    <string>LaunchScreen-iPhone</string>
    <key>UIPrerenderedIcon</key>
    <false />
    <key>UIRequiredDeviceCapabilities</key>
    <array>
      <string>armv7</string>
    </array>
    <key>UIRequiresFullScreen</key>
    <true />
    <key>UIRequiresPersistentWiFi</key>
    <false />
    <key>UIStatusBarHidden</key>
    <true />
    <key>UIStatusBarStyle</key>
    <string>UIStatusBarStyleDefault</string>
    <key>UISupportedInterfaceOrientations</key>
    <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
    </array>
    <key>Unity_LoadingActivityIndicatorStyle</key>
    <integer>-1</integer>
    <key>UnityCloudProjectID</key>
    <string></string>
    <key>UnityCrashSubmissionURL</key>
    <string></string>
  </dict>
</plist>
`

**Comment by juaxma** [comment]
Any new information about this problem? I have tried with version 6.3.0 and it keeps happening.

<key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <string>True</string>
    </dict>

**Comment by juaxma** [comment]
6.4.0 fix the problem
Release Notes: (FIXED) (iOS) Handle malformed Info.plist files when patching Xcode projects.

Thanks!
