### ISSUE TITLE
Please add const string or static property string ProviderId to each available AuthProvider

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#410]
Not important but I think if the ProviderID of AuthProvider is constant, it should available to get from static without creating credential first. So we can use it to check with user's `ProviderData` without the need to get the credential first

Currently now if we want to programmatically know the ProviderID

Instead of just

```C#
var user = await FirebaseAuth.DefaultInstance.SignInWithCustomTokenAsync(customToken);
if(!user.ProviderData.Any((provider) => provider.ProviderId == GameCenterAuthProvider.ProviderID)))
    await user.LinkWithCredentialAsync(await GameCenterAuthProvider.GetCredentialAsync());
```

We need to login with that provider first like this

```C#
var user = await FirebaseAuth.DefaultInstance.SignInWithCustomTokenAsync(customToken);

var credential = await GameCenterAuthProvider.GetCredentialAsync();
if(!user.ProviderData.Any((provider) => provider.ProviderId == credential.Provider)))
    await user.LinkWithCredentialAsync(credential.Provider);
```

And user might not want to logged in so we will not get the credential

js SDK also contain this property so unity sdk should be the same

**Comment by a-maurice** [comment]
Thanks for the suggestion.

**Comment by Thaina** [comment]
Is it available now?

**Comment by stewartmiles** [comment]
@Thaina not yet

**Comment by patm1987** [comment]
Apologies for the silence on this issue, but this change should be in as of [6.9.0](https://firebase.google.com/support/release-notes/unity#version_690_-_december_27_2019)

Thanks for waiting!
--Patrick
