### ISSUE TITLE
iOS - Xcode: linker command failed with exit code 1

### ISSUE THREAD

**Issue by MichelPro** [firebase/quickstart-unity#413]
Unity editor version: 2018.2.20f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.):Analytics、RemoteConfig
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): IOS

What steps will reproduce the problem:
1.Upgrade Firebase Version from 5.2.1 to 6.1.1
2.Export to XCode
3.Update Google-Mobile-Ads-SDK to 7.46.0
4.Build in XCode Failed

Log:
```

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/michel/XCodeProject/SudokuTemp/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_Firebase_App_FirebaseApp_ReleaseReferenceInternal", referenced from:
      _AppUtilPINVOKE_Firebase_App_FirebaseApp_ReleaseReferenceInternal_m3955561404 in Bulk_Firebase.App_0.o
      _FirebaseApp_ReleaseReferenceInternal_m2632704087 in Bulk_Firebase.App_0.o
     (maybe you meant: _AppUtilPINVOKE_Firebase_App_FirebaseApp_ReleaseReferenceInternal_m3955561404)
  "_Firebase_App_GetEnabledAppCallbackByName", referenced from:
      _AppUtil_GetEnabledAppCallbackByName_m2220055647 in Bulk_Firebase.App_0.o
      _AppUtilPINVOKE_Firebase_App_GetEnabledAppCallbackByName_m3221530277 in Bulk_Firebase.App_0.o
     (maybe you meant: _AppUtilPINVOKE_Firebase_App_GetEnabledAppCallbackByName_m3221530277)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by a-maurice** [comment]
Hi @MichelPro 

It sounds like a library is missing for you.  In your Unity project, if you look in Assets/Firebase/Plugins/iOS, do you have Firebase.App.dll?  If you look in Assets/Plugins/iOS/Firebase, do you have libFirebaseCppApp.a?

In the project generated for Xcode, under your project's Linked Frameworks and Libraries, is libFirebaseCppApp.a listed?

**Comment by MichelPro** [comment]
Thanks for your replay @a-maurice 
 I have done what you said before I added this issue.
But it still failed when I  build project.
I upgraded from version 5.2.1 to version 6.1.1.
It build successful in version 5.2.1.

**Comment by a-maurice** [comment]
The error is definitely about a missing file, though if all those files are there, I'm not sure why it would be missing from the XCode build.  Perhaps a file got excluded when installing the newer version on accident?  Could you try installing the unitypackage again?  Alternatively, you could try deleting the Firebase SDK, to guarantee that all the files are removed, though unfortunately it must be done manually, and then try reinstalling it.

**Comment by MichelPro** [comment]
Thanks!!!!!
It build succeed!

**Comment by a-maurice** [comment]
Great, thanks for following up.
