### ISSUE TITLE
Unauthenticated at Firebase Functions HttpsCallableReference

### ISSUE THREAD

**Issue by montreal-qc-ca-earth** [firebase/quickstart-unity#415]
Firebase 6.2.0
Unity 2018.3.13f1
.NET 4.x

I used this sample code after anonymous auth completed, 
Error Message:

Error: System.AggregateException: One or more errors occurred. ---> Firebase.Functions.FunctionsException: Unauthenticated
  at Firebase.Functions.HttpsCallableReference.<CallAsync>m__0 (System.Threading.Tasks.Task`1[TResult] task) [0x0004b] in Z:\tmp\tmp.UKVnYpbOyJ\firebase\functions\client\unity\proxy\HttpsCallableReference.cs:74 
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00024] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.Functions.FunctionsException: Unauthenticated
  at Firebase.Functions.HttpsCallableReference.<CallAsync>m__0 (System.Threading.Tasks.Task`1[TResult] task) [0x0004b] in Z:\tmp\tmp.UKVnYpbOyJ\firebase\functions\client\unity\proxy\HttpsCallableReference.cs:74 
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00024] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 <---

UnityEngine.Debug:Log(Object)
<>c:<AddNumbers>b__10_0(Task`1) (at Assets/scrUserFirebase.cs:105)
Firebase.Extensions.<ContinueWithOnMainThread>c__AnonStorey9:<>m__0() (at Z:/tmp/tmp.2zH29dVReE/firebase/app/client/unity/task-extension/TaskExtension.cs:112)
Firebase.<RunAsync>c__AnonStorey1`1:<>m__0() (at Z:/tmp/tmp.gevFFDgvJM/firebase/app/client/unity/src/Platform/Dispatcher.cs:61)
Firebase.ExceptionAggregator:Wrap(Action) (at Z:/tmp/tmp.gevFFDgvJM/firebase/app/client/unity/src/Platform/ExceptionAggregator.cs:98)
Firebase.Dispatcher:PollJobs() (at Z:/tmp/tmp.gevFFDgvJM/firebase/app/client/unity/src/Platform/Dispatcher.cs:107)
Firebase.Platform.FirebaseHandler:Update() (at Z:/tmp/tmp.gevFFDgvJM/firebase/app/client/unity/src/Unity/FirebaseHandler.cs:188)
Firebase.Platform.FirebaseMonoBehaviour:Update() (at Z:/tmp/tmp.gevFFDgvJM/firebase/app/client/unity/src/Unity/FirebaseMonoBehaviour.cs:29)

**Comment by stewartmiles** [comment]
@montreal-qc-ca-earth you solved your issue?

**Comment by temelal** [comment]
actually no. when i see this code run without auth code, i closed the issue.
but when add the auth code again i saw same problem again.

**Comment by stewartmiles** [comment]
What platform are you running on?  Are you able to reproduce this issue in our sample code?

**Comment by dakimaru** [comment]
Happens to me as well.
Firebase 6.2.0
Unity 2019.1.9f1
.NET 4.x

Running on MacOS 10.14.4
Unity Target iOS, Android

Code:
![image](https://user-images.githubusercontent.com/1298467/61096587-1d494680-a493-11e9-9608-feae093032ca.png)

Debugger Output:
![image](https://user-images.githubusercontent.com/1298467/61096688-7618df00-a493-11e9-83c8-7fade8e596b7.png)

**Comment by chkuang-g** [comment]
Hi folks,

I think this is one of the two cases:
1. If you have not used FirebaseAuth to sign-in before, you should.  I think @montreal-qc-ca-earth did sign-in before using FirebaseFunctions API.
2. If you have used FirebaseAuth sign-in before, it is possible that FirebaseAuth is GCed when you are using FirebaseFunctions.  If so, FirebaseFunctions cannot forward the proper auth token and may result in the exception.  We are trying to change Unity SDK to not reference FirebaseAuth after it is created.  But before that, your best bet is to keep a static reference to FirebaseAuth.

Please let us know which case you are in.  Thank you!
Shawn

**Comment by RaidelRoss** [comment]
The same happens to me
No matter what I do, I always have the same problem
the official sample code does not solve the problem

Firebase 6.2.1
Unity 2018.3.5f1
.NET 4.x

 Error: System.AggregateException: One or more errors occurred. ---> Firebase.Functions.FunctionsException: UNAUTHENTICATED at Firebase.Functions.HttpsCallableReference.<CallAsync>m__0 (System.Threading.Tasks.Task`1[TResult] task) [0x00056] in <b6dc13d6f8ee4449b12732293a4ddba7>:0 at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00024] in <d7ac571ca2d04b2f981d0d886fa067cf>:0  ...

**Comment by stewartmiles** [comment]
Folks as @chkuang-g pointed out you need to sign-in with FirebaseAuth _and_ hold a reference to the FirebaseAuth object if you want to remain authenticated.  If you're still running into an issue, please fork our functions sample with auth integrated and share it with us, then we'll take a look.

**Comment by Azale29** [comment]
How do i hold a reference?
