### ISSUE TITLE
 Showing Recent Messages :-1: Library not found for -lFirebaseCore in xcode project

### ISSUE THREAD

**Issue by santosh9604** [firebase/quickstart-unity#419]
Unity editor version: 2019.1.6
Firebase Unity SDK version: 6.2.1
Firebase plugins in use (Auth, Database, etc.): Analytics
Platform you are using the Unity editor on (Mac, Windows, or Linux): Macbook pro
Platform you are targeting (iOS, Android, and/or desktop): ios

Hi ,
I am trying to build a sample unity app for ios for Firebase Analytics feature. I used quickstart-unity demo for build and i follow the documentation of Firebase installation as well. Still am getting error " **Showing Recent Messages :-1: Library not found for -lFirebaseCore** " while building in xcode.I try to find solution on google , but don't find exact issue with solution.
Please ignore my English.

 This is what i get 👍 
ld: warning: directory not found for option '-L/Users/sattvarise/Library/Developer/Xcode/DerivedData/Unity-iPhone-algppzjqnlcqllfxqcgmkcwmjatj/Build/Products/ReleaseForRunning-iphoneos/FirebaseCore'
ld: warning: directory not found for option '-L/Users/sattvarise/Library/Developer/Xcode/DerivedData/Unity-iPhone-algppzjqnlcqllfxqcgmkcwmjatj/Build/Products/ReleaseForRunning-iphoneos/FirebaseInstanceID'
ld: warning: directory not found for option '-L/Users/sattvarise/Library/Developer/Xcode/DerivedData/Unity-iPhone-algppzjqnlcqllfxqcgmkcwmjatj/Build/Products/ReleaseForRunning-iphoneos/GoogleUtilities'
ld: warning: directory not found for option '-L/Users/sattvarise/Library/Developer/Xcode/DerivedData/Unity-iPhone-algppzjqnlcqllfxqcgmkcwmjatj/Build/Products/ReleaseForRunning-iphoneos/nanopb'
**_ld: library not found for -lFirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)_**

Thanks in advance.

**Comment by alexames** [comment]
Hmm... That issue doesn't look familiar to me. 

You followed the directions here, right?

https://github.com/firebase/quickstart-unity/blob/master/analytics/testapp/readme.md#ios

Did you follow all the directions exactly? I would recommend starting with a fresh copy of hte repository and trying again from the beginning, making sure to follow each step exactly. It sounds like maybe something went wrong when importing the Firebase package into Unity.

**Comment by chkuang-g** [comment]
Hi @santosh9604 
We have not heard from you for awhile.  If the error still occurs, please let us know the exact steps to reproduce your issue.
I will close this bug for now.
