### ISSUE TITLE
firebase_unity_sdk_1.1.1 require Xcode 8 or higher?

### ISSUE THREAD

**Issue by T264** [firebase/quickstart-unity#42]
The specifications are as follows

> https://firebase.google.com/docs/unity/setup
> Xcode 7.0 or later.

> https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp
> Xcode 7.3 or higher (when developing for iOS).

However, it also has the following description.

> https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp
> In the window that appears, scroll to UserNotifications.framework and click on that entry, then click on Add. This framework will only appear in Xcode version 8 and higher, required by this library.

Actually, when I use Xcode7 or Xcode8 without UserNotifications.framework, the following error will appear.
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UNUserNotificationCenter", referenced from:
      objc-class-ref in libMessaging.a
```

Is there no way to use firebase_unity_sdk_1.1.1 in Xcode 7.x?

**Comment by tfe2012** [comment]
I get same error

**Comment by stewartmiles** [comment]
It looks like we ended up with a hard reference to the notification
framework in the messaging library which caused the Xcode 8 requirement.
We're testing a fix now (change to a weak reference) and will post an
update shortly.

**Comment by jonsimantov** [comment]
Version 1.1.2 of the Firebase Unity SDK has been released, which removes the Xcode 8 requirement. You can view the release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.2) and download the release from https://firebase.google.com/docs/unity/setup.

**Comment by tfe2012** [comment]
Thx
