### ISSUE TITLE
Bundle ID is inconsistent

### ISSUE THREAD

**Issue by superarts** [firebase/quickstart-unity#422]
I know several people are asking similar questions, but I can't find out where my problem is. I created 2 iOS apps for my "main" app and Today Widget app. They have different IDs. Whilst my main app works fine, Today Widget complains:

```
6.4.0 - [Firebase/Core][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'com.deloitte.lilly.vega.today.extension'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
```

I even tried to set up a break point and `po Bundle.main.bundleIdentifier`, and it's the same as I put in the pist file, which I put under `Today Widget` target. Of course, it's the same as the bundle ID that shows in Xcode.

If it's open source, it would be very easy for me to dig out what the problem is. And now I have to deal with this blackbox, which is very frustrating. Without sharing my code I can't even prove what I said was true.

**Comment by superarts** [comment]
I mean, how hard is it to add something like "The project's Bundle ID YOUR_BUNDLE_ID_HERE is inconsistent with either the Bundle ID in 'GoogleService-Info.plist'"??

**Comment by alexames** [comment]
Are you using different plist files for each app? Have you verified that each of your apps has a bundle ID in the Unity editor that matches what specified in the Firebase Console? It sounds like the plist file is expecting a bundle ID of "com.deloitte.lilly.vega.today.extension" - does that match what you have in the editor?
