### ISSUE TITLE
Include google sign-in with FirebaseAuth

### ISSUE THREAD

**Issue by jmarisalandanan** [firebase/quickstart-unity#426]
Feature request to include google sign-in with firebase auth. It would be really nice to have it built in and not having to write a wrapper or integrate a separate SDK for this. I think same goes for Facebook/Twitter.

**Comment by Thaina** [comment]
No please. It make the package bloated and not all of them will be used. If we pack twitter sdk inside firebase but I use just facebook then the twitter package would be just useless parts that added into the file size and dex header in my app

We should just wait for UPM or similar tech to let firebase make a package that could specify dependency

**Comment by alexames** [comment]
Thanks for the feedback. For feature requests like these, it helps to fill out our feature request form (which you can find here: https://firebase.google.com/support/) so that we can have the Firebase team evaluate the feature.
