### ISSUE TITLE
Sms is Not Received 

### ISSUE THREAD

**Issue by NAYEK82** [firebase/quickstart-unity#427]
## Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: 
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): 

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Hi All 

I am working in Unity Firebase. Where i  have downloaded  quick start code. and  i have enabled firebase  phone authentication  and i have downloaded google-services.json.
While i  build and run the apk. When i give the phone number and click the button  the sms is not received. 

Whats wrong ? I did not add any Sha1 certificate. Did Sha1 signing certificate is needed for sending SMS?

**Comment by alexames** [comment]
I believe a sha1 cert is requried. 

https://firebase.google.com/docs/auth/android/phone-auth

> If you haven't already set your app's SHA-1 hash in the Firebase console, do so. See Authenticating Your Client for information about finding your app's SHA-1 hash.

**Comment by chkuang-g** [comment]
Hi @NAYEK82 
Does SHA1 Cert resolve your issue?

**Comment by NAYEK82** [comment]
@alexjames thanks for your reply. @cnkuang  .. ya we need Sha1  certificate needed for  that. I have added in player console. Now it is working.  you can find sha1 certificate in google player console.  I did  not remember the exact location. But it is in Google Play Console. If you need I will post it exact location.
But Sha1 Certificate is needed for Sending SMS.
