### ISSUE TITLE
iOS app does not load after adding messaging lib

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#43]
With version 1.1.1, after adding the messaging lib, I have to add UserNotification.framework manually to the iOS project, and our app does not load. It gives a black screen. In the debug console, it doesn't give any error message.

Device: iPhone 6+
OS: 9.3.2

It works fine on iPhone 6 with OS 9.3.5 and all other iPhones that we have running OS 10+.

**Comment by stewartmiles** [comment]
Could you share the log up to the hang?  Is this reproducible with our quickstart sample?

**Comment by stewartmiles** [comment]
We fixed this issue in 1.1.2 and many more in 3.0.0, check out the latest release https://firebase.google.com/support/release-notes/unity#3.0.0
