### ISSUE TITLE
MethodAccessException same as Issue 384

### ISSUE THREAD

**Issue by IvzhenkoOleksii** [firebase/quickstart-unity#430]
## Please fill in the following fields:
Unity editor version: 2019.1.8f1
Firebase Unity SDK version: 6.2.1
Firebase plugins in use (Auth, Database, etc.): Messaging, DynamicLInks
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, GameAnalytics, GameOfWhales
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): ios + android

## Please describe the issue here:
Try to update Firebase from version 5.5.0 to 6.2.1. after update on any Scene recieve a lot of such errors:

MethodAccessException: Method `Google.RunOnMainThread.Run(System.Action,bool)' is inaccessible from method `Firebase.Editor.NetSDKChecker..cctor()'
Firebase.Editor.NetSDKChecker..cctor () (at Z:/tmp/tmp.lUJ3Ncf6L3/firebase/app/client/unity/editor/src/NetSdkChecker.cs:21)

MethodAccessException: Method `Google.RunOnMainThread.Run(System.Action,bool)' is inaccessible from method `Firebase.Editor.GenerateXmlFromGoogleServicesJson..cctor()'
Firebase.Editor.GenerateXmlFromGoogleServicesJson..cctor () (at Z:/tmp/tmp.lUJ3Ncf6L3/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:88)

Update to latest play-services-resolver (v1.2.122.0) as it was a solution in issue 384 didn`t help.

**Comment by chkuang-g** [comment]
Hi @IvzhenkoOleksii 

You seems to used an older version of Play Services Resolver which has not expose Google.RunOnMainThread().  
https://github.com/googlesamples/unity-jar-resolver/commit/cea8035e3cec7551779f2b0e8a2ee56dec2de17d#diff-8b0683bb75d78519adeed5d3b7684470

The Play Service Resolver coming with 6.2.1 should includes this change already.

Could you try to
1. Close your editor
2. Remove Play Service Resolver entirely. (Under Assets/PlayServicesResolver)
3. Open Unity Editor
4. Reimport the latest Play Service Resolver
https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.124

Shawn

**Comment by IvzhenkoOleksii** [comment]
Hi, it seems to help. Thanks
