### ISSUE TITLE
Crashlytics: Unity SDK 6.2.2 (java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR))

### ISSUE THREAD

**Issue by Vah94** [firebase/quickstart-unity#435]
## Please fill in the following fields:
Unity editor version: 2018.4.4f1 
Firebase Unity SDK version: 6.2.2 
Firebase plugins in use (Analytics, Crashlytics, DynamicLink, RemoteConfig):
Additional SDKs you are using (Facebook, Applovin, Appsflyer.): 
Platform you are using the Unity editor on (Windows): 
Platform you are targeting (Android): 

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
The game freezes during an error.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No

******************************************************************
08-02 14:47:09.614 700-887/? E/MessageQueue: IdleHandler threw exception
    java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    Build fingerprint: 'samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU5DSFB:user/release-keys'
    Revision: '10'
    pid: 700, tid: 887, name: UnityMain  >>> com.companyname.gamename<<<
        r0 00000001  r1 a6ff05c0  r2 b431a1a0  r3 cea97d60
        r4 b431a1a0  r5 a6ff05c0  r6 00000000  r7 00000000
        r8 00000000  r9 00000004  sl cea98470  fp cea97da8
        ip bd73a708  sp cea97d28  lr bd683b03  pc bd683734  cpsr 00000377
    
        at libFirebaseCppApp-6_2_2.firebase::crashlytics::internal::CrashlyticsInternal::LogException(char const*, char const*, std::__ndk1::vector<firebase::crashlytics::Frame, std::__ndk1::allocator<firebase::crashlytics::Frame> >)(crashlytics:19)
        at libFirebaseCppApp-6_2_2.firebase::crashlytics::Crashlytics::LogException(char const*, char const*, std::__ndk1::vector<firebase::crashlytics::Frame, std::__ndk1::allocator<firebase::crashlytics::Frame> >)(crashlytics:26)
        at libFirebaseCppApp-6_2_2.Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException(Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException:54)

[bug.txt](https://github.com/firebase/quickstart-unity/files/3461112/bug.txt)

**Comment by ivk1800** [comment]
Make sure that target architectures in inspector same  as in the file AndroidResolverDependencies.xml
`<setting name="androidAbis" value="arm64-v8a,armeabi-v7a,x86" />`

for example if you build with arm64-v8a, but in AndroidResolverDependencies.xml does not have arm64-v8a, you can catch error `DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.2.2` or crash.

you need make Resolve affter change target architectures

**Comment by Vah94** [comment]
08-05 14:33:19.868 18799-19586/? E/CRASH:   #00  pc 000000000000069c  [vdso] ()
        #01  pc 000000000001e020  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libFirebaseCppApp-6_2_2.so (_ZN8firebase11crashlytics8internal19CrashlyticsInternal12LogExceptionEPKcS4_NSt6__ndk16vectorINS0_5FrameENS5_9allocatorIS7_EEEE+32)
        #02  pc 000000000001e6a0  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libFirebaseCppApp-6_2_2.so (_ZN8firebase11crashlytics11Crashlytics12LogExceptionEPKcS3_NSt6__ndk16vectorINS0_5FrameENS4_9allocatorIS6_EEEE+52)
        #03  pc 000000000001ca38  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libFirebaseCppApp-6_2_2.so (Firebase_Crashlytics_CSharp_FirebaseCrashlyticsInternal_LogException+88)
        #04  pc 00000000009215b0  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #05  pc 000000000091eed4  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #06  pc 0000000000cd1508  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #07  pc 000000000091df78  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #08  pc 0000000000f2a2d8  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #09  pc 0000000000f29f50  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #10  pc 0000000000709eec  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #11  pc 000000000063951c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #12  pc 0000000000c3c5cc  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb+164)
        #13  pc 0000000000c4b924  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb+152)
        #14  pc 0000000000c287dc  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN20Application_Bindings25LogCallbackImplementationERK21DebugStringToFileData7LogTypeb+128)
        #15  pc 00000000013762d4  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN14CallbackArray3IRK21DebugStringToFileData7LogTypebE6InvokeES2_S3_b+120)
        #16  pc 0000000001375f3c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_Z40DebugStringToFilePostprocessedStacktraceRK21DebugStringToFileData+208)
        #17  pc 00000000013765f8  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_Z17DebugStringToFileRK21DebugStringToFileData+240)
        #18  pc 0000000000c4d78c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN9Scripting23LogExceptionFromManagedE21ScriptingExceptionPtriPKcb+424)
        #19  pc 0000000000cfd994  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_Z44DebugLogHandler_CUSTOM_Internal_LogExceptionP37ScriptingBackendNativeObjectPtrOpaqueS0_+184)
        #20  pc 00000000009a38c8  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #21  pc 0000000000d21754  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #22  pc 0000000000d20f10  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #23  pc 0000000000d20ca0  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #24  pc 00000000006fca7c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #25  pc 000000000063951c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libil2cpp.so ()
        #26  pc 0000000000c3c5cc  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb+164)
        #27  pc 0000000000c4b924  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb+152)
        #28  pc 0000000000c5204c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN13MonoBehaviour16CallUpdateMethodEi+292)
        #29  pc 00000000008920c4  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN20BaseBehaviourManager12CommonUpdateI16BehaviourManagerEEvv+204)
        #30  pc 0000000000891fe4  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZN16BehaviourManager6UpdateEv+32)
        #31  pc 0000000000a1f61c  /data/app/cam.companyname.gamename-7-GP9bGEQEAZKvPSbKPI7A==/lib/arm64/libunity.so (_ZZ23InitPlayerLoopCallbacksvEN41UpdateScriptRunBehaviourUpdateRegistrator7ForwardEv+48)
    
[bug.txt](https://github.com/firebase/quickstart-unity/files/3467174/bug.txt)

**Comment by Vah94** [comment]
@ivk1800 thanks. DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6.2.2 is fixed.
But I still get an error in CRASHLYTICS during a custom error.
The game hangs or closes. (Unity version 2018.4.df1 and 2019.2.0f1)

**Comment by patm1987** [comment]
Hi @Vah94 ,

Are you still seeing the issue in the latest Firebase Unity SDK (6.3.0)? If it's the same issue as #421 referenced above, it should hopefully be fixed.

Thanks,
--Patrick

**Comment by stewartmiles** [comment]
@Vah94 since we haven't heard from you we'll assume it was fixed in the latest upgrade.
