### ISSUE TITLE
Database does not seem to synchronize across different devices under the same profile

### ISSUE THREAD

**Issue by vkaramian** [firebase/quickstart-unity#439]
## Please fill in the following fields:
Unity editor version: 2019.2
Firebase Unity SDK version: 6.2.2 
Firebase plugins in use (Auth, Database, etc.): Authentication, Database, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Google Play
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows and Mac 
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android

## Please describe the issue here:
Database does not seem to synchronize across different devices under the same profile.

Thanks!
Vk

**Comment by cynthiajoan** [comment]
Hi @vkaramian, can you please provide more details here? What's your repro steps, what do you expect to see and what's the wrong behavior. Do you see the same error if using our [sample app](https://github.com/firebase/quickstart-unity/tree/master/database/testapp)?

**Comment by vkaramian** [comment]
I have solved the problem. The issue was due to saving data outside of the main thread. The proper way of doing it after the Unity 2019.2 Upgrade is to use the event handlers for data change values on Database path. @cynthiajoan thanks.
