### ISSUE TITLE
Authentication: "One or more Firebase dependencies are not present"

### ISSUE THREAD

**Issue by luizfcdnascimento** [firebase/quickstart-unity#44]
When I start the authentication app in Android, I receive the error below:

"One or more Firebase dependencies are not present.
Current dependency status: UnavailableOther"

Can someone help?
 
Thanks and regards.

**Comment by luizfcdnascimento** [comment]
Hi. Just for the record, after press Resolve Client Jars (Assets >> Play Services Resolver >> Android Resolver >> Resolve Client Jars), the app is crashing in Android. I'm using Firebase Unity SDK 1.1.1..

Thanks.

**Comment by stewartmiles** [comment]
Do you have a log of the crash?  Are any errors present in your Unity console log?

**Comment by luizfcdnascimento** [comment]
Hi. I have updated the google-services.json file and now it's working fine. Not sure why but, first time I downloaded the json file, it was missing a couple of data (like api_key).

Thanks for the support.
