### ISSUE TITLE
Build completed with a result of 'Failed'

### ISSUE THREAD

**Issue by Shahdee** [firebase/quickstart-unity#440]
## Please fill in the following fields:
Unity editor version: 2018.1.0.f2
Firebase Unity SDK version: 5.3.0
Firebase plugins in use (Auth, Database, etc.): Analytics, DynamicLinks, App, Invites, Messaging, Platform, RemoteConfig 
Additional SDKs you are using (Facebook, AdMob, etc.): Chartboost
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Unable to build Android build (build system internal), due to these errors in Console: 

CommandInvokationFailure: Unable to merge android manifests. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/margarita/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.google.firebase.firebase-abt-18.0.0/AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
++    <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.abt.component.AbtRegistrar"
Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.google.firebase.firebase-config-18.0.0/AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
++    <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.remoteconfig.RemoteConfigRegistrar"
Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.google.firebase.firebase-dynamic-links-18.0.0/AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
++    <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.dynamiclinks.internal.FirebaseDynamicLinkRegistrar"
Error: [Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.google.firebase.firebase-iid-19.0.1/AndroidManifest.xml:12] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
]
stdout[
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.android.support.support-core-ui-26.1.0/AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.android.support.support-core-utils-26.1.0/AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.android.support.support-fragment-26.1.0/AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.android.support.support-media-compat-26.1.0/AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.android.support.support-v4-26.1.0/AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-measurement-impl-17.0.1/AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
[Temp/StagingArea/AndroidManifest-main.xml, /Users/margarita/Documents/Repos/hm_master_branch/UnlimitedJourney/Temp/StagingArea/android-libraries/com.google.android.gms.play-services-measurement-sdk-api-17.0.1/AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommand (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No

**Comment by cynthiajoan** [comment]
Hi @Shahdee, first would like to understand why using 5.3.0 when our latest SDK is updated to 6.2.2, any specific reason?

For AndroidManifest conflict, the first thing I would recommend to try is using our android resolver https://github.com/googlesamples/unity-jar-resolver and see if force resolving can fix the issue for you.

**Comment by patm1987** [comment]
Hi @Shahdee,

I assume that you're still stuck. Have you tried running in the latest SDK (now 6.3.0)? Also, do you have any other `AndroidManifest.xml` that could be complicating the merger or is it just Firebase and Chartboost?

Thanks,
--Patrick

**Comment by stewartmiles** [comment]
You need to upgrade your Android SDK.

See https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826
