### ISSUE TITLE
java.lang.Error signal 6 (SIGABRT), code -6 FirebaseStorage  AppLogCallback LogLevel

### ISSUE THREAD

**Issue by oddgames-david** [firebase/quickstart-unity#446]
Unity editor version: 2018.4.0f1
Firebase Unity SDK version: 5.6.0
Firebase plugins: Analytics, Storage, RemoteConfig
SDK: Facebook, Admob, OneSignal, Bugsnag
Unity Editor: Windows
Platform: Android

We've received 61 occurrences from 41 users of the the following stacktrace.
7 affected android versions from 5.1.1 to 9.0
30 different handsets

I can see in our breadcrumbs that an error was raised and we went ahead and uploaded some debug data to firebase about 8 seconds before this crash but i also have other reports without any firebase activity. See the attached pdf for the last 21 seconds of breadcrumbs, if you want more I can give one of your dev's access to our project on bugsnag.

[java.lang.Error in Trucks Gone Wild.pdf](https://github.com/firebase/quickstart-unity/files/3504245/java.lang.Error.in.Trucks.Gone.Wild.pdf)
```
java.lang.Error signal 6 (SIGABRT), code -6 (?), fault addr --------
Build fingerprint: 'google/crosshatch/crosshatch:9/PQ3A.190801.002/5670241:user/release-keys'
Revision: 'MP1.0'
pid: 18230, tid: 20206, name: FirebaseStorage  >>> au.com.oddgames.trucksgonewild <<<
    x0   0000000000000000  x1   0000000000004eee  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000000000
    x8   0000000000000083  x9   00000078752790a0  x10  fffffff87ffffbdf  x11  0000000000000001
    x12  0000000000000001  x13  ffffffffffffffff  x14  0000000000000000  x15  ffffffffffffffff
    x16  00000078752b32c8  x17  00000078751f0dcc  x18  00000077d23b7000  x19  0000000000004736
    x20  0000000000004eee  x21  00000077d2085000  x22  00000077ea61e680  x23  00000077c09fcec0
    x24  000000007861a00c  x25  0000000000040000  x26  0000007795036020  x27  0000000000013405
    x28  0000000000000000  x29  00000077d5180420  x30  00000078751e594c
    sp   00000077d51803e0  pc   00000078751e5974  pstate 0000000060000000
 
    unknown [vdso].
    abort:112 libc.abort
    _ZN9__gnu_cxx27__verbose_terminate_handlerEv:396 libil2cpp._ZN9__gnu_cxx27__verbose_terminate_handlerEv
    _ZN10__cxxabiv111__terminateEPFvvE:8 libil2cpp._ZN10__cxxabiv111__terminateEPFvvE
    _ZSt9terminatev:12 libil2cpp._ZSt9terminatev
    __cxa_throw:136 libil2cpp.__cxa_throw
    unknown libil2cpp.
    unknown libil2cpp.
    unknown libil2cpp.
    unknown libil2cpp.
    unknown libil2cpp.
    _ZN8firebaseL14AppLogCallbackENS_8LogLevelEPKcPv:76 libFirebaseCppApp-6._ZN8firebaseL14AppLogCallbackENS_8LogLevelEPKcPv
    _ZN8firebaseL23LogMessageWithCallbackVENS_8LogLevelEPKcSt9__va_list:164 libFirebaseCppApp-6._ZN8firebaseL23LogMessageWithCallbackVENS_8LogLevelEPKcSt9__va_list
    _ZN8firebase8LogDebugEPKcz:36 libFirebaseCppApp-6._ZN8firebase8LogDebugEPKcz
    _ZN8firebase7storage8internal24StorageReferenceInternal24CppByteUploaderReadBytesEP7_JNIEnvP7_jclasslllP8_jobjectii:128 libFirebaseCppApp-6._ZN8firebase7storage8internal24StorageReferenceInternal24CppByteUploaderReadBytesEP7_JNIEnvP7_jclasslllP8_jobjectii
    unknown storage_resources_lib.
```
I've not been able to replicate on devices I have.

**Comment by DellaBitta** [comment]
Hi @oddgames-david,

Firebase SDK version 6.0.0 has a fix for a crash when the app is being shut down before a log stream has been completed, which seems similar to this log here.  Could it  be that the app is being shut down in these cases?  

I know you mentioned that you have some crashes without Firebase activity, too.  Any more information about these scenarios would be helpful.

**Comment by stewartmiles** [comment]
@oddgames-david since we haven't heard from you we'll assume that upgrading to the latest SDK fixed this for you.
