### ISSUE TITLE
Cannot disable Crashlytics Debug log calls on 6.1.1

### ISSUE THREAD

**Issue by CriticalForce** [firebase/quickstart-unity#448]
## General Info:
Unity editor version: 2018.4.1f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use Analytics, Crashlytics, Messaging, DynamicLinks, RemoteConfig, InstanceID
Additional SDKs you are using: Facebook, Google Play Games, HelpShift
Platform you are using the Unity editor on: Mac + Windows
Platform you are targeting: Android/iOS

## The issue:
When Migrating from Fabric to FireBase Crashlytics, using Crashlytics.Log "to give yourself more context for the events leading up to a crash" causes them to be logged also via UnityEngine.Debug.Log causing overhead on the device.
I did even tried setting:
Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Error;

I also noticed there are 'CrashlyticsSettings' but I was unable to find any documentation if I could adjust the debug level that way.

## Reproduction
Migrating from Fabric to FireBase Crashlytics using the migration instructions caused these issues to pop up. With Fabric these logs were not popping up in the unity debug logs.

**Comment by DellaBitta** [comment]
Hi @CrtiicalForce,

Unfortunately I couldn't reproduce this (version 6.2.2 on Windows).  I'm fairly certain that the Console.Log function doesn't tie into the Debug.Log for any log level, but if you can reproduce this using the Crashlytics testapp, or provide a stand alone example, then please let me know. Thanks!

**Comment by stewartmiles** [comment]
Hi @CriticalForce are you able to reproduce this issue with our sample project?

On Android the Unity SDK just calls `CLSLog`on iOS and [CrashlyticsCore .log](https://firebase.google.com/docs/reference/android/com/crashlytics/sdk/android/crashlytics-core/CrashlyticsCore.html#log(java.lang.String)) on Android neither of which are supposed to log to the console.

**Comment by CriticalForce** [comment]
After closer inspection I can confirm that I must have misread my issue.

What I'm actually seeing is a Debug print in **adb Logcat** for each Crashlytics Log which logs under Unity with the command: "adb logcat -s Unity"

Example of the print:
![image](https://user-images.githubusercontent.com/11941373/65575446-827fe480-df78-11e9-96e1-5558ad8aae7f.png)

**Comment by stewartmiles** [comment]
@CriticalForce could you share the logs that you're seeing in particular?  If you see a debug log from Unity that could be from Unity not Firebase.

**Comment by MagicMiikka** [comment]
The logs I'm seeing are the messages I'm sending to Crashlytics via Crashlytics.Log but for some reason it is being logged onto the ADB debug track as well.

Might be something else interfering with it as well but it started happening after migration to FireBase.Crashlytics from Fabric.Crashlytics Log call

**Comment by MagicMiikka** [comment]
![image](https://user-images.githubusercontent.com/49847631/66292182-56575280-e8ec-11e9-822c-610e62b010e4.png)

I'm not sure if there is a third party in our SDK logging these out 🤔

**Comment by MagicMiikka** [comment]
I now reproed the issue with the Crashlytics test project.

Unity 2018.4.1f1
FireBase 6.2.1 & 6.3.0

With just one script on a gameobject doing
> Firebase.Crashlytics.Crashlytics.Log("DEBUG!");


![image](https://user-images.githubusercontent.com/49847631/66428231-5bb4ba00-ea1e-11e9-8359-87e508c2b097.png)

**Comment by cynthiajoan** [comment]
Hi @MagicMiikka, thanks for providing follow up logs. Our crashlytics team is looking into the issue.

**Comment by MagicMiikka** [comment]
@cynthiajoan any updates on this?

This is a blocking bug for our Fabric migration as it would introduce potential performance regression.

**Comment by patm1987** [comment]
Sorry, there's no update to give right now.

If you do have profiling data comparing Firebase and Fabric Crashlytics that you'd like to share with the team feel free to post it here and I'll forward it along. You can also open a support ticket at https://firebase.google.com/support.

**Comment by MagicMiikka** [comment]
Thanks for the update @patm1987 

We've not profiled this unfortunately but I'll can consult our tech lead on this and if we should just reduce the overall amount of logs we use via crashlytics in the meantime.

**Comment by mrichards** [comment]
The latest Firebase Unity release (6.15) uses the new [Firebase Crashlytics SDKs](https://firebase.googleblog.com/2020/06/crashlytics-sdk-now-available.html), which no longer echo log calls to LogCat.
