### ISSUE TITLE
Error with Google-Services.json bundle id

### ISSUE THREAD

**Issue by femoreti** [firebase/quickstart-unity#450]
## Please fill in the following fields:
Unity editor version: 2019.1.12f1
Firebase Unity SDK version: 6.3.0
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob and PlayGamesServices
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
When I import my google-services.json I get this message (Project Bundle ID com.fmgames.ski.penguin does not match any bundle IDs in your google-services.json files
This will result in an app that will fail to initialize.), my bundle ID is exactly the bundle in services.json file 
"android_client_info": {
          "package_name": "com.fmgames.ski.penguin"
        }

I don't know what else I can do.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes

**Comment by patm1987** [comment]
Hi @femoreti,

If you don't mind, I just want to run through a few basic troubleshooting steps to get started.

There are a lot of ways to set your bundle ID, I've personally worked on a number of games where it was actually procedurally set as part of the build process.

Can you verify that in your project settings, you're viewing Android:
![image](https://user-images.githubusercontent.com/1111611/63365744-71b6d000-c335-11e9-8f49-aeebec9914cd.png)

and that your PackageName matches here:
![image](https://user-images.githubusercontent.com/1111611/63365779-84c9a000-c335-11e9-9eb9-6200d20a216d.png)

Exactly to `"com.fmgames.ski.penguin"` as mentioned above. Ie: there's no `.enterprise` or other modifier that you might have on your machine or that the bundle isn't set after the build completes.

Can you also verify that you have one google-services.json.

Finally, if your dialog box looks anything like mine, there should be an `Apply` button that fixes it for you:
![image](https://user-images.githubusercontent.com/1111611/63366299-a2e3d000-c336-11e9-995a-96abd6b39c19.png)

 Does clicking this button make the issue go away? And does it do anything else unexpected to your project?

I'm sorry that you're running into an issue, and for your patience so far,
--Patrick

**Comment by femoreti** [comment]
Hi Patrick, thanks for answering.

My package name in Project Settings is exactly the same as the bundle listed in the google-services.json file (which I also have in the project Assets folder).

After investigating for a while I ended up getting a workaround for this problem, the solution was as follows:

Replace the file `"generate_xml_from_google_services_json.exe"` in the `./Assets/Firebase/Editor` folder with an older one from another project I own. So apparently the problem is in this executable.

Thank you, Felipe.

**Comment by patm1987** [comment]
Thanks for that info,

If you don't mind, I'd like to see if this is an error with the 6.3.0 SDK in general or if just a really odd one-off event. If you pull in a Firebase 6.3.0 unitypackage again, does the issue manifest itself again?

--Patrick

**Comment by femoreti** [comment]
Okay, so I made a few more tests.

I created an empty project and add my bundle ID to it.
![image](https://user-images.githubusercontent.com/17441598/63455104-7311f680-c422-11e9-9d19-585becede2f4.png)

Then I import FirebaseAnalytics. After set up as an android platform I add google-services.json. 
![image](https://user-images.githubusercontent.com/17441598/63455200-afdded80-c422-11e9-947e-b6e98e62e0cd.png)

And finally I opened the Firebase window menu in `Window/Firebase/Documentation`, the error appears. 
`
"Project Bundle ID com.Company.ProductName does not match any bundle IDs in your google-services.json files
This will result in an app that will fail to initialize."
`

![image](https://user-images.githubusercontent.com/17441598/63455255-d0a64300-c422-11e9-91c5-6babcc4fe1c2.png)

And here I replace the `generate_xml_from_google_services_json.exe` file under `.Assets/Firebase/Editor` by one that I have from another project with firebase version 5.3.1 (image)

![image](https://user-images.githubusercontent.com/17441598/63455581-6e017700-c423-11e9-977a-033b20732dd5.png)

The error continues after that, but once you change the `Api Compatibility` Level (doesn't matter wich one you're using, just change to another then change back to the original state) the error disappear and the analytics start to work after build.

It's weird and I don't know why this works, but works.

Thanks for your help Patrick.

--Felipe

**Comment by patm1987** [comment]
Thank you for letting us know! Feel free to reach out if you have any more information to share (and I may ping this thread again as necessary).

**Comment by stewartmiles** [comment]
@femoreti we tried reproducing the problem with generate_xml_from_google_services_json.exe and wasn't able to with 6.5.0 .  Could you try pulling the latest plugin and seeing whether you're still experiencing the issue?

**Comment by femoreti** [comment]
Hey @stewartmiles, sorry for the delay, here is the UnityEditor log file.
[Editor.log](https://github.com/firebase/quickstart-unity/files/3616451/Editor.log)

**Comment by stewartmiles** [comment]
@femoreti in the log it says...

```
Project Bundle ID com.fmgames.ski.penguin does not match any bundle IDs in your google-services.json files
This will result in an app that will fail to initialize.

Available Bundle IDs:


You need to either:
* Fix your app's bundle ID under "Player Settings --> Bundle Identifier"
or:
* Add another app to your firebase project
  Goto https://firebase.google.com/docs/unity/setup#add_firebase_to_your_app_1
  and add the new configuration file to your project.
```

This is what you need to do.

**Comment by stewartmiles** [comment]
Actually, looking at this error message, I'm confused as to why it says that no bundle IDs are available.  @femoreti could you open up a support request via https://firebase.google.com/support and share your google-services.json and GoogleServices-Info.plist files that you're using or even better a minimal project with these configuration files that reproduces this?

It looks like a configuration file is present but it's not possible to parse the available bundle IDs from it.

**Comment by femoreti** [comment]
@stewartmiles Yeah, the log says that the bundle does not match, but it is the same bundle..

I'll open a support there and send the sample project I created for this bug.

Thanks!

**Comment by desiki** [comment]
Was the issue of this found? I am suffering the same. It was everything working and suddenly it does not recognise it. Exactly same as everything here.
I am using Firebase 6.6.0

**Comment by alexames** [comment]
Hi @desiki, 

Can you make sure you tried following the steps that @patm1987 posted in his comment [here](https://github.com/firebase/quickstart-unity/issues/450#issuecomment-523096158), just to verify that whether you're seeing the same issue?

**Comment by chkuang-g** [comment]
@desiki Please open an new issue and include details required from the template.

Thank you

**Comment by shareyourlocationsite** [comment]
...and what is the solution? Why did you close this issue?
