### ISSUE TITLE
Firebase's libApp.so was not found for this device's architecture

### ISSUE THREAD

**Issue by wg-mblazin** [firebase/quickstart-unity#454]
## Please fill in the following fields:
Unity editor version: 2018.3.8f1
Firebase Unity SDK version: 4.2.1
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AppsFlyer, Fabric Crashlytics 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac, Windows
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS

## Please describe the issue here:
- Create a new Unity project and add the Firebase Analytics Unity SDK version 4.2.1
- Set the Scripting Backend to IL2CPP and set the target architecture for Android to arm64
- Start the app on a mobile device and see the following error in adb logcat:

08-27 11:06:51.448 24126 24157 E Unity   : InitializationException: Firebase's libApp.so was not found for this device's architecture
08-27 11:06:51.448 24126 24157 E Unity   : in your APK.

It looks like the libapp.so file is not available for arm64 for Unity version 4.2.1, is there a backport available for this version of the Unity?

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No

**Comment by stewartmiles** [comment]
@alexames we added arm64 builds when Unity added support in 5.2.0. https://firebase.google.com/support/release-notes/unity#version_520_-_july_23_2018 we patched the Play Services Resolver in later release to deal with Unity's ABI / platform selection APIs changing.

@wg-mblazin the short story is that I agree with @alexames you should really try to upgrade, we've changed a lot over almost 2 years while _trying_ to make minimal breaking API changes.
