### ISSUE TITLE
Issue with Storage

### ISSUE THREAD

**Issue by deezusdyse** [firebase/quickstart-unity#456]
## Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: Unity 2018.3.14f1
Firebase plugins in use (Auth, Database, etc.): Storage
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Unity

## Please describe the issue here:
The type or namespace name "Storage" does not exist in the namespace 'Firebase' (are you missing an assembly reference?) and many other similar issues. 

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes.

**Comment by alexames** [comment]
Can you describe the steps you followed to cause this to occur? It sounds like you didn't properly import the library based on the error you're getting.

**Comment by stewartmiles** [comment]
As @alexames it sounds like you didn't import the FirebaseStorage.unitypackage, I recommend you follow the instructions in the readme.
