### ISSUE TITLE
Auth does not work in 2018.4.8f1

### ISSUE THREAD

**Issue by kevinfoley** [firebase/quickstart-unity#457]
## Please fill in the following fields:
**Unity editor version:** 2018.4.6f1 / 2018.4.8f1 (tested both separately)
**Firebase Unity SDK version:** 6.2.2 / 6.4.0 (tested both separately)
**Firebase plugins in use:** Analytics, Auth, Database, Functions
**Additional SDKs you are using:** Facebook
**Platform you are using the Unity editor on:** Windows
**Platform you are targeting:** Android

## Please describe the issue here:
Up through Sunday, I was able to run/use our app in the Editor without issues. Today, it has randomly stopped working.

I enter my username and password, and click the login button, which calls `SignInWithEmailAndPasswordAsync();` Firebase immediately throws a useless "Internal error" exception. No other information is provided, even with verbose logging enabled.

Steps I have tried to remedy the issue, without success:

- Clear PlayerPrefs
- Clear cache for this app (from `C:\Users\{user_name}\AppData\LocalLow\{company_name}\{project_name}`)
- Upgrade from Firebase 6.2.2 to Firebase 6.4.0
- Downgrade from Unity 2018.4.8f1 to 2018.4.6f1
- Reimport all files
- Restart Editor
- Restart computer

Again, I must stress that **I could log in on Sunday but can't log in today (two days later).** We're using Git and I can see that _no files have changed_ (other than when I tested upgrading to Firebase 6.4.0).

Login _does_ work when I log in on mobile devices with the app installed (Android and iOS). This problem seems specific to the Editor or maybe even to my PC.

**Comment by kevinfoley** [comment]
Although it's still not working for me in 2018.4.6f1, another team member reported that the login broke when he upgraded from 2018.4.6f1 to 2018.4.8f1. I had upgraded recently as well, so this does seem likely to be the culprit.

**Comment by stewartmiles** [comment]
@kevinfoley we have no dependencies upon Unity version in the Auth SDK AFAIK.  Are you able to reproduce the failure with the auth sample project in this repo?

**Comment by kevinfoley** [comment]
It looked like a bug to me; possibly some unforeseen compatibility issue with 2018.4.8f1. Possibly Firebase cached an invalid auth token somewhere I couldn't find. Regardless, the project just changed hands, so I'm no longer involved and can't finish tracking down this bug.
