### ISSUE TITLE
How can I save data of a user logged in with firebase auth play games in google firebase database?

### ISSUE THREAD

**Issue by Jhan321** [firebase/quickstart-unity#458]
## Please fill in the following fields:
Unity editor version: 2017.3.1f1
Firebase Unity SDK version: 5.4.0
Firebase plugins in use (Auth, Database, etc.): Auth, database
Additional SDKs you are using (Facebook, AdMob, etc.): GoogleMobileAds, GooglePlayGames, Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

So I am developing a game in unity3d similar to those asked, I use firebase to save all the data of the users that register with email and password, everything is going well, but I want new users to register and log in with play games or google, the question is: how can I save the tados of users logged in with google play games in firebase database, so where I understand firebase play games only works for a login,

In my current project I have a function of beginning of section and another of registration, the application only saves data in google firebase when it is registered, what happens in the case of google play games?

**Comment by stewartmiles** [comment]
@patm1987 FYI

Unfortunately, we don't have Unity specific docs for these but [this document](https://firebase.google.com/docs/auth/android/play-games) describes how to associate a FirebaseUser with Play Games.  Once the account is associated with the FirebaseUser you can use the Firebase user ID to save user specific data.
