### ISSUE TITLE
Dynamic Links Crashes The App On Internal Testing

### ISSUE THREAD

**Issue by xtrecoolx** [firebase/quickstart-unity#463]
## Please fill in the following fields:
Unity editor version: Unity 2019.2.3.f1
Firebase Unity SDK version: 6.4.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Messaging, RemoteConfig, DynamicLinks
Additional SDKs you are using (Facebook, AdMob, etc.): Admob, Facebook, Applovin
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
I am facing a really weird problem. I have implemented Dynamic Links to my game then pushed the aab file to my device(bundletool install). When I started the game, everything worked just fine. Then I published the same aab file to Play Store for internal testing. The app died instantly without any reasonable explanation given on the debug console on the same device. I wish I can give you guys a stack trace, but there is seriously nothing except "app died, no saved state".

Obviously, I can't publish this to production since this happened at internal testing. Can you please help me ?

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No since everything works when running on device.

**Comment by xtrecoolx** [comment]
@stewartmiles I had to reopen this issue because i am not really certain if dynamic link can cause the following or not. Maybe you can make a guess...

After I wrote my initial post, I have decided to update my app without changing any lines of code at the Google Play Store and published to internal testing. The app did open without any problems. Then I removed the app from the device, reinstalled once again from the play store and the app crashed. Then I updated the app once again at Google Play Store and reinstalled it and the app worked just fine once again. I can even receive dynamic links.

As you can see its really weird and hard for me to tell if this is directly related to dynamic links. The only exception I am getting is "app died, no saved state" after Firebase Messaging is initialized.

I am thinking of going into production but I am afraid this non-sense crash may happen for some users.

**Comment by stewartmiles** [comment]
@xtrecoolx to debug this we really need a stack trace / the logs from your game when it's starting up to see whether that could help point at the cause.  Ideally, if you can reproduce the issue with our sample application in this repo we should be able to figure out what's going on more quickly.  The thing is, if you have a load of components in your game it's hard to tell what is causing the problem without using cause elimination debugging.

**Comment by xtrecoolx** [comment]
@stewartmiles can you instruct me on how to get the stack trace you need ?

is the below command sufficient ?
adb logcat -s Unity ActivityManager PackageManager dalvikvm DEBUG

**Comment by stewartmiles** [comment]
@xtrecoolx ideally the entire unfiltered output of adb logcat would be great since we have information that will show up in multiple streams e.g

On Mac / Linux
```
adb logcat | tee logcat.log
```

On Windows
```
adb logcat > logcat.log
```

**Comment by xtrecoolx** [comment]
@stewartmiles Again the same thing happened when I uninstalled the app and reinstalled it. I have attached the log file.
Thank you.
[logcat.zip](https://github.com/firebase/quickstart-unity/files/3592605/logcat.zip)

**Comment by stewartmiles** [comment]
@xtrecoolx looking at this stack trace, I'm not sure how you came to the conclusion that this has anything to do with dynamic links, `libFirebaseCppApp-${version}.so` (the C++ component of Firebase used by dynamic links) isn't in the stack trace.  It looks like _something_ is deallocating an invalid address.  If you're not already, you could try building with debug symbols and without split APK (https://docs.unity3d.com/Manual/android-OBBsupport.html) to see whether you can get more information on the crash.  Also, I recommend removing plugins - if possible - (i.e use cause elimination debugging) to narrow down which component(s) or perhaps parts of your game could be causing this.

**Comment by xtrecoolx** [comment]
@stewartmiles Thank you for your time. I thought this happened after I installed DynamicLinks package. However, it turned out to be a problem with PlayerPrefs. It's a Unity bug.
