### ISSUE TITLE
DllNotFoundException: FirebaseCppApp-6.2.1

### ISSUE THREAD

**Issue by turkm3000** [firebase/quickstart-unity#465]
Unity editor version: 2019.2.4f1
Firebase Unity SDK version: 6.2.1
Firebase plugins in use : Auth, Database, Functions
Additional SDKs you are using : Facebook
Platform you are using the Unity editor on : Windows
Platform you are targeting : Android

Unity Player sittings: Other sittings:
Scripting Backend: IL2CPP
API compatibility level:  .NET 4.x
Target Architecture:
   ARMv 7: true
   ARMv64: true
   x86: false

all other sittings default.

I used Firebase Unity quickstarts samples for : Auth, Database, and Functions still the same issue
but when i resolve it or force resolve it, it succeeded 

THE LOG:
DllNotFoundException: FirebaseCppApp-6.2.1
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.LXG0TU0ZlU/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:118)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.LXG0TU0ZlU/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:138)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.LXG0TU0ZlU/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.LXG0TU0ZlU/firebase/app/client/unity/proxy/LogUtil.cs:74)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.LXG0TU0ZlU/firebase/app/client/unity/proxy/LogUtil.cs:30)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.LXG0TU0ZlU/firebase/app/client/unity/proxy/FirebaseApp.cs:56)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Sample.Auth.UIHandler.Start () (at Assets/Firebase/Sample/Auth/UIHandler.cs:74)

**Comment by turkm3000** [comment]
I switched to unity 2019.2.4 and firebase SDK 6.4.0 and all works fine now

**Comment by tonyjoseph456** [comment]
> 
> 
> I switched to unity 2019.2.4 and firebase SDK 6.4.0 and all works fine now

Still it didnt worked for me. I'm having the same issue.
