### ISSUE TITLE
ProviderDataList always returns 0 providers

### ISSUE THREAD

**Issue by ColorTwist** [firebase/quickstart-unity#467]
I am trying to get the ProviderDataList, but it seems it always return 0 length List for a signed-in user (email or facebook, both return provider list 0). Note that i am testing this on Unity Editor and when auth auto authenticates the user at play. Target platform is Android.
I remember once it was working, currently, i am using version 6.4 of Firebase.
I place this code inside:  ` AuthStateChanged(object sender, System.EventArgs eventArgs)`

 inside: 
` if (signedIn) {
`
Function to get providers is shown as in the Auth example here:
```

 private void GetUserProvider(FirebaseUser user, int indentLevel)
    {
        string indent = new String(' ', indentLevel * 2);
        var providerDataList = new List<Firebase.Auth.IUserInfo>(user.ProviderData);
        var numberOfProviders = providerDataList.Count;
        if (numberOfProviders > 0)
        {
            for (int i = 0; i < numberOfProviders; ++i)
            {
                Debug.Log(String.Format("{0}Provider Data: {1}", indent, i));
            }
        }
    }
```
```

**Comment by markchandler-google** [comment]
Hi @ColorTwist,

Initial investigation this looks like a bug in Firebase with restoring user information. Ill file an internal bug and try and get a fix into the next release.

**Comment by ColorTwist** [comment]
Great to know you can replicate it!
Note that if you signup or do full login (aka enter user/password or FB token) it seems to work, but not totally sure tho since sometimes it does and sometimes it doesn't.
 I can't work with such non persistence  behavior.

**Comment by ColorTwist** [comment]
Could that also cause for the DisplayName of the auth user to be received blank?

**Comment by a-maurice** [comment]
Hi @ColorTwist 

This issue should be resolved in the latest release of the Unity SDK, 6.6.0, which you can download via https://firebase.google.com/download/unity

Thanks for letting us know about this issue!
