### ISSUE TITLE
Unable to build the app with firebase 6.5.0 | Play Services Resolver 1.2.124

### ISSUE THREAD

**Issue by Divyanshu-del** [firebase/quickstart-unity#469]
## Please fill in the following fields:
Unity editor version: 5.3.4f1
Firebase Unity SDK version: 6.5.0
Firebase plugins in use (Auth, Database, etc.): Auth and Database
Additional SDKs you are using (Facebook, AdMob, etc.): None 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Everything runs fine in the editor but it fails to build the app because of the failure of merging manifest.xml files. I am using jdk: jdk1.8.0_221 and sdk tools: 25.2.5 with .net 3.5. 

**These errors are logged in console after build failure and unable to merge manifest.xml error:**
1. Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-auth-19.0.0\AndroidManifest.xml:8] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

______________________________________________________________________________________________________

2. Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-common-19.1.0\AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

----------------------------------------------------------------------------------------------------------

3. Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-database-19.0.0\AndroidManifest.xml:11] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

----------------------------------------------------------------------------------------------------------

4. Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-19.0.0\AndroidManifest.xml:12] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun(

----------------------------------------------------------------------------------------------------------

5. CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_221\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:\Users\dell-pc\AppData\Local\Android\sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-auth-19.0.0\AndroidManifest.xml:8] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-common-19.1.0\AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:directBootAware="true"
++    @android:exported="false"
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-database-19.0.0\AndroidManifest.xml:11] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.database.DatabaseRegistrar"
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-19.0.0\AndroidManifest.xml:12] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-measurement-impl-17.2.0\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

----------------------------------------------------------------------------------------------------------

6. CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_221\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:\Users\dell-pc\AppData\Local\Android\sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-auth-19.0.0\AndroidManifest.xml:8] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-common-19.1.0\AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:directBootAware="true"
++    @android:exported="false"
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-database-19.0.0\AndroidManifest.xml:11] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.database.DatabaseRegistrar"
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-19.0.0\AndroidManifest.xml:12] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\Public\Documents\LO SHU GRID - MANGLAM\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-measurement-impl-17.2.0\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
]
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

----------------------------------------------------------------------------------------------------------

Update: I have also tried solutions mentioned in the previous threads:
- Tried sdk 26: Presents another set of errors
- Updating unity from scratch and vs with framework now, I'll update if I get the results meanwhile anyone here can answer and help, will be very much appreciated.

**Comment by Divyanshu-del** [comment]
Update: I have also tried solutions mentioned in the previous threads:

Tried sdk 26: Presents another set of errors
Updating unity from scratch and vs with framework now, I'll update if I get the results meanwhile anyone here can answer and help, will be very much appreciated.

**Comment by Divyanshu-del** [comment]
I am using resolver 1.2.124, can anyone please help me in the matter? I am stuck from last 5 days with this firebase now. Its delaying my production.

**Comment by yakirbu** [comment]
Hi,

Please try using a custom gradle, use resolver to patch gradle and change firebase-auth version to 18 instead of 19.
Let me know if it helps.

**Comment by Divyanshu-del** [comment]
Is custom gradle option available in unit 5.3?

**Comment by Divyanshu-del** [comment]
I have successfully solved this issue by updating my unity and Visual studio and now Apk is build but it has other issues now but for this problem I am closing the issue and opening a new one. I am thankful for the help everyone gave me.
