### ISSUE TITLE
Can't create storage bucket programmatically? Help wanted

### ISSUE THREAD

**Issue by DoubleALabs** [firebase/quickstart-unity#470]
## Please fill in the following fields:
Unity editor version: 2018.4.4
Firebase Unity SDK version: Most Recent
Firebase plugins in use (Auth, Database, etc.): Storage
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows and Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android

## Please describe the issue here:
Hello! So I have been using the Firebase SDK for about a month and still can't figure out how to create a bucket from a unity script if this is even possible? Is the only way to programmatically create a storage bucket is through the gsutil tool through the command line or can I do it in Unity?

**Comment by markchandler-google** [comment]
Hi @DoubleALabs, what is the use case you are trying to solve from Unity script? Firebase SDK is meant as a client side library for end users and thus doesnt have API's to script and configure the back end.

**Comment by DoubleALabs** [comment]
Thanks for the response! I figured that was functionality was off-limits for front end libraries. My case is special because I'm creating an editor tool in Unity to help build and deploy asset bundles through firebase. I have everything setup to drag and drop a prefab in a public field and press upload content in a bucket. I'll go through the Node.js route and setup a secure restful call to a node function to create a bucket for the assetbundles.
