### ISSUE TITLE
Unity editor crashes on RunTransaction successful completion.

### ISSUE THREAD

**Issue by utkarshparasarampuria** [firebase/quickstart-unity#472]
Unity editor version: 2019.1.4f1
Firebase Unity SDK version: 6.3.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Storage, Cloud Functions
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android + iOS

Issue:
Unity editor crashes when RunTransaction tries to update a double value. The build for Android works without any crash. Changing the double to a string fixes the crash on the Editor. No logs in the Editor.log file about the crash. Same crash occurring also when I'm trying to update a Database path with ServerValue.Timestamp.

Steps to reproduce in quickstart project:
1. Comment out line 73 in UIHandler.cs- StartListener() : not a necessary step, but just to ensure that the crash is only due to RunTransaction.
2. Add "mutableData.Value = ServerValue.Timestamp;" below line 163 to make the transaction write the Timestamp value.
3. Run on the unity editor, add an email id and click "Add score". The transaction write will be successful but the Editor will just close.

**Comment by markchandler-google** [comment]
Hi @utkarshparasarampuria,

This is fixed in Firebase SDK 6.4 (see release notes: https://firebase.google.com/support/release-notes/unity). Please update to latest Firebase SDK and try again.
