### ISSUE TITLE
Unable to Find Firebase Cpp app 6.5.0

### ISSUE THREAD

**Issue by Divyanshu-del** [firebase/quickstart-unity#473]
## Please fill in the following fields:
Unity editor version: 2018.4.9f1
Firebase Unity SDK version: 6.5.0
Firebase plugins in use (Auth, Database, etc.):Auth and Database
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
.Net Framework: 4.5

## Please describe the issue here:
I am working with an app in unity that saves the name and number of the user it works perfectly in editor but not in android. All the other things in the app work fine except firebase. It doesn't even log in to firebase using android.
I am using latest android studio and sdk and I have not created any keystore yet. The Read and write rules for database in firebase are both set to true.

**I found this error in logcat right after running the app in mobile, when it was supposed to log in to the databse:**

09-16 04:51:42.833: E/Unity(22140): Unable to find FirebaseCppApp-6_5_0

09-16 04:51:43.126: E/Unity(22140): DllNotFoundException: FirebaseCppApp-6_5_0

09-16 04:51:43.126: E/Unity(22140):   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)

09-16 04:51:43.126: E/Unity(22140):   at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <69e925fd6c2a4e388a551291825100de>:0 

09-16 04:51:43.126: E/Unity(22140): Rethrow as TypeInitializationException: The type initializer for 'SWIGE

09-16 04:51:43.136: E/Unity(22140): DllNotFoundException: FirebaseCppApp-6_5_0

09-16 04:51:43.136: E/Unity(22140):   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)

09-16 04:51:43.136: E/Unity(22140):   at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <69e925fd6c2a4e388a551291825100de>:0 

09-16 04:51:43.136: E/Unity(22140): Rethrow as TypeInitializationException: The type initializer for 'SWIGE
 
**This is the logcat error record when Data is sent for submission in database:**
09-16 04:55:48.397: E/Unity(22140): NullReferenceException: Object reference not set to an instance of an object

09-16 04:55:48.397: E/Unity(22140):   at DataBridge.SaveData () [0x00086] in <bb9677e4389447aba61a8304d9907b92>:0 

09-16 04:55:48.397: E/Unity(22140):   at UnityEngine.Events.InvokableCall.Invoke () [0x00011] in <81acad278e0345a68d9c76a3f5a99fc0>:0 

09-16 04:55:48.397: E/Unity(22140):   at UnityEngine.Events.UnityEvent.Invoke () [0x00023] in <81acad278e0345a68d9c76a3f5a99fc0>:0 

09-16 04:55:48.397: E/Unity(22140):   at UnityEngine.UI.Button.Press () [0x00027] in <201e781509bb45d1b9d03d931181326d>:0 

09-16 04:55:48.397: E/Unity(22140):   at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00011] in <201e781509bb45d1b9d03d931181326d>:0 

09-16 04:55:48.397: E/Unity(22140):   at UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) [0x00008] in <201e781509bb45d1b9d03d931181326d>:0 

09-16 04:55:48.397: E/Unity(22140):   at UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) [0x00070] in <201e781509

                                              **The Code I am using for OnStart authentication is this:** 
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Firebase.Auth;
using UnityEngine.UI;

public class AuthControl : MonoBehaviour {

    public Text Error;

     void Start()
    {

        LoginAnonymous();
    
    }
     void Update()
    {
        if (Input.GetKey (KeyCode.Escape))

        {
            Logout();
            Application.Quit();
        
        }
    }

    
    public void LoginAnonymous()
    {
        FirebaseAuth.DefaultInstance.SignInAnonymouslyAsync().ContinueWith((task =>
        {

            if (task.IsCanceled)
            {
                return;
            }

            if (task.IsFaulted)
            {
                Firebase.FirebaseException e =
                    task.Exception.Flatten().InnerExceptions[0] as Firebase.FirebaseException;
                GetErrorMessage((AuthError)e.ErrorCode);
                return;
            }

            if (task.IsCompleted)
            {
                print("Anonymous Logged In");
                Error.text = "Logged In";
            }
        }));
    }
    public void Logout()
    {
        if (FirebaseAuth.DefaultInstance.CurrentUser != null)
        {
            FirebaseAuth.DefaultInstance.SignOut();
        }

        Debug.Log("Logged Out"); 
    }
void GetErrorMessage(AuthError errorcode)
    {
        string msg = "";
        msg = errorcode.ToString();
        print(msg);
        Error.text = msg;  
    }
}
                                     **The code for Saving Data to database is this:**

using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
using Firebase;
using Firebase.Database;
using Firebase.Unity.Editor;

public class DataBridge : MonoBehaviour {

    public Text usernameInput, numberInput;

    private SaveNumber data;

    private string DATA_URL = "https://manglam-lo-shu.firebaseio.com/";

    private DatabaseReference databaseReference;

    void Start()
    {

        FirebaseApp.DefaultInstance.SetEditorDatabaseUrl(DATA_URL);

        databaseReference = FirebaseDatabase.DefaultInstance.RootReference ;
    
    }

    public void SaveData()
    {
        if (usernameInput.text.Equals("") && numberInput.text.Equals(""))
        {
            print("No Data");
            return;
        
        }
        data = new SaveNumber(usernameInput.text, numberInput.text);
        string jsonData = JsonUtility.ToJson(data);
        databaseReference.Child("Users" + Random.Range(0, 100000)).
            SetRawJsonValueAsync(jsonData);
    }

I submitted the issue earlier for manifest.xml building problems which are fixed now and I have closed the issue, Please help me solve this one. Can Anyone Help??

Thanks in Advance.

**Comment by Divyanshu-del** [comment]
@stewartmiles I followed through your previous similar issues, I force resolved and it succeeded, can you help me out in fixing it? I know you can, please help me.

Thanks in advance

**Comment by Divyanshu-del** [comment]
For everyone who is non-responsive, I fixed it. For someone who needs help, Do this:

1. Use jdk 1.8
2. Use latest sdk tools
3. Update to a recent stable release of unity
4. Use latest firebase sdk(Delete all the old folders of firebase package from the editor first) 
5. Use .net 4, if possible in visual studio 2010 or better
6. Even if auto resolution succeeded, forse resolve from assers>play services resolver>Android >Force Resolve
7. Use the highest sdk target in player setting and set lowest to 4.1 jellybean.

Bam... That's all, go ahead build in and run it in your android device.

Anyone with any other issues can ask in comments but for now I am closing this issue as it is solved.

Thanks everyone(Even though no one responded)..

Just kidding

**Comment by stewartmiles** [comment]
@Divyanshu-del FYI this is a best effort support channel.  If you want immediate support I recommend a paid support plan via a Google Cloud account.  Glad you figured this out.

**Comment by Divyanshu-del** [comment]
I appreciate your concern and offer but free services are all i need at the moment but I could'nt have figured out withoutblooking at your responses from previous similar issues. The app stoll works perfect

Thanks
