### ISSUE TITLE
How to ensure the ordered processing of children in ChildAdded callback in Unity?

### ISSUE THREAD

**Issue by utkarshparasarampuria** [firebase/quickstart-unity#479]
Unity editor version: 2019.1.4f1
Firebase Unity SDK version: 6.5.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Cloud Functions, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS

This is not as much an issue as it is a support query. I've tried all other ways including SO for my query but not able to get a definitive answer. I need to process children added to a particular Database branch in a particular order which I define using an "index" in the children. There is a possibility that multiple children are added in the branch at the same moment, but it is ensured their indexes are correctly ordered.
My query is: Is it possible that the children are processing in parallel in the Unity callback function, even if they might be triggered in order? What I think is happening is that the callback is triggered in order for each of the children, but all these children are possibly processed in parallel. I just need a yes/no answer if this is possible or not?

Here's the SO link for the question I had asked:
[https://stackoverflow.com/questions/58026809/how-to-ensure-ordered-processing-of-children-in-childadded-event-listener](https://stackoverflow.com/questions/58026809/how-to-ensure-ordered-processing-of-children-in-childadded-event-listener)

**Comment by alexames** [comment]
If I am understanding your question correctly, you have a location in the database with some number of children, and those children have field on them that you want to use to order them, such that when when they are added they will called in the order given by their index. 

So if you have...

    {
      "a": {
        "index": 100,
        "value": "apple"
      },
      "b": {
        "index": 101,
        "value": "banana"
      },
      "c": {
        "index": 102,
        "value": "carrot"
      }
    }

...and then you try to add new fields like this...

    {
      "d": {
        "index": 103,
        "value": "durian"
      },
      "e": {
        "index": 104,
        "value": "eggplant"
      },
      "f": {
        "index": 105,
        "value": "fig"
      }
    }

...you want to ensure that your ChildAdded callbacks get called in the order based on the index, is that correct?

Have you set the [OrderBy](https://firebase.google.com/docs/reference/unity/class/firebase/database/query#class_firebase_1_1_database_1_1_query_1a63006db86c9c79e84f92fe27d743b8ce) value on the DatabaseReference you're using? And if so, have you set the [".indexOn" value in the database rules](https://firebase.google.com/docs/database/security/indexing-data)? Setting both of those should ensure that you get values from the database in the order you specify.

**Comment by utkarshparasarampuria** [comment]
Thanks for the quick reply. I've ensured both the things you're suggesting, and most of the times things work perfectly.

MyDatabaseRef.OrderByChild("index").ChildAdded += ProcessChild;

I use this code to achieve it and it works fine. Suppose it takes 200ms for ProcessChild() to finish processing a child that is added to the database location. And suppose 5 children with indexes 106, 107, 108, 109, 110 are added at this database location at the same moment (I'm using cloud functions to do this). I understand that ProcessChild() will be called in the proper order. My question is that is it possible that the child with index 107 starts to be processed say 50ms after the child with index 106 starts to be processed. In this case some part of their processing will happen in parallel. I want to know if all the ProcessChild() calls are executed parallely? Or does the next child processing wait for the older one to complete? I just need a yes/no answer for the possibility of parallelism in the ChildAdded callbacks.

I ask this because the bug I'm encountering should be encountered only if a child with a higher index gets processed before a child with a lower index. My ProcessChild function is small enough such that most of the times I do not encounter any bug, but in rare cases when one child might take some time to process, the other child with a higher index finishes processing and causes the bug. This is the hypothesis I'm building for the bug if the answer to the possibility of parallel execution is yes. And if that's the case, I think I'll have to implement a solution to eliminate this parallelism. If no, then I'll look for other options.

In any case, I'd like to know the answer to this question because RTDB will remain my choice of database for my next projects and I need be informed about details of how it works with Unity.

**Comment by alexames** [comment]
It's not clear to me exactly what you mean when you say "added at this database location at the same moment".

If you mean they are all added with the same function call, via  `update` or `set`  (which I believe is how you set those values via firebase functions) or all together in a single transaction, then I believe you should get all the callbacks at the same time in the expected order.

If you make multiple calls, even if they are done rapidly in succession, I do not believe you can be guaranteed that they'll all be processed in exactly the right order.

The safest way to do this on the Firebase Functions side is probably via a transaction. This will allow you to ensure that the Function making the update and the database server receiving the update are in sync and that the updates are made in the order you expect. This should also guarantee that the unity clients will receive updates in the right order as well.

**Comment by utkarshparasarampuria** [comment]
I understand it right about multiple calls not guaranteeing ordered processing on the client and I haven't implemented that. I'm using a single `update` call to add 3-4 children at a database location.

You say "then i believe you should get all the callbacks at the same time in the expected order." I'm trying to understand this behavior. Even if the callbacks are triggered in the correct order, is it possible that due to a lower index child taking a longer time to process, a child with a higher index completes processing first? Are these callbacks called parallely for each child added? Or does the callback waits to complete the processing of a child and only then processes another one? Does the callback triggering work in a queue-like manner, or the callbacks are triggered as soon as any child is received at the client?

**Comment by alexames** [comment]
When you make a single call to update, the database should be updated atomically, and the updates will be communicated to the client atomically as well. A single update will be sent from the server to your Unity client with all the changes you made. The database client has a single background thread for applying updates. When the application and/or the app make updates to the database, they are queued up and applied one at a time in the order they arrived.

Using the example I posted above, if the updates to locations d, e and f are made in a single update, you should receive that same set of updates together, and the function registered to OnChildAdded will be called on locations d, e and f in that order since that is what the index specifies.

**Comment by utkarshparasarampuria** [comment]
So basically the answer is no. The children are not processed parallely, but in a queue. If my understanding is correct here, then this issue can be closed. Thanks for the help.
