### ISSUE TITLE
Can you improve documentation of sdk?

### ISSUE THREAD

**Issue by tfe2012** [firebase/quickstart-unity#48]
Hi, can you add more information about push notification ?

I send notification to Messaging test app, build it.

I do all like in instruction. 

But don’t receive push notification.

How debug or understand error?

**Comment by stewartmiles** [comment]
Could you provide some more information about your issue?  Which platform
are you running on and targeting and which devices are you testing with?

Did you follow our documentation here:

   -
   https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/readme.md
   - https://firebase.google.com/docs/cloud-messaging/unity/client

Cheers,
Stewart

**Comment by tfe2012** [comment]
Yes, I follow this documentation:

https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/readme.md

I send try send notification to iPhone. This is my curl example.
curl -s "https://fcm.googleapis.com/fcm/send" -H "Authorization:key=AIzaSy.....dQdk" -H "Content-Type:application/json" -d '{"to": "fKCr4djxTik:AP.....U5QirDvsCx4-","priority" : "high", "vibrate": 1, "notification": { "title": "Port", "body" : "great", "color": "#379F00"}, "data": {"title" : "3.21.15", "body": 12345678}}'

**Comment by stewartmiles** [comment]
Do you have push notifications enabled in your iOS developer account?

Could you verify it's possible to send notifications via the Firebase
console to determine whether the issue is in your curl request?

**Comment by tfe2012** [comment]
Yes I enabled notifications.

Yes I try send notifications via the Firebase console. And I see it in app then it's run.

**Comment by stewartmiles** [comment]
If it's working in the Firebase console but not from a curl request, things
to check:

   - Verify the device ID is correct (you can try this by sending via the
   console as well)
   You could also try sending to a device group or all devices using curl
   to see whether the auth key is the problem.
   - Verify the API / Authorization key is correct (check against the
   console).

**Comment by tfe2012** [comment]
You understand me wrong :)

It's work well from curl and from console.

Problem is that I receive message in running application. I see them there. But I don't get any push notification.

**Comment by stewartmiles** [comment]
When the app is running a notification does not appear in the title bar -
this is by design as you can catch the message and display the notification
in app rather than as a system notification.  When the app is in the
background / not running the operating system displays the notification in
the notification bar instead.

Is this not the behavior you're expecting?

We have the same behavior on both Android and iOS:

https://firebase.google.com/docs/cloud-messaging/ios/receive
https://firebase.google.com/docs/cloud-messaging/android/receive

**Comment by tfe2012** [comment]
When my app is in the background  I don't receive any notification in the notification bar

I use unity sdk

**Comment by tfe2012** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/8733714/22219198/89ee62da-e1b2-11e6-98b3-0164d4086512.jpg)
![unnamed 1](https://cloud.githubusercontent.com/assets/8733714/22219200/8b274036-e1b2-11e6-8c07-e3885632da75.jpg)

This is screenshots from device

to show that notification are enabled and I don't receive any notifications

**Comment by tfe2012** [comment]
Then you build app in Unity you can check like "develop version"

Maybe need this check ?

**Comment by stewartmiles** [comment]
If it's working in the foreground and not in the background it sounds like you haven't configured APNS certs correctly as the Firebase Cloud Messaging needs to sent push notifications via Apple's servers when an app goes to the background or isn't running.

See https://firebase.google.com/docs/cloud-messaging/ios/certs for the setup instructions.

Another thing you could try is to test your config with the Obj-C iOS sample as well. https://github.com/firebase/quickstart-ios/tree/master/messaging If things still don't work then you definitely have an APNS setup issue and you can open a ticket with our support https://firebase.google.com/support/contact/troubleshooting/ and the support techs can help you debug there as you can share confidential info on that channel.

**Comment by tfe2012** [comment]
Thx, after build test application I found problem.

After build app in Unity, you open application in XCode. And you need turn on push notifications 
<img width="849" alt="screen shot 2017-01-30 at 14 49 36" src="https://cloud.githubusercontent.com/assets/8733714/22423660/5c948d98-e6fb-11e6-914c-de8e35e9b700.png">
