### ISSUE TITLE
E/FirebaseInstanceId: Google Play services missing or without correct permission.

### ISSUE THREAD

**Issue by CIVITAS-John** [firebase/quickstart-unity#480]
## Please fill in the following fields:
Unity editor version: 2018.4.9f1
Firebase Unity SDK version: 6.6.0
Firebase plugins in use: Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): None related
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
Configured Firebase with only analytics module. Try to test it on an emulator. Successfully built but without any data sent back. 

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes.

**Comment by CIVITAS-John** [comment]
The problem seems to be quite weird. Analytics actually works the first time I install the app, sending initial events; however, whatever event I try to send later, it will basically do nothing. I close the app and open it again, it won't work; only when I uninstall and reinstall will I be able to see another log in the realtime interface. 

In the Logcat, I repeatedly received: 10-02 04:29:17.240 5151-5175/com.civitas.quantumphysics E/FirebaseInstanceId: Google Play services missing or without correct permission.

However, in the first installation, I also get the same log. We are deploying this app to both U.S and Chinese users, the latter usually without Google Play services.

**Comment by CIVITAS-John** [comment]
In the quickstart app, I can see after 'Reset Analytics Data' another pack of data is sent, just as the re-installation case. Otherwise whatever event I sent I simply cannot track in the dashboard.

I tested both on my Android phone without Google Play Services, and in an emulator.

**Comment by chkuang-g** [comment]
Hi @CIVITAS-John 
Thank you for reporting this.

Just to clarify, the issue only happened when you uses Android phone without Google Play Services?  Does it happen if you an Android phone with Google Play Service?

Shawn

**Comment by chkuang-g** [comment]
Just got back from Analytics team.

In normal operations, GA4F will upload every hour or so whatever events except on first open of the app where we will upload after the first 10 seconds.

You can enable debug mode, and the instructions are here : https://firebase.google.com/docs/analytics/debugview#enabling_debug_mode

As for the log, Analytics will keep trying to get Firebase ID whenever it can to upload along event, so it will keep showing up but should not affect Analytics functionality.

Could you check if those event showed up after an hour and if the debug mode works for you?

Shawn

**Comment by CIVITAS-John** [comment]
Okay. I will look into this. But I wonder what will happen if the user opens the app for 10min and closes that? Will the data also be recorded if he never opens the app again?

**Comment by CIVITAS-John** [comment]
And are there any ways to modify this preset behaviour?

**Comment by chkuang-g** [comment]
AFAIK, the upload is done by a background service which does not matter whether your app is opened or not.

And I don't think you can change other than setting the property per device since this is for debug purpose only.

**Comment by CIVITAS-John** [comment]
So will it work as expected without Google Play Service? 

And how about the upload strategy on iOS? It seems that on iOS data are sent more frequently.

**Comment by CIVITAS-John** [comment]
Debug mode works. Do you know if Analytics works from Mainland China?

**Comment by CIVITAS-John** [comment]
I think it works.

**Comment by chkuang-g** [comment]
On iOS I think we try to upload before the app is completely closed.

The SDK will run on non Play devices and should work in China.

Shawn
