### ISSUE TITLE
I cannot write more than 10 Scores using the Example. This was working, now it is not.

### ISSUE THREAD

**Issue by dbarla** [firebase/quickstart-unity#481]
## Please fill in the following fields:
Unity editor version:  2019.2.6f1 - Unity 5.6.6f1 (tested on both)
Firebase Unity SDK version:  lastest 6
Firebase plugins in use (Auth, Database, etc.): Database
Additional SDKs you are using (Facebook, AdMob, etc.):  No.
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop):  Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I cannot add more than 10 Scores using the Example.
I've sent the project to Support.

System.Aggregation Exception after 10 Scores.
Sometimes, not even reaching 10 Scores.

Unstable and unusable now.
Database it's broken.

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

Yes.

**Comment by chkuang-g** [comment]
Hi @dbarla 

We need a bit more information from you.

- Does this happens in the editor or on Android?
- Could you post your log, at least the System.AggregationException?
- What Firebase SDK did you use to add scores?  Did you use RunTransaction?

Thanks
Shawn

**Comment by malyawka** [comment]
Also such a problem.

- Editor.
- The log does not write an error, the transaction returns with Exception Message: "Internal task faulted".![image](https://user-images.githubusercontent.com/35719795/66052857-f8b4b600-e539-11e9-8a91-d84f68e2ec87.png)
- 6.6.0. Yes, implement mutableData as List<object> and as Dictionary<string, object> returned this exception.
- 6.3.0 -> 6.6.0

**Comment by dbarla** [comment]
Hi,

Does this happens in the editor or on Android? Good question and im wondering the same.
For now i just see this on Editor, i didn't have the time to prepare a test from Android.

Could you post your log, at least the System.AggregationException?

inner?Firebase.Database.DatabaseException: Internal task faulted ---> System.AggregateException: Exception of type 'System.AggregateException' was thrown.
-----------------
Firebase.FirebaseException: 

  --- End of inner exception stack trace ---
0x00000001417C85FB (Unity) StackWalker::GetCurrentCallstack
0x00000001417CA2AF (Unity) StackWalker::ShowCallstack
0x00000001417A4220 (Unity) GetStacktrace
0x0000000140D53EDB (Unity) DebugStringToFile
0x0000000140D546BC (Unity) DebugStringToFile
0x000000014141DCF2 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000000003E7834EB (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,string,UnityEngine.Object)
0x000000003E7833D4 (Mono JIT Code) [DebugLogHandler.cs:9] UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[]) 
0x000000003E782D65 (Mono JIT Code) [Logger.cs:41] UnityEngine.Logger:Log (UnityEngine.LogType,object) 
0x000000003E782A76 (Mono JIT Code) [DebugBindings.gen.cs:103] UnityEngine.Debug:Log (object) 
0x0000000058124302 (Mono JIT Code) [UIHandler.cs:3489] UIHandler:<AddScore2>m__9 (System.Threading.Tasks.Task`1<Firebase.Database.DataSnapshot>) 
0x0000000058123CF9 (Mono JIT Code) [TaskExtension.cs:112] Firebase.Extensions.TaskExtension/<ContinueWithOnMainThread>c__AnonStorey8`1/<ContinueWithOnMainThread>c__AnonStorey9<object>:<>m__0 () 
0x000000003EFD07F1 (Mono JIT Code) [Dispatcher.cs:76] Firebase.Dispatcher:RunAsyncNow<bool> (System.Func`1<bool>) 
0x000000003EFD04AF (Mono JIT Code) [Dispatcher.cs:53] Firebase.Dispatcher:RunAsync<bool> (System.Func`1<bool>) 
0x000000003EFD032B (Mono JIT Code) [FirebaseHandler.cs:114] Firebase.Platform.FirebaseHandler:RunOnMainThreadAsync<bool> (System.Func`1<bool>) 
0x0000000058123BC6 (Mono JIT Code) [TaskExtension.cs:111] Firebase.Extensions.TaskExtension/<ContinueWithOnMainThread>c__AnonStorey8`1<object>:<>m__0 (System.Threading.Tasks.Task`1<object>) 
0x00000000581239EC (Mono JIT Code) System.Threading.Tasks.Task`1/<ContinueWith>c__AnonStorey1`1<object, object>:<>m__0 (System.Threading.Tasks.Task)
0x0000000058123771 (Mono JIT Code) System.Threading.Tasks.Task/<ContinueWith>c__AnonStorey0`1/<ContinueWith>c__AnonStorey1<object>:<>m__0 ()
0x000000005811F553 (Mono JIT Code) System.Threading.Tasks.Task:<immediateExecutor>m__1 (System.Action)
0x0000000058123612 (Mono JIT Code) System.Threading.Tasks.Task/<ContinueWith>c__AnonStorey0`1<object>:<>m__1 (System.Threading.Tasks.Task)
0x000000005811EF1E (Mono JIT Code) System.Threading.Tasks.Task`1<object>:RunContinuations ()
0x000000005811ECC2 (Mono JIT Code) System.Threading.Tasks.Task`1<object>:TrySetException (System.AggregateException)
0x000000005811DFB4 (Mono JIT Code) System.Threading.Tasks.TaskCompletionSource`1<object>:TrySetException (System.Exception)
0x000000005811DCB5 (Mono JIT Code) System.Threading.Tasks.TaskCompletionSource`1<object>:SetException (System.Exception)
0x00000000581231E1 (Mono JIT Code) [Query.cs:101] Firebase.Database.Query:CheckTaskStatus<object> (System.Threading.Tasks.Task,System.Threading.Tasks.TaskCompletionSource`1<object>) 
0x0000000058122FD7 (Mono JIT Code) [Query.cs:122] Firebase.Database.Query/<WrapInternalDataSnapshotTask>c__AnonStorey0:<>m__0 (System.Threading.Tasks.Task`1<Firebase.Database.Internal.InternalDataSnapshot>) 
0x0000000058121E8C (Mono JIT Code) System.Threading.Tasks.Task`1/<ContinueWith>c__AnonStorey0<object>:<>m__0 (System.Threading.Tasks.Task)
0x0000000058121D85 (Mono JIT Code) System.Threading.Tasks.Task/<ContinueWith>c__AnonStorey2:<>m__0 (System.Threading.Tasks.Task)
0x0000000058121B41 (Mono JIT Code) System.Threading.Tasks.Task/<ContinueWith>c__AnonStorey0`1/<ContinueWith>c__AnonStorey1<int>:<>m__0 ()
0x000000005811F553 (Mono JIT Code) System.Threading.Tasks.Task:<immediateExecutor>m__1 (System.Action)
0x000000005811F267 (Mono JIT Code) System.Threading.Tasks.Task/<ContinueWith>c__AnonStorey0`1<int>:<>m__1 (System.Threading.Tasks.Task)
0x000000005811EF1E (Mono JIT Code) System.Threading.Tasks.Task`1<object>:RunContinuations ()
0x000000005811ECC2 (Mono JIT Code) System.Threading.Tasks.Task`1<object>:TrySetException (System.AggregateException)
0x000000005811DFB4 (Mono JIT Code) System.Threading.Tasks.TaskCompletionSource`1<object>:TrySetException (System.Exception)
0x000000005811DCB5 (Mono JIT Code) System.Threading.Tasks.TaskCompletionSource`1<object>:SetException (System.Exception)
0x000000005811D39A (Mono JIT Code) [Future_InternalDataSnapshot.cs:71] Firebase.Database.Internal.Future_InternalDataSnapshot/<GetTask>c__AnonStorey0:<>m__0 () 
0x000000005811C767 (Mono JIT Code) [Future_InternalDataSnapshot.cs:147] Firebase.Database.Internal.Future_InternalDataSnapshot:SWIG_CompletionDispatcher (int) 
0x00000000580EC13C (Mono JIT Code) (wrapper native-to-managed) Firebase.Database.Internal.Future_InternalDataSnapshot:SWIG_CompletionDispatcher (int)
0x000007FEE4D937C3 (FirebaseCppApp-6.2.1) Firebase_Messaging_CSharp_delete_AndroidNotificationParams
0x000007FEE4D936EE (FirebaseCppApp-6.2.1) Firebase_Messaging_CSharp_delete_AndroidNotificationParams
0x000007FEE4D93A2B (FirebaseCppApp-6.2.1) Firebase_Messaging_CSharp_delete_AndroidNotificationParams
0x000000003F00766D (Mono JIT Code) (wrapper managed-to-native) Firebase.AppUtilPINVOKE:PollCallbacks ()
0x000000003F0074D5 (Mono JIT Code) [AppUtil.cs:32] Firebase.AppUtil:PollCallbacks () 
0x000000003F007439 (Mono JIT Code) [FirebaseAppUtils.cs:17] Firebase.Platform.FirebaseAppUtils:PollCallbacks () 
0x000000003F007038 (Mono JIT Code) [FirebaseHandler.cs:189] Firebase.Platform.FirebaseHandler:Update () 
0x000000003F006E06 (Mono JIT Code) [FirebaseMonoBehaviour.cs:29] Firebase.Platform.FirebaseMonoBehaviour:Update () 
0x000000000B4B7672 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x000007FEE8375CDF (mono) [mini.c:4937] mono_jit_runtime_invoke 
0x000007FEE82C8499 (mono) [object.c:2623] mono_runtime_invoke 
0x000000014107DC85 (Unity) scripting_method_invoke
0x0000000141073541 (Unity) ScriptingInvocation::Invoke
0x00000001414BC7CB (Unity) MonoBehaviour::CallMethodIfAvailable
0x00000001414C08CF (Unity) MonoBehaviour::CallUpdateMethod
0x0000000140AD6F66 (Unity) BaseBehaviourManager::CommonUpdate<BehaviourManager>
0x0000000140AD7B5F (Unity) BehaviourManager::Update
0x0000000140D88687 (Unity) PlayerLoop
0x000000014174467E (Unity) Application::UpdateScene
0x0000000141745E4F (Unity) Application::UpdateSceneIfNeeded
0x000000014174E7FA (Unity) Application::TickTimer
0x000000014181962C (Unity) CrashCallback
0x000000014181B1B4 (Unity) WinMain
0x0000000141B06734 (Unity) strnlen
0x0000000076FF59CD (kernel32) BaseThreadInitThunk


What Firebase SDK did you use to add scores? Did you use RunTransaction?

Yes:

 reference.RunTransaction(AddScoreTransaction)
        .ContinueWithOnMainThread(task => {
          if (task.Exception != null) {
            DebugLog(task.Exception.ToString());
          } else if (task.IsCompleted) {
            DebugLog("Transaction complete.");
          }
        });

Which Firebase version did you upgrade from? And what is the exact version number you are using now?

6.6.0, seeing the issue creating a project from fresh, no upgrade.

In my project, im upgrading since 2 years ago without this problem,
so i don't recall the last version before this happened.

**Comment by markchandler-google** [comment]
Hi @dbarla,

This issue should be fixed in the next Firebase release. Thanks for the bug report.

**Comment by DellaBitta** [comment]
Hi @dbarla,

This issue should now be fixed with the release of 6.7.0 last week.
