### ISSUE TITLE
Slowing down on first call to cloud function on android device

### ISSUE THREAD

**Issue by berabue** [firebase/quickstart-unity#482]
Unity editor version: 2019.1.8f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.): analytics, auth, messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook 7.17.0
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

The first time call a function after running app, get a response after approximately two minutes.

`exports.test = functions.https.onRequest((req, res) => {
    const now = Date.now();
    return res.send(JSON.stringify(now));
});`

The first time call a function, it responds slowly, but after I receive it, I get a very fast response.

In addition, when using Wi-Fi on the Android terminal, I get a very fast response. When use LTE, receive a very slow response.

In some cases, people who have tested on their Android devices receive quick response while using LTE.

What's wrong? I hope you help me.

**Comment by chkuang-g** [comment]
@berabue 

If I understand you correctly, you were using Firebase Cloud Function Unity SDK to call a Cloud Function.  The first time you call the function after launching the app would usually take a long time like 2 minutes.  But the following call would take a much shorter time.

A couple of question:

- Could you check your Firebase Console and see if your Cloud Function logged any error? 
- Does such delay happen if you kill your app and relaunch it again?
- Does it happen if you play in the editor too?
- When did it start to happen?  Did you upgrade the SDK before it started to happen?
- Could you try to upgrade to our latest SDK (6.6.0 now) and see if the issue is resolved?  You can also see the execution time there.

Shawn

**Comment by berabue** [comment]
@chkuang-g 

The function was used through the http request without invoking it using the Unity SDK.

- Firebase console check result error log not logged.
- If exit and rerun the app using Application.Quit() in Unity, I will receive a quick response, but if exit and rerun the app using the Android device Menu, I will receive a slow response.
- Get a quick response from the editor.
- There was no problem two weeks ago.
- I will try Unity SDK and record additional threads.

**Comment by chkuang-g** [comment]
"I will try Unity SDK and record additional threads."

Please do.  6.1.1 was released on June 7.  Many thing can be improved during this time.

Please let us know if the long delay still happens to you in the latest Firebase SDK.

Shawn

**Comment by berabue** [comment]
@chkuang-g 

Testing using the version 6.1.1 of the Firebase Cloud Functions SDK confirmed that the request was completed without delay.

However, a delay occurs when the SDK is not used and the http request is made.

I will be forced to add SDK due to delay in response from app in service.

But I don't think that's a fundamental solution. Is there any way to get a quick response to a http request?

**Comment by markchandler-google** [comment]
Since on android, OkHttpClient is used to make the request it might be related to this issue: https://github.com/square/retrofit/issues/1489

**Comment by stewartmiles** [comment]
@berabue if a delay occurs without the Unity SDK it makes me wonder whether you're forming the same request that is being generated by the SDK.  The Unity SDK uses the C++ and Android SDKs i.e it ends up hitting the code here https://github.com/firebase/firebase-android-sdk/blob/69f29d43f4b4e14bed7f5c44a1dc3883c11cce57/firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java#L238 which follows the protocol https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions/call .

To @markchandler-google 's point if you're using a different HTTP client like OkHttp it's possible a bug in that library is causing the slow start.
