### ISSUE TITLE
Crash: Caused by java.lang.Error signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by craNich** [firebase/quickstart-unity#484]
Unity editor version: 2019.1.9f1
Firebase Unity SDK version: 6.5.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Firestore, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): Mapbox 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
![crash](https://user-images.githubusercontent.com/53269312/66259336-18551400-e7b0-11e9-99ab-09f1eb7a2624.png)

Fatal Exception: java.lang.Error
FATAL EXCEPTION [UnityMain] Unity version : 2019.1.9f1 Device model : HUAWEI HRY-LX1 Device fingerprint: HONOR/HRY-LX1/HWHRY-H:9/HONORHRY-L21/266C432:user/release-keys

Errors:
Caused by java.lang.Error
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 000000a1 Build fingerprint: 'HONOR/HRY-LX1/HWHRY-H:9/HONORHRY-L21/266C432:user/release-keys' Revision: '0' pid: 32641, tid: 32693, name: UnityMain >>> appname <<< r0 d0d19010 r1 c0276290 r2 ffffffff r3 00000081 r4 c0276290 r5 c0276290 r6 c242f590 r7 d05f6388 r8 d05f655c r9 cf27e934 sl cf27f2cc fp cf27e7d0 ip 00000003 sp cf27e700 lr c1e42d90 pc cf991c9c cpsr 00007fb5

Caused by java.lang.Error
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000 Build fingerprint: 'HONOR/HRY-LX1/HWHRY-H:9/HONORHRY-L21/266C432:user/release-keys' Revision: '0' pid: 22964, tid: 23115, name: Thread Pool Wor >>> com.EpidemicGames.NajdiPrachy <<< r0 c3c08b10 r1 00000000 r2 d01ba3e8 r3 cf1ce4b8 r4 be13d590 r5 00000000 r6 be2220f0 r7 00000000 r8 c2c63c6c r9 c2c63c6c sl c0ec4838 fp c0ec4834 ip c0ec4640 sp c0ec47a0 lr cf1d2768 pc cf1d27bc cpsr 00005a4b

Hello, sometimes at start of my app I am getting crashes. At start of my app I am loading some game data from firebase database and parsing them. Based on that data I am creating a list of objects of class and instantiating some gameObjects. The crash happens after few added records / instantiated gameObjects and I have no idea why. Maybe it loads wrong data from firebase, or where can be the issue?
Similar crash sometimes happens after in game. It happens when I click on the instantiated gameObject, trigger it and call some function which sends data to database and stuff. But the data seems loaded from firebase without problems (I checked it). What I also saw is very strange. Few times I couldnt see the instantiated gameObject, but it existed, I could trigger him which lead to insta crash.

I just dont get it, what is wrong. This situations happens like 1 per 20 tries (app starts). 
Edit: Okey, when I read more data and then spawn more gameObjects, the chance of this crash increases. I would understand, that its some problem with instantiating too many objects or something, but ... it just does only in some percent of cases.

**Comment by craNich** [comment]
Okey, I actualy maybe solved the issue by simpy awaiting few seconds before loading the game data from firebase. Not sure where is the specific issue tho. And not sure if it wont occur again.

**Comment by cynthiajoan** [comment]
Hi @craNich, I'm wondering did you try repro the case with our database sample app?
