### ISSUE TITLE
Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), Error

### ISSUE THREAD

**Issue by cabanel** [firebase/quickstart-unity#485]
Hi,
I am receiving this with Crashlytics.
I am using Unity Firebase SDK 6.6.0 and Unity 2018.4.9f with a target architecture for Armv7 & Arm64.

Maybe someone encountered this and have a direction of how to solve this.

Log:

Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000007f62e34c44
Build fingerprint: 'Huawei/ALE-L21/hwALE-H:6.0/HuaweiALE-L21/C432B607:user/release-keys'
Revision: '0'
pid: 19256, tid: 19521, name: ExoPlayerImplIn  >>> *** <<<
    x0   0000005588dd1ed0  x1   0000007f62e34000  x2   0000000000000c44  x3   00000000000003bc
    x4   0000000000000000  x5   0000000000570000  x6   0000000000000000  x7   0000000000430000
    x8   0000000000000001  x9   0000007f86cf2000  x10  0000007f86cf49a0  x11  0000000000000036
    x12  0000000000000000  x13  0000000000080000  x14  0000000000000001  x15  0000000000000000
    x16  000000558504551c  x17  0000000000000000  x18  0000005585045518  x19  00000000000003bc
    x20  0000000000000c44  x21  0000007f549f8928  x22  0000007f62e34000  x23  00000000000003bc
    x24  0000000000000c44  x25  0000007f8b065000  x26  0000000000000000  x27  0000007f8b072ae8
    x28  0000000000000613  x29  0000007f549f8850  x30  0000007f8afcb830
    sp   0000007f549f8850  pc   0000007f8afcb51c  pstate 0000000080000000

       at [vdso].()
       at libandroid_runtime.()
       at libandroid_runtime.()
       at system@framework@boot.()

**Comment by cynthiajoan** [comment]
Hi @cabanel, could you also provide what Firebase product you are using, eg Auth/Database etc, and in which scenario the issue happens? We also recommend to try to repro the issue with our testapp, so we can have the same repro conditions.

**Comment by cabanel** [comment]
Analitics+Messaging+Crashlytics

I am receiving this with Crashlytics, I don't know the context

thanks

**Comment by cynthiajoan** [comment]
Thanks @cabanel. By reading the error message I noticed this line:
pid: 19256, tid: 19521, name: ExoPlayerImplIn >>> *** <<<
Are you using ExoPlayer in your app? This looks related to that library.

**Comment by cabanel** [comment]
it seems so, could this be the problem?

**Comment by cynthiajoan** [comment]
I would recommend to reach out to ExoPlayer's support channel. At the moment I don't have knowledge that there is compatible issue between Firebase and ExoPlayer.

**Comment by CarlosPerson** [comment]
I was having this error, took me a while to figure it out. Turns out that the sign-in callback is called on a separate Thread (a Task). If you try to call the Unity API within that thread, memory segmentation errors like this will happen. 

In order to make the sign-in thread-safe, use this:

```
GoogleSignIn.DefaultInstance.SignIn()
                .ContinueWith(OnAuthenticationFinished, TaskScheduler.FromCurrentSynchronizationContext());
```

Hope this helps you, or at least puts you in the right track to fix your issue!

**Comment by patm1987** [comment]
If the above answer fixes your issue, consider using the Firebase extension method [ContinueWithOnMainThread](https://firebase.google.cn/docs/reference/unity/class/firebase/extensions/task-extension). It will be a wee bit safer as far as where it enters your Unity process. I go on a deep dive of Unity and threading here:
https://firebase.googleblog.com/2019/07/firebase-and-tasks-how-to-deal-with.html

**Comment by cabanel** [comment]
thanks
