### ISSUE TITLE
App crash on Launch in iOS after static splash 

### ISSUE THREAD

**Issue by 70nybl4nc0** [firebase/quickstart-unity#486]
## Please fill in the following fields:
Unity editor version: 2018.3.11
Firebase Unity SDK version: 6.0.3
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook and Google/SignIn
Platform you are using the Unity editor on (Mac, Windows, or Linux): Window, and Unity Cloud Build
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

### Description:

The iOS app is compiled, and is uploaded to Test Flight perfectly. But after the static splash the app exit the execution.

### Crash Logs:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1a357898c __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1a32a10a4 objc_exception_throw + 56 (objc-exception.mm:565)
2   CoreFoundation                	0x1a347c43c -[NSObject(NSObject) doesNotRecognizeSelector:] + 140 (NSObject.m:144)
3   CoreFoundation                	0x1a357ce08 ___forwarding___ + 1324 (NSForwarding.m:3325)
4   CoreFoundation                	0x1a357ebec _CF_forwarding_prep_0 + 92
5   {AppName}                     	0x10371df90 firebase::App::Create(firebase::AppOptions const&, char const*) + 480
6   {AppName}                     	0x10371dd60 firebase::App::Create() + 84
7   {AppName}                     	0x103724870 firebase::AppGetOrCreateInstance(firebase::AppOptions const*, char const*) + 184
8   {AppName}                     	0x10384acdc FirebaseApp_CreateInternal_m039014CF3B7DB1B092068767F49B9E0C9D9C11D6 + 84 (Bulk_Firebase.App_0.cpp:5112)
9   {AppName}                     	0x103848b6c FirebaseApp_CreateAndTrack_m9432CF67F169FAFC2D57F7C8E2460CBE174CB6F7 + 364 (Bulk_Firebase.App_0.cpp:8340)
10  {AppName}                     	0x10384d264 Listener__ctor_mC45E321812941A2EAF18DA7C324384CBF8DF047F + 180 (Bulk_Firebase.Messaging_0.cpp:4248)
11  {AppName}                     	0x10384c09c Listener_Create_m483EBB5038EAD465DBDF0B3A039144B5975B03C3 + 156 (Bulk_Firebase.Messaging_0.cpp:4305)
12  {AppName}                     	0x10384bfe0 FirebaseMessaging__cctor_m843511351AB475AC95CF227A47B213CAAD1F60FF + 52 (Bulk_Firebase.Messaging_0.cpp:3560)
13  {AppName}                     	0x102c46780 RuntimeInvoker_FalseVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void (*)(), MethodInfo const*,... + 20 (Il2CppInvokerTable.cpp:36414)
14  {AppName}                     	0x1036f5598 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 108 (Runtime.cpp:531)
15  {AppName}                     	0x1036f4090 il2cpp::vm::Runtime::ClassInit(Il2CppClass*) + 356 (Runtime.cpp:830)
16  {AppName}                     	0x103756174 FirebaseManager_Start_m56CA419BE12EC35D1F0BE9C116A91DC130A4F32F + 136 (Bulk_Assembly-CSharp_1.cpp:43147)
17  {AppName}                     	0x102c468a0 RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void (*)(), MethodInfo const*, ... + 20 (Il2CppInvokerTable.cpp:36449)
18  {AppName}                     	0x1036f5598 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 108 (Runtime.cpp:531)
19  {AppName}                     	0x1031b9744 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExc... + 108 (ScriptingApi_Il2Cpp.cpp:243)
20  {AppName}                     	0x1031c15a4 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 56 (ScriptingInvocation.cpp:347)
21  {AppName}                     	0x1031cb17c MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingEx... + 968 (MonoBehaviour.cpp:0)
22  {AppName}                     	0x1031cb374 MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) + 84 (MonoBehaviour.cpp:888)
23  {AppName}                     	0x1031ca184 MonoBehaviour::DelayedStartCall(Object*, void*) + 104 (MonoBehaviour.cpp:508)
24  {AppName}                     	0x10308b310 DelayedCallManager::Update(int) + 652 (CallDelayed.cpp:179)
25  {AppName}                     	0x103131790 ExecutePlayerLoop(NativePlayerLoopSystem*) + 88 (PlayerLoop.cpp:347)
26  {AppName}                     	0x1031317c4 ExecutePlayerLoop(NativePlayerLoopSystem*) + 140 (PlayerLoop.cpp:364)
27  {AppName}                     	0x10313199c PlayerLoop() + 212 (PlayerLoop.cpp:418)
28  {AppName}                     	0x103304e4c UnityPlayerLoopImpl(bool) + 52 (LibEntryPoint.mm:0)
29  {AppName}                     	0x102b3863c UnityRepaint + 140 (UnityAppController+Rendering.mm:276)
30  {AppName}                     	0x102b38528 -[UnityAppController(Rendering) repaintDisplayLink] + 88 (UnityAppController+Rendering.mm:71)
31  QuartzCore                    	0x1a9dbe514 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 632 (CADisplay.mm:2486)
32  QuartzCore                    	0x1a9e88774 display_timer_callback(__CFMachPort*, void*, long, void*) + 264 (CADisplayTimer.cpp:164)
33  CoreFoundation                	0x1a34cd6d4 __CFMachPortPerform + 172 (CFMachPort.c:533)
34  CoreFoundation                	0x1a34f6e5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56 (CFRunLoop.c:1937)
35  CoreFoundation                	0x1a34f6588 __CFRunLoopDoSource1 + 444 (CFRunLoop.c:2075)
36  CoreFoundation                	0x1a34f145c __CFRunLoopRun + 2168 (CFRunLoop.c:3098)
37  CoreFoundation                	0x1a34f08bc CFRunLoopRunSpecific + 464 (CFRunLoop.c:3192)
38  GraphicsServices              	0x1ad35c328 GSEventRunModal + 104 (GSEvent.c:2246)
39  UIKitCore                     	0x1a75866d4 UIApplicationMain + 1936 (UIApplication.m:4753)
40  {AppName}                     	0x102b30950 main + 160 (main.mm:41)
41  libdyld.dylib                 	0x1a337b460 start + 4

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001a3370ebc __pthread_kill + 8
1   libsystem_pthread.dylib       	0x00000001a3290c1c pthread_kill$VARIANT$armv81 + 192 (pthread.c:1456)
2   libsystem_c.dylib             	0x00000001a31e0824 abort + 100 (abort.c:110)
3   {AppName}                     	0x000000010368fc4c uncaught_exception_handler + 28
4   {AppName}                     	0x0000000102b41c04 UncaughtExceptionHandler(NSException*) + 172 (CrashReporter.mm:94)
5   {AppName}                     	0x0000000102cdcc18 FBSDKExceptionHandler + 64 (FBSDKCrashHandler.m:155)
6   CoreFoundation                	0x00000001a3578c94 __handleUncaughtException + 636 (NSException.m:253)
7   libobjc.A.dylib               	0x00000001a32a134c _objc_terminate() + 112 (objc-exception.mm:700)
8   libc++abi.dylib               	0x00000001a3346304 std::__terminate(void (*)()) + 16 (cxa_handlers.cpp:59)
9   libc++abi.dylib               	0x00000001a3345ed8 __cxa_rethrow + 144 (cxa_exception.cpp:618)
10  libobjc.A.dylib               	0x00000001a32a1258 objc_exception_rethrow + 40 (objc-exception.mm:604)
11  CoreFoundation                	0x00000001a34f092c CFRunLoopRunSpecific + 576 (CFRunLoop.c:3206)
12  GraphicsServices              	0x00000001ad35c328 GSEventRunModal + 104 (GSEvent.c:2246)
13  UIKitCore                     	0x00000001a75866d4 UIApplicationMain + 1936 (UIApplication.m:4753)
14  {AppName}                     	0x0000000102b30950 main + 160 (main.mm:41)
15  libdyld.dylib                 	0x00000001a337b460 start + 4
```

### My podFile looks like:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Unity-iPhone' do
  pod 'Bolts', '~> 1.7'
  pod 'FBSDKCoreKit', '~> 5.2'
  pod 'FBSDKLoginKit', '~> 5.2'
  pod 'FBSDKShareKit', '~> 5.2'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Google/SignIn'
end

**Comment by 70nybl4nc0** [comment]
> ## Please fill in the following fields:
> Unity editor version: 2018.3.11
> Firebase Unity SDK version: 6.0.3
> Firebase plugins in use (Auth, Database, etc.): Messaging
> Additional SDKs you are using (Facebook, AdMob, etc.): Facebook and Google/SignIn
> Platform you are using the Unity editor on (Mac, Windows, or Linux): Window, and Unity Cloud Build
> Platform you are targeting (iOS, Android, and/or desktop): iOS
> 
> ## Please describe the issue here:
> (Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
> 
> ### Description:
> The iOS app is compiled at Cloud, and is uploaded to Test Flight perfectly. But after the static splash the app exit the execution.
> 
> ### Crash Logs:
> Exception Type: EXC_CRASH (SIGABRT)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note: EXC_CORPSE_NOTIFY
> Triggered by Thread: 0
> 
> Last Exception Backtrace:
> 0 CoreFoundation 0x1a357898c __exceptionPreprocess + 220 (NSException.m:199)
> 1 libobjc.A.dylib 0x1a32a10a4 objc_exception_throw + 56 (objc-exception.mm:565)
> 2 CoreFoundation 0x1a347c43c -[NSObject(NSObject) doesNotRecognizeSelector:] + 140 (NSObject.m:144)
> 3 CoreFoundation 0x1a357ce08 _**forwarding**_ + 1324 (NSForwarding.m:3325)
> 4 CoreFoundation 0x1a357ebec _CF_forwarding_prep_0 + 92
> 5 {AppName} 0x10371df90 firebase::App::Create(firebase::AppOptions const&, char const*) + 480
> 6 {AppName} 0x10371dd60 firebase::App::Create() + 84
> 7 {AppName} 0x103724870 firebase::AppGetOrCreateInstance(firebase::AppOptions const*, char const*) + 184
> 8 {AppName} 0x10384acdc FirebaseApp_CreateInternal_m039014CF3B7DB1B092068767F49B9E0C9D9C11D6 + 84 (Bulk_Firebase.App_0.cpp:5112)
> 9 {AppName} 0x103848b6c FirebaseApp_CreateAndTrack_m9432CF67F169FAFC2D57F7C8E2460CBE174CB6F7 + 364 (Bulk_Firebase.App_0.cpp:8340)
> 10 {AppName} 0x10384d264 Listener__ctor_mC45E321812941A2EAF18DA7C324384CBF8DF047F + 180 (Bulk_Firebase.Messaging_0.cpp:4248)
> 11 {AppName} 0x10384c09c Listener_Create_m483EBB5038EAD465DBDF0B3A039144B5975B03C3 + 156 (Bulk_Firebase.Messaging_0.cpp:4305)
> 12 {AppName} 0x10384bfe0 FirebaseMessaging__cctor_m843511351AB475AC95CF227A47B213CAAD1F60FF + 52 (Bulk_Firebase.Messaging_0.cpp:3560)
> 13 {AppName} 0x102c46780 RuntimeInvoker_FalseVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void (_)(), MethodInfo const_,... + 20 (Il2CppInvokerTable.cpp:36414)
> 14 {AppName} 0x1036f5598 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 108 (Runtime.cpp:531)
> 15 {AppName} 0x1036f4090 il2cpp::vm::Runtime::ClassInit(Il2CppClass*) + 356 (Runtime.cpp:830)
> 16 {AppName} 0x103756174 FirebaseManager_Start_m56CA419BE12EC35D1F0BE9C116A91DC130A4F32F + 136 (Bulk_Assembly-CSharp_1.cpp:43147)
> 17 {AppName} 0x102c468a0 RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017(void (_)(), MethodInfo const_, ... + 20 (Il2CppInvokerTable.cpp:36449)
> 18 {AppName} 0x1036f5598 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 108 (Runtime.cpp:531)
> 19 {AppName} 0x1031b9744 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExc... + 108 (ScriptingApi_Il2Cpp.cpp:243)
> 20 {AppName} 0x1031c15a4 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 56 (ScriptingInvocation.cpp:347)
> 21 {AppName} 0x1031cb17c MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingEx... + 968 (MonoBehaviour.cpp:0)
> 22 {AppName} 0x1031cb374 MonoBehaviour::InvokeMethodOrCoroutineChecked(ScriptingMethodPtr, ScriptingObjectPtr) + 84 (MonoBehaviour.cpp:888)
> 23 {AppName} 0x1031ca184 MonoBehaviour::DelayedStartCall(Object*, void*) + 104 (MonoBehaviour.cpp:508)
> 24 {AppName} 0x10308b310 DelayedCallManager::Update(int) + 652 (CallDelayed.cpp:179)
> 25 {AppName} 0x103131790 ExecutePlayerLoop(NativePlayerLoopSystem*) + 88 (PlayerLoop.cpp:347)
> 26 {AppName} 0x1031317c4 ExecutePlayerLoop(NativePlayerLoopSystem*) + 140 (PlayerLoop.cpp:364)
> 27 {AppName} 0x10313199c PlayerLoop() + 212 (PlayerLoop.cpp:418)
> 28 {AppName} 0x103304e4c UnityPlayerLoopImpl(bool) + 52 (LibEntryPoint.mm:0)
> 29 {AppName} 0x102b3863c UnityRepaint + 140 (UnityAppController+Rendering.mm:276)
> 30 {AppName} 0x102b38528 -[UnityAppController(Rendering) repaintDisplayLink] + 88 (UnityAppController+Rendering.mm:71)
> 31 QuartzCore 0x1a9dbe514 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 632 (CADisplay.mm:2486)
> 32 QuartzCore 0x1a9e88774 display_timer_callback(__CFMachPort*, void*, long, void*) + 264 (CADisplayTimer.cpp:164)
> 33 CoreFoundation 0x1a34cd6d4 __CFMachPortPerform + 172 (CFMachPort.c:533)
> 34 CoreFoundation 0x1a34f6e5c **CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION** + 56 (CFRunLoop.c:1937)
> 35 CoreFoundation 0x1a34f6588 __CFRunLoopDoSource1 + 444 (CFRunLoop.c:2075)
> 36 CoreFoundation 0x1a34f145c __CFRunLoopRun + 2168 (CFRunLoop.c:3098)
> 37 CoreFoundation 0x1a34f08bc CFRunLoopRunSpecific + 464 (CFRunLoop.c:3192)
> 38 GraphicsServices 0x1ad35c328 GSEventRunModal + 104 (GSEvent.c:2246)
> 39 UIKitCore 0x1a75866d4 UIApplicationMain + 1936 (UIApplication.m:4753)
> 40 {AppName} 0x102b30950 main + 160 (main.mm:41)
> 41 libdyld.dylib 0x1a337b460 start + 4
> 
> Thread 0 name:
> Thread 0 Crashed:
> 0 libsystem_kernel.dylib 0x00000001a3370ebc __pthread_kill + 8
> 1 libsystem_pthread.dylib 0x00000001a3290c1c pthread_kill$VARIANT$armv81 + 192 (pthread.c:1456)
> 2 libsystem_c.dylib 0x00000001a31e0824 abort + 100 (abort.c:110)
> 3 {AppName} 0x000000010368fc4c uncaught_exception_handler + 28
> 4 {AppName} 0x0000000102b41c04 UncaughtExceptionHandler(NSException*) + 172 (CrashReporter.mm:94)
> 5 {AppName} 0x0000000102cdcc18 FBSDKExceptionHandler + 64 (FBSDKCrashHandler.m:155)
> 6 CoreFoundation 0x00000001a3578c94 __handleUncaughtException + 636 (NSException.m:253)
> 7 libobjc.A.dylib 0x00000001a32a134c _objc_terminate() + 112 (objc-exception.mm:700)
> 8 libc++abi.dylib 0x00000001a3346304 std::__terminate(void (*)()) + 16 (cxa_handlers.cpp:59)
> 9 libc++abi.dylib 0x00000001a3345ed8 __cxa_rethrow + 144 (cxa_exception.cpp:618)
> 10 libobjc.A.dylib 0x00000001a32a1258 objc_exception_rethrow + 40 (objc-exception.mm:604)
> 11 CoreFoundation 0x00000001a34f092c CFRunLoopRunSpecific + 576 (CFRunLoop.c:3206)
> 12 GraphicsServices 0x00000001ad35c328 GSEventRunModal + 104 (GSEvent.c:2246)
> 13 UIKitCore 0x00000001a75866d4 UIApplicationMain + 1936 (UIApplication.m:4753)
> 14 {AppName} 0x0000000102b30950 main + 160 (main.mm:41)
> 15 libdyld.dylib 0x00000001a337b460 start + 4
> 
> ### My podFile looks like:
> source 'https://github.com/CocoaPods/Specs.git'
> platform :ios, '10.0'
> 
> target 'Unity-iPhone' do
> pod 'Bolts', '~> 1.7' pod 'FBSDKCoreKit', '~> 5.2'
> pod 'FBSDKLoginKit', '~> 5.2' pod 'FBSDKShareKit', '~> 5.2'
> pod 'Firebase/Core'
> pod 'Firebase/Messaging'
> pod 'Google/SignIn'
> end

**Comment by cynthiajoan** [comment]
Hi @70nybl4nc0, I'd like to ask can you repro the same issue with our testapp? Or can you share code snippets of how you initialize firebase in your app? What's the repro ratio?

**Comment by 70nybl4nc0** [comment]
HI @cynthiajoan , and thanks for the help. I debug mi app in XCode yesterday and i get a different log.this time. i add it to this issue https://github.com/firebase/quickstart-unity/issues/489, but you answer here... it happen every time after the splash.

About my initialization 
```
	public void Start()
	{
		#if USE_FIREBASE_MESSAGING
		Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
		Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
		#endif
	}
```

**Comment by 70nybl4nc0** [comment]
the problem was resolved by deleting :
pod 'Firebase/Core'
pod 'Google/SignIn'
and adding:
pod 'Firebase/Analytics'

**Comment by cynthiajoan** [comment]
Ah cool, glad that you've figured out the issue. Thanks for letting us know!
