### ISSUE TITLE
DatabaseReference.RunTransaction() fails with numeric keys when digit count increases

### ISSUE THREAD

**Issue by chronicgamedev** [firebase/quickstart-unity#487]
## Please fill in the following fields:
Unity editor version: 2019.2.5f1
Firebase Unity SDK version: 6.6
Firebase plugins in use (Auth, Database, etc.): realtime database
Additional SDKs you are using (Facebook, AdMob, etc.): none
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
After experiencing seemingly random firebase db failures I managed to isolate the failure condition:

Using keys derived from integers ("9", "10", "11", etc.), writing to the realtime db with DatabaseReference.RunTransaction() will fail when the digit count in the key increases, (i.e., from "9" to "10" or from "99" to "100"), and subsequent calls to .RunTransaction() at the same parent node will also fail.

Note that prefixing the numeric keys with a letter ("m9", "m10", "m11") will SUCCEED.

The workaround is a slow and bandwidth intensive "double checked locking" pattern using .Get/.SetValueAsync()

Attached text file is a C# script from the firebase Unity SDK modified to showcase the problem

[FirebaseComponent.txt](https://github.com/firebase/quickstart-unity/files/3694930/FirebaseComponent.txt)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

yes

**Comment by alexames** [comment]
Thanks for the repro steps, I'll take a look and see what I can find.

**Comment by Adnimistrator** [comment]
I have experienced similar bug and Unity editor will crash after transaction.  (my data is structured by years and weeks of the year)  
![firebase_data](https://user-images.githubusercontent.com/11898558/67080269-22eeb080-f195-11e9-9dcb-79db43aa8dc7.png)

When I try to modify data inside weeks all at once via transaction Unity editor will crash.

Is chronicgamedev's bug report considered as official firebase unity sdk bug? Will it be fixed any soon?

**Comment by DellaBitta** [comment]
Hi @chronicgamedev, the release with the fix has been pushed live. If you update to the the latest SDK (v6.7.0) the problem should be resolved. If you still have issues feel free to re-open this bug.
