### ISSUE TITLE
Unhandle exception crash iOS after splash

### ISSUE THREAD

**Issue by 70nybl4nc0** [firebase/quickstart-unity#489]
## Please fill in the following fields:
Unity editor version: 2018.3.11
Firebase Unity SDK version: 6.3.0
Firebase plugins in use (Auth, Database, etc.): Messa
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

- -[FIROptions initWithGoogleAppID:GCMSenderID:]: unrecognized selector sent to instance 0x28010a850
- [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
- <Error> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
- Uncaught exception: NSInvalidArgumentException: -[FIROptions initWithGoogleAppID:GCMSenderID:]: unrecognized selector sent to instance 0x28010a850

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by cynthiajoan** [comment]
Hi @70nybl4nc0 , so the error log points out the FIRApp is not configured, can you help verified that you've done all the steps listed in this [page](https://firebase.google.com/docs/ios/setup#initialize_firebase_in_your_app)? Thanks!

**Comment by 70nybl4nc0** [comment]
Ok, i'm going to close this issue, the problem was the pod file here https://firebase.google.com/docs/ios/setup#initialize_firebase_in_your_app
