### ISSUE TITLE
Overly long Editor dialog

### ISSUE THREAD

**Issue by kevinfoley** [firebase/quickstart-unity#490]
I _think_ this is the "do you want to remove outdated files?" dialog, but hard to tell because it goes off the top and bottom of the screen...

![FirebaseDialog](https://user-images.githubusercontent.com/7231744/66507214-a1579e00-ea83-11e9-95b5-12f118716f1f.png)

**Comment by cynthiajoan** [comment]
Hi @kevinfoley, I think we fixed the issue in our jar resolver [1.2.125](https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#version-12125---sep-23-2019), which is included in [Unity SDK 6.6.0](https://firebase.google.com/support/release-notes/unity#version_660_-_september_25_2019), please upgrade and see if that fix the issue. Thanks!

**Comment by kevinfoley** [comment]
@cynthiajoan  Thanks Cynthia! To be clear, I encountered this issue when upgrading from 6.4.0 to 6.6.0; sorry, I should have specified that in the original report.

**Comment by cynthiajoan** [comment]
@kevinfoley I see. In this case it should not affect your upgrade result, you don't need to worry about this issue. You can do a force resolve if you want, otherwise you will not see this long dialog in the future upgrade.

**Comment by cynthiajoan** [comment]
Would like to close this for now, if that still occurs, please reopen the issue.
