### ISSUE TITLE
Crashlytics broken in 2019.3b6

### ISSUE THREAD

**Issue by NilokiloxD** [firebase/quickstart-unity#493]
Unity editor version: 2019.3b6
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
The post build process crashes with a deprecated Unity - iPhone message

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

Stacktrace:
![IMG_20191011_214559](https://user-images.githubusercontent.com/50952613/66680311-8eee8780-ec70-11e9-8e5c-35744c26d895.jpg)

**Comment by DellaBitta** [comment]
Thank you for the ticket. I was able to reproduce this with the test app and I've created an internal ticket track this issue.

**Comment by jasonhu-g** [comment]
The bug will be fixed in the next release. Thanks!

**Comment by NilokiloxD** [comment]
Any date when this release will be out?
Also can you raise the ios deployment target in the pods file to 8.0 or higher because xcode 11 always complains that crashlytics and fabrics use 7.0 which is no longer supported.

**Comment by DellaBitta** [comment]
Hi @NilokiloxD, the release with the fix has been pushed live. If you update to the the latest SDK (v6.7.0) the problem should be resolved. If you still have issues feel free to re-open this bug.
