### ISSUE TITLE
Unable to install APK in 4.4 or lower

### ISSUE THREAD

**Issue by Ankit-Jegames** [firebase/quickstart-unity#495]
Unity editor version: Unity Editor 217.4.30f1
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
I can run my APK in all newer devices i.e. Android M, Android P, Android O etc, but when I tried to install that same APK in 4.2, 4.4.2 (devices Tecno R-7, Samsung TAB 3), etc. it is giving an error "Error while parsing package".

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes, only if I use Firebase Messaging and build an APK it gives the same error in the above-mentioned devices.

What's the issue repro rate? 100%

**Comment by DellaBitta** [comment]
Hi Ankit-Jegames,

Firebase Messaging requires a mininum of Android 4.1 and the Google Play Store must be installed on the device. [ Full info is here](https://firebase.google.com/docs/cloud-messaging/android/client).

Could you please double check that the Play Store app is installed., and if you're still having and issue could you please post a log for us to review?

Thanks!

**Comment by Ankit-Jegames** [comment]
[Log.txt](https://github.com/firebase/quickstart-unity/files/3734439/Log.txt)
@DellaBitta please check the attached file for Logs, I have Google play store installed on my "Galaxy TAB 3" and still got the error. 

Feel free to ask me anything if you don't find anything in log, what you were asking for.

**Comment by Ankit-Jegames** [comment]
Hey all, thanks to all of you to respond to this question.
I guess there was some micro mistake from my side I created new app added new google-services.json file with the new package name and app just got installed, it's working fine and also receiving notifications as well.

Please accept my apologies if you feel this was just west of your time.
Thank you, Sorry
