### ISSUE TITLE
System.AggregateException is thrown when sending invite

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#5]
I tried to run the Invite sample and received the following error when sending an invite:
```
System.AggregateException: Exception of type 'System.AggregateException' was thrown.
-----------------
Firebase.FirebaseException: 

UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityEngine.MonoBehaviour:print(Object) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:107)
UIHandler:DebugLog(String) (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:136)
UIHandler:HandleSentInvite(Task`1) (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:123)
System.Threading.Tasks.<ContinueWith>c__AnonStorey0:<>m__0(Task)
System.Threading.Tasks.<ContinueWith>c__AnonStorey2:<>m__0(Task)
System.Threading.Tasks.<ContinueWith>c__AnonStorey1:<>m__0()
System.Threading.Tasks.Task:<immediateExecutor>m__1(Action)
System.Threading.Tasks
```
Also, when I tried to create a dynamic link on the Firebase console manually and clicked the link to open the app, it crashes with the following error:
```
D/firebase: (InvitesClass) getInvitation:onResult:Status{statusCode=SUCCESS, resolution=null}
D/Unity: (InvitesClass) getInvitation:onResult:Status{statusCode=SUCCESS, resolution=null}: 0 at ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp:42 (17408, 0, 0)
I/Unity: (InvitesClass) getInvitation:onResult:Status{statusCode=SUCCESS, resolution=null}
         UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
         UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
         UnityEngine.Logger:Log(LogType, Object)
         UnityEngine.Debug:Log(Object)
         Firebase.FirebaseHandler:LogMessage(LogLevel, String)
          
         (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
         
         
         
         --------- beginning of crash
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9716 (irg.test)
```

**Comment by stewartmiles** [comment]
Did you sign your app?
If you didn't sign your application you won't be able to send invites.

From https://github.com/firebase/quickstart-unity/blob/master/invites/testapp/readme.md

- To [generate a SHA1](https://developers.google.com/android/guides/client-auth),
        first you will need to set the keystore in the Unity project.
        - Locate the `Publishing Settings` under `Player Settings`.
        - Select an existing keystore, or create a new keystore using the toggle.
        - Select an existing key, or create a new key using "Create a new key".
      - After setting the keystore and key, you can generate a SHA1 by
        running this command:
        ```
        keytool -exportcert -list -v -alias <key_name> -keystore <path_to_keystore>
        ```

You have the start of a crash (stack trace) in your report any chance you could share the complete log with us?  If you can't post the trace here you can share it privately via https://firebase.google.com/support/contact/bugs-features/ just reference this issue.

**Comment by comtaler** [comment]
Thanks for the reply. I originally started the test using our app's bundle ID. Now I re-tested it using the default bundle ID and created a new firebase project for it and things started to work fine. I will investigate more and update on this issue.

**Comment by comtaler** [comment]
Not sure what was causing this. Couldn't reproduce it anymore after switching back to my own app's bundle ID. It maybe that I didn't run Play Services Resolver after changing bundle ID. The invite flow works now.

**Comment by exzizt** [comment]
I just installed the Invites package and set everything up as per the guide. I am getting this exception as well, and my application IS signed.
