### ISSUE TITLE
Ingame Events Doesnt show

### ISSUE THREAD

**Issue by hanilak** [firebase/quickstart-unity#501]
### Please fill in the following fields:
Unity editor version: 2019.2.4f1
Firebase Unity SDK version: 6.4.0-6.6.0
Firebase plugins in use (Auth, Database, etc.):Firebase analytics,firebase messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Admob,EasyMobile
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
I built an apk file to confirm sdk install to get console and it went well but after some time i launched apk again but there is no event in streamview, but if i try debugview all the data can be seen in streamview
for good understanding this is workflow
1-build and apk and install it to my phone
2-play it around 5 min 
3-there is about 10-15 events in streamview
4-wait for some time
5-play it around 5 min again
6-there is no event on streamview(i checked streamview about 30 minutes after that)
7-uninstall apk from my phone
8-there is events from step-5 gameplay +remove event in streamview

so in general i think it is only sending install and remove package but i dont know how to solve it

**Comment by markchandler-google** [comment]
Hi @hanilak,

Thanks for the question. Looks like you are hitting a feature of analytics where it does bulk updates. Looks like `DebugView` in the Firebase console is updated more frequently and might solve your problem.

You can read more about it on [this blog post](https://firebase.googleblog.com/2016/11/how-long-does-it-take-for-my-firebase-analytics-data-to-show-up.html?m=1).

**Comment by hanilak** [comment]
@markchandler-google but thats not my problem, i already tried to debugview and i can see datas as i write in my question but i cant see datas in streamview, how often streamview events updating?
