### ISSUE TITLE
The received event of Dynamic Links is called many times on Android

### ISSUE THREAD

**Issue by akinobu-tani** [firebase/quickstart-unity#502]
### Please fill in the following fields:
Unity editor version: 2019.2.10f1
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.): Dynamic Links
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

1. Create a short link for Android app.
2. Tap the link outside the app. Then the app is displayed and the received event is called.
3. Tap the android home button.
4. Tap the app icon. Then the app is displayed and the received event with the same URL as the previous call is called again.

If this is repeated, the received event will be called many times
The same thing doesn't happen on iOS.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by stewartmiles** [comment]
Hi @akinobu-tani I've attempted to reproduce this behavior and I never see what you describe happen with the Dynamic Links quickstart.  If you have a reproducible case either sharing via drive / attachment or sending it to firebase.google.com/support for inspection / debugging would be useful.

This is what should be happening:
- The Android SDK fetches the dynamic link cached for the application and clears the cached link on the backend when the client has acknowledged receipt.
- Each time you bring the application to the foreground we have code that will hit the dynamic links backend to see whether a link is pending for the application and only notify the application if a new link is available.

So unless the backend was misbehaving when you were testing, I'm not sure how the behavior you're describing would happen.

**Comment by akinobu-tani** [comment]
@stewartmiles thanks for the response.
I could still reproduce it in my project, so I sent it to support.

**Comment by a-maurice** [comment]
Since it seems like this is an internal issue that has to be resolved via the support channel, closing this issue.
