### ISSUE TITLE
DllNotFoundException: FirebaseCppApp-6_6_0, i seen that this issue was raised and closed before. i didn't got solution from there, also there is no positive comments. so i want to know that is it possible to resolve this issue or not?

### ISSUE THREAD

**Issue by supermanstudeo** [firebase/quickstart-unity#503]
### Please fill in the following fields:
Unity editor version: 2019.2.8f1
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.):Auth
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):Mono

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
step 1:
generate Unity app with Firebase Auth with unity 2019.2.8f1 
step2:
export unity project to android with ETC2 and 'Export Project' checked.
step 3:
open exported file in android studio, then
generate .aar file by changing com.android.application to com.android.library.
step 4:
create or open another native android app and include .aar file as a new module, which generated in step 3. 
And you have an issue : 
DllNotFoundException: FirebaseCppApp-6_6_0

**Here is Logs** :
`
Unable to find FirebaseCppApp-6_6_0
10-31 18:51:09.081 22252-22427/com.pentasoft.socialad E/Unity: DllNotFoundException: FirebaseCppApp-6_6_0
        at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
      at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <8c7b73be776844879184b3886ba9cec3>:0 
    Rethrow as TypeInitializationException: The type initializer for 'SWIGE
`

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes
What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by markchandler-google** [comment]
Hi @supermanstudeo,

Can you please make sure you invoke the Play Services Resolver "Resolve" function before building to download and install required libraries.

![image](https://user-images.githubusercontent.com/372282/67971133-70254600-fbc9-11e9-8f3b-7116745765da.png)


More Info: https://medium.com/firebase-developers/how-to-manage-your-native-ios-and-android-dependencies-in-unity-like-firebase-921659843aef

**Comment by supermanstudeo** [comment]
Hi @markchandler-google 
Thanks for suggestion sir, but i tried it so many times before. I'm trying to resolve this error from days.

after exporting Unity game as a Android Project everything works perfectly.
but as i convert that unity Android project into .aar file and import it to my Native Android app, Firebase shows this error : 
DllNotFoundException: FirebaseCppApp-6_6_0

**Comment by patm1987** [comment]
Hi @supermanstudeo,

I suspect that you may be running into an issue with how the Unity-specific Android dependencies are shipped. You'll find all the relevant files included in "Assets/Firebaser/m2repository" and referenced in your exported `.gradle` file as:
```
        maven {
            url "file:////Users/martinpatrick/Documents/git/sword-chucks/SwordChucks/Assets/Firebase/m2repository" // Assets/Firebase/Editor/AnalyticsDependencies.xml:20, Assets/Firebase/Editor/AppDependencies.xml:20, Assets/Firebase/Editor/AuthDependencies.xml:20, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/DynamicLinksDependencies.xml:20, Assets/Firebase/Editor/StorageDependencies.xml:20
        }
```

I suspect that if you were to include this maven repository in the project where you also include your generated `.aar` file then you should be able to work around this issue. This is unfortunately hardcoded to the absolute path of where you checked out your Unity project, so you may want to either move this to a known location or edit the generated project to include the `aar` directly and include the dependencies giving you an issue as described [here](https://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst).

Let us know if this resolves you issue, and if it does definitely feel free to [file a feature request](https://firebase.google.com/support/troubleshooter/report/features/) if it's something you'd like to see automated (if you do this definitely include a link to this issue any any other relevant information about your use case).

--Patrick

**Comment by supermanstudeo** [comment]
Thanks @patm1987 for suggestion,

your idea solved DllNotFoundException: FirebaseCppApp-6_6_0 error,
and another error occurred as i build :

`
Manifest merger failed : Attribute provider#com.google.firebase.provider.FirebaseInitProvider@authorities value=(com.rt.fr.firebaseinitprovider) from [com.google.firebase.firebase-common-19.1.0.aar] AndroidManifest.xml:8:80-132
	is also present at [com.google.firebase:firebase-common:11.0.4] AndroidManifest.xml:6:19-78 value=(com.pentasoft.socialad.firebaseinitprovider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:8:5-184 to override.
`

**as it suggest to add**
`
'tools:replace="android:authorities"' to <provider> element  at AndroidManifest.xml:8:5-184 to override.
 `
**i can't find this provider element anywhere in any manifest files.**

here is my Native Apps Manifest file. in which .aar file included as a Module.

`
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.pentasoft.socialad">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/logo"
        android:label="SCCN"
        android:roundIcon="@mipmap/logo"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true"
        tools:replace="android:icon,android:theme,android:label">
        <activity android:name=".Start"></activity>

        <receiver android:name="com.tune.TuneTracker">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar" />
        <activity android:name=".LoginRegister.LogIn">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".LoginRegister.Register" />
        <activity android:name=".MyProfilee.ProfileCheckPassword" />
        <activity android:name=".MyProfilee.MyProfile" />
        <activity android:name=".Fragments.ShopAndEarn.ShopAndEarn" />
        <activity android:name=".SelfEarning.SelfEarnings" />
        <activity android:name=".CouponAndOffer.CouponsAndOffers" />
        <activity android:name=".WatchVideo" />
        <activity android:name=".LatestUpdateNews.LatestUpdateAndNews" />
        <activity android:name=".LoginRegister.CheckSponsor" />
        <activity android:name=".MyProfilee.ChangePassword" />
        <activity android:name=".MyProfilee.UpdateProfile" />
        <activity android:name=".InviteAndEarn.InviteAndEarn" />
        <activity android:name=".InviteAndEarn.InviteEarnImages" />
        <activity android:name=".Fragments.ShopAndEarn.OfferDetails" />
        <activity android:name=".SelfEarning.InstructionDialog" />
        <activity android:name=".Horoscope.Horoscope" />
        <activity android:name=".Horoscope.HoroscopeDetail" />
        <activity android:name=".Fragments.MyNetwork.NetworkDetail" />
        <activity android:name=".LatestUpdateNews.NewsDetail" />
        <activity android:name=".ChatSupport" />
        <activity android:name=".ContactUs" />
        <activity android:name=".Faq.FAQ" />
        <activity android:name=".HelpVideos.HelpVideos" />
        <activity android:name=".AboutUs" />
        <activity
            android:name=".AP.Main2Activity"
            android:label="@string/title_activity_main2"
            android:theme="@style/AppTheme" />
        <activity android:name=".Fragments.Recharge.Recharge2" />
        <activity android:name=".Fragments.Recharge.Operator" />
        <activity android:name=".Fragments.Recharge.Circle" />
        <activity android:name=".Fragments.Recharge.Payment_details" />
        <activity android:name=".AP.AdminPanel"></activity>

        <service
            android:name=".AP.FloatingViewService"
            android:enabled="true"
            android:exported="false"
            android:screenOrientation="sensorPortrait"
            android:showOnLockScreen="true" /> 
        <activity
            android:name=".hindi.MainActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar" />
        <activity android:name=".hindi.LoginRegister.Register" />
        <activity android:name=".hindi.MyProfilee.ProfileCheckPassword" />
        <activity android:name=".hindi.MyProfilee.MyProfile" />
        <activity android:name=".hindi.Fragments.ShopAndEarn.ShopAndEarn" />
        <activity android:name=".hindi.SelfEarning.SelfEarnings" />
        <activity android:name=".hindi.CouponAndOffer.CouponsAndOffers" />
        <activity android:name=".hindi.WatchVideo" />
        <activity android:name=".hindi.LatestUpdateNews.LatestUpdateAndNews" />
        <activity android:name=".hindi.LoginRegister.CheckSponsor" />
        <activity android:name=".hindi.MyProfilee.ChangePassword" />
        <activity android:name=".hindi.MyProfilee.UpdateProfile" />
        <activity android:name=".hindi.InviteAndEarn.InviteAndEarn" />
        <activity android:name=".hindi.InviteAndEarn.InviteEarnImages" />
        <activity android:name=".hindi.Fragments.ShopAndEarn.OfferDetails" />
        <activity android:name=".hindi.SelfEarning.InstructionDialog" />
        <activity android:name=".hindi.Horoscope.Horoscope" />
        <activity android:name=".hindi.Horoscope.HoroscopeDetail" />
        <activity android:name=".hindi.Fragments.MyNetwork.NetworkDetail" />
        <activity android:name=".hindi.LatestUpdateNews.NewsDetail" />
        <activity android:name=".hindi.ChatSupport" />
        <activity android:name=".hindi.ContactUs" />
        <activity android:name=".hindi.Faq.FAQ" />
        <activity android:name=".hindi.HelpVideos.HelpVideos" />
        <activity android:name=".hindi.AboutUs" />
        <activity android:name=".hindi.Fragments.Recharge.Recharge2" />
        <activity android:name=".hindi.Fragments.Recharge.Operator" />
        <activity android:name=".hindi.Fragments.Recharge.Circle" />
        <activity android:name=".hindi.Fragments.Recharge.Payment_details" />
        <activity android:name=".RedeemBalance.ReedemBalance" />
        <activity android:name=".RedeemBalance.RedeemDetails" />
        <activity android:name=".AP.BankReedem.BankReedem" />
    </application>

</manifest>
`

**Comment by supermanstudeo** [comment]
Thanks @patm1987 

i did as you suggested and DllNotFoundException: FirebaseCppApp-6_6_0 error gone,
**but as i run it in my Android Device it shows 'Setting up Firebase Auth', and not fetching any data.
here is the Screen Shot of my Mobile Device**,
![Screenshot_20191101-175813 1](https://user-images.githubusercontent.com/50273012/68025159-22e0cb80-fcd2-11e9-9034-587a2ebc8619.png)

**after i click on SignIn Anonymously it keep showing this**,
![Screenshot_20191101-175834 1](https://user-images.githubusercontent.com/50273012/68025243-558ac400-fcd2-11e9-9f4a-8d9eaa0f6f71.png)

**here is the Logs i'm getting in Android Studio,**
`
11-01 17:59:43.518 5314-5314/? E/Zygote: v2
11-01 17:59:43.518 5314-5314/? E/Zygote: accessInfo : 0
11-01 17:59:45.238 5314-5314/com.pentasoft.socialad E/ViewSystem: ViewRootImpl #2 Surface is not valid.
11-01 17:59:52.638 5314-5841/com.pentasoft.socialad E/firebase: method_ids[i] || (method.optional == kMethodOptional)
11-01 17:59:52.638 5314-5841/com.pentasoft.socialad E/firebase: Unable to find Method com/google/firebase/FirebaseApp.delete (signature '()V', instance).  Please verify the AAR which contains the com/google/firebase/FirebaseApp class is included in your app.
11-01 17:59:52.648 5314-5841/com.pentasoft.socialad E/firebase: g_initialized_count
11-01 17:59:52.728 5314-5485/com.pentasoft.socialad E/Unity: method_ids[i] || (method.optional == kMethodOptional)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
11-01 17:59:53.168 5314-5485/com.pentasoft.socialad E/firebase: method_ids[i] || (method.optional == kMethodOptional)
11-01 17:59:53.168 5314-5485/com.pentasoft.socialad E/Unity: method_ids[i] || (method.optional == kMethodOptional)
     
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
11-01 17:59:53.168 5314-5485/com.pentasoft.socialad E/firebase: Unable to find Method com/google/firebase/FirebaseApp.delete (signature '()V', instance).  Please verify the AAR which contains the com/google/firebase/FirebaseApp class is included in your app.
11-01 17:59:53.168 5314-5485/com.pentasoft.socialad E/firebase: g_initialized_count
`

**Comment by markchandler-google** [comment]
Hi @supermanstudeo,

Are you sure you are also including all the *.aar files that Firebase needs to work on android? You can find them under the Assets/Plugins/Android folder (selected ones are just an example. I think all of them are required):

![image](https://user-images.githubusercontent.com/372282/68039000-6d3d5a80-fc88-11e9-9a11-8681418d283c.png)

**Comment by supermanstudeo** [comment]
Hi,
@markchandler-google 
**i have Firebase in my native app V: 11.0.4 and In module its V19.1.0**
**so, if i'm adding this these 3 dependencies you suggested then, this error shown up:**

`
Duplicate class com.google.firebase.FirebaseApp found in modules classes.jar (com.google.firebase.firebase-common-19.1.0.aar) and classes.jar (com.google.firebase:firebase-common:11.0.4)
Duplicate class com.google.firebase.FirebaseNetworkException found in modules classes.jar (com.google.firebase.firebase-common-19.1.0.aar) and classes.jar (com.google.firebase:firebase-common:11.0.4)
Duplicate class com.google.firebase.FirebaseOptions found in modules classes.jar (com.google.firebase.firebase-common-19.1.0.aar) and classes.jar (com.google.firebase:firebase-common:11.0.4)
Duplicate class com.google.firebase.FirebaseOptions$Builder found in modules classes.jar (com.google.firebase.firebase-common-19.1.0.aar) and classes.jar (com.google.firebase:firebase-common:11.0.4)
Duplicate class com.google.firebase.FirebaseTooManyRequestsException found in modules classes.jar (com.google.firebase.firebase-common-19.1.0.aar) and classes.jar (com.google.firebase:firebase-common:11.0.4)
Duplicate class com.google.firebase.provider.FirebaseInitProvider found in modules classes.jar (com.google.firebase.firebase-common-19.1.0.aar) and classes.jar (com.google.firebase:firebase-common:11.0.4)
`

**Comment by supermanstudeo** [comment]
i Solved Everything.
Thanks both of you for support @markchandler-google and @patm1987 .
