### ISSUE TITLE
Firebase_App_CSharp_TerminatePlayServicesInternal crash in editor

### ISSUE THREAD

**Issue by ddalacu** [firebase/quickstart-unity#504]
Unity editor version: 2018.4.12
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.):Authentication, RealtimeDatabase,
Additional SDKs you are using (Facebook, AdMob, etc.): Admob, GameAnalytics 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Ios, Android
Scripting Runtime (Mono, and/or IL2CPP):Il2cpp/Mono

Crash while inside editor without no aparent reason only on specific pc (windows 7), on other pc it does not happen, all we have is the crash logs. On the device it happens we can reproduce it 100% now.
[error.log](https://github.com/firebase/quickstart-unity/files/3797774/error.log)
[Editor.log](https://github.com/firebase/quickstart-unity/files/3797775/Editor.log)

**Comment by markchandler-google** [comment]
Hi @ddalacu,

Looks like its crashing in setup. Have you called `CheckAndFixDependenciesAsync` before invoking any Firebase API's?

See: https://firebase.google.com/docs/unity/setup#confirm_google_play_version and https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#checkandfixdependenciesasync

**Comment by ddalacu** [comment]
Yes we are calling init async, could it be that we are not waiting the task to complete before calling    firebase api?

**Comment by markchandler-google** [comment]
Yes, please wait for it to complete and check the result.

**Comment by ddalacu** [comment]
Hi, it seems to work now, thanks for helping me out.I would make a suggestion that you guys print some kind of warning so other people that do this mistake can debug it.
