### ISSUE TITLE
Why Unity Firebase collect information in Editor?It's make my Editor freeze many times!

### ISSUE THREAD

**Issue by stkman** [firebase/quickstart-unity#506]
### Please fill in the following fields:
Unity editor version: 2019.2.f1
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Platform you are targeting (iOS, Android, and/or desktop): 
Scripting Runtime (Mono, and/or IL2CPP):

### Please describe the issue here:
![image](https://user-images.githubusercontent.com/6999099/68185181-e8ca3f00-ffdb-11e9-8d63-ff927a2c337f.png)

When editor console this, it's freeze 100%!  Just make me crazy!

### Please answer the following, if applicable:
no

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by stewartmiles** [comment]
AFAIK this is not information reported by the Firebase plugin.  We do not collect any information in the editor, feel free to disassemble Firebase.Editor.dll or browse through https://github.com/googlesamples/unity-jar-resolver .  We're currently plumbing in analytics but it's disabled at the moment and will be opt-in if / when it's available.
