### ISSUE TITLE
Crash in Cloud Messaging on Android

### ISSUE THREAD

**Issue by programmermattsrum** [firebase/quickstart-unity#508]
### Please fill in the following fields:
Unity editor version: 2018.4.12f1
Firebase Unity SDK version: 6.60
Firebase plugins in use (Auth, Database, etc.): Auth, Analytics, Realtime-Database, DynamicLinks, Messaging, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): Admob, Unity IAP, GooglePlayGames
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Crashlytics issue below - 

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
       at com.android.okhttp.internal.Util.skipAll(Util.java:172)
       at com.android.okhttp.internal.Util.discard(Util.java:154)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:619)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(com.google.firebase:firebase-messaging@@19.0.1:4)
       at com.google.firebase.messaging.zzi.close(com.google.firebase:firebase-messaging@@19.0.1:37)
       at com.google.firebase.messaging.zzb.zza(com.google.firebase:firebase-messaging@@19.0.1:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@19.0.1:59)
       at com.google.firebase.messaging.zzg.run(com.google.firebase:firebase-messaging@@19.0.1:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

N/A

What's the issue repro rate? (eg 100%, 1/5 etc)

I have seen this a couple of times

Device information

Device
Brand: samsung
Model: Galaxy S9
Orientation: Portrait
RAM free: 1.17 GB
Disk free: 28.6 GB
Operating System
Version: 9
Orientation: Portrait
Rooted: No

**Comment by stewartmiles** [comment]
@programmermattsrum thanks for the report it looks like an issue with the Cloud Messaging SDK.  I'm poking folks internally to see whether we can get more information on this
https://github.com/firebase/quickstart-android/issues/927

**Comment by programmermattsrum** [comment]
@stewartmiles Thanks for the quick response.

**Comment by stewartmiles** [comment]
@programmermattsrum we've looped in the Cloud Messaging folks and they're looking into it.

It appears to also be tracked by https://github.com/firebase/firebase-android-sdk/issues/709

**Comment by colbygarland** [comment]
I am having the same issues, it seems for it happens when the app is open and a Firebase Push Notification is received.

**Comment by D3m0n92** [comment]
Same problem here... Any solution?

**Comment by jgersindemir** [comment]
Same problem. Any solution ? or workaround ?

**Comment by D3m0n92** [comment]
> Same problem. Any solution ? or workaround ?

Yes, use OneSignal and don't use Firebase Coud Messaging.

**Comment by stewartmiles** [comment]
The issue has been fixed internally and only affected image messages on Android. Once the new Android SDK is out you can point the Unity SDK at the new Android library via MessagingDependencies.xml (see https://github.com/googlesamples/unity-jar-resolver/blob/master/README.md#android-resolver-usage for details on how to modify this file)

@D3m0n92 One Signal uses Firebase Cloud Messaging on Android, it's likely it works as it hasn't picked up the image messaging feature yet.

**Comment by jgerdoganakgun** [comment]
Hi @stewartmiles, 
Your internal fix was working until 3 Jan. It started to happen again. We using still firebase messaging 20.0.0 but we'll update to 20.1.0 as soon as possible. Could you check what is difference between before and after 3 january, please?

**Comment by stewartmiles** [comment]
The changes are documented in https://firebase.google.com/support/release-notes/android#messaging_v20-1-0 , you need 20.1.0 to pick up the fix for the Null Pointer Exception (NPE).

**Comment by DellaBitta** [comment]
Hi @programmermattsrum,

A fix for this went out in Firebase Cloud Messaging 20.1.0 which has been released. Could you try upgrading your Firebase SDK for Unity and see if it solves the problem?  Thanks!

**Comment by programmermattsrum** [comment]
Does 1.16 have the fix?  I have upgraded to that version.

Sent from Yahoo Mail on Android 
 
  On Fri, Jun 12, 2020 at 10:34 AM, DellaBitta<notifications@github.com> wrote:   


Hi @programmermattsrum,

A fix for this went out in Firebase Cloud Messaging 20.1.0 which has been released. Could you try upgrading your Firebase SDK for Unity and see if it solves the problem? Thanks!

**Comment by patm1987** [comment]
It should be in the [6.15.0 Unity SDK](https://firebase.google.com/support/release-notes/unity#version_6150_-_june_2_2020).

Is that what you meant with "1.16"?

**Comment by programmermattsrum** [comment]
Sorry yeah I meant that version

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 15, 2020 at 3:44 PM, Patrick<notifications@github.com> wrote:   


It should be in the 6.15.0 Unity SDK.

Is that what you meant with "1.16"?

**Comment by patm1987** [comment]
Sorry to keep bouncing this back and forth. Can you confirm whether or not you see the issue then (on the 6.15 release). If not, I'll close the bug but if you do I'll add the bug label again and re-open our internal issue.
