### ISSUE TITLE
Exception: Invalid PBX project

### ISSUE THREAD

**Issue by DavidAbrakam** [firebase/quickstart-unity#51]
Hello,
I'm currently tying to integrate your Unity package in my iOS game (I'm using Unity 5.4.2p1). But I cannot pass the XCode build phase...

I took for instance the unity "messaging" quickstart example, and followed precisely the informations of the readme file to build it. However, when I hit the build button and wait for the unity build to complete, at the very end of the build Unity logs this message

`Exception: Invalid PBX project (parsing line 0)
UnityEditor.iOS.Xcode.PBX.Parser.ParseTree () (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBX/Parser.cs:114)
UnityEditor.iOS.Xcode.PBXProjectData.ParseContent (System.String content) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:451)
UnityEditor.iOS.Xcode.PBXProjectData.ReadFromStream (System.IO.TextReader sr) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProjectData.cs:458)
UnityEditor.iOS.Xcode.PBXProject.ReadFromStream (System.IO.TextReader sr) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:868)
UnityEditor.iOS.Xcode.PBXProject.ReadFromString (System.String src) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/XCode/PBXProject.cs:863)
Google.IOSResolver.UpdateProjectDeps (BuildTarget buildTarget, System.String pathToBuiltProject)
Google.IOSResolver.OnPostProcessUpdateProjectDeps (BuildTarget buildTarget, System.String pathToBuiltProject)
UnityEditor.HostView:OnGUI()`

If I try to continue to follow the build instructions on the resulting XCode project (adding the UserNotification.framework to the list of dependencies, enabling the push notification service,...), at the link phase, XCode fails with the following link errors:

`Undefined symbols for architecture arm64:
 "_OBJC_CLASS_$_FIROptions", referenced from:
     objc-class-ref in libApp.a(app_ios_c76c7d869e568a9b561ea55e25a7dcc0.o)
 "_OBJC_CLASS_$_FIRInstanceID", referenced from:
     objc-class-ref in libMessaging.a(messaging_0d72481c6b9f9d4c5456dcb81aa103f1.o)
 "_OBJC_CLASS_$_FIRApp", referenced from:
     objc-class-ref in libApp.a(app_ios_c76c7d869e568a9b561ea55e25a7dcc0.o)
 "_OBJC_CLASS_$_FIRMessaging", referenced from:
     objc-class-ref in libMessaging.a(messaging_0d72481c6b9f9d4c5456dcb81aa103f1.o)
 "_kFIRInstanceIDTokenRefreshNotification", referenced from:
     ____ZN8firebase9messaging17NotifyListenerSetEPNS0_8ListenerE_block_invoke in libMessaging.a(messaging_0d72481c6b9f9d4c5456dcb81aa103f1.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

What can I do? I already checked and "pod --version" outputs 1.1.1.
Thanks!

**Comment by stewartmiles** [comment]
Exception: Invalid PBX project (parsing line 0) UnityEditor.iOS.Xcode.PBX.Parser.ParseTree

This sounds like https://github.com/firebase/quickstart-unity/issues/13 see https://github.com/CocoaPods/CocoaPods/issues/1275 where the Xcode project is rewritten as an xml file rather than a old-style plist (which is supported by the Unity Xcode API).

First thing to check is the format of the Xcode project, if it's an XML file it's probably worth reinstalling Cocoapods to make sure you really have the right version when it's executed by our plugin.  Failing that, it may be worth looking at the other plugins used by your game, it's possible another plugin is changing the Xcode project format.

Cheers,
Stewart

**Comment by DavidAbrakam** [comment]
Hello,
Thank you for the fast answer. I "brew unlink cocoapods", "brew update" then "brew install cocoapods" and it installed version 1.2.0 (instead of 1.1.1). The PBX error disappeared of Unity for subsequent builds.

This resolved the issue :)
