### ISSUE TITLE
FirebaseCppApp-6_7_0.bundle cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by MarcoWilliamsPF** [firebase/quickstart-unity#515]
### Please fill in the following fields:
Unity editor version: 2019.2.12f1
Firebase Unity SDK version: Latest
Firebase plugins in use (Auth, Database, etc.): database
Additional SDKs you are using (Facebook, AdMob, etc.):  none
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac OSX Catalina 10.15.1 
Platform you are targeting (iOS, Android, and/or desktop):  ALL
Scripting Runtime (Mono, and/or IL2CPP):  IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

* Install firebase SDK 
* Follow quickstart example
* Run project

The issue is that when I push player I get the following popups from the security of Catalina.

> FirebaseCppApp-6_7_0.bundle” cannot be opened because the developer cannot be verified. Are you sure you want to open it?
> 
> By opening this app, you will be overriding system security which can expose your computer and personal information to malware that may harm your Mac or compromise your privacy.
> 

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?  YES

What's the issue repro rate? (eg 100%, 1/5 etc) 
100%

**Comment by SlobodanNikolic** [comment]
Also have this issue, after upgrading to Catalina!

**Comment by Duna** [comment]
same here: https://drive.google.com/file/d/1_RRjEvfrAI9fYk10IXofKPr1AT7bSA6u/view?usp=sharing

**Comment by SlobodanNikolic** [comment]
Just go into security settings on your mac, and you will see firebase blocked because it has an untrusted developer. Allow it there and you are good to go. I solved it that way👍🏻

**Comment by Duna** [comment]
Yup, it just works!

**Comment by a-maurice** [comment]
Thanks for bringing this to our attention, and thanks for adding that way to solve it.  We will look into what is causing this issue.

**Comment by chkuang-g** [comment]
I think what @SlobodanNikolic said is the right solution.  Unfortunately this is how Catalina works.
