### ISSUE TITLE
Error: There is no user record corresponding to this identifier. The user may have been deleted.

### ISSUE THREAD

**Issue by josemendezpUdem** [firebase/quickstart-unity#518]
### Please fill in the following fields:
Unity editor version: 2018.3.4f1
Firebase Unity SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.): Auth, RealtimeDatabase
Additional SDKs you are using (Facebook, AdMob, etc.): none
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android/iOS
Scripting Runtime (Mono, and/or IL2CPP): I really dont know...

### Please describe the issue here:
When I try to log in using firebase, I recieve this error:
I have tried to create delete and create users, and also create a whole new Firebase project...

```
Failed to access task with System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: There is no user record corresponding to this identifier. The user may have been deleted.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: There is no user record corresponding to this identifier. The user may have been deleted.
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.FirebaseException: There is no user record corresponding to this identifier. The user may have been deleted.<---
<---

UnityEngine.Debug:LogWarning(Object)
<DoAccessUser>d__10:MoveNext() (at Assets/FirebaseManager.cs:118)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

Few days ago I was able to log in without problem, and I haven't moved anything from my LogIn system.

### Please answer the following, if applicable:
This is my code:

    IEnumerator DoAccessUser(string email, string password)
    {
        var auth = FirebaseAuth.DefaultInstance;
        var logTask = auth.SignInWithEmailAndPasswordAsync(email, password);
        yield return new WaitUntil(() => logTask.IsCompleted);

        if (logTask.Exception != null)
        {
            Debug.LogWarning($"Failed to access task with {logTask.Exception}");
        }
        else
        {
            Debug.Log($"Successfully access user {logTask.Result.Email}");
        }
    }

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by alexames** [comment]
Are you able to register new users? You said you tried to delete and create users, is is possible you've accidentally deleted the user you were using?
