### ISSUE TITLE
Compatibility of database SDK with older Android version

### ISSUE THREAD

**Issue by winz97006** [firebase/quickstart-unity#52]
Hi,
I'm running the database/testapp sample without problems with Android 5 or 6, but the call to .ContinueWith never returns neither on a Galaxy Tab (Android 4.4.2) nor on a S3 (Android 4.4.2).

I have the same problem when calling .Result on a simple GetValueAsync(): the call never returns.

Is there any known compatibility issue?

Thanks
Vince

**Comment by stewartmiles** [comment]
We fixed an issue with Task.ContinueWith() in release 1.1.2 (https://firebase.google.com/support/release-notes/unity#1.1.2) are you able to reproduce with the latest release?

**Comment by stewartmiles** [comment]
We resolved a whole load of bugs in our 3.0.0 release, please give it a try and reopen if you're still having problems https://firebase.google.com/support/release-notes/unity#3.0.0
