### ISSUE TITLE
Offline authentication with Google Play Games

### ISSUE THREAD

**Issue by andrex903** [firebase/quickstart-unity#522]
There is a way to login using previous session token when user is offline? At the moment i get the error 
"2019/11/25 13:34:09.880 13223 13223 Error SignInRequest: Sign-in failed with status code: 7"

here the code i use
```c#
public void Login(Action<bool> callback)
	{
		if (IsAuthenticated) return;
		void OnGoogleLogin(string authCode)
		{
			if (authCode.Equals(string.Empty))
			{
				callback(false);
				return;
			}
			Credential credential = PlayGamesAuthProvider.GetCredential(authCode);
			auth.SignInWithCredentialAsync(credential).ContinueWith(task =>
			{
				OnLogin(task, callback);
			}, TaskScheduler.FromCurrentSynchronizationContext());
		}
		GoogleController.main.Login(OnGoogleLogin);
	}
```

**Comment by alexames** [comment]
Hi Andrex903, 

You have to be online to log in. If you log in and then go offline you can remain logged in. However, once you've logged out you can't log in again until you are online again.
