### ISSUE TITLE
Some of Firebase plugins does not include on IL2CPP? [GameAssembly.dll]

### ISSUE THREAD

**Issue by davoodkharmanzar** [firebase/quickstart-unity#523]
why these plugins does not include on IL2CPP? [GameAssembly.dll]
is that secure?

![Capture](https://user-images.githubusercontent.com/10723167/69557611-c16fed80-0f5b-11ea-94e9-b232c45f27ac.PNG)

and is it possible to using firebase without json?
i mean implement the json contents on source code like these:
                APP = FirebaseApp.DefaultInstance;
                APP.Options.ApiKey =
                APP.Options.AppId = 
                APP.Options.DatabaseUrl = 
any suggestion?

**Comment by alexames** [comment]
Firebase works with IL2CPP, if you are having issues getting it to work let me know and we can try to figure out if its an issue with your configuration or an issue with the library. 

The DefaultInstance of FirebaseApp is constructed based on the google-services.json file that you provide, but if you don't want to use that you can create an AppOptions object and manually fill in the fields, then pass those to App.Create(options) to create a custom FirebaseApp. Generally it's easier to just use the google-services.json file, so only do this if you have a good reason to. 

These pages might be helpful to you:
- [Firebase.AppOptions reference documentation](https://firebase.google.com/docs/reference/unity/class/firebase/app-options)  
- [Firebase.FirebaseApp reference documentation](https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app)

**Comment by davoodkharmanzar** [comment]
@alexames 
thanks for your reply :]
but unfortunately and sadly ,seems that Firebase does not working on iran ...
everything is working if using VPN :[

i need Realtime DB and Phone Authentication  :[

so, does exists alternatives to do these?
