### ISSUE TITLE
Does exists any success story on Android?

### ISSUE THREAD

**Issue by davoodkharmanzar** [firebase/quickstart-unity#524]
hello guys,
i tried PhoneAuth + Anonymous login + realtime database ...

the Anonymous login and realtime database are working good on PC and android ...
but i can't get any successful results with phoneauth on android !!
and seems does not working anymore!! not codesent ... not verfication faild ... not messages ... not errors :[

i tried with 6.7 and 6.6 and 5.7 SDKs ...
on emulators and realphones with android 6.0 and 8.1 ...

so, any suggestion?
thanks.

Unity 2019.x + .net 4.x + IL2CPP / PC and Android

**Comment by davoodkharmanzar** [comment]
hello,
anybody there?

**Comment by davoodkharmanzar** [comment]
ok ... i changed my code and now something was happend ... the phoneauth was tried to sending the code ... but i got verification failed everytime :[
also i tried with an predefined test phone number on console and its working ... but on other phone numbers i got verification failed.
any solution?

**Comment by davoodkharmanzar** [comment]
well i tried to adding fingerprint based on keystore:
![2](https://user-images.githubusercontent.com/10723167/69951320-e0193b80-14a9-11ea-91ae-1852c344752a.PNG)

![1](https://user-images.githubusercontent.com/10723167/69951334-e7404980-14a9-11ea-958e-aaaff0b3ad52.PNG)

so, is that right?

**Comment by chkuang-g** [comment]
Hi @davoodkharmanzar 

Did you enable Phone Number as Sign-in Method?
https://firebase.google.com/docs/auth/unity/phone-auth

Also, are you able to reproduce the same issue with the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) project?

You can see this for more information about what you need to setup.
https://github.com/firebase/quickstart-unity/tree/master/auth/testapp#android

And this about how to use the API.
https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs#L550

**Comment by davoodkharmanzar** [comment]
@chkuang-g ,
hello and thanks for your reply :]

Answers:
1- Yes
2- Don't test it yet!
3- i Followed them
4- my codes are based on this.

and i'll double check again and send reports :]

**Comment by davoodkharmanzar** [comment]
ok ... i tried Auth and DataBase packages as separate projects and getting AAR and JAR dependencies ...
than merge them together ... [seems that some of dependencies of them are different]

and got these gradle build errors:

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class androidx.annotation.AnimRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.AnimatorRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.AnyRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.AnyThread found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.ArrayRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.AttrRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.BinderThread found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.BoolRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.CallSuper found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.CheckResult found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.ColorInt found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.ColorLong found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.ColorRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.DimenRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.Dimension found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.DrawableRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.FloatRange found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.FontRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.FractionRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.GuardedBy found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.HalfFloat found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.IdRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.IntDef found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.IntRange found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.IntegerRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.InterpolatorRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.Keep found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.LayoutRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.LongDef found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.MainThread found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.MenuRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.NavigationRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.NonNull found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.Nullable found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.PluralsRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.Px found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RawRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RequiresApi found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RequiresFeature found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RequiresPermission found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RequiresPermission$Read found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RequiresPermission$Write found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RestrictTo found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.RestrictTo$Scope found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.Size found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.StringDef found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.StringRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.StyleRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.StyleableRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.TransitionRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.UiThread found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.VisibleForTesting found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.WorkerThread found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)
  Duplicate class androidx.annotation.XmlRes found in modules androidx.annotation.annotation-1.0.0.jar (androidx.annotation.annotation-1.0.0.jar) and androidx.annotation.annotation-1.1.0.jar (androidx.annotation.annotation-1.1.0.jar)

**Comment by chkuang-g** [comment]
@davoodkharmanzar 
This is pretty bad idea to merge two projects.  We have a tool call Android Resolver to resolve dependencies for such kind of situation.
And these errors just means that you have duplicated AndroidX libraries due to the merge.

Could you provide some log (adb logcat) from Android device when PhoneAuth failed?
Shawn

**Comment by davoodkharmanzar** [comment]
@chkuang-g 
thanks for your reply :]

tha phone auth is solved woth SDK 6.8 on unity 2020.1.0a15 !!

but i have another problem ... now the database can't read on android!
everything are working good on Editor an PC Standalone!!

and does Anonymous auth working completely on Android?

**Comment by chkuang-g** [comment]
@davoodkharmanzar 

Could you include some log from Android (adb logcat) when it failed to access database?

You can also enable verbose logging to debug why you cannot access the database. (You can turn both of the following to verbose)
https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#loglevel
https://firebase.google.com/docs/reference/unity/class/firebase/database/firebase-database#loglevel

Also, could you verify if your security rule is setup correctly?

**Comment by davoodkharmanzar** [comment]
@chkuang-g 

ok ... i found my problem!

start coroutine does not working on android [IL2CPP] ...

i mean like this:
Account.SignInAnonymouslyAsync().ContinueWithOnMainThread(task => { if (task.Result.Metadata != null) StartCoroutine(Register(task.Result)); });

so, any suggestion?

**Comment by davoodkharmanzar** [comment]
ok ... solved :]
