### ISSUE TITLE
Java class com/google/firebase/FirebaseFunctions not found. Please verify the AAR which contains the com/google/firebase/FirebaseFunctions class is included in your app.

### ISSUE THREAD

**Issue by vnminh1999** [firebase/quickstart-unity#526]
### Please fill in the following fields:
Unity editor version: 2019.2.8f1
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Functions
Additional SDKs you are using (Facebook, AdMob, etc.): Mapbox
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
Hello. I'm currently working on a Unity game making use of Firebase's cloud functions. I'm trying to have the game call some https.onCall functions that have been deployed, which requires using Firebase.Functions. Building the game works, however when I try running it, it crashes. I've been able to identify from logcat it crashes when I try to get FirebaseFunctions.DefaultInstance, and the logcat says that that "Java class com/google/firebase/FirebaseFunctions not found. Please verify the AAR which contains the com/google/firebase/FirebaseFunctions class is included in your app."

I looked into the Assets/Plugins/Android folder, and noticed that there isn't an .aar file for FirebaseFunctions. Running Play Services Resolver doesn't seem to help as it wipes all .aar and .jar files, however in mainTemplate.gradle, it does add FirebaseFunctions as a dependency.

Any ways I could fix this or get the aar file that contains Firebase Functions?

Thank you!

**Comment by chkuang-g** [comment]
Hi @vnminh1999 

Did you try to force resolve with Android Resolver?
  Asset > Play Services Resolver > Android Resolver > Force Resolve

And could you check Android resolver setting and see if Auto-Resolution is turned off?
  Asset > Play Services Resolver > Android Resolver > Settings

If these still does not help, could you let us know if you can reproduce with [quickstart](https://github.com/firebase/quickstart-unity/tree/master/functions/testapp) project?

Shawn
