### ISSUE TITLE
Error: Could not load signature of Firebase.Crashlytics.Editor.iOSPostBuild:GetMainUnityProjectTargetGuid

### ISSUE THREAD

**Issue by michael-spb-gor** [firebase/quickstart-unity#529]
### Please fill in the following fields:
Unity editor version: **2019.3.0f1** 
Firebase Unity SDK version: **6.7.0**
Firebase plugins in use (Auth, Database, etc.): **Firebase Crashlytics**
Additional SDKs you are using (Facebook, AdMob, etc.): No
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows 10**
Platform you are targeting (iOS, Android, and/or desktop): **Android**
Scripting Runtime (Mono, and/or IL2CPP): Both

### Please describe the issue here:
**Error:** Could not load signature of Firebase.Crashlytics.Editor.iOSPostBuild:GetMainUnityProjectTargetGuid due to: Could not load file or assembly 'UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:UnityEditor.iOS.Extensions.Xcode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
**Error:** Unloading broken assembly Assets/Firebase/Editor/Firebase.Crashlytics.Editor.dll, this assembly can cause crashes in the runtime

Steps to reproduce :
On Windows 10, install Unity 2019.3 for Windows with Android Build Support (AndroidSDK+OpenJDK)
Create empty 2D project 
Download and unzip Firebase SDK 6.7.0
Import package FirebaseAnalytics.unitypackage - All Ok
Import package FirebaseCrashlytics.unitypackage - Error Occure immediately
Targeting : Android ( Standalone/Windows as well )

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
On Empty Project with Firebase Analytics and Crashlytics

What's the issue repro rate? 
Reproduce rate 100%

Hello, Firebase Team !

Thank You for great products ! 
Now I catch stable error on Unity for Windows ( Firebase SDK 6.7.0 ) and there is no workaround found after googling.

Same issue also occure on 2019.2.7f2 (Firebase SDK 6.7.0) if import Firebase Crashlitics over Analitycs, RemoteConfig. 
Without Crashlitics project with Firebase Analitycs, Firebase Remote Configs work very well.

Best regards,
Michael

**Comment by stewartmiles** [comment]
This is a bug in the Crashlytics Unity editor plugin, we have a fix lined up internally.  The workaround is to install the Unity iOS extension which will resolve the missing type and allow the DLL to load.

**Comment by michael-spb-gor** [comment]
Thank you! 

Also this bug seems don't break build process. And after build for Android, in runtime Crashlytics can sent reports on exception.  
The error message can be removed if run PlayServiceResolver->AndroidResolver->ForceResolve ( untill next auto dependency resolve )

**Comment by patm1987** [comment]
This should be fixed as of version [6.8.1](https://firebase.google.com/support/release-notes/unity#version_681_-_december_16_2019). Feel free to re-open if you still experience this error!

--Patrick
