### ISSUE TITLE
Firebase auto-auth strange crash

### ISSUE THREAD

**Issue by craNich** [firebase/quickstart-unity#531]
Unity editor version:2019.1.9f1
Firebase Unity SDK version: 6.5.0
Firebase plugins in use (Auth, Database, etc.): FirebaseAnalytics, Auth, Database, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Mapbox
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS

Crashlytics:
Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000061
Build fingerprint: 'HONOR/HRY-LX1/HWHRY-H:9/HONORHRY-L21/280C432:user/release-keys'
Revision: '0'
pid: 21869, tid: 22033, name: Thread Pool Wor  >>> com.xxx.xx <<<
    r0 cadb8010  r1 b9559b90  r2 ffffffff  r3 00000041
    r4 b9559b90  r5 b9559b90  r6 bf16e290  r7 cc2bd388
    r8 cc2bd55c  r9 c06c9a34  sl c8df6f44  fp c06c98d0
    ip 00000001  sp c06c9800  lr bf536e70  pc cb658c9c  cpsr 00005611

       at libunity.005cdc9c()
       at libunity.005d0744()
       at libunity.00b0dc34()
       at libunity.004aa5c4()
       at libunity.004aa4f8()
       at libunity.004aae60()
       at libunity.004ab15c()
       at libunity.006efbbc()
       at Unknown.000064ac()

Code:     

```
async void AuthStateChanged(object sender, System.EventArgs eventArgs)
    {
        if (auth.CurrentUser != user)
        {
            bool signedIn = user != auth.CurrentUser && auth.CurrentUser != null;

            if (!signedIn && user != null)
            {
                Debug.Log("User relogged.");
            }

            user = auth.CurrentUser;
            if (signedIn)
            {
                Debug.Log("User signed in. Email:" + user.Email);
                // await new WaitForEndOfFrame();
                ApplicationInitManager.Instance.LoadAndInitializeData(auth.CurrentUser.UserId);
            }
        }
    }

```

Hello. Very strange bug/crash lately started to happen to me, which never happens on the first run of app. I debugged it a lot and what I found out is very weird: 
After the user is auto-authenticated, the LoadAndIntializeData functions is called. I deleted almost everything, so the functions just activates a canvas, where is just text (TextMeshPro) and image. I found that app crashs because of the TextMeshPro. When I remove it from the canvas, app running just fine, no crashes. Another solution is just to put some await before the activating canvas or the whole function (wait for endofframe is enough).
Happens on my Android - Honor 10 lite. (via editor no crashes)

Is there any logical solution to this?

**Comment by cynthiajoan** [comment]
Hi @craNich, you mentioned the crash is caused by TextMeshPro and after you delete that the crash went away. What is the TextMeshPro trying to render? Can you repro the same crash with our testapp?

**Comment by craNich** [comment]
Hello. Yeah, ifI remove the TextMeshPro / or replace by standard Text / or await one frame before enabling canvas, no crash occures.

I cut the whole code, this is what I got. Game crashes in 100% examples at second+ run.
```
    void AuthStateChanged(object sender, System.EventArgs eventArgs)
    {
        if (auth.CurrentUser != user)
        {
            bool signedIn = user != auth.CurrentUser && auth.CurrentUser != null;

            if (!signedIn && user != null)
            {
                Debug.Log("User relogged.");
            }

            user = auth.CurrentUser;
            if (signedIn)
            {
                Debug.Log("User signed in. Email:" + user.Email);
                canvas.SetActive(true);
            }
        }
    }
```

Canvas (just canvas with textmeshpro text):
![test](https://user-images.githubusercontent.com/53269312/70612819-efb22600-1c07-11ea-9fc2-9b21fbcf8121.png)

**Comment by cynthiajoan** [comment]
you can try Auth Sample app follow the directions [here](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp)
