### ISSUE TITLE
Android not register in analytics

### ISSUE THREAD

**Issue by yosi1202** [firebase/quickstart-unity#532]
### Please fill in the following fields:
Unity editor version: 2019.2.11f1
Firebase Unity SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
I implemented as described in the instruction video but after building the apk and running it on my phone the activity is not shown in the Firebase analytics console, the logging in the console show that Firebase is initialised successfully 

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes

What's the issue repro rate? 100%

**Comment by cynthiajoan** [comment]
Hi @yosi1202,

In the instruction of [sample app](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp), it mentioned "After around 5 hours, data should be visible under the Analytics tab in the Firebase Console).". That's my first guess and would like to make sure you've wait enough time to let data show up in the console.

**Comment by yosi1202** [comment]
@cynthiajoan 
no its not it, I show in the project overview that the android device was active yesterday but still in the stream view it only show when the ios version is active but not the android

**Comment by yosi1202** [comment]
well sometimes randomly is show in in a delay of like 20 minutes in the stream view, still doesnt show in the analytics dashboard

**Comment by cynthiajoan** [comment]
There are the following steps that you can try to debug your issue:
1. Check the project is registered correctly with analytics. ([link](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp#android))
2. Following the [debug guide](https://firebase.google.com/docs/analytics/debugview?authuser=0) and find out if the event has been sent to Analytics service.
3. If we've verified the event is sent correctly and you still cannot see that in the console, the best way is to file a [support request](https://firebase.google.com/support/troubleshooter/analytics/help/) so our team can look into your project information to diagnose.

**Comment by yosi1202** [comment]
@cynthiajoan 
well it shows after enabling the debug, but still doesnt after disabling the debug again for now I will work with the debug

**Comment by chkuang-g** [comment]
Hi @yosi1202 

For what it worth, could you upgrade to [Firebase 6.10.0](https://firebase.google.com/download/unity) and see if this issue persists?

Seems like Android team fixed several issues in Analytics.
Firebase Unity 6.8.0 -> [Firebase Android 17.2.1](https://firebase.google.com/support/release-notes/android#analytics_v17-2-1)
Firebase Unity 6.10.0 -> [Firebase Android 17.2.2](https://firebase.google.com/support/release-notes/android#analytics_v17-2-2)

Shawn
