### ISSUE TITLE
Android native Firebase code SIGSEGV SEGV_MAPERR crashes, after updating 6.1.1 -> 6.4

### ISSUE THREAD

**Issue by tswierkot** [firebase/quickstart-unity#533]
### Please fill in the following fields:
Unity editor version: 2018.4.4
Firebase Unity SDK version: 6.4.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Crashlytics, InstanceID, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Admob, Adjust, IronSource
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
We recently started getting crashes after upgrading from Firebase 6.1.1 to 6.4.0. The crashes are the following: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
They occur both on ARM64 and ARMv7 builds, on Android versions 7/8/8.1/9. The seem to occur in native Firebase code. We get 4x as many on ARMv7 builds than on ARM64. 
Example symbolicated crash dumps:
- ARMv7, Samsung Galaxy J7 Neo (j7velte), Android 9: https://pastebin.com/raw/AVd2sLee
- ARM64, Samsung Galaxy S7 (herolte), Android 8.0: https://pastebin.com/raw/rdEa5k5s

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? 
No

What's the issue repro rate? (eg 100%, 1/5 etc)
We have not been able to reproduce this crash on our test devices. We get around 50 of these crashes a month (only a few repeated per user), with around 800 DAU.

**Comment by FrankNine** [comment]
We had similar issue and the occurrence reduced greatly by following:  
https://github.com/firebase/quickstart-unity/issues/485#issuecomment-545047855
and replace all ContinueWith calls with ContinueWithOnMainThread

**Comment by cynthiajoan** [comment]
Thanks @FrankNine providing the info. @tswierkot would you like to try with the solution?

**Comment by tswierkot** [comment]
We found one call to ContinueWith, chained with FixDependenciesAsync. We replaced that with a continuation on the main thread (using the Firebase extension method). However, we think it's unlikely this could be the cause, as this part of the code was the same when we were using 6.1.1 and no such crashes occured.

We also updated the Firebase SDK version from 6.4 to 6.8. We're releasing a new version of the game on Monday, so we'll monitor if these changes fix the problem. I'll close this for now and open a new issue if the problem persists.

**Comment by FrankNine** [comment]
The situation is very strange for us, too. We basically copied all the Firebase code from an old project to a new project. The only difference is the old one based on Unity 2017 and new one based on 2018. We didn't replace ContinueWith with ContinueWithOnMainThread in the old project and it's totally fine. But it crashes from time to time on new project until we did the replacement.
