### ISSUE TITLE
Auth and Database custom domain?? [PC - Android]

### ISSUE THREAD

**Issue by davoodkharmanzar** [firebase/quickstart-unity#534]
hello guys,

is it possible to define custom domain [i mean BLABLABLA.com] against of Firebaseio.com for Android and PC apps that sends or gets their all of Auth or Database request to this domain?
i mean this custom domain is doing redirect of this requests to main Firebase server ...

PC / Android      <=======>      BLABLABLA.com      <===================>     Firebase

**Comment by stewartmiles** [comment]
@davoodkharmanzar nope that's not possible.
