### ISSUE TITLE
Google tag manager + fire base not working on android

### ISSUE THREAD

**Issue by yosi1202** [firebase/quickstart-unity#537]
### Please fill in the following fields:
Unity editor version: 2019.2.11f1
Firebase Unity SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.):
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
I am trying to add google tag manager with firebase in unity, I managed to make it work on ios by adding the container to the xcode project, but I cant make it work when searching it only show how to add it with firebase on native android app, no instructions for unity, I tried adding the gtm container to the 'plugins/android/firebase/res' folder but it doesn't seem to work

**Comment by yosi1202** [comment]
Any help? please?

**Comment by DellaBitta** [comment]
Hi @yosi1202,

The Google Tag Manager leverages the Firebase SDK but the Tag Manager itself is supported via the [Google Tag Manager Support Portal](https://support.google.com/tagmanager#topic=3441530) which hosts the existing installation guides. I recommend reaching out to that team.

I hope this helps!

**Comment by yosi1202** [comment]
@DellaBitta 
Unfortunately no, there is nothing there about integration with Unity, and no response when sending a massage

**Comment by stewartmiles** [comment]
@yosi1202 I'm afraid you'll need to connect with the Tag Manager team and work with them to solve the issue.

**Comment by pratikcouragedigital** [comment]
@yosi1202  hey have you solved this??
did you find something?
