### ISSUE TITLE
Firebase storage throwing error when calling PutFileAsync

### ISSUE THREAD

**Issue by bysammy** [firebase/quickstart-unity#546]
Unity editor version: 2019.3.0f3
Firebase Unity SDK version: 6.6.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Google Sign-in, Photon Pun2
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop):  Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

When trying to upload a file to Firebase storage, the application returns an error (below) when PutFileAsync is called **from any Android device**. 
The application works as intended when tested from within the editor. I tried uploading a file located on the local windows PC and it worked perfectly fine. I tried using relative paths and hard-coding the fixed location of the file on Android devices. Nothing seemed to work. 

> System.AggergateException: One or more errors occured. --->Firebase.Storage.StorageException: No content provider: /storage/emulator/0/Android/data/com.xcompany.xproduct/files/image.jpg
--- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.Storage.StorageException: No content provider: /storage/emulator/0/Android/data/com.xcompany.xproduct/files/image.jpg<---

The code is something like this:

`

         StorageReference profile_ref = storage_ref.Child("image.jpg");
         string local_file = Path.Combine(Application.persistentDataPath, "image.jpg");
        
        profile_ref.PutFileAsync(local_file).ContinueWith((Task<StorageMetadata> task) =>
        {
            if (task.IsFaulted || task.IsCanceled)
            {
             Debug.Log(task.Exception.ToString());  // This is where the Error occurs
            }
            else
            {
`

This happens always 100% on several Android devices that were tested, but works perfectly fine within the editor. 

Thank you

**Comment by bysammy** [comment]
> 
> 
> This issue does not seem to follow the issue template. Make sure you provide all the required information.

Yes it does, but you don't know, because you're a bot.

**Comment by paulinon** [comment]
Hi @bysammy Could you provide a minimal reproducible example of your project? Thanks!

**Comment by jemalpartidayump** [comment]
@bysammy , you need add "file://". You can use Uri.UriSchemeFile.
For example:
~~~
string local_file = Path.Combine(Application.persistentDataPath, "image.jpg");
string local_file_uri = string.Format("{0}://{1}". Uri.UriSchemeFile, local_file);
profile_ref.PutFileAsync(local_file_uri).ContinueWith((_task)=>{....});
~~~
This works for me in Unity Editor and in Android device.

**Comment by bysammy** [comment]
> 
> 
> @bysammy , you need add "file://". You can use Uri.UriSchemeFile.
> For example:
> 
> ```
> string local_file = Path.Combine(Application.persistentDataPath, "image.jpg");
> string local_file_uri = string.Format("{0}://{1}". Uri.UriSchemeFile, local_file);
> profile_ref.PutFileAsync(local_file_uri).ContinueWith((_task)=>{....});
> ```
> 
> This works for me in Unity Editor and in Android device.

Works like a charm, thanks!
