### ISSUE TITLE
FirebaseCppApp-6_9_0.so filesize slighlty too big for github

### ISSUE THREAD

**Issue by walaoRIKI** [firebase/quickstart-unity#547]
### Please fill in the following fields:
Unity editor version:  2019.1.14f1
Firebase Unity SDK version: 6.9.0
Firebase plugins in use (Auth, Database, etc.): Auth, Cloud Functions, Realtime Database, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
FirebaseCppApp-6_9_0.so file size slightly too big for GitHub. Current Github file size limit is 100mb, but the file size 104mb

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by cometa93** [comment]
Shit... got the same problem, can't update firebase because we are using GitHub to store the project, CppApp.so file is way to big!

**Comment by Zarkend** [comment]
Same here ;(

**Comment by walaoRIKI** [comment]
> Same here ;(



> Shit... got the same problem, can't update firebase because we are using GitHub to store the project, CppApp.so file is way to big!

Hi guys, I do have solution for now is that I gitignore the so and meta file, then export it as unitypackage and distribute among the programmer

**Comment by cometa93** [comment]
We did enable LFS support for entire project, but still it's not a good option. If someone do not have premium account it will not be able to continue development with githbub or firebase.

**Comment by Estellise-Esuteriize** [comment]
Got the same problem also.

Forgive me for asking but is the FirebaseCppApp.so needed if I'm only using the firebase database and nothing else?.

**Comment by stewartmiles** [comment]
`FirebaseCppApp.so` is Firebase's C++ implementation for all components on Linux desktop.  If you're not running the editor on Linux or compiling for Linux, you can remove it to workaround the issue.

**Comment by phobos2077** [comment]
@stewartmiles I also have the same issue and I've removed this file, but even though I'm on Windows desktop I still see errors in console about missing `so` file. I had to add ifdefs to skip any firebase-related runtime code from compilation in editor to avoid errors when playing in editor.

**Comment by LukePenkava** [comment]
> `FirebaseCppApp.so` is Firebase's C++ implementation for all components on Linux desktop. If you're not running the editor on Linux or compiling for Linux, you can remove it to workaround the issue.

Worked on Mac just fine. Thanks

**Comment by zaneclaes** [comment]
I ran into this problem because I *am* building to target Linux x86_64. I tried using `git lfs track`, but for some reason when my build machines check out the code the filesize of the `.so` is tiny:
```
ls -la Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.so
-rwxr-xr-x 1 buildkite-agent buildkite-agent 134 Feb  2 11:11 Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.so
```

This results in a successful Unity build but an application which cannot actually start:
```
Plugins: Couldn't open /usr/local/bin/cardgrid_Data/Plugins/FirebaseCppApp-6_10_0.so, error: /usr/local/bin/cardgrid_Data/Plugins/FirebaseCppApp-6_10_0.so: invalid ELF header 
(Filename:  Line: 306)
```

AFAICT, the only way to build for Linux right now is to downgrade Firebase to before the filesize grew (or perhaps automate the package installation itself on the build agents instead of committing the binaries).

**Comment by stopiccot** [comment]
I think it's good idea to have firebase unitypackage with only iOS/Android dependencies for mobile devs

**Comment by exzizt** [comment]
> I think it's good idea to have firebase unitypackage with only iOS/Android dependencies for mobile devs

I agree 100%! @stewartmiles Is anything like this in the works? 😄

**Comment by dennis-gonzales** [comment]
> `FirebaseCppApp.so` is Firebase's C++ implementation for all components on Linux desktop. If you're not running the editor on Linux or compiling for Linux, you can remove it to workaround the issue.

Does removing this will give us any problem later on?
For me, i'm only going to build this using Android/IOS.

**Comment by wilczarzgit** [comment]
I am getting this error too (240MB!)
`FirebaseCppApp-6_14_0.so is 242.71 MB; this exceeds GitHub's file size limit of 100.00 MB`
If I'm on Mac abd building for iOS / Android, am I safe to delete this file too?

**Comment by DioNNiS** [comment]
+1

**Comment by SameelNawaz** [comment]
+1

**Comment by drallcom3** [comment]
Half a year later and the file is now 200mb in size... still too large for Git.

**Comment by stopiccot** [comment]
That's how they force us to migrate to UPM Firebase installation

**Comment by phobos2077** [comment]
@stopiccot  I'm planning to migrate to UPM installation in future. But the other option is to use git lfs :)

**Comment by chkuang-g** [comment]
Hi folks,

You should be able to install Firebase through UPM now (and it is FUN!)
In this case, you can just checkin `Packages/manifest.json`

Instructions
https://firebase.google.com/docs/unity/setup#add-sdks-upm
Known Issues
https://firebase.google.com/docs/unity/setup#known-issues
