### ISSUE TITLE
No Data on dashboard for Unity Android

### ISSUE THREAD

**Issue by Ansh2020** [firebase/quickstart-unity#549]
Unity editor version: 2017.4.21f1
Firebase Unity SDK version: 5.5.0
Firebase plugins in use : Analytics, Messaging
Additional SDKs you are using : Facebook, Singular, Google play services 0.9.64
Platform you are using the Unity editor on : Mac OS Mojave
Platform you are targeting : Android, iOS
Scripting Runtime : Mono and IL2CPP

I used Firebase SDK for messaging and analytics and implemented as described in the documentations. For iOS, everything is working fine, I am able to see custom events on dashboard. But for Android platform, Firebase console is not registering any data. 
 
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No, Using sample app, I am able to get events on firebase dashboard for androids.

**Comment by paulinon** [comment]
Hi @Ansh2020 It appears that you're using an old SDK version. Could you try using the latest version and see if the issue persists? Otherwise, please send a runnable example so I could identify why this issue occurs. Thanks!

**Comment by Ansh2020** [comment]
> Hi @Ansh2020 It appears that you're using an old SDK version. Could you try using the latest version and see if the issue persists? Otherwise, please send a runnable example so I could identify why this issue occurs. Thanks!

Hi paulinon,

I update the SDK versions as follow:
Firebase Unity SDK v6.9.0
Google Play Services v0.10.06
Facebook Unity SDK v7.16.1
Jar Resolver v1.2.135

But the issue persists. Google login working fine, Facebook functionalities working fine. Firebase Analytics and messaging working fine on iOS. On Android, No data on Firebase dashboard. 

Create a blank Unity project and integrate all above plugins, everything is working fine.

Please find attached the verbose log file.
[Log.txt](https://github.com/firebase/quickstart-unity/files/4064216/Log.txt)

Please suggest how to debug this issue because I can not share a runnable example as everything is working fine in blank project.

**Comment by paulinon** [comment]
Hi @Ansh2020 there could be an issue with your google-services.json file which prevents Firebase functionality from working on Android builds. Ensure that you have placed the correct file in your Assets folder and the filename remains to be "google-services.json".

Also, note that it may take up to 24 hours for the events to appear on the dashboard. Alternatively, you can use the DebugView which enables you to see the raw event data logged by your app on development devices in near real-time.
