### ISSUE TITLE
Firebase.Messaging.FirebaseMessaging.Unsubscribe()

### ISSUE THREAD

**Issue by k1151204** [firebase/quickstart-unity#55]
Hello.
Thank you very much for your help.
I was using FCM without any problems.
The message is received well.
Here I want to unsubscribe from the message using the Unsubscribe () function.
I used topic for Unsubscribe (topic) just like subscribe (topic) when receiving.
You will still receive messages.
Is there a way to use the Unsubscribe () function?
Answers I'll wait.

![21344](https://cloud.githubusercontent.com/assets/16028998/22550740/d505938a-e994-11e6-8e5b-fe89655e87dd.PNG)

**Comment by k1151204** [comment]
There is one more question.
Can I use the specified icon instead of App_icon when receiving a message?

**Comment by stewartmiles** [comment]
Hi what platform are you targeting where you're having problems unsubscribing?  Are you able to reproduce the problem in the sample application?

To change the icon see
http://stackoverflow.com/questions/37325051/notification-icon-with-the-new-firebase-cloud-messaging-system
https://firebase.google.com/docs/cloud-messaging/android/client#manifest

you can set the "com.google.firebase.messaging.default_notification_icon" and "com.google.firebase.messaging.default_notification_color" metadata values to customize the icon.

**Comment by stewartmiles** [comment]
Assuming you guys figured this out after my last comment, please reopen if you still have issues.

**Comment by liseylee** [comment]
I got this problem in iOS. When user logout to unsubscribe topic like that 
`[[FIRMessaging messaging] unsubscribeFromTopic:@"new"]`
but it doesn't work. I also got the topic message.
