### ISSUE TITLE
Assembly.GetTypes fails on Firebase.Editor assembly when iOS build support is not installed

### ISSUE THREAD

**Issue by phobos2077** [firebase/quickstart-unity#550]
### Please fill in the following fields:
Unity editor version: **2019.2.14f1, 2019.2.17f1**
Firebase Unity SDK version: **6.8.1**
Firebase plugins in use (Auth, Database, etc.): **Crashlytics**
Additional SDKs you are using (Facebook, AdMob, etc.): -
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows**
Platform you are targeting (iOS, Android, and/or desktop): **Desktop**
Scripting Runtime (Mono, and/or IL2CPP): **Mono**

### Please describe the issue here:
When any code in project attempts to call `Assembly.GetTypes` the `ReflectionTypeLoadException` is thrown.

How to reproduce.

- Create empty project
- Open in Unity 2019.2.17f1 w/o either iOS or Android build support
- Import Crashlytics SDK 6.8.1
- Open Package Manager and install packages "Terrain Tools" preview 2.0.2 and "Memory Profiler" 0.1.0 preview.9 (you have to click "Advanced - Show preview packages" so they show up in the list)
- Close and reopen the project.

You should see these errors in console:
```
NoiseLib::GatherNoiseTypes: Failed to get types from assembly: Firebase.Editor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at C:/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:108)
```

Another example:
```
ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetTypes () (at <567df3e0919241ba98db88bec4c6696f>:0)
Unity.MemoryProfiler.ReflectionUtility.GetTypesImplementingInterfaceFromCurrentDomain (System.Type baseType) (at Library/PackageCache/com.unity.memoryprofiler@0.1.0-preview.9/Runtime/Utilities/ReflectionUtility.cs:17)
Unity.MemoryProfiler.MetadataInjector.InitializeMetadataCollection () (at Library/PackageCache/com.unity.memoryprofiler@0.1.0-preview.9/Runtime/MetadataInjector.cs:34)
Unity.MemoryProfiler.MetadataInjector.EditorInitMetadata () (at Library/PackageCache/com.unity.memoryprofiler@0.1.0-preview.9/Runtime/MetadataInjector.cs:20)
```

I want to stress that this issue does not appear to be related to those two packages specifically. But more to the way Unity loads assemblies and any attempt to call `Assembly.GetTypes` on *Firebase.Editor* assembly.

This issue does not appear if I open the same project in a version of Unity with iOS and Android build support modules installed.

My guess is that Firebase.Editor assembly is somehow linked to platform-specific DLLs in plugin folder and it tries to load them even when it shouldn't (Standalone platform is selected).

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
- *Yes*

What's the issue repro rate?
 - **100%**

**Comment by phobos2077** [comment]
ILSPY shows that *Firebase.Editor.dll* has a reference to *UnityEditor.iOS.Extensions.Xcode.dll* which is a part of iOS support module. This really looks like a bug, because:

1. There is no mention about iOS build support requirement in the documentation: https://firebase.google.com/docs/crashlytics/get-started?platform=unity
2. Unity project != iOS project. Some projects don't have iOS versions (only Android) and many developers who would be required to install redundant iOS support module every time Unity version is updated in the project.

This issue blocks us from integrating Firebase SDK because it's an Android project.

**Comment by stewartmiles** [comment]
@phobos2077 we have a patch lined up that removes the reference to UnityEditor.iOS.Extensions.Xcode.dll from Firebase.Editor.dll.  In the meantime you can workaround the issue by installing iOS support in Unity.

**Comment by phobos2077** [comment]
@stewartmiles thank you for a timely reply! Would you be so kind to give a hint when can we expect this patch?

**Comment by phobos2077** [comment]
Any update on this? Other SDK's seem to have been updated in January, but Unity SDK is still old.

**Comment by phobos2077** [comment]
@stewartmiles I've just installed a recent SDK 6.10.0 and the issue is still there! The DLL reference that causes the issue still exists. What was that patch you mentioned that was supposed to resolve this?

**Comment by stewartmiles** [comment]
I just tried this out with 6.12.0 without iOS build support installed and it works.
https://firebase.google.com/support/release-notes/unity#version_6120_-_march_5_2020

You could try 6.12.0 ?

**Comment by phobos2077** [comment]
I ended up hacking the DLL and removing iOS DLL reference manually. I will give this another look when updating to the latest Firebase version later.

**Comment by DellaBitta** [comment]
Hi @phobos2077,

Any updates here?  Thanks!

**Comment by bradzoob** [comment]
I don't know if this is any help at all but I don't have Terrain Tools installed, i'm targetting Windows only (standalone) and my only overlap is i have MemoryProfiler enabled and this has started showing up for me but I don't know why.

ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
System.Reflection.Assembly.GetTypes () (at <7d97106330684add86d080ecf65bfe69>:0)
Unity.MemoryProfiler.ReflectionUtility.GetTypesImplementingInterfaceFromCurrentDomain (System.Type baseType) (at Library/PackageCache/com.unity.memoryprofiler@0.2.0-preview.1/Runtime/Utilities/ReflectionUtility.cs:17)
Unity.MemoryProfiler.MetadataInjector.InitializeMetadataCollection () (at Library/PackageCache/com.unity.memoryprofiler@0.2.0-preview.1/Runtime/MetadataInjector.cs:34)
Unity.MemoryProfiler.MetadataInjector.EditorInitMetadata () (at Library/PackageCache/com.unity.memoryprofiler@0.2.0-preview.1/Runtime/MetadataInjector.cs:20)

Removing MemoryProfiler removes the emitted error for me in Unity 2019.1.14f1.
