### ISSUE TITLE
Receive Firebase Short Dynamic Link in DynamicLinkReceived callback event

### ISSUE THREAD

**Issue by Russel1** [firebase/quickstart-unity#552]
I would like to use **Firebase Dynamic Links** so users can invite friends and be rewarded with.
Each user gets a different Short Dynamic Link in the form of **https://test.page.link/abcd**
The user can share this Short DynamicLink with friends.

When the invited friend comes into the app, this callback is called.

    private void OnDynamicLink(object sender, EventArgs args) {
    		var dynamicLinkEventArgs = args as ReceivedDynamicLinkEventArgs;
    		Debug.LogFormat("Received dynamic link {0}",
    						dynamicLinkEventArgs.ReceivedDynamicLink.Url.OriginalString);
    	}

Unfortunately, I only get back the base link that was necessary to create the short dynamic link.

> Received dynamic link https://www.example.com/referral?xxxxxxxxxx

I get an additional native output with my iOS app

> IOSNative::Native->Unity callback data:
> {"m_EventName":"continueUserActivity","m_Data":"https://test.page.link/?link=https://www.example.com/referral?xxxxxxxxxx&apn=de.test.testapp&isi=123456789&ibi=de.test.testapp&cid=1579347010984123886&_osl=https://test.page.link/abcd&_fpb=AB6327276CFGHT==&_cpt=cpit&_iumenbl=1&_iumchkactval=1&_plt=2076&_uit=2692&_cpb=1"}
> 2020-01-14 15:30:20.455009+0100 ambassador[315:8406]
> IOSNative::Native->Unity callback data:
> {"m_EventName":"applicationDidBecomeActive","m_Data":""}

**Now my question is how do I get the generated short dynamic link that I have shared with a friend in this callback? I need the value behind the parameter "&_osl" as seen in additional native output. But I only get the Base Url back in Unity.**

**Comment by jonsimantov** [comment]
Dynamic Links only gives you the URL that the dynamic link points to, not the short link (or long link) that the user clicked on. If you want to identify the user who sent the link, I'd recommend including some identifier in the destination URL (e.g. in the referral?xxxxxxxxxx part you mentioned above) before generating the short link. That way, when the link is clicked on by someone else, you can use that to identify who sent the link to the person who clicked it.
