### ISSUE TITLE
Could you please provide gitignore that would be fit for unity that use firebase?

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#554]
I'm not so sure but it seem like some file and folder come from resolver and so it should excluded from git, but then I haven't seen (if there is) any official verdict about what should be ignore and whatnot. Some is confused such as `m2repository`

Can you please add default `.gitignore` it into this repo?

**Comment by paulinon** [comment]
Hi @Thaina You'd want to include files such as autogenerated files, cache directories, and builds in your gitignore. You may refer to the guide [here](https://github.com/github/gitignore/blob/master/Unity.gitignore).

**Comment by Thaina** [comment]
@paulinon My point is, currently now firebase and some other library relate to android also made some auto generated file more than the base ignore that guide provided. I don't know which could be ignore and which auto generated but still require anyway

I think if firebase library know which file are auto generated by itself, firebase repo should list that so we could extend the `gitignore` file too

**Comment by paulinon** [comment]
Thanks for the clarification. I've filed an internal feature request regarding this. I'm not able to provide any timelines for this, so I'll leave this open.

**Comment by Thaina** [comment]
@paulinon As of now I wish to know first, should we ignore crashlytics build id and version xml file?

**Comment by p0w1nd** [comment]
> @paulinon As of now I wish to know first, should we ignore crashlytics build id and version xml file? Also can we ignore `aar` and other file in `m2repository` ?

I'm having the same question.

**Comment by josewweee** [comment]
any solution?

**Comment by chkuang-g** [comment]
If you are using the latest version of Firebase (6.15.2 for example), here are a list of file you can ignore in Assets folder
```
# This may be different if it is changed in Android Resolver settings
Assets/GeneratedLocalRepo/

Assets/StreamingAssets/google-services-desktop.json
Assets/Plugin/Android/Firebase/

# Use the following one ONLY IF all aar files here are generated by Android Resolver.  Note that some Unity plugins does import libraries under this folder
# Assets/Plugin/Android/*.aar
```

Please do not ignore `Assets/Firebase/m2repository`

Hope this answer the question!

**Comment by p0w1nd** [comment]
Thanks @chkuang-g 

> If you are using the latest version of Firebase (6.15.2 for example), here are a list of file you can ignore in Assets folder
> 
> ```
> # This may be different if it is changed in Android Resolver settings
> Assets/GeneratedLocalRepo/
> 
> Assets/StreamingAssets/google-services-desktop.json
> Assets/Plugin/Android/Firebase/
> 
> # Use the following one ONLY IF all aar files here are generated by Android Resolver.  Note that some Unity plugins does import libraries under this folder
> # Assets/Plugin/Android/*.aar
> ```
> 
> Please do not ignore `Assets/Firebase/m2repository`
> 
> Hope this answer the question!

I think `Assets/Plugin/` should be `Assets/Plugins/`

**Comment by chkuang-g** [comment]
My bad.  Edited :)
