### ISSUE TITLE
Unable to find FirebaseCppApp-6_9_0

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#559]
### Please fill in the following fields:
Unity editor version: 
Firebase Unity SDK version: 6_9_0
Unity version 2019.2.18f1
Firebase plugins in use (Auth, Database, etc.):Auth, Database, Functions, messaging, analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook,admob,native_plugins,voxelbusters_utility_lib
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP ARMv7 ARM64

### Please describe the issue here:

This issue keeps getting opened and closed here but no proper solution was found. (issues: #514 , #466 , #398 , #403 )

Here is my mainTemplate.gradle.  When building to Android it compiles with no errors and runs on the device, but with the error Unable to find FirebaseCppApp-6_9_0 on runtime on android.  The file exists on   Assets/Firebase/plugins/x86_64 . I noticed that there's no "implementation" for firebase on the gradle file:

### mainTemplate.gradle 

     buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    **BUILD_SCRIPT_DEPS**}
    }

    allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
    }

    // Android Resolver Repos Start
    ([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = "file:///" + file(rootProject.projectDir.path + "/../../").absolutePath
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/Firebase/m2repository") //     
     Assets/Firebase/Editor/MessagingDependencies.xml:22,     
     Assets/GoogleMobileAds/Firebase/Editor/AnalyticsDependencies.xml:20,     
     Assets/GoogleMobileAds/Firebase/Editor/AppDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/AuthDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/DatabaseDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/FunctionsDependencies.xml:22
        }
        maven {
            url "https://maven.google.com/" //     
     Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
    }
     // Android Resolver Repos End
       apply plugin: 'com.android.application'
      **APPLY_PLUGINS**

    dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:multidex:1.0.3'
    // Android Resolver Dependencies Start
    implementation 'com.android.support:appcompat-v7:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:cardview-v7:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:customtabs:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:exifinterface:27.1+' // Assets/Standard 
    Assets/VoxelBusters/NativePlugins/Editor/CPNPDependencies.xml:8
    implementation 'com.android.support:support-v4:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:support-v4:27.1+' // Assets/Standard Assets/VoxelBusters/NativePlugins/Editor/CPNPDependencies.xml:6
    implementation 'com.google.android.gms:play-services-ads:17.2.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.auto.value:auto-value-annotations:1.6.3' // Assets/GoogleMobileAds/Firebase/Editor/AppDependencies.xml:22

   
   
    // Android Resolver Dependencies End
    **DEPS**}

    // Android Resolver Exclusions Start
    android {
     packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
      }
    }
    // Android Resolver Exclusions End
    android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
      multiDexEnabled true
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
    }**SIGN**

    buildTypes {
        debug {
            minifyEnabled **MINIFY_DEBUG**
            useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD**
            jniDebuggable true
        }
        release {
            minifyEnabled **MINIFY_RELEASE**
            useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD****SIGNCONFIG**
        }
    }**PACKAGING_OPTIONS****SPLITS**
    **BUILT_APK_LOCATION**
    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
    }**SPLITS_VERSION_CODE****REPOSITORIES****SOURCE_BUILD_SETUP**

**Next, I try to use Android resolver (1.2.133) - force resolve,  all firebase implementation lines are being added to the main gradle file ( not sure if correct because it seems like there are some duplicates (attached the "forced" main gradle file-**. Anyway, after force I no longer can build to android, I get the error-
 Error while generating the main dex list
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
* What went wrong:
Execution failed for task ':transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

### Here is my mainTemplate.gradle (after force resolve)

    buildscript {
    repositories {
        google()
        jcenter()
    }

     dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    **BUILD_SCRIPT_DEPS**}
    }

    allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
      }
    }

    // Android Resolver Repos Start
    ([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
    }
    ([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/Firebase/m2repository") //     
    Assets/Firebase/Editor/MessagingDependencies.xml:20, 
    Assets/Firebase/Editor/StorageDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/AnalyticsDependencies.xml:18, 
    Assets/GoogleMobileAds/Firebase/Editor/AppDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/AuthDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/DatabaseDependencies.xml:20, 
    Assets/GoogleMobileAds/Firebase/Editor/FunctionsDependencies.xml:20
        }
        maven {
            url "https://maven.google.com/" // 
    Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
    }
    // Android Resolver Repos End
    apply plugin: 'com.android.application'
    **APPLY_PLUGINS**

    dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:multidex:1.0.3'
    // Android Resolver Dependencies Start
    implementation 'com.android.support:appcompat-v7:25.3.1' //     
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:cardview-v7:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:customtabs:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:exifinterface:27.1+' // Assets/Standard 
    Assets/VoxelBusters/NativePlugins/Editor/CPNPDependencies.xml:8
    implementation 'com.android.support:support-v4:25.3.1' // 
    Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:support-v4:27.1+' // Assets/Standard 
    Assets/VoxelBusters/NativePlugins/Editor/CPNPDependencies.xml:6
    implementation 'com.facebook.android:facebook-applinks:[5,6)' // 
    Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:6
    implementation 'com.facebook.android:facebook-core:[5,6)' // 
    Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:5
    implementation 'com.facebook.android:facebook-login:[5,6)' // 
    Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:7
    implementation 'com.facebook.android:facebook-share:[5,6)' // 
    Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads:17.2.0' // 
    Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.firebase:firebase-analytics:17.2.1' // 
    Assets/GoogleMobileAds/Firebase/Editor/FunctionsDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:6.9.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:6.9.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/AppDependencies.xml:20
    implementation 'com.google.firebase:firebase-auth:19.2.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:6.9.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:19.3.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-database:19.2.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/DatabaseDependencies.xml:13
    implementation 'com.google.firebase:firebase-database-unity:6.9.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/DatabaseDependencies.xml:20
    implementation 'com.google.firebase:firebase-functions:19.0.1' // 
    Assets/GoogleMobileAds/Firebase/Editor/FunctionsDependencies.xml:13
    implementation 'com.google.firebase:firebase-functions-unity:6.9.0' // 
    Assets/GoogleMobileAds/Firebase/Editor/FunctionsDependencies.xml:20
    implementation 'com.google.firebase:firebase-messaging:20.1.0' // 
    Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:6.9.0' // 
    Assets/Firebase/Editor/MessagingDependencies.xml:20
    implementation 'com.google.firebase:firebase-storage:19.1.0' // 
    Assets/Firebase/Editor/StorageDependencies.xml:13
    implementation 'com.google.firebase:firebase-storage-unity:6.9.0' // 
    Assets/Firebase/Editor/StorageDependencies.xml:20
    implementation 'com.parse.bolts:bolts-android:1.4.0' // 
    Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:4
     // Android Resolver Dependencies End
      **DEPS**}

    // Android Resolver Exclusions Start
    android {
    packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
      }
    }
    // Android Resolver Exclusions End
    android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        applicationId '**APPLICATIONID**'
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
    multiDexEnabled true
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**]
    }**SIGN**

    buildTypes {
        debug {
            minifyEnabled **MINIFY_DEBUG**
            useProguard **PROGUARD_DEBUG**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-    
       unity.txt'**USER_PROGUARD**
            jniDebuggable true
        }
        release {
            minifyEnabled **MINIFY_RELEASE**
            useProguard **PROGUARD_RELEASE**
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard- 
       unity.txt'**USER_PROGUARD****SIGNCONFIG**
        }
      }**PACKAGING_OPTIONS****SPLITS**
      **BUILT_APK_LOCATION**
      bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
      }
       }**SPLITS_VERSION_CODE****REPOSITORIES****SOURCE_BUILD_SETUP**

Please answer the following, if applicable:
####Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? NO

**Comment by paulinon** [comment]
Hi @shlighter thanks for reporting your issue. From the looks of your error message, it seems that the issue may come from your Unity setup. Here are some steps you can try to resolve this:

- Try Force Resolve by going to Asset > Play Services Resolver > Android Resolver > Force Resolve
- Disable "Enable Auto Resolution" under Asset > Play Services Resolver > Android Resolver > Settings
- Ensure that your JDK and SDK in your Unity Preferences are updated.

If none of these worked, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project. You can do this using Google Drive via shareable link

**Comment by shlighter** [comment]
Hey there, I disabled Enable Auto Resolution it didn't work,  force resolve just makes things worse as you can read in my first post. JDK and SDK are updated.
Though I managed to solve my issue so you can close it-
I needed to remove 3 Facebook lines from my Gradle after force resolve adding them- 
implementation 'com.facebook.android:facebook-applinks:[5,6)' // 
Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:6
implementation 'com.facebook.android:facebook-core:[5,6)' // 
Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:5
implementation 'com.facebook.android:facebook-login:[5,6)' // 
Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:7
implementation 'com.facebook.android:facebook-share:[5,6)' // 
Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:8

Facebook still seems to work fine, not sure why force resolve adding those lines but the solution is to do force resolve in order to firebase to be loaded properly and remove those specific Facebook lines
