### ISSUE TITLE
Firebase Crashlytics Unity replaces scenes asset bundles hashes

### ISSUE THREAD

**Issue by Incont** [firebase/quickstart-unity#561]
### Please fill in the following fields:
Unity editor version: 2019.2.9
Firebase Unity SDK version: 6.8.0
Firebase plugins in use (Auth, Database, etc.): Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac, Windows
Platform you are targeting (iOS, Android, and/or desktop):  iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

I added Firebase Crashlytics to my project, and got a major problem - all scenes bundles have new hashes, but the files weren't modified. It means that users will reload all scenes (900mb for my project). It is very bad user experience.
I researched the problem and found the reason.
Firebase Crashlytics Unity contains an internal class Firebase.Crashlytics.Editor.AndroidPreBuild that uses the UnityEditor.Callbacks.PostProcessScene attribute for preparing to an android build. I checked in the test project, adding and deleting the PostProcessScene attribute in code affects scenes asset bundles hashes.
You should use IPreprocessBuild.OnPreprocessBuild (for unity 2017) and IPreprocessBuildWithReport.OnPreprocessBuild (for new unity) intead of the PostProcessScene atribute.
Because this code is in a dll and I didn't find the source code, I cannot fix this problem myself. Please fix it.

**Comment by paulinon** [comment]
Sorry to hear about your issue @Incont, could you try sending a minimal, runnable example of your project so I can try and reproduce this behavior? Thanks

**Comment by Incont** [comment]
https://github.com/Incont/UnityTestApp is minimal project for building scene asset bundle.  Also, you can add firebase crashlytics unity package and test with it.

**Comment by paulinon** [comment]
I was able to reproduce your issue. An internal bug report has been filed regarding this. I'm not able to share any timelines, so I'll keep this open. Thanks!

**Comment by chkuang-g** [comment]
According to this https://github.com/googlesamples/unity-jar-resolver/issues/315
It does sounds like Unity bug.  Are you able to upgrade Unity or Firebase and see if this issue still occurs?
