### ISSUE TITLE
[Analytics Dashboard Best Practice] Best ways to see parameterized data in analytics dashboard.

### ISSUE THREAD

**Issue by sourav-paul** [firebase/quickstart-unity#562]
### Apologies if this is not the right place to ask the question. That case please direct me to it.

This is not an issue with implementation. I've been successfully using Firebase analytics for a few projects.

But I've only been using it `LogEvent("One_String_Parameter");` style.

The problem with it is it will take all 500 unique event limit. For a game having 500+ levels, it might not be much useful. And I believe it's not intended that way.

So I started trying parameterized reporting. Data are submitting properly but not I'm getting a good way to see those data in the dashboard.

What are the best ways to visualize `LogEvent("Level_Started", 16);` logs in dashboard?

**Comment by paulinon** [comment]
Hi @sourav-paul there are two ways you can visualize these logs in your dashboard:
- [Custom-parameter reporting](https://support.google.com/firebase/answer/7397304?hl=en)
- Export your data to [BigQuery](https://support.google.com/firebase/answer/6318765?hl=en) and customize your own dashboard using [Data Studio](https://support.google.com/firebase/answer/7200987?hl=en)

If you have any other questions, you may contact [Firebase Support](https://firebase.google.com/support)
