### ISSUE TITLE
IAP Not Working After Importing Firebase Crashlytics in Unity

### ISSUE THREAD

**Issue by sendy50** [firebase/quickstart-unity#563]
### Please fill in the following fields:
Unity editor version: 2019.2.8f1
Firebase Unity SDK version: 6.9.0
Firebase plugins in use (Auth, Database, etc.): Analytics, Crashlytics, Messaging 
Additional SDKs you are using (Facebook, AdMob, etc.): Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): IOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:

   

- 1. 	   Complete work IAP in my game. i was test in debug mode as well as Direct Install from play store.
- 2.     Now i want to add Firebase Crashlytics in my game for analytics.
- 3.     i was imported FirebaseAnalytics.unitypackage than test IAP run Complete.
- 4.     After i was import FirebaseCrashlytics.unitypackage than IAP not working and give a reason show below

> Unity: IAP purchasing failed: In-App Purchasing is not initialized.

[Check Stackoverflow](https://stackoverflow.com/q/59891514/5773037)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by paulinon** [comment]
Sorry to hear about your issue @sendy50 Could you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I could reproduce it on my end? Thanks
