### ISSUE TITLE
ANR's in Google Play Developer Console

### ISSUE THREAD

**Issue by Temka193** [firebase/quickstart-unity#564]
Unity editor version: 2018.4.6f1
Firebase Unity SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook SDK, Applovin SDK
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

Google Play Developer Console has a lot of ANRs.
Unfortunately, I do not know the exact steps to play. But I suspect that this happens when viewing UnityAds or Applovin ads when the application goes into the background.

What's the issue repro rate? (eg 100%, 1/5 etc) ~0,5% of all devices

All the data I own is data from the Google Play Developer Console. If you need more data, I will provide.

Below are screenshots of ANRs:
![image](https://user-images.githubusercontent.com/11135702/73289692-34bd0680-420e-11ea-97d1-a53090feddc7.png)
![image](https://user-images.githubusercontent.com/11135702/73289832-7188fd80-420e-11ea-8c81-2790ca0b46f2.png)
![image](https://user-images.githubusercontent.com/11135702/73289927-954c4380-420e-11ea-9cda-c4171f7a7e69.png)
![image](https://user-images.githubusercontent.com/11135702/73289848-75b51b00-420e-11ea-8477-8f2875006be3.png)
![image](https://user-images.githubusercontent.com/11135702/73289957-9ed5ab80-420e-11ea-8205-be7873c8f962.png)

**Comment by paulinon** [comment]
Thanks for reporting the issue, @Temka193. Could you check if you're still facing a lot of ANR's when you have the up-to-date versions of Unity and Firebase SDK to build your app?

**Comment by Temka193** [comment]
> Thanks for reporting the issue, @Temka193. Could you check if you're still facing a lot of ANR's when you have the up-to-date versions of Unity and Firebase SDK to build your app?

Sorry for not responding. Unfortunately, I cannot update Unity yet.
