### ISSUE TITLE
URI with Multiple parameters is incorrectly handled in Dynamic Linking

### ISSUE THREAD

**Issue by ut2496** [firebase/quickstart-unity#566]
Unity editor version: 2018.4.7f1
Firebase Unity SDK version: 6.9
Firebase plugins in use (Auth, Database, etc.): Dynamic Links
Additional SDKs you are using (Facebook, AdMob, etc.): none
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac/Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS/Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Issue Description :
Firebase dynamic link is treating URI parameters as its own when the base URI has multiple parameters. 
#### Reproduction steps : 

- Create a URI with multiple parameters.
- Create a Dynamic link with above URI as base link using `Firebase.DynamicLinks.DynamicLinkComponents()` 
- Receive the created Dynamic link on a target device using `ReceivedDynamicLinkEventArgs`

#### Example
The following is a sample dynamic long link generated using the Firebase unity sdk. (This is just an example, the example.page.link dynamic link doesn't exist)

`https://example.page.link/?afl=&amv=0&apn=com.bundle.id&ibi=com.bundle.id&ifl=&ipfl=&link=https://www.example.com/?para1=parameterValue&para2=parameterValue&para3=parameterValue`

When the `AbsoluteURI` of this dynamic link is received on a device (iOS/Windows/Android) using `ReceivedDynamicLinkEventArgs`, instead of the link being received as `https://www.example.com/?para1=parameterValue&para2=parameterValue&para3=parameterValue` only the link with first parameter i.e. `https://www.example.com/?para1=parameterValue` is received. The Dynamic link is treating the remaining parameter arguments appended using the `&` character as part of its own arguments rather than the link's. 
Is there any way to receive the target link as a whole ? Apologies if this is a duplicate issue.

### Workaround 
For the target link URI, instead of using `&` use a different unique character to append parameters and write a custom parser to receive said URI on the device.

What's the issue repro rate? 100 %

**Comment by paulinon** [comment]
Thanks for reporting this issue @ut2496. I'll try to reproduce this on my end. In the meantime, could you try using the latest versions of the Firebase SDK and Unity Editor to see if the issue persists? If so, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project that I can try out.

**Comment by ut2496** [comment]
Hi, Apologies the lack of communication from my end, I had been a bit busy recently. I am attaching a Unity Project and an Apk for device testing. The project is extremely minimal and displays a Generated Dynamic Link and when available a Received Dynamic Link.

Steps for Reproduction 
1. Generate Dynamic Link using Unity Project (Can be done through Apk too)
2. Use the dynamic link on a device with the apk installed. 
3. Logs can be seen through the command `adb logcat -s Unity`

Link for the package : https://drive.google.com/open?id=13y-OdmDjUG8M1Y-Ly3bxcZFBPsip7dYF

**Comment by paulinon** [comment]
Hi @ut2496. I seem to have an issue extracting your project on my end. Could you try using a .zip file instead?

**Comment by ut2496** [comment]
@paulinon 
Link for the zip file : https://drive.google.com/open?id=1u5lE7nohPhw3Q-DUyNTIeck4LcGfIDuU

Even if Google Drive doesn't show the preview you should be good to download and use the project inside. The folder also contains an .apk for testing on devices.

**Comment by paulinon** [comment]
Hi @ut2496. The reason for this behavior is that your deep link URL is not encoded, causing the last two parameters of your URL not to be received. If you're using multiple parameters in your deep link, ensure that it's URL-encoded.
