### ISSUE TITLE
Plugins: Couldn't open Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle, error: dlopen(Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle, 2): no suitable image found.  Did find: 	Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle: code signature in (Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle) not valid for use in process using Library

### ISSUE THREAD

**Issue by ctykaya** [firebase/quickstart-unity#567]
### Please fill in the following fields:
Unity editor version:  2019.03.0f6
Firebase Unity SDK version:  6.10.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Stroage, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac OS 10.15.3
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS and desktop
Scripting Runtime (Mono, and/or IL2CPP): Both

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I import the latest version of Firebase Unity SDK 6.10 to the project. When I press play button throws an error and pause the app and also popup a native waring message from os. 

I also try to delete Firebase and reimport it but cannot fixed the issue.

Says “FirebaseCppApp-6_10_0.bundle”, Cannot open because the developer could not be verified.
macOS, cannot verify that this application does not contain malware.

If I build the project with MONO and IL2CPP both arm7 and arm64  selected there is no problem 

I tried to resolve and  force resolve it return successfully but the problem is still there. I check the dll files on Plugin folder.

Here is the console log messages 

Plugins: Couldn't open Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle, error: dlopen(Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle, 2): no suitable image found.  Did find: 	Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle: code signature in (Assets/Firebase/Plugins/x86_64/FirebaseCppApp-6_10_0.bundle) not valid for use in process using Library

DllNotFoundException: FirebaseCppApp-6_10_0
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.5kTaS2UUGh/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:117)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.5kTaS2UUGh/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:137)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.5kTaS2UUGh/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.5kTaS2UUGh/firebase/app/client/unity/proxy/LogUtil.cs:80)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.5kTaS2UUGh/firebase/app/client/unity/proxy/LogUtil.cs:36)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.5kTaS2UUGh/firebase/app/client/unity/proxy/FirebaseApp.cs:62)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
LoginSceneManager.Awake () (at Assets/Scripts/LoginSceneManager.cs:79)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Haven't tried yet

What's the issue repro rate? (eg 100%, 1/5 etc)
%100

**Comment by paulinon** [comment]
Thanks for reporting the issue @ctykaya. It seems that this has something to do with your Unity setup. To resolve the issue, you can try the following:

- Disable "Enable Auto Resolution" under Asset > Play Services Resolver > Android Resolver > Settings
- Ensure that your JDK and SDK in your Unity Preferences are updated.

You can also follow along #559 and see if the developer's solution can apply for your case. 
If none of these worked, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project. You can do this using Google Drive via shareable link

**Comment by ctykaya** [comment]
Thanks @paulinon  I Disable "Enable auto Resolution" and force to resolve and re install the Unity with jdk and sdk packages but the problem continues. When I add a new project and import firebase sdk it works. What could I do to solve this problem?

**Comment by paulinon** [comment]
You can try following along #514. There are various solutions in this thread that could help you out. You can also try making use of the quickstart to see if the issue still persists. If you're still facing issues, could you share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project? Thanks.

**Comment by ctykaya** [comment]
@paulinon  I tried all advices at #514  but nothing helps. Here is the the link of google drive of the example project which you can reproduce the issue.  https://drive.google.com/file/d/1IMmJ3jPf8FOldBvzyjiEDtpJTKAYxm1z/view?usp=sharing

**Comment by paulinon** [comment]
Hi @ctykaya. It seems that you're facing an issue with your OS (probably similar to #515). Firebase could be blocked for this case. Simply go to your Security and Privacy Settings and allow Firebase.

**Comment by ctykaya** [comment]
yepp @paulinon  thanks for your help. It works 👍
