### ISSUE TITLE
Unity SIWA - Firebase Auth 6.10.0 Question

### ISSUE THREAD

**Issue by joses1234** [firebase/quickstart-unity#569]
I see in the docs you recommended usage of Unity's Sign in with apple asset store package. However a required parameter for `OAuthProvider.GetCredential` is the `nonce` which I cannot seem to figure out how to obtain with said package. 

I might be missing something here but how do i generate the `nonce` parameter? I tried inputting a random value and it seems to work, so I'm thinking about just generating the nonce myself. But would like to know your thoughts in this. Thanks!

**Comment by paulinon** [comment]
Thank you for your question @joses1234. Generally, a third-party plugin is used for Apple sign in nonce and token generation. You can try importing Unity's [Sign In With Apple Asset Storage Package](https://blogs.unity3d.com/2019/09/19/support-for-apple-sign-in/) in your project to do this.

**Comment by joses1234** [comment]
Thanks for your response @paulinon , I am currently using Unity's Sign in with apple asset store package. But I am not seeing a way on how to generate the nonce in the package.

**Comment by pistoleta** [comment]
Im facing the same problem here, the unity asset doesn't seem to provide any method to create this Nonce key.
Reading the documentation included inside the asset, the last part talks about Server Validation and Apply the ​standard JWT validation,  which seems it  has to be done by any other 3rd party library... I'm wondering if its that the way of creating this Nonce key.

**Comment by joses1234** [comment]
What i was able to get working was to amend the objective c file `UnitySignInWithApple.m` to generate the nonce and so you can receive it on callback in `CallbackArgs.userInfo`. 

I used the iOS documentation for SIWA in https://firebase.google.com/docs/auth/ios/apple as a guide and I believe you can find everything you need here for the nonce generation.

**Comment by chkuang-g** [comment]
Hi folks,

I think the latest [Firebase 6.10.0](https://firebase.google.com/download/unity) should include the function you need.
https://firebase.google.com/support/release-notes/unity#version_6100_-_january_30_2020

Please let us know if this works!

**Comment by DellaBitta** [comment]
Hi @joses1234 and all,

Thanks for the questions and comments.  We'll work to improve our documentation so that it's clear that users will need to generate a nonce and provide it to whichever plugins they use for Apple Sign In.

**Comment by chkuang-g** [comment]
@joses1234 

Can you problem be resolved by Unity plugin or native iOS code?

Shawn

**Comment by joses1234** [comment]
@chkuang-g The Unity plugin in itself doesn't support nonce generation, so I edited the objective c file that came with it to support nonce generation.

**Comment by reysantana** [comment]
Hello  @joses1234, I would like you to share the modified object c file...
Best, 
Rey

**Comment by chkuang-g** [comment]
@DellaBitta 

Isn't this suppose to be fixed in 6.14.1?
https://firebase.google.com/support/release-notes/unity#authentication

**Comment by DellaBitta** [comment]
Hi @joses1234 and @chkuang-g,

Yes, we've released an API update that accepts Apple Sign In credentials with a nonce.  For more information on how to use it, please review the [Firebase Unity Auth Guide for Apple Sign In](https://firebase.google.com/docs/auth/unity/apple) and let us know if you have any questions.  Thanks!

**Comment by DellaBitta** [comment]
I'm going to close this issue for now but feel free to re-open it if you have questions.
