### ISSUE TITLE
(iOS) How to determine if remote notification (while app in background) was tapped

### ISSUE THREAD

**Issue by jediric** [firebase/quickstart-unity#57]
Hi,

I am unsure how to determine whether the user tapped the notification while the app was in background.
When I check through the Message object, I see no difference between the message coming through tapping and the message simply being received while the app is open.

Am I missing something?

On Android it appears that the Notification object within the Message is being simply consumed once I tapped on it and therefore null when I receive the Message. But on iOS this does not appear to be the same.

**Comment by stewartmiles** [comment]
Excellent point!

Right now all messages received in the background on Android end up being routed to the app.  This differs to the behavior on iOS where we can't actually get at the message from the APNS notification until the user taps on it.  I've filed a bug internally where we can come up with a solution.

In the meantime, if you're willing to deal with some Java, you could customize the activity entry point (see https://firebase.google.com/docs/cloud-messaging/unity/client#note_for_android) to flag the message passed to onNewIntent() - which will be the message the user clicked on.  This would allow you to set a flag when the user clicks on a message vs. messages that were received in the background but never clicked on.

**Comment by stewartmiles** [comment]
We added NotificationOpened to message in the 3.0.0 release of the SDK, see https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-message#class_firebase_1_1_messaging_1_1_firebase_message_1a0ed7d611a65bfbcafe254c0456bf6524
