### ISSUE TITLE
DynamicLinkReceived is only called on first app start after install or the app is in background

### ISSUE THREAD

**Issue by Russel1** [firebase/quickstart-unity#571]
### Please fill in the following fields:
Unity editor version: 2019.2.17f1
Firebase Unity SDK version: 6.8.1
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, Crashlytics, Database, Dynamic Links, Messaging, RemoteConfig, Storage, Functions
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Adjust.io, StanAssets
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

I use firebase dynamic links. DynamicLinkReceived is only called on first app start after install or when the app is in background. But not on second cold start. I click the dynamic link it just opens the app and does not call the method.

Here someone also has the problem with the native SDK: https://stackoverflow.com/questions/54816290/dynamic-links-firebase-only-work-the-first-time

What's the issue repro rate? (eg 100%, 1/5 etc)
**100%**

**Comment by chkuang-g** [comment]
Hi @Russel1 

iOS SDK seems to [released a fix](https://firebase.google.com/support/release-notes/ios#version_6140_-_december_17_2019) in version 6.14.0 related to a crash on app launch.  Might related to your issue.

Firebase Unity SDK 6.8.1 is using iOS SDK 6.12.0 which does not include the fix.  I would recommend to upgrade to [the latest Unity SDK 6.10.0](https://firebase.google.com/download/unity) which points to iOS SDK 6.14.0, and see if that resolve your issue.

Let us know.
Shawn

**Comment by Russel1** [comment]
Firebase Update fixed the bug.
