### ISSUE TITLE
Firebase Auth failed on iOS (Unity, XCode)

### ISSUE THREAD

**Issue by MayisGM** [firebase/quickstart-unity#572]
Unity editor version: 2019.2.20f1
Firebase Unity SDK version: 6.10.0
Firebase plugins in use (Auth, Database, etc.): Auth
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

Xcode: 11 the latest
CocoaPods: The latest version

Hi everyone,

This is the second day I am not sleeping and trying to make Firebase Unity SDK work on iOS 13 device. I was able to build the project, but the issue is I am not able sign up or authenticate user.

Steps to Reproduce: (What I did)

1. Downloaded quickstart-unity/auth/testapp project
2. Opened in Unity 2019.2.20f1 with iOS platform
3. Changed Bundle ID to the one I have registered in Firebase Console
4. Put GoogleService-Info.plist under Assets/Firebase folder
5. Set Resolver iOS settings option Add CocoaPods to the Xcode project
6. Imported the latest Firebase Auth package 6.10.0 from dotnet4 folder to the project
7. Did build

What I see in Xcode project:

1. PodFile content looks like this:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'Firebase/Auth', '6.14.0'
  pod 'Firebase/Core', '6.14.0'
end
```
2. GoogleService-Info.plist is in Xcode project hierarchy too

Signed and build on my iPhone 8 with iOS 13.

Result: When I try to fill fields email and password and push button "Create User" which calls the method:

```
// Create a user with the email and password.
    public Task CreateUserWithEmailAsync() {
      DebugLog(String.Format("Attempting to create user {0}...", email));
      DisableUI();

      // This passes the current displayName through to HandleCreateUserAsync
      // so that it can be passed to UpdateUserProfile().  displayName will be
      // reset by AuthStateChanged() when the new user is created and signed in.
      string newDisplayName = displayName;
      return auth.CreateUserWithEmailAndPasswordAsync(email, password)
        .ContinueWithOnMainThread((task) => {
          EnableUI();
          if (LogTaskCompletion(task, "User Creation")) {
            var user = task.Result;
            DisplayDetailedUserInfo(user, 1);
            return UpdateUserProfileAsync(newDisplayName: newDisplayName);
          }
          return task;
        }).Unwrap();
    }
```

I see this error on device screen and in xcode logs too:

```
AuthError.Failure: Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.
```
Please find attached the full log from XCode...

Also I tried to do:

1. Build on device with lower iOS version.
2. Tried to build with Unity 2019.1.11 and 2019.1.13 versions
3. Tried to import GoogleService-Info.plist directly to Xcode project
4. Tried Firebase SDK 6.8.0 version
5. Tried to add [FIRApp configure] manually

Nothing worked.

Firebase console configured for project and contains two apps android and iOS with different Bundle IDs. Android version works perfect tested many time.

[iOS Xcode Log.txt](https://github.com/firebase/quickstart-unity/files/4160522/iOS.Xcode.Log.txt)

**Comment by xeonsrs** [comment]
I have the same kind of issue. Following the step by step instructions given in sample with no success!

**Comment by MayisGM** [comment]
As the error code not clear what is happening I added this kind of Logging:

```
auth.CreateUserWithEmailAndPasswordAsync(email, pass)
        .ContinueWithOnMainThread((task) => {
            if (task.IsCanceled)
            {
                PrintLog("CreateUserWithEmailAndPasswordAsync was canceled.");
                return;
            }
            if (task.IsFaulted)
            {
                PrintLog("CreateUserWithEmailAndPasswordAsync encountered an error: " + task.Exception);

                foreach (var e in task.Exception.Flatten().InnerExceptions)
                {
                    PrintLog(e.Message);
                }

                return;
            }


            // Firebase user has been created.
            Firebase.Auth.FirebaseUser newUser = task.Result;
            PrintLog(string.Format("Firebase user created successfully: {0} ({1})",
                newUser.DisplayName, newUser.UserId));
        });
```

To get some kind of readable information about exception, and I get this logs:

```
[SA LOG] CreateUserWithEmailAndPasswordAsync encountered an error: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.<---
<---
```
I see "Inner Exception #0", so I conclude error code is 0. According to this Firebase documentation:

https://firebase.google.com/docs/reference/unity/class/firebase/firebase-exception

```
If the error code is 0, the error is with the Task itself, and not the API. See the exception message for more detail.
```
Also according to this from Firebase Unity Integration documentation:
```
Unity 2017.1 IL2CPP compilation in .NET 4.x projects
Firebase supports .NET 4.x as an experimental build option in Unity 2017 and later. Firebase plugins use components of the Parse SDK to provide some .NET 4.x classes in earlier versions of .NET.

Therefore, the Firebase Unity SDK version 5.4.0 and later provides type forwarding DLLs which forward Parse types (for example, Parse implementation of System.Threading.Tasks.Task) to the .NET framework. Unfortunately, IL2CPP (a transpiler that converts C# to C++) that is shipped in Unity 2017.1.x does not correctly process type forwarding DLLs which results in build errors that resemble the following:

Fatal error in Unity CIL Linker Mono.Cecil.ResolutionException: Failed to
resolve System.Threading.Tasks.TaskCompletionSource`1<T>

There is currently no workaround available for .NET 4.x IL2CPP build errors in Unity 2017.1, so you must upgrade to Unity 2017.2 or later to use .NET 4.x in projects compiled with IL2CPP.
```
SO is that possible there is some issue with Parse.Tasks.dll and iOS build on newer Unity version than 2017.1? Building success without any errors, but Authentication not working anyway with the error mentioned above.

**Comment by paulinon** [comment]
Thanks for reporting this, @MayisGM. I've successfully created a user on my end using the quickstart. The difference is that I set my Cocoapods Integration to "Add CocoaPods to the Xcode project". Could you try doing that and see if everything works on your end?

**Comment by MayisGM** [comment]
Thank you for response @paulinon. My CocoaPods integration is exactly the same as you said. Also I call Install CocoaPods in Resolver. I see PodFIle, Podfile.lock and Pods folder. Also I tried to install CocoaPods manually. Nothing helps.

**Comment by chkuang-g** [comment]
Hi @MayisGM 

You issue is unlikely to related to Parse.Task.dll since it is only used for .NET 3.x.  Unity 2019 should use .NET 4.x.

I was not able to reproduce the issue with Unity 2019.1.11.  A couple of things that may help us to find the problem.

- Did you see any error in the Unity editor while building the Xcode project?
- Could you switch iOS Resolver setting to `Xcode Workspace - Add Cocoapods to the Xcode workspace`
- Since you are using quickstart to reproduce it (Great job! Thank you!), do you mind to share the whole project for us to analyze.

Thank you,
Shawn

**Comment by MayisGM** [comment]
Hi @chkuang-g 

Thanks for response. At least I was able to fix the problem. Here is the description how I fixed it.

As I mentioned above Unity was exporting PodFile like this:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'Firebase/Auth', '6.14.0'
  pod 'Firebase/Core', '6.14.0'
end
```
So this means Firebase Unity SDK 6.10.0 requires Pods version 6.14.0.
Building with this pods I was seeing error mentioned above:

```
[SA LOG] CreateUserWithEmailAndPasswordAsync encountered an error: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.FirebaseException: An internal error has occurred, print and inspect the error details for more information.<---
<---
```

As you can see this error says nothing.

After doing long research I noticed in CocoaPods website there are newer versions for Firebase pods available so I changed my PodsFile like this manually and installed Pods using terminal:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'FirebaseAnalytics', '~> 6.2'
  pod 'FirebaseAuth', '~> 6.4'
  pod 'FirebaseCore', '~> 6.6'
end
```

After building I was able to get human readable error which says:

```
Response body: {
  "error": {
    "code": 400,
    "message": "API key expired. Please renew the API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/37062923653/apiui/credential"
          }
        ]
      }
    ]
  }
}
```
I updated API key in Google Developer Console as error says and now everything works well.

Conclusion:

This wasn't issue related to Firebase Unity SDK 6.10.0 and nor 6.8.0, and also this wasn't related to Parse DLLs. Just the problem was the older versions 6.14.0 for Firebase Pods not giving human readable error, so I wasn't able to understand what was going on. After using latest Firebase Pods I was able to understand error reason.

Thanks everyone who responded to my problem.

P.S: Wish (Suggestion): Please improve Firebase Unity Samples UI responsiveness for different screen resolutions and make it more user friendly. If I didn't know this UI was made by Firebase team I will never believe this sample was made by Firebase team, because your all products are cool. ))

**Comment by DellaBitta** [comment]
Thanks for following up with us about the resolution and comments!
