### ISSUE TITLE
Use Firebase in Unity through a proxy

### ISSUE THREAD

**Issue by emaadgh** [firebase/quickstart-unity#573]
Hi, I am wondering that is there any way to use Firebase features like Remote Config, Analytics, etc in Android/iOS Unity apps by using this plugin through a proxy?

Thanks.

**Comment by paulinon** [comment]
Thank you for your question, @emaadgh. For you to be able to do this, you must first be able to whitelist various domain. For Analytics, the domain is "https://app-measurement.com/a". For Remote config, the domain is "https://cloudconfig.googleapis.com/config" for devices and "https://firebaseremoteconfig.googleapis.com/*" for managing config templates.

**Comment by emaadgh** [comment]
Thanks for your answer, @paulinon. We are able to whitelist these domains, But we need to use Firebase in a network that is behind a proxy and apps should connect through the proxy to access the internet. Is there any way to do this?

**Comment by emaadgh** [comment]
Hi, Any updates on this issue? If you need any more information please let me know.
Thanks.

**Comment by paulinon** [comment]
Sorry for the late reply @emaadgh. You can try following along this [community post](https://stackoverflow.com/questions/53275949/how-to-use-firebase-behind-firewall-proxy) which involves using a node.js application.

**Comment by emaadgh** [comment]
Thanks for your answer @paulinon, is there any way to directly set proxy address in Firebase Unity Plugin? So the plugin uses that proxy for all requests it sends?

**Comment by DellaBitta** [comment]
Hi @emaadgh,

No, sorry, there aren't proxy settings in the plugin itself.  Re-routing through a proxy must be done at the OS or Firewall level.  I hope this helps.
