### ISSUE TITLE
Dynamic Links - iPads iOS 13 - Incorrectly detected as not mobile. Opening final url in browser instead redirecting to app

### ISSUE THREAD

**Issue by SebaDudzic** [firebase/quickstart-unity#574]
### Please fill in the following fields:
Unity editor version: 2018.4.5f1
Firebase Unity SDK version: 5.6, 5.10
Firebase plugins in use (Auth, Database, etc.): Analytics, RemoteConfig, Crashlytics, DynamicLinks
Additional SDKs you are using (Facebook, AdMob, etc.):  Admob mediation, Facebook provider for Admob, Facebook SDK, Appsflyer, Android Native Pro,
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Run any firebase dynamic link on iPads Air or Pro with iOS 13+ without target app installed
Current behavior: Browser opened with final url.
Expected behavior: AppStore with target app is opened. Then I can install my app and receive link after opening it.

So in this case, it doesn't matter if I have good sdk, because my app is not installed anyway. If app is installed everything is working fine. App is opened, link is received.

So steps to reproduce:
1. Prepare iOS Pro or Air with iOS 13
2. Uninstall target app (in this case April Coloring)
3. Click dynamic link (in this case https://aprilcoloring.page.link/?afl=&amv=0&apn=com.crimsonpine.april&ibi=com.crimsonpine.april&ifl=&isi=1360270159&ipfl=&link=https:%2F%2FmessageID_42967d74-8f5e-45bc-8f5a-8a475180fb50&efr=1)
4. Bug is here. Browser with final url ( https://messageID_42967d74-8f5e-45bc-8f5a-8a475180fb50) is opened instead of AppStore

We have encountered a similar problem while making our custom link shortener. It seems that new iPads while opening urls do not pass in field "user_agent" value "mobile" or "tablet". Only way to detect this is iPad and not MacOS is to analyze other fields - there is special section similar to "Version/13.0.0". 

This is how mentioned iPads apprears (looking like macos):
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/**13.0.4** Safari/605.1.15"

Devices tested:
**- Working:**
- iPhone 8, 7, 6, 5, XsMax - iOS 12 and 13
- iPad Mini (gen 2) iOS 12
- iPad Mini (gen 4, 5) iOS 13
- iPad Air (gen 2) iOS 12
**- Not working:**
- iPad Air (gen 3) iOS 13
- iPad Pro (gen 3 11") iOS 13
- iPad Pro (gen 2 12,9") iOS 13
**- Not tested:**
- Newest iPhones (11, 11 Pro etc.)

Note: our link we are passing to dynamic links looks like https://messageID_someuid

Video of good and bad behavior:
https://drive.google.com/file/d/1aiOg4tcgRfU1ea4YwqGNrdFjYMV6Fw3r/view?usp=sharing

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by paulinon** [comment]
Thanks for reporting this issue @SebaDudzic. It appears that you're using an old version of the SDK. Could you try using the latest version of the Firebase SDK and see if the issue still persists? If it does, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I could check out what's wrong.

**Comment by SebaDudzic** [comment]
I'm sorry I have made a mistake in use case description. Below is true problem:

Run any firebase dynamic link on iPads Air or Pro with iOS 13+ without target app installed
Current behavior: Browser opened with final url.
Expected behavior: AppStore with target app is opened. Then I can install my app and receive link after opening it.

So in this case, it doesn't matter if I have good sdk, because my app is not installed anyway. If app is installed everything is working fine. App is opened, link is received.

So steps to reproduce:
1. Prepare iOS Pro or Air with iOS 13
2. Uninstall target app (in this case April Coloring)
3. Click dynamic link (in this case https://aprilcoloring.page.link/?afl=&amv=0&apn=com.crimsonpine.april&ibi=com.crimsonpine.april&ifl=&isi=1360270159&ipfl=&link=https:%2F%2FmessageID_42967d74-8f5e-45bc-8f5a-8a475180fb50&efr=1)
4. Bug is here. Browser with final url ( https://messageID_42967d74-8f5e-45bc-8f5a-8a475180fb50) is opened instead of AppStore

You can use our link ;)

**Comment by SebaDudzic** [comment]
I don't want to make another issue, but there are also similar problems with Safari (when you paste url manually). No matter what iOS if this is iPhone or iPad. It either open AppStore even if you have app installed, or it has bug mentioned in this issue. 

Here is some snapshot of our testing results (we have tested more devices but not all was documented):
![image](https://user-images.githubusercontent.com/28657500/73936491-42941b00-48e3-11ea-80d7-1aed444293d1.png)

**Comment by paulinon** [comment]
Thanks for clarifying, @SebaDudzic. There are two possible reasons for this behavior with your other devices.
- There could be another SDK interfering with swizzling. To show that this is the case, could you try using our quickstart and progressively add other SDKs till you face the issue?
- The dynamic link could be broken. Could you try using our [iOS quickstart](https://github.com/firebase/quickstart-ios) and see if the issue persists?

**Comment by dmandar** [comment]
Thanks for reporting. On iPad, Safari opens the desktop version of the site by default. Internal bug b/148649490 is tracking this.

**Comment by SebaDudzic** [comment]
@paulinon 

- How can I add or remove SDKs if my app is not installed? It makes no sense. I explained in my previous message that this is case with no app on device. Redirecting to store is not working.
- This is another test where I used quickstart project to generate dynamic link, and then clicked it on iPad. Results are the same.

https://drive.google.com/file/d/1DNhns-3us47kMYXQ62mWNnEdjmSCN2io/view?usp=sharing

**Comment by SebaDudzic** [comment]
What about opening these links from other apps than safari? This was my main issue here. No information if you even work on it.

**Comment by teerawat-hot-now** [comment]
I'm also facing the same problem. @SebaDudzic when application is not installed it should show the preview page and direct to the App Store. I tested it on iPad Pro (12.9) 3gen.

**Comment by SebaDudzic** [comment]
We are not using preview page. Maybe that's why this is not working

**Comment by adrianpaiva1** [comment]
I'm facing the exact same issue, any updates on this?

**Comment by dmandar** [comment]
Our backend team is actively working on a fix. Please stay tuned.

**Comment by Jacowaco** [comment]
Same happening here.

**Comment by Jacowaco** [comment]
> Our backend team is actively working on a fix. Please stay tuned.

Do you have an estimated date? My game is only with millions of users, and the iOS users can't open the custom levels created by other users with dynamic links. Or is there a "hack" or workaround?

**Comment by harmrietjens** [comment]
Problem also happening on our end. Any update on this would be great.

**Comment by harmrietjens** [comment]
@dmandar Can you ask the backend team if they're still actively working on a solution like you indicated on April 1?

**Comment by chkuang-g** [comment]
@harmrietjens 

I had a peak at b/148649490 and seems like it has been fixed in this May.

Could you verify if this is still happening in our latest Unity SDK `6.16.1`?

Thank you,
Shawn

**Comment by DellaBitta** [comment]
I'm going to close this for now as the release has been out for some time.  Please feel free to re-open and @ me if you continue to have issues.  Thanks!
