### ISSUE TITLE
Build error iOS

### ISSUE THREAD

**Issue by LukasRoper** [firebase/quickstart-unity#577]
Hi,

I'm having an annoying issue building out one of my projects. I get the following error (posted at the bottom).

It seems that GTMSessionFetcher can't be copied and I'm 90% sure this worked before as I managed to do a build yesterday without the issue. 

I'm building from a Mac and have uninstalled and reinstalled cocoa pods and have attempted another build from another project that seems to work.

Just wondered if there were any obvious steps for me to take?

Thanks,

> iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
Downloading dependencies
Installing Firebase (6.14.0)
Installing FirebaseAnalytics (6.1.7)
Installing FirebaseCore (6.5.0)
Installing FirebaseCoreDiagnostics (1.2.0)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseInstanceID (4.2.8)
Installing GoogleAppMeasurement (6.1.7)
Installing GoogleDataTransport (3.3.1)
Installing GoogleDataTransportCCTSupport (1.3.1)
Installing GoogleUtilities (6.5.1)
Installing nanopb (0.3.9011)
Generating Pods project

 MARKDOWN TEMPLATE 

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ a723d4a0679fe48ed976f881a66f9a1fc7ff9201
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'Unity-iPhone' do
  pod 'Firebase/Analytics', '6.14.0'
  pod 'Firebase/Core', '6.14.0'
  pod 'GVRSDK', '~> 1.170'
end
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/dev/Test3/Pods/Target Support Files/GTMSessionFetcher/GTMSessionFetcher.xcconfig
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:21:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:21:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:21:in `update_changed_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:570:in `create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:60:in `block in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:32:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator.rb:114:in `block in install_pod_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `install_pod_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:294:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

 TEMPLATE END 

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fdev%2FTest3%2FPods%2FTarget+Support+Files%2FGTMSessionFetcher%2FGTMSessionFetcher.xcconfig&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m

pod repo update output:

Updating spec repo `cocoapods`

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.c5cHAkrYVv/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:127)
Google.IOSResolver:Log(String, Boolean, LogLevel) (at Z:/tmp/tmp.Q78nyHwtKI/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:1007)
Google.IOSResolver:OnPostProcessInstallPods(BuildTarget, String) (at Z:/tmp/tmp.Q78nyHwtKI/third_party/unity/unity_jar_resolver/source/IOSResolver/src/IOSResolver.cs:2331)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

>

**Comment by chkuang-g** [comment]
Hi @LukasRoper 

Could you give as more information as the template asked for? Ex. Unity version, Firebase version.

Thank you,
Shawn

**Comment by LukasRoper** [comment]
Sorry, I've included more details below. 

_Please fill in the following fields:_

Unity editor version: 2019.1.14f1
Firebase Unity SDK version: 6.10
Firebase plugins in use (Auth, Database, etc.): Analytics. Also using Cardboard (outside of Firebase).
Platform you are using the Unity editor on (Mac, Windows, or Linux): Max
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

_Please describe the issue here:_

Use case: Just trying to build
Current behavior: Error on build completion (see initial post above). I feel like a file is being locked and not sure why.

_Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?_
Not tried with the quickstart, also not with another project. I've managed to successfully build previously too. 

_What's the issue repro rate? (eg 100%, 1/5 etc)_
90%

**Comment by DellaBitta** [comment]
Hi @LukasRoper,

Could this be a file open permissions error, something similar to this [rb-sysopen owner permissions problem](https://stackoverflow.com/questions/44770882/how-do-i-remove-permission-denied-rb-sysopen-gem-install-error)?  Thanks!

**Comment by LukasRoper** [comment]
I'll try that, thanks for your response!
