### ISSUE TITLE
Current dependency status: UnavailableOther

### ISSUE THREAD

**Issue by CoffeeGames9** [firebase/quickstart-unity#58]
i'm using firebase cloud messaging unity package.
In the GUI I get this too

one or more firebase dependencies are not present
Current dependency status: UnavailableOther

What does this mean? 
how tor resolve this issue?

**Comment by stewartmiles** [comment]
I'm guessing you're targeting Android?  If so see my response to https://github.com/firebase/quickstart-unity/issues/53

**Comment by stewartmiles** [comment]
Please reopen if #53 didn't resolve your issue.
