### ISSUE TITLE
Setting up Firebase Auth SignInWithProvider Error

### ISSUE THREAD

**Issue by fatmousemiyabi** [firebase/quickstart-unity#580]
### Please fill in the following fields:
Unity editor version: 5.6.6.f1
Firebase Unity SDK version: 6.10.0
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):Mono

### Please describe the issue here:
I have build this sample successful and run on mobile of Android platform.
Now I find an error when the sample running.
When I click "Signwith|Yahoo" or "Signwith | Microsoft", the screen will lower brightness. Then I click mobile "Home" button and return this apps again, if I click "Signwith|Yahoo" or "Signwith | Microsoft" again, will occur an error:
Setting up Firebase Auth SignInWithProvider encounted an error. AuthError.WebContextAlreadyPresented: Firebase.FirebaseException: A headful operation is already in progress. Please wait for that to finish. SignInWithProviderTask - Excepton: Exception of type 'System.AggregateException' was thrown.

Could somebody tell me what to do of this ?
Thinks

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?Yes

What's the issue repro rate? 100%

**Comment by paulinon** [comment]
Thanks for reporting this issue @fatmousemiyabi. I've noticed that you're using an old version of the Unity Editor. Could you try using the latest version of the editor then redo your build and see if the issue still occurs? If so, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I could isolate the cause of the issue.

**Comment by fatmousemiyabi** [comment]
> Thanks for reporting this issue @fatmousemiyabi. I've noticed that you're using an old version of the Unity Editor. Could you try using the latest version of the editor then redo your build and see if the issue still occurs? If so, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I could isolate the cause of the issue.

Thanks for your advise, and I change a new version of unity (Unity2019.2.6f1).
But when I Input the sample in unity, it occur another error :
Assets\Firebase\Sample\Auth\UIHandler.cs(251,38): error CS0433: The type 'Task' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

How can I resolve this problem？
Thanks.

**Comment by paulinon** [comment]
This can be resolved by deleting the Parse folder found in your Assets.

**Comment by fatmousemiyabi** [comment]
> This can be resolved by deleting the Parse folder found in your Assets.

I had tried to deleting the Parse folder, then occur another error:
Assets\Firebase\Sample\Auth\UIHandler.cs(80,7): error CS0012: The type 'Task<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

And How can I resolve this error？
Thanks.

**Comment by paulinon** [comment]
Could you share your [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) project so I can try to resolve it on my end?

**Comment by fatmousemiyabi** [comment]
> reproducible example

I have upload my project to this cloud disk：
address：https://pan.baidu.com/s/1B6W_fBvuIrmvVxk0aajUdA
access code：n2pp

And the file neme include unity version I use.

**Comment by paulinon** [comment]
I'm having an issue trying to access your file. Could you try uploading your project to a Github repository and share it to me?

**Comment by fatmousemiyabi** [comment]
I try to create a repository buy "FirebaseCppApp-6_10_0.so" is too big to upload......
My project is just use "https://github.com/firebase/quickstart-unity/tree/master/auth" this sample project, and change a little code in UIHandle:
`if (GUILayout.Button("SignInWith | Facebook"))
        {
            SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Google"))
        {
            SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId);
        }`
And use myself "google-services.json"

**Comment by paulinon** [comment]
Before I proceed with replicating your issue, could you please share your UIHandler code? I can't seem to find the place to insert the code you provided

**Comment by fatmousemiyabi** [comment]
I just insert a few lines in "void GUIDisplayControls()" this function.
`if (GUILayout.Button("SignInWith | Facebook")) { SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId); } if (GUILayout.Button("SignInWith | Google")) { SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId); }`

below is whole code of this function:
`void GUIDisplayControls() {
      if (UIEnabled) {
        controlsScrollViewVector =
          GUILayout.BeginScrollView(controlsScrollViewVector);
        GUILayout.BeginVertical();
        GUILayout.BeginHorizontal();
        GUILayout.Label("Email:", GUILayout.Width(Screen.width * 0.20f));
        email = GUILayout.TextField(email);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Password:", GUILayout.Width(Screen.width * 0.20f));
        password = usePasswordInput ? GUILayout.PasswordField(password, '*') :
          GUILayout.TextField(password);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Display Name:", GUILayout.Width(Screen.width * 0.20f));
        displayName = GUILayout.TextField(displayName);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Phone Number:", GUILayout.Width(Screen.width * 0.20f));
        phoneNumber = GUILayout.TextField(phoneNumber);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Phone Auth Received Code:", GUILayout.Width(Screen.width * 0.20f));
        receivedCode = GUILayout.TextField(receivedCode);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        if (GUILayout.Button("Create User")) {
          CreateUserWithEmailAsync();
        }
        if (GUILayout.Button("Sign In Anonymously")) {
          SigninAnonymouslyAsync();
        }
        if (GUILayout.Button("Sign In With Email")) {
          SigninWithEmailAsync();
        }
        if (GUILayout.Button("Sign In With Email Credential")) {
          SigninWithEmailCredentialAsync();
        }
        if (GUILayout.Button("Link With Email Credential")) {
          LinkWithEmailCredentialAsync();
        }
        if (GUILayout.Button("Reauthenticate with Email")) {
          ReauthenticateAsync();
        }
        GUIDisplayGameCenterControls();
        if (GUILayout.Button("Reload User")) {
          ReloadUser();
        }
        if (GUILayout.Button("Get User Token")) {
          GetUserToken();
        }
        if (GUILayout.Button("Get User Info")) {
          GetUserInfo();
        }
        if (GUILayout.Button("Unlink Email Credential")) {
          UnlinkEmailAsync();
        }
        if (GUILayout.Button("Sign Out")) {
          SignOut();
        }
        if (GUILayout.Button("Delete User")) {
          DeleteUserAsync();
        }
        if (GUILayout.Button("Show Providers For Email")) {
          DisplayProvidersForEmail();
        }
        if (GUILayout.Button("Password Reset Email")) {
          SendPasswordResetEmail();
        }
        if (GUILayout.Button("Authenticate Phone Number")) {
          VerifyPhoneNumber();
        }
        if (GUILayout.Button("Verify Received Phone Code")) {
          VerifyReceivedPhoneCode();
        }
        if (GUILayout.Button(String.Format("Fetch Profile on Sign-in {0}",
                                            signInAndFetchProfile ?
                                              "Enabled" : "Disabled"))) {
          signInAndFetchProfile = !signInAndFetchProfile;
        }
        if (HasOtherAuth && GUILayout.Button(String.Format("Switch to auth object {0}",
                                                            otherAuth.App.Name))) {
          SwapAuthFocus();
        }

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Phone-Only OAuth2:", GUILayout.Width(Screen.width * 0.4f));
        GUILayout.EndHorizontal();

        GUILayout.BeginHorizontal();
        GUILayout.Label("scope 1:", GUILayout.Width(Screen.width * 0.20f));
        scope1 = GUILayout.TextField(scope1, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("scope 2:", GUILayout.Width(Screen.width * 0.20f));
        scope2 = GUILayout.TextField(scope2, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Key1:", GUILayout.Width(Screen.width * 0.20f));
        customParameterKey1 = GUILayout.TextField(customParameterKey1, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Value1:", GUILayout.Width(Screen.width * 0.20f));
        customParameterValue1 = GUILayout.TextField(customParameterValue1, GUILayout.Width(Screen.width * 0.25f));
        GUILayout.EndHorizontal();

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Key2:", GUILayout.Width(Screen.width * 0.20f));
        customParameterKey2 = GUILayout.TextField(customParameterKey2, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Value2:", GUILayout.Width(Screen.width * 0.20f));
        customParameterValue2 = GUILayout.TextField(customParameterValue2, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);
        if (GUILayout.Button("SignInWith | Facebook"))
        {
            SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Google"))
        {
            SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Microsoft"))
        {
            SignInWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Yahoo"))
        {
            SignInWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
        }
        if (GUILayout.Button("ReauthWith | Microsoft"))
        {
            ReauthenticateWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("ReauthWith | Yahoo"))
        {
            ReauthenticateWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
        }
        if (GUILayout.Button("LinkWith | Microsoft"))
        {
            LinkWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("LinkWith | Yahoo"))
        {
            LinkWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
        }
        if (GUILayout.Button("Unlink User | Microsoft"))
        {
            UnlinkUser(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("Unlink User | Yahoo"))
        {
            UnlinkUser(Firebase.Auth.YahooAuthProvider.ProviderId);
        }

        GUIDisplayCustomControls();
        GUILayout.EndVertical();
        GUILayout.EndScrollView();
      }
    }`

**Comment by fatmousemiyabi** [comment]
I just insert a few lines in "void GUIDisplayControls()" this function.
if (GUILayout.Button("SignInWith | Facebook")) { SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId); } if (GUILayout.Button("SignInWith | Google")) { SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId); }

below is whole code of this function:
`  void GUIDisplayControls() {
    if (UIEnabled) {
    controlsScrollViewVector =
    GUILayout.BeginScrollView(controlsScrollViewVector);
    GUILayout.BeginVertical();
    GUILayout.BeginHorizontal();
    GUILayout.Label("Email:", GUILayout.Width(Screen.width * 0.20f));
    email = GUILayout.TextField(email);
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("Password:", GUILayout.Width(Screen.width * 0.20f));
    password = usePasswordInput ? GUILayout.PasswordField(password, '*') :
      GUILayout.TextField(password);
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("Display Name:", GUILayout.Width(Screen.width * 0.20f));
    displayName = GUILayout.TextField(displayName);
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("Phone Number:", GUILayout.Width(Screen.width * 0.20f));
    phoneNumber = GUILayout.TextField(phoneNumber);
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("Phone Auth Received Code:", GUILayout.Width(Screen.width * 0.20f));
    receivedCode = GUILayout.TextField(receivedCode);
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    if (GUILayout.Button("Create User")) {
      CreateUserWithEmailAsync();
    }
    if (GUILayout.Button("Sign In Anonymously")) {
      SigninAnonymouslyAsync();
    }
    if (GUILayout.Button("Sign In With Email")) {
      SigninWithEmailAsync();
    }
    if (GUILayout.Button("Sign In With Email Credential")) {
      SigninWithEmailCredentialAsync();
    }
    if (GUILayout.Button("Link With Email Credential")) {
      LinkWithEmailCredentialAsync();
    }
    if (GUILayout.Button("Reauthenticate with Email")) {
      ReauthenticateAsync();
    }
    GUIDisplayGameCenterControls();
    if (GUILayout.Button("Reload User")) {
      ReloadUser();
    }
    if (GUILayout.Button("Get User Token")) {
      GetUserToken();
    }
    if (GUILayout.Button("Get User Info")) {
      GetUserInfo();
    }
    if (GUILayout.Button("Unlink Email Credential")) {
      UnlinkEmailAsync();
    }
    if (GUILayout.Button("Sign Out")) {
      SignOut();
    }
    if (GUILayout.Button("Delete User")) {
      DeleteUserAsync();
    }
    if (GUILayout.Button("Show Providers For Email")) {
      DisplayProvidersForEmail();
    }
    if (GUILayout.Button("Password Reset Email")) {
      SendPasswordResetEmail();
    }
    if (GUILayout.Button("Authenticate Phone Number")) {
      VerifyPhoneNumber();
    }
    if (GUILayout.Button("Verify Received Phone Code")) {
      VerifyReceivedPhoneCode();
    }
    if (GUILayout.Button(String.Format("Fetch Profile on Sign-in {0}",
                                        signInAndFetchProfile ?
                                          "Enabled" : "Disabled"))) {
      signInAndFetchProfile = !signInAndFetchProfile;
    }
    if (HasOtherAuth && GUILayout.Button(String.Format("Switch to auth object {0}",
                                                        otherAuth.App.Name))) {
      SwapAuthFocus();
    }

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("Phone-Only OAuth2:", GUILayout.Width(Screen.width * 0.4f));
    GUILayout.EndHorizontal();

    GUILayout.BeginHorizontal();
    GUILayout.Label("scope 1:", GUILayout.Width(Screen.width * 0.20f));
    scope1 = GUILayout.TextField(scope1, GUILayout.Width(Screen.width * 0.5f));
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("scope 2:", GUILayout.Width(Screen.width * 0.20f));
    scope2 = GUILayout.TextField(scope2, GUILayout.Width(Screen.width * 0.5f));
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("customParam Key1:", GUILayout.Width(Screen.width * 0.20f));
    customParameterKey1 = GUILayout.TextField(customParameterKey1, GUILayout.Width(Screen.width * 0.5f));
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("customParam Value1:", GUILayout.Width(Screen.width * 0.20f));
    customParameterValue1 = GUILayout.TextField(customParameterValue1, GUILayout.Width(Screen.width * 0.25f));
    GUILayout.EndHorizontal();

    GUILayout.BeginHorizontal();
    GUILayout.Label("customParam Key2:", GUILayout.Width(Screen.width * 0.20f));
    customParameterKey2 = GUILayout.TextField(customParameterKey2, GUILayout.Width(Screen.width * 0.5f));
    GUILayout.EndHorizontal();

    GUILayout.Space(20);

    GUILayout.BeginHorizontal();
    GUILayout.Label("customParam Value2:", GUILayout.Width(Screen.width * 0.20f));
    customParameterValue2 = GUILayout.TextField(customParameterValue2, GUILayout.Width(Screen.width * 0.5f));
    GUILayout.EndHorizontal();

    GUILayout.Space(20);
    if (GUILayout.Button("SignInWith | Facebook"))
    {
        SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId);
    }
    if (GUILayout.Button("SignInWith | Google"))
    {
        SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId);
    }
    if (GUILayout.Button("SignInWith | Microsoft"))
    {
        SignInWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
    }
    if (GUILayout.Button("SignInWith | Yahoo"))
    {
        SignInWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
    }
    if (GUILayout.Button("ReauthWith | Microsoft"))
    {
        ReauthenticateWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
    }
    if (GUILayout.Button("ReauthWith | Yahoo"))
    {
        ReauthenticateWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
    }
    if (GUILayout.Button("LinkWith | Microsoft"))
    {
        LinkWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
    }
    if (GUILayout.Button("LinkWith | Yahoo"))
    {
        LinkWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
    }
    if (GUILayout.Button("Unlink User | Microsoft"))
    {
        UnlinkUser(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
    }
    if (GUILayout.Button("Unlink User | Yahoo"))
    {
        UnlinkUser(Firebase.Auth.YahooAuthProvider.ProviderId);
    }

    GUIDisplayCustomControls();
    GUILayout.EndVertical();
    GUILayout.EndScrollView();
  }
}`

**Comment by fatmousemiyabi** [comment]
I just insert a few lines in "void GUIDisplayControls()" this function.
if (GUILayout.Button("SignInWith | Facebook")) { SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId); } if (GUILayout.Button("SignInWith | Google")) { SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId); }

below is whole code of this function:
```CSharp
    void GUIDisplayControls() {
      if (UIEnabled) {
        controlsScrollViewVector =
          GUILayout.BeginScrollView(controlsScrollViewVector);
        GUILayout.BeginVertical();
        GUILayout.BeginHorizontal();
        GUILayout.Label("Email:", GUILayout.Width(Screen.width * 0.20f));
        email = GUILayout.TextField(email);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Password:", GUILayout.Width(Screen.width * 0.20f));
        password = usePasswordInput ? GUILayout.PasswordField(password, '*') :
          GUILayout.TextField(password);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Display Name:", GUILayout.Width(Screen.width * 0.20f));
        displayName = GUILayout.TextField(displayName);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Phone Number:", GUILayout.Width(Screen.width * 0.20f));
        phoneNumber = GUILayout.TextField(phoneNumber);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Phone Auth Received Code:", GUILayout.Width(Screen.width * 0.20f));
        receivedCode = GUILayout.TextField(receivedCode);
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        if (GUILayout.Button("Create User")) {
          CreateUserWithEmailAsync();
        }
        if (GUILayout.Button("Sign In Anonymously")) {
          SigninAnonymouslyAsync();
        }
        if (GUILayout.Button("Sign In With Email")) {
          SigninWithEmailAsync();
        }
        if (GUILayout.Button("Sign In With Email Credential")) {
          SigninWithEmailCredentialAsync();
        }
        if (GUILayout.Button("Link With Email Credential")) {
          LinkWithEmailCredentialAsync();
        }
        if (GUILayout.Button("Reauthenticate with Email")) {
          ReauthenticateAsync();
        }
        GUIDisplayGameCenterControls();
        if (GUILayout.Button("Reload User")) {
          ReloadUser();
        }
        if (GUILayout.Button("Get User Token")) {
          GetUserToken();
        }
        if (GUILayout.Button("Get User Info")) {
          GetUserInfo();
        }
        if (GUILayout.Button("Unlink Email Credential")) {
          UnlinkEmailAsync();
        }
        if (GUILayout.Button("Sign Out")) {
          SignOut();
        }
        if (GUILayout.Button("Delete User")) {
          DeleteUserAsync();
        }
        if (GUILayout.Button("Show Providers For Email")) {
          DisplayProvidersForEmail();
        }
        if (GUILayout.Button("Password Reset Email")) {
          SendPasswordResetEmail();
        }
        if (GUILayout.Button("Authenticate Phone Number")) {
          VerifyPhoneNumber();
        }
        if (GUILayout.Button("Verify Received Phone Code")) {
          VerifyReceivedPhoneCode();
        }
        if (GUILayout.Button(String.Format("Fetch Profile on Sign-in {0}",
                                            signInAndFetchProfile ?
                                              "Enabled" : "Disabled"))) {
          signInAndFetchProfile = !signInAndFetchProfile;
        }
        if (HasOtherAuth && GUILayout.Button(String.Format("Switch to auth object {0}",
                                                            otherAuth.App.Name))) {
          SwapAuthFocus();
        }

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("Phone-Only OAuth2:", GUILayout.Width(Screen.width * 0.4f));
        GUILayout.EndHorizontal();

        GUILayout.BeginHorizontal();
        GUILayout.Label("scope 1:", GUILayout.Width(Screen.width * 0.20f));
        scope1 = GUILayout.TextField(scope1, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("scope 2:", GUILayout.Width(Screen.width * 0.20f));
        scope2 = GUILayout.TextField(scope2, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Key1:", GUILayout.Width(Screen.width * 0.20f));
        customParameterKey1 = GUILayout.TextField(customParameterKey1, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Value1:", GUILayout.Width(Screen.width * 0.20f));
        customParameterValue1 = GUILayout.TextField(customParameterValue1, GUILayout.Width(Screen.width * 0.25f));
        GUILayout.EndHorizontal();

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Key2:", GUILayout.Width(Screen.width * 0.20f));
        customParameterKey2 = GUILayout.TextField(customParameterKey2, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);

        GUILayout.BeginHorizontal();
        GUILayout.Label("customParam Value2:", GUILayout.Width(Screen.width * 0.20f));
        customParameterValue2 = GUILayout.TextField(customParameterValue2, GUILayout.Width(Screen.width * 0.5f));
        GUILayout.EndHorizontal();

        GUILayout.Space(20);
        if (GUILayout.Button("SignInWith | Facebook"))
        {
            SignInWithProvider(Firebase.Auth.FacebookAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Google"))
        {
            SignInWithProvider(Firebase.Auth.GoogleAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Microsoft"))
        {
            SignInWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("SignInWith | Yahoo"))
        {
            SignInWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
        }
        if (GUILayout.Button("ReauthWith | Microsoft"))
        {
            ReauthenticateWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("ReauthWith | Yahoo"))
        {
            ReauthenticateWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
        }
        if (GUILayout.Button("LinkWith | Microsoft"))
        {
            LinkWithProvider(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("LinkWith | Yahoo"))
        {
            LinkWithProvider(Firebase.Auth.YahooAuthProvider.ProviderId);
        }
        if (GUILayout.Button("Unlink User | Microsoft"))
        {
            UnlinkUser(Firebase.Auth.MicrosoftAuthProvider.ProviderId);
        }
        if (GUILayout.Button("Unlink User | Yahoo"))
        {
            UnlinkUser(Firebase.Auth.YahooAuthProvider.ProviderId);
        }

        GUIDisplayCustomControls();
        GUILayout.EndVertical();
        GUILayout.EndScrollView();
      }
    }```

**Comment by fatmousemiyabi** [comment]
And I wonder can I use firebase with unity version 5.5.6f2 ?
because my game make with this version.
Thanks.

**Comment by fatmousemiyabi** [comment]
And I wonder can I use firebase with unity version 5.6.6f2 ?
because my game make with this version, and hard to update.
Thanks.

**Comment by paulinon** [comment]
Hi @fatmousemiyabi. When you said that the screen will lower its brightness, it means that it's bound to redirect to an external page for a sign-in in progress. I have a few questions regarding your project:

- Were you able to add your SHA certificate fingerprint? If not, you may refer to the instructions [here](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp#android).
- Have you tested using another device? On my end, I was redirected to Yahoo's sign in page when I tapped "SignInWith | Yahoo"

**Comment by fatmousemiyabi** [comment]
![0LP08783_K8XG%)N78WLJEO](https://user-images.githubusercontent.com/12016817/74700891-f7153180-523f-11ea-959b-4b1af386b3cf.png)

**Comment by fatmousemiyabi** [comment]
Hi @paulinon . I think that log error maybe related to weak network. 
Below is my test apps picture of normal interface: 
![a1](https://user-images.githubusercontent.com/12016817/74795645-6f8ff700-5301-11ea-8d96-93bf84fbe2ee.png)
If in weak network state and click any "SigninWith | XXX" button. It will wait for the external page, like the interface below(lower its brightness):
![0FDDDE93A823C6FE8162B43B49E7BD0F](https://user-images.githubusercontent.com/12016817/74795896-1d030a80-5302-11ea-8325-6a02db850b16.jpg)

If click "Home" button this time and then wake up my test apps again，it will return to normal interface look, but appear the error : 
Firebase.FirebaseException: A headful operation is already in progress. Please wait for that to finish. SignInWithProviderTask - Excepton: Exception of type 'System.AggregateException'

It like sign-in progress dosn't be canceled. And then I can do nothing.

**Comment by DellaBitta** [comment]
Hi @fatmousemiyabi,

Note that Firebase supports SignInWithProvider functionality for Yahoo and Microsoft. There may be errors on the device and/or the firebase backend if you attempt to use other providers wih the SignInWithProvider flow.  Please see the corresponding guides on how to sign in with [Facebook](https://firebase.google.com/docs/auth/unity/facebook-login), [Google](https://firebase.google.com/docs/auth/unity/google-signin), and [Twitter](https://firebase.google.com/docs/auth/unity/twitter-login) via the Unity SDK.

It sounds like what's occuring is an error when the Android Activity is swtching to show the Provider Sign In page.  It may be related to an unsupported provider.  Are there any obvious logs coming from the device via logcat at the time that the screen is becoming darker?

**Comment by fatmousemiyabi** [comment]
Hi @paulinon ,
There is no other logs. But this is just occur in my access to the internet is not good. (Can not pop up the Signin Page and waiting)
If I ckick "Back" button, this state(call sign-in page in progress) will be canceled, so I can call sign-up continue.
But if I click "Home" button, it seem the progress of sign-in is not canceled. so if I call sign-up again, it will show this error again an again.

**Comment by DellaBitta** [comment]
Hi @fatmousemiyabi ,

Could you review my note above?  It has links to the guides for the Firebase Auth Sign In for various providers.  SignInWithProvider is officially supported with Yahoo and Microsoft providers only, but I see in your screenshot that you're using it with Facebook, Google and Twitter.  This might be the cause of the problem.
