### ISSUE TITLE
SigninWith|Facebook Error

### ISSUE THREAD

**Issue by fatmousemiyabi** [firebase/quickstart-unity#581]
### Please fill in the following fields:
Unity editor version: 5.6.6.f1
Firebase Unity SDK version: 6.10.0
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):Mono

### Please describe the issue here:
I have build this sample successful and run on mobile of Android platform.
But when I click "SigninWith|Facebook", will occur this error:
AuthError.Unimplemented: Firebase.FirebaseException: Sign in with Facebook is not supported via this method; the Facebook TOS dictate that you must use the Facebook Android SDK for Facebook login.

Could anyone can help me ?
Thinks

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?Yse

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by paulinon** [comment]
Thanks for reporting this issue @fatmousemiyabi. I've noticed that you're using an old version of the Unity Editor. Could you try using the latest version of the editor then redo your build and see if the issue still occurs? If so, please share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I could isolate the cause of the issue.

**Comment by DellaBitta** [comment]
Hi @fatmousemiyabi ,

Facebook login is not one of the 3rd party providers that Firebase supports via SignInWithProvider. Please see our [Unity Facebook Login guide](https://firebase.google.com/docs/auth/unity/facebook-login) for information on how to authenticate with Facebook. Thanks!

**Comment by fatmousemiyabi** [comment]
@DellaBitta 
Ok~ Thank you~
