### ISSUE TITLE
Game Center teamPlayerID

### ISSUE THREAD

**Issue by voody2506** [firebase/quickstart-unity#586]
Hello, I want to use Unity Firebase Authentication with Game Center / Play Games id in my game. But at WWDC apple announced that standard GameCenterUsersID  is deprecated and developers should use 2 new variables to identify users:
1. gamePlayerID - unique id for the game.
2. teamPlayerID - unique id for all developer company games.

So in Unity 2020.1 Social.localUser.ID will return the TeamPlayerID instead of GameCenterUsersID on iOS 12 and above

My Questions: That's mean that if player starts my game with iOS 11 and update to iOS 13, Firebase Authentification can't math old and new ID's and creates new user.

Is there any solution to solve this?

**Comment by DellaBitta** [comment]
Hi @voody2506,

This issue doesn't fall into the domain of our Unity SDK but in how the backend handles authorization, so I contacted the Auth team. They said that while this is not a problem currently, it may become one in the future. 

Please reach out to [Firebase Support](https://firebase.google.com/support) directly and/or start a topic in the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk).

Thanks!

**Comment by voody2506** [comment]
> Hi @voody2506,
> 
> This issue doesn't fall into the domain of our Unity SDK but in how the backend handles authorization, so I contacted the Auth team. They said that while this is not a problem currently, it may become one in the future.
> 
> Please reach out to [Firebase Support](https://firebase.google.com/support) directly and/or start a topic in the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk).
> 
> Thanks!

Hello. No, it is very big problem. After Unity 2020.1 release standard Unity API method  
`Social.localUser.ID` will return the TeamPlayerID. 
That's mean that If developers upgrade to Unity 2020.1 and their game use Firebase Game Center Auth, players with IOS 12/ 13 will automatically lose their progress.

You can find more info at changelog
https://unity.cn/releases/beta/2020/2020.1.0a15
