### ISSUE TITLE
Crashlytics does not compile on ios xcode

### ISSUE THREAD

**Issue by Eggsterone** [firebase/quickstart-unity#589]
### Please fill in the following fields:
Unity editor version: 2018.4.14f1
Firebase Unity SDK version: 0.9.10
Firebase plugins in use (Auth, Database, etc.):Analytics, crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I have an issue with compiling the project. The error has a linking error. With crashlystics

And is giving a warning of the IOS deployment target is set to 7 but the range of supported targets 
Is 8.0 to 13.9. For both crashlytics pod and fabric pod

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by paulinon** [comment]
Thanks for reporting this @Eggsterone. You might be facing the issue talked about on this [community post](https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d). Try following along and see if it helps in resolving your issue.
