### ISSUE TITLE
ERROR: ret == 0 || ret == 22

### ISSUE THREAD

**Issue by karimsallam** [firebase/quickstart-unity#59]
When build a Unity iOS app and launching it I get this message in the console and Firebase database does not work property. (it works fine in the Unity editor).

```2017-02-17 11:16:44.503765 app[19583:3237749] ERROR: ret == 0 || ret == 22
ApplicationException: ret == 0 || ret == 22
  at Firebase.FutureBase.Status () [0x00000] in <filename unknown>:0 
  at Firebase.FutureString+<GetTask>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at Firebase.FutureString.SWIG_CompletionDispatcher (Int32 key) [0x00000] in <filename unknown>:0 
  at Firebase.AppUtil.PollCallbacks () [0x00000] in <filename unknown>:0 
 
(Filename: currently not available on il2cpp Line: -1)
```

Using Unity 5.5.1 and Firebase SDK 1.1.1

Any idea? I can't find a solution!

**Comment by karimsallam** [comment]
I was using Firebase Messaging 1.1.1 and an older version of Database... 
Working fine now

**Comment by karimsallam** [comment]
Maybe when you download the SDK from the website it could say which version it is? I got confused as I added messaging after a while and downloaded it again from the website but it was an updated version.

**Comment by stewartmiles** [comment]
The zip file filename contains the version number, were you after us
changing the download button to include the SDK revision?
https://firebase.google.com/docs/unity/setup

Cheers,
Stewart
