### ISSUE TITLE
403

### ISSUE THREAD

**Issue by AlexeyGodyaev** [firebase/quickstart-unity#592]
Non-fatal Exception: com.google.firebase.d: An internal error has occurred. [ <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/sendVerificationCode</code> from this server.  <ins>That’s all we know.</ins> ]
       at com.google.firebase.auth.api.internal.zzdv.zza(zzdv.java:18)
       at com.google.firebase.auth.api.internal.zzex.zza(zzex.java:3)
       at com.google.firebase.auth.api.internal.zzfa.run(zzfa.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by AlexeyGodyaev** [comment]
Device
Brand: Xiaomi Model: Mi A2 Orientation: Vertical Free RAM: 1.36 GB Free disk space: 2.32 GB operating system Version: 10 Orientation: Vertical Root Access: No Crash Date: Feb 17 2020, 23:50:00

Device
Brand: samsung Model: Galaxy J3 (2017) Orientation: Vertical Free RAM: 401.89 MB Free disk space: 580.48 MB operating system Version: 9 Orientation: Vertical Root Access: No Crash Date: Feb 17 2020, 20:29:00

Device
Brand: samsung Model: Galaxy A50 Orientation: Vertical Free RAM: 2.35 GB Free disk space: 95.8 GB operating system Version: 9 Orientation: Vertical Root Access: No Crash Date: Feb 17 2020, 00:32:00

**Comment by paulinon** [comment]
Thanks for reporting this, @AlexeyGodyaev. Could you share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project as well as the steps you've taken before encountering this issue? This way, I can try to reproduce the issue on my end and hopefully find a solution.
