### ISSUE TITLE
FirebaseAuth.DefaultInstance Freezing??

### ISSUE THREAD

**Issue by davoodkharmanzar** [firebase/quickstart-unity#593]
Unity 2019.x or 2020.x
SDK 6.x
.net 4.x
Editor / IL2CPP
Any platforms

**FirebaseAuth.DefaultInstance** or **FirebaseAuth.GetAuth(xx)** cause freezing if Editor or Built App did **not connected to internet** or had **not any network connection** [Firewall Blocking] ...

**Comment by paulinon** [comment]
Thanks for reporting this issue, @davoodkharmanzar. I'd like you to try some things on your end:
- Try using the quickstart with an updated version of the SDK to see if this issue persists. I tried using `FirebaseAuth.DefaultInstance` on my end, and neither the editor nor the build app froze.
- If you're experiencing blocking by your firewall, try whitelisting "www.googleapis.com"

If none of these worked, please send a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project so I could identify what's causing the issue.

**Comment by davoodkharmanzar** [comment]
1) **FirebaseAuth.DefaultInstance** cause this freeze too :]
2) i mean **firewall on client pc** and not google servers ...

P.S:
i'm using this method to initializing my FirebaseAPP without using any JSON file:
`Base = FirebaseApp.Create(AppOptions.LoadFromJsonConfig(JSONSTRING));`
`Account = FirebaseAuth.GetAuth(Base);`

i don't have any problem with initializing of database !!

**and in generally its working like a charm if had access to internet connection ...**

**Comment by patm1987** [comment]
Hi @davoodkharmanzar , thanks for your report.

It would really help us get to a resolution quickly if you could tell us if it's freezing in the [auth testapp](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp). If it isn't, can you tell us what to change in the testapp to reproduce your freeze.

I tried real quickly to just run the testapp with my networking turned off in the latest Unity editor (2019.3.2) and Firebase SDK (6.11.0), and other than the typical errors for not being online I didn't notice any issues (ie: the game didn't freeze).

It would also help if you can send us the logs of the issue (especially if you can reproduce it in the quickstart).

Thanks for your help!
--Patrick

**Comment by davoodkharmanzar** [comment]
@patm1987 

hi,

this is my code:

![Capture](https://user-images.githubusercontent.com/10723167/75226217-e34a5d80-5760-11ea-857c-6bdb4c268ec0.JPG)

so, what do you think?

**Comment by patm1987** [comment]
I can't reproduce on my own machine by changing `FirebaseAuth.DefaultInstance();` in the [test app](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) to `FirebaseAuth.GetAuth(FirebaseApp.DefaultInstance());`. The best thing you could do to help us debug this is to reproduce it in the [test app](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp) and tell us how you did it.

Another really helpful piece of information would be to share the Unity log at the time of the freeze. Preferably with the log level set to verbose:
```
FirebaseApp.LogLevel = LogLevel.Verbose;
```

Finally it would be super handy if you could get us a call stack at the point where Unity is freezing. I can't tell which IDE you're using, but most can attach to the Unity Editor now. If you could just get it to freeze, hit pause, and tell us what's happening it will be super helpful to see what exactly is going on.

Another thing that could help is letting us know what exactly freezing means. When this occurs in the editor, does the editor itself become unresponsive or does that Coroutine simply stop executing?

Sorry that I don't have an answer offhand, but if you can get a little more debug information we can probably work through this!

--Patrick

**Comment by davoodkharmanzar** [comment]
never mind ...
i decided to use database without authorization ...
and freezing is gone ...
