### ISSUE TITLE
[Question] Firebase plugins in UPM

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#597]
Hi!
Is there any intention, plan, roadmap, whatever to deliver firebase plugins via UPM?
I think it would have really advantages since we were using our own package manager and we saw the benefits of this way of delivery.

Thanks

**Comment by patm1987** [comment]
Hi @MartinGonzalez,

I love this idea!

Feel free to add any more comments about what did/didn't work with respect to your own custom package system or the [play services resolver](https://github.com/googlesamples/unity-jar-resolver).

--Patrick

**Comment by MartinGonzalez** [comment]
Basically we have to wrap firebase plugins sdks into our own upm implementation, so we can deliver every firebase sdk instead of importing it like a unitypackage.

To be clear about the dev process we have.
We create a package, containing for example only Firebase stuff and another package for play services resolver

So we can have 
Firebase Analytics@1.1.0 ---> Play Services resolver@1.0.0
                                          ---> SomeShareThings@1.0.0
Firebase Messaging@1.0.1 ---> Play Services resolver@1.0.0
                                             ---> SomeShareThings@1.0.0

The problem is that every Firebase plugin comes with stuff that is shared through plugin, I guess a Parse folder, and other stuff.
So we had to implement something that moves our package content to the project itself and everything that is equal is not being replaced. It's a bit like hack.
Having every firebase plugin as an UPM package would resolve a lot of things, and also everything is going to that delivery method.

What do you thing @patm1987 ? :D

**Comment by patm1987** [comment]
Thanks for that breakdown, I've shared it with the team. I definitely love the idea.

We'd probably have to support the old method still for Unity 5.x users, but I love the explicit versioning and dependency resolution.

**Comment by stopiccot** [comment]
Ability to use Firebase via UPM would be extremely useful

**Comment by patm1987** [comment]
I wanted to circle back and say, good news!
[Firebase SDK 6.13.0 added UPM support](https://firebase.google.com/support/release-notes/unity#version_6130_-_march_23_2020)
[See more info here](https://firebase.google.com/docs/unity/setup#add-sdks-upm)

**Comment by MartinGonzalez** [comment]
Nnnnnnnnnnnnnnnnnniiiiiiiiiiiiceeeeeeeeeeeeeeeeeeeeeeeeee!
