### ISSUE TITLE
ActivateFetched: Load values for next time not working

### ISSUE THREAD

**Issue by hlongvu** [firebase/quickstart-unity#599]
### Please fill in the following fields:
Unity editor version: 2019.2.14f1
Firebase Unity SDK version: 6.10.0
Firebase plugins in use (Auth, Database, etc.): RemoteConfig
Additional SDKs you are using (Facebook, AdMob, etc.): FacebookSDK, admob, onesignal
Platform you are using the Unity editor on (Mac, Windows, or Linux): Macos
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

I am working with Unity and calling ActivateFetched immediately after start to retrieve previous config [(Strategy #3: Load values for next time)](https://firebase.googleblog.com/2017/01/firebase-remote-config-loading.html). If this strategy is working correctly it will update value on the next start. But nothing changes. 

If I called ActivateFetched on Firebase Load complete callback, the value is updated correctly. I wonder if Unity Editor working with Strategy #3 or not? Are those remote configs saved somewhere on local storage that not working in Unity Editor?

**Comment by stewartmiles** [comment]
@hlongvu you need to call Fetch() to download the most recent values, then ActivateFetch() to apply those values to the configuration that is returned by the RemoteConfig API.

The remote config data in the editor / desktop is stored in a [FlexBuffer](https://github.com/firebase/firebase-cpp-sdk/blob/c6a326f52cbdd0247f020123ae1652911b30b0d9/remote_config/src/desktop/config_data.cc#L127) in [remote_config_data](https://github.com/firebase/firebase-cpp-sdk/blob/c6a326f52cbdd0247f020123ae1652911b30b0d9/remote_config/src/desktop/remote_config.cc#L30) file in the local working directory.
