### ISSUE TITLE
Win32Exception: ApplicationName='python',

### ISSUE THREAD

**Issue by echeg** [firebase/quickstart-unity#6]
SDK use [firebase_unity_sdk_1.0.0 ](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_1.0.0.zip)
Manual use https://firebase.google.com/docs/unity/setup

On 

> Setup for Android
> Add the SDK to your app
> 5. Add the google-services.json file to the project.
> Drag the google-services.json downloaded from the Firebase console into any folder in your project.

I have error:
Win32Exception: ApplicationName='python', CommandLine='"D:/testP/Firebase/analytics/testapp/Assets\..\Assets\Firebase\Editor\generate_xml_from_google_services_json.py" -i "Assets/FireBaseConfig/google-services.json" -l', CurrentDirectory='D:\testP\Firebase\analytics\testapp'
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start ()
(wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
GooglePlayServices.CommandLine.Run (System.String toolPath, System.String arguments, System.String workingDirectory, System.Collections.Generic.Dictionary`2 envVars, GooglePlayServices.IOHandler ioHandler)
Firebase.Editor.GenerateXmlFromGoogleServicesJson.RunResourceGenerator (System.String arguments, Boolean showCommandLine)
Firebase.Editor.GenerateXmlFromGoogleServicesJson.ReadBundleIds (System.String googleServicesFile)
Firebase.Editor.GenerateXmlFromGoogleServicesJson.CheckBundleId (System.String newBundleId, System.String googleServicesFile)
Firebase.Editor.GenerateXmlFromGoogleServicesJson.UpdateJson ()
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:222)

**Comment by stewartmiles** [comment]
Thanks for the bug report, we have an internal fix for this that we'll be
publishing shortly.  For the moment you'll need to install Python on your
Windows machine, this requirement will go away with our upcoming release.

**Comment by rad-ed** [comment]
You need to install python, and properly add it to your path, then restart unity before continuing.

**Comment by stewartmiles** [comment]
Hi everyone,

We've fixed this issue in the 1.0.1 release:
https://firebase.google.com/support/release-notes/unity#1.0.1

You can download the latest release from:
https://firebase.google.com/docs/unity/setup

Cheers,
Stewart
