### ISSUE TITLE
Il2CppExceptionWrapper

### ISSUE THREAD

**Issue by zhangjianshuai** [firebase/quickstart-unity#604]
Please fill in the following fields:

Unity editor version: 2017.4.30f1
Firebase Unity SDK version: 6.10.0
Firebase plugins in use (Auth, Database, etc.): Messaging , Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, google game,
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP):IL2Cpp
Please describe the issue here:
```
#0 Thread
Il2CppExceptionWrapper
(null)

amsw | il2cpp::vm::Exception::Raise(Il2CppException*, MethodInfo*) (Exception.cpp:38)
-- | --
1 amsw | _OUTLINED_FUNCTION_0 + 12
2 amsw | AppDomain_InternalSetContext_m139827955 (Bulk_mscorlib_2.cpp:24073)
3 amsw | FirebaseApp_InitializeCrashlyticsIfPresent_m1568632807 (Bulk_Firebase.App_0.cpp:0)
4 amsw | U3CRunU3Ec__AnonStorey0_1_U3CU3Em__0_m2970009708_gshared (Bulk_Generics_3.cpp:0)
5 amsw | ExceptionAggregator_Wrap_m2066008961 (Bulk_Firebase.Platform_0.cpp:6170)
6 amsw | Dispatcher_PollJobs_m1460709859 (Bulk_Firebase.Platform_0.cpp:0)
7 amsw | FirebaseHandler_Update_m3612919502 (Bulk_Firebase.Platform_0.cpp:7368)
8 amsw | RuntimeInvoker_Void_t1185182177 (Il2CppInvokerTable.cpp:138489)
9 amsw | il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) (Runtime.cpp:470)
10 amsw | scripting_method_invoke (ScriptingApi_Il2Cpp.cpp:216)
11 amsw | Invoke (ScriptingInvocation.cpp:329)
12 amsw | CallUpdateMethod (MonoBehaviour.cpp:552)
13 amsw | CommonUpdate<BehaviourManager> (Behaviour.cpp:176)
14 amsw | PlayerLoop (PlayerLoop.cpp:175)
15 amsw | UnityPlayerLoopImpl (LibEntryPoint.mm:243)
16 amsw | UnityRepaint (UnityAppController+Rendering.mm:270)
17 amsw | -[UnityAppController(Rendering) repaintDisplayLink] (UnityAppController+Rendering.mm:77)
18 QuartzCore | 0x00000002197da000 + 69720
19 QuartzCore | 0x00000002197da000 + 895436
20 CoreFoundation | ___CFMachPortPerform + 192
21 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 60
22 CoreFoundation | ___CFRunLoopDoSource1 + 444
23 CoreFoundation | ___CFRunLoopRun + 2088
24 CoreFoundation | CFRunLoopRunSpecific + 452
25 GraphicsServices | GSEventRunModal + 104
26 UIKitCore | UIApplicationMain + 216
27 amsw | main (main.mm:33)
28 libdyld.dylib | 0x0000000214ccb000 + 4128
```

###What's the issue repro rate? (eg 100%, 1/5 etc)
<img width="1114" alt="图片" src="https://user-images.githubusercontent.com/9998301/76275248-cf087380-62bd-11ea-8d99-e9ac94281c06.png">

this issuse also happened after i update firebase sdk for unity 6.10.0, according to those stack, the reason cannot be analyzed,  It may be related to firebase initialization, hope you can help me, thanks...

**Comment by zhangjianshuai** [comment]
We didn't use Crashlytics in our project

**Comment by jonsimantov** [comment]
Hmm, it's odd that InitializeCrashlyticsIfPresent is causing an issue even without Crashlytics being included.

Could you:
- Try updating to version 6.12.0 of the Firebase Unity SDK.
- If the problem persists, see if adding FirebaseCrashlytics to your project prevents the crash.
If adding Crashlytics fixes the issue then that points us to a problem with InitializeCrashlyticsIfPresent and we can take a look further.

Thanks!

**Comment by zhangjianshuai** [comment]
> ake sure that the old versions of Firebase plugins are all removed from the project, so you don't have conflicting versions.)

okay, i will try updating unity sdk, thanks

**Comment by zhangjianshuai** [comment]
Sorry to bother you again, I used the 6.12.0 Firebase SDK for Unity, but the android package log is
```
03-16 12:57:47.026  3774  3832 E Unity   : Unable to find FirebaseCppApp-6_10_0
03-16 12:57:47.088  3774  3832 E Unity   : [2020-03-16 12:57:47:085]=>The type initializer for 'Firebase.FirebaseApp' threw an exception.
```

@jonsimantov  Is there a problem with SDK access? I'm sure the SDK access is correct

**Comment by zhangjianshuai** [comment]
<img width="727" alt="图片" src="https://user-images.githubusercontent.com/9998301/76725961-c4048600-678a-11ea-90fa-2928c5ea3573.png">

**Comment by a-maurice** [comment]
Hi @zhangjianshuai 

Did updating the Unity SDK resolve your issue?

**Comment by zhangjianshuai** [comment]
> Hi @zhangjianshuai
> 
> Did updating the Unity SDK resolve your issue?

no it doesn't work

**Comment by chkuang-g** [comment]
Hi @zhangjianshuai 

Which Firebase version did you use before with no issue?
Also, which Firebase version did you upgrade but not resolve your issue?
