### ISSUE TITLE
ARM64 Build ???

### ISSUE THREAD

**Issue by davoodkharmanzar** [firebase/quickstart-unity#606]
hi,

does Firebase supports on android ARM64 [v8] ?
i can't find any libraries of that on v8 build !!

![Capture](https://user-images.githubusercontent.com/10723167/76394153-42e46380-6332-11ea-9320-e32d1620e0ed.PNG)

**Comment by jonsimantov** [comment]
Hi,

It looks like you need to run the resolver after changing the build target settings.
Choose **Assets > Play Services Resolver > Android Resolver > Resolve** from the Unity menu. If that doesn't work, you can Force Resolve to ensure it includes the correct library versions.

Please let me know if that works. Thanks!

**Comment by davoodkharmanzar** [comment]
thanks ...
its solved :]
