### ISSUE TITLE
Firebase does not work inside of my unity build for PC, but works fine in my editor

### ISSUE THREAD

**Issue by cs17wwt** [firebase/quickstart-unity#611]
### Please fill in the following fields:
Unity editor version: 2019.3.1f1
Firebase Unity SDK version: 6.11.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): desktop
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.) I built my application and attempted to use the same login information that I use inside of my unity editor to log in through the built application but it does not log me in. Furthermore, if attempt to sign up a new user, the user's details are not added to the authentication database either.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by a-maurice** [comment]
Hi,

I haven't had any luck reproducing this on my end.  Have you seen this with the quickstarts?  In the Build Settings, what options are you using?

Thanks

**Comment by cs17wwt** [comment]
This is the build settings I use for my app. I also was unsure what was implied by quick starts sorry Im fairly new to coding 
![image](https://user-images.githubusercontent.com/33100159/77230551-e8969e80-6b8c-11ea-8634-5b24e9304990.png)

**Comment by alexames** [comment]
Hi @cs17wwt, the quickstart is the project in this github repository. Can you try cloning this project and reproducing the issue? If you can isolate the specific lines of code where the issue is occuring with a minimal reproduction case we can have a look, but we don't have enough information about your project to effectively diagnose the issue.
