### ISSUE TITLE
Launch App using URL, but OpenUrl Not Called when app is background

### ISSUE THREAD

**Issue by devauk** [firebase/quickstart-unity#612]
Unity editor version: 2018.3.13
Firebase Unity SDK version: 5.7.0
Firebase plugins in use : Messaging
Additional SDKs : Branch, DeltaDNA, Localytics, Singular
Platform you using the Unity editor : Mac
Platform you are targeting : iOS
Scripting Runtime : IL2CPP

After integrating Firebase the following UIApplicationDelegate callback is not getting called when the app is in background.

- (BOOL)application:(UIApplication *)app 
            openURL:(NSURL *)url 
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options;

I tried by adding "FirebaseAppDelegateProxyEnabled" to "NO" on info.plist but I am still having this problem.

**Comment by a-maurice** [comment]
Hi @devauk 

I believe this issue was resolved in version 6.1.0.  I'd recommend upgrading the version of the SDK you are using to at least that, though unless there is a specific reason not to, the latest version would be ideal.
