### ISSUE TITLE
IOS testflight crash

### ISSUE THREAD

**Issue by marad747** [firebase/quickstart-unity#613]
### Please fill in the following fields:
Unity editor version: Unity 2019.2.12
Firebase Unity SDK version: 6.9.0, now i trying update to 6.12.0 but i thing experiment will fail
Firebase plugins in use (Auth, Database, etc.): Analitycs\Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): no
Platform you are using the Unity editor on (Mac, Windows, or Linux):  MAC
Platform you are targeting (iOS, Android, and/or desktop): IOS 13,3,1, xcode 100% updated
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP
 
when i make build and run from my xcode to my phone - all fine. But when i export to testflight and download app - i have instantly crash. Help pls. Crash log attached 
[wowbox-2020-03-17-112156.ips.txt](https://github.com/firebase/quickstart-unity/files/4342565/wowbox-2020-03-17-112156.ips.txt)

**Comment by a-maurice** [comment]
Hi @marad747 

I'm not sure what your problem could be, and the crash log doesn't seem to have anything related to Firebase called out.  Were you able to reproduce this with the quickstart samples?

**Comment by marad747** [comment]
> Hi @marad747
> 
> I'm not sure what your problem could be, and the crash log doesn't seem to have anything related to Firebase called out. Were you able to reproduce this with the quickstart samples?

I solved my issue, but its very strange, i dont use ANY ads in my project, but after importing firebase my app crash because i dont set ads id in info file

**Comment by alexames** [comment]
That's very strange. From the looks of the crash log, it seems entirely unrelated to firebase, so setting an ads ID in your info file shouldn't make a difference. Are you sure that was the only thing you changed between when it worked and when it didn't? Were you able to reproduce the issue in the quickstart testapp?

**Comment by marad747** [comment]
> That's very strange. From the looks of the crash log, it seems entirely unrelated to firebase, so setting an ads ID in your info file shouldn't make a difference. Are you sure that was the only thing you changed between when it worked and when it didn't? Were you able to reproduce the issue in the quickstart testapp?

Are you sure that was the only thing you changed between when it worked and when it didn't? - yes
Were you able to reproduce the issue in the quickstart testapp? - i cant load to testflight quickstart

**Comment by alexames** [comment]
Hi, sorry for the delayed response. What do you mean when you say you can't load the testflight quickstart? I'm referring to the code in this repository, are you not able to clone it and then open the Unity Project? If you can follow the instructions in the readme file in this repo and it still doesn't work it will be easier to diagnose what's going on.
