### ISSUE TITLE
ios missing push

### ISSUE THREAD

**Issue by marad747** [firebase/quickstart-unity#615]
### Please fill in the following fields:
Unity editor version: Unity 2019.2.12
Firebase Unity SDK version:  6.9.0
Firebase plugins in use (Auth, Database, etc.): Analytic + Messaging
Additional SDKs you are using (Facebook, AdMob, etc.):  no
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop):  IOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP
I made ios build, load to testflight and push notification dont work on ios devices, whaen i made mistake? android FINE
![image](https://user-images.githubusercontent.com/20600166/77096147-9718d300-6a17-11ea-84e7-edd7980abb59.png)
![image](https://user-images.githubusercontent.com/20600166/77096230-b57ece80-6a17-11ea-8bd4-6e236a16a684.png)

**Comment by alexames** [comment]
Hi @marad747, based on the info you've given here I don't see any obvious issues. Try double checking the instructions in the readme file to make sure you didn't miss anything. Verify that your Google-Service.plist file has all the correct data in it, and that it's being properly included in your project. If you still can't get it working, try reproducing the issue in the quickstart app. If you still get the issue there it should be easier to track down. And if you don't, then we can see what you're doing differently.
