### ISSUE TITLE
Permission READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by giangnb-dev** [firebase/quickstart-unity#616]
I added Firebase Crashlytics for crash tracking and upgraded the firebase version to 6.12 in the project. After the upgrade, I checked the permissions in the AndroidManifest file including ACCESS_NETWORK_STATE, INTERNET, WRITE_EXTERNAL_STORAGE. 
But when building and pushing to google play and get a warning with READ_EXTERNAL_STORAGE access. Moreover, my game opened up asking for photo and media access. So must firebase add access itself?

**Comment by alexames** [comment]
READ_EXTERNAL_STORAGE is implied by WRITE_EXTERNAL_STORAGE. 

> Moreover, my game opened up asking for photo and media access. So must firebase add access itself?

I believe that is the expected behavior when you have the WRITE_EXTERNAL_STORAGE permission.
