### ISSUE TITLE
Every code change creates lag in Unity

### ISSUE THREAD

**Issue by JPhilipp** [firebase/quickstart-unity#617]
**Background:** I'm using the latest stable Unity (2019.3.0f6) along with the Firebase version recommended by the instructions (6.12.0) on Windows 10. I mostly don't have any code, really (just a semi-empty `FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(...)` for testing), and only imported the Analytics package (and later, the Firestore package, but below described issue appeared before). I only created a single Firestore database with a single collection with 1 document and 3 fields for testing. The Firebase Analytics dashboard shows my 1 user in the last 30 minutes successfully tracked. My tested Unity target platforms are PC or Android, the issue below prevails on both. My .Net is 4.0.

**Issue:** Now, whenever I make a code change (say, add `print("Hello world");`) in VS Code, and switch back to Unity, it takes me something like 3 seconds to be able to click into any interface again, like select a project asset, click into the hierarchy, or hit Play. I've never experienced this type of delay in my years of working with Unity, so I'm confused, and as I make frequent changes, this really slows things down. (The lag only occurs when there's no errors; a potential syntax error is instantly logged to the console when switching to Unity.)

My issue seems somewhat similar to [this older closed issue](https://github.com/firebase/quickstart-unity/issues/442).

I tried restarting Unity to no avail; ever after a restart, and without yet having run any code (like the Firebase initing), the issue appears. Help please? Thanks!

**Comment by alexames** [comment]
Do you see this issue when you remove the firebase initialization? Does it happen when you just import App but not Analytics? Do you experience this when running the quickstart testapps?

**Comment by kirilogan** [comment]
I'm experience this same issue. The freeze lasts anywhere between 10-20 seconds.

**Comment by JPhilipp** [comment]
> Also, what platform do you have selected in the Build Settings menu?

As mentioned, my tested Unity target platforms were both PC and Android, and the issue was seen on both. Sorry for not yet having found the time to answer all other questions.

**Comment by patm1987** [comment]
As a note, this issue sounds very similar to https://github.com/firebase/quickstart-unity/issues/639
If you continue to experience longer startup times when debugging in the Unity editor, especially on Windows, feel free to join in the discussion there.
