### ISSUE TITLE
Firebase does not correctly identify the .json file

### ISSUE THREAD

**Issue by mizaelmontengro** [firebase/quickstart-unity#620]
Unity editor version: 2019.3.5f1
Firebase Unity SDK version: 6.13.0
Firebase plugins in use (Auth, Database, etc.): Invite
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP .NET 4.x

I imported firebase for my project, put google-services.json in the Assets folder, however when I open Firebase in Window -> FireBase -> Documentation, I get the following error:

"
Project Bundle ID br.com.tretastudio does not match any bundle IDs in your google-services.json files.
This will result in an app that will fail to initialize.

Available Bundle IDs:

You need to either:
* Fix your app's bundle ID under "Player Settings --> Bundle Identifier"
or:
* Add another app to your firebase project
  Goto https://firebase.google.com/docs/unity/setup#add_firebase_to_your_app_1
  and add the new configuration file to your project.
"

I'm sure the name of the package is correct with what I inserted in the project. What could be wrong?

**Comment by mizaelmontengro** [comment]
You're wrong bot, all the information requested in the template is there

**Comment by alexames** [comment]
Without looking at your project directly, it's hard to diagnose what the issue might be. What bundle ID is displayed in Player Settings -> Bundle Identifier?

Have you tried reproducing the issue with the quickstart testapp in this repo?

**Comment by dbidwell94** [comment]
I just wanted to point out that I am having the same issue

" Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly."

I have tried both things. I have google-services.json in my Assets folder, AND I have tried explicitly setting the FirebaseApp.defaultInstance.options manually. No joy. Nothing works. Works perfectly for Desktop and in the Editor. But I am noticing that Firebase is not requesting Internet permissions on my Android device so maybe that is the issue. Either way, Firebase is broken for Android for the moment

**Comment by dbidwell94** [comment]
![image](https://user-images.githubusercontent.com/25497078/78205842-1368d880-7452-11ea-8ee4-af17128fa04e.png)

**Comment by dbidwell94** [comment]
![image](https://user-images.githubusercontent.com/25497078/78206165-f54fa800-7452-11ea-98f8-43ffe6f92de3.png)
^Firebase^
Also note my package names are correct
 
![image](https://user-images.githubusercontent.com/25497078/78206201-0dbfc280-7453-11ea-8569-cc5c79bdbe72.png)

^Unity^

**Comment by dbidwell94** [comment]
Update:

I was previously using the Unity 2020 Beta. I have completely downgraded to Unity 2019 latest stable version and Firebase connects without any issues. You guys might want to take a look at Unity 2020 for when it gets released. Cheers!

**Comment by mizaelmontengro** [comment]
I ended up giving up using Firebase, many integration problems with other libraries.
