### ISSUE TITLE
No API for sending a message to a specific device?

### ISSUE THREAD

**Issue by ltomov** [firebase/quickstart-unity#624]
Hi, I'm trying to send a push message to a specific device by using the device's FCM token.

I can do this from my server by sending a POST request to https://fcm.googleapis.com/fcm/send, but I see the Unity API can only send to topics, groups and send upstream messages.

I'm wondering whether this is a limitation that will be fixed in a future version, or is this the expected behaviour? Should we only send to devices using a POST request and the server key?

Thanks!

**Comment by alexames** [comment]
Sending to specific devices using tokens is supported. 

https://firebase.google.com/docs/cloud-messaging/http-server-ref#send-downstream

You fill out the 'to' field with the token you want to send to. For example, something like this should work:

```
curl -X POST \
    --header "Authorization: key=<SERVER_KEY>" \
    --header "Content-Type: application/json" \
    https://fcm.googleapis.com/fcm/send \
    -d '{"to":"<FCM_TOKEN>","notification":{"body":"Hello, World!"}'
```

**Comment by ltomov** [comment]
Thanks, that works yes, this is how I do it currently. However this way you need to provide the server key and I didn't want to embed it inside the Unity app.
But I guess I can route it through a backend server and send the POST request from there.

**Comment by alexames** [comment]
Ah, I misunderstood. You are correct, there is no device-to-device message functionality in FCM. You would need to send the message down from the server somehow.

**Comment by ltomov** [comment]
Got it, thank you!
