### ISSUE TITLE
"One or more Firebase dependencies are not present"

### ISSUE THREAD

**Issue by shiroto** [firebase/quickstart-unity#63]
Hi! I am tried to run the quickstart database sample, and it works fine in the editor. But when I try and make a build and put it on my android phone, I get that message: "One or more Firebase dependencies are not present. Current dependency status: UnavailableOther"
I have done everything according to the guide. I have a similar issue when making a new project from scratch and trying to use the database functions. I have posted that here: http://answers.unity3d.com/questions/1319720/firebase-typeinitializationexceptiondllnotfoundexc.html
I assume these two are related. So maybe someone here knows what is going wrong?

**Comment by shiroto** [comment]
Found the issue. I just had to press "Resolve Client Jars" and it works. Why is that not in the guide?

**Comment by stewartmiles** [comment]
Auto resolution is enabled by default, so it's typically not required.
Perhaps you turned off auto resolution?

**Comment by shiroto** [comment]
I figured as much, but it was turned off for me. I don't know why. I wasn't in that menu, I didn't even know it existed until someone pointed it out to me.

**Comment by stewartmiles** [comment]
Well that is really odd, perhaps you've used the Google Play Games plugin
in the past which uses the same - though older - common component and that
had it turned off?

I'm glad this resolved the issue.

Cheers,
Stewart
