### ISSUE TITLE
How to download an old version?

### ISSUE THREAD

**Issue by game-libgdx-unity** [firebase/quickstart-unity#633]
When I open https://firebase.google.com/download/unity it automically download the latest version.
Thanks!

**Comment by davoodkharmanzar** [comment]
https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_**x**.**yy**.**z**.zip

for example:
https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_6.13.0.zip

**Comment by chkuang-g** [comment]
@davoodkharmanzar Thanks for the reply.  This is correct.

@game-libgdx-unity Does this work for you?

**Comment by game-libgdx-unity** [comment]
yes, thanks a lot
