### ISSUE TITLE
Firebase not working after unity build in mobile

### ISSUE THREAD

**Issue by aqmalarfi** [firebase/quickstart-unity#641]
Please fill in the following fields:
Unity editor version: 2020.1.0.b4
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager):.unitypackage
Firebase plugins in use (Auth, Database, etc.): FirebaseDatabase.unitypackage
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Tried both

My Error is :

Firebase.InitializationException: Firebase app creation failed. at Firebase.FirebaseApp.CreateAndTrack (Firebase.FirebaseApp+CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) [0x000e3] in <1be6193be3e248d495eb52dc2920675d>:0 at Firebase.FirebaseApp.Create () [0x00027] in <1be6193be3e248d495eb52dc2920675d>:0 at Firebase.FirebaseApp.get_DefaultInstance () [0x00017] in <1be6193be3e248d495eb52dc2920675d>:0 at Home.Start () [0x0000a] in :0

Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes, the exact same thing happens here, and it feels worse.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by davoodkharmanzar** [comment]
hi,
did you tried to **Resolve** or **Force resolve** of Android dependencies??
i had this problem on ARM64 => https://github.com/firebase/quickstart-unity/issues/606

**Comment by minutd97** [comment]
Hello guys, not sure if it is the same issue as this one https://github.com/firebase/quickstart-unity/issues/596 but i managed to solve it by removing ExternalDependencyManager that was installed with the package and installed it seperatlly from this link : 

https://github.com/googlesamples/unity-jar-resolver/raw/master/external-dependency-manager-latest.unitypackage 

... and it actually worked, also after updating to this one there are no errors in the editor regarding editor stuff, i'm using Unity 2019.3.6f1, maybe this helps 👍

**Comment by patm1987** [comment]
@aqmalarfi ,

Does @minutd97 's solution work for you? Do you only experience the issue in the 2020 beta?

I've tried to repro it on my side without success, so any other information you have would be appreciated including the code where you're experiencing the issue (was it just the Database quickstart without any modifications?) and a full editor log if you're comfortable sharing it:
![image](https://user-images.githubusercontent.com/1111611/79278961-24f6ab00-7e6a-11ea-88d7-0ead93453522.png)

Thanks,
--Patrick

**Comment by ctykaya** [comment]
Same error for me 
Unity editor version: 2020.3.9.f1
Firebase Unity SDK version: 6.13.0
Firebase plugins in use (Auth, Database, etc.): FirebaseDatabase.unitypackage and Auth.unitypackage
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac Catalina
Platform you are targeting (iOS, Android, and/or desktop): Standalone Windows x86_64 but works fine on Mac build
Scripting Runtime (Mono, and/or IL2CPP): Tried Mono

I also tired @minutd97 solution but it doesn't help.  When I build for Windows and copy the build folder on windows the folder copied as read only. It works fine in Unity Personel License but when I buy Plus lincense this error occurs.  Could you please help ?

**Comment by SbbenjaminSanchez** [comment]
Hi, I have the same problem.

**Comment by patm1987** [comment]
Since this thread is locked and this last comment _seems_ different from the ones above - if you're still having an issue @SbbenjaminSanchez, please open a new issue and we'll be glad to take a look!
