### ISSUE TITLE
Crashlytics doesn't record crashes

### ISSUE THREAD

**Issue by roointan** [firebase/quickstart-unity#642]
### Please fill in the following fields:
Unity editor version: 2019.2.18f1
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Crashlytics, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook and Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android and iOS (mostly testing on Android)
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I tried to implement Crashlytics, I verified output, and libs are in the APK and other files.
But Crashlytics does not record Exceptions.
This is the logcat filtered by "Crashlytics":
```
2020-04-13 16:08:23.835 20191-20191/? I/CrashlyticsCore: Initializing Crashlytics 2.6.8.32
2020-04-13 16:08:23.855 20191-20191/? I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
2020-04-13 16:08:24.105 20191-20225/? V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
2020-04-13 16:08:28.132 20191-20265/com.gamovation.quickcheckers D/firebase: crashlytics app initializer Disabling
2020-04-13 16:08:28.161 20191-20265/com.gamovation.quickcheckers I/Unity: crashlytics app initializer Disabling
2020-04-13 16:08:28.736 20191-20191/com.gamovation.quickcheckers V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
2020-04-13 16:08:28.744 20191-20349/com.gamovation.quickcheckers D/firebase: crashlytics app initializer Disabling
2020-04-13 16:08:28.756 20191-20265/com.gamovation.quickcheckers I/Unity: crashlytics app initializer Disabling
2020-04-13 16:08:29.019 20191-20349/com.gamovation.quickcheckers I/Unity: Crashlytics inited!!!
```
firebase log level is Firebase.LogLevel.Debug
and I myself put "Crashlytics inited!!!" log inside the task run after CheckAndFixDependenciesAsync.
I tried Firebase Unity quickstarts, and it works with no problem.
Please note that I had these issues: 
https://github.com/firebase/quickstart-unity/issues/622
https://github.com/firebase/quickstart-unity/issues/619
So I had to disable Custom Gradle Template to make a build.
I don't see any logs in Firebase console, and no logcat logs for exception being recorded and no uploading of file after restart (unlike the quickstarts project)
Also please note that Firebase analytics works correctly in the same project.
I Also tried Force Resolve, but no change in runtime behaviour.

Update:
I receive logs in the console if I use Crashlytics.LogException(), 
but it doesn't automatically record exceptions.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? no. I tried that quickstart project and it works correctly.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by patm1987** [comment]
Hi @roointan ,

Thanks for reaching out. Unfortunately, it's really hard for us to help without solid repro steps (which is why we ask you to try to reproduce this on our quickstart project).

Can you try to figure out what is different between the quickstart and your own project? For example, when you say that nothing is logging after `CheckAndFixDependenciesAsync` my first suggestion might be to ensure that you're using `ContinueWithOnMainThread` instead of `ContinueWith`.

Another thing to check is that you're doing something like what `InitializeFirebase` is doing in the Crashlytics test app: https://github.com/firebase/quickstart-unity/blob/master/crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandler.cs

That `var app = FirebaseApp.DefaultInstance` is doing a bit of extra work by lazily initializing the Firebase singleton.

Let me know if any of that helps!

--Patrick

**Comment by roointan** [comment]
We thought having non-fatal crashes recorded is a good option, so we released an update with Crashlytics to production.
Interestingly it does record fatal crashes, and out of surprise my test crash appeared a while later! 
I hadn't even noticed it first, because for a while we had production crash logs, but not that tes one in the list. but now I see it among other logs.
Thanks for the help.
