### ISSUE TITLE
cant receive fcm token on some android devices

### ISSUE THREAD

**Issue by Jason-Zy** [firebase/quickstart-unity#646]
part of my register code:
Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
				{
					var status = task.Result;
					Debug.Log(" Firebase.FirebaseApp.CheckDependenciesAsync():" + status);
					if (status == Firebase.DependencyStatus.Available)
					{
						Firebase.Messaging.FirebaseMessaging.TokenReceived -= _onTokenReceived;
						Firebase.Messaging.FirebaseMessaging.TokenReceived += _onTokenReceived;

						Firebase.Messaging.FirebaseMessaging.MessageReceived -= _onMessageReceived;
						Firebase.Messaging.FirebaseMessaging.MessageReceived += _onMessageReceived;
					}
					else
					{
						Debug.LogError(
						  "Could not resolve all Firebase dependencies: " + dependencyStatus);
					}
				});

callback code:
private void _onTokenReceived(object sender, Firebase.Messaging.TokenReceivedEventArgs token)
    {
        if (token != null && !string.IsNullOrEmpty(token.Token))
        {
            Debug.Log("Received firebase registration token:" + token.Token);
            m_sFCMToken = token.Token;
            ReportFCMTokenToServer();
        }
        else
        {
            Debug.LogError("firebase token is invalid");
        }
    }

log:
![image](https://user-images.githubusercontent.com/26757867/79319925-90f51400-7f3b-11ea-8ca8-0a65ac48b932.png)

i never receive the token on some android devices such as Nexus6 and Pixel2,  but it performs good on some other devices such as MI8 and  Huawei mate 30 and so on. All of these devices had installed google framework ,google play store and play games app, our unity game is released in google play store. we need help. our unity version is 2019.1.14, and firebase sdk version is 5.4.3

**Comment by patm1987** [comment]
Hi @Jason-Zy ,

It would really help us track down this bug if you filled out the issue template:

> ### Please fill in the following fields:
> Unity editor version: 
> Firebase Unity SDK version: 
> Source you installed the SDK (.unitypackage or Unity Package Manager):
> Firebase plugins in use (Auth, Database, etc.):
> Additional SDKs you are using (Facebook, AdMob, etc.): 
> Platform you are using the Unity editor on (Mac, Windows, or Linux): 
> Platform you are targeting (iOS, Android, and/or desktop): 
> Scripting Runtime (Mono, and/or IL2CPP):
> 
> ### Please describe the issue here:
> (Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
> 
> ### Please answer the following, if applicable:
> Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
> 
> What's the issue repro rate? (eg 100%, 1/5 etc)

 I don't mean to sound super pedantic, but by giving us this information about your build environment and by giving us repro steps on the quickstart projects you really help the team zero in on the underlying issue.

**Comment by katowulf** [comment]
Unity quickstart repo is not the best place to troubleshoot FCM message delivery. See [understanding message delivery](https://firebase.google.com/docs/cloud-messaging/understand-delivery) and if you need help from there, [reach out to support](http://firebase.google.com/support).

**Comment by Jason-Zy** [comment]
thank you for replication!
Unity editor version:2019.1.14f1
Firebase Unity SDK version:5.4.3
Source you installed the SDK (.unitypackage or Unity Package Manager): FirebaseMessaging.unitypackage
Firebase plugins in use (Auth, Database, etc.):we only imported FirebaseMessaging.unitypackage
Additional SDKs you are using (Facebook, AdMob, etc.): we use facebook sdk7.17.2(https://developers.facebook.com/docs/unity),&nbsp; google play games sdk9.50(https://github.com/playgameservices/play-games-plugin-for-unity) twitter sdk (https://github.com/twitter-archive/twitter-kit-unity) and appsflyer sdk(https://support.appsflyer.com/hc/zh-cn/articles/213766183-AppsFlyer-SDK-%E5%AF%B9%E6%8E%A5-Unity) IM Chat sdk(https://dev.yunxin.163.com/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/Unity%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E9%9B%86%E6%88%90%E6%96%B9%E5%BC%8F) and&nbsp; some others small&nbsp;
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Patrick"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 凌晨1:03
收件人:&nbsp;"firebase/quickstart-unity"<quickstart-unity@noreply.github.com&gt;;
抄送:&nbsp;"JasonZy"<991700966@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [firebase/quickstart-unity] cant receive fcm token on some android devices (#646)





 
Hi @Jason-Zy ,
 
It would really help us track down this bug if you filled out the issue template:
  
Please fill in the following fields:
 
Unity editor version:
 Firebase Unity SDK version:
 Source you installed the SDK (.unitypackage or Unity Package Manager):
 Firebase plugins in use (Auth, Database, etc.):
 Additional SDKs you are using (Facebook, AdMob, etc.):
 Platform you are using the Unity editor on (Mac, Windows, or Linux):
 Platform you are targeting (iOS, Android, and/or desktop):
 Scripting Runtime (Mono, and/or IL2CPP):
 
Please describe the issue here:
 
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
 
Please answer the following, if applicable:
 
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
 
What's the issue repro rate? (eg 100%, 1/5 etc)
  
I don't mean to sound super pedantic, but by giving us this information about your build environment and by giving us repro steps on the quickstart projects you really help the team zero in on the underlying issue.
