### ISSUE TITLE
External Dependency Manager for Unity doesn't work on Unity 2019.3+ with Firebase 6.13.0

### ISSUE THREAD

**Issue by novavision** [firebase/quickstart-unity#647]
### Please fill in the following fields:
Unity editor version: 2019.3+
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Messaging, Analytics, Crashalytics
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android/iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
After installing any Firebase package using Package Manager editor fills up with an exceptions:
`Expected mapping key to be a sequence, actually a scalar
Assertion failed on expression: 'IsSequence()'
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Google.VersionHandler.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: Assets/ExternalDependencyManager/Editor/Google.VersionHandler.dll, /Users/Romaha/Desktop/Test/Library/PackageCache/com.google.external-dependency-manager@1.2.144/ExternalDependencyManager/Editor/Google.VersionHandler.dll
UnityEditor.Scripting.ScriptCompilation.EditorBuildRules.CreateTargetAssemblies (System.Collections.Generic.IEnumerable`1[T] customScriptAssemblies, System.Collections.Generic.IEnumerable`1[T] precompiledAssemblies) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorBuildRules.cs:275)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.UpdateCustomTargetAssemblies (System.Boolean forceUpdateAssetMetadata) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:834)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.SetAllCustomScriptAssemblyJsonContents (System.String[] paths, System.String[] contents, System.String[] guids) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:1173)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.SetAllCustomScriptAssemblyJsonContents (System.String[] allAssemblyJsonPaths, System.String[] allAssemblyJsonContents, System.String[] guids) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:259)`

[screenshot](https://take.ms/D040X)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Didn't try, but I use an empty project and followed instructions for External Dependency Manager for Unity (EDM4U) [usage](https://firebase.google.com/docs/unity/setup?authuser=0)

What's the issue repro rate? 100%

**Comment by RadekMikulkaAG** [comment]
you have multiple "Google.VersionHandler.dll" in project - just search "Google.VersionHandler" and remove duplicity in "Assets" folder - if you want to use dependency manager from package manager you have to remove folder with previous resolver (folder is called "PlayServicesResolver" by default and is right in root folder)

**Comment by patm1987** [comment]
Thanks @novavision and @RadekMikulkaAG ,

looking at the callstack, this appears to be the issue. Definitely make sure you don't have an `Assets/PlayServicesResolver` and also check for `Assets/ExternalDependencyManager`. Since it looks like you used the [Unity Package Manager integration](https://firebase.google.com/docs/unity/setup#add-sdks-upm), make sure you followed the instructions there.

Specifically:
> EDM4U provides a tool to uninstall managed packages which is accessible using the Assets > External Dependency Manager > Version Handler > Uninstall Managed Packages menu option. Select all Firebase SDKs as well as External Dependency Manager and click Uninstall Selected Packages.

let us know if this helps!

**Comment by novavision** [comment]
> you have multiple "Google.VersionHandler.dll" in project - just search "Google.VersionHandler" and remove duplicity in "Assets" folder - if you want to use dependency manager from package manager you have to remove folder with previous resolver (folder is called "PlayServicesResolver" by default and is right in root folder)

Did you try your approach? That doesn't work
[screenshot](https://take.ms/Gg5fS)

**Comment by novavision** [comment]
> Thanks @novavision and @RadekMikulkaAG ,
> 
> looking at the callstack, this appears to be the issue. Definitely make sure you don't have an `Assets/PlayServicesResolver` and also check for `Assets/ExternalDependencyManager`. Since it looks like you used the [Unity Package Manager integration](https://firebase.google.com/docs/unity/setup#add-sdks-upm), make sure you followed the instructions there.
> 
> Specifically:
> 
> > EDM4U provides a tool to uninstall managed packages which is accessible using the Assets > External Dependency Manager > Version Handler > Uninstall Managed Packages menu option. Select all Firebase SDKs as well as External Dependency Manager and click Uninstall Selected Packages.
> 
> let us know if this helps!

You didn't tell me anything new what I didn't see in installation instruction. This is 100% reproducible by a steps I provided before on a clean Unity 2019.3 project.

Moreover, I wonder how much Firebase crookedly implements package installation. In your documentation, not a word is written that you need to delete something from the folder after installing packages from the package manager. Every time I come across a requirement to install Firebase in the project, I am 100% sure that I will have to go through 7 circles of hell to do this.
Before writing general and meaningless answers that are of no value, take it and try to do it yourself on your devices - all the steps have already been described, but just in case, if you don’t see the text in my first message, I give an example again:

1. Install Unity 2019.3.9f1 (but I also had it on other 2019.3 versions)
2. Install External Dependency Manager for Unity (EDM4U). At this step just after installation when Unity Package Manager Resolver window appears I already see this error:
`Stopped polling job due to exception: System.ArgumentException: The specified path is not of a legal form (empty).
  at System.IO.Path.InsecureGetFullPath (System.String path) [0x00025] in <437ba245d8404784b9fbab9b439ac908>:0 
  at System.IO.Path.GetFullPath (System.String path) [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0 
  at Google.VersionHandlerImpl.get_EnabledEditorDllsLoaded () [0x0001c] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/VersionHandlerImpl.cs:2353 
  at Google.VersionHandlerImpl+<NotifyWhenCompliationComplete>c__AnonStorey6.<>m__10 () [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/VersionHandlerImpl.cs:2386 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:412)
Google.RunOnMainThread:<ExecuteAllUnnested>m__B() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)
`
After installing and adding registries I don't see any Firebase package available in Package Manager. To see it I need to restart Unity.
3. Install Firebase Cloud Messaging package from Package Manager. The error I mentioned above appears.
Watch this [screenshot](https://take.ms/brmvb) to check all the packages I got in sample project

**Comment by seansaleh** [comment]
The installation instructions are quite unclear.
Here's a diff showing exactly what you need to change in your project to add Firebase Crashlytics (should be easy to adapt to add more dependencies)
https://github.com/seansaleh/quickstart-unity/compare/4b94b072f8fd07b5bd379e9356b87723086ee827...seansaleh:e943f50c550e5bba08b341520c7b711f2d413bff

All you really need to do to add the SDKs is add the following to `Packages/manifest.json`:
```
 "scopedRegistries": [
    {
      "name": "Game Package Registry by Google",
      "url": "https://unityregistry-pa.googleapis.com",
      "scopes": [
        "com.google"
      ]
    }
  ]
```
Then you follow the [official instructions ](https://firebase.google.com/docs/unity/setup#add-sdks) of:

> Install Firebase Unity SDK components using the Unity Package Manager by selecting **Window > Package Manager** and searching for Firebase. Firebase Unity SDK components can be installed, ugpraded and removed through this interface.

The installation instructions could really do with a rewrite to make it clearer, or a better installation method should be written which just has you update the `Packages/manifest.json` instead of adding a package which simply updates `Packages/manifest.json` then requires you to manually remove that package >.<

**Comment by novavision** [comment]
> All you really need to do to add the SDKs is add the following to Packages/manifest.json
In a fact this entry automatically appears after external-dependency-manager installation, but if I understood you correctly, I had to remove
`"com.google.external-dependency-manager": "1.2.152",`
from the `manifest.json`. That did a trick, but anyway, I get the same errors I mentioned above just after installing any Firebase package. The good thing is that I can ignore these errors and I can use Firebase packages finally.
Do you have these error as well?

**Comment by seansaleh** [comment]
I do not have any warnings. As you can see and verify yourself by looking at this fork of this quickstart-unity project https://github.com/seansaleh/quickstart-unity/tree/e943f50c550e5bba08b341520c7b711f2d413bff/crashlytics/testapp 
Notice, unlike in your screenshots there is no `Assets/Plugins` folder

There are no google related binaries checked in, they are fully managed via the package manager, and there is no `com.google.external-dependency-manager` in the package manager, only `com.google.firebase.crashlytics`

**Comment by novavision** [comment]
@seansaleh after making the changes you provided above I also didn't have any `Assets/Plugins` folder anymore, but still have these errors. Are you on Mac also?

**Comment by seansaleh** [comment]
No, I am not on Mac when looking at warnings.
Do you get the warnings when using my fork of the quickstart repo? https://github.com/seansaleh/quickstart-unity/tree/master/crashlytics/testapp

If so that's a clearly reproducible bug which you can get Google to fix.

**Comment by novavision** [comment]
@seansaleh I can't understand how sample project targeted to EditorVersion: 5.4.1f1 can help to solve the issue related to Package Manager introduced in Unity 2017? Importing any of the sample project I have to import EDM4U > add dependencies > install the Firebase package. The `Assets/Firebase` will be just removed. Does it make sense at all?

**Comment by seansaleh** [comment]
For the crashlytics project my fork is updated to 2019.3 :) https://github.com/seansaleh/quickstart-unity/tree/master/crashlytics/testapp

**Comment by novavision** [comment]
@seansaleh tried crashlytics, got absolutely the same errors on project import

**Comment by DellaBitta** [comment]
Hi @novavision,

I tried to reproduce this but unfortunately I could not.  I put all of my steps down below.  Could you let me know where your results diverge?

**Load the Quickstart**

- Open a fresh quickstart project.
- If prompted, Upgrade Asset Database Version to Version 2.
- Upgrade the project to the 2019.3.
- Wait for the editor to fully load.

**Import the Firebase Messaging unity package**

- **Assets->Import Package->Custom Package**, select the the **Firebase Messaging** unity package.
- Accept the import.
- When the import completes a **Unity Package Manager Resolver** window will appear asking to add the Game Package Registry by Google.  Click **Add Selected Registries**.
  - If the Unity Package Manager Resolver does not appear, then select **Assets -> Reimport All**. The **Add Selected Registries** should appear when the editor reloads).
- A progress bar should appear to **Migrate the Packages**. 
- When complete, import the External Dependency Manager.  
  - Select **Assets->Import Package->Custom Package**.
  - Select the `external-dependency-manager-latest.unitypackage` downloaded from the [Unity Setup Guide](https://firebase.google.com/docs/unity/setup#add-sdks-upm).
- When a dialog appears, click **Import**.
- A progress bar should appear tracking the progress of **Importing Package** and then another with **Importing Assets**.
- When complete a **Google Version Handler** dialog will appear with all of the assets in **Assets/ExternalDependencyManager**, and **Assets/PlayServicesResolver**.  Ensure they’re all selected and click **Apply**.

**Remove the older assets**

- Select **Assets > External Dependency Manager > Version Handler > Uninstall Managed Packages** menu option. 
- Select all Firebase SDKs as well as External Dependency Manager and click Uninstall Selected Packages.

**Add Firebase assets via the Package Manager**

- Select **Window > Package Manager** and search for **Firebase**. Select **Firebase Cloud Messaging** and select **Import**.
 
Attempt to build and run your application.

I have seen two errors in the console (below), which I assume are from the Package Manager import and will need to be looked into, but they didn't inhibit my ability to build and run the app on an iOS target.

- "Expected mapping key to be a sequence, actually a scalar."
- "Assertion failed on expression: 'IsSequence()'"

Thanks!

**Comment by novavision** [comment]
@DellaBitta 
after this step
> A progress bar should appear tracking the progress of Importing Package and then another with Importing Assets.
I get the error in editor:
`Stopped polling job due to exception: System.ArgumentException: The specified path is not of a legal form (empty).
  at System.IO.Path.InsecureGetFullPath (System.String path) [0x00025] in <437ba245d8404784b9fbab9b439ac908>:0 
  at System.IO.Path.GetFullPath (System.String path) [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0 
  at Google.VersionHandlerImpl.get_EnabledEditorDllsLoaded () [0x0001c] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/VersionHandlerImpl.cs:2353 
  at Google.VersionHandlerImpl+<NotifyWhenCompliationComplete>c__AnonStorey6.<>m__10 () [0x00000] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/VersionHandlerImpl.cs:2386 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:412)
Google.RunOnMainThread:<ExecuteAllUnnested>m__B() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)`
No dialog appears after import completed.
In general this guide looks really weird. What are you are asking to do is to import everything manually after remove everything and install the same from PackageManager? Does it make sense at all? Why not just follow the instructions @seansaleh provided, adding entries to `manifest.json`

**Comment by mgrogin** [comment]
try removing    "com.google.external-dependency-manager": "1.2.153", from manifest.json
For me that was causing conflict with package cache

**Comment by novavision** [comment]
So, in conclusion - just don't use external package manager in package manager. Now I just use legacy method adding each firebase package importing it to the project, and everything seems ok...for now at least

**Comment by chkuang-g** [comment]
@novavision 

What @seansaleh suggest definitely works if you know what to add to `manifest.json`. For some user, install EDM4U `.unitypackage` first and migrate to UPM probably is more straightforward.  The latest EDM4U also offers an auto migration feature too.

As for your original issue, it does looks like an installation conflict issue where EDM4U is installed from both UPM and `Assets` folder.  As mentioned in #695, the best solution right now is to manually remove `Assets/ExternalDependencyManager` and/or `Assets/PlayServicesResolver` folders.  We are also looking for some solution to remove those folders automatically if they are re-added by other packages such as Facebook SDK.

Hope this helps!
Shawn
