### ISSUE TITLE
One or more Firebase dependencies are not present.

### ISSUE THREAD

**Issue by thebrianbabu** [firebase/quickstart-unity#65]
I followed the steps as instructed in readme.md file.
I keep getting output as
"One or more Firebase dependencies are not present.
Current dependency status: UnavailableOther"

I see the readme was updated 2 months back and the testapp was updated 28 days back.
I'd really appreciate if you could help me resolve this.

Thanks in advance.

**Comment by stewartmiles** [comment]
Firstly take a look at my response to https://github.com/firebase/quickstart-unity/issues/53

Then you should check that your test device has Play Store access (open the Play Store on the device) and finally update Google Play Services on the device if it's out of date https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en .

BTW: Our readme hasn't been updated as the instructions haven't changed :)

Cheers,
Stewart

**Comment by thebrianbabu** [comment]
Hey Stewart,

Thank you for the reply, but its not resolving the issue. I have the updated Google Play Store App.
The console isnt throwing any errors.

Its just that the app is outputting the statement "One or more Firebase dependencies are not present."

Regards,
Brian

**Comment by stewartmiles** [comment]
Could you share the contents of your Android logcat output when running the app?

**Comment by josh-flyclops** [comment]
I'm also getting the same issue. When I check the logs, I get this:

```
03-07 16:58:02.810 17083 17101 D Unity   :Unable to lookup library path for 'App', native render plugin support disabled.
03-07 16:58:02.811 17083 17101 E Unity   : Unable to find App
03-07 16:58:02.905 17083 17101 I Unity   : DllNotFoundException: App
03-07 16:58:02.905 17083 17101 I Unity   :   at (wrapper managed-to-native) Firebase.AppUtilPINVOKE/SWIGExceptionHelper:SWIGRegisterExceptionCallbacks_AppUtil (Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
03-07 16:58:02.905 17083 17101 I Unity   :   at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x00000] in <filename unknown>:0
03-07 16:58:02.905 17083 17101 I Unity   : Rethrow as TypeInitializationException: An exception was thrown by the type initializer for SWIGExcepti
```

**Comment by stewartmiles** [comment]
@josh-flyclops did you make sure auto / background resolution is enabled in the Play Services Resolver?  What ABIs are you building for?

**Comment by josh-flyclops** [comment]
@stewartmiles whoops, I forgot to resolve the jars. Worked afterwards. Thanks!

**Comment by stewartmiles** [comment]
@thebrianbabu did you resolve the problem?

**Comment by thebrianbabu** [comment]
No i wasn't able to resolve it. I just moved on from using the quickstart and I have a tight deadline for a work besides i dont know how to get the Android logcat output for unity app. I have done that via eclipse a long time back.

**Comment by stewartmiles** [comment]
@thebrianbabu You can get the logcat output from your device by running...

"adb logcat"

from the command line.

We would appreciate working with you to track this down to see whether it's unique to your test environment.

**Comment by stewartmiles** [comment]
We had an issue when the Gradle build system is used and only a single target ABI (architecture) was selected on Android.

This should be resolved in 3.0.1
https://firebase.google.com/support/release-notes/unity#3.0.1

You'll need to delete all files and directories under Plugins/Android that are labeled with "gpsr" to force dependency resolution to run again.

**Comment by studiokarisma** [comment]
@stewartmiles   i have same issue , but i didnt get how i can do this 
"did you make sure auto / background resolution is enabled in the Play Services Resolver? What ABIs are you building for?"
how i can change that? 
iim working with unity 2017.4.7

**Comment by stewartmiles** [comment]
@studiokarisma I don't follow what you're asking.  I recommend starting with the one of the sample projects, make sure you can build and run one of those then compare with your project.
