### ISSUE TITLE
Editor Crash after play/stop 2-5 times

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#653]
### Please fill in the following fields:
Unity editor version: 2018.4.21f
Firebase Unity SDK version: 6.12
Source you installed the SDK : unitypackage
Firebase plugins in use : Auth, FireStore
Additional SDKs you are using : Facebook, AdMob, VoxelBusters 
Platform you are using the Unity editor on : Windows
Platform you are targeting : Android
Scripting Runtime : IL2CPP

### Please describe the issue here:
Using FireStore normally in my code. Play/Stop to run and debug 2-5 times will make editor silently crash

This below is the crash log given from unity issue case 1238725

```
Crash is found in case editor_log log:
SWIGRegisterStringCallback_StorageInternal
Firebase_Firestore_CSharp_FirestoreInternal_Collection__SWIG_0
Firebase.Firestore.FirestoreUtilPINVOKE:FirestoreInternal_Collection__SWIG_0
Firebase.Firestore.FirestoreInternal:Collection
Firebase.Firestore.FirebaseFirestore:Collection
FirebaseManager/<Init>d__9:MoveNext
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<TStateMachine_REF>
FirebaseManager:Init
AWSConnector/<InitAWS>d__29:MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:InvokeMoveNext
System.Threading.ExecutionContext:RunInternal
System.Threading.ExecutionContext:Run
System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner:Run
System.Threading.Tasks.AwaitTaskContinuation:InvokeAction
System.Threading.Tasks.AwaitTaskContinuation:RunCallback
System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run
System.Threading.Tasks.Task:FinishContinuations
System.Threading.Tasks.Task:FinishStageThree
System.Threading.Tasks.Task`1<TResult_REF>:TrySetResult
System.Threading.Tasks.TaskCompletionSource`1<TResult_REF>:TrySetResult
AWSConnector/<>c__DisplayClass29_0:<InitAWS>b__10
Amazon.CognitoIdentity.CognitoIdentityAsyncExecutor/<>c__DisplayClass1_1`1<T_REF>:<ExecuteAsync>b__1
Amazon.Runtime.Internal.UnityMainThreadDispatcher:ProcessRequests
Amazon.Runtime.Internal.UnityMainThreadDispatcher:Update
object:runtime_invoke_void__this__
mono_jit_runtime_invoke
do_runtime_invoke
mono_runtime_invoke
scripting_method_invoke
ScriptingInvocation::Invoke
MonoBehaviour::CallMethodIfAvailable
MonoBehaviour::CallUpdateMethod
BaseBehaviourManager::CommonUpdate<BehaviourManager>
BehaviourManager::Update
`InitPlayerLoopCallbacks'::`2'::UpdateScriptRunBehaviourUpdateRegistrator::Forward
ExecutePlayerLoop
PlayerLoop
PlayerLoopController::UpdateScene
Application::TickTimer
MainMessageLoop
WinMain
```

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Cannot

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by DellaBitta** [comment]
Hi @Thaina,

after further investigation we believe this is indeed the same underlying problem as #638.  I understand this goes against the initial impressions in the other thread.

Please reopen this issue (or file a new bug) after #638 is resolved and you still have an issue with starting and stoping that produces a stack trace like the one above. Thank you!
