### ISSUE TITLE
Firebase storage stops working after "Unable to create StorageReference" error

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#656]
### Please fill in the following fields:
Unity editor version: 2019.3.6f1
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager):unitypackage 
Firebase plugins in use (Auth, Database, etc.):Auth, Database, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): none
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android (eventually)
Scripting Runtime (Mono, and/or IL2CPP):/

### Please describe the issue here:
I noticed that if I apply a wrong URL to StorageReference, that gives me "Unable to create StorageReference" error, that's fine, but then I can't connect to the storage anymore, even if I type a correct StorageReference afterward (that gives no error), seems like I need to reset/clear the storage reference somehow.

Here is my code, if I remove the line with the arrow it works perfectly if I leave it as is the code is stuck at
GetBytesAsync and never continues, no catch, no fail.  
What I tried-  remove the await, using 2 different storageRefernces, resetting storage to DefaultInstance 

My code is very basic-

        string wrongurl= "Not a good url"
        string goodurl ="gs://...."
        storage = FirebaseStorage.DefaultInstance;
        const long maxAllowedSize = 1 * 1024 * 1024;

         try{
        ===> storageRef =storage.GetReferenceFromUrl(wrongurl);}
        catch{}  //always caught because wrong url
       
        try{storageRef =storage.GetReferenceFromUrl(goodurl);}
        catch{}  //no catch because good

        try{
        var task2 = await storageRef.GetBytesAsync(maxAllowedSize).ContinueWith(t => t);

        if (task2.IsFaulted || task2.IsCanceled)
            {
                  Debug.Log(task2.Exception.ToString());
                // Uh-oh, an error occurred!
            }
            else
            {}
        }
        catch{} // no catch

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes

What's the issue repro rate? (eg 100%, 1/5 etc)
5
Fir

**Comment by patm1987** [comment]
Hi shlighter!

I'm having a hard time reproducing your bug in the [Unity Quickstart](https://github.com/firebase/quickstart-unity/tree/master/storage/testapp) by doing the following:

I modified the `GetStorageReference` function a little bit to ensure that I'm always getting the default instance rather than creating a new `FirebaseStorage` for every call:
```
protected StorageReference GetStorageReference()
{
  // If this is an absolute path including a bucket create a storage instance.
  if (storageLocation.StartsWith("gs://") ||
      storageLocation.StartsWith("http://") ||
      storageLocation.StartsWith("https://")) {
    var storageUri = new Uri(storageLocation);
    var firebaseStorage = FirebaseStorage.DefaultInstance;
    // var firebaseStorage = FirebaseStorage.GetInstance(
      // String.Format("{0}://{1}", storageUri.Scheme, storageUri.Host));
    return firebaseStorage.GetReferenceFromUrl(storageLocation);
  }
  // When using relative paths use the default storage instance which uses the bucket supplied
  // on creation of FirebaseApp.
  return FirebaseStorage.DefaultInstance.GetReference(storageLocation);
}
```

I'd first add some random garbage to the "Storage Location" field in the UI to make sure I was uploading to a bad place then clicked "Upload".

Without relaunching, I'd fix my url and click "Upload" again.

The second time always works both in the Editor (MacOS) and on Android.

Can you confirm whether or not repeating these steps causes the bug to occur? What if you update to the latest (6.14) SDK?

Thanks,
--Patrick
