### ISSUE TITLE
Why are there double callbacks for Firebase.Messaging.FirebaseMessaging.TokenReceived?

### ISSUE THREAD

**Issue by josh-flyclops** [firebase/quickstart-unity#66]
The method "OnTokenReceived" gets called twice. Meaning, I get the token id twice (prints it twice). This seems like an error because the client code listens to Firebase.Messaging.FirebaseMessaging.TokenReceived only once. Is the native side sending the token message twice by any chance?

This is for android.

Update: This seems to be happening when I implement FCM into my own project too

**Comment by alexames** [comment]
I feel like I've seen this bug before, but I can't replicated the bug with the most recent releases of Firebase and the test app. Can you verify that it's still happening to you and if so can you provide a minimal reproduction case or the steps you followed to cause it to happen?

**Comment by ESG-Steven** [comment]
I actually have the opposite problem where I never get an 'onTokenReceived'... Should this not be happening on first startup?

**Comment by alexames** [comment]
That sounds like a different bug. Can you create an issue and list your set up and reproduction steps?

**Comment by alexames** [comment]
Scratch that, I see that you've already opened an issue. It was in the very next tab :P

**Comment by stewartmiles** [comment]
@josh-flyclops is this a problem for your use case?  Is there anything you can share about how you use the FCM token?

**Comment by antxDotDe** [comment]
I also get the token twice but only the first time I run the app (after uninstall followed reinstall) and this only on Android.
And no for me this is no problem.

**Comment by stewartmiles** [comment]
We resolved this issue in 4.0.2 (release notes here https://firebase.google.com/support/release-notes/unity).

Cheers,
Stewart
