### ISSUE TITLE
0 Records on Firebase Analytics

### ISSUE THREAD

**Issue by ugulser** [firebase/quickstart-unity#663]
### Please fill in the following fields:
Unity editor version: 2020.1.0a18
Firebase Unity SDK version: Latest (I can not find the version but I downloaded it from instructions)
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity=> Import Package => (FirebaseAnalytics.unitypackage)
Firebase plugins in use (Auth, Database, etc.): I do not know.
Additional SDKs you are using (Facebook, AdMob, etc.): No.
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:

I did everything that was shown. However, no records appear on the Firebase Console. 
I saved release, debug and Google Play fingerprints(SHA-1 and SHA-256) to Firebase Settings.
I imported google-services.json to my Unity Project(Assets folder). 
Then I imported FirebaseAnalytics Unity package.
Then I wrote a script as shown`FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(continuationAction: task =>
       {
           FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
       });`
Then I builded .apk file and sent it to an Android mobile device. Then I opened it but no records appear on the Firebase Console. I also tried debug version but nothing happens. 

I think I did everthing right. What could have caused this problem?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Yes.

What's the issue repro rate? (eg 100%, 1/5 etc)
%100.

**Comment by czanier** [comment]
Having same problem, @ugulser have you been able to sort it out?

**Comment by ugulser** [comment]
@czanier Unfortunately. I started using Unity Analytics.

**Comment by vanes96** [comment]
Same problem. I cant see any changes in statistics but all steps have been done. Ok, I will wait for 24 hours but I dont believe that something will appear there.

**Comment by chkuang-g** [comment]
Hi foks,

Could you try to enable debug mode and see if any event logged in DebugView?
https://firebase.google.com/docs/analytics/debugview

**Comment by chkuang-g** [comment]
Update: 

I did notice that no event log using Firebase 6.14.0.  I'll have the team to investigate more about this.

**Comment by chkuang-g** [comment]
Update:

Did you see 0 records under `Event` tab?
Could you verify this with [Analytics testapp](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp)
I can see events like "first_open", "login", "app_removed" on our test project using this testapp.

**Comment by chkuang-g** [comment]
Update:

I did noticed that I was not able to create FirebaseApp in Android build created by Unity 2020.1.0b10.  

This seems to be related to some breaking change in Unity.

Did you guys see anything like the following in your `logcat`?
```
InitializationException:  Firebase app creation failed.
```
