### ISSUE TITLE
Batchmode Unity builds for 6.14 freeze with "Cancelling DisplayDialog: Enable Analytics [...]"

### ISSUE THREAD

**Issue by seansaleh** [firebase/quickstart-unity#669]
### Please fill in the following fields:
Unity editor version: 2019.3.10f
Firebase Unity SDK version: 6.14.0
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I updated firebase to 6.14.0 from 6.13.0 and my builds started freezing.
You can view my change and fork of the Quickstart Unity project here: https://github.com/seansaleh/quickstart-unity/commit/0d4a9b6898523aef4ea03f92683e648c7d72c047

I run Unity as part of an automated build with the flags like `-batchMode -quit -serial SC-<CUT> -username <CUT> -password <CUT> -buildTarget iOS -logFile "./unitybuild.log" -executeMethod DoBuild -projectPath "." `
The builds freeze with the following message:
```
Cancelling DisplayDialog: Enable Analytics Would you like to report Firebase usage to the developers?

This data can be used to improve this product.

For more information, see https://policies.google.com/privacy by clicking show policy
This should not be called in batch mode.
UnityEditor.EditorUtility:DisplayDialogComplex(String, String, String, String, String)
Google.Dialog:DisplayDefault(String, String, Option, String, String, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Dialog.cs:96)
Google.Dialog:Display(String, String, Option, String, String, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Dialog.cs:117)
Google.EditorMeasurement:PromptToEnable() (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\EditorMeasurement.cs:348)
Google.EditorMeasurement:Report(String, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\EditorMeasurement.cs:446)
Google.EditorMeasurement:Report(String, ICollection`1, String) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\EditorMeasurement.cs:434)
Firebase.Editor.Measurement:ReportWithBuildTarget(String, ICollection`1, String) (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\Measurement.cs:92)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator(IEnumerable`1, String, Boolean) (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:544)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String) (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:415)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:303)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:254)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:<GenerateXmlFromGoogleServicesJson>m__0() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:115)
Google.RunOnMainThread:ExecuteNext() (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction(Action) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:530)
Google.RunOnMainThread:Run(Action, Boolean) (at Z:\tmp\tmp.oShw7fyUik\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:472)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:.cctor() (at Z:\tmp\tmp.bqIAK2yOnW\firebase\app\client\unity\editor\src\GenerateXmlFromGoogleServicesJson.cs:115)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:114)

[/Users/builduser/buildslave/unity/build/Editor/Platform/OSX/EditorUtility.mm line 344] 
(Filename: Z Line: 0)
```

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes
Here's a fork of quickstart where before this commit builds worked, afterwards they failed.
https://github.com/seansaleh/quickstart-unity/commit/0d4a9b6898523aef4ea03f92683e648c7d72c047
Note, I also tested it on the Storage project [with this commit](https://github.com/seansaleh/quickstart-unity/commit/3b9d5ebbbc16a4f697e920d71633b83e451684fe) and had the same failure

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by tiagomartines11** [comment]
Have you tried using `-batchmode` instead of `-batchMode`? There is piece of code on Google.VersionHandlerImpl that checks against the lowercase version to decide if certain things should run or not.

**Comment by seansaleh** [comment]
Thanks! Using `-batchmode` instead of `-batchMode` worked as a workaround.
For Google folks can we track this as a bug since this is a regression considering builds for 6.13 worked just fine with `-batchMode`?

**Comment by chkuang-g** [comment]
Hi folks,

This has been fixed in the latest version of EDM4U
https://github.com/googlesamples/unity-jar-resolver/commit/30eaff257bf20ac36a8957ecfd4086a482b53079

You can update it to 1.2.155 through UPM.
