### ISSUE TITLE
Cannot compile project for WebGL upon using this plugin

### ISSUE THREAD

**Issue by jjmpsp** [firebase/quickstart-unity#67]
My team is using version 3 (the latest version) of the firebase SDK for Unity. Upon building our game for WebGL, we get no output files once the process has completed. We receive this error in the Unity Cloud Builder and from our local Desktop PCs. I've monitored Unity's log file and discovered the following error:

```stdout:
Fatal error in Mono CIL Linker
System.ArgumentException: Unable to find the file for the assembly named 'Firebase.App' specified in link file '/Users/Joel/Desktop/project-gold-game-cloud/ProjectGold/Assets/Firebase/Plugins/link.xml'. Should this assembly be in the project? Use the 'ignoreIfMissing="1"' attribute if this assembly may not always exist. ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Firebase.App, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
  at Mono.Linker.LinkContext.Resolve (IMetadataScope scope) <0x104546970 + 0x000e9> in <filename unknown>:0 
  at Mono.Linker.Steps.ResolveFromXmlStep.GetAssembly (Mono.Linker.LinkContext context, System.String assemblyName) <0x104546110 + 0x00036> in <filename unknown>:0 
  at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies (Mono.Linker.LinkContext context, System.Xml.XPath.XPathNodeIterator iterator) <0x104545060 + 0x0009e> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies (Mono.Linker.LinkContext context, System.Xml.XPath.XPathNodeIterator iterator) <0x104545060 + 0x003b0> in <filename unknown>:0 
  at Mono.Linker.Steps.ResolveFromXmlStep.Process () <0x104544690 + 0x0008b> in <filename unknown>:0 
  at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) <0x104544560 + 0x0006b> in <filename unknown>:0 
  at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) <0x104543620 + 0x000e6> in <filename unknown>:0 
  at Mono.Linker.Driver.Run (IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x101db4430 + 0x00be7> in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriverWithErrorHandling (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x101db43e0 + 0x00026> in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriver (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x101db42f0 + 0x0003b> in <filename unknown>:0 
```

Is this a known bug? I did try searching but didn't find anything. Any help would be greatly appreciated!

**Comment by stewartmiles** [comment]
We currently don't support Web as a target platform.  We support iOS & Android with stub implementations for the desktop.  See https://firebase.google.com/docs/unity/setup

**Comment by jjmpsp** [comment]
Hi @stewartmiles ,
Thanks for the super fast response! Apologies, I probably should have mentioned we're only using the plugin for iOS and Android specific functionality and can see why you closed this issue. 

Is there also a stub implementation for WebGL? I didn't see anything mentioned about this in the docs and I've tried messing around with various configs in Unity but still unable to get our game to compile for the WebGL platform. The exception that fires during the failed build is:

```Exception: /Applications/Unity/Unity.app/Contents/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!```

Any ideas on this?

**Comment by Rostin** [comment]
Hi, I'm also getting this issue with Unity 5.5 

``` 22445: [Unity] stdout:
22446: [Unity] Fatal error in Mono CIL Linker
22447: [Unity] System.ArgumentException: Unable to find the file for the assembly named 'Firebase.App' specified in link file '/BUILD_PATH/rostin.projectgold.default-webgl/Assets/Firebase/Plugins/link.xml'. Should this assembly be in the project? Use the 'ignoreIfMissing="1"' attribute if this assembly may not always exist. ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Firebase.App, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
22448: [Unity]   at Mono.Linker.LinkContext.Resolve (IMetadataScope scope) <0x102798a10 + 0x000e9> in <filename unknown>:0 
22449: [Unity]   at Mono.Linker.Steps.ResolveFromXmlStep.GetAssembly (Mono.Linker.LinkContext context, System.String assemblyName) <0x1027981b0 + 0x00036> in <filename unknown>:0 
22450: [Unity]   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies (Mono.Linker.LinkContext context, System.Xml.XPath.XPathNodeIterator iterator) <0x102797100 + 0x0009e> in <filename unknown>:0 
22451: [Unity]   --- End of inner exception stack trace ---
22452: [Unity]   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies (Mono.Linker.LinkContext context, System.Xml.XPath.XPathNodeIterator iterator) <0x102797100 + 0x003b0> in <filename unknown>:0 
22453: [Unity]   at Mono.Linker.Steps.ResolveFromXmlStep.Process () <0x102796730 + 0x0008b> in <filename unknown>:0 
22454: [Unity]   at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) <0x102796600 + 0x0006b> in <filename unknown>:0 
22455: [Unity]   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) <0x1027956c0 + 0x000e6> in <filename unknown>:0 
22456: [Unity]   at Mono.Linker.Driver.Run (IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x10251d430 + 0x00be7> in <filename unknown>:0 
22457: [Unity]   at Mono.Linker.Driver.RunDriverWithErrorHandling (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x10251d3e0 + 0x00026> in <filename unknown>:0 
22458: [Unity]   at Mono.Linker.Driver.RunDriver (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x10251d2f0 + 0x0003b> in <filename unknown>:0 
22459: [Unity] stderr: ```

**Comment by stewartmiles** [comment]
@jjmpsp we haven't even tried building for WebGL so I'm pretty sure it's not going to work.  Our stub implementations are provided in shared native libraries at the moment.  You may need to go down the path of using conditional compilation (use #if) to strip out references to Firebase when targeting WebGL. 

@Rostin as I mentioned to @jjmpsp we don't support WebGL at the moment I'm afraid.

**Comment by maksimonishchenko** [comment]
just happend to ios build and firebase 3.0.1 
4888: [Unity] Fatal error in Mono CIL Linker
4889: [Unity] System.ArgumentException: Unable to find the file for the assembly named 'Firebase.App'. Should this assembly be in the project? ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Firebase.App, Culture=neutral, PublicKeyToken=null'
4890: [Unity]   at Mono.Linker.Driver.RunDriverWithErrorHandling (Mono.Linker.Driver driver) [0x00000] in <filename unknown>:0 
4891: [Unity] Error building Player: Exception: /UNITY_PATH/Unity/Unity-4_7_2/Unity.app/Contents/Frameworks/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!
4892: [Unity] Player export failed. Reason: Error building Player: Exception: /UNITY_PATH/Unity/Unity-4_7_2/Unity.app/Contents/Frameworks/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!
4893: ! build of 'default-ios' failed. compile failed
4894: publishing finished successfully.
4895: Finished: FAILURE
unity 4.7.2 tho

**Comment by johnb003** [comment]
@maksimonishchenko is this related to webGL or a new issue?
As has been mentioned WebGL is not currently supported.

If it's for another platform, can can you please start a new issue and detail your setup?

Version of Unity: 4.7.2    (thanks)
Version of the plugin: 3.0.1    (thanks)
Target Platform? It's unclear if you're targetting ios (in the log), or webGL -- this thread.
What ABI type is your device? Or just name the device.
Are you targeting the architecture specifically or with Universal lib?

Can you test with the player settings, byte stripping disabled:
![image](https://cloud.githubusercontent.com/assets/6802349/24259200/715d232c-0fad-11e7-8d86-edcd3092b206.png)

Thanks!

**Comment by johnb003** [comment]
It seems like a Unity bug with the stripping based on your log:

> 4_7_2/Unity.app/Contents/Frameworks/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!

**Comment by maksimonishchenko** [comment]
ios cloud unity build. . this is a namespace collision with a parse.dll this one fixed by using var task = ...instead of Task task = ... in all task declarations. altho have another bug with build 

34671:        [xcode] /BUILD_PATH/froschmedialtd.skater.default-ios/temp.yRyeyE/Pods/Headers/Public/Firebase/Firebase.h:1:9: fatal error: 'FirebaseAnalytics/FirebaseAnalytics.h' file not found
34672:        [xcode] #import <FirebaseAnalytics/FirebaseAnalytics.h>
34673:        [xcode] 1 error generated.

34680:        [xcode] ** BUILD FAILED **
34681:        [xcode] The following build commands failed:
34682:        [xcode] 	CompileC build/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Objects-normal/armv7/PluginAppController.o Libraries/PluginAppController.mm normal armv7 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
34683:        [xcode] (1 failure)
34684: ! build of 'default-ios' failed. compile failed

i know its unity 4.7 and firebase says it needs 5.3+ still maybe some fix is available for now. according to log it couldnt find analytics.i didnt imprted it while on intergration stage just the messagin.unitypackage -> does this dependency is mandatory?(messagin->analytics?)  thanks

**Comment by johnb003** [comment]
Please repost this as a new issue and we can discuss there.

**Comment by comtaler** [comment]
Just in case someone is looking also having this issue and just want to have webgl built without error. Here is what you can do:

In the editor, go to Assets/Firebase/Plugins and select all the dlls. Then in the inspector, check WebGL under Include Platforms.

**Comment by thanhson90** [comment]
You can try this one:

Open "Firebase/Plugins/link.xml" file and remove assembly Firebase.app.

good luck

**Comment by theshked** [comment]
Another option, in "Firebase/Plugins/link.xml" add ignoreIfMissing="1" for the Firebase.App assembly:

`<assembly fullname="Firebase.App" ignoreIfMissing="1">`

**Comment by chrisfairc** [comment]
thank you @theshked ! This seems like the right answer. 

To the admins: The issue is not that we need firebase support for webgl. The issue is that we want to be able to build webgl project from the same repo from which we build our mobile apps without firebase causing compile errors.

**Comment by dustinkerstein** [comment]
FYI - I am getting the same error when building for Windows Universal.
