### ISSUE TITLE
Unity Editor Crash with realtime database emulator.

### ISSUE THREAD

**Issue by unace** [firebase/quickstart-unity#671]
### Please fill in the following fields:
Unity editor version: 2019.3.13f1
Firebase Unity SDK version: 6.14.0
Source you installed the SDK (.unitypackage or Unity Package Manager):Unity Package Manager
Firebase plugins in use (Auth, Database, etc.):Database
Additional SDKs you are using (Facebook, AdMob, etc.): Nothing
Platform you are using the Unity editor on (Mac, Windows, or Linux): Macbook Pro
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
Unity Editor Crash with realtime database emulator. Doesn't unity sdk support the realtime database emulator?
Unity seems to work well with functions emulator.

### Please answer the following, if applicable:
Repro steps:
1. Create a new empty project.
1. setup firebase unity sdk. https://firebase.google.com/docs/unity/setup
1. setup firebase local emulator. https://firebase.google.com/docs/emulator-suite 
1. add below script to GameObject (I changed "YOUR_DATABASE_NAMESPACE" to my project id. Is it correct?)
```
public class Test : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        var database = Firebase.Database.FirebaseDatabase.GetInstance("http://localhost:9000?ns=YOUR_DATABASE_NAMESPACE");
        database.GetReference("test").GetValueAsync().ContinueWith((task) =>
        {

        });
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
```
1. run preview 
1. crash!

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by chkuang-g** [comment]
@unace 

- Did you call `Firebase.FirebaseApp.CheckAndFixDependenciesAsync()` before using any database APIs?
- Could you take a look if [Editor.log](https://docs.unity3d.com/2018.3/Documentation/Manual/LogFiles.html) and post the crash callstack?
- For even more precise callstack, could you try to use Xcode to attach to the Unity instance and capture the the callstack of all threads (You can use `bt all` when Xcode breaks after Unity crash)

Thank you,
Shawn
