### ISSUE TITLE
Issue with Gradle Resolution 

### ISSUE THREAD

**Issue by GamerSarath** [firebase/quickstart-unity#672]
### Please fill in the following fields:
Unity editor version:  2019.2.2
Firebase Unity SDK version:  6.14
Source you installed the SDK (.unitypackage or Unity Package Manager):.unitypackage
Firebase plugins in use (Auth, Database, etc.):Auth,Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): GooglePlayGames
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I have read some other answers on the issue saying that issue is gradle wrapper problem. so I removed entire gradle wrapper directory and re installed it correctly and verified installation on command prompt. 

Then I set the java environment variables in the system path correctly and re opened the unity. Still I am getting the issue and the issue is I am addressing below. Kindly help me to find the solution.

Running Gradle...

D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/Firebase/m2repository;file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-auth:19.3.0;com.google.firebase:firebase-analytics:17.3.0;com.google.firebase:firebase-auth-unity:6.14.0;com.google.games:gpgs-plugin-support:0.9.50;com.google.firebase:firebase-common:19.3.0;com.google.firebase:firebase-app-unity:6.14.0;com.google.firebase:firebase-analytics-unity:6.14.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.4.0"
Executing command: D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/Firebase/m2repository;file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-auth:19.3.0;com.google.firebase:firebase-analytics:17.3.0;com.google.firebase:firebase-auth-unity:6.14.0;com.google.games:gpgs-plugin-support:0.9.50;com.google.firebase:firebase-common:19.3.0;com.google.firebase:firebase-app-unity:6.14.0;com.google.firebase:firebase-analytics-unity:6.14.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.4.0"
Reporting analytics data: /androidresolver/resolve/gradle/failed/fetch?unityVersion=2019.2.21f1&unityPlatform=WindowsEditor&installSource=unitypackage&version=1.2.152&scope= 'Android Resolver: Gradle Resolve: Tool Extraction Failed'
ERROR: Gradle failed to fetch dependencies.

Failed to run 'D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/Firebase/m2repository;file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-auth:19.3.0;com.google.firebase:firebase-analytics:17.3.0;com.google.firebase:firebase-auth-unity:6.14.0;com.google.games:gpgs-plugin-support:0.9.50;com.google.firebase:firebase-common:19.3.0;com.google.firebase:firebase-app-unity:6.14.0;com.google.firebase:firebase-analytics-unity:6.14.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.4.0"'
stdout:

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

stderr:

exit code: 1

The issue is regarding

2020/05/09 23:40:21.326 21351 21407 Error Unity   : DllNotFoundException FirebaseCppApp-6_14_0
2020/05/09 23:40:21.326 21351 21407 Error Unity      at (wrapper managed-to-native) Firebase.AppUtilPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_AppUtil(Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate,Firebase.AppUtilPINVOKE/SWIGExceptionHelper/ExceptionDelegate)
2020/05/09 23:40:21.326 21351 21407 Error Unity      at Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () [0x000ee] in <06ddddb21dba4794a39b0dff7ab25aa8>:0 
2020/05/09 23:40:21.326 21351 21407 Error Unity   : Rethrow as TypeInitializationException The type initializer for 'SWIG

the above problem I found some answers saying that resolving android dependencies will give the solution. But I am unable to resolve android dependency. Resolving is saying resolution succeeded but force resolve is giving me the above mentioned error. 

Kindly give me a solution.

Thank & Regards

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by GamerSarath** [comment]
After Restarting the system, there is progress. Now I am getting new error while resolving.

Running Gradle...

D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/Firebase/m2repository;file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-auth:19.3.0;com.google.firebase:firebase-analytics:17.3.0;com.google.firebase:firebase-auth-unity:6.14.0;com.google.games:gpgs-plugin-support:0.10.09;com.google.firebase:firebase-common:19.3.0;com.google.firebase:firebase-app-unity:6.14.0;com.google.firebase:firebase-analytics-unity:6.14.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.4.0"
Executing command: D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/Firebase/m2repository;file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-auth:19.3.0;com.google.firebase:firebase-analytics:17.3.0;com.google.firebase:firebase-auth-unity:6.14.0;com.google.games:gpgs-plugin-support:0.10.09;com.google.firebase:firebase-common:19.3.0;com.google.firebase:firebase-app-unity:6.14.0;com.google.firebase:firebase-analytics-unity:6.14.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.4.0"
Reporting analytics data: /androidresolver/resolve/gradle/failed/fetch?unityVersion=2019.2.21f1&unityPlatform=WindowsEditor&installSource=unitypackage&version=1.2.152&scope= 'Android Resolver: Gradle Resolve: Tool Extraction Failed'
ERROR: Gradle failed to fetch dependencies.

Failed to run 'D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\gradlew.bat --no-daemon -b "D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK" "-PTARGET_DIR=D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Assets\Plugins\Android" "-PMAVEN_REPOS=file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/Firebase/m2repository;file:///D:/Production/3SCUBESTUDIOS/GamesUnitedStudios/HoneyRoyale_V.1.0/HoneyRoyale/Assets/GooglePlayGames/Editor/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-auth:19.3.0;com.google.firebase:firebase-analytics:17.3.0;com.google.firebase:firebase-auth-unity:6.14.0;com.google.games:gpgs-plugin-support:0.10.09;com.google.firebase:firebase-common:19.3.0;com.google.firebase:firebase-app-unity:6.14.0;com.google.firebase:firebase-analytics-unity:6.14.0" "-PUSE_JETIFIER=1" "-PDATA_BINDING_VERSION=3.4.0"'
stdout:

> Configure project :
ANDROID_HOME: C:/Program Files/Unity/Hub/Editor/2019.2.21f1/Editor/Data/PlaybackEngines/AndroidPlayer\SDK

stderr:

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Production\3SCUBESTUDIOS\GamesUnitedStudios\HoneyRoyale_V.1.0\HoneyRoyale\Temp\PlayServicesResolverGradle\PlayServicesResolver.scripts.download_artifacts.gradle' line: 873

* What went wrong:
A problem occurred evaluating root project 'PlayServicesResolverGradle'.
> Uninitialized object exists on backward branch 45
  Exception Details:
    Location:
      com/android/tools/build/jetifier/core/proguard/ProGuardTypesMap.<init>([Lkotlin/Pair;)V @101: goto
    Reason:
      Error exists in the bytecode
    Bytecode:
      0x0000000: 2b12 bfb8 008d 2a2b 4d3a 0d03 3e2c 3a04
      0x0000010: bb00 2459 2cbe b700 2cc0 002e 3a05 0336
      0x0000020: 0619 043a 0719 07be 3608 0336 0915 0915
      0x0000030: 08a2 0037 1907 1509 323a 0a19 0519 0a3a
      0x0000040: 0b3a 0e03 360c 190b b600 d419 0bb6 00d7
      0x0000050: b800 b6b8 0065 3a0f 190e 190f b900 5902
      0x0000060: 0057 8409 01a7 ffc8 1905 c000 5b3a 0e19

**Comment by GamerSarath** [comment]
Taking a new empty project also is giving me the same error. But your quick start project with analytics sdk imported is giving resolution succeeded.

**Comment by GamerSarath** [comment]
Resolution is failing in Quick start project of yours also..

**Comment by rehmanilyas** [comment]
Having same issue with Unity 2019.3.13f1. @GamerSarath did you find any solution?

**Comment by chkuang-g** [comment]
@GamerSarath 

Just like to clarify on your issue.  
1. In Unity Editor, when it is running Android resolver or when you were building an Android build, you saw: `ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.`
2. Even with the error, you can still build the apk.  However, when you run the app on an Android phone, you saw: `Error Unity : DllNotFoundException FirebaseCppApp-6_14_0`

Regarding to problem 1, can you verify if you can run `java --version` with Windows command line tool?  Are you using Java 8 (version 1.8)?  Also, you can check if you set the Java path properly in `Preferences > External Tool > Android JDK`.
