### ISSUE TITLE
Please fix your bundle id

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#682]
### Please fill in the following fields:
Unity editor version: 2019.3.6f1
Firebase Unity SDK version: firebase_unity_sdk_6.14.1
Source you installed the SDK (.unitypackage or Unity Package Manager):unitypackage 
Firebase plugins in use (Auth, Database, etc.):auth,database,storage
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): windows
Platform you are targeting (iOS, Android, and/or desktop): android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Every time I sign in / use auth on my app, sign in goes successfully but then - I get the following message- 
 Provided authentication credentials are invalid. This indicates your FirebaseApp instance was not initialized correctly. Make sure your google-services.json file has the correct firebase_url and api_key. You can re-download google-services.json from https://console.firebase.google.com/.

Even though I redownloaded the google-services.json many times and even created a new one on the console.

I noticed someone had the same issue and they closed the ticket-https://github.com/firebase/quickstart-unity/issues/450#issuecomment-523096158

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by shlighter** [comment]
OK I fixed it by 2 steps-
1.  I copied an old "generate_xml_from_google_services_json.exe" from my previous project + the 4 files come with it.  Which made the "Please fix your bundle id" window disappear. That annoying message kept coming without even running my code.
But I still got "Provided authentication credentials are invalid" after signing
2. That was a mistake on my end-  FirebaseApp.DefaultInstance.SetEditorDatabaseUrl(*****) It was a wrong URL to my previous project

**Comment by DellaBitta** [comment]
Hi @shlighter ,

Other people are seeing the repeated bundle ID dialog box errors.  To help us narrow this down, could you let me know which version of the Firebase Release the working generate_xml_from_services_json.exe came from?  Is it from 6.13.0?

Thanks!
