### ISSUE TITLE
Undefined symbols for architecture armv7:   "_OBJC_CLASS_$_SKProductsRequest", referenced from:

### ISSUE THREAD

**Issue by felix-laofan** [firebase/quickstart-unity#683]
### Please fill in the following fields:
Unity editor version: 2018.4.12f
Firebase Unity SDK version: 6.14.0
Source you installed the SDK (.unitypackage or Unity Package Manager):.unitypackage 
Firebase plugins in use (Auth, Database, etc.):FirebaseMessage
Additional SDKs you are using (Facebook, AdMob, etc.): Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): IOS
Scripting Runtime (Mono, and/or IL2CPP):Mono

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMProductsRequest_1d32402b235273321d4fe5e67f0b9438.o)
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics_4f9668e08eb8601f3872dcf3f26aec26.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<img width="590" alt="QQ图片20200519202116" src="https://user-images.githubusercontent.com/24423418/82325762-538a1780-9a0e-11ea-9f51-5926d17b3c94.png">

**Comment by felix-laofan** [comment]
> This issue does not seem to follow the issue template. Make sure you provide all the required information.

i had edit it again!!!!

**Comment by chkuang-g** [comment]
@felix-laofan 

- Where did you see this error?  Is it in Xcode?
- Did you see any error in Unity editor after you try to build Xcode project?
- Does this happen without FirebaseMessage?
- Are you able to reproduce with [quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp)?
