### ISSUE TITLE
Firebase initialization failed when using with Crashlytics

### ISSUE THREAD

**Issue by ishnu47** [firebase/quickstart-unity#685]
### Please fill in the following fields:
Unity editor version: 2018.4.21f1
Firebase Unity SDK version: 6.14.1
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manage
Firebase plugins in use (Auth, Database, etc.): Google Firebase Analytics, Firebase Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Firebase initialization failed on iOS device. 

Please check the code in my project.
If I disable Crashlytics call completely, the bug not happen.
```
    void SetCrashlyticsCustomKey(string key, string value)
    {
        // un-comment this will cause the Firebase initialization failed
        // if (IsFirebaseReady)
        //     Firebase.Crashlytics.Crashlytics.SetCustomKey(key, value);
    }
```

Please run the attached project on device (I tested on my iPhone 6S Plus, 13.4.1)

[FirebaseBug.zip](https://github.com/firebase/quickstart-unity/files/4660441/FirebaseBug.zip)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Not yet, but i think it's the same.

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by ishnu47** [comment]
Although this is related directly to Crashlytics, but due to its weird behavior, I think there might be other unexpected issues similar to this.
Hope you guys will have an investigation soon.

Thank you.

**Comment by muriloc-ssg** [comment]
I was having this problem after my project started using the Firebase UPM version. Looks like it's related to this issue: https://github.com/firebase/quickstart-unity/issues/623
Since you're using code stripping you need the Crashlytics link.xml file in your assets folder (because Unity does not process link.xml files in the packages folder)

**Comment by ishnu47** [comment]
@muriloc-ssg Thank you! That solved my problem.
Btw, I should switch to import the Unity package directly, instead of using UPM.

**Comment by DellaBitta** [comment]
Closing this issue since we now know it's a duplicate and there's more information captured in [#623](https://github.com/firebase/quickstart-unity/issues/623).  Thanks!
