### ISSUE TITLE
FCM custom handling of onMessageReceived function in Unity

### ISSUE THREAD

**Issue by abhilashranjan343** [firebase/quickstart-unity#686]
I am developing FCM for unity and I need to send some stats when the Push Notifications are received by the android client.

For that, if app is in foreground I am able to handle the scenario. But if the app is killed/background, I am not able to handle the scenario.

For this I came across https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android

I tried to Override ListenerService Methods and for this approach I tried to create a jar but whenever I am not able to import the "com.google.firebase.messaging.cpp.ListenerService".

Can you please suggest how can I achieve this functionailty

**Comment by chkuang-g** [comment]
@abhilashranjan343 

Did you try to add the services to AndroidManifest.xml?
https://firebase.google.com/docs/cloud-messaging/cpp/client#update_androidmanifestxml

**Comment by abhilashranjan343** [comment]
I was trying to create a jar which would handle the push notifications. For this I tried to import the "com.google.firebase.messaging.cpp.ListenerService". But it is throwing an error. So could not create the jar.
Is there any other package from java side, which I can use to override the default handling of notification.

**Comment by patm1987** [comment]
Hi @abhilashranjan343 ,

If you want to intercept the message handling at the Activity level, you should reference [this doc page](https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity).

The TL;DR is that you'd really need to create a [custom Activity](https://docs.unity3d.com/Manual/AndroidUnityPlayerActivity.html) where you handle the `onNewIntent` callback and fire off whatever custom logic you want in the jar. Although I would suggest double checking that you can't handle the logic you want in the [OnMessageReceived callback](https://firebase.google.com/docs/cloud-messaging/unity/receive).

Let me know if that helps!
