### ISSUE TITLE
Reopen #450: Error with Google-Services.json bundle id

### ISSUE THREAD

**Issue by CodeMasterYi** [firebase/quickstart-unity#687]
### Please fill in the following fields:
Unity editor version: 2018.4.3f1
Firebase Unity SDK version: v6.9.0
Source you installed the SDK (.unitypackage or Unity Package Manager):.unitypackage
Firebase plugins in use (Auth, Database, etc.):Analytics, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Suddenly happened! I have finished integrating Firebase yesterday, and everything worked well. But today, it suddenly force me to select a valid bundle ID. I don't know what is happenning!

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)
99.999999%

**Comment by CodeMasterYi** [comment]
![D8227CEB-475E-4B0B-8621-95C6D5D52212](https://user-images.githubusercontent.com/10430162/82547803-e355d000-9b8c-11ea-9999-83b3bcf10ddd.png)

**Comment by CodeMasterYi** [comment]
same here: https://github.com/firebase/quickstart-unity/issues/450

**Comment by CodeMasterYi** [comment]
I wonder how Firebase get the bundle id and  match it!

**Comment by DellaBitta** [comment]
Hi @CodeMasterYi,

I would say [check this post](https://github.com/firebase/quickstart-unity/issues/450#issuecomment-523096158) about ensuring that the Package Name in project settings is the same of your Firebase project.  But it does seem odd that bundle ID in the dialog box is the same as the one in the pull down menu.  Does the app still work if you select **Apply**?

**Comment by CodeMasterYi** [comment]
> Hi @CodeMasterYi,
> 
> I would say [check this post](https://github.com/firebase/quickstart-unity/issues/450#issuecomment-523096158) about ensuring that the Package Name in project settings is the same of your Firebase project.  But it does seem odd that bundle ID in the dialog box is the same as the one in the pull down menu.  Does the app still work if you select **Apply**?  

I do choose the right bundle I'd and select **Apply**! BUT!!! If it appears, it will appear again and again until I restart Unity Editor!!!

**Comment by chkuang-g** [comment]
@CodeMasterYi 

Could you double check a couple of things
- What does your Editor log says?
- Is the bundle Id under "Player Settings --> Bundle Identifier" matches the one in GoogleServices.plist?
- Did you import multiple GoogleServices.plist?
- What are other options in that dialog like?

Shawn

**Comment by CodeMasterYi** [comment]
@chkuang-g
Hi, thx for your attention!
I search the whole project just now. Here is the result:
There is only one `google-services.json` and only one `GoogleService-Info.plist` under folder `Assets/PlayServicesConfigurations`.
And there is also only one `google-services-desktop.json` under folder `Assets/StreamingAssets`.
And there is also only one `google-services.xml` under folder `Assets/Plugins/Android/Firebase/res/values`.

our bundle id for android and ios is different, and it is set correctly in the player setting!
and I also check the googleservice configurations downloaded from firebase page!
bundle id for android is right.
bundle id for ios is right too.

Emmm... I didn't check the Editor Log and I don't see the dialog now. I don't know why it appears sometimes.

I dont know what you mean by saying `What are other options in that dialog like?`.
Tell me to select another bundle id?

**Comment by chkuang-g** [comment]
What I meant is: when "Please Fix Your Bundle ID" pop-up, from the drop-down menu, how many items are in it and are they the different to your current bundle id?

Since you said that the bundle id in player settings is correct, does that mean this dialog kept prompt to ask you to change to an incorrect bundle id?

Just like to understand the situation here since we cannot reproduce this issue from our side even with both google-services.json and GoogleServices.json presented in the project.

**Comment by CodeMasterYi** [comment]
there is two options for the dropdown list
android bundle id(selected as default when it pop-up)
& ios bundle id

Unity project is switched to `Android` platform.

see this:
![DF13ADAC-0FB7-40B4-A36F-E85734BC5F7E](https://user-images.githubusercontent.com/10430162/83249562-55579600-a1d9-11ea-99d0-5a1d2d598ccd.png)

this is what the dialog is like when it pop-up, i do not change it.
the strings that i mask are the same. they are all the android bundle id~

How can I locate the code where the dialog pop-up?

**Comment by patm1987** [comment]
Sorry to have let this bug grow so stale!

I have a few questions:
1) are you still experiencing the issue with the [latest](https://firebase.google.com/support/release-notes/unity) (6.15) SDK?
2) are you able to reproduce this in the [Analytics](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp) or [Crashlytics](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp) quickstarts?
3) In the thread linked above, a user reported solving this by pulling in the `generate_xml_from_google_services_json.exe` from the [5.3.1 Unity SDK](https://dl.google.com/firebase/sdk/unity/firebase_unity_sdk_5.3.1.zip). Can you tell us if that fixes your issue? If it does, I want to keep this open as a bug to investigate, but it could also give you a good temporary workaround.

**Comment by areegqween2** [comment]
> 
> Since there haven't been any recent updates here, I am going to close this issue.
> 
> @CodeMasterYi if you're still experiencing this problem and want to continue the discussion just leave a comment here and we are happy to re-open this.
