### ISSUE TITLE
auth testapp README issue

### ISSUE THREAD

**Issue by jonahgoldsaito** [firebase/quickstart-unity#688]
auth / testapp / README.md

In the Troubleshooting section, the 2nd bullet point trails off without completion:

> Then, select your Project Key alias and enter your key's password. **enabled in your project, you'll see compile errors from some types in the**

I'm trying to work through someone strange bugs trying to do a simple integration into a pre-existing app (2019.3.8 on OSX building to Android), and I'm curious if I might be missing an unspoken step/consideration. Thanks :)

**Comment by DellaBitta** [comment]
Hi @jonahgoldsaito, 

Yes, I'll work to remove that text. The sentence fragment is from the [Known Issues page](https://firebase.google.com/docs/unity/setup#net_compatibility_when_using_unity_2017x_and_later) about importing the correct .NET version of the Firebase SDK. The text is unrelated to the configuration of the keystore for Android builds.

Sorry for the confusion and thanks for pointing this out!

**Comment by DellaBitta** [comment]
The new docs have been publshed. Thanks again!
