### ISSUE TITLE
Crashlytics is not being enabled and does not send crash reports

### ISSUE THREAD

**Issue by vahagn-harutyunyan** [firebase/quickstart-unity#691]
### Please fill in the following fields:
Unity editor version: **2019.3.14**
Firebase Unity SDK version: **6.14.1**
Source you installed the SDK (.unitypackage or Unity Package Manager): **unitypackage**
Firebase plugins in use (Auth, Database, etc.): **Analytics, Crashlytics**
Additional SDKs you are using (Facebook, AdMob, etc.): **Facebook**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Mac**
Platform you are targeting (iOS, Android, and/or desktop): **iOS**
Scripting Runtime (Mono, and/or IL2CPP): **IL2CPP**

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

**After updating the firebase to 6.14.1 we have noticed that no crashes were received in Crashlytics for the new app version. After enabling the debug mode we noticed that we are getting the following logs:**

```
DEBUG: Disable crashlytics
DEBUG: crashlytics app initializer Disabling
[Crashlytics] Version 3.14.0 (144)
Registering Crashlytics exception handlers
Firebase.Crashlytics.ExceptionHandler:Register()
Firebase.Crashlytics.Crashlytics:Initialize()
Firebase.FirebaseApp:InitializeCrashlyticsIfPresent() 
Disable crashlytics
crashlytics app initializer Disabling
```

**When we throw a test exception we get this:**

`Crashlytics recording exception: Test please ignore`

**And when we restart the app we get** 

`[Crashlytics:Crash:Reports] Packaged report with id 'ca7e80b52a2142ed82494d4458bde0d6' for submission`

Here is the code for initialization:

```
public class StartupManager : MonoBehaviour
	{
		public void Awake()
		{
			Debug.Log("StartupManager.Awake");
			DontDestroyOnLoad(this);
			Application.targetFrameRate = 60;
			Application.runInBackground = false;
			CheckFireBase();
			Application.logMessageReceived += OnLogMessageReceived;
		}

		private void OnLogMessageReceived(string logMessage, string stackTrace, LogType type)
		{
			Crashlytics.Log(logMessage);
			LogMessagesStorage.Log(logMessage, stackTrace, type);
		}

		public void Start()
		{
			Debug.Log("StartupManager.Start");
		}

		private static void CheckFireBase()
		{
			FirebaseApp.LogLevel = LogLevel.Debug;
			if (FirebaseApp.CheckDependencies() != DependencyStatus.Available)
			{
				FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => { OnFirebaseInitialized(); });
			}
			else
			{
				OnFirebaseInitialized();
			}
		}

		private static void OnFirebaseInitialized()
		{
			var status = FirebaseApp.CheckDependencies();
			if (status == DependencyStatus.Available)
			{
				FirebaseApp app = FirebaseApp.DefaultInstance;
				Debug.LogError("Firebase was initialized. Status: " + status);
			}
			else
			{
				Debug.LogError("Firebase was not initialized. Status: " + status);
			}
		}
	}
```

Note, we have migrated from fabric before. Can you please confirm that it is ok to have this empty?

![Screen Shot 2020-05-27 at 12 49 10](https://user-images.githubusercontent.com/58180877/82998200-7cb33500-a018-11ea-9dc5-782009125d78.png)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? **Did not try**

What's the issue repro rate? (eg 100%, 1/5 etc) **100%**

**Comment by samedson** [comment]
Hey @vahagn-harutyunyan because you migrated from Fabric, you'll want to put your legacy Fabric API key in that box in the screenshot you posted. I believe your crashes are being dropped because of that.

In addition, in the next release of the Unity plugin this step won't be needed, so you can also wait for the next release and your situation should get fixed.

**Comment by vahagn-harutyunyan** [comment]
Hi @samedson,
Thank you for the answer.

Can you please hint at where we can find the legacy Fabric key? The Fabric web site is not available anymore.
Also, any idea of when the next release will happen?

Thank you in advance.

**Comment by vahagn-harutyunyan** [comment]
Hi @samedson 
This is to confirm that adding the Fabric api key resolved the issue.

**Comment by samedson** [comment]
Great! Next release should be in the upcoming week.
