### ISSUE TITLE
Incorrect code in the documentation for Dynamic Links

### ISSUE THREAD

**Issue by roointan** [firebase/quickstart-unity#692]
### Please fill in the following fields:
Firebase Unity SDK version: 6.13.0

### Please describe the issue here:
The codes in the following document are incorrect:
https://firebase.google.com/docs/dynamic-links/unity/create

**Comment by DellaBitta** [comment]
Hi @roointan,

Which part of the code is causing problems? Thanks!

**Comment by roointan** [comment]
> Hi @roointan,
> 
> Which part of the code is causing problems? Thanks!

For example, Firebase.DynamicLinks.GetShortLinkAsync(components, options) is incorrect,
it should be Firebase.DynamicLinks.DynamicLinks.GetShortLinkAsync()

also Firebase.DynamicLinks.ShortLink, which should be Firebase.DynamicLinks.ShortDynamicLink

There may be more.

**Comment by DellaBitta** [comment]
I've updated the docs in the guide. Thanks again for pointing this out to us.
