### ISSUE TITLE
Duplicate class com.google.firebase.MessagingUnityPlayerActivity

### ISSUE THREAD

**Issue by qbit86** [firebase/quickstart-unity#693]
### Please fill in the following fields:
Unity editor version: 2018.4.10f1
Firebase Unity SDK version: 6.14.1
Source you installed the SDK: FirebaseMessaging.unitypackage from `firebase_unity_sdk_6.14.1.zip`
Firebase plugins in use: FirebaseAnalytics, FirebaseMessaging
Additional SDKs you are using: GoogleMobileAds-v5.1.0, facebook-unity-sdk-7.18.1, etc.
Platform you are using the Unity editor on: Windows and macOS
Platform you are targeting: iOS and Android
Runtime version: .NET 4.x Equivalent
Scripting backend: IL2CPP
API compat: .NET Standard 2.0

### Please describe the issue here:

I updated Firebase Unity plugin, resolved Android dependencies via Android Resolver.
Building on CI-machine (macOS) fails with “duplicate class” error:
> Execution failed for task ':checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
> java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class **com.google.firebase.MessagingUnityPlayerActivity** found in modules classes.jar (:**com.google.firebase.firebase-messaging-unity-6.14.1**:) and libmessaging_unity_player_activity.jar (**libmessaging_unity_player_activity.jar**)

### Please answer the following, if applicable:

What's the issue repro rate? Always.

**Comment by qbit86** [comment]
@DellaBitta Could you please comment on why `MessagingUnityPlayerActivity` was added to **com.google.firebase.firebase-messaging-unity-6.?.?.aar** at some point?
It wasn't there in **6.12.0**, but appeared in **6.14.0**.

It is already present in existing **libmessaging_unity_player_activity.jar** — should I remove it?

**Comment by chkuang-g** [comment]
@qbit86 

We pack `libmessaging_unity_player_activity.jar` into `com.google.firebase.firebase-messaging-unity-6.?.?.aar` since 6.13.0 since it is harder to resolve dependency with loose `.jar` files.

Did you upgrade from an older version of Firebase SDK? If so, it is safe to remove `libmessaging_unity_player_activity.jar` from your `Assets` folder and that should resolve your issue.

Shawn

**Comment by chkuang-g** [comment]
Glad to know :)
