### ISSUE TITLE
Firebase Dynamic Links for Unity escape social meta tag parameters, and double escapes if I escape myself

### ISSUE THREAD

**Issue by roointan** [firebase/quickstart-unity#694]
### Please fill in the following fields:
Unity editor version: 2018.4.22f1
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Crashlytics, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): yet Android for this issue
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
I'm trying to create a Dynamic Link. For me, social meta parameters include space. But if I pass them as is to SocialMetaTagParameters, they will not be URL encoded and link would be broken when retrieving bycomponents.LongDynamicLink.ToString() . sample code:
            SocialMetaTagParameters = new SocialMetaTagParameters()
            {
                Title = 'my title",
                Description = "a sample description",
                ImageUrl = new System.Uri("https://a_url")
            },

I tried encoding the values for Title and Description using System.Uri.EscapeUriString, but then they will be double encoded,
my%2520title instead of my%20title and not usable again.

Does it escape %, but not space?

I'm going to try manually adding values for social meta parameters to the link, I hope it works. 
What's weird is in some Android builds it works correctly. I wonder how is that.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Didn't try, but I see the sample project is using underscores in place of spaces, so probably it's the same!

What's the issue repro rate? (eg 100%, 1/5 etc)
most of the times.

**Comment by roointan** [comment]
Seems like I can't manually add the social meta tags to the long dynamic link.

I actually tried, but if I get a copy of `components.LongDynamicLink.ToString()` and make changes to it and then pass it to `DynamicLinks.GetShortLinkAsync(System.Uri, options)` and try creating a new Uri from the long link, the generated short link won't work as expected.

Touching the short link on a device will not pass the parameter.

but it would work if I use this signature of GetShotLinkAsync -> `DynamicLinks.GetShortLinkAsync(DynamicLinkComponents, options)` (and thus don't have social meta tags)

**Comment by DellaBitta** [comment]
Hi @roointan,

We couldn't reproduce this on 6.15.0, but I just wanted to double check something.  The code above for the title has a mismatch of quotes (single quote and then a double quote).  I just want to ensure that's not what's causing the problem.  Thanks.
