### ISSUE TITLE
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#695]
### Please fill in the following fields:
Unity editor version: 2020.1.0b10.3837
Firebase Unity SDK version: 6.14
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Auth,FireStore,
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook,OneSignal
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
This is not critical issue, but after the build was successed it throw error like this in editor

```
GUID [7da5ed20c5fc4cf4b992c1e2e1b123af] for asset 'Packages/com.google.external-dependency-manager/ExternalDependencyManager/Editor/external-dependency-manager_version-1.2.155_manifest.txt' conflicts with:
  'Assets/ExternalDependencyManager/Editor/external-dependency-manager_version-1.2.155_manifest.txt' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
```

![image](https://user-images.githubusercontent.com/1042507/83392315-1581f000-a41f-11ea-8b38-349fd73b3cf6.png)

It seem it don't have any problem at all but I don't know why it need to have error like these in the first place

### Please answer the following, if applicable:

What's the issue repro rate?

100%

**Comment by chkuang-g** [comment]
@Thaina 

It looks like EDM4U is installed from both UPM and in `Assets` folder. 

If you install any Firebase packages from UPM, EDM4U will be automatically installed through UPM as well. That is why we recommend to remove EDM4U from `Assets` folder BEFORE installing any Firebase SDK from UPM.

This may happen when you install any other packages including EDM4U or PlayServicesResolver in their `.unitypackage`, ex. Facebook, OneSignal.  All you need is to remove those folders (`Assets/ExternalDependencyManager` and/or `Assets/PlayServicesResolver`) from `Assets` folder.  We do not have a good solution to resolve such installation conflict at this point but we will look for some solution to make your life easier.

**Comment by Thaina** [comment]
This is sure helping, Thank you very much
