### ISSUE TITLE
OrderByKey().LimitToLast returns an old DataSnapshot and doesn't return new Keys

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#697]
### Please fill in the following fields:
Unity editor version: 2019.3.6f1
Firebase Unity SDK version: 6.13
Source you installed the SDK : unitypackage
Firebase plugins in use : Auth, sorage
Platform you are using the Unity editor on : Windows, Android

### Please describe the issue here:
I'm trying to receive my last 4 items on my DB (because the last one is the newest item).
`  task3 = await FirebaseDatabase.DefaultInstance.GetReference("users/").OrderByKey().LimitToLast(4).GetValueAsync().ContinueWith(t => t);
 DataSnapshot d = task3.Result;
  foreach (DataSnapshot s in d.Children)
            { Debug.Log(s.Key);}`

This code works fine, I really get my last 4 items,

But then I add a new user to my Users DB from another device and I run the same code above from my first device (Unity Editor) but still get the same 4 items as before without the new one.

The code is correct because if I stop the game on Unity and reset the app, I get the right values.
I can't get the updated values without resetting the app, what am I missing?

Edit: If I remove .OrderByKey().LimitToLast(4) and get all the values without the limitation- I do get the new keys as well, it means there's some issue with the limitation
### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by Whyser** [comment]
Hey @shlighter , can you try this:

```
var query = FirebaseDatabase.DefaultInstance.GetReference("users/").OrderByKey().LimitToLast(4);
query.ValueChanged += (sender, e)=>{
   //do nothing for now
};
query .GetValueAsync().ContinueWith(t => t); foreach (DataSnapshot s in d.Children) { Debug.Log(s.Key);}
```

I had similar issue and this resolved it, but unsure if this is a bug or intended (but figured it might be intended). It's very frustrating to say the least since I don't always wanna listen to the change...

**Comment by shlighter** [comment]
Thanks, yeah I don't want to use listeners, just to get new values. But I have some new information- if I remove .OrderByKey().LimitToLast(4) and get all the values without the limitation- I do get the new keys as well (without any listener),  it means there's some issue with the limitation

**Comment by Whyser** [comment]
Neither do I, but can you confirm if it works if you add the listener? I don't mean that you check the value inside the callback, only that you confirm if the value from GetValueAsync is updated _if_ you have attached an listener?

**Comment by alexames** [comment]
I suspect this is what is happening: When you query the value at a location, it locally caches it. If you're not actively listening on a location, it won't get live updates. If a cached value is present, the cached value will be returned when querying it. Try calling [KeepSynced](https://firebase.google.com/docs/reference/unity/class/firebase/database/query#keepsynced) on that location, it should solve the problem for you.

**Comment by shlighter** [comment]
> I suspect this is what is happening: When you query the value at a location, it locally caches it. If you're not actively listening on a location, it won't get live updates. If a cached value is present, the cached value will be returned when querying it. Try calling [KeepSynced](https://firebase.google.com/docs/reference/unity/class/firebase/database/query#keepsynced) on that location, it should solve the problem for you.

Thanks for your reply,  what's the difference between KeepSynced and a listener (query.ValueChanged)?
if I understand right KeepSynced listens to the data

**Comment by alexames** [comment]
Placing a value on that location means that the registered listener's callbacks will be called each time there is a change. KeepSync'd just ensures that the data is kept up to date but does not result in any callbacks being called. 

(For what it's worth, internally, KeepSync is implemented as a listener on the location that simply does nothing)

**Comment by shlighter** [comment]
Then KeepSynced is better than query.ValueChanged (fewer calls), 
OK thank you, it works- every time I use GetValueAsync- I know it's going to get the most updated value-Is there a way to write it in 1 line?
Where would you insert KeepSynced(true)  it in this line, i tried options and it doesn't let me-
task = await FirebaseDatabase.DefaultInstance.GetReference("users").OrderByKey().LimitToFirst(5).GetValueAsync().ContinueWith(t => t);

Otherwise, it's 3 lines (1-creating a DatabaseReference, 2- use KeepSynced on it 3-ref.GetValueAsync line...)

**Comment by alexames** [comment]
Unfortunately there's no clean on-liner for this. You'll have to set KeepSynced and then perform your operation afterward.
