### ISSUE TITLE
Can i change topic from the UI button??

### ISSUE THREAD

**Issue by holymokee** [firebase/quickstart-unity#7]
when i use "android firebase sdk", i can change topic from the UI button..

void buttonLangKor()
{
  FirebaseMessaging.getInstance().unsubscribeFromTopic("LangKor");
  FirebaseMessaging.getInstance().unsubscribeFromTopic("LangEng");

  FirebaseMessaging.getInstance().subscribeToTopic("LangKor");
}

void buttonLangEng()
{
  FirebaseMessaging.getInstance().unsubscribeFromTopic("LangKor");
  FirebaseMessaging.getInstance().unsubscribeFromTopic("LangEng");

  FirebaseMessaging.getInstance().subscribeToTopic("LangEng");
}

But, when i use "unity firebase sdk", i can't change topic from the UI button..
Instead, i can change topic when the app start time..

void Start()
{
   ....
   InitializeFirebase()
   ...
}

void InitializeFirebase() 
{
        Firebase.Messaging.FirebaseMessaging.Unsubscribe("LangKor");
        Firebase.Messaging.FirebaseMessaging.Unsubscribe("LangEng");

        Firebase.Messaging.FirebaseMessaging.Subscribe("LangKor");
        ....
}

I want to change the topic every time i press the button in the app.

i would appreciate your advice. please help me~~

**Comment by stewartmiles** [comment]
To clarify, you're saying that topic unsubscription / subscription does not work after the messaging API has been initialized?

If so, which platform have you reproduced the problem on?   Is this Android, iOS or both?

**Comment by stewartmiles** [comment]
This is a bug in the C++ SDK (used by the Unity SDK) on Android.

See https://groups.google.com/d/msg/firebase-talk/Cdvbr_WUNXU/cjRcn42IAgAJ for the details.

Unfortunately, there is no workaround for the moment.  I'm putting together a patch now which will be available in our next release.

**Comment by holymokee** [comment]
Thank you for answer.

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

We've updated the Messaging sample with a topic field and subscribe / unsubscribe buttons for you to check out as well. 

Cheers,
Stewart
