### ISSUE TITLE
Can't resolve dependencies when adding new firebase features to an existing ones.

### ISSUE THREAD

**Issue by EricBatlle** [firebase/quickstart-unity#701]
### Please fill in the following fields:
Unity editor version:  2019.3
Firebase Unity SDK version: 6.14.1
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Messaging, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Resolve and Force Resolve always send Resolution Failed (Some conflicting dependencies were found). But it only occurs if I add new package, it doesn't occur if I add them all at the same time.

So if I start a new project, and put them Database, it works, if then I add Auth, it brokes. But If I start a new project, and attach both Auth and Database, it works.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by EricBatlle** [comment]
What I've noticed is that if you import the packages, and unselect the already imported External dependencies, it won't crash.

**Comment by DellaBitta** [comment]
Hi @EricBatlle,

In the Package Manager Resolver after the import of Database do you select "Add to Registries"?  If so, then the package manager resolver will create its own version of the imported asset in its own path.  Unity will see two versions of Database the next time a package is imported: the one from the .unitypackage import and the one from the Package Manager Resolver.  

If you remove the Databae files for  .unitypackage import from the Assets folder then this error should go away.  Please check #695 for more details and to see if this helps with the problem. 
 Thank you.

**Comment by chkuang-g** [comment]
@EricBatlle 
It would be helpful if you can provide the editor log for more information.
