### ISSUE TITLE
How to disable personalized advertising features

### ISSUE THREAD

**Issue by gayanW** [firebase/quickstart-unity#702]
In the [documentation](https://firebase.google.com/docs/analytics/configure-data-collection?platform=android#configure_the_use_of_data) it says:

> To set the default personalized advertising behavior, specify the following field in your app's AndroidManifest.xml in the application tag:

    <meta-data android:name="google_analytics_default_allow_ad_personalization_signals" android:value="false" />

I have two AndroidManifest.xml files in my assets directory:

```
Assets/Plugins/Android/Firebase/AndroidManifest.xml
Assets/Plugins/Android/GoogleMobileAdsPlugin/AndroidManifest.xml

```
Will adding the meta tag to `Assets/Plugins/Android/Firebase/AndroidManifest.xml`  disables personalized advertising features?

---

If I understood correctly this only indicates that data collected by Firebase Analytics are not available for personalized advertising. So for instance I also use Admob SDK to serve ads. This won't disable personalized ads in Amob itself, right?

**Comment by DellaBitta** [comment]
Hi @gayanW,

Your correct in that those Analytics settings are not respected by AdMob.  Please see the [Unity Admob guide for Targeting](https://developers.google.com/admob/unity/targeting#request_configuration) and [Guide for EU Consent](https://developers.google.com/admob/unity/eu-consent) for similar configurations to what I think you're attempting to setup here.

Thanks.

**Comment by DellaBitta** [comment]
Hi @gayanW,

I'm going to close this issue for now.  Please feel free to mention me or reopen the issue if you have any further questions on the subject.  Thanks!
