### ISSUE TITLE
Firestore ConvertTo not working in iOS 

### ISSUE THREAD

**Issue by amoswazana** [firebase/quickstart-unity#703]
Unity editor version: 2019.2.15f1
Firebase Unity SDK version: 6.12.0
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Analytics, Auth, DynamicLinks, Firestore, Functions, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Admob, Photon, GPGS
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
**Firestore ConvertTo function fails when converting map-type fields from DB to Dictionary<string, double>. Works fine in Unity editor.**
I am trying to convert a bunch of product documents with a map-type field containing their price by currency.
Example product JSON:
`{
  "CoinValue":10000,
  "Currency":{
    "EUR":3.01,
    "USD":3.01
  },
  "SKUSuffix":".coin.10000"
}`

The Unity code:
```c#
    public void GetProductDatas() {
        Firebase.Firestore.Query productsQuery = db.Collection("Shop/Products/AllProducts");
        productsQuery.GetSnapshotAsync().ContinueWithOnMainThread((t) => {
            foreach (DocumentSnapshot docSnap in t.Result.Documents) {
                try {
                    Product product = docSnap.ConvertTo<Product>();
                    Debug.Log("product: " + product);
                } catch (Exception ex) {
                    Debug.Log("exception in converting: " + ex.Message);
                }
            }
        });
    }  

    [FirestoreData]
    [Serializable]
    public class Product {
        [FirestoreProperty("CoinValue")]
        public int CoinValue { get; set; }

        [FirestoreProperty("SKUSuffix")]
        public string SKUSuffix { get; set; }

        [FirestoreProperty("Currency")]
        public Dictionary<string, double> Currency { get; set; }

        public override string ToString() {
            string currencies = "";
            foreach (var key in Currency.Keys) {
                currencies += key + ": " + Currency[key] + ",";
            }
            return string.Format("SKUSuffix: {0}, CoinValue: {1}, Currencies: {2}", SKUSuffix, CoinValue, currencies);
        }
    }
```

In editor this above function returns fine with the products properly converted. One of the products for example:
`product: SKUSuffix: .coin.10000, CoinValue: 10000, Currencies: CAD: 3.99,GBP: 2.99,CHF: 3.01,JPY: 370.01,EUR: 3.49,AUD: 4.49,HKD: 23.01,ILS: 10.9,KRW: 3900.01,PLN: 13.99,RUB: 229.01,USD: 2.99,`

In Android and iOS however, the above function returns the following exception for each product:
`exception in converting: **Attempting to call method 'Firebase.Firestore.Converters.ConverterCache::CreateDictionaryConverter<System.Double>' for which no ahead of time (AOT) code was generated.**`

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Not applicable

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by wilhuff** [comment]
HI @amoswazana, thanks for writing in and sorry for the trouble with this.

We've done considerable work on converters since 6.12.0. Does this issue still occur in 6.15.0?

**Comment by amoswazana** [comment]
You are totally right. Updating solved this issue...
Thanks for the help :)
