### ISSUE TITLE
Fetching keys from remote

### ISSUE THREAD

**Issue by tharak** [firebase/quickstart-unity#71]
Hi, I'm trying to fetch the keys from my remote but nothing comes from it.
I did the following:
1- cloned https://github.com/firebase/quickstart-unity
2- opened quickstart-unity-master/remote_config/testapp on unity
3- imported FirebaseRemoteConfig.unitypackage into project
4- created a project on https://console.firebase.google.com/
5- added iOS and android app on the project
6- created Remote Config param "user_os" with conditions for based on OS type and default 
7- downloaded GoogleService-Info.plist and google-services.json and copied to Assets folder
8- switched platform for android (Firebase's unity plugin says Android and iOS are "Ready to use")
9a- Play on Editor
10a- Click Fetch (print: Fetching data..., fetch completed successfully!, Remote data loaded and ready.)
11a- Click Display Current Data (print: Current Data: config_test_string: default local string, config_test_int: 1, config_test_float: 1, config_test_bool: False) 

9b- Build and run on device
10b- Click Fetch (print: Fetching data..., fetch completed successfully!, Fetch failed for unknown reason)

I also tried creating a new project but ended up with the same results.

Tharak

**Comment by johnb003** [comment]
First of all, the implementation used inside of the editor is only a stub. It reports success but it isn't actually doing anything.

So there's an error, did you get an info from the log? (adb logcat when running)
Are there any error messages when you build and run in the Editor Log?
Also what device are you running on?
Are you trying to use a specific ABI target or the universal ABI?
What version of the firebase plugin are you using?

**Comment by tharak** [comment]
I took a look at logcat and found out some errors that lead me to other errors, so I decided to take a step back and test only the analytics as it seems easier. After I make it work I will try the config again.

Thank you.

**Comment by johnb003** [comment]
If your issue reappears, feel free to re-open the bug.

**Comment by tharak** [comment]
tried again and it didnt work, switched to iOS and it worked after some problems with cocoapods.
