### ISSUE TITLE
FCM messages not received after user disables Push Notifications on iOS

### ISSUE THREAD

**Issue by novavision** [firebase/quickstart-unity#711]
### Please fill in the following fields:
Unity editor version: 2019.3.13f1
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Cloud Messaging, Analytics, Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): Faceboo, AdMob
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS/Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
If user disable push notifications in App settings on iOS after he accepted 1st time Push Notification request (native popup dialog) FCM messages received ONLY if app is in foreground. FCM contains gameplay related data which should be used silently, without obligate push notifications permission. I assumed it should be cached and sent to the user when FCM initializes on app start. Is it expected behaviour, or it's a bug?

### Please answer the following, if applicable:
Yes

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by patm1987** [comment]
Hi @novavision ,

This does appear to be working as intended - if the user denies your game access to push notifications there's little Firebase can do to work around this.

Further, when considering how to work around this issue, note that messages coming in on the foreground are probably relying on "directChannel" - [which has been deprecated](https://github.com/firebase/firebase-ios-sdk/pull/4710/files).

If players blocking this permission is game breaking, you may want to consider [Realtime Database](https://firebase.google.com/products/realtime-database) if you're sending messages in response to gameplay, [Remote Config](https://firebase.google.com/products/remote-config) if you're tweaking the gameplay in response to analytics data, or [Dynamic Links](https://firebase.google.com/products/dynamic-links) if you're building incentivised rewards that a player can acquire outside of your game.

I hope that helps!

--Patrick
