### ISSUE TITLE
"The password is invalid" exception after unlink and re-authentication

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#717]
### Please fill in the following fields:
Unity editor version: 2019.3.15f1
Firebase Unity SDK version: 6.15.0
Source you installed the SDK (.unitypackage or Unity Package Manager): unitypackage
Firebase plugins in use (Auth, Database, etc.): Auth, Firestore, Crashlytics, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AdMob, Tapdaq, GetSocial
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
I implemented email/password authentication with Firebase Auth the following way:
1. User starts the app for the first time and an anonymous account is created
2. At a later point, users can decide to convert their anonymous account into an email/password based account with
```
Credential credential = EmailAuthProvider.GetCredential(email, password);
FirebaseUser = await FirebaseUser.LinkWithCredentialAsync(credential);
```
3. After converting their account, users have the option to unlink their account again with `FirebaseUser.UnlinkAsync(providerID);`, where `providerID` is `EmailAuthProvider.ProviderId` ("password"). After this, the account should fall back to the anonymous account.
4. When the user now decides to log back into his account with 
```
Credential credential = EmailAuthProvider.GetCredential(email, password);
FirebaseUser = await FirebaseUser.LinkWithCredentialAsync(credential);
```
the following exception is thrown:
`FirebaseException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.`
5. Because of this, I'm trying to sign the user back in with
`firebaseAuth.SignInWithCredentialAsync(credential);`
but this throws the error: `FirebaseException: The password is invalid or the user does not have a password.`

When checking the Firebase Auth dashboard, the user account's `Provider` field is empty after step 3, so not even the anonymous icon is shown anymore.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Didn't try, as this is probably not an issue with my project but with how the SDK works.

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by a-maurice** [comment]
Hi @Nyankoo 

I believe this is expected behavior.  The user adds password auth, then removes password auth.  If they then try to login with password auth, it would fail because the password auth was just unlinked.  Does that make sense, or am I missing something that you are trying to do?  If you have a code snippet that covers the bug fully, that'd be ideal, to get a sense on what the problem is.

**Comment by Nyankoo** [comment]
@a-maurice I'm sorry, I forgot to write one step down in the post above. I corrected step 4 and added step 5 above, but here is what I added:

4. When the user now decides to log back into his account with 
```
Credential credential = EmailAuthProvider.GetCredential(email, password);
FirebaseUser = await FirebaseUser.LinkWithCredentialAsync(credential);
```
the following exception is thrown:
`FirebaseException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.`
5. Because of this, I'm trying to sign the user back in with
`firebaseAuth.SignInWithCredentialAsync(credential);`
but this throws the error: `FirebaseException: The password is invalid or the user does not have a password.`

**Comment by chkuang-g** [comment]
Sorry for the late reply.

We will ping the Auth team for more information.

**Comment by patm1987** [comment]
To follow up with @chkuang-g , we are actively investigating this issue.

I've gathered two suggested workarounds though, I'd love to know if they help:
a) consider linking unidirectional for now. That is, anonymous->linked account, you're now that linked user and you shouldn't use the anonymous account again (actually, you can't re-sign-in as an anonymous user. `SignInAnonymouslyAsync` _always_ creates a new user even if it's on the same install on the same device).

b) You can try re-signing-in as an anonymous user before `SignInWithCredentialAsync`. If this fixes the issue, this is still a bug but could be a temporary workaround (as noted above, if you `SignInAnonymouslyAsync`, this will be a new user you're linking to so you'll want some way to migrate data if there is any. Note that unlike other platforms, the implementation of FirebaseUser is such that you _cannot cache it_ Unity side).
