### ISSUE TITLE
Help with crash data in dashboard

### ISSUE THREAD

**Issue by marad747** [firebase/quickstart-unity#718]
### Please fill in the following fields:
Unity editor version:  2019,2,12
Firebase Unity SDK version:  6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): unitypackage 
Firebase plugins in use (Auth, Database, etc.): Analytics+crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): no
Platform you are using the Unity editor on (Mac, Windows, or Linux): windows
Platform you are targeting (iOS, Android, and/or desktop): ios\android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP
i have strange crash deta in my dashboard. Can you help me to fix crashes?
![image](https://user-images.githubusercontent.com/20600166/85691460-33203d80-b6dd-11ea-878d-667b2adf0b35.png)
![image](https://user-images.githubusercontent.com/20600166/85691498-3a474b80-b6dd-11ea-91fd-f2d87bea4758.png)

**Comment by a-maurice** [comment]
Hi @marad747 

Unfortunately, that isn't enough information to track down the problem.  My one assumption would be a problem with google play services on those devices, which can occasionally cause problems like that.  You can read a bit more about it, and how to do that check here: https://firebase.google.com/docs/unity/setup#confirm-google-play-version
