### ISSUE TITLE
Executing Unity code on Firebase async task callbacks (e.g. Continue With) will always crash thread on Android and iOS on .Net 4

### ISSUE THREAD

**Issue by EJAugust** [firebase/quickstart-unity#722]
### Please fill in the following fields:
Unity editor version: 2018.4.23f1
Firebase Unity SDK version: 6.15.0
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Auth, Dynamic Links, Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Adjust, Native Share
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac and Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
This issue took our team a week to solve and we missed our production deadline. Crashes were inconsistent across platforms, across STR, and device logs did not contain useful information, as they don't contain any information to indicate that the issue is firebase related.

The issue occurs on executing code from inside the ContinueWith of any Firebase async method. Executing unity code or methods on other third party plugins on .Net 4 will crash 100% of the time and across all platforms Code executed from ContinueWith does not execute on the main thread in .Net 4. Executing any unity code or code from other plugins will always crash the thread unless it's coming from the main thread. 

In .Net 3.5, this is not a problem, because ContinueWith executes on the main thread. We migrated from .Net 3.5 to .Net 4 and did not expect this change in behavior. Once we identified that it was caused by the multithreaded firebase tasks, we needed to rewrite significant portions of our code to accommodate catching the information from the firebase callbacks on the main thread. 

Even with firebase set to verbose logging, we found no useful information in the logs to indicate that this is a firebase issue. It was only through a lot of trial and error that we were able to produce consistent STR and identify the culprit.

After we narrowed it down to firebase's async calls on .Net 4, we went searching for information about that. We found very little information on this issue, except for this issue and a couple of issues that link back to this issue:

https://github.com/firebase/quickstart-unity/issues/261#issue-386686333

The above link contains a workaround somewhat similar to the changes we needed to make (catching Firebase callbacks on a game object Update to bring them into the main thread) but it is not an elegant solution and we aren't too excited about it, although we are glad to be up and running again.

We had a lot of firebase features running in .Net 3.5 but we needed to migrate to .Net 4 to support some vital third party plugins that have stopped supporting .Net 3.5. The Firebase documentation indicated to us that migrating to .Net 4 required only changing the plugin packages to their .Net 4 versions, but that was far from the case for us as we had to overhaul code to support different behavior across the two that was not made clear from the documentation.

We are dealing with this issue on the latest 6.15.0, but I can confirm that the issue goes back far into the older versions of Firebase, as integrating older versions was part of our trial and error attempts to fix this. 

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Did not attempt, but most likely. 

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

These are the questions that I hope the Firebase developers can answer for myself and future developers having this known issue who come across this post:

1. Has a more elegant solution to this problem been found? I see it has been a known issue to Firebase for 2 years and am wondering if in that time a new solution has been found or if the aforementioned workaround is still the one that the firebase developers recommend. Ideally, we would like to see a solution for this that is internal to the SDKs as it would clean up our code base significantly. 

2. Are there any pages in the Firebase documentation that detail this known issue and it's workaround? I personally was not able to find it. If it doesn't exist or is in an obscure place, I think there's an opportunity there to save developers some time by providing a warning, perhaps on this page:

https://firebase.google.com/docs/unity/setup

A statement saying "Warning: If migrating from .Net 3.5 to .Net 4, take note that ContinueWith will not execute on the main thread, and may have unexpected behavior" would have really helped us save some time. That page does mention that Firebase on .Net 4 is experimental, but that statement alone is too vague and it didn't help our team.

3. Are there any logs from the plugins that say that unexpected behavior can occur when executing ContinueWith from firebase callbacks in .Net 4? I was not able to see any when using DynamicLinks and with firebase logging set to verbose, but I also see in the documentation that some of the firebase plugins don't respond to that global logging setting so maybe that log is there and I just don't know how to enable it. If there isn't one, I think there's another great opportunity there to steer developers in the right direction when they encounter this issue.

Until there is a fix integrated into Firebase for .net 4, a log at least hinting at this multithreading problem which would log out when executing one of the async methods, would appear just above the thread crash itself and would make the issue a lot faster to diagnose and fix. 

Thanks,
- Eric

**Comment by Wrathlife** [comment]
Greetings,

I was experiencing similar issue, and the fix is mentioned in firecast video here: [https://www.youtube.com/watch?v=5GzFDXvZxKM&feature=youtu.be&t=83](url)

**Comment by alexames** [comment]
Hi @EJAugust, 

Sorry that you ran into this issue, and sorry that it's taken so long to reply. 

The short version of the story here is that .Net 3.5 doesn't have a standard Task class we could use, so we used a non-standard implementation instead. To make the code run as seamlessly as possible, we automatically use the standard Task in the 4.0 implementation. `ContinueWith` doesn't specify which thread that it will run on, the fact that in 3.5 it was always on the main thread was a quirk of the implementation, but it wasn't supposed to be part of the contract of the function. However, if you rely on that behavior, it can certainly be a shock when using the standard implementation that's used in 4.0. 

Because this is a common need, we have an extension method that can be used to force it to run on the main thread:

https://firebase.google.com/docs/reference/unity/class/firebase/extensions/task-extension

By using ContinueWithOnMainThread you can be sure that your continuations will run where you expect them to.

There is a [blog post](https://firebase.googleblog.com/2019/07/firebase-and-tasks-how-to-deal-with.html) (and [related video](https://www.youtube.com/watch?v=5GzFDXvZxKM)) that discuss the ins and outs of using async logic in unity.

I'll look into improving our docs to call out this change in behavior to help others who run into this issue. I'm going to go ahead and close this issue, but if you're still having problems feel free to re-open this issue or start a new one.
