### ISSUE TITLE
FireBase 6.15.1 with UPM causes shasum check fail and compilation issue.

### ISSUE THREAD

**Issue by MagicMiikka** [firebase/quickstart-unity#728]
### Please fill in the following fields:
Unity editor version: 2018.4.23f1 / 2019.4.3f1
Firebase Unity SDK version: 6.15.1
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): see attachment
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, IronSource + Adapter
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android/iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
Package Manager started to throw errors on project open:
(Popup pre-launch and in UPM
![image](https://user-images.githubusercontent.com/49847631/87132707-efadfd80-c29e-11ea-9c8d-9dea645d44fb.png)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Did not try.

What's the issue repro rate? (eg 100%, 1/5 etc)
100% Started first on our CI and then after clearing UPM cache from local machine reproed 100% there too.

### Workaround
* Downgrading to 6.15.0 (as per attachment has no issues)

**Comment by epsmarkh** [comment]
We are seeing the same on most of our systems here too. Oddly a few PCs do not show the error or were fixed by zapping the local cache files but reverting to 6.15.0 was the only solution that worked for everyone. Downloading the files manually and checking the checksums shows they are mismatched in the repository.

**Comment by Thaina** [comment]
Didn't we have 6.15.2 already? Did you have try that?

**Comment by MagicMiikka** [comment]
> Didn't we have 6.15.2 already? Did you have try that?

Yes, 6.15.2 seems to also resolve the issue and we are testing that in our next build.
Ideally, these would not regress server side and break all validated build pipelines on demand 🍿

**Comment by alexames** [comment]
As mentioned, this issue should be resolved in 6.15.2. Sorry for the regression here.
