### ISSUE TITLE
Firebase Dynamic Links not calling DynamicLinkReceived callback

### ISSUE THREAD

**Issue by dex3r** [firebase/quickstart-unity#730]
### Please fill in the following fields:
Unity editor version: 2019.4.2f1 (LTS)
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): App, Authentication, Dynamic Links, Remote Config, Cloud Firestore, Cloud Functions
Additional SDKs you are using (Facebook, AdMob, etc.): com.unity.ads, unity in-apps (basically only Untiy + Firebase)
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP/.NET 4.x

### Please describe the issue here:
Whenever I use the Dynamic Link I have created, the app is properly launching (or focusing from background) or I am redirected to Google Play Store. However, I cannot in any way fetch that link from withing the app. `DynamicLinkReceived` callback is never called.
The app itself is still in internal tests phase but has already been published and reviewed on Google Play. 

DynamicLinks code: https://pastebin.com/2frcS12T
I am calling `GetReferralUserID` after initializing Firebase and logging in (which all works flawlessly).

logcat: https://pastebin.com/ZMG7HVRW
As you can see 'Subscribed to received deep link event' is logged, but no event ('Received dynamic link.') is called.

I tried everything I could think of. Building dev version and prod version. Installing apk myself, uploading abb to internal tests via Google Play console. Using links with and without parameters. Nothing. The callback is never, ever called.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)
10/10

**Comment by alexames** [comment]
Have you tried repro-ing this using the dynamic links quickstart app? The easiest way to debug this would be to start from a known good state, so if you can give that a try we can diagnose the issue from there.

**Comment by dex3r** [comment]
_Whenever you see "??" there should be my app info I have censored for privacy reasons_

Ok I have tried running the quickstart-unity\dynamic_links\testapp using Unity 2019.4.5f1. I used my existing bundle ID and already registered app (again: Firestore, Authentication and Functions are working without a hitch). Following the [tutorial](https://github.com/firebase/quickstart-unity/blob/master/dynamic_links/testapp/readme.md) I've assigned this bundle ID in Untity, and in "UIHandler" I've assigned "Domain Uri Prefix" (??.page.link). I've downloaded "googe-services.json". I am using the same keystore as in my own app.

After building the app and using my already existing Dynamic Link ("https://??.page.link/??") the app is opening up (as before). This time, however, the event is called, but without information about my original link nor it's parameters. The log says:
"Received dynamic link https://play.google.com/store/apps/details?id=??.??.??". The link parameters (?param=value) are essential too me, so no real progress there yet.

Also, while generating short link from example I have some warnings:
`Param 'at' is not needed, since 'isi' is not specified. [https://firebase.google.com/docs/dynamic-links/create-manually#ddl_parameters]`
`Param 'ct' is not needed, since 'isi' is not specified. [https://firebase.google.com/docs/dynamic-links/create-manually#ddl_parameters]`
` Param 'pt' is not needed, since 'isi' is not specified. [https://firebase.google.com/docs/dynamic-links/create-manually#ddl_parameters]`
`We could not find bundle ID '??.??.??' in this Google project. [https://firebase.google.com/docs/dynamic-links/debug#app-not-in-project]` <-- the most worrying one.
`We could not find iPad bundle ID '??.??.??' in this Google project.` <-- I have not sed any apple IDs yet and runnig the example on Android anyway.

The generated short link, when clicked, is opening up "mysite/fallback" so it does not seem to work.

**Comment by dex3r** [comment]
Ok i figured out what the difference between my app and test app was. I use Proguard and test app do not. When I switched the test app Unity Minify options to Proguard I have the same problems. I guess I have to add Proguard config now to keep Firebase API intact. 

Using this: https://github.com/firebase/quickstart-unity/issues/429#issuecomment-585410451 I partially fixed is.

My only problem now is, that I click on link like this:
`https://??.page.link/experiment/?u=jfXsxIpT1OQZZmxonOwKjvtfK3T2`
when the app is bring back from background I got this:
`https://play.google.com/store/apps/details?id=??.??.??`
so all parameters (`u=jfXsxIpT1OQZZmxonOwKjvtfK3T2`) info is lost and that was the whole point of implementing this was.

Does this mean, that tutorial from here: https://firebase.google.com/docs/dynamic-links/use-cases/rewarded-referral#java_4 
Can only be used in native Android Java SDK and not in Unity itself?

**Comment by vimanyu** [comment]
@dex3r,
Thanks for figuring out the differences with Proguard builds. We will look into it. 
As far as encoding user parameters in your dynamic link, I tried it in the test app, and could retrieve my custom url in the following manner,
```
      return new DynamicLinkComponents(
        // The base Link.
        new System.Uri("https://example.url.com/search?q=something"),   <----- This is where you can place your user id link
        // The dynamic link domain.
        kDomainUriPrefix) {
        GoogleAnalyticsParameters = new Firebase.DynamicLinks.GoogleAnalyticsParameters() {
          Source = "mysource",
          Medium = "mymedium",
          Campaign = "mycampaign",
          Term = "myterm",
          Content = "mycontent"
          ...
```

And I could see this custom link show up as it is in the testapp's listener,
```
    // Display the dynamic link received by the application.
    void OnDynamicLink(object sender, EventArgs args) {
      var dynamicLinkEventArgs = args as ReceivedDynamicLinkEventArgs;
      DebugLog(String.Format("Received dynamic link {0}",
                             dynamicLinkEventArgs.ReceivedDynamicLink.Url.OriginalString));
    }
```
One difference is that I followed the tutorial exactly (package name set to "com.google.FirebaseUnityDynamicLinksTestApp.dev
") and didnt use a custom bundle ID.

**Comment by dex3r** [comment]
@vimanyu thank you for your response. However I cannot still solve my problem. Please, help me understand how it works and how to do it correctly.

I cannot really find information what the first `DynamicLinkComponents` parameter is. "The base Link.". The base link to what? I guess to my website? But I don't use my website, I just want to open the app using the link generated from Firebase Console in Dynamic Links section (where I have set up social media tags etc.)

How do I do that? I tried a few things.  To make things simpler let's assume my app is called MYAPP and my bundle id is MY.APP.COM. In Firebase Console in Dynamic Links i have created a link (without custom domain). Lets say the URL is "https://MYAPP.page.link/experiment". When I click on it on device my app is opening, if MYAPP is not installed then I am redirected to the store. Social media tags are working. PERFECT. However, I want to use custom parameter, u=123456789. If I click on link "https://MYAPP.page.link/experiment?u=123456789" the app is opening up with ReceivedDynamicLink.Url.OriginalString: "https://play.google.com/store/apps/details?id=MY.APP.COM". My parameter is lost. 

So I tried using Dynamic links in Unity like this:

```
      return new DynamicLinkComponents(
        new System.Uri("https://MYAPP.page.link/experiment?u=123456789"),
        kDomainUriPrefix) {
```

But it gives me a warning: "Param 'link' should not be on FDL domain." Also, when I clink on the generated link ("https://MYAPP.page.link/y9xdcbm7xTxMuxAQx") it's opening my app with ReceivedDynamicLink.Url.OriginalString: "https://play.google.com/store/apps/details?id=MY.APP.COM" Again: I only want to open the app, I don't care about fallback, I don't want to use my custom domain.

**I can create fully working, long link by hand**. It looks like this:
https://MYAPP.page.link/?apn=MY.APP.COM&link=https://MYAPP.page.link/experiment/?u=123456789

It's social tags are working, it's opening the app, the ReceivedDynamicLink.Url.OriginalString is valid (https://MYAPP.page.link/experiment/?u=123456789). I guess I can just hardcode this link in my app and just change "u" parameter. But is there Is there a way to shorten it from withing the app?

Thanks again.

**Comment by vimanyu** [comment]
Hi @dex3r,
Just letting you know that I am still looking into this. 

Here are my quick thoughts though,
- "base link" in DynamicLinkComponents is the same as "deep link" mentioned in other places
https://firebase.google.com/docs/dynamic-links/create-manually#parameters

- In general, custom parameters should be appended to the "deep link" and not "dynamic link (short or long)". I am not surprised the API doesnt allow you to have a deep link from the same domain. That could cause issues of recursion. Also, a short link encodes the entire deep link within it. So allowing more parameters on the short link can have interesting cases to think about. What if the deep link already had "?u=1234" and you added this parameter to short link also?

I am finding out if there is any possibility of saving social tags in a link in the console and somehow encoding custom parameters in the deep link contained within the dynamic link which you create via the API in code. One way of doing that could be via "Remote Config' too. You could define these social tags with well named keys and fetch them in your application. That way, you can tweak these variables via console and the code directly reads off them.

**Comment by vimanyu** [comment]
Would Remote config workflow work for you?

**Comment by dex3r** [comment]
Yes, I will probably use that. But I will generate links in an incorrect way, with warnings and ignoring Firebase Console social tags. Feels more like major workaround than actual solutions/using API properly if you ask me ;)

**Comment by patm1987** [comment]
Hi @dex3r ,

Let me know if this makes sense:
You should be able to mirror the logic in the tutorial you linked. For example:
```
val user = Firebase.auth.currentUser!!
val uid = user.uid
val invitationLink = "https://mygame.example.com/?invitedby=$uid"
Firebase.dynamicLinks.shortLinkAsync {
    link = Uri.parse(invitationLink)
    domainUriPrefix = "https://example.page.link"
    androidParameters("com.example.android") {
        minimumVersion = 125
    }
    iosParameters("com.example.ios") {
        appStoreId = "123456789"
        minimumVersion = "1.0.1"
    }
}.addOnSuccessListener { shortDynamicLink ->
    mInvitationUrl = shortDynamicLink.shortLink
    // ...
}
```

Should become something like:
```
var userId = FirebaseAuth.DefaultInstance.CurrentUser.UserId;
var invitationLink = $"https://mygame.example.com/?invitedby={userId}";
var components = new DynamicLinkComponents(new Uri(invitationLink), "https://example.page.link") {
    AndroidParameters = new AndroidParameters("com.your.package.name") {
        MinimumVersion = 125
    },
    IOSParameters = new IOSParameters("com.your.package.name"){
        AppStoreId = "123456789",
        MinimumVersion = "1.0.1"
    },
    SocialMetaTagParameters = new SocialMetaTagParameters() {
        // this isn't in the tutorial, but you ask about them above
        Title = title,
        Description = description,
        ImageUrl = imageUrl
    }
};
DynamicLinks.GetShortLinkAsync(components).GetShortLinkAsync().ContinueWithOnMainThread(task=>{
    // do stuff with task.Result here
});
```

This would give you the custom parameter and use the pre-built social tags.

To @vimanyu 's point, once you generate a link, you shouldn't add parameters to it (the parameters are in the `linkTarget`). This should be a valid URL that can be opened when not on a device (ie: opening a dynamic link in the browser will open this site). If you do want to generate a link in the console with a custom target, you would use this UI:
![image](https://user-images.githubusercontent.com/1111611/89958027-26589a00-dbf6-11ea-8114-3d052ea5a93c.png)

If I'm understanding that you want to create a link outside of the game (ex as if in the console) but with a bunch of custom `?u=` parameters, you will either need to touch the [REST endpoint](https://firebase.google.com/docs/dynamic-links/rest) or use the [manual URL construction](https://firebase.google.com/docs/dynamic-links/create-manually) with the `?link=` parameter filled out and properly escaped. There's an informative looking medium post that could help [here](https://medium.com/the-andela-way/creating-firebase-dynamic-links-with-firebase-cloud-functions-e96d1713530f).

I would expect you to get warnings related to missing package id's &c until you register them all (iOS and Android) on the Firebase console.

Finally, if you think a URL is being constructed wrong, append the `?d=1` parameter to the end of it as mentioned [here](https://firebase.google.com/docs/dynamic-links/create-manually#debugging_a_url). This will let us see the graph of what's happening and maybe see where your custom parameter is disappearing if the issue persists (ie: if I missed stuff leading up to this post and am giving you redundant information, this could be a good next step).

Let me know if that helps!
