### ISSUE TITLE
FCM not working on iOS development build

### ISSUE THREAD

**Issue by novavision** [firebase/quickstart-unity#733]
### Please fill in the following fields:
Unity editor version: 2019.3.13
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): unitypackage
Firebase plugins in use (Auth, Database, etc.): Crashlytics, Messaging, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook. AdMob, IronSource
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS/Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
FCM not received or received randomly (after some manipulations enabling/disabling notifications in app settings) in development build OR production build deployed by USB connection from XCode. TestFlight builds works perfectly.
I use APN key for push setup in Firebase console, but this problem occurred using legacy .p12 dev/production certificates as well. 
Googled trying to find the problem, but no results. Settings the additional keys to .plist, like `FirebaseScreenReportingEnabled` and `FirebaseAppDelegateProxyEnabled ` didn't affect as well. What's the problem with it?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes

What's the issue repro rate? (eg 100%, 1/5 etc).
Hard to say. It never works on 1st app start, and sometimes disabling/enabling notification in native app settings during the app session helps, sometimes not.

**Comment by chkuang-g** [comment]
@chliangGoogle Could you offer some insights about what may cause the inconsistent behavior?

AFAIK, Unity SDK 6.13.0 is using iOS SDK 6.17.0, while the latest (6.15.2) is using iOS SDK 6.24.0.
I did not see any release note that is relevant to this.
https://firebase.google.com/support/release-notes/ios

**Comment by chliangGoogle** [comment]
Can you elaborate more on the behavior of the issues? What do you mean receive randomly? Is there a delay or not receiving at all?

**Comment by novavision** [comment]
I think I found the issue - this happens if you didn't remove the app from the device before installing new dev or production build using USB connection. Not likely related to FCM

**Comment by chliangGoogle** [comment]
Please reopen the issue if you see anything unusual on fcm side. Thanks!
