### ISSUE TITLE
Unable to copy firebase to GeneratedLocalRepo when Forced Resolve

### ISSUE THREAD

**Issue by pogsdbest** [firebase/quickstart-unity#734]
### Please fill in the following fields:
Unity editor version: 2019.3.13f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Firebase App, Firebase Cloud Messaging
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AdMob, GoogleSignin
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows10
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
1.installed EDM4U 1.2.156.
2.installed Facebook, Admob, GoogleSignin via .unitypackage
3.forced resolve working properly. and GeneratedLocalRepo has a folder inside, but only for GoogleSignin
4.installed Firebase App and Firebase Messaging via package manager. both or Firebase App alone. same error.
5.forced resolve failed. with the error. below. 

`Unable to copy Packages\com.google.firebase.app\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar to Assets/GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.aar.  Assets/GeneratedLocalRepo\Firebase\m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.aar will not be included in Gradle builds. Reason: Source file Packages\com.google.firebase.app\Firebase/m2repository\com\google\firebase\firebase-app-unity\6.15.2\firebase-app-unity-6.15.2.srcaar not found.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\Logger.cs:136)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:990)
GooglePlayServices.GradleTemplateResolver:CopySrcAars(ICollection`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\GradleTemplateResolver.cs:134)
GooglePlayServices.GradleTemplateResolver:InjectDependencies(ICollection`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\GradleTemplateResolver.cs:312)
GooglePlayServices.<ResolveUnsafe>c__AnonStorey9:<>m__1() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1850)
Google.RunOnMainThread:ExecuteNext() (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction(Action) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:530)
Google.RunOnMainThread:Run(Action, Boolean) (at Z:\tmp\tmp.Loyh5konAN\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:472)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1849)
GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterPromptCheck(Action`1, Boolean, Boolean, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1763)
GooglePlayServices.<ResolveUnsafeAfterJetifierCheck>c__AnonStorey7:<>m__0(Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1674)
GooglePlayServices.<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__1(ApiLevelJetifierResult) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2594)
GooglePlayServices.PlayServicesResolver:CheckApiLevelForJetifier(Boolean, String, Action`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2558)
GooglePlayServices.<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__0(Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2579)
GooglePlayServices.PlayServicesResolver:CheckGradleVersionForJetifier(Boolean, String, Action`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2486)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String, Action`1) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2577)
GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterJetifierCheck(Action`1, Boolean, Boolean, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1671)
GooglePlayServices.<ScheduleResolve>c__AnonStorey5:<>m__0() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1638)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1495)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1651)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve(Boolean) (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1904)
GooglePlayServices.PlayServicesResolver:MenuForceResolve() (at Z:\tmp\tmp.glyoHcYR53\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1928)`

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

tried, to reproduce on a clean project. but it didn't happen. this only happen on my working project.

What's the issue repro rate? (eg 100%, 1/5 etc): 100%

**Comment by chkuang-g** [comment]
You seems file ticket on EDM4U as well 
https://github.com/googlesamples/unity-jar-resolver/issues/392

Since this is an EDM4U issue, I will close this one for now.
