### ISSUE TITLE
Dynamic Links again! Sorry

### ISSUE THREAD

**Issue by MartinGonzalez** [firebase/quickstart-unity#736]
Unity editor version: 2018.4.16
Firebase Unity SDK version: 
Source you installed the SDK (.unitypackage or Unity Package Manager): UPM
Firebase plugins in use (Auth, Database, etc.): Messaging, DynamicLinks, Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS/Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

I'm really, but really sorry to bring this topic again but I cannot make Dynamic links work in iOS > 13 and things are getting really dark.
I've been searching issues, stackoverflow, apple forums everywhere! And I cannot open the app with dynamic links.

* firebase project is well configured
* TeamId is set
* associate domain capability is set with the correct `applinks:mydomain.bla.bla`
* Deleted and restarted the app didn't work
* Erasing Safari cache didn't work
* I'm not using appsflyer (I'm but I removed it to test)
* https://search.developer.apple.com/appsearch-validation-tool is telling this about the apple-app-site provided by firebase
(both /.well-known and common apple-app-site path)
![image](https://user-images.githubusercontent.com/4130008/87984152-ea775c80-caaf-11ea-83fe-7940ee85a05c.png)
* sysdiagnose is telling this which seems to be the error
```
--------------------------------------------------------------------------------
Service:              applinks
App ID:               A876NJFJCE.com.etermax.turnbased
App Version:          0
Domain:               turnbased.page.link
User Approval:        unspecified
Site/Fmwk Approval:   unspecified
Flags:                updating
Next Check:           0001-01-01 03:27:36 +0000
--------------------------------------------------------------------------------
```
* When installign the app this warning is throw
```
Error getting enterprise-managed associated domains data. If this device is not enterprise-managed, this is normal: Error Domain=SWCErrorDomain Code=1701 "Failed to get associated domain data from ManagedConfiguration framework." UserInfo={NSDebugDescription=Failed to get associated domain data from ManagedConfiguration framework., Line=250, Function=<private>}
```

Any thoughts?

**Comment by MartinGonzalez** [comment]
Is it possible that Firebase need to update AASA (apple-app-site-association) format to the new one?

**Comment by chkuang-g** [comment]
@MartinGonzalez 

Did you follow the instruction [here](https://firebase.google.com/docs/dynamic-links/ios/receive#open-dynamic-links-in-your-app) to configure your Xcode project properly?  Ex. if your `mydomain.bla.bla` is a custom domain, you will need to create additional keys in your `Info.plist`.

Otherwise, could you provide a bit more information? Ex. your Firebase SDK version.  Also, are you able to reproduce the same issue with the [quickstart project](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp)?

**Comment by MartinGonzalez** [comment]
@chkuang-g Thanks for reply.
I'm using Firebase domain that is page.link. I was able to reproduce it in an empty project. Also because I'm a bit mad with issue I test branch.io solution, in the same empty project, following the same steps and it worked (I don't know if they have another strategy) but in terms of configuration was the same.

Something that a firebase support told me, that is not in any documentation was that DynamicLinks does not support multiple applications in the same project but it cannot guarantee the order. I've deleted the extra application, updated to AASA and still is not working. I'm truly lost with this issue, I've tested everything and seems to be out of my knowledge

**Comment by chkuang-g** [comment]
I see.  Sorry for the inconvenience. 

I have filed an internal ticket b/162111628 and have Dynamic Link team to take a look of this issue.

**Comment by MartinGonzalez** [comment]
Something that I'm trying to validate is in this page.
https://search.developer.apple.com/appsearch-validation-tool

I have to sites with the apple-app-site-association json file one from firebase and one from branch.io

Firebase: http://turnbased.page.link/apple-app-site-association. None item passes
Branch.io: http://turnbased.app.link/apple-app-site-association. 2 item passes

Both look  similar but in path array there are some different things.

**Comment by MartinGonzalez** [comment]
I've a question about the Dynamic link setup in the firebase console 
![image](https://user-images.githubusercontent.com/4130008/88559887-c82b9480-d003-11ea-9126-c9648e2bf138.png)

If we are 100% mobile app, what should be the value of the dynamic link?

**Comment by patm1987** [comment]
HI @MartinGonzalez ,

For the validation, it looks like there's an issue Apple side [via this forum post](https://developer.apple.com/forums/thread/123554). It looks like it may be similar to [this iOS bug](https://github.com/firebase/firebase-ios-sdk/issues/4914).

For the second question - the Deep Link URL should be something that would be meaningful to desktop users. If someone opens your dynamic link on a platform like Windows or MacOS, you should probably display some sort of info about your game, a description of what happened (ex: your friend invited you to play, open the link on your phone!), and perhaps link to your app store pages for each supported platform.

This is also where you can pass custom data to your application. For example, you can put query parameters into the deep link URL and retrieve them when you receive the dynamic link in your app. This would let you, say, attribute a deep link to its sender (whomever is sending the invite).

Let me know if that helps!
