### ISSUE TITLE
Export HD maps issues?

### ISSUE THREAD

**Issue by Addi2020** [firebase/quickstart-unity#737]
1. ArgumentNullException: Value cannot be null.
Parameter name: key

System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <437ba245d8404784b9fbab9b439ac908>:0)
Simulator.Map.Helper.CreateOrAdd[TKey,TValue] (System.Collections.Generic.IDictionary`2[TKey,TValue] dict, TKey key, TValue val) (at Assets/Scripts/Map/MapLaneSection.cs:216)
Simulator.Map.MapLaneSection.setLaneRelations (System.Collections.Generic.List`1[T] lanes) (at Assets/Scripts/Map/MapLaneSection.cs:162)
Simulator.Map.MapLaneSection.SetLaneData () (at Assets/Scripts/Map/MapLaneSection.cs:83)
Simulator.Map.MapManagerData.ProcessLaneSections (System.Collections.Generic.List`1[T] laneSections) (at Assets/Scripts/Map/MapManagerData.cs:235)
Simulator.Map.MapManagerData.GetTrafficLanes () (at Assets/Scripts/Map/MapManagerData.cs:41)
MapManager.SetMapData () (at Assets/Scripts/Managers/MapManager.cs:41)
MapManager.Awake () (at Assets/Scripts/Managers/MapManager.cs:27)
UnityEngine.Object:Instantiate(MapManager, Transform)
SimulatorManager:Init(Nullable`1) (at Assets/Scripts/Managers/SimulatorManager.cs:178)
Simulator.Loader:EditorInit() (at Assets/Scripts/Web/Loader.cs:246)
Simulator.Loader:Start() (at Assets/Scripts/Web/Loader.cs:115)

2.0720map is missing Pedestrian NavMesh
UnityEngine.Debug:LogError(Object)
PedestrianManager:Start() (at Assets/Scripts/Managers/PedestrianManager.cs:102)

**Comment by chkuang-g** [comment]
Hi @Addi2020 

Are you sure this issue is related to Firebase SDK?
