### ISSUE TITLE
AdvertisingIdentifierString reason for apple rejection

### ISSUE THREAD

**Issue by MohHeader** [firebase/quickstart-unity#738]
### Please fill in the following fields:
Unity editor version: 2018.4.19
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage 
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP):

### Please describe the issue here:
Please check this issue: https://github.com/firebase/firebase-ios-sdk/issues/5153
it was fixed in Firebase iOS 6.27.1, but the pod file for Firebase Unity is pointing to: 6.24.0

is it safe to change the version in pod file to match 6.27.1?

Thanks

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by chkuang-g** [comment]
@MohHeader 

We currently only tested Unity SDK 6.15.2 with iOS SDK 6.24.0.  Theoretically it could work with iOS SDK 6.27.1 as long as there is no breaking changes from iOS side but we cannot guarantee that.

If you like to do that, I would recommend you to test your iOS build thoroughly especially features that touches Firebase SDK.

I think it make sense to bump up iOS SDK version in the next release.  However, the team currently is going through a major change in build process so the release will slow down in the future.

Sorry for the inconvenience. 

Shawn

**Comment by MohHeader** [comment]
Sorry, what info is needed? I feel I missed something
our use for Firebase is minimal, only Analytics + Crashlatyics, so far app is working normal
will keep an eye and if anything raised will keep you updated

Thanks for the clarification.

**Comment by chkuang-g** [comment]
Thanks.  I'll leave this issue as it is.

**Comment by KShoukry** [comment]
@MohHeader Did that fix get you past the apple rejection?

**Comment by MohHeader** [comment]
@KShoukry, Yes indeed 👍

**Comment by chkuang-g** [comment]
Good news. [6.16.0](https://firebase.google.com/download/unity) is release and it should include those changes in iOS SDK.

I'll close this issue for now.  If the issue remains, please report a new bug using [bug template](https://github.com/firebase/quickstart-unity/issues/new?labels=new&template=issue.md)
