### ISSUE TITLE
Never get a 'TokenReceived' message

### ISSUE THREAD

**Issue by ESG-Steven** [firebase/quickstart-unity#74]
I receive logs for 'Firebase App Initializing' and 'Firebase Cloud Messaging API Initialized.' I do not ever receive a callback for TokenReceived. I need the Token to register to a server that will be sending push notifications. Event when I send a push notification message to all users (which would only be my device seeing as I have not pushed FCM live), I receive a notification while the app is not running but still don't get my Token... I don't even get a MessageReceived if the app was opened through a notification...

How can I get the Token (what I assume is AKA a registration token) on startup? It's clear you can do this with a manual call in the native android library `FirebaseInstanceId.getInstance().getToken()`, so why not in the Unity library?

**Comment by alexames** [comment]
What version of Unity and Firebase are you using? Have you correctly imported your google-services.json into your Unity project? And just to be clear, you are getting a token that appears valid when you call `FirebaseInstanceId.getInstance().getToken()` directly?

**Comment by ESG-Steven** [comment]
`RirebaseInstanceId.getInstance().getToken()` is a native only call, I just saw it in their Android Native documentation and noticed it wasn't even available in Unity.
I did have the google-services.json and just redownloaded it and made a build to be sure.
I am using Unity 5.3.0f3 & have tried both Firebase 3.0.0 & 3.0.1.
I have also made sure to run "Play Services Resolver->Version Handler->Update" 
I am using version 0.9.36 of the Google Play Services plugin (https://github.com/playgameservices/play-games-plugin-for-unity) that seemed to resolve nicely with firebase.

**Comment by alexames** [comment]
It looks like there's been an update to the play games services plugin that might solve your problem. Can you try updating to 0.9.37 and seeing if that resolves the issue?

If you still see the error after updating, the next step is to send us some logs of your app during start up so we can see if anything seems off.

**Comment by ESG-Steven** [comment]
Hey Alex,
That update Google Play Services put out yesterday totally fixed my problem!
Thanks a lot. I do have another request but I will close this one and open a different topic.
