### ISSUE TITLE
Duplicate class com.google.firebase.MessagingUnityPlayerActivity

### ISSUE THREAD

**Issue by mechaniqe** [firebase/quickstart-unity#742]
### Please fill in the following fields:
Unity editor version: **2020.1.0f1**
Firebase Unity SDK version: **6.15.2**
Source you installed the SDK (.unitypackage or Unity Package Manager): **Unity Package Manager**
Firebase plugins in use (Auth, Database, etc.): **Cloud Messaging**
Additional SDKs you are using (Facebook, AdMob, etc.): **Facebook, Amplitude, Branch**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Windows**
Platform you are targeting (iOS, Android, and/or desktop): **Android**
Scripting Runtime (Mono, and/or IL2CPP): **Mono and IL2CPP**

### Please describe the issue here:
I updated Firebase Unity plugin and resolved Android dependencies via External Dependency Manager. Building fails with "duplicate class" error:
> java.lang.RuntimeException: Duplicate class com.google.firebase.MessagingUnityPlayerActivity found in modules com.google.firebase.firebase-messaging-unity-6.15.2-runtime.jar (:com.google.firebase.firebase-messaging-unity-6.15.2:) and custom-activity-runtime.jar (:custom-activity:)

A similar issue was raised back in May (#693), but the solution proposed in it isn't applicable to our application, as our application relies on the **custom activity** we've generated, so we can't delete it from Assets folder.

The recommendation of the [documentation](https://firebase.google.com/docs/cloud-messaging/unity/client) can't be used too, as deleting/clearing-contents-of supplied AndroidManifest simply recreates it (as it is inside the Packages and not Assets anymore).
> If your app does not use the default UnityPlayerActivity you will need to remove the supplied AndroidManifest.xml ...

### Please answer the following, if applicable:
_Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?_
Not really applicable to this specific issue, as it relates to using custom activity (instead of MessagingUnityPlayerActivity).

_What's the issue repro rate? (eg 100%, 1/5 etc)_
100%

**Comment by DellaBitta** [comment]
Hi @mechaniqe,

The Messaging SDK ships with a MessagingUnityPlayerActivity class. Could it be that the class was copied into the custom-activity-runtime.jar, too, and so it resides in both locations?  If so, then the duplicate implementation should be removed from the custom-activity-runtime.jar file.

Regarding the `AndroidManifest.xml` files inside the `Packages` folder (instead of the `Assets` folder), the Firebase implementation for the Unity Editor will now copy AndroidManifest.xml to `Assets/Plugin/Android` folder if it's not already there.  I don't know if the clears anything up in the regard.

Thanks!

**Comment by mechaniqe** [comment]
Hello @DellaBitta ,

Thanks for your input and sorry for delayed response, I've missed these notifications.

### MessagingUnityPlayerActivity class
In our case (as it can be for many others), our custom activity extends **MessagingUnityPlayerActivity**. AndroidManifest (which is located in Assets/Plugins/Android) sets that custom activity as the main, as it handles a number of other features (e.g. Deep Linking):

`
<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
`

Are you proposing to keep that activity as main, but not to extend it from MessagingUnityPlayerActivity?

### AndroidManifest
At what point does Firebase add AndroidManifest to `Assets/Plugin/Android`? Would it be at time of setup, while resolving dependencies or at time of building? We are custom building AndroidManifest file ourselves at time of building, hopefully that won't cause any conflicts.

### (Temporary) Fix
For the time being we've moved away from importing the package through Package Manager (although that's the preference) and had to implement a minor fix, where our build script opens up `mainTemplate.gradle` file and removes the line `implementation 'com.google.firebase:firebase-messaging-unity` to prevent it being added to the project twice.

**Comment by patm1987** [comment]
There's a set of instructions [here](https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_an_android_entry_point_activity) for how to provide your own custom Activity and use Cloud Messaging.

The TL:DR; is that you're best off just inheriting from `UnityPlayerActivity` and adding these overrides:
```
/**
 * Workaround for when a message is sent containing both a Data and Notification payload.
 *
 * When the app is in the background, if a message with both a data and notification payload is
 * received the data payload is stored on the Intent passed to onNewIntent. By default, that
 * intent does not get set as the Intent that started the app, so when the app comes back online
 * it doesn't see a new FCM message to respond to. As a workaround, we override onNewIntent so
 * that it sends the intent to the MessageForwardingService which forwards the message to the
 * FirebaseMessagingService which in turn sends the message to the application.
 */
@Override
protected void onNewIntent(Intent intent) {
  Intent message = new Intent(this, MessageForwardingService.class);
  message.setAction(MessageForwardingService.ACTION_REMOTE_INTENT);
  message.putExtras(intent);
  message.setData(intent.getData());
  startService(message);
}

/**
 * Dispose of the mUnityPlayer when restarting the app.
 *
 * This ensures that when the app starts up again it does not start with stale data.
 */
@Override
protected void onCreate(Bundle savedInstanceState) {
  if (mUnityPlayer != null) {
    mUnityPlayer.quit();
    mUnityPlayer = null;
  }
  super.onCreate(savedInstanceState);
}
```

I believe that the answer to the manifest question is that it performs that work at dependency resolution time (which may be at build time depending on your settings), and that it just copies over AndroidManifest.xml if none exists. I'm working to confirm this and will update this issue if I find that that's incorrect.

**Comment by patm1987** [comment]
(it does look like my characterization of `AndroidManifest.xml` is correct)
