### ISSUE TITLE
Projects that import FirebaseStorage.unitypackage cannot be built on iOS

### ISSUE THREAD

**Issue by sinano1107** [firebase/quickstart-unity#744]
### Please fill in the following fields:
Unity editor version: 2019.3.15f1
Firebase Unity SDK version: dotnet4
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): storage
Additional SDKs you are using (Facebook, AdMob, etc.): nothing
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
When I create a new unity project and import FirebaseStorage.unitypackage and then try to build&run it, I get an error

```

Showing Recent Issues
Undefined symbol: _OBJC_CLASS_$_FIRGameCenterAuthProvider

Undefined symbol: _OBJC_CLASS_$_GKLocalPlayer

Undefined symbol: _OBJC_CLASS_$_FIRGoogleAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRPhoneAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRPhoneAuthCredential

Undefined symbol: _OBJC_CLASS_$_FIROAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRFacebookAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIREmailAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRGitHubAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRTwitterAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRAuth

Undefined symbol: _FIRAuthErrorUserInfoUpdatedCredentialKey


```

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by sinano1107** [comment]
I was able to solve this problem by removing the `6.24.0` version specification from the podfile and doing a `pod update`.

But it's very annoying to do this every time you build.
Do you have any ideas?

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '6.24.0'
  pod 'Firebase/Auth', '6.24.0'
  pod 'Firebase/Core', '6.24.0'
  pod 'Firebase/Storage', '6.24.0'
end
```
Here
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
end
```
Change this to `pod update`.

**Comment by DellaBitta** [comment]
Hi @sinano1107,

I tried to reproduce this downloading the latest Firebase SDK and building the Storage Quickstart app from this repo and unfortunately I couldn't reproduce the problem there.  Is there any chance that you can try creating a quickstart project from scratch and building it for iOS to see if you have a problem with that flow? 

Chat happens if you copy your currently download Firebase Pods to a different directory (temporarily removing them) and using the 6.24.0 variant of the pod file?

**Comment by sinano1107** [comment]
Thank you @DellaBitta.

I got the same error when I imported the same SDK as the one that gave me the error after I installed [this repository](https://github.com/firebase/quickstart-unity/tree/master/storage/testapp)
```

Showing Recent Issues
Undefined symbol: _OBJC_CLASS_$_FIRGameCenterAuthProvider

Undefined symbol: _OBJC_CLASS_$_GKLocalPlayer

Undefined symbol: _OBJC_CLASS_$_FIRGoogleAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRPhoneAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRPhoneAuthCredential

Undefined symbol: _OBJC_CLASS_$_FIROAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRFacebookAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIREmailAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRGitHubAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRTwitterAuthProvider

Undefined symbol: _OBJC_CLASS_$_FIRAuth

Undefined symbol: _FIRAuthErrorUserInfoUpdatedCredentialKey
```

This probably indicates that my SDK is bad.
The SDK I got is [this](https://firebase.google.com/download/unity?hl=ja).
Isn't this the most recent one?
Also what do I have to do to get the latest SDK?

**Comment by sinano1107** [comment]
The repository also worked by removing `6.24.0` as well.

**Comment by sinano1107** [comment]
Strangely enough, running `sudo gem install cocoapods` solved this problem.

I don't know why this solved the problem, but I hope it helps people who are having the same problem as me.

**Comment by DellaBitta** [comment]
Hi @sinano1107, 

I recall having to do something similar after upgrading to Catalina . I wonder if it's somewhat related.  

Glad you were able to get it sorted out, and thanks for following up with more information!
