### ISSUE TITLE
Android crash report not symbolicated after uploading cSYM file

### ISSUE THREAD

**Issue by daniel3512** [firebase/quickstart-unity#745]
### Please fill in the following fields:
Unity editor version: 2019.4.2f1
Firebase Unity SDK version: 6.13.0
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Crashlytics
Additional SDKs you are using (Facebook, AdMob, etc.): AppsFlyer
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I created a folder for `strippedNativeLibsDir` with `libil2cpp.so` and `libunity.so` from `Temp\gradleOut\launcher\build\intermediates\transforms\mergeJniLibs\release\0\lib`
and another folder for `unstrippedNativeLibsDir` with `libil2cpp.sym.so` and `libunity.sym.so` from build.symbols.zip generated by Unity. 

I renamed `libil2cpp.sym.so` and `libunity.sym.so` to `libil2cpp.so` and `libunity.so` because `strippedNativeLibsDir`  and `unstrippedNativeLibsDir` need to have files with the same name.

When I run uploadCrashlyticsSymbolFileRelease --debug I get:
`Generating symbols for \Temp\gradleOut\launcher\libs\unstripped\arm64-v8a\libunity.so`
`Using ELF data for cSYM generation.`

and 

`Crashlytics symbol file uploaded successfully; deleting local csym: \Temp\gradleOut\launcher\build\crashlytics\Release\nativeSymbols\il2cpp-aarch64-59bca83a9172e58251c70f066785e514ee2968ce.cSYM`

But in Firebase console I still have 

```
libunity.0x2bbe09
libunity.0x7a498f
libunity.0x2eb493
Unknown.0x9a5c4f6

```

**Comment by DellaBitta** [comment]
Hi @daniel3512,

I have sent this as an internal ticket to the Crashlytics team to see if they have any insight as to what's going wrong.

**Comment by UncleJey** [comment]
Hi! @daniel3512 @DellaBitta

Can you please link documentation of this magic manipulations to upload sym-files
Pleeeeease!

**Comment by daniel3512** [comment]
https://firebase.google.com/docs/crashlytics/ndk-reports

**Comment by chkuang-g** [comment]
@UncleJey Does the link from @daniel3512 resolve your issue?

**Comment by UncleJey** [comment]
@chkuang-g official documentations is not usable and too hard for understanding.
You better make guide for unity users. HOWTO from a to z. Step by step.

i still have difficulty understanding what i have to do and how i can do it.
But native reports is to important for us.

**Comment by UncleJey** [comment]
please. i need link to "howto" setup it for unity3d.

**Comment by patm1987** [comment]
@UncleJey I will move this to a feature request, as native crash symbolication in Unity is not officially supported - although you may be able to manually work around it with some modification to Unity's gradle files in newer versions of the editor.

Looking at @DellaBitta 's bug, it has also been moved to a feature request internally.

**Comment by UncleJey** [comment]
> 
> 
> @UncleJey I will move this to a feature request, as native crash symbolication in Unity is not officially supported - although you may be able to manually work around it with some modification to Unity's gradle files in newer versions of the editor.
> 
> Looking at @DellaBitta 's bug, it has also been moved to a feature request internally.

Thank you so much!

**Comment by zhangjianshuai** [comment]
https://support.unity.com/hc/en-us/articles/115000177543-Where-I-can-get-the-symbols-file-for-the-libil2cpp-so-library-in-an-Android-IL2CPP-build-to-symbolicate-call-stacks-from-crashes-on-my-production-builds-

**Comment by sp-duarte-roso** [comment]
Hi @patm1987,
Any updates on this one?

**Comment by paulinon** [comment]
Hi folks,

As of version [8.6.0](https://firebase.google.com/support/release-notes/unity#version_860_-_november_8_2021) of the SDK, you may now upload symbol files for your builds so that the symbolicated IL2CPP stack traces can be displayed in the Crashlytics console.

**Comment by oliverebert** [comment]
@paulinon thanks I have been looking for the solution to this problem for a long time. :)
