### ISSUE TITLE
APP_CRASH###java.lang.Error###

### ISSUE THREAD

**Issue by reysantana** [firebase/quickstart-unity#749]
### Please fill in the following fields:
Unity editor version: 2019.4.7f1 (e992b1a16e65)
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Auth, Firestore, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
detail : APP_CRASH###com.lacey.dabump###java.lang.Error###*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.7f1 (e992b1a16e65)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
Build fingerprint: 'samsung/dream2qltezh/dream2qltechn:7.1/N2G48H/G9550ZHU1AQEE:user/release-keys'
Revision: '12'
ABI: 'arm'
Timestamp: 2020-08-10 19:16:25-0400
pid: 10533, tid: 10629, name: Thread-4  >>> com.lacey.dabump <<<
uid: 10067
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0  00000000  r1  00000001  r2  00000000  r3  00000000
    r4  8092fc50  r5  8092fc78  r6  00000001  r7  8092fed0
    r8  b3f49008  r9  00000002  r10 00000000  r11 7f615378
    ip  04b0c924  sp  7f6152f8  lr  04357dec  pc  04357ee8

backtrace:
      #00 pc 00357ee8  /data/app/com.lacey.dabump-1/lib/arm/libunity.so (BuildId: c3d534a7f46b577de576c48396952460338c2789)

package : com.lacey.dabump
state : APP_CRASH

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
No

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

> I am downloading images from firebase storage using GetFileAsync and after 5 secs(splash screen display time), I login to the app using Firebase Auth.
> If I login with Facebook, there is no error at all, but if I login with Google and if the downloading progress didn't finish, it causes error, if completed, then no error.
> 
Edit:
I first download all images from firebase storage and after that, when i try to login with firebase, it always crash.

**Comment by reysantana** [comment]
Here is code:
private async void Start()
    {
        await FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(async task =>
        {
            dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available)
            {
                await InitializeFirebaseAsync();
            }
            else
            {
                Debug.Log("Could not resolve all Firebase dependencies: " + dependencyStatus);
            }
        });
    }

    private async Task InitializeFirebaseAsync()
    {
        auth = FirebaseAuth.DefaultInstance;
        auth.StateChanged += AuthStateChanged;
        AuthStateChanged(this, null);

        if (!FB.IsInitialized)
        {
            FB.Init(InitCallback, OnHideUnity);
        }
        else
        {
            FB.ActivateApp();
        }

        firestore = FirebaseFirestore.DefaultInstance;
        storage = FirebaseStorage.DefaultInstance;

        await FetchNecessaryFilesAsync();
// after downloading completed, the scene switches to firebase login scene and when I click login button, it initializes but it crashes after I select account. ** This script is set as a DontDestroyOnLoad, so it is not destroying when I switch scene.
    }

**Comment by munaraza** [comment]
@reysantana Do you find any solution ?  I am using Firebase Storage in my case On **samsung J6** ll2CPP build crash but mono build work correct but on Samsung S8 plus ll2CPP and Mono both work correct. I am unable to find the reason can you help me for this ?

**Comment by reysantana** [comment]
Use firebase functions instead

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by munaraza** [comment]
@reysantana  here us function 

    string fireBaseBucket = "gs://color-by-number-project.appspot.com/";
    string refrence = "gs://color-by-number-project.appspot.com/";
    bool isTaskCompleted = false;
    long fileSize;
    string currentCatagorey;
    StorageReference _ref ;
    StorageMetadata _metaFile;
    FirebaseStorage storage;


 public void downloadFile(string catagoreyName)
    {
        
       
        // Create local filesystem URL
         string destination = Path.Combine(Application.persistentDataPath,catagoreyName);
        print(destination);
        _ref = storage.GetReferenceFromUrl(refrence + catagoreyName);

        getFileTotalSize(catagoreyName);


        // Start downloading a file
        Task task = _ref.GetFileAsync(destination,
        new Firebase.Storage.StorageProgress<DownloadState>((DownloadState state) =>
        {

            // called periodically during the download
            if (ReskinManager.instance.loadingBar != null)
            {
                ReskinManager.instance.loadingBar.value = (state.BytesTransferred * 100) / fileSize;
            }

        }), CancellationToken.None);

        task.ContinueWith(resultTask =>
        {
            if (!resultTask.IsFaulted && !resultTask.IsCanceled)
            {
                Debug.Log("Download Finished");
                isTaskCompleted = task.IsCompleted;
                print(isTaskCompleted);
            }
        });

    }


all these thing work fine in unity editor as well as all things work fine on S8 plus with mono and ll2CPP  but on samsung J6 crash at ll2CPP  and work fine at mono. I don't know the reason.

**Comment by munaraza** [comment]
@reysantana  can you help me through skype its about two week in this issue. here is skype id =  razamustafa36. Thank you

**Comment by reysantana** [comment]
Please try to add file://<file:///> ?

“File://” + Application.persistantDataPath

**Comment by munaraza** [comment]
@reysantana  I just check “File://” + Application.persistantDataPath and it isnot working for me.

**Comment by patm1987** [comment]
Hi @reysantana (and @munaraza - I just got to your question as well!),

It's most helpful if you can reproduce your issue on the [Crashlytics quickstart](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp). Because the team knows it so well, it really helps track down the issue and prevent it from regressing once it's fixed.

It would help if you can get more error logging before the stack dump so we can see exactly which exception is being raised and where in code it's happening. It may help to test in debug mode with script debugging:
![Screen Shot 2020-08-13 at 10 27 23 AM](https://user-images.githubusercontent.com/1111611/90164655-e956e980-dd54-11ea-8317-d6a46ea2a5f8.png)

Some notes that _might_ help with the initial code drop. I see you're doing this:
```
await FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(async task =>
```

`await` and `ContinueWith` are redundant (and `ContinueWith` will likely execute in the background). I'd recommend either doing:
```
var dependencyStatus = await FirebaseApp.CheckAndFixDependenciesAsync();
if (dependencyStatus == DependencyStatus.Available) {
    await InitializeFirebaseAsync();
}
```

or:
```
FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
    var dependencyStatus = task.Result;
    if (dependencyStatus == DependencyStatus.Available) {
        InitializeFirebaseAsync(); // .ContinueWithOnMainThread isn't needed here unless you plan on doing something with the result
    }
});
```

You also don't need to explicitly dispose `FirebaseApp`, the SDK does some clever stuff to manage it on its own.

Let me know if any of that helps, if you can repro it in the test app, and/or if you have any additional logs that I can check!

--Patrick
