### ISSUE TITLE
Automatically adding -FIRDebugEnabled to iOS project built through Unity Cloud Build

### ISSUE THREAD

**Issue by jessiagee** [firebase/quickstart-unity#753]
### Please fill in the following fields:
Unity editor version: 2018.4.12f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, Helpshift, AppLovin, bugsnag
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
We use Unity Cloud Build to distribute our Unity game to our players. I would like to automate the ability to add -FIRDebugEnabled to Xcode with a post process build script so that our testers are able to look at the DebugStreamView with the .ipa created from UCB. 

Is this something that is provided with Firebase SDK? I couldn't find any documentation for Unity code that would either toggle the logging automatically and/or add the option to set this value in the scheme. Is this something I need to speak with Unity about?

**Comment by cynthiajoan** [comment]
Hi @jessiagee,

How to get Unity Cloud Build to able to pass in argument to xcode build is a question for Unity, I find [reference](https://docs.unity3d.com/Manual/UnityCloudBuildiOS.html) in last section here might be able to help.

You can also change the log level in the code using [this](https://firebase.google.com/docs/reference/unity/class/firebase/firebase-app#loglevel), which should be able to print firebase log informations in DebugStreamView.

Hope these answer your question.
