### ISSUE TITLE
Realtime database - Adding retrieved snaphosts.Children to list/array silently fails

### ISSUE THREAD

**Issue by michelepanegrossi** [firebase/quickstart-unity#759]
### Please fill in the following fields:
Unity editor version: 2019.4.1f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): .unitypackage dotnet4
Firebase plugins in use (Auth, Database, etc.): Database
Additional SDKs you are using (Facebook, AdMob, etc.): Google Arcore, Photon
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android, iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I am **successfully** saving instances of this class on the realtime database

```
public class FPTLineToRetrieve
{
    public string _name;
    public List<Vector3> _allThePoints;
    public Vector4 _lineColor;
    public float _thickness;
    public int _sortingOrder;

    public FPTLineToRetrieve()
    {
    }

    public FPTLineToRetrieve(string _name, List<Vector3> _allThePoints, Color _lineColor, float _thickness, int _sortingOrder)
    {
        this._name = _name;
        this._allThePoints = _allThePoints;
        this._lineColor.x = _lineColor.r;
        this._lineColor.y = _lineColor.g;
        this._lineColor.z = _lineColor.b;
        this._lineColor.w = _lineColor.a;
        this._thickness = _thickness;
        this._sortingOrder = _sortingOrder;
    }
}  
```

Using this code

```
public void LogLine(FPTLineToRetrieve _currentLineToSave)
{
        string tempJsonList = JsonConvert.SerializeObject(_currentLineToSave);
        reference.Child("AllLines").Child(_currentLineToSave._name).SetRawJsonValueAsync(tempJsonList);
 }
```

Then I retrieve the instances using this code
```
private FPTLineToRetrieve _currentLineToRetrieve;
private List<FPTLineToRetrieve> _AllLinesToRetrieve;

public void RetrieveAllLines()
    {
        FirebaseDatabase.DefaultInstance.GetReference("AllLines").GetValueAsync().ContinueWith(lineTask => {
            if (lineTask.IsFaulted)
            {
                Debug.Log("No snapshot");
            }
            else if (lineTask.IsCompleted)
            {
                DataSnapshot snapshot = lineTask.Result;
                Debug.Log("Children Count:= " + snapshot.ChildrenCount);

                foreach (DataSnapshot ds in snapshot.Children)
                {

                    _currentLineToRetrieve = JsonConvert.DeserializeObject<FPTLineToRetrieve>(ds.GetRawJsonValue());
                    _AllLinesToRetrieve.Add(_currentLineToRetrieve);

                    Debug.Log("_currentLineToRetrieve:= " + _currentLineToRetrieve._name);
                    Debug.Log("_currentLineToRetrieve:= " + _currentLineToRetrieve._sortingOrder);
                    Debug.Log("_currentLineToRetrieve:= " + _currentLineToRetrieve._thickness);
                    Debug.Log("_currentLineToRetrieve:= " + _currentLineToRetrieve._allThePoints.Count);
                }

            }
        });
    }
```

Here is where the problem starts. `Debug.Log("Children Count:= " + snapshot.ChildrenCount);` is printed in the Unity Console but **then nothing else is printed in the Console**. All the other `Debug.Log` lines are not executed and the `foreach` loop is not executed. It just seems to silently stop.

**However** if I comment the line `_AllLinesToRetrieve.Add(_currentLineToRetrieve);` the `foreach` loop executes correclty and I see all the `Debug.Log` entries printing correctly in the Console for each snaphot child in the database. It seems that saving the instances to a List/array is breaking the `foreach` loop?

I am using .NET 4.x API Compatibility Level and the dotnet4 Firebase SDK version (6.15.2). I wanted to see whether using `GetValueAsync().ContinueWithOnMainThread()` would solve the issue but I cannot find the Firebase Extensions unitypackage anywhere.

Any help would be greatly appreciated!!!

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

I don't think it is possible?

What's the issue repro rate? (eg 100%, 1/5 etc) **100%**

**Comment by michelepanegrossi** [comment]
I think I found what the problem was. After initialising the List with `_AllLinesToRetrieve = new List<FPTLineToRetrieve>();` the problem disappeared..

I have a nother question though. Is there an event which will tell me when all the entries have been retrieved from the databse so that I can act upon the _AllLinesToRetrieve List being sure that it has been filled properly?

**Comment by cynthiajoan** [comment]
Hi @michelepanegrossi, glad you've figured out what the issue is.

For your following question, in the ContinueWith of the async call, you are grabbing a DataSnapshot which should already contains all entries and the _AllLinesToRetrieve should be ready after your for loop.

**Comment by michelepanegrossi** [comment]
Thank you @cynthiajoan that makes sense and it works 👍
