### ISSUE TITLE
Problem iOS Notification Send Message to Topic

### ISSUE THREAD

**Issue by JangT** [firebase/quickstart-unity#76]
I am using the Firebase Unity SDK.
Topic works well for AOS but not for iOS Topic.
In iOS, if i send to user segment, I received a notification. If i send it to Topic, i did not be received.

and than I received a warning message as below.
"Can not subscribe to topic: / topics / *** with token: (null)"  like this

I did a check provisioning profile and re-Install but failed.

Firebase-unity version : 3.0.1
Unity version : 5.5.1f

**Comment by alexames** [comment]
Is this with a pristine download of the quickstart app, or did you make any changes to it? I can't reproduce the issue with a clean download of the quickstart messaging app. Are you able to send notifications to specific users using their registration token?

**Comment by stewartmiles** [comment]
@JangT any updates on this?  Did you try following the setup instructions?

**Comment by stewartmiles** [comment]
I'm assuming this is resolved.  We've been testing with topics with no issues.  If this is still a problem please reopen.

Cheers,
Stewart
