### ISSUE TITLE
More than one file was found with OS independent path 'lib/x86/libFirebaseCppAnalytics.so

### ISSUE THREAD

**Issue by SebastienDevQuebec** [firebase/quickstart-unity#760]
### Please fill in the following fields:
**Unity editor version:** 2019.4.8f1
**Firebase Unity SDK version:** 6.15.2
**Source you installed the SDK:** Unity Package Manager
**Firebase plugins in use (Auth, Database, etc.):** Firebase App, Auth, Firestore, Function & Analytics
**Additional SDKs you are using (Facebook, AdMob, etc.):** None
**Platform you are using the Unity editor on (Mac, Windows, or Linux):** Windows
**Platform you are targeting (iOS, Android, and/or desktop):** Android
**Scripting Runtime (Mono, and/or IL2CPP):** Mono

### Please describe the issue here:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:transformNativeLibsWithMergeJniLibsForRelease'.
> More than one file was found with OS independent path 'lib/arm64-v8a/libFirebaseCppFirestore.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[

> Configure project :launcher
Exception while marshalling C:\Program Files\2019.4.8f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\2019.4.8f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\2019.4.8f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-28\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\2019.4.8f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :unityLibrary:Firebase:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:Firebase:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:checkReleaseManifest UP-TO-DATE
> Task :launcher:extractProguardFiles UP-TO-DATE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:Firebase:checkReleaseManifest
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:prepareLintJar UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:Firebase:processReleaseManifest
> Task :unityLibrary:Firebase:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:Firebase:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:Firebase:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:Firebase:generateReleaseResValues
> Task :unityLibrary:Firebase:generateReleaseResources
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:Firebase:packageReleaseResources
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:generateReleaseSources UP-TO-DATE
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> Task :unityLibrary:transformNativeLibsWithIntermediateJniLibsForRelease UP-TO-DATE
> Task :unityLibrary:Firebase:generateReleaseRFile
> Task :unityLibrary:Firebase:generateReleaseBuildConfig
> Task :unityLibrary:Firebase:prepareLintJar UP-TO-DATE
> Task :unityLibrary:Firebase:generateReleaseSources
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :launcher:preReleaseBuild
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:Firebase:javaPreCompileRelease
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:checkReleaseManifest UP-TO-DATE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:generateReleaseSources UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:Firebase:compileReleaseJavaWithJavac
> Task :unityLibrary:Firebase:bundleLibCompileRelease
> Task :unityLibrary:Firebase:prepareLintJarForPublish UP-TO-DATE
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:Firebase:mergeReleaseShaders
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:Firebase:compileReleaseShaders
> Task :unityLibrary:Firebase:generateReleaseAssets
> Task :unityLibrary:Firebase:packageReleaseAssets
> Task :unityLibrary:Firebase:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeRelease UP-TO-DATE
> Task :unityLibrary:Firebase:bundleLibResRelease
> Task :unityLibrary:Firebase:bundleLibRuntimeRelease
> Task :unityLibrary:Firebase:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :unityLibrary:Firebase:mergeReleaseJniLibFolders

> Task :launcher:processReleaseManifest
G:\My Games\Project_01\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:Firebase:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:Firebase:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :launcher:processReleaseResources
> Task :launcher:compileReleaseJavaWithJavac UP-TO-DATE
> Task :launcher:compileReleaseSources UP-TO-DATE
> Task :launcher:lintVitalRelease
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseShaders UP-TO-DATE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:validateSigningRelease UP-TO-DATE
> Task :launcher:signingConfigWriterRelease UP-TO-DATE
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
> Task :launcher:transformClassesAndResourcesWithR8ForRelease UP-TO-DATE
> Task :launcher:mergeReleaseJniLibFolders UP-TO-DATE
> Task :launcher:transformNativeLibsWithMergeJniLibsForRelease FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
63 actionable tasks: 25 executed, 38 up-to-date
]
exit code: 1 

**What's the issue repro rate?** 100%

**Comment by chkuang-g** [comment]
Hi @SebastienDevQuebec 

I think Unity 2019.4.6f1 is using Gradle 5.1.1.  Even Unity 2020.1.2f1 is using Gradle 5.6.  Are you using Gradle 6+?
Gradle 6 introduced many breaking changes so I do not think it will work with the gradle project generated by Unity.

I actually just built [MechaHamster](https://github.com/google/mechahamster) using Firebase from UPM this week and did not have any issue.  Could you make sure your Android SDK, NDK and Gradle Settings in `Preferences > External Tools` is correct and try again?

Thank you,
Shawn
