### ISSUE TITLE
iOS 14/IDFA support, any changes needed? Should we expect a new SDK version soon?

### ISSUE THREAD

**Issue by fliperamma** [firebase/quickstart-unity#763]
It has been increasingly hard to keep track of all changes needed in order to prepare for the iOS 14/IDFA release (from all third-party software we usually use in our projects).

I'd like to ask the team if an iOS 14/IDFA-specific update is planned for the **Firebase Unity SDK** and its components and, if yes, when should we expect it. It would be great if you could point us towards a roadmap with more details, if possible.

> If this is not the ideal place to ask, please, point me towards the correct one (that is Unity-specific).

Best,

Fabio

**Comment by chkuang-g** [comment]
There are some discussion in this thread https://github.com/firebase/firebase-ios-sdk/issues/5928

It does seem that Analytics added some support to iOS 14 app tracking prompt.
https://firebase.google.com/support/release-notes/ios#version_6310_-_august_25_2020

We are rolling up iOS SDK version in the next release so this should be included.

**Comment by fliperamma** [comment]
Thanks @chkuang-g 
Lots of good information on the referred thread.

If I understood it well, a Firebase update is only be required _if using Google Analytics for Firebase_, meaning the iOS 14/IDFA _will not affect_ Crashlytics, FCM or Dynamic Links, for example, and it is safe to keep using the current version. Would this be correct @chkuang-g ?

**Comment by samedson** [comment]
Hey folks,

In terms of Crashlytics specifically, the SDK does read from the IDFA since we launched to GA for iOS (4.0.0 and above). 

Please use Firebase Unity version `6.15.0` and above, which uses the newer versions of the underlying iOS SDK.

**Comment by chkuang-g** [comment]
I would expect all the other Firebase component behave similarly to Crashlytics.

But I'll keep up updated if I hear anything from iOS team.

**Comment by chkuang-g** [comment]
A couple updates:

Seems like Apple is pushing back IDFA to next year.
https://twitter.com/alexeheath/status/1301565700394250241

For use of Firebase, as long as you are using the latest version Analytics, you should be good.
https://firebase.google.com/support/release-notes/ios#analytics

We will include this change in the next Firebase release.

**Comment by fliperamma** [comment]
Thanks for the update @chkuang-g 
Not to put pressure on you/the team, but do you have an ETA on the new Unity SDK that contains the latest iOS SDK?

**Comment by chkuang-g** [comment]
We are actively making the release. Unfortunately we cannot give you an accurate ETA at this point.
There are quite a number of iOS/Android deps we need to sort out since last release.
Will keep you updated

**Comment by chkuang-g** [comment]
Good news. [6.16.0](https://firebase.google.com/download/unity) is release and it should include those changes in Analytics.

I'll close this issue for now.  If the issue remains, please report a new bug using [bug template](https://github.com/firebase/quickstart-unity/issues/new?labels=new&template=issue.md)
