### ISSUE TITLE
Failed to initialize the Crashlytics SDK

### ISSUE THREAD

**Issue by midopooler** [firebase/quickstart-unity#767]
## Please fill in the following fields:

Unity editor version: 2020.1.1f1
Firebase Unity SDK version: 6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager): from firebase website
Firebase plugins in use (Auth, Database, etc.): crashlytics only
Additional SDKs you are using (Facebook, AdMob, etc.): nothing
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android (UCB)
Scripting Runtime (Mono, and/or IL2CPP): Mono 

### Please describe the issue here:
Compact Logs:- https://docs.google.com/document/d/1L1o0DMJquwM856T_rhfaAg2eIfIz64X08mmJ1ZZId54/edit?usp=sharing
Full logs:- https://docs.google.com/document/d/1Hi1jECTAvRuBmI0ZGhsw6mSyJnjEST250qNEUITpLtY/edit?usp=sharing

Hi, I built Crashlytics mainscene over Unity Cloud Builds. (Android)
I manually imported the crashlytics unitypackage downloaded from firebase website and had done all the basic configurations done. After installing it into my Android phone I was able to view my user count go 0 to 1 in the firebase console but the crashlytics console wasn't being initialised. I tried crashing the app manually first, didn't saw any changes in the console. And then I tried customised non-fatal crashes by using scripts on firebase docs. Even then, the console didn't initialise.
 Below are the photos I saw on the console.
![Screenshot_1](https://user-images.githubusercontent.com/43686606/91977206-e9d51580-ed3f-11ea-9d64-484510f5a6b9.png)
![image](https://user-images.githubusercontent.com/43686606/91977266-04a78a00-ed40-11ea-9e0d-ef81b942334a.png)

Please help me out as this issue had cracked me up for almost a month. :/

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I tried building the scene giving in this GitHub repository, even that didn't help.

What's the issue repro rate? (eg 100%, 1/5 etc)
What is repro rate? I'll fill this later when I get to know its meaning.

**Comment by midopooler** [comment]
> This issue does not seem to follow the issue template. Make sure you provide all the required information.

Where did I missed? :(

**Comment by midopooler** [comment]
@patm1987 help needed. 🙏

**Comment by kevinkokomani** [comment]
Thanks - could you try replacing the code you're using to test crash the app with the following:

`Utils.ForceCrash(ForcedCrashCategory.Abort);`

And see if you're able to get past the onboarding screen with that?

**Comment by midopooler** [comment]
@kevinkokomani Correct me if I'm wrong, I've to replace this with line number 38. Right?
Also CrashlyticsTester.cs is not my code, that's taken from Firebase docs https://firebase.google.com/docs/crashlytics/test-implementation?authuser=0&platform=unity

**Comment by kevinkokomani** [comment]
I believe line 38 is correct. You followed the instructions correctly, I just wanted to check if that would help you get past the onboarding screen - I've seen this help one other developer in the past.

**Comment by midopooler** [comment]
I did a cloud build and got these following logs.
ERRORS:
[Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
Failed to start server: Error: listen EADDRINUSE: address already in use 127.0.0.1:10010
[Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
Truncated to 10 lines.
[Unity] Initialize engine version: 2020.1.4f1 (fa717bb873ec)
[Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
UPM Server already running, skipping...
[Unity] Initialize engine version: 2020.1.4f1 (fa717bb873ec)
[Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,12): error CS0103: The name 'Utils' does not exist in the current context
[Unity] Assets/CrashlyticsTester.cs(39,29): error CS0103: The name 'ForcedCrashCategory' does not exist in the current context
publishing finished successfully.

Do you think this is because of something like missing namespace?

**Comment by chkuang-g** [comment]
@midopooler 

First of all, if you are building Android App using Unity 2020, take a look of this blog post.
https://firebase.googleblog.com/2020/08/firebase-compatibility-with-unity-20201.html
It is unfortunately painful but all the fixes should be coming in the next release.
One note is that in `Crashlytics Support` section, instead of modifying `launchTemplate.gradle`, you can just rename `Assets/Plugins/Android/Firebase` to `Assets/Plugins/Android/Firebase.androidlib`. Make sure you see `crashlytics_bundle_id` and `google-services.xml` under `Assets/Plugins/Android/Firebase.androidlib/res/values/`

Second, AFAIK, you cannot hard-crash Unity Android app because Unity will handle all the exceptions.  If you **really** want to hard-crash Android App, like for testing, throw a Java exception from a non-main-thread.
