### ISSUE TITLE
My ios app does not appear in notification section in settings

### ISSUE THREAD

**Issue by SallmanRafi** [firebase/quickstart-unity#769]
### Please fill in the following fields:
Unity editor version: 2019.2.20
Firebase Unity SDK version:  6.15.2
Source you installed the SDK (.unitypackage or Unity Package Manager):Imported from Unity Package Manager
Firebase plugins in use (Auth, Database, etc.):Firebase cloud messaging
Additional SDKs you are using (Facebook, AdMob, etc.): admob
Platform you are using the Unity editor on (Mac, Windows, or Linux): mac
Platform you are targeting (iOS, Android, and/or desktop): ios
Scripting Runtime (Mono, and/or IL2CPP):IL2CPP

### Please describe the issue here:
I have imported firebase cloud messaging from package manager, Enabled custom background in build settings, both "Background Fetch" and "Remote Fetch". Opened In Xcode, added "Push notification" from capabilities.
My pods are :
  pod 'Firebase/Core', '6.24.0'
  pod 'Firebase/Messaging', '6.24.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.63'

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by vimanyu** [comment]
Hi @SallmanRafi,
Could you please verify if you have followed the steps detailed in this guide ?
https://firebase.google.com/docs/cloud-messaging/unity/client#add_user_notifications

I am also curious if the Unity quickstart messaging example is working for you. It will be easier to reproduce this issue on our end if you confirm this.

**Comment by SallmanRafi** [comment]
Thank Your for reply @vimanyu 
Yup I have done everything mentioned in guide
but still no notification appear in my ios app notification section

**Comment by vimanyu** [comment]
Thanks for confirming. Were you able to test if its happening with Unity quickstart messaging example too?

**Comment by SallmanRafi** [comment]
same issue when building with unity quickstart messaging example
Can you please tell the steps when building in xcode
Thank You

**Comment by patm1987** [comment]
Using the [quickstart project](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp), I was able to get the test app to show up with a bundle id/provisioning profile setup to send push notifications.

![image](https://user-images.githubusercontent.com/1111611/93935195-7ccef300-fce1-11ea-9d40-6914feaff8a7.png)

This would be with the 6.15.2 Firebase SDK installed via the Unity Package Manager (to match your configuration). I am using Unity 2020.1.6f1.

My pods do match yours:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Firebase/Core', '6.24.0'
  pod 'Firebase/Messaging', '6.24.0'
end
```

To ask a few more simple questions: have you [configured APNs](https://firebase.google.com/docs/cloud-messaging/ios/certs)?
Is [swizzling enabled](https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in)? It should be enabled for Firebase to function, and is relatively difficult to turn off in Unity - but just verify that you don't have `FirebaseAppDelegateProxyEnabled` set to `NO`.
