### ISSUE TITLE
Question | Email link auth

### ISSUE THREAD

**Issue by MiroslavShard** [firebase/quickstart-unity#772]
Hi guys, 

I have a question about Firebase Email Link Authentication. Is it possible to integrate this function into Unity app?

If yes, how can I do it? I haven't found any information in the docs.

If no, can you add this feature into future updates of Firebase SDK?

Thank you for your hard work.

**Comment by vimanyu** [comment]
Hi @MiroslavShard,
Unfortunately, this is not currently supported in Unity. We have this on our roadmap and will update when its implemented.
I am going to close this ticket as we have another ticket for this issue flagged as a feature request. 
https://github.com/firebase/quickstart-unity/issues/197
