### ISSUE TITLE
Reauthenticate non-existing user

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#776]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.7f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: Crashlytics, Firestore, Messaging (Auth, Database, etc.)
  * Additional SDKs you are using: AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

- Link **new** email/password provider with anonymous account
- Wait "a long time"
- Log out of above provider
- Link **old** email/password provider to account

The last step throws a "RequiresRecentLogin" AuthError.
When then trying to reauthenticate the user with the above email/password provider (FirebaseUser.ReauthenticateAsync), the following error occurs:
`FirebaseException: There is no user record corresponding to this identifier. The user may have been deleted.`
AuthError: UserNotFound

This seems to make sense, as the email/password combination doesn't exist anymore, as it was removed when logging out of the account.
The question now is how to link the provider again?

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
Credential credential = EmailAuthProvider.GetCredential(email, password);  //Create credentials
FirebaseUser = await FirebaseUser.LinkWithCredentialAsync(credential); //Try to link account 

[Try/catch] will catch "RequiresRecentLogin" exception from link method]

credential = EmailAuthProvider.GetCredential(email, password);  //Create new credentials with same email/password values
await FirebaseUser.ReauthenticateAsync(credential);  //Try to reauthenticate

[Try/catch] will catch "UserNotFound" exception from reauthenticate method]
```

**Comment by DellaBitta** [comment]
Hi @Nyankoo,

In the code sample above the variable names share are the same as the class names, and so I have some followup questions if you don't mind.  

The code invokes Reauthenticate on a Firebase User that was assigned by the original attempt to invoke LinkWithCredential, but as you say that was an exception.  Could it be that the FirebaseUser variable that you're attempting to Reauthenticate isn't the user object that you expect? Could you add some output about the user_id, etc, to ensure that it's the correct user?

Thanks!

**Comment by Nyankoo** [comment]
Hi @DellaBitta, thank you for getting back about this!

I was testing the above issue some more, and now Firebase lost the connection between my app install and the UID, as a new UID was linked to the app install.
Is there a way to access a specific UID of an anonymous account, so I can get the connection back? Or is my previous account now lost in Firebase limbo?

**Comment by DellaBitta** [comment]
Hi @Nyankoo, 

I'm sorry to say that I believe that the account is now in limbo since there's no way to sign-in again with just the UID.

**Comment by Nyankoo** [comment]
Hi @DellaBitta,
nothing we can do about that. I will try to continue reproducing this error again, but it may take some time due to the "RequiresRecentLogin" login preoid.

On another note, is there a (easy) way to transfer all documents and collections from one UID to another? This would be helpful in cases were an account ends up in limbo, and you want to continue on another account.

**Comment by DellaBitta** [comment]
Hi @Nyankoo,

The merging of user data has to be done programmatically by querying the data from one user and setting it in the other.  Instead maybe it would be good to associate the user with another login provider (google for instance) so that you have another way to login that particular user after unlinking email auth.

**Comment by Nyankoo** [comment]
Hi @DellaBitta,

while it's an option to have multiple login providers liked to an account, you can't really force your users to log in with multiple accounts.

For merging user data on the backend, would Cloud Functions be the way to go?

**Comment by DellaBitta** [comment]
Hi @Nyankoo,

I was suggested linking the testing account to another provider as I thought you were running into uses disassociating that particular account.  Sorry if I misunderstood.

You can merge data either with the client or on the backend.  I recommend reaching out to the [Firebase Talk Google Group](https://groups.google.com/g/firebase-talk) to ask & discuss best practices and options.
