### ISSUE TITLE
Autologin/Silent Login with Facebook and Firebase Authentication

### ISSUE THREAD

**Issue by fer-gamboa** [firebase/quickstart-unity#778]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.10F1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: none for now
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime:  IL2CPP)

### [REQUIRED] Please describe the issue here:

I want to complete an express login with Facebook provider.

 properly initialise Facebook doing `FB.Init( () => { FB.ActivateApp();} );`, and make sure `FB.IsInitialized`. 

Firebase side: `auth.SignInWithCredentialAsync(credential)`

Facebook side: 

```
 var perms = new List<string>() { "public_profile", "email" };
FB.LogInWithReadPermissions(perms, myCallback);
``` 

The first time I log in in Facebook, it works like a charm. When I try to open the app again, I want to do a "silent login" like with Google login. So I do:

```
        FB.Android.RetrieveLoginStatus((ILoginStatusResult result) => {
            if (string.IsNullOrEmpty(result.Error) || result.Failed || result.Cancelled) {
                Debug.LogError("Failure: Access Token could not be retrieved");
                c = null;
            }
            else {
                c = FacebookAuthProvider.GetCredential(result.AccessToken.TokenString);

                Debug.LogError("Success: " + result.AccessToken.UserId);
            }
        });
```

But the problem is that FB never comes back from here. It is as if this never gets inside the callback function. And yes, I have ensured that FB is initialised properly.

**Comment by DellaBitta** [comment]
Hi @fer-gamboa,

The code appears to hang in the Facebook Unity SDK in RetrevieLoginStatus operation and not the Firebase Auth Unity SDK, is that correct?  If so then I recommend posting in their SDK forum.  If not, then could you please clarify which part of the Firebase SDK is failing?  Thanks!

**Comment by fer-gamboa** [comment]
Hello @DellaBitta I am not sure if it fails on the FB SDK or in Firebase. I did ask on the [Facebook SDK GitHub](https://github.com/facebook/facebook-sdk-for-unity/issues/477) with no response, and I'm not aware about other hubs.

It was my understanding that since Firebase offers FB login, you should be able to provide some assistance.

**Comment by DellaBitta** [comment]
Hi @fer-gamboa,

The facebook login code is mainly on the Firebase service side after the credential has been created.  Unfortunately we don't have much knowledge into the Facebook client SDK which is what seems to be failing.  Unfortunately the only thing I can think of doing is add a debug log at the top of the task to see if it's returning at all and to ensure that any subsequent method invocations aren't silently failing.

**Comment by fer-gamboa** [comment]
I don't have any other information to provide. Is there anything I could do to provide that? The silent login/autologin with Facebook remains not working.

**Comment by DellaBitta** [comment]
Hi @fer-gamboa,

Unfortunately we don't have working knowledge on the internals of the Facebook SDK.  I recommend isolating the problem - take out everything in callback (it looks to be modeled after the [Express Login from the Facebook guide](https://developers.facebook.com/docs/unity/examples/#express-login) so maybe just use that instead? ) and simply log output to see if it's ever called.  If it's not called then the issue seems to be entirely in the Facebook SDK and hopefully someone in the group can help you better.
