### ISSUE TITLE
FR: Add support to other platforms (WebGL, Android without PlayServices, PC, Mac, etc)

### ISSUE THREAD

**Issue by bilck** [firebase/quickstart-unity#779]
### Feature proposal

* Firebase Component: Auth, Core, Remote Config, Database, Analytics, etc
Describe your use case and/or feature request here.
We would like to use Firebase on our Unity project for platforms other than iOS and "Android with Play Services".
I understand that in some cases it's possible to create a wrapper for Rest APIs, but I believe Unity SDK should consider these platforms. By doing that it would also fix some issues related to builds and plugin conflicts.

Of course, some features would be unavailable due to native libraries dependencies or the lack of a given feature on some platforms, but at the moment it's not even viable to create a User/Password login and use Firestore to save data without resorting to a 3rd-party plugin.

**Comment by DellaBitta** [comment]
Hi @blick,

I'll send this request to our product team.   We cannot publicaly comment on our long term roadmap so I'm going to close this ticket for now.  Thanks for the post and for your enthusasim to use Firebase everywhere!
