### ISSUE TITLE
FR: Replace CustomYields for simply "await" async calls

### ISSUE THREAD

**Issue by EricBatlle** [firebase/quickstart-unity#780]
### Feature proposal

* Firebase Component: Firestore.

More than a feature request is a question (but completly not a bug), why is needed all the WaitForTaskCompletion class?
I've been reading the comment above the class, justifying that nested routines could be a problem....but why even routines?

I mean, I've replaced that structure and use **async** methods  with the keyword **await** and it works like a charm.
For example your GetKnownValue code that is using the **WaitForTaskCompletion** class:
```
protected IEnumerator GetKnownValue() {
      DocumentReference doc1 = db.Collection("col1").Document("doc1");
      var task = doc1.GetSnapshotAsync();
      yield return new WaitForTaskCompletion(this, task);
      if (!(task.IsFaulted || task.IsCanceled)) {
        DocumentSnapshot snap = task.Result;
        IDictionary<string, object> dict = snap.ToDictionary();
        if (dict.ContainsKey("field1")) {
          fieldContents = dict["field1"].ToString();
        } else {
          DebugLog("ERROR: Successfully retrieved col1/doc1, but it doesn't contain 'field1' key");
        }
      }
    }
```
Will look like:
```
protected async void GetKnownValue() 
{
  DocumentReference doc1 = db.Collection("col1").Document("doc1");
  await doc1.GetSnapshotAsync().ContinueWith((task)=>
  {
    if (!(task.IsFaulted || task.IsCanceled)) 
    {
      DocumentSnapshot snap = task.Result;
      IDictionary<string, object> dict = snap.ToDictionary();
      if (dict.ContainsKey("field1")) 
      {
        fieldContents = dict["field1"].ToString();
      } 
      else 
      {
        DebugLog("ERROR: Successfully retrieved col1/doc1, but it doesn't contain 'field1' key");
      }
    }
  });
  DebugLog("Finished GetKnownValue");
}
```
But you are the pros here, so probably I'm missing something, my question is:
Why are you doing this **WaitForTaskCompletion** class approach?

Many thanks!

**Comment by DellaBitta** [comment]
Hi @EricBatlle,

Thanks for the post!  We aim to provide example code that's common across all of our supported Unity versions.  Some of these include a version of C# that doesn't support the async and await clauses.

If you don't need your to support older versions then you can definitely use these new language features, but for now our examples have to stick with version agnostic-implementations.
