### ISSUE TITLE
System.AggregateException when invoking cloud function in Unity

### ISSUE THREAD

**Issue by trsquarelab** [firebase/quickstart-unity#782]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.24f1, also seen in the latest version
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK:  Unity Package Manager
  * Problematic Firebase Component:Cloud Functions
  * Other Firebase Components in use: Auth, Database
  * Additional SDKs you are using:
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting:  Android, and desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

Getting the below error when I try to execute any cloud function

|Unknown error, try again! System.AggregateException: One or more errors occurred. ---> Firebase.Functions.FunctionsException: INTERNAL
  at Firebase.Functions.HttpsCallableReference.<CallAsync>m__0 (System.Threading.Tasks.Task`1[TResult] task) [0x0004b] in Z:\tmp\tmp.cd1fT0ctMR\firebase\functions\client\unity\proxy\HttpsCallableReference.cs:88 
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00024] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Threading.Tasks.Task.Execute () [0x00010] in <e1319b7195c343e79b385cd3aa43f5dc>:0
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Firebase.Functions.FunctionsException: INTERNAL
  at Firebase.Functions.HttpsCallableReference.<CallAsync>m__0 (System.Threading.Tasks.Task`1[TResult] task) [0x0004b] in Z:\tmp\tmp.cd1fT0ctMR\firebase\functions\client\unity\proxy\HttpsCallableReference.cs:88 
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00024] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Threading.Tasks.Task.Execute () [0x00010] in <e1319b7195c343e79b385cd3aa43f5dc>:0 <---

UnityEngine.Debug:LogError(Object)
trrlfw.Common:Log(String, Int32) (at Assets/Trrlfw/Script/Src/Common.cs:72)
MainUI:showError(String) (at Assets/Rummy/Script/MultiPlayer/Main/MainUI.cs:311)
<>c__DisplayClass23_0:<onMatchRequestComplete>b__0() (at Assets/Rummy/Script/MultiPlayer/Main/MainUI.cs:192)
trrlfw.BaseMonoBehaviour:invokeUpdateCallback() (at Assets/Trrlfw/Script/Src/BaseMonoBehaviour.cs:29)
MainUI:Update() (at Assets/Rummy/Script/MultiPlayer/Main/MainUI.cs:69)

I have tried using java script, no issues observed. Only from Unity not able to call the cloud functions

All was working fine previously, not sure what triggered the issue. I have updated to Mac 10.15.6 (19G2021) not sure if this one caused the issue.

#### Steps to reproduce:
Just call the cloud function

What's the issue repro rate?  100%

#### Relevant Code:

```
	public Task<object> call(string method, Dictionary<string, object> args, Engine.AsyncResult.Callback callback) {
                 var mFunctions = Firebase.Functions.FirebaseFunctions.DefaultInstance;
		var function = mFunctions.GetHttpsCallable(method);
		return function.CallAsync(args).ContinueWith((task) => {
			if (callback != null) {
				var result = new Engine.AsyncResult();
				if (task.IsFaulted) {
					result.set(Engine.AsyncResult.ErrorCode.UnknownError, "Unknown error, try again! " + task.Exception.ToString());
				} else {
					result = FirebaseCommon.toResult(task.Result.Data);
				}
				callback(result);
			}
			return task.Result.Data;
		});
	}

```

**NOTE:** if I try the function with firebase emulator then it is working fine.

**Comment by trsquarelab** [comment]
One update, if I try the function with firebase emulator then it is working fine.

**Comment by DellaBitta** [comment]
Hi @trsquarelab,

There aren't any known issues executing Cloud functions with the current versions of the SDKs.  Could you work to try to reproduce this using the Unity example application as an isolated test case?  Thanks!
