### ISSUE TITLE
Can this work on desktop games?

### ISSUE THREAD

**Issue by Brainversation** [firebase/quickstart-unity#79]
Hello,

Was looking into this and was wondering if this is only for mobile or if it would work for desktop games?

Thanks in advance!

**Comment by stewartmiles** [comment]
Nope, we don't support desktop at the moment I'm afraid.

**Comment by Brainversation** [comment]
Oh no problem. Found this [issue ](https://github.com/firebase/quickstart-unity/issues/45) as well that says that.
