### ISSUE TITLE
GUID [c0ae98308ab0475a9583e1ea6e82ec65] for asset 'Packages/com.google.firebase.messaging/Plugins/Android/AndroidManifest.xml' conflicts with:   'Assets/Plugins/Android/AndroidManifest.xml' (current owner)

### ISSUE THREAD

**Issue by gaurangtalwadkar** [firebase/quickstart-unity#791]
### Please fill in the following fields:

  * Unity editor version: 2019.2.21f
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager
  * Firebase Components in use: Messaging, Analytics, Crashlytics, Dynamic Links
  * Additional SDKs you are using: Facebook, MoPub
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### Please describe the issue here: 
After installing Firebase SDK from Unity Package Manager, getting this warning
```
GUID [c0ae98308ab0475a9583e1ea6e82ec65] for asset 'Packages/com.google.firebase.messaging/Plugins/Android/AndroidManifest.xml' conflicts with:
  'Assets/Plugins/Android/AndroidManifest.xml' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
```
Tried solution mentioned here: https://github.com/firebase/quickstart-unity/issues/695, but still getting warning.
This is not a showstopper but how to fix this warning.

What's the issue repro rate? 
100%

**Comment by patm1987** [comment]
I believe that this is safe to ignore - the GUID should only really be used to hook things together in the editor (ex: adding components to game objects), and a different process picks up the `AndroidManifest.xml` for inclusion into your game. If you want to get rid of the warning, you should be able to just delete the `.meta` file from your file system (`Assets/Plugins/Android/AndroidManifest.xml.meta`) and unity should create a new one.

An interesting note is that our sun would probably explode before a GUID collision assuming randomly distributed id's (assuming one GUID per second, I think that's about 85 billion years until a 50% chance of collision - the sun will explode in 5 billion). So there still might be a bug to work around to make sure the GUIDs differ during Firebase setup. I'm not running into the issue on my own test project, but if you can get to this state again from a fresh project - give us instructions and we may move this to a bug.

I'm marking this as needs info, so the two pieces of info I'm looking for are
1) did my workaround work
2) can you get to this state again from a fresh project

**Comment by gaurangtalwadkar** [comment]
I tried deleting `Assets/Plugins/Android/AndroidManifest.xml.meta` file. But still getting the issue. 

I will try with new project and share my findings.

**Comment by gaurangtalwadkar** [comment]
I tried with new sample project but not facing the issue

**Comment by patm1987** [comment]
Talking with the engineer who worked on this feature, that file _may_ be redundant. You should be able to delete `AndroidManifest.xml` from `Assets/Plugins/Android/` entirely if you haven't modified it for any other purpose. If you have, you could try deleting and recreating it with the changes you need.

For my "delete the meta file" recommendation. It might be regenerating from the `Library/` folder. You could try dragging the file _out_ of Unity, focusing on Unity so it processes that it's been removed, then dragging it back into Unity. But it could be best to just delete it if you're not using it (or live with the warning, but I try to be in the "0 warning in shipped games" camp myself).
