### ISSUE TITLE
Event AnalyticsEventScreenView is not available

### ISSUE THREAD

**Issue by jlubeck** [firebase/quickstart-unity#793]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2.0b2.3094
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics, Analytics (Auth, Database, etc.)
  * Other Firebase Components in use: none (Auth, Database, etc.)
  * Additional SDKs you are using: none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: Not sure what this means (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

The blog post at https://firebase.googleblog.com/2020/08/google-analytics-manual-screen-view.html mentions that calling SetCurrentScreen is deprecated.

But there is no AnalyticsEventScreenView event in Firebase.Analytics.FirebaseAnalytics

I even tried sending a `screen_view` string (as that is what is mentioned in the blog post) but I'm getting back an error saying 

```
Event is not subject to real-time event count daily limit. Marking an event as real-time. Event name, parameters: error (_err), {
    ga_debug (_dbg) = 1;
    ga_error (_err) = EventNameIsReserved (13);
    ga_error_value (_ev) = screen_view;
    ga_event_origin (_o) = auto;
    ga_realtime (_r) = 1;
}
```

**Comment by jlubeck** [comment]
FYI, manually updating the pod file to use 
```
  pod 'Firebase/Analytics', '6.29.0'
  pod 'Firebase/Core', '6.29.0'
```

Made this work:

```csharp
        Firebase.Analytics.FirebaseAnalytics.LogEvent("screen_view", new Firebase.Analytics.Parameter("screen_name", name));
```

**Comment by patm1987** [comment]
Thanks for reporting this and giving us a workaround. If you've installed Messaging via the unitypackage (vs. via EDM4U), you should be able to change `MessagingDependencies.xml` from this:
```
<dependencies>
  <iosPods>
    <iosPod name="Firebase/Messaging" version="6.24.0" minTargetSdk="8.0">
    </iosPod>
  </iosPods>
  <androidPackages>
    <androidPackage spec="com.google.firebase:firebase-messaging:20.1.7">
    </androidPackage>
    <androidPackage spec="com.google.firebase:firebase-analytics:17.4.1">
    </androidPackage>
    <androidPackage spec="com.google.firebase:firebase-messaging-unity:6.15.2">
      <repositories>
        <repository>Assets/Firebase/m2repository</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```

to this:
```

<dependencies>
  <iosPods>
    <iosPod name="Firebase/Messaging" version="6.29.0" minTargetSdk="8.0">
    </iosPod>
  </iosPods>
  <androidPackages>
    <androidPackage spec="com.google.firebase:firebase-messaging:20.1.7">
    </androidPackage>
    <androidPackage spec="com.google.firebase:firebase-analytics:17.4.1">
    </androidPackage>
    <androidPackage spec="com.google.firebase:firebase-messaging-unity:6.15.2">
      <repositories>
        <repository>Assets/Firebase/m2repository</repository>
      </repositories>
    </androidPackage>
  </androidPackages>
</dependencies>
```
(ie: change the version to match the pod).

I don't know if you'll also have to track down `Firebase/Core` to make a similar change in `AppDependencies.xml`. See [this medium post](https://medium.com/firebase-developers/how-to-manage-your-native-ios-and-android-dependencies-in-unity-like-firebase-921659843aef) as an explanation of how this is all going together.

I'm going to mark this as a feature request, and it'll likely get resolved the next time the Firebase Games SDK for Unity is updated.

**Comment by chkuang-g** [comment]
Good news. [6.16.0](https://firebase.google.com/download/unity) is release and it should be using iOS SDK `6.32.2`, which is above `6.29.0` 

I'll close this issue for now.  If the issue remains, please report a new bug using [bug template](https://github.com/firebase/quickstart-unity/issues/new?labels=new&template=issue.md)
