### ISSUE TITLE
DynamicLinks.DynamicLinkReceived is never called 

### ISSUE THREAD

**Issue by claudio-tezzin-playkids** [firebase/quickstart-unity#795]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.10f
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Dynamic Link
  * Other Firebase Components in use: Analytics, Crashlytics, Config
  * Additional SDKs you are using: Facebook, AdMob, AppsFlyer, many Network Adapters
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS and Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

DynamicLinks.DynamicLinkReceived is never called when open app using Dynamic Link.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

1- Install apk at android
2- Open the app using the dynamic Link
3- Callback is not called but in android side is possible to see the link with a code like:

`        FirebaseDynamicLinks.getInstance()
                .getDynamicLink(intent)
                .addOnSuccessListener(this) { pendingDynamicLinkData ->
                    Log.w("[Dynamic Link]", "pendingDynamicLinkData: ${pendingDynamicLinkData.link}")
                }
                .addOnFailureListener(this) { e ->
                    Log.w("[Dynamic Link]", "onFailure", e)
                }
`

OR

1- Click dynamic Link
2- It will send to google play store
3- Manually install apk with unity dynamic link implemented.
4- Callback is not called but in android side is also possible to see the link

I used this sample project as example but did not tried it directly.

#### Relevant Code:

`Initialize is called as soon as Firebase is ready.`

```
public class FirebaseDynamicLinkManager : MonoBehaviour
    {
        Uri _lastLinkUrl;

        public void Initialize()
        {
            Debug.Log("Dynamic link initialized");
            DynamicLinks.DynamicLinkReceived += OnDynamicLink;
        }
        
        void OnDestroy() {
            Debug.Log("Dynamic link destroyed");
            DynamicLinks.DynamicLinkReceived -= OnDynamicLink;
        }

        void OnDynamicLink(object sender, EventArgs args) {
            Debug.Log("Dynamic link event received");
            var dynamicLinkEventArgs = args as ReceivedDynamicLinkEventArgs;
            if (dynamicLinkEventArgs == null)
            {
                Debug.Log("Dynamic link cast failed.");
                return;
            }
            _lastLinkUrl = dynamicLinkEventArgs.ReceivedDynamicLink.Url;
            Debug.LogFormat("Received dynamic link {0}", _lastLinkUrl.OriginalString);
            Debug.LogFormat("Received dynamic link query {0}", _lastLinkUrl.Query);
        }
    }
```

**Comment by cynthiajoan** [comment]
Hi @claudio-tezzin-playkids, can you try to use the pattern in our quickstart app, add the callback after firebase initialization is done, to see if that can fix your issue?

https://github.com/firebase/quickstart-unity/blob/master/dynamic_links/testapp/Assets/Firebase/Sample/DynamicLinks/UIHandler.cs

public virtual void Start() {
      FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
        dependencyStatus = task.Result;
        if (dependencyStatus == DependencyStatus.Available) {
          DynamicLinks.DynamicLinkReceived += OnDynamicLink;
        } else {
          Debug.LogError(
            "Could not resolve all Firebase dependencies: " + dependencyStatus);
        }
      });
    }

**Comment by claudio-tezzin-playkids** [comment]
That is the exactly way that we use the firebase:

`void Start()
        {
            //Crashlytics doc says to init on Start 
            CheckDependency();
        }

        void CheckDependency()
        {
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task => {
                var dependencyStatus = task.Result;
                if (dependencyStatus == DependencyStatus.Available) {
                    InitializeFirebase();
                } else {
                    Debug.LogError($"Could not resolve all Firebase dependencies: {dependencyStatus}");
                    // Firebase Unity SDK is not safe to use here.
                }
            });
        }

        void InitializeFirebase()
        {
            _remoteConfigManager.Initialize();
            _dynamicLinkManager.Initialize();
            IsInitialized = true;
        }


      // REMOTE CONFIG
       public void Initialize()
        {
            Debug.Log("Dynamic link initialized");
            DynamicLinks.DynamicLinkReceived += OnDynamicLink;
        }
`

**Comment by claudio-tezzin-playkids** [comment]
I just could test the iOS version and it is working fine. The issues just at android build.

Any help with that?

**Comment by chkuang-g** [comment]
@claudio-tezzin-playkids 

Could you try to upgrade to the latest `6.16.1` and use [Dynamic Link quickstart](https://github.com/firebase/quickstart-unity/blob/master/dynamic_links/testapp/) and see if you can reproduce the same issue?  

I did just try it and DynamicLinkReceived did get called properly. I am wonder if this could be an issue in combination with other plugins, ex. AppsFlyer. (Similar to this one https://github.com/firebase/quickstart-unity/issues/626 but on Android instead)

Thanks,
Shawn

**Comment by claudio-tezzin-playkids** [comment]
I will check it and return to you!
