### ISSUE TITLE
Firebase Unity SDK is still using the Direct Channel API 

### ISSUE THREAD

**Issue by T-Y-GHub** [firebase/quickstart-unity#796]
Firebase Team sent the following email to developers in May 2020:
> [Action Required] Firebase Messaging iOS SDK v7.0 will no longer support the FCM Direct Channel API

The email tells us to stop using "[FCM Direct Channel API](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessaging#shouldestablishdirectchannel)" in our app as soon as possible.

However, the API is enabled by the Firebase Unity SDK.
Specifically, Firebase Messaging sets YES to shouldEstablishDirectChannel when AppDelegateApplicationDidBecomeActive.
<img width="1309" alt="スクリーンショット 2020-09-24 18 19 02" src="https://user-images.githubusercontent.com/24775849/94249654-27057f80-ff5b-11ea-973a-ae8be4bbb78e.png">

Firebase Unity SDK must be updated to stop using the "FCM Direct Channel API".

**Comment by cynthiajoan** [comment]
Hi @T-Y-GHub, thanks for bringing this up. We are aware of it and working on an update to fix the issue. We will ping in this thread when the release of the change is out.

**Comment by cynthiajoan** [comment]
This is updated in 7.0.0
