### ISSUE TITLE
can't receive the notification when the app is killed

### ISSUE THREAD

**Issue by Leo-lwj** [firebase/quickstart-unity#797]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.13
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: FirebaseMessaging (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: FirebaseMessaging (Auth, Database, etc.)
  * Other Firebase Components in use: no (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

I use link send message like this : https://console.firebase.google.com/project/xxxx-xxxx/notification/compose

When the app in the foreground and background, my android  device can be receive messages and notifications.
But, when the app is killed(just do Closed game (swipe away)), I'm waiting with my device.  waiting, waiting, waiting... 
.After a long time, my device is not very happy and can't display any notifications.
What can I do here, and then my device can be informed？

**Comment by chkuang-g** [comment]
@Leo-lwj 

Sorry for the late reply.

I actually tried both Firebase `6.15.2` and the latest `6.16.0` with [FCM quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) and I actually can still receive push notification after the app is in foreground, background or after killed, if I subscribed to the topic.

Could you try and see if you can reproduce the issue with quickstart?  Also, could you give us an example about how you compose the notification, ex what you filled in each field?

Shawn

**Comment by matmlyreal** [comment]
Have had the same issue. In my case it happened when I launch the application via Android Studio run button. What I had to do was to run the freshly builded app on the device as usual. Then Kill the app, open again by tapping on the app icon on the device, then kill or close the app again and then voila. Now I can receive push notifications even when the app is closed.

**Comment by chkuang-g** [comment]
@matmlyreal 

Did you try to build Android apk from Unity directly? 
Also, could you detail about your process to create Android project and some more information such as Unity version, Firebase SDK version, like those from the template.
It would be great if you can provide a minimum viable produce, like modified quickstart.

Shawn
