### ISSUE TITLE
Not found Assets/Plugins/Android/libmessaging_unity_player_activity.jar after installed Unity Firebase Cloud Messaging

### ISSUE THREAD

**Issue by masaki-takano** [firebase/quickstart-unity#799]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.4f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Cloud Messaging
  * Other Firebase Components in use: Analytics, Auth, Crashlytics 
  * Additional SDKs you are using: No
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: Mono and/or IL2CPP

### [REQUIRED] Please describe the issue here:

1. Install Cloud Messaging by Unity Package Manager
2. Assets -> "External Dependency Manager" -> Android -> Resolve
3. not found `Assets/Plugins/Android/libmessaging_unity_player_activity.jar`

**Comment by cynthiajoan** [comment]
Hi @masaki-takano, can you check if you still have firebase sdk files under Assets folder? If so please delete them and try resolve again, to see if that can fix your issue.
