### ISSUE TITLE
All firebase plugins in one project

### ISSUE THREAD

**Issue by sezeregrek** [firebase/quickstart-unity#8]
Do you have plan to create an Unity project that includes all of plugins?

**Comment by stewartmiles** [comment]
Not at the moment.

What exactly do you want to see?

**Comment by sezeregrek** [comment]
I have a problem when I have imported auth and db plugins in my project. Problem is that when I try to auth from apk on my phone, I see user is authenticated in firebase console but call back functions didn't called. Do you have any suggestions?

**Comment by stewartmiles** [comment]
Could you see whether the problem occurs with the authentication sample which hooks an event to determine when a user logs in / logs out ? https://github.com/firebase/quickstart-unity/tree/master/auth/testapp

User change events are hooked here:
https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/TestApp/UIHandler.cs#L108

Here's an example of a callback after sign-in:
https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/TestApp/UIHandler.cs#L147

**Comment by sezeregrek** [comment]
There is no problem with using only auth pulgin in unity. if I add database plugin, I can send and receive data from database (editor auth via p12 file), but there is no response from Android login. 

Also, when I try to login from editor, there is no "System.AggregateException: Exception of type 'System.AggregateException' was thrown." in console. I know, yo dont support editor login, I just wanna see the error message. 

https://github.com/firebase/quickstart-unity/issues/3

**Comment by stewartmiles** [comment]
Similar to https://github.com/firebase/quickstart-unity/issues/5 you need to sign your application for Auth to work on Android.

From https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/readme.md

- To [generate a SHA1](https://developers.google.com/android/guides/client-auth),
        first you will need to set the keystore in the Unity project.
        - Locate the `Publishing Settings` under `Player Settings`.
        - Select an existing keystore, or create a new keystore using the toggle.
        - Select an existing key, or create a new key using "Create a new key".
      - After setting the keystore and key, you can generate a SHA1 by
        running this command:
        ```
        keytool -exportcert -list -v -alias <key_name> -keystore <path_to_keystore>
        ```

**Comment by stewartmiles** [comment]
@sezeregrek any progress on your side?  Did you get this to work?

**Comment by stewartmiles** [comment]
We now have a sample that integrates *almost* all Firebase features, check it out here:
https://github.com/google/mechahamster
