### ISSUE TITLE
Invalid bitcode version

### ISSUE THREAD

**Issue by cgascons** [firebase/quickstart-unity#800]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.3f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: ---
  * Other Firebase Components in use: Auth, FCM, Crashlytics, Realtime DB
  * Additional SDKs you are using: Google Analytics for Firebase/Google App Bundle/Google In-App Review
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Stuck when archiving project from xCode v 11.3.1, building from xCode works fine, but when archiving to install the app on a device this error shows up.

`ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.29.0_0' Reader: '1100.0.33.17_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.17)' for architecture arm64`

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Haven't tried
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
1 - Build the game on Unity making sure to select xCode v 11.3.1
2 - Once the build is done and since we are using Firebase, we followed the steps mentioned in the Firebase dashboard when adding an iOS app and installed the pod via `pod install`, that successfully installed the dependencies
3 - Open xCode project by double clicking on the _Unity-iPhone.xcworkspace_ file created
4 - Build for Generic device
5 - Archive -> When this process is close to ending it will crash generating the trace posted above.

Notice that, after googling for this issue I ended up reading this post [here](https://forum.unity.com/threads/ld-could-not-reparse-bitcode-bundle-on-ios-builds.669451/) which as far as I understand is telling me that the project has a library that has been generated using a more recent xCode build that the one I have, even though I don't quite understand the build number nomenclature here, I understand I am the "reader" here, hence I should have the same version than the producer, right?

**Comment by cynthiajoan** [comment]
Hi @cgascons, in our SDK 6.15.2, we are building agains xCode 11.4, so the bitcode issue usually caused by the conflict in different xCode versions. Could you try with xCode 11.4 to see if you can get it working? Thanks!

**Comment by cgascons** [comment]
Hi @cynthiajoan, thank you for replying, that's indeed what I understand, 6.15.2 builds against xCode 11.4 (could not find that information in the release notes by the way and it's quite useful). My problem is, I can't use xCode 11.4 with my current OS version (Mojave 10.14.5), I need to update my os to Catalina in order to be able to use it and can't do that because I use some old 32 bit software that won't run on that OS. I'm quite in the middle of a very serious compatibility issue here and I'm not sure how to proceed.

**Comment by cynthiajoan** [comment]
I see. Yeah that's really annoying. The current work around I can think of is since we bumped xCode version only in 6.15.2, so to unblock you for now, probably worth rolling back to 6.15.1 or earlier to make it working. Can you try with that to see if 6.15.1 can satisfy your need?

**Comment by cgascons** [comment]
I would downgrade to 6.15.1 but that would be leaving trouble for the future when we need to update the plugin for any other reason. Not sure what we will end up doing but thanks anyways for the info. Also, regarding the comment I made about the release notes, is there any other page we can visit to check which xCode version was used to make each update?
Thanks,

**Comment by cynthiajoan** [comment]
@cgascons, thanks for pointing out, we will add a section to clarify the xcode version.

**Comment by chkuang-g** [comment]
@cgascons Thanks for reporting.  We added the minimum Xcode version in our release note.

https://firebase.google.com/support/release-notes/unity
