### ISSUE TITLE
DllNotFoundException: FirebaseCppApp-6_15_2

### ISSUE THREAD

**Issue by bauervision** [firebase/quickstart-unity#801]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.5f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono
### [REQUIRED] Please describe the issue here:

After setting everything up per the instructions listed here under android:
[auth quick start](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp)

When I go to deploy to my device, debugging enabled, I get the following error logged:
`AndroidPlayer(ADB@127.0.0.1:34999) DllNotFoundException: FirebaseCppApp-6_15_2`

And the app itself says:
`One of more Firebase dependencies are not present
Current dependency status: UnavailableOther`

#### Steps to reproduce:

Reproduced this issue with my project and the Github Auth Quick Start project listed above.

Followed the steps in the quick start guide, go to build, and the
`FirebaseCpp-App-6_15_2`
is always missing.

In Unity Package Manager I see that Firebase App(Core) Firebase Authentication are installed.

[Closed issue regarding this DLL file](https://github.com/firebase/quickstart-unity/issues/732) was of no help, so I opened a new issue.

**Comment by cynthiajoan** [comment]
Hi @bauervision, can you refer #732 and follow the steps in Package Manager to see if that can fix your problem? Thanks.

**Comment by bauervision** [comment]
I have followed those steps. 

I just removed all firebase dependencies from my manifest, and then re-added them via the Package manager, going from :
Firebase App (Core) first and then Firebase Auth.

Now my manifest now shows
`"com.google.firebase.app": "6.15.2", "com.google.firebase.auth": "6.15.2",`

And package manager confirms these.

However, now when I build the app, after I removed and re-added to the manifest, I get this error pop during build
`A failure occured while executing
com.android.build.gradle.internal.tasks.Workers$ActionFacade`

As well as:
`type bitter.jnibridge.JNIBridge$a is defined multiple times` 
`com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: `
and a slew of other errors, all seemingly stemming from  multiple class definitions

Running the Android Resolver didn't help, nor did Force Resolve

**Comment by chkuang-g** [comment]
Good news. [6.16.0](https://firebase.google.com/download/unity) is release and it should include the fixes described in this post. https://github.com/firebase/quickstart-unity/issues/677#issuecomment-703816821

I'll close this issue for now.  If the issue remains, please report a new bug using [bug template](https://github.com/firebase/quickstart-unity/issues/new?labels=new&template=issue.md)
