### ISSUE TITLE
[FirestoreProperty] Dictionary<string, struct> causes AOT error in il2cpp builds

### ISSUE THREAD

**Issue by christianmrswordsmith** [firebase/quickstart-unity#802]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.9f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Cloud Firestore for Firebase (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows 10 (Mac, Windows, or Linux)
  * Platform you are targeting: iOS, Android  (iOS, Android, and/or desktop)
  * Scripting Runtime:  IL2CPP  (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
Dictionaries with structs in documents will fail deserialization using DocumentSnapshot.ConvertTo<T>. Changing from struct to a class makes this issue go away. This happens in IL2CPP builds. Not in the editor.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

Exception:
Attempting to call method 'Firebase.Firestore.Converters.ConverterCache::CreateDictionaryConverter<Mws.Project.Storage.TestStruct>' for which no ahead of time (AOT) code was generated.

Stack trace:
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
Firebase.Firestore.Converters.AttributedTypeConverter.SerializeMap (Firebase.Firestore.SerializationContext context, System.Object value, System.Collections.Generic.IDictionary`2[TKey,TValue] map)
Firebase.Firestore.Converters.MapConverterBase.Serialize (Firebase.Firestore.SerializationContext context, System.Object value)
Firebase.Firestore.ValueSerializer.Serialize (Firebase.Firestore.SerializationContext context, System.Object value)
Firebase.Firestore.WriteBatch.Set (Firebase.Firestore.DocumentReference documentReference, System.Object documentData, Firebase.Firestore.SetOptions options)
Mws.Project.Storage.AccountStorage+<CreateProfileState>d__20.MoveNext ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext (System.Object stateMachine)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run ()
System.Threading.Tasks.AwaitTaskContinuation.InvokeAction (System.Object state)
System.Threading.Tasks.AwaitTaskContinuation.RunCallback (System.Threading.ContextCallback callback, System.Object state, System.Threading.Tasks.Task& currentTask)

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
ProfileStateDocument profileStateDocument = snapshot.ConvertTo<ProfileStateDocument>();

Data structure that fails: 
[FirestoreData]
public class ProfileStateDocument
{
		[FirestoreProperty] public Dictionary<string, TestStruct> TestStructDictionary { get; set; } = new Dictionary<string, TestStruct>();
}

[FirestoreData]
public struct TestStruct
{
	[FirestoreProperty] public string TestData { get; set; }

	public TestStruct(string testData)
	{
		TestData = testData;
	}

}

```
// TODO(you): code here to reproduce the problem
```

**Comment by wu-hui** [comment]
Unfortunately this is a platform (IL2CPP) restriction: generic methods cannot be instantiated with custom value type, because they are instantiated at compile time, and the memory size of the value type would be unknown.

The workaround, as you already noted, is to use a reference type, or do manual deserialization for value types in dictionaries.

We will add this as a caveat to the SDK in our doc, and also try to warn users in log messages.

In the meantime, I am closing this issue, sorry for the inconvenience.

**Comment by christianmrswordsmith** [comment]
@wu-hui Ok! Surprising as deserialization of dictionary<string, struct> works fine in Json.net.
