### ISSUE TITLE
 Firestore crashes Unity Editor; if 2 sessions have been launched

### ISSUE THREAD

**Issue by shadd3** [firebase/quickstart-unity#804]
Hi,

Firestore crashes Unity editor.
if 2 sessions of Unity Editor have been launched with Firestore running.

Maybe see also #699

Unity3d 2019.4.5f1
Firestore 6.15.2

Thanks

**Comment by cynthiajoan** [comment]
Hi @shadd3, could you please provide a bit more information, especially the crash stack? Thanks!

**Comment by wilhuff** [comment]
Without further details, it's hard to be sure, but I suspect this is intended, though crashing is not the way we want to handle this. Firestore for Unity is still an alpha product though, so some rough edges are still there.

At issue is that Firestore uses persistent storage by default, and that backing store is opened exclusively. The second session for the same project is trying to open the underlying database and failing.

Assuming this is the issue, there are several workarounds:

  * Disable persistence in all but the first instance
  * Use a different Firebase App name for each instance (every App is stored separately)
  * Use a different GCP Project for each instance (every Project is also stored separately)

The error and stack trace would confirm this. I'm going to close this issue given that it matches something I expect, though if your error message and stack trace don't support this conclusion, I'll happily reopen.
