### ISSUE TITLE
Unity- Android- Notifications not showing on the system tray when application is in foreground

### ISSUE THREAD

**Issue by hehehoho1** [firebase/quickstart-unity#81]
Hi, I've just integrated firebase messaging, it works as expected when the app is in background or not running, but when  the app is in foreground, when a message was fired, my Android test device receive that a message was received (by logging a Debug log when the Firebase.Messaging.FirebaseMessaging.MessageReceived was fired) but the notification not showing on the system tray. 

I have no idea what going wrong?? Please have, thanks!

**Comment by stewartmiles** [comment]
That's the intended behavior, the message is routed to your application where you can decide whether or not to show the notification in the app or in the system tray.  Typical behavior for applications is to pop it up in the context of the app running in the foreground.
See https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages for the different cases.
