### ISSUE TITLE
AndroidX dependencies are not automatically added in Unity 2020.1 with the Firebase 6.16.0 SDK when using a mainTemplate.gradle

### ISSUE THREAD

**Issue by patm1987** [firebase/quickstart-unity#810]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.6f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database (Auth, Database, etc.)
  * Other Firebase Components in use: Database (Auth, Database, etc.)
  * Additional SDKs you are using: none (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

When building a Firebase project (in this case, the Database test app) with a `mainTemplate.gradle`, I get the following issue:
```
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

It will go away if I also generate a `gradleTemplate.properties` file with `android.useAndroidX=true` in it or if I delete the `mainTemplate.gradle` file.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
1. Check out one of the test apps (I used the Database one).
2. Add a mainTemplate.gradle file
![image](https://user-images.githubusercontent.com/1111611/95138690-0b9f2f00-0728-11eb-9944-3fc8e797485e.png)
Restart Unity (you may get a resolution failed error if you don't perform this step)
3. Click "Build And Run" for Android

Android Resolver Settings:
![image](https://user-images.githubusercontent.com/1111611/95138846-70f32000-0728-11eb-9161-2796e5041a5b.png)

Workaround (if you need a `mainTemplate.gradle` file, it works fine without one):
1. Also generate a `gradleTemplate.properties` file:
![image](https://user-images.githubusercontent.com/1111611/95138898-92540c00-0728-11eb-8dee-df224bcfbed5.png)
2. Add `android.useAndroidX=true` to the end of it. Note that just generating this file is not enough, but it must be modified as well.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? 100%

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by vimanyu** [comment]
I could not reproduce this on my end. I tried both in 2019.4 and 2020.2. Here are the steps I followed,

- Fresh checkout of Unity firebase database quickstart testapp
- Launch Unity (2019 or 2020)
- Player Settings -> Settings for Android -> Publishing Settings -> Enable Custom Gradle Template
- Add Google Package Registry (manually modifying Package.manifest in 2019 and using Project Settings -> Package Manager -> Scoped Registries in 2020)
- Install Firebase Database via UPM
- Assets -> External Dependency Manager -> Android Resolver -> Settings -> Enable "Use Jetifier"
- Assets -> External Dependency Manager -> Android Resolver -> Force Resolve
Expected error:
```
Resolution failed because EDM4U could not enable Jetifier in Unity 2020.1 without Custom Gradle Properties Template. Please enable 'Custom Gradle Properties Template' found under 'Player Settings > Settings for Android -> Publishing Settings' menu. Due to changes in Gradle project generated by Unity 2019.3 and above, our recommended way of enabling Jetifier is by injecting properties to Assets/Plugins/Android/gradleTemplate.properties.
```
- Player Settings -> Settings for Android -> Publishing Settings -> Enable Custom Gradle Properties Template
- Force Resolve again (should be successful)
- Build 
Error on first build:
```
Failed to update Android SDK package list. See the Console for details.
```
- Restart Unity -> Build 
Everything works aside from that build error on first time builds.

**Comment by patm1987** [comment]
After some experimenting, I have verified that a "Force Resolve" after generating a `gradleTemplate.properties` file does add the necessary entries:
```
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.parallel=true
android.enableR8=**MINIFY_WITH_R_EIGHT**
# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
**ADDITIONAL_PROPERTIES**
```

**Comment by vimanyu** [comment]
Talking to @patm1987, the difference was that I ran a "Force resolve" before building. The bug here is that a build should trigger this resolution automatically and that isn't happening.

**Comment by vimanyu** [comment]
There were many corner cases and we ended up resorting to a strategy to ensure we resolve dependencies atleast once "Auto resolve on Build" is enabled. There are several triggers (eg: change in Build Settings or Android Resolver settings) that dictate to the system whether it should resolve dependencies or not. Aside from that, we were also optimizing based on if the module is already loaded. 
Newer versions of Unity do not reload the entire app domain. This caused our optimization to not function as expected. 
Now, we are utilizing a Unity post-build callback to reset things after a build. The issue is that this reset only happens after a successful build. If the build fails, it is highly advisable to manually "Force Resolve" from the menu.

Related commit,
https://github.com/googlesamples/unity-jar-resolver/commit/76a3f36fabc592933ded1a3115d0db4ded74ed9d

https://github.com/googlesamples/unity-jar-resolver/commit/76a3f36fabc592933ded1a3115d0db4ded74ed9d
