### ISSUE TITLE
Firebase 6.16.0 + Unity 2020.1 + UPM = not generating the AndroidManifest.xml

### ISSUE THREAD

**Issue by bauervision** [firebase/quickstart-unity#811]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.7f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: App
  * Other Firebase Components in use: Auth, Database
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

With the latest 6.16 update a lot of my issues and workarounds to get firebase working on android have been cleared up but one thing remains, if I use the UPM to install Firebase, I can't get the androidManifest to generate which means that there is no
`/Plugins/Android/Firebase*` being generated either

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes
What's the issue repro rate?100%

What happened? How can we make the problem occur?

* Make sure that `google-services.json` is present inside of assets folder.

* Add the scoped registries to the manifest.json
````
"scopedRegistries": [
    {
      "name": "Game Package Registry by Google",
      "url": "https://unityregistry-pa.googleapis.com",
      "scopes": [
        "com.google"
      ]
    }
  ]
````

* Then install the Firebase App, Auth, whatever, modules via UPM.
* Verify that after all resolutions are complete, it is still missing the AndroidManifest as well as everything inside of Plugins/android/Firebase*
* StreamingAssets folder is also not created

I notice that when I go import the sdk via unitypackage, that the `Plugin/Android/Firebase` structure is present, but not from using the UPM. Is there a step I'm missing here? 

Additonally, is there anything I can do, when on Android, to stop the iOS.Extensions.Xcode from getting installed?

I'd like to stop getting the `Assembly 'Packages/com.google.firebase.app/Firebase/Editor/Firebase.Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'UnityEditor.iOS.Extensions.Xcode'. Is the assembly missing or incompatible with the current platform?` Error.

**Comment by chkuang-g** [comment]
Hi @bauervision 

I found that Unity 2020 is getting more and more aggressive in searching any reference to `UnityEditor.iOS.Extensions.Xcode` in the assemblies.  I think we removed all of the reference from class properties and function parameters a while ago but I did occasionally saw the error message you mentioned on Windows.

This usually goes away after I restarted Unity.  Could you try to restart Unity and see if that helps?

Shawn

**Comment by bauervision** [comment]
Yep, a restart did in fact generate the folder structure, and removed the Xcode error.

All errors are now cleared, and it is deploying successfully to the phone.

Maybe we can throw in a pop up that tells the user Unity needs to restart after Firebase sdk is installed? @chkuang-g

**Comment by bauervision** [comment]
Actually... @chkuang-g I'm now getting a Unity crash when I try to Play in the editor.

Deploying to the device went flawlessly, but continuing development and testing in the editor proves impossible. Bug has been reported to Unity as well.

**Comment by chkuang-g** [comment]
FYI, there is an issue with Database in editor https://github.com/firebase/quickstart-unity/issues/807

The temporary fix is to create the proper folder as mentioned by the folder.
