### ISSUE TITLE
Metadata server endpoints are now deprecated- Firebase cloud functions

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#812]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____
 "firebase-functions": "^3.11.0"
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
 "firebase-functions": "^3.11.0"
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

I got this in the email "Our records show that you own projects with App Engine applications or Cloud Functions that are still calling the pre-GA v0.1 and v1beta1 endpoints of the App Engine and Cloud Functions metadata server. These endpoints are in the process of being turned down."

I use the latest Firebase Functions SDK version

"@google-cloud/logging": "^4.1.0",
"firebase-admin": "^9.2.0",
"firebase-functions": "^3.11.0"
"node": "10"
My code uses the admin and Firebase Database

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

`exports.func2 = functions.https.onCall(async (data, context) => {
 console.log('connected');
 let curCoins=0;
 const uid = context.auth.uid;
 const date =data.date;

 if (context.auth!==null)
 {
 await admin.database().ref(`/users/${uid}/coins`).once('value').then(function(snapshot)
 {
 if (snapshot.child(oid).exists()) 
 {
   OrderExistOnDB= 1;}
 })

 const doc: any = {
 purchasedDate: date,
 price: dollarPrice,
 };

 await admin.database().ref(`/users/${uid}/1/proVersion`).set(1);

  }}
  return 0;

  });`
```

**Comment by chkuang-g** [comment]
Hi @shlighter 

This repo is for Firebase Unity SDK, and your question does not seem to be related to it.

According to your description, I assume you are using Firebase Admin Node.js SDK, is that correct?  In that case, you will have a better chance to get your answer by filing a question here.
https://github.com/firebase/firebase-admin-node/issues

Please let me know if I understand it incorrectly.

Thanks,
Shawn
