### ISSUE TITLE
FirebaseAnalytics.GetAnalyticsInstanceIdAsync().ContinueWithOnMainThread() crashes on iOS 9 devices.

### ISSUE THREAD

**Issue by emreyanik** [firebase/quickstart-unity#815]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2018.4.19f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Messaging, Crashlytics
  * Additional SDKs you are using: Facebook, Adjust, Helpshift, One Signal
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS & Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

We have two iOS 9 (9.3.5) test device and both crashes when we call FirebaseAnalytics.GetAnalyticsInstanceIdAsync().ContinueWithOnMainThread() method everytime.

For a test purpose we tried to prevent getInstanceId method call on iOS 9 and there is not any crash.

Stack trace:

EXC_BREAKPOINT 0x00000000e7ffdefe
Crashed: Thread
0  ???                            0x1fe8b08c (Missing)
1  ???                            0x1fe8da7b (Missing)
2  ???                            0x1fe8dcd9 (Missing)
3  ???                            0x25b4e444 (Missing)
4  dev                            0x2077469 firebase::analytics::AnalyticsDataResetter::GetInstanceId() + 34641001
5  dev                            0x207728b firebase::analytics::GetAnalyticsInstanceId()::$_0::__invoke(firebase::SafeFutureHandle<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*) + 34640523
6  dev                            0x2077963 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(firebase::SafeFutureHandle<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*), firebase::SafeFutureHandle<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*> >(void*) + 114
7  libsystem_pthread.dylib        0x25ccb85b _pthread_body + 138
8  libsystem_pthread.dylib        0x25ccb7cf _pthread_start + 110
9  libsystem_pthread.dylib        0x25cc9724 thread_start + 8

#### Relevant Code:

```
FirebaseAnalytics.GetAnalyticsInstanceIdAsync().ContinueWithOnMainThread(task =>
{
	if (task.IsCompleted)
	{
		...
	}
});
```

**Comment by chkuang-g** [comment]
Hi @emreyanik 

Thank you for reporting this.

Which Firebase SDK version did you use before which did not cause the crash?
Also, do you have other devices in different iOS version which did not crash?

We have not updated Analyitcs C++/Unity SDK for a while so any more information can help us to pinpoint the issue.

Thanks,
Shawn

**Comment by emreyanik** [comment]
Hi @chkuang-g 
We used Firebase Unity v6.1.1 before.
We tested new sdk on ios 10,11,12,13 and 14 devices and there is not any crash like ios9.

Due to this crash and more problems related to ios9, we decided to drop iOS 9 support.

**Comment by chkuang-g** [comment]
I see.

Firebase Unity v6.1.1 is using Firebase/Analytics Cocoapod (6.1.0), and Unity v6.16.0 is using 6.32.2.  Many changes probably was made.

I can ping the team and see if there is any tracked issue related to this, or whether iOS 9 is still supported by the iOS team.

Shawn

**Comment by chkuang-g** [comment]
The team confirmed that iOS 9 should still be supported in the current version of Analytics (iOS SDK 6.32.2)

It is not clear what is causing it yet.

There is another thread https://github.com/firebase/firebase-ios-sdk/issues/6392 which _may_ be related.

**Comment by cynthiajoan** [comment]
With the related issue that mentions Unity 8.10.0 has the fix, would close this legacy one and please open a new one with latest SDK if it still exists.
