### ISSUE TITLE
Change icon on push notification

### ISSUE THREAD

**Issue by felipeprov** [firebase/quickstart-unity#82]
Hi
I am trying to integrate the firebase-notification in my game, i am receiving the messages correctly, but the notifications are using the main icon of my app, that becomes a white block in the notication bar. So i need the push notications use my second icon (ic_stat_ic_notification.png).

I tried to add 
```
 <meta-data
	android:name="com.google.firebase.messaging.default_notification_icon"
	android:resource="@drawable/ic_stat_ic_notification" />
```

in the AndroidManifest.xml, 
And i have a ic_stat_ic_notification.png in the drawable folder if i open the APK.

So i think, everything is in place...

But it always uses the wrong icon...

I am sending messages using the console with the key **icon** defined.

There is anything else i am supposed to do to change the notification icon?

Best Regards

**Comment by stewartmiles** [comment]
All the details are here https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest

From your manifest snippet it looks like you're doing the right thing.  Have you verified the final merged manifest included in your APK includes this metadata?

**Comment by felipeprov** [comment]
@stewartmiles  thank you very much your answer!

I just found my mistake:
my xml hierachy was incorrect!

I will just leave it here, in case someone have the same problem
```

<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
    xmlns:tools="http://schemas.android.com/tools"
    android:installLocation="preferExternal"
    android:versionCode="1"
    android:versionName="1.0">
    <supports-screens
        android:smallScreens="true"
        android:normalScreens="true"
        android:largeScreens="true"
        android:xlargeScreens="true"
        android:anyDensity="true"/>

    <application
        android:theme="@style/UnityThemeSelector"
        android:icon="@drawable/app_icon"
        android:label="@string/app_name"
        android:debuggable="true">
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>
	<meta-data
	      android:name="com.google.firebase.messaging.default_notification_icon"
              android:resource="@drawable/icon2" />
      
    </application>
</manifest>

```
