### ISSUE TITLE
Error: status is pending return the pending future when calling RequestPermissionAsync on iOS

### ISSUE THREAD

**Issue by thsbrown** [firebase/quickstart-unity#821]
### Please fill in the following fields:

  * Unity editor version: 2018.4.17f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Cloud Messaging (Auth, Database, etc.)
  * Other Firebase Components in use: Core (Auth, Database, etc.)
  * Additional SDKs you are using: PlayFab (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### Please describe the issue here:

For some reason when I call `await FirebaseMessaging.RequestPermissionAsync()` I seem to always get the error `Error: status is pending return the pending future`. I have also tried using `ContinueWithOnMainThread` as well as `ContinueWith` and I still get the same error.

#### Steps to reproduce:

What's the issue repro rate? 100%

1. Create a script with a function that contains `await FirebaseMessaging.RequestPermissionAsync()`
2. Trigger the function on a button press.
3. Check the runtime debug logs.
4. Notice the error `Error: status is pending return the pending future`

#### Relevant Code:

```
public static async Task Initialize()
{
    await FirebaseMessaging.RequestPermissionAsync();
    DissmissCanvasController();
}
 ```

**Comment by chkuang-g** [comment]
HI @thsbrown 

I actually tried our [FCM quickstart]https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp and did not see the fail.

Note that it is calling `FirebaseMessaging.RequestPermissionAsync` in the continuation function of `Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread`

https://github.com/firebase/quickstart-unity/blob/72fea4d7dab8eb0315e0bfc25710fdd8d3fa22ca/messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs#L89

Could you check if you configure your Xcode project properly, specifically Capability and Framework part?
https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp#ios

Also make sure that you configure your certs properly.
https://firebase.google.com/docs/cloud-messaging/ios/certs 

And do try our quickstart and follow every instructions.  

Let us know if this helps!
Shawn

**Comment by thsbrown** [comment]
I'll go ahead and check this bit out and get back to you asap! Thanks for looking into this 👍 .
