### ISSUE TITLE
Firebase realtime database returns snapshot with only 1 child. ( ChildrenCount returns one)

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#823]
"info" : {
  "created" : "2020/10/06  19:35:57",
   "last" : "Peterre",
   "name" : "Dan"
}

`
    var task = await FirebaseDatabase.DefaultInstance.GetReference("users/" + nameID+"/info").GetValueAsync().ContinueWith(t => t);
 
if (task.IsCompleted)
{
 DataSnapshot users = task.Result;
 Debug.Log(users.ChildrenCount); // returns "1", (it should be "3")
 Debug.Log(users.Child("last").Exists);// returns true
 Debug.Log(users.Child("name").Exists);//return false
 foreach (DataSnapshot fss in users.Children)
 {
   Debug.Log(fss.Key); //itirates only one time, returns "last"
 }
 }`

I checked the address a few times and even copied Debug.Log(users.Reference) and pasted it in the browser and I see the DB with 3 fields- "created" "last" and "name". Why does it show only "last"???? What am I missing??

*Note, sometimes when I start the app it shows "name" but not "last"
I also tried DataRefence.KeepSynced(true) and it's still problematic

[https://i.stack.imgur.com/nGiWI.png](https://i.stack.imgur.com/nGiWI.png)

Unity- 2019.3.13f1
Firebase- 6.14.1

**Comment by chkuang-g** [comment]
Hi @shlighter 

Please please follow the [bug template](https://github.com/firebase/quickstart-unity/issues/new?labels=new&template=issue.md) and it can save time for back and forth.

  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

**Comment by shlighter** [comment]
Source you installed the SDK: unitypackage
Other Firebase Components in use:Auth, Database,Functions, storage
Additional SDKs you are using: none
Platform you are using the Unity editor on:Windows
Platform you are targeting: ios, android
Scripting Runtime:IL2CPP

**Comment by patm1987** [comment]
Hi @shlighter ,

Can you try a few things?

First:
````
var task = await FirebaseDatabase.DefaultInstance.GetReference("users/" + nameID + "/info").GetValueAsync().ContinueWith(t => t);
```

might not be doing what you think it's doing. Try changing it to just:
```
var DataSnapshot = await FirebaseDatabase.DefaultInstance.GetReference("users/" + nameID + "/info").GetValueAsync();
Debug.Log(users.ChildrenCount); // returns "1", (it should be "3")
Debug.Log(users.Child("last").Exists);// returns true
Debug.Log(users.Child("name").Exists);//return false
foreach (DataSnapshot fss in users.Children)
{
    Debug.Log(fss.Key); //itirates only one time, returns "last"
}
```

It looks like your mixing continuations with async/await a little bit. Don't worry, this can be complicated! I wrote up a [quick blog post](https://firebase.googleblog.com/2019/07/firebase-and-tasks-how-to-deal-with.html) and [video](https://youtu.be/5GzFDXvZxKM) about this.

Next, if that works, you should try to massage your code to look a little more like:
```
private DatabaseReference _infoNode;

void Start() {
    _infoNode = FirebaseDatabase.DefaultInstance.GetReference("users/" + nameID + "/info");
    _infoNode.ValueChanged += HandleUserInfoChanged;
}

void OnDestroy() {
    _infoNode.ValueChanged -= HandleUserInfoChanged;
}

private void HandleUserInfoChanged(object sender, ValueChangedEventArgs args) {
    var DataSnapshot = e.Snapshot;
    // do stuff here, make sure you handle the null case!
}
```

What's happening here is that `.GetValueAsync()` basically registers a `ValueChanged` listener then immediately unregisters it. There's an [awesome breakdown here](https://stackoverflow.com/questions/34486417/firebase-offline-capabilities-and-addlistenerforsinglevalueevent/34487195#34487195) that covers all the nitty gritty details.

Finally, if none of that helps, if you can [reproduce this in our quickstart](https://github.com/firebase/quickstart-unity/tree/master/database/testapp) it will help us get to the bottom of the issue!
