### ISSUE TITLE
ERROR: Unable to find dependency com.google.firebase firebase-analytics-impl

### ISSUE THREAD

**Issue by JinHyuckKim** [firebase/quickstart-unity#83]
Hello.
I am a Korean person and I am mistaken in English. Thank you for your patience.

I'm trying to do firebase analytics on unity, android.

used project
quickstart-unity-master

used unity package
firebase_unity_sdk/FirebaseAnalytics.unitypackage

and I imported "google-services.json" to unity.

I try android build and run, but app clash.

I read this issue. (https://github.com/firebase/quickstart-unity/issues/53)

I tried

 "Assets --> Play Services Resolver--> Android --> Settings open, and Then check Enable Background Resolution"

and

"Assets --> Play Services Resolver--> Android --> Resolve Client Jars" menu option

Then displayed message "Android jar Dependencies. Resolution Complete".

However, an error is displayed in the console window.

This message.

```
ERROR: Unable to find dependency com.google.firebase firebase-analytics-impl [10.2.6] in ($SDK/extras/android/m2repository, $SDK/extras/google/m2repository, $SDK/extras/android/m2repository, $SDK/extras/google/m2repository)
UnityEngine.Debug:Log(Object)
Google.JarResolver.PlayServicesSupport:Log(String, Boolean)
Google.JarResolver.PlayServicesSupport:FindCandidate(Dependency)
Google.JarResolver.PlayServicesSupport:GetDependencies(Dependency)
Google.JarResolver.PlayServicesSupport:ResolveDependencies(Boolean, String)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:MenuResolve()
```

```
Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.firebase:firebase-analytics-impl:[10.2.6]
  at Google.JarResolver.PlayServicesSupport.GetDependencies (Google.JarResolver.Dependency dep) [0x00000] in <filename unknown>:0 
  at Google.JarResolver.PlayServicesSupport.ResolveDependencies (Boolean useLatest, System.String destDirectory) [0x00000] in <filename unknown>:0 
  at GooglePlayServices.ResolverVer1_1.DoResolutionNoAndroidPackageChecks (Google.JarResolver.PlayServicesSupport svcSupport, System.String destinationDirectory, Google.JarResolver.OverwriteConfirmation handleOverwriteConfirmation) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogError(Object)
GooglePlayServices.ResolverVer1_1:DoResolutionNoAndroidPackageChecks(PlayServicesSupport, String, OverwriteConfirmation)
GooglePlayServices.<DoResolution>c__AnonStorey1:<>m__0()
GooglePlayServices.ResolverVer1_1:DoResolution(PlayServicesSupport, String, OverwriteConfirmation, Action)
GooglePlayServices.PlayServicesResolver:Resolve(Action)
GooglePlayServices.PlayServicesResolver:MenuResolve()
```

Is there any missing step to do?
I am waiting for your help.

**Comment by JinHyuckKim** [comment]
<img width="369" alt="2017-05-19 12 55 07" src="https://cloud.githubusercontent.com/assets/10163220/26232615/66fe15d2-3c92-11e7-839b-3e386fc776a1.png">

**Comment by JinHyuckKim** [comment]
![2017-05-19 12 56 27](https://cloud.githubusercontent.com/assets/10163220/26232649/9964ac20-3c92-11e7-925d-06ca9a0b8e95.png)

**Comment by stewartmiles** [comment]
The local maven repository downloaded by the Android SDK manager should
include the last few releases of Google Play services and the Firebase
client libraries.  For example, after install
$ ls
~/dev/sdk/android-sdk-macosx/extras/google/m2repository/com/google/firebase/firebase-analytics
10.0.0                  10.2.6                  9.2.1
maven-metadata.xml
10.0.1                  9.0.0                   9.4.0
maven-metadata.xml.md5
10.2.0                  9.0.1                   9.6.0
maven-metadata.xml.sha1
10.2.1                  9.0.2                   9.6.1
10.2.4                  9.2.0                   9.8.0

If they're not present we have a tool that runs the Android SDK manager
from Unity to download the packages, perhaps this is broken for you?

You could try cleaning out the local copies of the client libraries and
installing them again manually from the Android SDK manager:

rm -rf ${your_sdk_dir}/extras/*

Then, run the Android SDK manager manually:

​

**Comment by JinHyuckKim** [comment]
@stewartmiles 

Thank you for reply.

I deleted the existing SDK and tried again.

But it failed.

This is my sdk folders.
ls /Applications/eclipse_and/sdk/extras/google/m2repository/com/google/firebase/firebase-analytics

```
10.0.0                  10.2.1                  9.0.0                   9.2.0                   9.6.0                   maven-metadata.xml
10.0.1                  10.2.4                  9.0.1                   9.2.1                   9.6.1                   maven-metadata.xml.md5
10.2.0                  10.2.6                  9.0.2                   9.4.0                   9.8.0                   maven-metadata.xml.sha1
```

However, same error is displayed in the console window.

Are there any other items to check?
Please let me know.

**Comment by JinHyuckKim** [comment]
@stewartmiles 
I am very sorry.
I was using the old firebase SDK.
Thank you very much for taking the time to solve your problem.
Thank you.

**Comment by MarkWijnbergen** [comment]
Hi Stewart, 

I have the same issue as JinHyuckKim has. 
This is the error I get:
![image](https://user-images.githubusercontent.com/25037754/27383784-5bd9fb74-5684-11e7-8134-bb21da76b168.png)

&&

![image](https://user-images.githubusercontent.com/25037754/27383820-830309ca-5684-11e7-89ed-9e9f467ee685.png)

I've downloaded the firebase SDK via the following link:
https://firebase.google.com/download/unity

and the firebase SDK is added to the Android SDK:

![image](https://user-images.githubusercontent.com/25037754/27383930-e9bdb958-5684-11e7-99bf-d1837d341055.png)

Within Unity, the player Services Resolver settings are checked:

![image](https://user-images.githubusercontent.com/25037754/27384002-30dc2810-5685-11e7-9d28-94ae3cc70994.png)

and the resolution is completed:

![image](https://user-images.githubusercontent.com/25037754/27384027-47bd127e-5685-11e7-9aa8-ce4913c83b6c.png)


However, there are no AAR files in the plugin availabe:

![image](https://user-images.githubusercontent.com/25037754/27384084-7879162e-5685-11e7-8d48-e640310c2a3f.png)

Do you have any idea what I've done wrong?

Thanks in advance,

Mark

**Comment by a-maurice** [comment]
Hi Mark,

One thing stands out as odd to me in the pictures you provided (thanks for
those, btw).  The Play Services Resolver settings image seems really out of
date.  To confirm, opening it should be Play Services Resolver > Android
Resolver > Settings.  If you look in Assets/PlayServicesResolver/Editor/,
the latest versions are v1.2.29.0, so make sure that those are what you
have in that directory.  If those are out of date, they should be included
in all of the unityPackages from the Firebase SDK, so you can reimport
whichever one you are using, and make sure it is checked.

If that doesn't resolve things, mind looking in
m2repository/com/google/firebase/firebase-analytics-impl/, and see what
version you go up to?  I believe that latest release is 11.0.0, which you
should have and it should be trying to resolve with.  The Play Services
Resolver should be prompting you to update those if necessary, but if not
you can update them yourself.  To do that, under where the SDK is, run
either "android" or "sdkmanager", which will list out a bunch of packages.
Make sure that "Extras/Google Play services" is up to date.

Hopefully that helps, but please let me know if it doesn't.
-Anthony
