### ISSUE TITLE
Failed to read Firebase options from the app's resources. Either make sure google-services.json is included in your build or specify options explicitly.

### ISSUE THREAD

**Issue by swap-mpl** [firebase/quickstart-unity#832]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 19.2.21f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: .unitypackage__ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics(Auth, Database, etc.)
  * Other Firebase Components in use: No(Auth, Database, etc.)
  * Additional SDKs you are using: No(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android(iOS, Android, and/or desktop)
  * Scripting Runtime: Mono(Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
- Import Crashlytics unity SDK 6.16 in a test project.
- Update app package and add google-services.json under Assets/.
- Resolve native dependencies.
- Build apk.
- Install and run the apk and see the logs in AndroidStudio.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
I just setup a test app (com.fbcrash.testapp) in the firebase console to test Crashlytics plugin and imported the firebase crashlytics sdk in unity. Once i run the app and see the logs in android studio it says failed to read firebase options from the app's sources even though I have added the google-services.json to my project.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
void Start()
    {
        Firebase.FirebaseApp.LogLevel = LogLevel.Debug;

        // Initialize Firebase
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
        {
            var dependencyStatus = task.Result;
            if (dependencyStatus == Firebase.DependencyStatus.Available)
            {
                // Create and hold a reference to your FirebaseApp,
                // where app is a Firebase.FirebaseApp property of your application class.
                // Crashlytics will use the DefaultInstance, as well;
                // this ensures that Crashlytics is initialized.
                Firebase.FirebaseApp app = Firebase.FirebaseApp.DefaultInstance;

                // Set a flag here for indicating that your project is ready to use Firebase.
                isInitialised = true;
            }
            else
            {
                UnityEngine.Debug.LogError(System.String.Format(
                  "Could not resolve all Firebase dependencies: {0}", dependencyStatus));
                // Firebase Unity SDK is not safe to use here.
            }
        });
    }

**Comment by vimanyu** [comment]
Hi @swap-mpl,
Apologies for the late response. I just tried our Crashlytics unity quickstart app and couldn't reproduce this on my end with either 6.15.2 or 6.16.1

Here are my steps,
1. Launch `quickstart-unity/crashlytics/testapp` with Unity 2019
2. Install 6.16.1 Crashlytics via Assets -> Import Package -> Custom Package 
3. Copy `google-services.json` from your firebase test project to the `Assets` folder
4. Set scene to MainScene under Assets/Firebase/Samples/Crashlytics
5. Hit "Play" in Editor - it should work and show a menu with buttons
6. Test with Build and run Android app also worked for me.

Could you verify if the same steps on this quickstart work for you?
