### ISSUE TITLE
Unable to find command line tool python required for Firebase Android resource generation on ubuntu20

### ISSUE THREAD

**Issue by mughis369** [firebase/quickstart-unity#835]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.12f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Auth
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Linux (Ubuntu 20.04.1 LTS focal)
  * Platform you are targeting: Android
  * Scripting Runtime: First I tried Mono and then IL2CPP none of them seems to be working

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
1-Create a new project
2-Import firebase packages
3-above two steps are enough to reproduce the error even if google-services.json is present in Assets folder 
#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts?
Yes
What's the issue repro rate? (eg 100%)

What happened? How can we make the problem occur?
Below is the error message I get
Unable to find command line tool python required for Firebase Android resource generation.
python is required to generate the Firebase Android resource file google-services.xml from Assets/google-services.json. Without Firebase Android resources, your app will fail to initialize.
python was distributed with each Firebase Unity SDK plugin, was it deleted?

System.ComponentModel.Win32Exception (0x80004005): ApplicationName='python', CommandLine='"/home/mughis/Unity/CP-Cash_Riddle_Game-main/Assets/Firebase/Editor/generate_xml_from_google_services_json.py" -i "Assets/google-services.json" -l', CurrentDirectory='/home/mughis/Unity/CP-Cash_Riddle_Game-main', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at GooglePlayServices.CommandLine.RunViaShell (System.String toolPath, System.String arguments, System.String workingDirectory, System.Collections.Generic.Dictionary`2[TKey,TValue] envVars, GooglePlayServices.CommandLine+IOHandler ioHandler, System.Boolean useShellExecution, System.Boolean stdoutRedirectionInShellMode) [0x002dc] in <3c3527f58bf541c9a5e9efe18e257c11>:0 
  at GooglePlayServices.CommandLine.Run (System.String toolPath, System.String arguments, System.String workingDirectory, System.Collections.Generic.Dictionary`2[TKey,TValue] envVars, GooglePlayServices.CommandLine+IOHandler ioHandler) [0x00000] in <3c3527f58bf541c9a5e9efe18e257c11>:0 
  at Firebase.Editor.PythonExecutor.Run (System.Collections.Generic.IEnumerable`1[T] arguments, System.String workingDirectory, System.Collections.Generic.Dictionary`2[TKey,TValue] envVars, GooglePlayServices.CommandLine+IOHandler ioHandler) [0x0001c] in <685f3df879854c5fbc61809c34b3dfd0>:0 
  at Firebase.Editor.GenerateXmlFromGoogleServicesJson.RunResourceGenerator (System.Collections.Generic.IEnumerable`1[T] arguments, System.String inputPath, System.Boolean showCommandLine) [0x0002b] in <685f3df879854c5fbc61809c34b3dfd0>:0 
UnityEngine.Debug:LogError(Object)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator(IEnumerable`1, String, Boolean)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory()
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration()
Firebase.Editor.GenerateXmlFromGoogleServicesJson:<GenerateXmlFromGoogleServicesJson>m__0()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)

along with a warning

Null
UnityEngine.Debug:LogWarning(Object)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:LogWarningIfEnabled(String)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory()
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration()
Firebase.Editor.GenerateXmlFromGoogleServicesJson:<GenerateXmlFromGoogleServicesJson>m__0()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)

#### Relevant Code:
this does not seems like a code problem however I'm using the below code

```
using UnityEngine;
using UnityEngine.UI;
using Firebase.Auth;
using Firebase.Extensions;

public class AuthManager : MonoBehaviour
{
    public InputField phoneNo;
    public InputField code;
    public Text text;
    public GameObject panel;

    private string phoneId;
	private bool toggleLogs;


    Firebase.DependencyStatus dependencyStatus = Firebase.DependencyStatus.UnavailableOther;
	FirebaseAuth auth;
	FirebaseUser user;
	PhoneAuthProvider provider;

    void Start()
    {
		WriteLog("Start Called");
		toggleLogs = false;
        Firebase.FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task =>
		{
			dependencyStatus = task.Result;
			//if (dependencyStatus == Firebase.DependencyStatus.Available)
			{
				InitializeFirebase();
				WriteLog("Firebase initializing...");
			}
			//else
			{
				WriteLog("Could not resolve all Firebase dependencies: " + dependencyStatus + " ERR");
			}
		});
    }

    
    void InitializeFirebase()
	{
		auth = FirebaseAuth.DefaultInstance;
		auth.StateChanged += AuthStateChanged;
		//AuthStateChanged(this, null);
	}

	public void PhoneGetVerificationCode_Click()
	{
		//Debug.Log(auth);
		WriteLog("GET VERIFICATION CODE");
		provider = PhoneAuthProvider.GetInstance(auth);
		Debug.Log(provider);
		WriteLog("Verify Phone Number: " + phoneNo.text);
		provider.VerifyPhoneNumber(phoneNo.text, 60, null, //phoneAuthTimeoutMs = 60
		verificationCompleted: (credential) => {
			// Auto-sms-retrieval or instant validation has succeeded (Android only).
			// There is no need to input the verification code.
			// `credential` can be used instead of calling GetCredential().
			WriteLog("Auto-sms-retrieval or instant validation has succeeded (Android only).");

			OnVerifyCode(credential);
		},
		verificationFailed: (error) => {
			// The verification code was not sent.
			// `error` contains a human readable explanation of the problem.
			WriteLog("The verification code was not sent.");
			WriteLog(error.ToString());
		},
		codeSent: (id, token) => {
			// Verification code was successfully sent via SMS.
			// `id` contains the verification id that will need to passed in with
			// the code from the user when calling GetCredential().
			// `token` can be used if the user requests the code be sent again, to
			// tie the two requests together.
			WriteLog("Verification code was successfully sent via SMS.");
			WriteLog("Id: " + id);
			WriteLog("Token: " + token);
			phoneId = id;

		},
		codeAutoRetrievalTimeOut: (id) => {
			// Called when the auto-sms-retrieval has timed out, based on the given
			// timeout parameter.
			// `id` contains the verification id of the request that timed out.
			WriteLog("Auto-sms-retrieval has timed out");
			WriteLog("Id: " + id);

		});
	}

	public void PhoneVerifyCode_Click()
	{
		Credential credential = provider.GetCredential(phoneId, code.text);
		OnVerifyCode(credential);
	}

	private void OnVerifyCode(Credential credential)
	{
		WriteLog("VERIFY CODE");
		auth.SignInWithCredentialAsync(credential).ContinueWith(task => {
			if (task.IsFaulted)
			{
				WriteLog("SignInWithCredentialAsync encountered an error: " + task.Exception);
				return;
			}

			FirebaseUser newUser = task.Result;

			WriteLog(System.String.Format("User signed in successfully: {0} (ProviderID = {1})",
				newUser.PhoneNumber, newUser.ProviderId));
		});
	}

	void AuthStateChanged(object sender, System.EventArgs eventArgs)
	{
		WriteLog("Auth State Changed");
	}


    void WriteLog(string msg)
    {
        string temp = text.text;
        text.text += "\n" + msg;
    }

    public void OnSendCode()
    {
        PhoneGetVerificationCode_Click();
		string num = phoneNo.text;
    }

    public void OnVerfiyCode()
    {
        PhoneVerifyCode_Click();
		string otp = code.text;
    }

    public void OnSignout()
    {
        Debug.Log("Signout");
    }

    public void ToggleLogs()
    {
		if(toggleLogs)
		{
			panel.SetActive(true);
			text.gameObject.SetActive(false);
			toggleLogs = false;
		}
		else
		{
			panel.SetActive(false);
			text.gameObject.SetActive(true);
			toggleLogs = true;
		}
    }
}
```

**Comment by DellaBitta** [comment]
Hi @mughis369,

The Firebase Unity SDK leverages python as part of its build process and so it's required to be installed on your linux instance.  The build scripts specifically look for the `python` binary executable and we recommend that you install python 3.x instead of python 2.x.  You can do some searches on how to install python on linux via `apt`.

You can test if it's configured correctly by starting a new shell instance and running `python -version` from the command line.  For example:

```
  $ python --version
  Python 3.6.8 (or something)
```

I hope this helps!

**Comment by KibiH** [comment]
Hi @DellaBitta 
I have a project which I wanted to add Oculus integration to  - so I installed the Oculus Integration from the Asset Store. Having done so, I receive the errors

```
Unable to find command line tool python required for Firebase Android resource generation.
python is required to generate the Firebase Android resource file google-services.xml from Assets/GoogleService-Info.plist. Without Firebase Android resources, your app will fail to initialize.
python was distributed with each Firebase Unity SDK plugin, was it deleted?

```
I certainly haven't deleted anything (just installed Unity), and in a new shell instance I ran 

`python -- version`

and got

`Python 3.8.5`

Any ideas, what I might be doing wrong?

**Comment by DellaBitta** [comment]
Hi @KibiH,

Was python working before you added the Occulus Integration?  Also are you also on Linux?

**Comment by KibiH** [comment]
@DellaBitta 
Python was working fine before Oculus

I am on Ubuntu 20.04 LTS

**Comment by DellaBitta** [comment]
Hi @KibiH,

It seems that the Oculus package might clobber the path environment variable that the Firebase SDK depends upon.  Unfortunately it's hard to determine how and why this occurs. May I suggest:

  1. Asking the Oculus support group about why this problem might exist?
  1. Start with a clean project, install Oculus first and then install Firebase to determine if the path environment variable remains intact in this order?
