### ISSUE TITLE
Get error log on iOS with 6.16.1

### ISSUE THREAD

**Issue by xalbillos** [firebase/quickstart-unity#837]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.9f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Crashlytics, Messaging, Dynamic Links
  * Other Firebase Components in use: 
  * Additional SDKs you are using: Facebook, Swrve
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

On runtime, I get this on my iOS device (iPad). Wondering if that's a bad sign or a harmless error log ?
`[Error]
Attempting to complete future before FCM initialized.
UnityEngine.Debug:LogError(Object)
Firebase.Platform.FirebaseLogger:LogMessage(PlatformLogLevel, String)
Firebase.LogUtil:LogMessage(LogLevel, String)
Firebase.LogUtil:LogMessageFromCallback(LogLevel, String)
 `

#### Steps to reproduce:

I can see this error every time I boot the app.

What happened? How can we make the problem occur?
Just boot the app with 6.16.1 in.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by DellaBitta** [comment]
Hi @xalbillos,

That error occurs when an application receives a response from the Apple Push Notification service before the Firebase Messaging SDK has been fully initialized.   The SDK uses the Firebase Error Logger if the Apple response is a failure, and logs a Warning if the Apple response indicated a success.  If you're curious, [this code is open sourced in the CPP SDK for reference](https://github.com/firebase/firebase-cpp-sdk/blob/1d13237b37dcecdc3a48ccd882337e03d4ac5bf0/messaging/src/ios/messaging.mm#L336). It serves as the underlying implementation for the Unity SDK as well.

Does your application follow [the initialization flow from the quickstart example](https://github.com/firebase/quickstart-unity/blob/f997826d90f0a1b535880c3990ed94e619628217/messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs#L64)?  The start() method initializes Firebase App, and then it asynchronously calls the local method InitializeFirebase to configure the Messaging SDK.  Only then does it call RequestPermissionAsync.  If you're still getting those error messages with that flow then that would be helpful to know!

Thanks.
