### ISSUE TITLE
Postponing Cloud Messaging initialization

### ISSUE THREAD

**Issue by patdev88** [firebase/quickstart-unity#84]
My company explicitly requested me that iOS apps should not prompt the user with "**APP_NAME Would Like to Send You Notification**" during startup.
Is there a way to manually invoke the registration process?

**Comment by stewartmiles** [comment]
I believe we already support this use case.  We currently initialize Firebase Cloud Messaging (FCM) on iOS when you register a MessageReceived or TokenReceived handler.
https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-messaging#class_firebase_1_1_messaging_1_1_firebase_messaging_1aa23b4ab44c1727df94708c99639afc1d
https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-messaging#tokenreceived

If you postpone this registration we shouldn't initialize the API.  Please reopen if you still have issues.

Cheers,
Stewart
