### ISSUE TITLE
we want to get the user_pseudo_id (bigquery) in the client SDK

### ISSUE THREAD

**Issue by armnotstrong** [firebase/quickstart-unity#840]
We want to find a method to get the `user_pseudo_id` of bigquery table in the client-side.

**Comment by DellaBitta** [comment]
Hi @armnotstrong,

The Firebase Games SDK suite doesn't provide APIs access Google Cloud BigQuery.  If I'm understanding your request correctly then please investigate the [BigQuery SDKs from Google Cloud](https://cloud.google.com/sdk), or if that's not what you're looking for then please feel free to re-open this issue and @ me.

Thanks!
