### ISSUE TITLE
app crashed on start after installing ARCore extensions

### ISSUE THREAD

**Issue by gbo999** [firebase/quickstart-unity#841]
* Unity editor version: 2019.4.12
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: maybe messaging? (Auth, Database, etc.)
  * Other Firebase Components in use: auth,database,storage,functions,app, (Auth, Database, etc.)
  * Additional SDKs you are using: ARCore extensions (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: windows(Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

i was having the firebase working and all but after installing the ARCore extensions and using custom mainTemplate.gradle and launcherTemplate.gradle suddenly it stop working and the app crashing on start with following log cat:

Debug ActivityTaskManager Failed startActivity, result=-92, intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.Mycity.at38/com.google.firebase.MessagingUnityPlayerActivity }, caller=com.android.server.wm.ActivityTaskManagerService.startActivityAsUser:1717 com.android.server.wm.ActivityTaskManagerService.startActivityAsUser:1613

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

tried force resolve android with dependency manager

try updating firebase to the latest version

tried also to use this article:https://firebase.googleblog.com/2020/08/firebase-compatibility-with-unity-20201.html

What happened? How can we make the problem occur?

maybe try installing the ARCore extensions in addition to firebase and use custom mainTemplate.gradle and launcherTemplate.gradle

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```

**Comment by patm1987** [comment]
Hi @gbo999 ,

First, my workaround should no longer be needed with the 6.16 versions of the Firebase SDK. Feel free to ignore that now!

Judging from the logs, it looks like ARCore is conflicting with the custom activity used in Messaging. Can I have you do a bit of verification for me?

1) Build and run the [Messaging test app](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp). For the purposes of this test, you don't actually have to get messaging working, just make sure it builds and runs.
2) Add ARCore and build and run again.

It would help too if you reproduced this test with another test app that doesn't need a custom activity. [Database](https://github.com/firebase/quickstart-unity/tree/master/database/testapp) is a good one, and again you don't need to get the database working - I just want you to make sure that the app builds and runs!

Once you've validated that ARCore is _not_ working with just Messaging (and ideally _is_ working with some other plugin), I will have a good starting point to look at. It looks like an `AndroidManifest.xml` is still expecting a Messaging activity that doesn't exist. So the likely path forwards will be to figure out _which_ activity needs to be the launcher activity then follow the [flow for configuring a custom entry point](https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_a_custom_entry_point_activity).

--Patrick

**Comment by gbo999** [comment]
Nevermind, i started a new project, and I no longer have this problem. I think it didnt work because messing up the templates, if it will happen again i will open a new issue. Thanks
