### ISSUE TITLE
FCM: Disconnect FCM Service

### ISSUE THREAD

**Issue by LongLostPenPal** [firebase/quickstart-unity#847]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.2.21f
  * Firebase Unity SDK version: 6.10.0
  * Xcode: 11.5
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use:FirebaseAnalytics/FirebaseCrashlytics/FirebaseMessaging/FirebaseRemoteConfig
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
-> applicationDidEnterBackground()
2020-10-29 17:19:46.427961+0800 xxxxxxxFCM: Disconnect FCM service
2020-10-29 17:19:46.428506+0800 xxxxxxx FCM: Disconnect FCM service
-> applicationWillEnterForeground()
2020-10-29 17:19:47.476913+0800 xxxxxxx FCM: Connected to FCM
-> applicationDidBecomeActive()
```
I do all the step the doc tells. [Doc](https://firebase.google.com/docs/unity/setup?authuser=1) .
It works well on android,but not work on ios. I received the token, and push a test notifacition at firebase console,but can't receive message in background. When I back to the app, I Also cant receive the message.

**Comment by LongLostPenPal** [comment]
i dont konw why , but it worked when i re-install several times....   and when app enterbackground fcm still print Disconnect FCM service

**Comment by LongLostPenPal** [comment]
why i get this warning , and no callback in unity [Firebase.Messaging.FirebaseMessaging.MessageReceived]
`
-> applicationWillEnterForeground()
2020-10-30 15:29:56.701636+0800 xxxxx Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.
2020-10-30 15:29:56.720139+0800 xxxxx [] nw_read_request_report [C34] Receive failed with error "Software caused connection abort"
2020-10-30 15:29:56.720214+0800 xxxxx [] nw_read_request_report [C37] Receive failed with error "Software caused connection abort"
2020-10-30 15:29:56.720258+0800 xxxxx [] nw_read_request_report [C33] Receive failed with error "Software caused connection abort"
2020-10-30 15:29:56.720297+0800 xxxxx [] nw_read_request_report [C34] Receive failed with error "Software caused connection abort"
2020-10-30 15:29:56.720989+0800 xxxxx [] nw_read_request_report [C37] Receive failed with error "Software caused connection abort"
2020-10-30 15:29:56.722031+0800 xxxxx [] nw_read_request_report [C33] Receive failed with error "Software caused connection abort"
2020-10-30 15:29:57.020859+0800 xxxxx FCM: Connected to FCM
-> applicationDidBecomeActive()
`

**Comment by patm1987** [comment]
Hi @LongLostPenPal ,

This seems like an issue better suited to [Firebase Support](https://firebase.google.com/support). They'll have much better debugging tools to debug your backend configuration.

To keep helping you here, I will need to find some way to sync a local configuration to what you have. Would you be able to reproduce your issue in the [Messaging quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp)? By adding your own `GoogleService-Info.plist` and changing the bundle id to match your current app, you should be able to get it talking to your own Firebase instance.

Would you also be able to upgrade to the [latest Unity SDK](https://firebase.google.com/support/release-notes/unity) to see if that helps (6.16.1).
Share more of your logs (with the argument `-FIRDebugEnabled` [set in XCode](https://help.apple.com/xcode/mac/8.0/#/dev3ec8a1cb4)).
Verify that you have not disabled method swizzling (you would have to do this manually in your Info.plist).
Verify that you've [enabled push notifications and background modes](https://firebase.google.com/docs/cloud-messaging/unity/client#enable_push_notifications). This may reset on a clean build.
Confirm that you _are not_ using [Unity's notification system](https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.3/manual/index.html).

Let me know if you opt to go the Firebase Support route or if you have the information above.

Thanks! And apologies for not having a quick and easy answer for you!
--Patrick

**Comment by LongLostPenPal** [comment]
> Hi @LongLostPenPal ,
> 
> This seems like an issue better suited to [Firebase Support](https://firebase.google.com/support). They'll have much better debugging tools to debug your backend configuration.
> 
> To keep helping you here, I will need to find some way to sync a local configuration to what you have. Would you be able to reproduce your issue in the [Messaging quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp)? By adding your own `GoogleService-Info.plist` and changing the bundle id to match your current app, you should be able to get it talking to your own Firebase instance.
> 
> Would you also be able to upgrade to the [latest Unity SDK](https://firebase.google.com/support/release-notes/unity) to see if that helps (6.16.1).
> Share more of your logs (with the argument `-FIRDebugEnabled` [set in XCode](https://help.apple.com/xcode/mac/8.0/#/dev3ec8a1cb4)).
> Verify that you have not disabled method swizzling (you would have to do this manually in your Info.plist).
> Verify that you've [enabled push notifications and background modes](https://firebase.google.com/docs/cloud-messaging/unity/client#enable_push_notifications). This may reset on a clean build.
> Confirm that you _are not_ using [Unity's notification system](https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.3/manual/index.html).
> 
> Let me know if you opt to go the Firebase Support route or if you have the information above.
> 
> Thanks! And apologies for not having a quick and easy answer for you!
> --Patrick

Thanks for replying! 

> Would you be able to reproduce your issue in the Messaging quickstart?

I will try immediately when I have time

> Would you also be able to upgrade to the latest Unity SDK to see if that helps (6.16.1).

I upgrade to 6.16.1 and it got the same situation

> Share more of your logs (with the argument -FIRDebugEnabled set in XCode).

[FullLogs](https://github.com/LongLostPenPal/MyPackage/blob/master/FCM_Log.txt)

> Verify that you have not disabled method swizzling (you would have to do this manually in your Info.plist).

I test disabled/enabled method swizzling , Both get the same situation

> Verify that you've enabled push notifications and background modes. This may reset on a clean build.

there is no problem

> Confirm that you are not using Unity's notification system.

I'm using Unity's notification system.

Thanks!

**Comment by jrubiog611** [comment]
> Hi @LongLostPenPal ,
> 
> This seems like an issue better suited to [Firebase Support](https://firebase.google.com/support). They'll have much better debugging tools to debug your backend configuration.
> 
> To keep helping you here, I will need to find some way to sync a local configuration to what you have. Would you be able to reproduce your issue in the [Messaging quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp)? By adding your own `GoogleService-Info.plist` and changing the bundle id to match your current app, you should be able to get it talking to your own Firebase instance.
> 
> Would you also be able to upgrade to the [latest Unity SDK](https://firebase.google.com/support/release-notes/unity) to see if that helps (6.16.1).
> Share more of your logs (with the argument `-FIRDebugEnabled` [set in XCode](https://help.apple.com/xcode/mac/8.0/#/dev3ec8a1cb4)).
> Verify that you have not disabled method swizzling (you would have to do this manually in your Info.plist).
> Verify that you've [enabled push notifications and background modes](https://firebase.google.com/docs/cloud-messaging/unity/client#enable_push_notifications). This may reset on a clean build.
> Confirm that you _are not_ using [Unity's notification system](https://docs.unity3d.com/Packages/com.unity.mobile.notifications@1.3/manual/index.html).
> 
> Let me know if you opt to go the Firebase Support route or if you have the information above.
> 
> Thanks! And apologies for not having a quick and easy answer for you!
> --Patrick

Hi, if have a question

If i'm using both Unity's notification system and firebase FCM is possible that they are interfering between them?

**Comment by patm1987** [comment]
There has been [at least one other bug](https://github.com/firebase/quickstart-unity/issues/631) associated with the presence of the Mobile Notifications package. If you're able, it would be really useful to know if we can isolate your issue to this.

If you can try reproducing your issue in the [Quickstart](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp), and let us know if it _doesn't_ occur with the vanilla quickstart but _does_ after adding Mobile Notifications - that would go a good way towards getting to the bottom of the issue!
