### ISSUE TITLE
Unable to detect error after calling functions.https.onCall -task is never faulted/cancelled

### ISSUE THREAD

**Issue by fer-gamboa** [firebase/quickstart-unity#857]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.11f1 
  * Firebase Unity SDK version: 7.2.1.2
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Cloud Functions (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Firestore, Analytics, Dynamic Links(Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, AdMob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Window (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

I have been trying to call an `onCall` function from my Unity game, write some stuff into my Cloud Firestore, and back to Unity to detect if everything was okay or if there was an error. In order to proceed.

Things that work fine: calling the function, passing arguments, validating those arguments, writing into the database, returning successfuly value as a JSON string.

Things that **do not work**: detecting if there was an error or not in the `onCall` when I go back into the client side (i.e. Unity side).

The below is a simplified version of my Cloud Functions code. I am using Node.js 10, and writing in Javascript:

```
exports.tutorialCompleted = functions.https.onCall((data, context) => {

	return doSomething(data, context.auth.uid).then(newUData => {

             	...  //Create map  

         	return JSON.stringify(map);

       }).catch(err => {
         	console.log('Error', err);
		
		//I tried to return:
         	// (1) return err;
		// (2) return null;
		// (3) return Promise.reject("rejected");
      		return new functions.https.HttpsError('Error', 'error');
       });
});
```

The return `return JSON.stringify(map);` works fine, and I can access the values. The problem is on the error. I tried (1) returning the same error that I get on the catch, (2) returning a null value, (3) returning a rejected promise, (4) returning (or throwing!) an `HttpsError`. _None of these work!_ Unity **always** says that the task completed, that is _not_ cancelled and _not_ faulted.

_Note: I have tried to purposefully send my function to the catch block_. In those cases, (1-3) worked but were unrecognizable in my Unity side, and (4) simply exploded everything in the server side, and the game just froze waiting for a response that never came.

<br />

Now, my Unity code looks as follows:

```
internal static callFunction(string functionName, object data) {
        // Get the instance
        FirebaseFunctions ffunction = FirebaseFunctions.DefaultInstance;

        // Call the function
        Task<HttpsCallableResult> mytask = ffunction.GetHttpsCallable(functionName).CallAsync(data);

	mytask.ContinueWith((Task<HttpsCallableResult> task) => {
		
		// If the task was completed successfully
                if (task.IsCompleted) {
			Debug.LogError("Task Completed");
                }
		else if(task.IsFaulted) {
			Debug.LogError("Task Faulted");
		}
                else {
			Debug.LogError("Task Cancelled");
                }
            });
	}
}

```

 
Whatever happens, `task.IsFaulted` and `task.IsCanceled` will always say false, and the `task.IsCompleted` always says true. How should I detect the error in Unity. I don't want to make a workaround to send a custom JSON in case of error!

**Comment by patm1987** [comment]
Does it work as expected if you replace `return new functions.https.HttpsError` with `throw new functions.https.HttpsError` as documented [here](https://firebase.google.com/docs/functions/callable#handle_errors)?

**Comment by fer-gamboa** [comment]
> Does it work as expected if you replace `return new functions.https.HttpsError` with `throw new functions.https.HttpsError` as documented [here](https://firebase.google.com/docs/functions/callable#handle_errors)?

Hello @patm1987. As per my opening issue, on the point (4), I tried_"returning (or throwing!)_". So yeah, I've already tried what you suggest _and still doesn't work_. What happens is that Functions do not return anything to Unity, and Unity keeps waiting forever for a result that never arrives.

**Comment by chkuang-g** [comment]
Hi @fer-gamboa 

Just to confirm, does this issue happen on both Android and in Unity editor?

Also, if you deploy something like the following, does the Unity Task failed properly?
```
exports.httpErrorTest = functions.https.onRequest((request, response) => {
  // Send an http error with no body.
  response.status(400).send();
});
```

Thanks,
Shawn

**Comment by fer-gamboa** [comment]
Hello @chkuang-g. Thanks for replying, but as explained, I am using `onCall` and not `onRequest`. I cannot use `onRequest` either.

What I have found so far:

- If a task fails, Unity will _still recognise it_ as Completed **and** Failed, both at the same time. So you need to evaluate `IsFaulted` first, before the Completed.

- When throwing an HttpsError, I can only make it work if the first argument is either `failed-precondition` or `invalid-argument`. Changing that to any other custom string completely invalidates the exception, and it is thrown in the Firebase console, never reaching Unity. However, I have _not tested this much, but my initial attempts seem to point to this type of behaviour._

```
throw new functions.https.HttpsError('failed-precondition', 'Cannot complete the request');
```

**Comment by chkuang-g** [comment]
@fer-gamboa 

If you take a look of the description for `Task.IsComplete`, it stated: `true if the task has completed (that is, the task is in one of the three final states: RanToCompletion, Faulted, or Canceled); otherwise, false.`
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.iscompleted?view=net-5.0

That is, it is the right way to check `Task. IsFaulted` before `Task.IsComplete`.

Could you confirm if `Task. IsFaulted` is `false` in any of the following scenario?
- `return new functions.https.HttpsError('Error', 'error');`
- `throw new functions.https.HttpsError()` with error code listed [here](https://firebase.google.com/docs/reference/functions/providers_https_#functionserrorcode), except for "ok".

Thanks,
Shawn

**Comment by fer-gamboa** [comment]
I finally managed to try this. In particular, tried `aborted` and `not-found`.  In both cases I managed to catch it in Unity. 

The message can be read if you do: `task.Exception.InnerException.Message`. 

But to read the actual "code" (or text) that I wrote on the function, I needed to do:

```
// Cast the inner exception:
Firebase.Functions.FunctionsException fe = (Firebase.Functions.FunctionsException)t2.Exception.InnerException;

// Get the code
string code = fe.ErrorCode
```

In that case, when I sent `aborted` in CloudFunctions, I received `Aborted` in Unity. Notice the difference in capitalisation. I didn't manage to test more to see how the others (those with a - in between) are received in Unity.

**Comment by chkuang-g** [comment]
Yes, you are correct.

You can see how to find the error code from this sample.
https://github.com/firebase/quickstart-unity/blob/241b0e5f527fb0b2088709a16e747d080853ca89/functions/testapp/Assets/Firebase/Sample/Functions/TestCase.cs#L64

So seems like we get some conclusion here:
1. In cloud function, throw HttpsError instead of returning it
2. Check `Task.IsFaulted` before `Task.IsComplete`
3. Use `task.Exception.InnerException` to get the error code.

I'll close this issue.  Please open a new issue if you still have problem using Functions.

Shawn
