### ISSUE TITLE
Firebase Push Notifications issue

### ISSUE THREAD

**Issue by BigGiantHead** [firebase/quickstart-unity#867]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.13f
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Push Notifications
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP
### [REQUIRED] Please describe the issue here:

Recently I noticed that in a build of my app the Push Notifications don't work. We tested on 3 devices iPhone 11, which did not receive the notifications, iPhone XR which receives notifications, and iPhone 6s that doesn't receive notifications.
I checked the whole setup and everything looks fine on Firebase and our server app. Also all certificates and profiles look good and valid on AppStore.
The issue started happening out of the blue, we didn't change anything in the setup.

#### Steps to reproduce:

I am not sure how can you reproduce this problem. My phone simply doesn't receive notifications.

**Comment by BigGiantHead** [comment]
Same behaviour if I use the .unitypackage instead of Package Manager.

**Comment by cynthiajoan** [comment]
Hi @BigGiantHead, can you help verify two things?

First did you try with our [quickstart unity](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp) to see if it can repro on your device?

If that's reproducible, can you try with the [quickstart ios](https://github.com/firebase/quickstart-ios/tree/master/messaging) so we can narrow down if it's unity sdk issue or ios sdk issue.

Thanks!

**Comment by BigGiantHead** [comment]
@cynthiajoan I will try both, but I will need some time to put into this.
Firebase messaging worked perfectly fine before though.

**Comment by cynthiajoan** [comment]
Thanks @BigGiantHead, will wait for your update.
