### ISSUE TITLE
Firebase Crashlytics Console doesn't register non-fatal exceptions on Android device

### ISSUE THREAD

**Issue by MayisGM** [firebase/quickstart-unity#873]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.12f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Auth, Database, Storage, DynamicLinks, CloudMessaging, Analytics, Functions
  * Additional SDKs you are using: Facebook, Admob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

After building apk and installing on my android device I can see non-fatal error report in Firebase Console, but only in case if I have all these 3 flags enabled:
1. Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;
2. Crashlytics.IsCrashlyticsCollectionEnabled = true;
3. Debug.unityLogger.logEnabled = true;

If I set false 2. or 3. or comment 1. crashlytics reporting not working again.

I am building release apk with signed release keystore. Tried on Samsung Galaxy S8 device with Android 9 OS version.

Not sure is this a bug or it's by design so if application wasn't downloaded from Play Market it must work with only in case flags above are enabled.

**Comment by bilck** [comment]
@MayisGM I believe this issue is caused by this one: https://github.com/firebase/quickstart-unity/issues/798

As a sidenote, it's also not working for me.

**Comment by MayisGM** [comment]
> @MayisGM I believe this issue is caused by this one: #798
> 
> As a side note, it's also not working for me.

Hi thanks for response.

Do you also need to enable both of these to make it working?

Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;
Crashlytics.IsCrashlyticsCollectionEnabled = true;

**Comment by chkuang-g** [comment]
Hi folks,

I just built [Crashlytics quickstart](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp) with Firebase `6.16.1` on Unity 2020.1.6f1 for Android, click all the buttons on the app and those [non-fatal exceptions ](https://github.com/firebase/quickstart-unity/blob/master/crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandler.cs#L69) was shown on the console with no problem. And as you can see from the sample code, you do not need to turn any of those on at all.

Note that those event will only be sent to backend after you relaunch the app.  Also, you will need to remove that "Event Type = Crashes" filter on the console.

Could you try to build the quickstart with your Firebase console? 

Shawn

**Comment by MayisGM** [comment]
> Hi folks,
> 
> I just built [Crashlytics quickstart](https://github.com/firebase/quickstart-unity/tree/master/crashlytics/testapp) with Firebase `6.16.1` on Unity 2020.1.6f1 for Android, click all the buttons on the app and those [non-fatal exceptions ](https://github.com/firebase/quickstart-unity/blob/master/crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandler.cs#L69) was shown on the console with no problem. And as you can see from the sample code, you do not need to turn any of those on at all.
> 
> Note that those event will only be sent to backend after you relaunch the app. Also, you will need to remove that "Event Type = Crashes" filter on the console.
> 
> Could you try to build the quickstart with your Firebase console?
> 
> Shawn

Hi @chkuang-g,
Did you import crashlytics package directly or install using UPM?

**Comment by chkuang-g** [comment]
I imported through UPM.

**Comment by MayisGM** [comment]
> I installed through UPM.

@chkuang-g I made a build using quick-start sample project for Crashlytics and installed crashlytics sdk using UPM and it was working well. Also I tried to add other Firebase components in sample project. I added the same components I had in my main project. And everything worked as expected. So now I am trying to understand what is wrong in my project so Crashlytics doesn't behave as needed. 

I tried to compare two projects to understand what is the difference and I noticed one thing:
Sample project Assets/Plugins/Android folder contains many android libraries with prefix androidx.xxx.xx.xxx, but the main project doesn't.

Both projects has the same External Dependencies Resolver Plugin with the same configurations.

Question 1. Could this difference cause the problem?

My main project uses Api Compatiblity Level: .Net Standard 2.0 but Sample project uses .Net 4.x

Question 2. Could .Net Standard 2.0 level be problematic with Crashlytics SDK?

I saw FirebaseApp.androidlib and FirebaseCrashlytics.androidlib in both projects I tried to remove them and again did Force Resolve, but this time only FirebaseApp.androidlib appeared even after restarting Editor.

Question 3. Do I need to have both these files under Android/Plugins folder or only FirebaseApp.androidlib enough?

This really makes me crazy I spent 4-5 days on this issue, can't understand the reason why this is not working in my project.

**Comment by chkuang-g** [comment]
@MayisGM 

Regarding question 1, I assume you are using `Plugins/Android/mainTemplate.grade`. When you are using custom gradle template, EDM4U injects dependencies to that file instead of downloading them to `Plugins/Android/` since Unity will use Gradle to resolve the dependencies during build time. Are you using `mainTemplate.gradle` in your own project?  If so, could you try to use `mainTemplate.gradle` in the sample project as well?

Regarding question 2, I don't see how `.Net Standard 2.0 level` can cause the issue.  Are you able to reproduce the issue if you use `.Net Standard 2.0 level` in the sample project? Also, `FirebaseCrashlytics.androidlib` is only generated during build time.  If you be generated when you build the apk.

Regarding question 3, libraries under `Android/Plugins` is only necessary if you are NOT using `mainTemplate.gradle`. If those libraries are missing, you should see many error message in your log already.  And both `FirebaseApp.androidlib` and `FirebaseCrashlytics.androidlib` are required to make Crashlytics works.

Shawn
