### ISSUE TITLE
Task ':uploadCrashlyticsSymbolFileRelease' is not up-to-date because: Task has not declared any outputs despite executing actions

### ISSUE THREAD

**Issue by zhangjianshuai** [firebase/quickstart-unity#879]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: __unity mac 2017.4.31f1___
  * Firebase Unity SDK version: __firebase sdk for unity v6.16.1___
  * Source you installed the SDK: _unitypackage____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: ___ firebaseCrashlytics__ (Auth, Database, etc.)
  * Other Firebase Components in use: __Messing, Analyis___ (Auth, Database, etc.)
  * Additional SDKs you are using: __Admob Facebook___ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _mac____ (Mac, Windows, or Linux)
  * Platform you are targeting: _Android____ (iOS, Android, and/or desktop)
  * Scripting Runtime: __IL2cpp___ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

[#4314](https://github.com/invertase/react-native-firebase/issues/4314)

 i am also facing this issuse, used unity mac 2017.4.31f1, build with il2cpp and mainTemplate, firebase sdk for unity6.16.1;    
 cannot build success when using  (according https://firebase.google.com/docs/crashlytics/ndk-reports?authuser=0#java):
```

    classpath 'com.android.tools.build:gradle:4.1.1' //3.4.3
    classpath 'com.google.gms:google-services:4.3.4'
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'

` implementation 'com.google.firebase:firebase-crashlytics-ndk:17.2.2'`


signingConfigs {
        release {
......
	        // Add this extension
	          firebaseCrashlytics {
	              nativeSymbolUploadEnabled true
	          }
.....
        }
    }
```

, could you help me ,and the building errorlog : 

`
```
* Where:
Build file '/Users/jens/Documents/AMS/DevBranch/Client/Game/Temp/gradleOut/build.gradle' line: 187

* What went wrong:
A problem occurred evaluating root project 'gradleOut'.
> Could not find method firebaseCrashlytics() for arguments [build_4630dycsspsb9cr5ti5hn2v7z$_run_closure7$_closure23$_closure28$_closure29@37d602e6] on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.
```
`

or 

```
* What went wrong:

A problem occurred evaluating root project 'gradleOut'.
> Failed to apply plugin [id 'com.google.firebase.crashlytics']
   > Could not create plugin of type 'CrashlyticsPlugin'.
      > org/gradle/api/tasks/TaskProvider

```

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

`yes, can reproduce with firebase unity quickstarts, and 100%
`

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

`when setting upload symbol file , cannot build   android apk(il2cpp) successful  using firebase Crashlytics sdk for unity;
`
#### Relevant Code:

```
```
` implementation 'com.google.firebase:firebase-crashlytics-ndk:17.2.2'`

signingConfigs {
        release {
......
	        // Add this extension
	          firebaseCrashlytics {
	              nativeSymbolUploadEnabled true
	          }
.....
        }
    }
```
```

Waiting for your reply, thanking you;;;
Don't know how to correctly set upload symbol file using unity mainTemplate build il2cpp apk;

**Comment by zhangjianshuai** [comment]
https://github.com/firebase/quickstart-unity/issues/745

**Comment by zhangjianshuai** [comment]
> I found a few problems with this issue:
> 
> * I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
> * This issue does not seem to follow the issue template. Make sure you provide all the required information.

had updated

**Comment by zhangjianshuai** [comment]
`
> Configure project :FirebaseCrashlytics.androidlib
Evaluating project ':FirebaseCrashlytics.androidlib' using build file '/Users/jens/Desktop/testapp/Temp/gradleOut/FirebaseCrashlytics.androidlib/build.gradle'.
Creating configuration androidTestUtil
All projects evaluated.
Analytics other plugin to proto: Unknown plugin type com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin expected enum COM_GOOGLE_FIREBASE_CRASHLYTICS_BUILDTOOLS_GRADLE_CRASHLYTICSPLUGIN
Selected primary task 'uploadCrashlyticsSymbolFileRelease' from project :
Tasks to be executed: [task ':generateCrashlyticsSymbolFileRelease', task ':uploadCrashlyticsSymbolFileRelease']
Tasks that were excluded: []
:generateCrashlyticsSymbolFileRelease (Thread[Execution worker for ':',5,main]) started.

> Task :generateCrashlyticsSymbolFileRelease
Task :generateCrashlyticsSymbolFileRelease in gradleOut Starting
Caching disabled for task ':generateCrashlyticsSymbolFileRelease' because:
  Build cache is disabled
Task ':generateCrashlyticsSymbolFileRelease' is not up-to-date because:
  Task.upToDateWhen is false.
Task :generateCrashlyticsSymbolFileRelease in gradleOut Finished
:generateCrashlyticsSymbolFileRelease (Thread[Execution worker for ':',5,main]) completed. Took 0.003 secs.
:uploadCrashlyticsSymbolFileRelease (Thread[Execution worker for ':',5,main]) started.

> Task :uploadCrashlyticsSymbolFileRelease
Task :uploadCrashlyticsSymbolFileRelease in gradleOut Starting
Caching disabled for task ':uploadCrashlyticsSymbolFileRelease' because:
  Build cache is disabled
Task ':uploadCrashlyticsSymbolFileRelease' is not up-to-date because:
  **Task has not declared any outputs despite executing actions.**
Task :uploadCrashlyticsSymbolFileRelease in gradleOut Finished
:uploadCrashlyticsSymbolFileRelease (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.

BUILD SUCCESSFUL in 546ms
2 actionable tasks: 2 executed`

**Comment by zhangjianshuai** [comment]
and The official document  No matter how to switch the android, iOS, the Unity of the document, all show the iOS;;;;;;;

**Comment by chkuang-g** [comment]
Hi @zhangjianshuai 

Sorry for the delay.  When you are using Crashlytics Unity SDK, you actually do not need to add those lines described here, since Crashlytics Unity editor tools is doing all the required works already.
https://firebase.google.com/docs/crashlytics/ndk-reports?authuser=0#java

In fact, I think the issue is because you added `classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'` into `mainTemplate.gradle`.

Please try to remove those lines and see if the issue persists.  I personally built Crashlytics testapp for Android with `6.16.1` many times.  It should works without any manual editing to `mainTemplate.gradle`.

Shawn
