### ISSUE TITLE
How to Solve Phone Auth,verification failed:Invalid Token  Error 

### ISSUE THREAD

**Issue by CLOUDFIRE91** [firebase/quickstart-unity#881]
I am using Unity Firebase unity Sdk 6.16.1 and Unity latest quick master. 

I have enabled Phone Authorization in Firebase Console and added team id and .p8 file in Firebase Console. 

Actually when i run the  Auth project from Unity latest quick master. The SMS is sent to the desired no. 
But it asks for Captacha and then only it sent sms to the desired no. 

So i have enabled Push Notification,Backround Mode and Remote config options in Xcode to avoid Image capatcha..

After i enabled it  and  when i run it it says

Phone Auth, Verification failed: Invalid Token Firebase Error

So what i have to do.  I am using Xcode  12.01   Mac OS catalina  10.15.7

What i have to do get the Sms. I dont need capatcha in  my app. I have to bye pass them .  If i enabled pushnotification, backgroud mode.. then the  Sms is not sent. 

What i have to do..

**Comment by vimanyu** [comment]
Hi @CLOUDFIRE91,
This is a great question for the backend team and not something that is being caused in the Unity SDK. Please contact [Firebase Support](https://firebase.google.com/support) who will attempt to route the question to the backend team directly. Am closing this ticket here but please feel free to refer support to this ticket.

**Comment by CLOUDFIRE91** [comment]
Hi All 

I found a Solution. There is nothing in error in unity. I did not add .p8 file in firebase console. Once i added the error solved. 

Thanks vimanyu for your reply.
