### ISSUE TITLE
Duplicate classes, Editor Freeze, and depricated namespace in 7.0.0

### ISSUE THREAD

**Issue by TheFishInABowl** [firebase/quickstart-unity#886]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.15f1
  * Firebase Unity SDK version: 7.0.0
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: Auth, Database
  * Other Firebase Components in use: Auth, Database, Storage
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Using UPM I upgraded all FB components to 7.0.0.

[1] I got multiple duplicate class error on a build, all of them with different classes from 19.3 runtime.jar vs 19.5.1.

[1-Soulution] The fix for the duplicate classes was to delete the old com.google.firebase.firebase-database-19.3.0.arr from assets/plugins/android. as it seems, this was not removed when I upgraded. It seemed like all the other old .arr files got removed.

[2] Now the namespace of **Firebase.Unity.Editor** doesn't exist anymore, and with that disappearing, I cant use FirebaseApp.DefaultInstance.SetEditorDatabaseUrl().
What's the replacement for those in 7.0.0?
If I remove them the whole engine freezes when I try to play in the editor.

#### Steps to reproduce:

this has been a two-year-old project which has used the realtime database from since it was available for download.
I have upgraded multiple times using git, unity packages and lately UPM.
Sadly I don't remember the former versions, but I know I have used 6.15, 6.15.2 and 6.16 through UPM before 7.0.0. 

#### Relevant Code:

```
using Firebase.Unity.Editor
FirebaseApp.DefaultInstance.SetEditorDatabaseUrl("url").
```

**Comment by DellaBitta** [comment]
Hi @TheFishInABowl,

It sounds like there was an issue when the resolver ran.  Perhaps some files weren't removed during the upgrade but they still need to be re-resolved for the new version to work fully.

If you're still having an issue then my suggestion is to delete your Plugins directory (back it up first - can't be too safe!), 
and do a **Force Resolve** with the Android resolver.  **Assets->External Dependency Manager->Android Resolver->Force Resolve**.  If you continue to get an error then please enable **Verbose Logging** (**Assets->External Dependency Manager->Android Resolver->Settings->Verbose Logging**) and see if you can detect where the error occurred in the output there. If not then please feel free to post the verbose log here.

Regarding SetDatabaseUrl: that method had been deprecated and it was recently removed. Please set the Database URL via the L [FirebaseAppOptions](https://firebase.google.com/docs/reference/unity/class/firebase/app-options#class_firebase_1_1_app_options) when constructing the firebase app.

I hope this helps!
