### ISSUE TITLE
Firebase.Firestore.DocumentSnapshot.ToDictionary() Crash if documentSnapshot.Exists == false

### ISSUE THREAD

**Issue by paradizIscool** [firebase/quickstart-unity#887]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: UPM (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Firestore (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, RemoteConfig (Auth, Database, etc.)
  * Additional SDKs you are using: Google SignIn (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

documentSnapshot.ToDictionary() Crash if documentSnapshot.Exists == false

Documentation says

Returns | A Dictionary{String, Object} containing the document data or null if this is a nonexistent document.

Tested on 7.0.0, but it's totally broken (see other bugs).

#### Steps to reproduce:

Load a Document that does not exist

JNI DETECTED ERROR IN APPLICATION: can't call java.util.Set java.util.Map.keySet() on null object
...
CheckJNI::CallObjectMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+72)
/lib/arm64/libFirebaseCppApp-6_16_1.so (firebase::firestore::FieldValueInternal::map_value() const+160)
...

**Comment by wilhuff** [comment]
Thanks for the report! I've been able to reproduce this issue and am working on a fix.

**Comment by wilhuff** [comment]
I've submitted a fix for this issue that will go out with the next release.

**Comment by wilhuff** [comment]
FYI, we released 7.0.2 today to fix a critical issue (#900). To reduce the risk inherent in that release, this fix will wait for the next regular release.

**Comment by dconeybe** [comment]
The fix for this bug is included in today's Unity SDK 7.1.0 release.
