### ISSUE TITLE
FirebaseFirestore.LogLevel crash if no instance was created

### ISSUE THREAD

**Issue by paradizIscool** [firebase/quickstart-unity#888]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: UPM (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Firestore (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, RemoteConfig(Auth, Database, etc.)
  * Additional SDKs you are using: Google sign in (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)

#### get crash:
After FirebaseApp is ready, call:
FirebaseFirestore.setLoggingEnabled(true);

crash 

#00 pc 0000000000203360  /data/app/com.iscoolentertainment.snc-uASpMzKBwqBTylOAvW-FkA==/lib/arm64/libFirebaseCppApp-6_16_1.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+72) (BuildId: 53fcddeb61b159ccb0507acde42d344e)
E/CRASH:       #01 pc 0000000000225c64  /data/app/com.iscoolentertainment.snc-uASpMzKBwqBTylOAvW-FkA==/lib/arm64/libFirebaseCppApp-6_16_1.so (firebase::firestore::Firestore::set_log_level(firebase::LogLevel)+44) (BuildId: 53fcddeb61b159ccb0507acde42d344e)

#### workaround:
Have to create an Instance first

var db = FirebaseFirestore.DefaultInstance;
FirebaseFirestore.LogLevel = Debug.isDebugBuild ? LogLevel.Debug : LogLevel.Error;

do not crash

In firestore_android.cc, bool FirestoreInternal::Initialize(App* app) must before anything else, I suppose that it's called on the first Instance Creation. Did not test ios.

**Comment by wilhuff** [comment]
Thanks for the report and sorry for the difficulty. On Android the SDK, there's a bit of global initialization that's missing if you come in via a static method first. I'm working on a fix.

**Comment by wilhuff** [comment]
I've submitted a fix for this issue and it will go out with our next release.

**Comment by wilhuff** [comment]
FYI, we released 7.0.2 today to fix a critical issue (#900). To reduce the risk inherent in that release, this fix will wait for the next regular release.

**Comment by dconeybe** [comment]
The fix for this bug is included in today's Unity SDK 7.1.0 release.
