### ISSUE TITLE
Crashlytics not working when installed using Unity Package Manager

### ISSUE THREAD

**Issue by AntonPetrov83** [firebase/quickstart-unity#890]
CRASHLYTICS

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.2f1
  * Firebase Unity SDK version: 6.16.1
  * Source you installed the SDK: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Crashlytics (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook, devtodev (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

First I added Google scoped registry and then added analytics and crashlytics packages to the project using Unity Package Manager. Analytics got working but crashlytics does not work.

The suspicious things are in the log:
```
Disable module 'crashlytics' for 'Firebase.Crashlytics.FirebaseCrashlytics, Firebase.Crashlytics'
Disable module 'instance_id' for 'Firebase.InstanceId.FirebaseInstanceId, Firebase.InstanceId'
Disable module 'messaging' for 'Firebase.Messaging.FirebaseMessaging, Firebase.Messaging'

analytics app initializer Enabling
auth app initializer Disabling
crashlytics app initializer Disabling
database app initializer Disabling
dynamic_links app initializer Disabling
functions app initializer Disabling
instance_id app initializer Disabling
App initializer invites not found, failed to enable.
messaging app initializer Disabling
App initializer performance not found, failed to enable.
remote_config app initializer Disabling
storage app initializer Disabling
App initializer test_lab not found, failed to enable.
```

After checking that quickstart-unity sample works I removed all packages and reinstalled Firebase from the downloadable zip-archive. And it worked! And log changed to:

```
crashlytics app initializer Enabling
```

I would prefer to continue working with Unity Package Manager rather then update packages by hand from downloadable archive which is 1.7 Gb (!!!)

P.S. It looks like the official Firebase documentation was edited and currently do not mentions installing Firebase from scoped registry. Why is this so?

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

No because I installed packages from the downloadable SDK distribution.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Not yet.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

I cannot share the project.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by simontgs** [comment]
We're experiencing similar issues, unable to get crashlytics to kick in, stuck on the green waiting for event in the dashboard.
 We're on 2020.1.16, Firebase 6.16.1 and 7.0.1 exhibiting same behaviour

**Comment by DellaBitta** [comment]
Hi  @AntonPetrov83,

It appears not to be a Crashlytics issue specifically since a few other modules are also being disabled, according to the logs.   Could you check to see if the [package has been disabled in the package manager](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.7/manual/index.html#PackManDisable), or maybe it's been [disabled in the build.gradle](https://www.techyourchance.com/disable-firebase-crashlytics-in-android-debug-builds/) file?

Thanks!
