### ISSUE TITLE
iOS App using "IMPL_APP_CONTROLLER_SUBCLASS" will not launch.

### ISSUE THREAD

**Issue by lbllm** [firebase/quickstart-unity#894]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.1f1
  * Firebase Unity SDK version: firebase_unity_sdk_7.0.0
  * Source you installed the SDK: FirebaseAnalytics.unitypackage FirebaseMessaging.unitypackage
  * Platform you are targeting: iOS

### [REQUIRED] Please describe the issue here:

(Thread 1 Queue : com.apple.main-thread (serial)
#0 0x00000001a2559694 in <redacted> ()
#1 0x00000001a2559644 in <redacted> ()
#2 0x00000001a256a9ac in <redacted> ()
#3 0x0000000193b01e1c in __CFStrAllocateMutableContents ()
#4 0x0000000193b01648 in __CFStringChangeSizeMultiple ()
#5 0x0000000193afc098 in __CFStringAppendBytes ()
#6 0x0000000193aec780 in __CFStringAppendFormatCore ()
#7 0x0000000193aee154 in _CFStringCreateWithFormatAndArgumentsReturningMetadata ()
#8 0x00000001a915283c in _os_log_impl_dynamic ()
#9 0x00000001a9152d94 in _os_log_with_args_impl ()
#10 0x0000000193b2dbb8 in _CFLogvEx3 ()
#11 0x0000000194e04050 in <redacted> ()
#12 0x00000001042e95b0 in firebase::LogMessageV(firebase::LogLevel, char const*, char*) ()
#13 0x00000001042e9344 in firebase::InternalLogMessage(firebase::LogLevel, char const*, ...) ()
#14 0x00000001042e9010 in firebase::DefaultLogCallback(firebase::LogLevel, char const*, void*) ()
#15 0x00000001042e90c4 in firebase::LogMessageWithCallbackV(firebase::LogLevel, char const*,
char*) ()
#16 0x00000001042e9194 in firebase::LogInfo(char const*, ...) ()
#17 0x0000000104286328 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#18 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#19 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#20 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#21 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#22 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#23 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#24 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#25 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#26 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#27 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#28 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#29 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#30 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#31 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#32 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#33 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#34 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#35 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#36 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20
#37 0x0000000104286410 in
firebase::messaging::AppDelegateApplicationDidFinishLaunchingWithOptions(objc_object*,
objc_selector*, UIApplication*, NSDictionary*) ()
#38 0x000000010327ed6c in -[CustomAppController application:didFinishLaunchingWithOptions:]
at /Users/brandon/Documents/git/u3d_texas/project_texas_19_4/xcode/Libraries/Plugins/iOS/
CustomAppController.mm:20

#### Steps to reproduce:

must present

#### Relevant Code:

@interface CustomAppController : UnityAppController<UIApplicationDelegate>
@end
 
IMPL_APP_CONTROLLER_SUBCLASS (CustomAppController)

**Comment by simontgs** [comment]
In Firebase 7.0.0+ and on ios, there appears to be an issue with the tagging of GoogleService-Info.plist either due to xcode 12.2 or Unity 2020.1 - i haven't delved further, our app constantly crashes on boot saying it cannot find the GoogleService-Info.plist even though it is present in the xcode project. 
 The issue is the target Member has been tagged to 'unityframework' and not the Unity-iphone project. If i manually change this, it all works fine. I am trying to look into how to change this in our postprocessor step and override in the project file.

**Comment by patm1987** [comment]
Would y'all mind confirming that you still have the issue on the 7.0.1 SDK? There were some patches that may address this here.

Thanks!
--Patrick
