### ISSUE TITLE
Not being able to declare "using.Firebase.Unity.Editor" in unity

### ISSUE THREAD

**Issue by Nicokkam** [firebase/quickstart-unity#896]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____2020.1.0f1
  * Firebase Unity SDK version: _____Latest
  * Source you installed the SDK: _____ .unitypackage
  * Problematic Firebase Component: _____ Database
  * Other Firebase Components in use: _____ Auth, Database and Analytics
  * Additional SDKs you are using: _____ None
  * Platform you are using the Unity editor on: _____ Mac
  * Platform you are targeting: _____ iOS, Android
  * Scripting Runtime: _____ IL2CPP

### [REQUIRED] Please describe the issue here:

I was following your tutorial and could not procede, given that I am unable to declare "using Firebase.Unity.Editor".

When I do, the autocomplete turn into this:

![image](https://user-images.githubusercontent.com/48728550/102094984-ba837980-3e01-11eb-89e5-825405852906.png)

And when I force it to say "using Firebase.Unity.Editor", it prompts me the error of:

![image](https://user-images.githubusercontent.com/48728550/102098324-d12bcf80-3e05-11eb-8c63-6b7c417fc036.png)

#### Steps to reproduce:

Don't know if can be reproduced.

**Comment by patm1987** [comment]
Hi @Nicokkam ,

Can I ask what you're trying to use from that namespace? Everything [should be removed to my knowledge](https://firebase.google.com/support/release-notes/unity#version_700_-_december_2_2020), so the documentation needs to get updated.

--Patrick

**Comment by Nicokkam** [comment]
Hello Patrick,

I was just following the documentation in order to implement the Firebase Database extension and it got me confused. The images of that tutorial contain "using.Firebase.Unity.Editor". 

I priorized other implementations for the time being. If I have any doubts when I return to this subject, I will reopen the issue. 

Thanks!
