### ISSUE TITLE
DynamicLinks.GetShortLinkAsync crashes on Android

### ISSUE THREAD

**Issue by robotoKK** [firebase/quickstart-unity#897]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.11f1
  * Firebase Unity SDK version: 6.16.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: DynamicLinks
  * Other Firebase Components in use: Analytics, App, Auth, Crashlytics, Database, Functions
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac, Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

We are using DynamicLinks to generate an invite link. There is no issue generating a long link and sending+receiving it on Android or iOS. However, it immediately crashes after receiving the response for GetShortLinkAsync on Android (iOS is fine).

There is an error just after the GetShortLinkAsync response:
`indirect_reference_table.cc:60] JNI ERROR (app bug): accessed stale Local 0x21  (index 2 in a table of size 0)`
which looks like a GC issue (https://stackoverflow.com/questions/14765776/jni-error-app-bug-accessed-stale-local-reference-0xbc00021-index-8-in-a-tabl). We're targeting api level 30, minimum api level 21, if that's relevant.

Full crash log [dynamiclinks-crash.log](https://github.com/firebase/quickstart-unity/files/5697925/dynamiclinks-crash.log)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?  Have not tried yet
What's the issue repro rate? 100%

What happened? How can we make the problem occur?
Run GetShortLinkAsync on Android. I used a Pixel 3.

Note: this issue sounds similar to #429 in title, however we have not enabled stripping or Proguard.

#### Relevant Code:

Our code is pretty similar to the Unity example (https://firebase.google.com/docs/dynamic-links/unity/create):

```
public void GetShortLinkAsync(Action<string> callback)
{
    string deeplink = "some deeplink";
    string dynamicLinkPrefix = "prefix setup on Firebase console";

    // generate long link (works)
    DynamicLinkComponents components = new DynamicLinkComponents(
        new System.Uri(deeplink),
        dynamicLinkPrefix)
    {
        IOSParameters = new IOSParameters("our ios package"),
        AndroidParameters = new AndroidParameters("our android package"),
    };

    Debug.LogWarning("GetShortLinkAsync longlink " + components.LongDynamicLink.ToString());

    // generate short link
    var options = new DynamicLinkOptions
    {
        PathLength = DynamicLinkPathLength.Default
    };

    DynamicLinks.GetShortLinkAsync(components, options).ContinueWith(task => {
        // if the short link failed, just use the deeplink as is
        if (task.IsCanceled)
        {
            Debug.LogError("GetShortLinkAsync was canceled.");
            callback?.Invoke(deeplink);
            return;
        }
        if (task.IsFaulted)
        {
            Debug.LogError("GetShortLinkAsync encountered an error: " + task.Exception);
            callback?.Invoke(deeplink);
            return;
        }

        // Short Link has been created.
        ShortDynamicLink link = task.Result;
        var warnings = new List<string>(link.Warnings);
        string warningsString = "";
        foreach (var warning in warnings)
            warningsString += "\n" + warning;
        Debug.LogWarning("GetShortLinkAsync Generated short link "+ link.Url+", warnings "+warnings.Count+warningsString);
        callback?.Invoke(link.Url.ToString());

        // CRASH on Android
    });
}

```

**Comment by patm1987** [comment]
Hi @robotoKK ,

Would you mind [updated to the latest version](https://firebase.google.com/support/release-notes/unity#version_701_-_december_8_2020) and validating that you're still running the issue. RemoteConfig's underlying Android implementation has gone through some significant refactors since the 6.x implementation, and just the version bump to 7.0.1 should hopefully put you in a better state.

--Patrick

**Comment by robotoKK** [comment]
@patm1987 thanks for the info! We can't upgrade to 7.0.1 just yet since Firebase is now built with XCode 11.7 as of 7.0.0. Our project depends on Unity Cloud Build for our release builds, and it only supports up to XCode 11.4.1. Unity said they will update this soon. I can try 7.0.1 locally though.

As a workaround until we can upgrade, we found that the DynamicLinks REST API works fine with UnityWebRequest on both Android and iOS (better even, since it works on Web and in Editor too), though the package manager version is still required to receive links.

**Comment by patm1987** [comment]
I get that. Perhaps if you could try [reproducing on the quickstart](https://github.com/firebase/quickstart-unity/tree/master/dynamic_links/testapp) (it should be fine to configure it with the same app id &c as your current app to make everything easier). If you see the crash on the Firebase SDK there (7.0.1), that would help a ton. If you _can't_ get it to work on 7.0.1 but it does occur on 6.16.0, it'd be useful to know and maybe there's a better workaround that could be tracked down.
