### ISSUE TITLE
Where do I find the gradle file?

### ISSUE THREAD

**Issue by chuakc92** [firebase/quickstart-unity#9]
I'm following the steps outlined here:

1: Click Add Firebase to your Android app and follow the setup steps. If you're importing an existing Google project, this may happen automatically and you can just download the config file.
2: When prompted, enter your app's package name. It's important to enter the package name your app is using; this can only be set when you add an app to your Firebase project.
3: Download a google-services.json file when instructed. You can redownload this file again at any time.
4: Copy this file to anywhere inside your project's assets folder.

After 4, the next step prompts me to add lines into gradle files, but I can't find anywhere to download the gradle package for Unity. Am I missing something here?

**Comment by stewartmiles** [comment]
Where is the documentation you're referring to?

Are the docs part of the Firebase Console (i.e http://console.firebase.google.com) or something else?

**Comment by chuakc92** [comment]
Here: https://firebase.google.com/docs/unity/setup

Under Add Firebase to Your app, it says to "Click Add Firebase to your Android app and follow the setup steps.". 

The last step of that includes linking the gradle files. How exactly do I do that for Unity? Or how does it read the Json file downloaded?

**Comment by stewartmiles** [comment]
Ah I see, yes we're aware we need to update the documentation in the
Firebase Console's add project steps to support other integrations e.g
Unity, C++ etc.  For the moment, after you've downloaded the .json / .plist
just go back to https://firebase.google.com/docs/unity/setup and continue
working through the setup steps.

e.g for Android

"
5. Add the google-services.json file to the project.

  *Drag the google-services.json downloaded from the Firebase console into
any folder in your project.*
"

Cheers,
Stewart

**Comment by chuakc92** [comment]
I've tried that, but even when FetchAsync() returned true, the values did not fetch correctly from the server. It still returned the default values. What might be the problem here? I've checked my bundle identifier and it's correct. 

Even the quickstart app I downloaded returned the default values.

**Comment by stewartmiles** [comment]
Did you call ActivateFetched() ?

https://github.com/firebase/quickstart-unity/blob/master/remote_config/testapp/Assets/TestApp/UIHandler.cs#L130

Fetch simply downloads data from the server.  ActivateFetched switches the
local config for the most recently fetched config values.

**Comment by chuakc92** [comment]
Yes, I did. Unfortunately, it still returns the default value. I'm doing this in the Unity editor, though. Do I have to build it on a device to work? 

Also, how exactly do I link my. json file? Do I only need to drag and drop it any where in my folder?

**Comment by stewartmiles** [comment]
The desktop implementations consist of stubs (i.e it's purely for testing and doesn't connect to our backends).
https://firebase.google.com/docs/unity/setup#stub_implementations_for_the_editor

You need to build and deploy on Android and iOS for our SDKs to work.
https://firebase.google.com/docs/unity/setup#overview

Regarding the crash, what logs do you see from the devices?

**Comment by stewartmiles** [comment]
Also, regarding the .json and .plist files you need to drag / drop them anywhere in your Unity project folder.  If you do not do this, check the Unity console - you'll see errors in the Unity console warning you that when the projects launch on device they'll fail to work.

**Comment by chuakc92** [comment]
I know how to look at logs within logcat, but what do I look for in this case? It crashes on every single device.

**Comment by stewartmiles** [comment]
The crash you're seeing is due to missing Android resources in your project.  You can verify Android resources are unpacked by looking for files matching under Assets/Plugins/Android/firebase-* .  If they're not present, select the "Assets -> Play Services Resolver -> Android Resolver -> Resolve Client Jars" from the Unity menu.

Check your Unity logs to see whether any errors are reported, if errors are present you'll need to resolve them before proceeding to build the application.

**Comment by chuakc92** [comment]
There are NO errors in Unity.

 "Assets -> Play Services Resolver -> Android Resolver -> Resolve Client Jars" from the Unity menu asks if I want to replace Google Play services 9.8.0 with 10.0.0, then throws this error:

Unable to find jar in the system path. This tool is required to process Play Services dependencies. Either set JAVA_HOME or add jar to the PATH variable to resolve this error.

**Comment by stewartmiles** [comment]
There's your error.  You need to setup your java environment and point the
JAVA_HOME environment variable at the Java directory.

**Comment by chuakc92** [comment]
I was able to build the app. The first fetch was successful. After I added the parameters to Firebase console and fetched data again, it says:
Fetch completed successfully!
Fetch failed for unknown reason

I checked and the bundle identifiers and the .json are correct. How do I resolve this issue?

**Comment by stewartmiles** [comment]
Could you share the complete log from the application?

**Comment by chuakc92** [comment]
Hi Stewart, I managed to fix the above errors.

I have another question. I'm trying to include Admob in my project. The Firebase documentation pointed me to this package: https://github.com/googleads/googleads-mobile-unity/releases/tag/3.1.2

I downloaded the package and imported it then built.

It built successfully onto my device, but my app crashes upon starting and throws the following error:

`11-29 15:07:46.231 1678-3326/? I/ActivityManager: Start proc 25811:com.testapp/u0a140 for activity com.testapp/com.unity3d.player.UnityPlayerActivity
11-29 15:07:46.256 1678-2748/? I/qti_sensors_hal: LIS3DH Accelerometer: batch  15.00    inf
11-29 15:07:46.295 25811-25811/? D/AndroidRuntime: Shutting down VM
11-29 15:07:46.296 25811-25811/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.testapp, PID: 25811
                                                   Theme: themes:{}
                                                   java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/app/com.testapp-1/base.apk)
                                                       at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5207)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4802)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4742)
                                                       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                       at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                       at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5471)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
11-29 15:07:46.297 1678-3339/? W/ActivityManager:   Force finishing activity com.testapp/com.unity3d.player.UnityPlayerActivity`


What is causing this?

**Comment by stewartmiles** [comment]
Looks like you're ending up with conflicting aars (Android packages) being included in the project.

Before you attempted to resolve the error - which I think made this worse - do you have the error logs reported by the plugins?  It's likely the Jar Resolver complained about conflicting aar versions, it would be great to see exactly what happened so that we can fix it.

**Comment by stewartmiles** [comment]
Closing out the issue here as it looks like you've cross posted to the AdMob tracker.
https://github.com/googleads/googleads-mobile-unity/issues/314

In future, please either close out duplicate threads / issues or reference the cross posts using a link as it saves everyone following along a lot of time searching for information or answering questions.
