### ISSUE TITLE
Error in auth TestApp

### ISSUE THREAD

**Issue by leehotae** [firebase/quickstart-unity#90]
![error](https://user-images.githubusercontent.com/21328168/27509065-16bead02-592f-11e7-8893-02e3d43fe5a7.PNG)

what is the problem?..

**Comment by stewartmiles** [comment]
Did you follow the setup instructions?
See https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/readme.md

**Comment by stewartmiles** [comment]
It looks like you didn't import the correct version of the SDK.  Download the latest version from https://firebase.google.com/docs/unity/setup .  The latest version is 4.0.3 (see https://firebase.google.com/support/release-notes/unity) you can verify the downloaded SDK version from the zip filename and the changelog in the readme.md.
