### ISSUE TITLE
StringIndexOutOfBoundsException on firestore API with unicode character

### ISSUE THREAD

**Issue by Thaina** [firebase/quickstart-unity#900]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2016.1
  * Firebase Unity SDK version: 7.0.1 (suspect since 7.0.0)
  * Source you installed the SDK: UPM
  * Problematic Firebase Component: FireStore
  * Other Firebase Components in use: Auth,Analytics,Crashlytics,DynamicLinks,Messaging
  * Additional SDKs you are using: Facebook, Admob, OneSignal
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

There are weird error in android when using firebase 7.0.1, which is not occur in 6.16.1 when there is unicode character in firestore document

#### Steps to reproduce:

- Making a firestore document with some unicode character, for example

![image](https://user-images.githubusercontent.com/1042507/102321972-f6107600-3fb0-11eb-973b-e53e5546f03e.png)

- Listening to collection query normally and just try to access field with unicode

- It then error like this

```
12-16 12:14:10.776 12841 12993 W System.err: java.lang.StringIndexOutOfBoundsException: offset=0 length=8 string.length()=4
12-16 12:14:10.776 12841 12993 W System.err: 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
12-16 12:14:10.776 12841 12993 W System.err: 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
12-16 12:14:10.776 12841 12993 W System.err: 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
12-16 12:14:10.776 12841 12993 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
12-16 12:14:10.776 12841 12993 W System.err: 	at android.os.Looper.loop(Looper.java:214)
12-16 12:14:10.776 12841 12993 W System.err: 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
```

- In this case it error from `"message" : "محمد"` but also happen to emoji too. Maybe any unicode would be the same problem

#### Relevant Code:

```C#
collection.Listen((messages) => {
	var messageTexts = messages.Documents.Select((doc) => {
		try
		{
			Debug.LogFormat("Message : {0}",doc.Id); // debug can still log this line
			if(doc.TryGetValue<string>("message",out var message)) // error around this line
				Debug.LogFormat("MessageType : {0}",message);
			return message;
		}
		catch(Exception e)
		{
			Debug.LogException(e);
			throw;
		}
	}).ToArray();

	// do something
});
```

**Comment by wilhuff** [comment]
Thanks for this report and I'm sorry for the trouble. I'm not yet sure what the cause of this issue is yet, but I've managed to reproduce the error you're seeing and will give updates as I have have them.

**Comment by Thaina** [comment]
@wilhuff I wish this would fix and release immediately. I couldn't just roll back to 6.16.1 because it will have dependency conflict in ios. While 7.0.1 let me build ios but will have this error in android

**Comment by wilhuff** [comment]
I've found the issue and submitted a fix for review. This was a regression introduced in 7.0.0.

I'll discuss our release options with the team tomorrow.

What's the dependency conflict issue with rolling back to 6.16.1? My understanding is that if you roll back the Unity SDK and the corresponding CocoaPods there should be no conflict.

**Comment by Thaina** [comment]
@wilhuff Sorry for not being clear, it just conflict dependency with admob that I was upgraded along with firebase 7.0

**Comment by Thaina** [comment]
@wilhuff How the fix is going? Could we have ETA about this?

**Comment by wilhuff** [comment]
The download package has been [released](https://firebase.google.com/support/release-notes/unity#version_702_-_december_21_2020). The Unity Package Manager release is in progress.
