### ISSUE TITLE
Undefined symbols when building Auth with Facebook

### ISSUE THREAD

**Issue by andymads** [firebase/quickstart-unity#908]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.16
  * Firebase Unity SDK version: 7.0.1
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: None
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Cannot build in Xcode due to this error

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GKLocalPlayer", referenced from:
      objc-class-ref in libFirebaseCppAuth.a(credential_ios_7e32949a14fe9694040ff5eed8d1b954.o)

#### Steps to reproduce:

Create new Unity project
Import Auth sdk 7.0.1
Import Facebook Unity sdk 8.1.1 (minus PlayServicesResolver folder)
Build in Unity
Open in Xcode and build

**Comment by abogarsukov-braingames** [comment]
The same happens for us when installing latest Firebase & Facebook SDKs using UPM.

Firebase SDK 7.0.2
Facebook SDK 8.1.1
Unity 2019.4.15

**Comment by andymads** [comment]
Yes, reverting to Firebase 6.16.1 worked for me too.

**Comment by andymads** [comment]
I've just also discovered that reverting to Facebook 8.1.0 fixes it.

**Comment by chkuang-g** [comment]
Hi @andymads 

If you upgrade to Facebook `8.1.1`, also be aware of this issue https://github.com/firebase/quickstart-unity/issues/862#issuecomment-758893827

I'll close this issue for now.
