### ISSUE TITLE
For some reason Realtime Database don't write data

### ISSUE THREAD

**Issue by jogranda** [firebase/quickstart-unity#909]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.16f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth, Analytics, Storage.
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android, IOS
  * Scripting Runtime: Mono and IL2CPP

### [REQUIRED] Please describe the issue here:

I have some database references for use in my project and all of them work fine. But there is one reference in particular that don't could save any data in its path or its children, I was testing before with another DatabaseReference with the same parent reference, and it works fine.

#### Steps to reproduce:

- Starts with creating a path reference to somewhere in the database.
- Save/write data as a transaction or with the method SetValueAsync() in the created path.
- Notice there isn't any data wrote in the database.

#### Relevant Code:

DatabaseReferenceRef.RunTransaction(mutableData =>
            {
                mutableData.Value = (Dictionary<string, string>) DataFormatted;
                return TransactionResult.Success(mutableData);
            });

or

DatabaseReferenceRef.SetValueAsync(DataFormatted);

**Comment by alexames** [comment]
Did the future complete successfully? Are there any write permissions on your database that might cause an issue? What was the path you were writing to, have you verified it's a legal path name?
