### ISSUE TITLE
Android: App crashed at startup [vdso].()

### ISSUE THREAD

**Issue by Winvz** [firebase/quickstart-unity#912]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity 2018.4.10f1
  * Problematic Firebase Component: auth:19.3.2,analytics:17.5.0,messaging:20.2.4,crashlytics:17.2.1(Auth, Database, etc.)
  * Additional SDKs you are using: admob:19.5.0, Facebook 5.15.3:19.5.0(Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP(Mono, and/or IL2CPP)
  * The firebase sdk source from Android not Unity, in our project

### [REQUIRED] Please describe the issue here:

       Caused by java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000001d3e3f
       Build fingerprint: 'samsung/c2qsqw/c2q:11/RP1A.200720.012/N986USQU1CTL2:user/release-keys'
       Revision: '10'
       pid: 29867, tid: 28308, name: UnityPreload  >>> com.myapp <<<
       x0   0000000000000000  x1   0000000000000000  x2   0000000000000003  x3   0000000000000055
       x4   0000000000000021  x5   0000000000000048  x6   0000007b54e41000  x7   000000000833d49c
       x8   00000000001d3a4f  x9   42d0376bc4410664  x10  0000000000000001  x11  0000000000000004
       x12  000000000000004e  x13  000000005fead669  x14  0000000000000000  x15  000017d33e3fd8f7
       x16  0000007833c4fa08  x17  0000007b4fb089ec  x18  00000078a4321f54  x19  0000007833ca0fc0
       x20  00000076fc960050  x21  000000000000007e  x22  0000007833ca1000  x23  0000007833ca1060
       x24  0000000000024e71  x25  0000000000000001  x26  00000077c46c9000  x27  0000000000000c3a
       x28  00000077c46c9000  x29  0000000000000c3b  x30  000000783334de54
       sp   00000077c46c83e0  pc   000000783334de90  pstate 0000000060001000

       at [vdso].()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libunity.()
       at libc._ZL15__pthread_startPv(_ZL15__pthread_startPv:64)
       at libc.__start_thread(__start_thread:64)

#### Steps to reproduce:

The majority (87%) of this problem occurs on Samsung phones(Galaxy S20,other), and the majority (74%) are Android11

**Comment by chkuang-g** [comment]
Hi @Winvz 

The versions in your post is Android SDK version, correct?
```
auth:19.3.2,analytics:17.5.0,messaging:20.2.4,crashlytics:17.2.1
```

First of all, do you know which Unity SDK version are you using? You should be able to find it under `Assets/Firebase/Editor`. See files like `FirebaseCrashlytics_version-7.0.2_manifest.txt`

Second, I did not see any Firebase related functions in your callstack.  What lead you to think it is an issue in Firebase SDK?

Let us know
Shawn

**Comment by Winvz** [comment]
我们是从Android接入的Firebase SDK，而不是Unity（unitypackage）

**Comment by Winvz** [comment]
![image](https://user-images.githubusercontent.com/48202519/105271181-07f9c000-5bd2-11eb-9fc4-8a88cff0d119.png)
I read about the Firebase SDK version in the Android project build.gradle. The call stack is in the Firebase Crash report. We want to know what problem caused this situation

**Comment by DellaBitta** [comment]
Hi @Winvz,

The engineers who monitor this repo are involved in C# code which wraps the iOS and Android SDKs for accessibility in Unity.  While we have some understanding of the underlying Android SDK, there's a different team which actually maintains that library.

If you're not invoking the Firebase Unity SDK but instead calling directly into the Android SDK itself then I recommend contacting [Firebase Support](https://firebase.google.com/support).  There's an option to open a support case at the bottom of the page and a support engineer can work with you and the Firebase Android SDK team.

I hope this helps and I'm going to close this issue for now. However,  please feel free to reopen this ticket if I misunderstood the situation. Thanks!
