### ISSUE TITLE
Could not find com.google.firebase:firebase-app-unity:7.0.2

### ISSUE THREAD

**Issue by AgrMayank** [firebase/quickstart-unity#926]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Database (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
Add and configure the Firebase Realtime database.
It works fine in unity editor.
Upon building it for Android, I get the error given below.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
It happens every time I try to build the project for android.
I tried using earlier firebase versions and the Unity 2020.1 versions, but that failed too.

What happened? How can we make the problem occur?
* What went wrong:
> Could not determine the dependencies of task ':unityLibrary:generateReleaseRFile'.
> Could not resolve all task dependencies for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not find com.google.firebase:firebase-analytics-unity:7.0.2.
     Required by:
         project :unityLibrary
   > Could not find com.google.firebase:firebase-app-unity:7.0.2.
     Required by:
         project :unityLibrary

#### Log File
[Editor.log](https://github.com/firebase/quickstart-unity/files/5794893/Editor.log)

**Comment by chkuang-g** [comment]
Hi @AgrMayank 

This looks like the `com.google.firebase:firebase-analytics-unity:7.0.2` and `com.google.firebase:firebase-app-unity:7.0.2` libraries were not resolved by EDM4U properly.

First of all, please try to click on `Assets > External Dependency Manager > Android Resolver > Force Resolve` menu item and see if this resolves your issue.

If not, please provide a bit more information
- Do you have `Assets/Plugins/Android/mainTemplate.gradle` in your project?
  - If so, did you see anything under `Assets/GeneratedLocalRepo/Firebase/m2repository/com/google/firebase/firebase-app-unity/7.0.2/`?
  - If not, can you find `com.google.firebase.firebase-app-unity-7.0.2.aar` under `Assets/Plugins/Android`?
- Could you provide verbose logging by enabling it in `Assets > External Dependency Manager > Android Resolver > Settings` menu item and run `Assets > External Dependency Manager > Android Resolver > Force Resolve` menu item again?

Thank you
Shawn

**Comment by AgrMayank** [comment]
Hi @chkuang-g

I tried Resolve and Force Resolve multiple times with getting "Resolution Succeeded all the time. But it didn't help.
- Yes, I have the mainTemplate.gradle file.
  - No, that folder isn't there. Attaching the image below for reference.
![Firebase-app folder missing](https://user-images.githubusercontent.com/26793209/104691006-78649500-572b-11eb-8af7-fdd0945abdc5.png)
  - It's not here either.

- [VerboseEditor.log](https://github.com/firebase/quickstart-unity/files/5819659/VerboseEditor.log)

**Comment by chkuang-g** [comment]
@AgrMayank 

Ah, ok.  There is definitely something odd going on here.

Could you check if the following files exists?
- `Assets/Firebase/Editor/AppDependencies.xml`.  Also, check if it has a section like the following:
  ```
    <androidPackage spec="com.google.firebase:firebase-app-unity:7.0.2">
      <repositories>
        <repository>Assets/Firebase/m2repository</repository>
      </repositories>
    </androidPackage>
  ```
- `Assets/Firebase/m2repository/com/google/firebase/firebase-app-unity/7.0.2/firebase-app-unity-7.0.2.srcaar` and `Assets/Firebase/m2repository/com/google/firebase/firebase-app-unity/7.0.2/firebase-app-unity-7.0.2.pom`

If you did not see any of them, please try to re-import `.unitypackage`(Auth, Database or Installation, any of them should work). Make sure you select every files.

I just try to install `7.0.2` and I am sure those files should be included in the `.unitypackage`.

Please let us know if this works for you.

**Comment by AgrMayank** [comment]
@chkuang-g 

Yeah, since even reimporting everything multiple times didn't work for me.

Nope, it doesn't exist there. And none of the files there contains those lines related to firebase-app.
![Firebase/Editor/](https://user-images.githubusercontent.com/26793209/105138888-89dae200-5b1b-11eb-9de9-d025e51435e6.png)

Again, not here. The firebase app folder itself is missing.
![Firebase/m2repository/com/google/firebase/](https://user-images.githubusercontent.com/26793209/105139123-dfaf8a00-5b1b-11eb-9c91-d1f442b35323.png)

I tried to import those multiple times over and over, and after the resolution, everything remains the same more or less. Moreover, everything works just fine in Unity Editor itself. 

Due to this issue, I was forced to use 3rd part REST API plugins for Firebase.

**Comment by chkuang-g** [comment]
@AgrMayank 

Yeah, Unity editor does not need those files. This is very odd.

When you import `.unitypackage`, say `dotnet4/FirebaseDatabase.unitypackage`, did you see those files in the list?
Something like this picture. (This is using `7.0.2`)
<img width="346" alt="Screen Shot 2021-01-20 at 4 08 00 PM" src="https://user-images.githubusercontent.com/31869252/105256174-0f6d8a80-5b3a-11eb-96dc-582cee0da094.png">

If you see those file in `unitypackage` but see nothing in your `Assets` folder after import, there is definitely weird happening from Unity side. In that case, perhaps try to remove all Firebase related files from `Assets` folder, which includes the following folders.
- `Editor Default Resources/Firebase`
- `ExternalDependencyManager`
- `Firebase`
- `Parse`
- `Plugins/iOS/Firebase`

**Comment by AgrMayank** [comment]
@chkuang-g 

I think this might be the whole reason since I don't see the app part in FirebaseDatabase import Assets/Firebase Folder. For some reason, it is under the Packages rather than the Assets folder.

![Import FirebaseDatabase.unitypackage](https://user-images.githubusercontent.com/26793209/105331836-eca2ab00-5bf9-11eb-8f51-d56b2ef4f95d.png)
![Import FirebaseDatabase.unitypackage](https://user-images.githubusercontent.com/26793209/105332189-5753e680-5bfa-11eb-8377-51b08f3473be.png)

**Comment by chkuang-g** [comment]
Ah, this is what I suspected.

Seems like you used Unity Package Manager to installed Firebase before. (or accidentally clicked on the migration button)
Anyway, there is a copy of App and EDM4U installed under `Package` folder.
Firebase currently does not support partial installation through `unitypackage` and partially through Unity Package Manager. Well, in fact, EDM4U would be quite confused when the project is in this state and cannot resolve Android dependency properly.

I would strongly recommend you to uninstall Firebase and EDM4U from all source first, including those in `Assets` folder as I mentioned, and those in Unity Package Manager. Then you need to pick a method, `unitypackage` or Unity Package Manger, to install Firebase SDK again.

Hope this helps!
Shawn

**Comment by AgrMayank** [comment]
@chkuang-g 

Actually, at first, I was using an older version of Firebase, so maybe on switching to a newer version the Package Manager contents got left out. Since those components were automatically installed via Package Manager for some reason.

I get it now and will try to implement the fix you mentioned.
Thanks!

**Comment by AgrMayank** [comment]
UPDATE: Finally got it to work after days of headache! Thanks 😊
