### ISSUE TITLE
FCM 7.0.x+ doesn't receive messages on iOS without `notification` object in playload

### ISSUE THREAD

**Issue by novavision** [firebase/quickstart-unity#927]
### [REQUIRED] Please fill in the following fields:

Unity editor version: 2020.1.17f1
Firebase Unity SDK version: 7.0.x+
Source you installed the SDK: Unity Package Manager
Problematic Firebase Component: FCM
Other Firebase Components in use: none
Additional SDKs you are using: none
Platform you are using the Unity editor on: Mac
Platform you are targeting: iOS
Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

7.0.0-7.0.2 Cloud Messaging SDK versions don't receive FCM message playload without `notification` object in json. when app is focused (in foreground).
Android version works well in this case (but there is another bug described here 

#### Steps to reproduce:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

> Yes

What's the issue repro rate? (eg 100%, 1/5 etc)

100% with quickstart project

> It's 100% reproducible on iOS build using quickstarts project

What happened? How can we make the problem occur?

1. setup FCM in Unity iOS project any version from 7.0.0 to 7.0.2
2. send FCM message playload without `notification` object while app in foreground
3. nothing received

**Comment by novavision** [comment]
Firebase 7.1.0 just released but seems this bug wasn't fixed in it... Any estimations? It's pretty important issue, we been expecting it at 7.1.0

**Comment by fliperamma** [comment]
Any news on this issue? 
We tested using a previous version of Firebase (`6.x`) and the notifications are coming through, but not on `7.1.0`, which is a major problem as we had to update Firebase in several apps for the iOS 14.5 releases. 
This will quickly start to impact a lot of companies, if it is not doing so already.

**Comment by LoveLindberg** [comment]
We have the same issue

**Comment by fliperamma** [comment]
Hello again 👋. 
Any known workaround regarding this issue @alexames @patm1987? 
Should we wait for a new release or would you recommend downgrading to `6.16.1` (the latest UPM version available that seems to work)? And if this is the case, would this version be iOS 14/IDFA changes compliant?

**Comment by antonliljeberg** [comment]
We have the same issue with 7.1. It's quite a blocker for us. Any news on when this will be fixed?
