### ISSUE TITLE
Storage auth in editor

### ISSUE THREAD

**Issue by paulhayes** [firebase/quickstart-unity#93]
Hi all,

I really appreciate the ability to have authenticated access to the Firebase database from within the Unity editor. It's great the documentation and the library has the Firebase.Unity.Editor extensions. 

However this feature doesn't seem to allow auth access to storage, so I keep having to temporarily turn off authentication rules, which will be potentially really dangerous after we release but are needing to continue development.

Is there any way around this, and if so, can you add it to the storage documentation for Unity?

All the best, and thanks for making such a fully features cloud solution library!

**Comment by stewartmiles** [comment]
We don't support auth in the editor at the moment I'm afraid.  We don't have a workaround for user authentication in the editor.

Cheers,
Stewart
