### ISSUE TITLE
Receive data message on ios when app is opened without asking apns token

### ISSUE THREAD

**Issue by paradizIscool** [firebase/quickstart-unity#94]
Hi,

We're using native firebase plugin to receive messages with unity, I wonder if it's now possible to request a fcm token without asking for an apns token.
This allows us to register te fcm token as soon as the app is launch, and eventually request for an apns token later. We can also send data messages to the user even if he refuses to give notification permissions.

**Comment by stewartmiles** [comment]
I'm still waiting on clarification from our FCM iOS guru but I'm pretty sure that if the user dismisses user notifications we'll still retrieve a FCM token which allows you to send silent messages to the application while it's in the foreground.

I'm not sure this satisfies your use case though as it sounds like you would prefer to defer requesting user notifications until later in the application.  Is that correct?

**Comment by paradizIscool** [comment]
Hi,

I'm not sure this satisfies your use case though as it sounds like you would prefer to defer requesting user notifications until later in the application. Is that correct?

Exactly

And yes I'm sure that if the user dismisses user notifications we'll still retrieve a FCM token.

**Comment by stewartmiles** [comment]
Unfortunately, at the moment in the C++ SDK (which resides under the C# layer) we do the following unconditionally when you assign either token or message event handlers

// iOS 7.1 and below
[[UIApplication sharedApplication] registerForRemoteNotificationTypes:allNotificationTypes];

// iOS 10 
[[UIApplication sharedApplication] registerUserNotificationSettings:settings];

We'll discuss how we can make this conditional in the API.

If you need a solution right now, you could:

- Temporarily swizzle out (i.e disable)  UIApplication:registerForRemoteNotificationTypes: and UIApplication:registerUserNotificationSettings: selectors on app startup in didFinishLaunchingWithOptions.
- Register your event handlers with the FCM C# API just enabling FCM without requesting user notifications.
- Later in your application have a method to restore the implementations of UIApplication:registerForRemoteNotificationTypes: and UIApplication:registerUserNotificationSettings: then register for user notifications.  You could call this method via PINVOKE from your C# code.

**Comment by stewartmiles** [comment]
We added support for this in 5.1.0 release of the Firebase Unity SDK
Release notes: https://firebase.google.com/support/release-notes/unity#5.1.0
Download: https://firebase.google.com/docs/unity/setup

Example here:
https://github.com/firebase/quickstart-unity/blob/a942c24ea665b4f69fabf2e7ec54496dd950b5ab/messaging/testapp/Assets/TestApp/UIHandler.cs#L65

Docs here:
https://firebase.google.com/docs/reference/unity/class/firebase/messaging/firebase-messaging#class_firebase_1_1_messaging_1_1_firebase_messaging_1a68dc94778094f82d2913ed3ddcd1892f
