### ISSUE TITLE
WhereNotIn and WhereNotEqualTo with OrderBy different field name causes Unity to crash or hang.

### ISSUE THREAD

**Issue by estellise-yukihime** [firebase/quickstart-unity#940]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.12f1, 2020.1.6f1
  * Firebase Unity SDK version: Version 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component:  Firestore
  * Other Firebase Components in use: Auth, Firestore
  * Additional SDKs you are using: NA
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android, iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
Calling "WhereNotIn", "WhereNotEqualTo" and appending "OrderBy" or "OrderByDescending" with different field name will cause Unity Editor to crash or hang.

#### Steps to reproduce:
1. Create a new Unity project
2. Import/Install Firebase version 7.0.2
3. Create a new firebase project
4. Create firestore database
5. Populate sample data
4. Import Firebase .json and .plist
5. Write Code
6. Run

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc): 100%

What happened? How can we make the problem occur?

[EditorLog.txt](https://github.com/firebase/quickstart-unity/files/5857075/EditorLog.txt)

#### Relevant Code:

```
var logRef = FirebaseFirestore
  .DefaultInstance
  .Collection("logs");

var gTask = await logRef
  .WhereNotIn("UserId",  new List<object> {"kfh0mDduNJKsdQWuUV0rsvEbMosGi1"})
  .OrderByDescending("UpdatedAt")
  .GetSnapshotAsync();
```

**Comment by estellise-yukihime** [comment]
Addtional:

Empty array inside "NotIn" also causes Unity Editor to hang or crash

[EditorLog.txt](https://github.com/firebase/quickstart-unity/files/5859873/EditorLog.txt)

```
var query = _firebaseCollectionInstance
                .WhereNotIn("UserId, new List<object>())
                .OrderByDescending("UserId")
                .OrderByDescending("UpdatedAt");
```

**Comment by wilhuff** [comment]
The editor log shows what the error is:

```
ERROR: Invalid argument: Invalid query. You have a where filter with an inequality (notEqual, lessThan, lessThanOrEqual, greaterThan, or greaterThanOrEqual) on field 'UserId' and so you must also use 'UserId' as your first queryOrderedBy field, but your first queryOrderedBy is currently on field 'UpdatedAt' instead.
```

This error was generated by the C++ core that underlies the Unity API and we're still working on getting C++ errors like these to translate into C# exceptions.
