### ISSUE TITLE
2020.2 2f1 not building for Android

### ISSUE THREAD

**Issue by SummerLynx** [firebase/quickstart-unity#944]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2 1f1, 2020.2 2f1
  * Firebase Unity SDK version: 7.0.2_
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Analytics
  * Other Firebase Components in use: Auth, Firestore, Storage
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Can not build for Android. When you install Firebase, your JDK link breaks. You are getting a JAVA_HOME error on build). If you try to fix that with: 
untoggle everying Android SDK, JDK and NDK related it in preferences, restart Unity, toggle It back
you get a message: do you want to activate Jetpack? AndroidX Jetttison needs target api to be 28 and forces the "Target Api level"
 to 28, which is not installed by default by Unity Hub, because they use 29. so you can't build with that. If you switch target back to (highest), it almost builds, but on "Building Gradle project" you get an error, described in issue #377. 

If you try to reimport firebase sdk, you get the cycle of "JDK" link breaking.
I managed to make it build once somehow, but the app crached on firebase app initialization

Buld Errors:

=================

Note: C:\Work\MatterFlowCommunity\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/armeabi-v7a/libFirebaseCppAnalytics.so'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

=================

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2020.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResValues
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseResources
> Task :unityLibrary:generateReleaseBuildConfig
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:generateReleaseResValues
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources
> Task :launcher:mainApkListPersistenceRelease
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :launcher:prepareLintJar
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseResources
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseBuildConfig
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseLibraryResources
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:prepareLintJarForPublish
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:parseReleaseLocalResources
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseShaders
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseShaders
> Task :unityLibrary:generateReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:packageReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseManifest
> Task :launcher:checkReleaseDuplicateClasses
> Task :unityLibrary:FirebaseApp.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResRelease
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseJniLibFolders
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateReleaseRFile
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:bundleLibResRelease
> Task :unityLibrary:mergeReleaseNativeLibs

> Task :launcher:processReleaseManifest
C:\Work\MatterFlowCommunity\Temp\gradleOut\launcher\src\main\AndroidManifest.xml:27:9-34:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:27 to replace other declarations but no other declaration present

> Task :unityLibrary:stripReleaseDebugSymbols
> Task :launcher:mergeReleaseShaders
> Task :launcher:compileReleaseShaders
> Task :launcher:generateReleaseAssets
> Task :unityLibrary:FirebaseApp.androidlib:compileReleaseJavaWithJavac
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileRelease
> Task :unityLibrary:FirebaseApp.androidlib:mergeReleaseNativeLibs
> Task :unityLibrary:FirebaseApp.androidlib:stripReleaseDebugSymbols
> Task :unityLibrary:FirebaseApp.androidlib:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeRelease
> Task :launcher:mergeReleaseAssets
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :launcher:mergeReleaseJniLibFolders
> Task :launcher:validateSigningRelease
> Task :unityLibrary:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:javaPreCompileRelease
> Task :unityLibrary:generateReleaseRFile
> Task :launcher:mergeReleaseResources

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :launcher:processReleaseResources
> Task :unityLibrary:bundleLibCompileRelease
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :launcher:mergeReleaseJavaResource
> Task :launcher:desugarReleaseFileDependencies
> Task :launcher:javaPreCompileRelease
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:compileReleaseSources
> Task :launcher:dexBuilderRelease
> Task :launcher:mergeReleaseNativeLibs FAILED
> Task :launcher:lintVitalRelease
> Task :launcher:mergeExtDexRelease
65 actionable tasks: 65 executed

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

==========================

#### Steps to reproduce:

1. Upgrade to Unity 2020.2 2f1 (i guess it has different target Android API setup then before? it now has "minimum" api level)
2. Try to build a project for android.
3. Observe build error.

What's the issue repro rate? 100%

**Comment by Almazikman** [comment]
I have the same problem, but with Firebase messaging. Unity version is the same.
Any idea how to fix it?

**Comment by patm1987** [comment]
So I just tried Analytics with 2020.2 f1 on MacOS Big Sur using the 7.0.2 SDK with the [Analytics Quickstart](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp) and didn't run into any issues.

Can you check something real fast in your setup, I'd like to see what Build looks like under "Publishing Settings" in player settings:
![image](https://user-images.githubusercontent.com/1111611/106528480-0c618b00-64a6-11eb-8c22-99c95bef0a4c.png)
Checking nothing works for me.

Similarly, I went from nothing checked to both "Custom Main Gradle Template" and "Custom Gradle Properties Template" checked with it working:
![image](https://user-images.githubusercontent.com/1111611/106529460-bb529680-64a7-11eb-883f-ca73f5baf377.png)

with the following caveats:
1) I had to restart Unity after changing this or I got a duplicate symbols error. As far as I can tell, this is because the Unity `Temp/` directory isn't properly cleaned up and restarting forces this to regenerate
2) I did have to uncheck "JDK Installed with Unity", but needing to toggle this has been kind of a long time issue. I did not have to restart Unity (I believe doing so would force you to toggle it again), and it pulled a JDK from Unity anyway (rather than one from my system)
![image](https://user-images.githubusercontent.com/1111611/106529390-9d853180-64a7-11eb-8ea8-ce0b4d69d4db.png)

So my ask would be 1) verify that it works (or doesn't) in the quickstart. 2) try the various permutations above to see if any of them resolve your issue.

This could also be a Windows specific issue or some other configuration, but this will help us start to isolate things.

**Comment by SummerLynx** [comment]
I can not understand, why your JDK path says 2019.4.1f1, where Unity defalut JDK would be at 2020.2 2f1 path. Do we have to have some special version of JDK, which was shipped with 2019.4. 1f1? 

Sorry, i don't have quickstart project and, sadly, i don't really have free time to set it up. Maybe @Almazikman can help. 
But here is what i can provide (unity version 2020. 2.f1): 

![image](https://user-images.githubusercontent.com/25877584/106558911-a6bcdf80-6535-11eb-82ac-1f22269588af.png)

Here is what i have. This is without "unchecing". I uncheck and hit build (surely, i have "no JDK" error) :

![image](https://user-images.githubusercontent.com/25877584/106559041-e1bf1300-6535-11eb-9e97-13d4ccd392a5.png)

Now i check again, and have the error:

![image](https://user-images.githubusercontent.com/25877584/106559868-1bdce480-6537-11eb-99af-78190c59f67d.png)

**Comment by patm1987** [comment]
There should be nothing special about any particular JDK, the field in there is just whatever Unity grabbed. I find that just the act of toggling that checkbox and letting systems in Unity handle it fixes build issues.

Another note is that EDM4U uses gradle to resolve dependencies if you don't enabled `mainTemplate.gradle` (with requires `JAVA_HOME`). Currently the JDK used in Unity is not passed to this process (see: https://github.com/googlesamples/unity-jar-resolver/issues/384#issuecomment-770273311 ).

So by adding the `mainTemplate.gradle` and `gradleTemplate.properties` files as I linked, you may force Unity build process to use one SDK for the entire build.

**Comment by SummerLynx** [comment]
Adding the mainTemplate.gradle and gradleTemplate.properties did help. 
Thank you very much, @patm1987 !
