### ISSUE TITLE
SetPriorityAsync- Error NoopPersistenceManager java.lang.AssertionError: hardAssert failed:  Error RunLoop Uncaught exception in Firebase Database runloop (19.4.0).

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#945]
Unity editor version: 2020.1.11f1
Firebase Unity SDK version: 6.16.1
Source you installed the SDK: .unitypackage
Problematic Firebase Component: RealTime database
Other Firebase Components in use: Auth, RealTime database, Storage, functions
Additional SDKs you are using: None
Platform you are using the Unity editor on: Windows
Platform you are targeting: Android
Scripting Runtime: IL2CPP
[REQUIRED] Please describe the issue here:
Android samsung crushes when trying to  FirebaseDatabase.DefaultInstance.RootReference.Child("users").Child(num).SetPriorityAsync(pir);
Never had issues with IOS, or in Unity editor, the app works fine there

I get this error:
`2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager Caught Throwable.
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager java.lang.AssertionError: hardAssert failed: 
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:293)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.view.ViewProcessor.applyServerOverwrite(ViewProcessor.java:319)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.view.ViewProcessor.applyOperation(ViewProcessor.java:90)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.view.View.applyOperation(View.java:173)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncPoint.applyOperationToView(SyncPoint.java:78)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncPoint.applyOperation(SyncPoint.java:109)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:925)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(SyncTree.java:887)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.access$400(SyncTree.java:76)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree$5.call(SyncTree.java:303)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree$5.call(SyncTree.java:299)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.SyncTree.applyServerOverwrite(SyncTree.java:298)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.core.Repo.onDataUpdate(Repo.java:342)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataPush(PersistentConnectionImpl.java:782)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataMessage(PersistentConnectionImpl.java:415)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.Connection.onDataMessage(Connection.java:164)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.Connection.onMessage(Connection.java:128)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:257)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:304)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021/01/31 15:14:06.812 23466 23582 Error NoopPersistenceManager 	at java.lang.Thread.run(Thread.java:764)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop Uncaught exception in Firebase Database runloop (19.4.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
2021/01/31 15:14:06.814 23466 23582 Error RunLoop java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: 
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:131)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyServerOverwrite(SyncTree.java:298)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.Repo.onDataUpdate(Repo.java:342)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataPush(PersistentConnectionImpl.java:782)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataMessage(PersistentConnectionImpl.java:415)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.Connection.onDataMessage(Connection.java:164)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.Connection.onMessage(Connection.java:128)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:257)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:304)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at java.lang.Thread.run(Thread.java:764)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop Caused by: java.lang.AssertionError: hardAssert failed: 
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:293)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.view.ViewProcessor.applyServerOverwrite(ViewProcessor.java:319)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.view.ViewProcessor.applyOperation(ViewProcessor.java:90)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.view.View.applyOperation(View.java:173)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncPoint.applyOperationToView(SyncPoint.java:78)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncPoint.applyOperation(SyncPoint.java:109)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:925)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(SyncTree.java:887)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree.access$400(SyncTree.java:76)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree$5.call(SyncTree.java:303)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.SyncTree$5.call(SyncTree.java:299)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
2021/01/31 15:14:06.814 23466 23582 Error RunLoop 	... 16 more
2021/01/31 15:14:06.816 23466 23466 Debug AndroidRuntime Shutting down VM
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of crash
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime FATAL EXCEPTION: main
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime Process: com.fff.fff PID: 23466
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (19.4.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:873)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:214)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7073)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime Caused by: java.lang.RuntimeException: java.lang.AssertionError: hardAssert failed: 
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:131)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyServerOverwrite(SyncTree.java:298)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.Repo.onDataUpdate(Repo.java:342)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataPush(PersistentConnectionImpl.java:782)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataMessage(PersistentConnectionImpl.java:415)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.Connection.onDataMessage(Connection.java:164)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.Connection.onMessage(Connection.java:128)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:257)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:304)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java:34)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:86)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at java.lang.Thread.run(Thread.java:764)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime Caused by: java.lang.AssertionError: hardAssert failed: 
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:234)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.utilities.Utilities.hardAssert(Utilities.java:229)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.snapshot.ChildrenNode.updateChild(ChildrenNode.java:293)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.view.ViewProcessor.applyServerOverwrite(ViewProcessor.java:319)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.view.ViewProcessor.applyOperation(ViewProcessor.java:90)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.view.View.applyOperation(View.java:173)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncPoint.applyOperationToView(SyncPoint.java:78)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncPoint.applyOperation(SyncPoint.java:109)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:925)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyOperationHelper(SyncTree.java:920)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.applyOperationToSyncPoints(SyncTree.java:887)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree.access$400(SyncTree.java:76)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree$5.call(SyncTree.java:303)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.SyncTree$5.call(SyncTree.java:299)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	at com.google.firebase.database.core.persistence.NoopPersistenceManager.runInTransaction(NoopPersistenceManager.java:126)
2021/01/31 15:14:06.818 23466 23466 Error AndroidRuntime 	... 16 more
`

And these are my dependencies:
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'com.google.ads.mediation:inmobi:9.1.0.0' // Assets/GoogleMobileAds/Editor/InMobiMediationDependencies.xml:7
    implementation 'com.google.ads.mediation:mopub:5.10.0.0' // Assets/GoogleMobileAds/Editor/MoPubMediationDependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads:19.3.0' // Assets/GoogleMobileAds/Editor/GoogleMobileAdsDependencies.xml:7
    implementation 'com.google.android.gms:play-services-base:17.4.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.firebase:firebase-analytics:17.5.0' // Assets/Firebase/Editor/StorageDependencies.xml:15
    implementation 'com.google.firebase:firebase-app-unity:6.16.1' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-auth:19.3.2' // Assets/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:6.16.1' // Assets/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:19.3.1' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-database:19.4.0' // Assets/Firebase/Editor/DatabaseDependencies.xml:13
    implementation 'com.google.firebase:firebase-database-unity:6.16.1' // Assets/Firebase/Editor/DatabaseDependencies.xml:20
    implementation 'com.google.firebase:firebase-functions:19.1.0' // Assets/Firebase/Editor/FunctionsDependencies.xml:13
    implementation 'com.google.firebase:firebase-functions-unity:6.16.1' // Assets/Firebase/Editor/FunctionsDependencies.xml:20
    implementation 'com.google.firebase:firebase-storage:19.2.0' // Assets/Firebase/Editor/StorageDependencies.xml:13
    implementation 'com.google.firebase:firebase-storage-unity:6.16.1' // Assets/Firebase/Editor/StorageDependencies.xml:20
// Android Resolver Dependencies End

**Comment by patm1987** [comment]
Hi @shlighter ,

Can you do a few tests for me:

- Can you test with the [latest Unity SDK](https://firebase.google.com/download/unity) ([currently 7.0.2](https://firebase.google.com/support/release-notes/unity)).
- If the issue persists, can you try to replicate this in the [Database Quickstart](https://github.com/firebase/quickstart-unity/tree/master/database/testapp) hosted in this repo and give us instructions about how to follow along?

6.x to 7.x had some pretty big changes under the hood, so this upgrade could be the culprit, otherwise this will give us a good starting point to replicate it on our end and see what's up.

**Comment by shlighter** [comment]
Hey Patrick,  I had other issues with 7.x that's why I don't upgrade, but I don't see any related notes to persistence data or real-time database in any case
But I can try one more time yes

**Comment by shlighter** [comment]
OK now that I could update to SDK 7.0.2 my app doesn't crash anymore. Thank you!
