### ISSUE TITLE
SDK 7.0.0 + errors-  The type or namespace name 'Editor' does not exist in the namespace 'Firebase.Unity'

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#947]
### [REQUIRED] Please fill in the following fields:

Unity editor version: 2020.1.11f1
Firebase Unity SDK version: 7.0.2  (any version after 6.16.1)
Source you installed the SDK: .unitypackage
Problematic Firebase Component: RealTime database
Other Firebase Components in use: Auth, RealTime database, Storage, functions
Additional SDKs you are using: None
Platform you are using the Unity editor on: Windows
Platform you are targeting: Android
Scripting Runtime: IL2CPP
[REQUIRED] Please describe the issue here:

I can't upgrade to the latest SDK or any SDK after 6.16.1 which is the last working one for me
I tried that multiple time and it's simply doesn't work any more
I get these errors-
error CS0234: The type or namespace name 'Editor' does not exist in the namespace 'Firebase.Unity' (are you missing an assembly reference?)
and it marks my code- "using Firebase.Unity.Editor;" with a red line.
Once I downgraded to 6.16.1 it's all fine.  Iv'e been waiting for this fix for months and today I tried again and still the same error..
I can also see that other people are starting to report this issue finally- https://answers.unity.com/questions/1801756/error-cs0234-the-type-or-namespace-name-editor-doe.html

**Comment by shlighter** [comment]
I just opened a brand new project, installed only the realtime Database SDKm  and added using Firebase.Unity.Editor; and get the same error

**Comment by patm1987** [comment]
Try deleting Firebase.Unity.Editor. There shouldn't be anything in there you need looking at your code (it might be leftover from the old `SetEditorDatabaseUrl` which is no longer used). Let me know if that fixes it.

**Comment by shlighter** [comment]
Yes I did, it did fix that error.  I changed SetEditorDatabaseUrl  to  Firebase.FirebaseApp.DefaultInstance.Options.DatabaseUrl . Please inform Firebase to update their Unity docs because it says to use it and shows to add "using Firebase.Unity.Editor" which now I learn that is obsolete, thanks
