### ISSUE TITLE
DllNotFoundException: FirebaseCppApp-7_0_2

### ISSUE THREAD

**Issue by fdinh** [firebase/quickstart-unity#949]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.9f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: FirebaseMessaging
  * Other Firebase Components in use: FirebaseAnalytics
  * Additional SDKs you are using: no
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: desktop
  * Scripting Runtime: Mono

### [REQUIRED] Please describe the issue here:

There are missing DLLs in the Windows build, while there are no problems for the Android build.
DLLs missing:
* FirebaseCppApp-7_0_2
* libFirebaseCppApp-7_0_2

Attached is a log from the Windows development build:
[Player.log](https://github.com/firebase/quickstart-unity/files/5908997/Player.log)

#### Steps to reproduce:

If needed, I can share the repo with the devs (it's private on github)

#### Relevant Code:
It is likely triggered the first time Firebase is called by the script:
```
string tokenFCM = await Firebase.Messaging.FirebaseMessaging.GetTokenAsync();
```

**Comment by patm1987** [comment]
Hi @fdinh ,

This shouldn't happen, but let me build some context around this and gather some more info.

First, neither Analytics nor Messaging work on desktop ([supported desktop products](https://firebase.google.com/docs/unity/setup#available-libraries-desktop)).

With that said, the _intent_ of the Firebase desktop SDKs are to let you test as much of Firebase as possible on your desktop without any additional effort. This means that you should be able to leave your messaging/analytics code in and your game will just work without having to `#ifdef` out chunks of your code. Additionally, the library that's missing appears to be the a dependency for _all_ of the Firebase SDKs so I would like to work this out if this above statement about support doesn't initially throw you off.

First, there's an easy thing you can check. Often times, version control systems use default filters to get rid of "build artifacts." These will often remove the binary library files Firebase relies on to work, so check that the dll is included. To do this, go to `Assets/Firebase/Plugins/x86_64/FirebaseCppApp-7_0_2' and make sure that the `.dll` one exists (the middle/highlighted in my screenshot):
![image](https://user-images.githubusercontent.com/1111611/106798623-7485ad80-661b-11eb-9945-d76e5e2415c9.png)

Similarly make sure that's included in "Standalone" and "Editor" builds by looking at the inspector when you select that library:
![image](https://user-images.githubusercontent.com/1111611/106798769-adbe1d80-661b-11eb-9818-125a17ab7b00.png)

If it's missing or the configuration looks funky, simply re-import the Firebase `.unitypackage` files that you're using and make sure you commit `FirebaseCppApp-7_0_2.dll` and `FirebaseCppApp-7_0_2.dll.meta` immediately.

If that doesn't work or doesn't describe your issue, I'd be curious if:
1) it works fine in the editor or you're running into issues there too?
2) are you doing a windows desktop build or UWP?

And finally, can you replicate your issue with one of the quickstart apps in this repo([Messaging](https://github.com/firebase/quickstart-unity/tree/master/messaging/testapp), [Analytics](https://github.com/firebase/quickstart-unity/tree/master/analytics/testapp)). If it happens in the quickstarts, it'll help us find the root of the issue much quicker!

**Comment by fdinh** [comment]
Hi @patm1987, thank you for your reply.
I've ended up solving this issue by checking for the device info in Unity before calling firebase, using something like
```cs
string tokenFCM = SystemInfo.deviceType != DeviceType.Handheld ? "" :
    await Firebase.Messaging.FirebaseMessaging.GetTokenAsync();
```
that solves it for me but it is nevertheless something that might need fixing.

I've checked on the folder and I can confirm that FirebaseCppApp-7_0_2 is there and that both Standalone and Editor are checked (I've never touched anything in that folder from the creation).

This bug appears only in the Windows build, not the Editor nor the Android one. I've never tried building for UWP.

I'll try to replicate it in the quickstart if I have some time this weekend, I'll let you know asap!

**Comment by cynthiajoan** [comment]
Thanks @fdinh for your update. Would like to know if you find anything interesting in quickstart app :)

**Comment by itsfaisalali** [comment]
> Hi @patm1987, thank you for your reply.
> I've ended up solving this issue by checking for the device info in Unity before calling firebase, using something like
> 
> ```cs
> string tokenFCM = SystemInfo.deviceType != DeviceType.Handheld ? "" :
>     await Firebase.Messaging.FirebaseMessaging.GetTokenAsync();
> ```
> 
> that solves it for me but it is nevertheless something that might need fixing.
> 
> I've checked on the folder and I can confirm that FirebaseCppApp-7_0_2 is there and that both Standalone and Editor are checked (I've never touched anything in that folder from the creation).
> 
> This bug appears only in the Windows build, not the Editor nor the Android one. I've never tried building for UWP.
> 
> I'll try to replicate it in the quickstart if I have some time this weekend, I'll let you know asap!

Can you Please tell me briefly how you solved this issue please I'm facing same issue in latest sdk version of firebase  . Thank in advance
