### ISSUE TITLE
CloudMessaging - dyld: Library not loaded when app launch

### ISSUE THREAD

**Issue by QuentinGprd** [firebase/quickstart-unity#95]
Hello,

I followed all the steps from the Quick Start to integrate Cloud Messaging in my application , however I get the following crash on app launch:

> dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
> (...)
> Reason: image not found

If I follow some resolutions found on internet, as adding the framework in Embedded Libraries, an error happens while building with xCode:

> Code sign error : bundle format unrecognized, invalid, or unsuitable

And I can't resolve this second one.

Any ideas ? Thank you.

**Comment by stewartmiles** [comment]
As described in https://github.com/firebase/quickstart-unity/blob/master/messaging/testapp/readme.md

- Configure the Xcode project for push messaging.
      - Select the `Unity-iPhone` project from the `Navigator area`.
      - Select the `Unity-iPhone` target from the `Editor area`.
      - Select the `General` tab from the `Editor area`.
      - Scroll down to `Linked Frameworks and Libraries` and click the `+`
        button to add a framework.
        - In the window that appears, scroll to `UserNotifications.framework`
          and click on that entry, then click on `Add`. This framework will only
          appear in Xcode version 8 and higher, required by this library.    <-- *You need to do this*
      - Select the `Capabilities` tab from the `Editor area`.
      - Switch `Push Notifications` to `On`.
      - Scroll down to `Background Modes` and switch it to `On`.
      - Tick the `Remote notifications` box under `Background Modes`.

We have an open task tracking this item to automate this in a future release.

Cheers,
Stewart

**Comment by QuentinGprd** [comment]
Thank you for your help. I already did all of those steps, and UserNotifications.framework does appear in the Linked Frameworks and Libraries. Unfortunately, I still get the same error.

Here is some screenshots of my configuration, Capabilities:
<img width="866" alt="screen shot 2017-07-17 at 18 40 53" src="https://user-images.githubusercontent.com/25503278/28296850-896b28e2-6b1f-11e7-96c5-a80b5e608a54.png">

Linked Frameworks and Libraries:
<img width="870" alt="screen shot 2017-07-17 at 18 40 33" src="https://user-images.githubusercontent.com/25503278/28296846-84bb3c2e-6b1f-11e7-9597-108eff4563a1.png">

I hope it helps,

Quentin

**Comment by stewartmiles** [comment]
Have you reproduced this problem with our sample application or is this specific to your app?

AFAIK Including the UserNotifications.framework as optional is the correct way to go for this to work across a range of iOS devices.  If you're seeing a dynlib load error are you sure that you didn't mark the framework as required and then run the application on a device without the framework (e.g iOS 7 ?).

**Comment by stewartmiles** [comment]
Ok I'm assuming this is specific to your application.  If you're able to reproduce with our sample please ping the bug with a reproducible case and we'll take a look.

Cheers,
Stewart
