### ISSUE TITLE
A/B test working on Unity?

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#953]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.17f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: A/B test (RemoteConfig?)
  * Other Firebase Components in use: Firestore, Analytics, Crashlytics, Remote Config
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

I configured an A/B test with RemoteConfig for our app. After adding the InstanceID of our test device to it in the A/B test dashboard, it still receives the "reference value" instead of the "variant value" specified for the test device through RemoteConfig.

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What happened? How can we make the problem occur?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by cynthiajoan** [comment]
Hi @Nyankoo, can you explain a bit more of "After adding the InstanceID of our test device to it in the A/B test dashboard", a screenshot gonna be better to help me understand the operation you are trying to do. Thanks!

**Comment by Nyankoo** [comment]
Hi @cynthiajoan,
here are two screenshots:
 
This shows the A/B test. You can see that it uses RemoteConfig and has a "Reference" value and a "Variant A" value.
![ab_test_1](https://user-images.githubusercontent.com/6652214/107583271-f5840c80-6bfa-11eb-87f6-af48cdeb5254.png)

This shows the A/B test's test device window. I added the InstanceID of our test device here and specified that it should see "Variant A".
![ab_test_2](https://user-images.githubusercontent.com/6652214/107583274-f61ca300-6bfa-11eb-995e-1c8f1e92adb2.png)

When I know open our app with the test device, it receives the "Reference" value instead of the "Variant A" value.

**Comment by cynthiajoan** [comment]
Hi @Nyankoo, since we released [7.1.0](https://firebase.google.com/support/release-notes/unity#remote-config) with an upgrade for Remote Config, can you check if your issue is also fixed within this upgrade? Thanks!

**Comment by Nyankoo** [comment]
@cynthiajoan I'm currently trying to add my device's Instance ID token to the A/B test (2nd screenshot above), but it always displays an error that the ID isn't valid.
This is with all Firebase plugins updated to 7.1.0.

**Comment by cynthiajoan** [comment]
Thanks @Nyankoo for the update. Looking into this.

**Comment by cynthiajoan** [comment]
Hi @Nyankoo, I just did some experiment, grab an installation token and feed into the A/B testing console, and it works.One thing needs to pay attention to is the token that grabbed for the device need to generated from the same project. (I made that mistake myself). Can you double check on that? Thanks!

**Comment by Nyankoo** [comment]
@cynthiajoan I'm grabbing the token directly from the app via logcat on an Android device with the code I posted above. Is this the same you did?

**Comment by cynthiajoan** [comment]
@Nyankoo Yeah I'm doing the same thing. With that, I'm recommending to submit a [support](https://firebase.google.com/support/troubleshooter/contact) ticket, so our experts can help looking into your project specific settings to diagnose with you.

**Comment by cynthiajoan** [comment]
Btw we just update the samples for [installations](https://github.com/firebase/quickstart-unity/tree/master/installations/testapp).

**Comment by Nyankoo** [comment]
@cynthiajoan I heard back from the Firebase support team, and the issue with adding the token to the A/B test on the dashboard is a bug on their end. They currently don't have an ETA on a fix, but as soon as I hear from them, I will further look into the original problem I opened this issue for!

**Comment by chkuang-g** [comment]
Let us know what you find after you look into the original problem!

**Comment by Nyankoo** [comment]
Still waiting on the Firebase support team to get back to me. Posting to keep this open.

**Comment by cynthiajoan** [comment]
Change to a more proper label.

**Comment by gclaret** [comment]
Im in 7.1.0 Firebase SDK and still seeing this issue. I get the auth token, set it in the test devices, but not getting the configuration im selecting.

I need to set the whole auth token right? for example:
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NzYxNDEyNjgxMjQzOmFuZHJvaWQ6ODMzOTMyNzgwZGY2NTYxZWUxNDJiZSIsImV4cCI6MTYxNzcyODM1OCwiZmlkIjoiYzNsMGJSZGNSZFM0S0p0SElBY2xuYyIsInByb2plY3ROdW1iZXIiOjc2MTQxMjY4MTI0M30.AB2LPV8wRAIgRFPCZ18Qw-ccngQgQQTZiJWemYSzLA3ws338MeF4UScCICyMI6IBiIoftSIU3YPgkqvzMXN-dlmXeoM_q8Fp66s_

**Comment by chkuang-g** [comment]
@gclaret This seems to be an issue in the backend.

Let me ping the team on Monday and see how things go.

**Comment by gclaret** [comment]
@chkuang-g thanks! I've been stuck with this for over a month, and we have a product where we need to implement ab testing asap. Will wait for your post on Monday!

**Comment by gclaret** [comment]
@chkuang-g 10 days gone by. Any news?

**Comment by DellaBitta** [comment]
Hi @Nyankoo and @gclaret,

The change in the Firebase A/B testing backend has been pushed.  Could you please test again and let us know what the results are?

Thanks!

**Comment by gclaret** [comment]
Hi @DellaBitta . I just tested it out, and it's still not working for me. These are the steps Im doing:

- Creating a Remote Config AB Test in Firebase, with a variant on an existing key.
- I put the weight 99-1 on baseline vs variant A
- Building a version of my app, to just output the installation token (no fetching at all is being done to Firebase) (This is done with the Firebase.Installations.FirebaseInstallations.DefaultInstance.GetTokenAsync call)
- Going to the console, add my test device, and assign it the variant A
- Install a new version of my app ON TOP (without uninstalling the previous one), and fetching the remote config
- Getting the baseline version still

**Comment by DellaBitta** [comment]
Hi @gclaret,

I'm sorry to hear that, and yes, this sounds like another backend issue.  I recommend you [Contact Firebase Support](https://firebase.google.com/support/troubleshooter/contact) directly as they will be able to monitor your project in the backend (where as we cannot) and will have a better understanding of what's going wrong.  I recommend linking this issue in your support request so that they have some context of who worked on the previous ticket, etc.

**Comment by DellaBitta** [comment]
@Nyankoo ,

I'm going to close this issue for now.  Please feel free to re-open this if you're still having problems, but like I mentioned above, Firebase Support is probably the best way to get through this issue.  Thanks!
