### ISSUE TITLE
Update(DocumentReference documentReference, IDictionary<string, object> updates) is unable to delete multiple entries

### ISSUE THREAD

**Issue by christianmrswordsmith** [firebase/quickstart-unity#956]
[REQUIRED] Please fill in the following fields:
Unity editor version: 2019.4.9
Firebase Unity SDK version: 7.0.2
Source you installed the SDK: Unity Package Manager
Problematic Firebase Component: Firestore
Other Firebase Components in use: Auth
Additional SDKs you are using: 
Platform you are using the Unity editor on: Windows
Platform you are targeting: iOS, Android
Scripting Runtime: IL2CPP
[REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
Issue has been reproduced in Editor. Not yet tested on iOS and Android.

`			string path = "profile-progression_test_v1/testProfileId2";
			DocumentReference documentReference = FirebaseFirestore.DefaultInstance.Document(path);

			await documentReference.DeleteAsync();
			await documentReference.SetAsync(new ProfileStateDocument());

			Dictionary<string, object> addedData = new Dictionary<string, object>();
			addedData.Add("Currencies.Val1", 1);
			addedData.Add("Currencies.Val2", 2);
			addedData.Add("Currencies.Val3", 3);

			WriteBatch batch = FirebaseFirestore.DefaultInstance.StartBatch();
			batch.Update(documentReference, addedData);
			await batch.CommitAsync();
			
			Dictionary<string, object> removeData = new Dictionary<string, object>();
			removeData.Add("Currencies.Val1", FieldValue.Delete);
			removeData.Add("Currencies.Val2", FieldValue.Delete);
			removeData.Add("Currencies.Val3", FieldValue.Delete);

			WriteBatch batch2 = FirebaseFirestore.DefaultInstance.StartBatch();

			batch2.Update(documentReference, removeData);
			await batch2.CommitAsync();`

Expected result: 
Currencies: {} //Empty map. 

Actual result: 
Currencies:
   Val2: 2
   Val3: 3
   
It seems that the Update function is only able to remove one entry. 

Steps to reproduce:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? Yes

What's the issue repro rate? (eg 100%, 1/5 etc) 100%

What happened? How can we make the problem occur? This could be a description, log/console output, etc.
Entries are not deleted as expected. Run the code above and you should see the problem.

If you have a downloadable sample project that reproduces the bug you're reporting, you will likely receive a faster response on your issue.

Relevant Code:
// TODO(you): c

**Comment by dconeybe** [comment]
@christianmrswordsmith Thank you for reporting this bug and I apologize for the confusion and inconvenience this has caused. This is actually a known issue (https://github.com/firebase/quickstart-unity/issues/882) and the fix will be included in the next release of the Unity SDK.

Fortunately, there is a workaround that you can use until the fix is released: use a `WriteBatch` to delete more than one field from a document. See the linked bug for details.

Since this issue is a duplicate, I'm going to close it; however, feel free to re-open if you think that this issue is different than the linked issue or if you have further questions or comments.

**Comment by christianmrswordsmith** [comment]
Thx!
Added work around :)

Any idea of when the fix might be released?

**Comment by dconeybe** [comment]
I'm glad the work around worked for you! The next release of the Unity SDK that would include the fix is *planned* for some time in March 2021; however, there is no committed date and I can't promise anything!
