### ISSUE TITLE
The default Firebase app has not yet been configured. 

### ISSUE THREAD

**Issue by MuhsinEge** [firebase/quickstart-unity#957]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 12.4(12D4e)
  * Firebase SDK version: 6.24
  * Installation method: CocoaPods 
  * Firebase Component:  Auth, Database

### [REQUIRED] Step 2: Describe the problem
We are trying to get IOS build of our game and run into this problem:

6.24.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.\

We actually get an answer about it from firebase support that was exactly same as: 
https://stackoverflow.com/questions/37334323/the-default-app-has-not-been-configured-yet

I could not find appDelegate file to add proper functions and have less experience with working MAC/IOS environment. 
 
Checked the .plist file and it was all configured well(Approved by the firebase support).
Unity Version: 2019.16f1. 

#### Steps to reproduce:

The App has some other SDKs and Big code base so i can not know how to reproduce the issue. 

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by cynthiajoan** [comment]
Hi @MuhsinEge 

I'd like to get more information. Is this issue starting to appear when you are trying to upgrade the SDK from 6.24 to 7.0? Are you developing using Unity Editor? Is the upgrading perform through Unity import asset or UPM?

**Comment by MuhsinEge** [comment]
Hi @cynthiajoan 

I actually made a mistake by writing 7.0.0 because i forgot that we roll back the whole project after i updated the FirebaseSDK but the roll back was not about Firebase SDK. The xCode project that i got this error was builded with 6.24 with Unity. I'm developing using the Unity Editor and the update of Firebase SDK was not the issue but just upgraded to 7.0.2 today and tomorrow i'll gonna try to get another build with it.  Sorry for my late response,

**Comment by cynthiajoan** [comment]
Thanks @MuhsinEge for your update. Yeah please let me know your experiment result tomorrow :)

**Comment by MuhsinEge** [comment]
Hi @cynthiajoan

I have upgraded the SDK.  I had some problems about Firebase removed the Firebase.Unity.Editor on the new releases but i finally figure out. There are some bugs about it and you can find it from my other github issue : https://github.com/firebase/quickstart-unity/issues/958

I'm trying to manual shard and one i done with it i'll gonna try to get new IOS build with 7.0.3.

**Comment by chkuang-g** [comment]
@MuhsinEge 
We actually fixed a couple of issue with iOS build in `7.1.0`
https://firebase.google.com/support/release-notes/unity#version_710_-_february_16_2021

You can also see #862

In brief, if you have multiple targets in your Podfile, `GoogleServices-Info.plist` need to be added to `Unity-iPhone` target as well. `7.1.0` now add the Firebase config file to all targets.

Please try to upgrade and see if that resolve your issue.

If not, could you provide a bit more information about your case? Logs are helpful.  Podfile would be nice.  Or basic information like the following.
  * Unity editor version: _____
  * Firebase Unity SDK version: _____
  * Source you installed the SDK: _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Additional SDKs you are using: _____ (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

**Comment by MuhsinEge** [comment]
@chkuang-g  Hi. 

Updated 7.0.2 and it solved our build problem but I don't know when we going to update 7.1.0. 

The following information is about the old versions that gave us error while playing.

Unity editor version: 2019.4.16f1
Firebase Unity SDK version: 6.24
Source you installed the SDK: unitypackage
Problematic Firebase Component:  Auth, Database
Other Firebase Components in use: Analytics, Messaging
Additional SDKs you are using: Facebook, GameAnalytics
Platform you are using the Unity editor on: Mac
Platform you are targeting: iOS
Scripting Runtime: IL2CPP

**Comment by cynthiajoan** [comment]
Hi @MuhsinEge, glad to see you are unblocked with 7.0.2. I will close the issue and if you still have related questions, feel free to reopen and comment.
