### ISSUE TITLE
Example needed for handling auth exceptions

### ISSUE THREAD

**Issue by mjholtzem** [firebase/quickstart-unity#96]
I need to be able to detect and handle specific errors for authorization requests (such as email being invalid or user account already exists). The documentation seems to only cover this for iOS and I don't see any way to detect these specific errors short of...

`if(task.Exception.ToString().Contains("The email address is already in use by another account"))`

or similar which is pretty unsatisfactory. An example of the proper way to achieve this would be super helpful.

**Comment by stewartmiles** [comment]
Thanks for reporting this.  We've exposed granular errors for auth in the 4.2.0 release of the SDK  https://firebase.google.com/support/release-notes/unity#4.2.0

See https://firebase.google.com/docs/reference/unity/namespace/firebase/auth#namespace_firebase_1_1_auth_1aef1e65c370d8edb018dc417ae73ec11c for the set of errors and https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/TestApp/UIHandler.cs#L210 as the example.

Cheers,
Stewart

**Comment by manelizzard** [comment]
Above github link not found. Here's is the updated link: https://github.com/firebase/quickstart-unity/blob/master/auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs
