### ISSUE TITLE
Firestore - Undefined symbols for architecture arm64 - iOS - Xcode

### ISSUE THREAD

**Issue by NudeNULL** [firebase/quickstart-unity#960]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: _____ 2019.4.14f1
  * Firebase Unity SDK version: _____ 7.0.2
  * Source you installed the SDK: _____ .unitypackage
  * Problematic Firebase Component: _____ Firestore
  * Other Firebase Components in use: _____ FirebaseAnalytics, FirebaseMessaging
  * Additional SDKs you are using: _____ Facebook, MAX, Google Play Games
  * Platform you are using the Unity editor on: _____ Windows
  * Platform you are targeting: _____ iOS, Android
  * Scripting Runtime: _____ IL2CPP

### [REQUIRED] Please describe the issue here:

Xcode build fails, the error:
Undefined symbols for architecture arm64:
  "firebase::auth::User::GetToken(bool)", referenced from:
      firebase::firestore::FirebaseCppCredentialsProvider::RequestToken(std::__1::function<void (firebase::firestore::util::StatusOr<firebase::firestore::auth::Token>)>) in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
  "firebase::auth::AuthStateListener::~AuthStateListener()", referenced from:
      firebase::firestore::FirebaseCppCredentialsProvider::FirebaseCppCredentialsProvider(firebase::auth::Auth*) in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      firebase::firestore::FirebaseCppCredentialsProvider::~FirebaseCppCredentialsProvider() in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      firebase::firestore::FirebaseCppCredentialsProvider::~FirebaseCppCredentialsProvider() in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      non-virtual thunk to firebase::firestore::FirebaseCppCredentialsProvider::~FirebaseCppCredentialsProvider() in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      non-virtual thunk to firebase::firestore::FirebaseCppCredentialsProvider::~FirebaseCppCredentialsProvider() in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
  "firebase::auth::Auth::AddAuthStateListener(firebase::auth::AuthStateListener*)", referenced from:
      firebase::firestore::FirebaseCppCredentialsProvider::SetCredentialChangeListener(std::__1::function<void (firebase::firestore::auth::User)>) in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
  "firebase::auth::Auth::current_user()", referenced from:
      firebase::firestore::(anonymous namespace)::GetCurrentUser(firebase::auth::Auth*) in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      firebase::firestore::FirebaseCppCredentialsProvider::GetToken(std::__1::function<void (firebase::firestore::util::StatusOr<firebase::firestore::auth::Token>)>) in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      firebase::firestore::FirebaseCppCredentialsProvider::IsSignedIn() const in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
      firebase::firestore::FirebaseCppCredentialsProvider::RequestToken(std::__1::function<void (firebase::firestore::util::StatusOr<firebase::firestore::auth::Token>)>) in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
  "firebase::g_auth_initializer", referenced from:
      firebase::auth_ref in libFirebaseCppFirestore.a(firestore_ios_eec52dfa6e1434eb3ea69ba309362c0c.o)
      firebase::auth_ref in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
  "typeinfo for firebase::auth::AuthStateListener", referenced from:
      typeinfo for firebase::firestore::FirebaseCppCredentialsProvider in libFirebaseCppFirestore.a(credentials_provider_ios_c4b11a23b793b1dcedea6096ad99afca.o)
  "firebase::auth::Auth::GetAuth(firebase::App*, firebase::InitResult*)", referenced from:
      firebase::firestore::(anonymous namespace)::CreateCredentialsProvider(firebase::App*) in libFirebaseCppFirestore.a(firestore_ios_eec52dfa6e1434eb3ea69ba309362c0c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

#### Steps to reproduce:

In my case is a huge project, so it's not easy to describe the steps to reproduce, but everything I did is simply setup Firebase libraries I mentioned as said in the documentation, and on Android everything works fine.

I believe it can be the same issue that was on older versions where the Dependencies version files contains wrong version for Firestore and the linker searches for the methods that no longer exists. The issue is I don't know 100% how to experiment and what version to try in order to test this possible fix.

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I did not try with quickstart project

What happened? How can we make the problem occur?
It happens everytime

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by wu-hui** [comment]
Thanks for the issue report.

Can you describe what steps you took, or at least what instruction you follow? And I'd recommend trying it out with quickstart project, because that can be helpful to identify if it is an issue with the SDK itself, or it is just not working in some environment.

**Comment by wu-hui** [comment]
I noticed in the components listed in the issue, you missed `FirebaseAuth` which seems to be what you are using. But you also said Android works for you, so I am not sure if this is the real cause or you simply missed it in the text.

**Comment by NudeNULL** [comment]
I am investigating now if the iOS build will work just without the Firestore, but everything else enabled.
Also why would I use FirebaseAuth? I did not add it to the project.

**Comment by wu-hui** [comment]
Because in the error message it is looking for `"firebase::auth::User::GetToken(bool)"` which suggests you do auth.

**Comment by NudeNULL** [comment]
Is it possible that the Firestore is using it by default?

**Comment by NudeNULL** [comment]
Anyway right now I am making a build without firestore, if it passes then the problem is that it is using Auth API somehow

**Comment by NudeNULL** [comment]
Yes, I confirm that the build worked without Firestore, waiting then for your research results. If you need more info let me know.

**Comment by NudeNULL** [comment]
I also tried to build with Auth plugin added to the project, now I am getting other error
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GKLocalPlayer", referenced from:
      objc-class-ref in libFirebaseCppAuth.a(credential_ios_7e32949a14fe9694040ff5eed8d1b954.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wu-hui** [comment]
I cannot reproduce this with my simple test app, unfortunately.

I am wondering if you have run `pod install` from the generate iOS directory by Unity. If not, please do. 

Another thing to try is to use a later version of the SDK. This has a less chance to work though, because not much has changed..

**Comment by NudeNULL** [comment]
I tried to use the latest version, thank you for the update, it worked!
