### ISSUE TITLE
[Question] Unity/IOS GameCenterAuth Does not work properly with quickstart example.

### ISSUE THREAD

**Issue by MuhsinEge** [firebase/quickstart-unity#962]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.16f1
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Not yet
  * Additional SDKs you are using: Facebook, Game Analytics
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the question here:

Hi Everyone, 

I had to implement Game Center Auth using the github quickstart and there are no other documentation about it on firebase docs. I include the .cs file for you to see. When i play the app on device the debug logs that i see goes like this:

Debug.Log("Game Center Initialization Complete - Result: " + success); //  Line:100
Debug.Log("Game Center Success 1 "); // Line105
Debug.Log("Game Center Success 3 "); // Line 118

Then it is supposed to go HandleSignInWithUser() and debug Line:163 but it does not for some reason. 

Do you have any idea about this? Or are there any new resource about [Unity/GameCenterAuth?]

[GameCenterAuth.zip](https://github.com/firebase/quickstart-unity/files/5996555/GameCenterAuth.zip)

Cheers.

**Comment by MuhsinEge** [comment]
Found out the thread does not continue after the execution of var loginTask = auth.SignInWithCredentialAsync(credential); with no error log.

**Comment by MuhsinEge** [comment]
I found out the problem was caused by me using the wrong auth object to signInWithCredentialASync. Fixed it by changing it to my default auth from singleton class.

**Comment by ArgoKang** [comment]
@MuhsinEge We are suffered from same problem for days.. Can you show how codes are changed?

**Comment by ArgoKang** [comment]
Solved. Move googleService~~.plist to classes folder. Oh god..

**Comment by MuhsinEge** [comment]
Hey @ArgoKang  

Happy to hear you solved your problem. I guess it was not caused by the same issue.
