### ISSUE TITLE
[Bug] Crashlytics is not being enabled (Did not register exception handlers: Crashlytics SDK was not initialized)

### ISSUE THREAD

**Issue by cramberrycookies** [firebase/quickstart-unity#963]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2.3.f21
   * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK:Tried both
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics
  * Additional SDKs you are using: Admob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime:IL2CPP

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)
Havent tried the github project

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Am trying to use Crashlytics and no crashes are registering in the firebase console. I get the output from the debug

Did not register exception handlers: Crashlytics SDK was not initialized

[...]
DEBUG: auth app initializer Enabling
DEBUG: App initializer crashlytics not found, failed to enable.
[...]

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
` {
        Firebase.FirebaseApp.LogLevel = Firebase.LogLevel.Debug;
        FirebaseApp.CheckAndFixDependenciesAsync().ContinueWithOnMainThread(task =>
        {
            dependencyStatus = task.Result;
            if (dependencyStatus == DependencyStatus.Available)
            {
                InitializeFirebase();
                Debug.Log("Firebase ready to use");
            }
            else
            {
                Debug.LogError("Could not resolve all Firebase dependencies: " + dependencyStatus);
            }
        });
    }

     // Handle initialization of the necessary firebase modules:
    void InitializeFirebase()
    {
        var app = FirebaseApp.DefaultInstance;
        FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
        firebaseInitialized = true;
        Firebase.Analytics.FirebaseAnalytics.LogEvent(Firebase.Analytics.FirebaseAnalytics.EventAppOpen);
        throw new System.Exception("test exception please ignore");
    }

**Comment by javierpal** [comment]
same here

**Comment by chkuang-g** [comment]
Hmm, this does not sound right.  According to code, it does look like Crashlytics failed to initialize.

@cramberrycookies @javierpal 
Could you provide a bit more information, like
- Did you see any other Crashlytics related log? Like Exceptions?
- Did you see any file generated under `Assets/Plugins/Android/FirebaseCrashlytics.androidlib/`?
