### ISSUE TITLE
[Question] What is crashlytics_build_id.xml and crashlytics_unity_version.xml and can they be gitignore'd?

### ISSUE THREAD

**Issue by p0w1nd** [firebase/quickstart-unity#966]
Hi!

In `Assets/Plugins/Android/FirebaseCrashlytics.androidlib/res/values` I notice there are 2 files:

_crashlytics_build_id.xml
crashlytics_unity_version.xml_
(and with 2 related .meta files generated by Unity)

Questions:

1. What are they for exactly?
2. Is it needed to track them in git or we can add them to .gitignore? (Especially it seems crashlytics_build_id.xml is changed every time I build the Unity project which I think it's like a "temp" generated file)

Thanks.

**Comment by alexames** [comment]
Those files are regenerated whenever you build your scene, so they're safe to .gitignore. I'm not sure what they're for off the top of my head but I'll ask and get back to you.

**Comment by chkuang-g** [comment]
They are required for Crashlytics Android SDK. Basically information like bundle-id and Unity version number. (You can click into it and read them. :) )

I would say you can gitignore the entire `FirebaseCrashlytics.androidlib` and `FirebaseApp.androidlib` folder.  They will just regenerate whenever Unity is launched.

I'll close this issue for now.

**Comment by Thaina** [comment]
@chkuang-g `FirebaseCrashlytics.androidlib` is not generated when launched, instead it generated when build. Could we have it generated when launched, or option to make it like so?
