### ISSUE TITLE
[Question] How to not re-trigger a Dynamic link? / How to check for pending links on app focus?

### ISSUE THREAD

**Issue by RobinopdeBeek** [firebase/quickstart-unity#969]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2.3
  * Firebase Unity SDK version: 7.0.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Dynamic Links
  * Other Firebase Components in use: Auth, Database, Firestore, Storage, Analytics, Cloud Functions
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android (iOS in the future)
  * Scripting Runtime:  IL2CPP

### [REQUIRED] Please describe the question here:

When I click on a dynamic link it opens the app and goes to the correct page (very cool stuff btw, thanks!). But when I put the app to the background and then reopen it, it re-triggers the dynamic link (and going to the page again). This also happens when I close the Android keyboard after typing stuff.
So how can I let my app know that the link was already used and shouldn't be used again? Can I dispose the Received Dynamic Link in some way? Why would it keep triggering anyway?

Here is my code that receives the dynamic link: 
```
public static class DynamicLinksManager 
{      
        private static bool isInitialized = false;

        // Gets called on Start after authentication has been setup.
        // Also gets called OnApplicationPause(false)
        public static void InitializeLinks()
        {
            if (!isInitialized)
            {
                Debug.Log("Initialized Dynamic Links");
                isInitialized = true;
                DynamicLinks.DynamicLinkReceived += OnDynamicLink;
            }
        }
       
        // Gets called OnApplicationPause(true)
        public static void DeinitializeLinks()  
        {
            if (isInitialized)
            {
                isInitialized = false;
                DynamicLinks.DynamicLinkReceived -= OnDynamicLink;
            }
        }

        private static void OnDynamicLink(object sender, EventArgs args)
        {
            var dynamicLinkEventArgs = args as ReceivedDynamicLinkEventArgs;
            var deeplink = dynamicLinkEventArgs.ReceivedDynamicLink.Url;
            Debug.Log("Received dynamic link: " + dynamicLinkEventArgs.ReceivedDynamicLink.Url.OriginalString);
            
            if (!deeplink.OriginalString.Contains("?ProjectID="))
            { 
                Debug.Log("Deeplink does not contain a ProjectID");
                return;
            }

            string projectID = GetProjectIDFromUrl(deeplink.OriginalString, "?ProjectID=");
            Debug.Log("Project ID received from link: " + projectID);

            GotoProject(projectID);
        }
}
```

**Comment by RobinopdeBeek** [comment]
So when I don't unsubscribe from receiving links (`DynamicLinks.DynamicLinkReceived -= OnDynamicLink`) when the app gets unfocused it stops re-triggering the dynamic link, which makes sense. However, then clicking the dynamic link stops working. It does open up the app again, but it doesn't bring me to the right page anymore. 

So maybe I should change the question to: <b> How to check for pending dynamic links? </b> or <b> How to check if same link was clicked again? </b>

Could still use some help :)

**Comment by chkuang-g** [comment]
Your issue seems to be the same to  #565

Unfortunately the team did not have a chance to look into this yet.  You should be able to use this workaround https://github.com/firebase/quickstart-unity/issues/565#issuecomment-620713784 to clear the intent extra when the Dynamic Link is triggered.

Let me know if this workaround works for you.  Also, please upvote #565 if that is the same issue of yours!

Shawn

**Comment by RobinopdeBeek** [comment]
Thanks Shawn! #565 was indeed the same issue and the suggested workaround of Johan worked like a charm. Apologies for not finding the issue on my own.

**Comment by vimanyu** [comment]
Thanks for confirming @RobinopdeBeek.
Closing this issue as duplicate to keep one thread for discussions.
