### ISSUE TITLE
there is no information about set AndroidManifest.xml

### ISSUE THREAD

**Issue by green4you** [firebase/quickstart-unity#97]
firebase message server needs to change AndroidMaanifest.xml file
but never find this information

**Comment by stewartmiles** [comment]
If you want to customize your manifest it's here:
https://firebase.google.com/docs/cloud-messaging/android/client#manifest

If you're looking for documentation about customizing the activity it's here:
https://firebase.google.com/docs/cloud-messaging/unity/client#note_for_android

If you want to customize the behavior of the messaging service on Android, it's here:
https://firebase.google.com/docs/cloud-messaging/cpp/client#custom_message_handling_on_android

**Comment by green4you** [comment]
@stewartmiles 

yes I read it all but
there is no information
UnityPlayerActivity should be changed to MessagingUnityPlayerActivity in AndroidManifest.xml

it should be written to firebase messaging SDK for unity guide
they wrote SDK make AndroidManifest automatically, but it didn't.

**Comment by alexames** [comment]
Can you give us a little bit more information about your project? It sounds like you added the Firebase Cloud Messaging Unity Package to your project, but the generated `AndroidManifest.xml` file did not contain MessagingUnityPlayerActivity, is that correct? It's supposed to be merged in automatically, so if it's not, then something might be broken. Can you verify that the file `Assets/Plugins/Android/AndroidManifest.xml` exists in your project? If so, can you post the contents of the auto-generated `AndroidManifest.xml`, which I believe should be located at `Temp/StagingArea/AndroidManifest.xml` (this location might vary by version)?

**Comment by stewartmiles** [comment]
@green4you do you have any further information about what you're looking for in the documentation?

**Comment by stewartmiles** [comment]
@green4you haven't heard from you in a while so I'm closing this out.  If you have any more docs that you're after let us know.
