### ISSUE TITLE
[Bug] Unable to find FirebaseCppApp error

### ISSUE THREAD

**Issue by jonathanahern** [firebase/quickstart-unity#971]
### Please fill in the following fields:

  * Unity editor version: Unity 2019.3.14
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Core
  * Other Firebase Components in use: Auth, Database, Google Analytics for Firebase
  * Additional SDKs you are using: Unity IAP, Appsflyer
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### Please describe the issue here:

The project works well for iOS and am only having problems with Android builds. I run Force Resolve and then start to build but get the massive amount of Androidx errors that I see online like so:

`java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class android.support.v4.graphics.drawable.IconCompatParcelizer found in modules classes.jar (:androidx.core.core-1.0.0:) and classes.jar (androidx.core:core:1.1.0)`

I tried pasting android.enableJetifier=true and android.useAndroidX=true but that didn't do the trick. I tried Delete Resolved Libraries and that got the build finished at least but I think it just caused other problems.

When the game starts up on my Android, it freezes up with errors such as:

```
2021/03/01 01:54:58.992 32286 32332 Error Unity Unable to find FirebaseCppApp-6_15_2
2021/03/01 01:54:59.035 32286 32332 Error Unity DllNotFoundException: Unable to load DLL 'FirebaseCppApp-6_15_2': The specified module could not be found.
2021/03/01 01:54:59.035 32286 32332 Error Unity   at Firebase.Analytics.FirebaseAnalyticsPINVOKE+SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_FirebaseAnalytics (Firebase.Analytics.FirebaseAnalyticsPINVOKE+SWIGExceptionHelper+ExceptionDelegate applicationDelegate...
```

Other possibly relevant facts:
- I made sure all versions of Firebase packages were the same. 
- I downgraded my Java version to 1.8 to solve an issue with builds (which I'm blanking now at what the problem was. It might have been the androidx problem).
- It was actually working fine on Friday except for this point at which it froze. This is when I decided to try and rebuild it and switch Java versions and it broke this way.
- I'm also getting an error about AppsFlyer in the logcat: 
`2021/03/01 01:54:59.147 32286 32332 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.appsflyer.unity.AppsFlyerAndroidWrapper`

Thanks for the help. Let me know if you need more information. I inherited this project so there might be elements I don't know about that are affecting this.

**Comment by jonathanahern** [comment]
Seems like it's working now. Definitely should not be deleting resolved libraries. Followed the advice of Pat on [this](https://github.com/firebase/quickstart-unity/issues/944) thread and added mainTemplate.gradle and gradleTemplate.properties as well just making a custom path to openJDK. Sorry to clutter.

**Comment by TwitRco** [comment]
dit was te verwachten, Jonathan! hoe kunnen wij je helpen zonder psychydelische  paddestoelen uit  de buurt moeten gaan zoeken om te kunnen knagen
