### ISSUE TITLE
[Bug] Need to add GameKit after update from 6.11 to 7.1.0

### ISSUE THREAD

**Issue by paradizIscool** [firebase/quickstart-unity#979]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2.6
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: UPM (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Auth
  * Other Firebase Components in use: Firestore, RemoteConfig, Analytics
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: iOS
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Need to add gameKit to build

#### Relevant Code:

Undefined symbols for architecture arm64:
 “_OBJC_CLASS_$_GKLocalPlayer”, referenced from:
   objc-class-ref in libFirebaseCppAuth.a(credential_ios_7e32949a14fe9694040ff5eed8d1b954.o)
5:04
You should add GameKit.framework to your build

**Comment by paradizIscool** [comment]
Note, I don't want to use GameCenter Auth method (already using apple sign in)

**Comment by chkuang-g** [comment]
Duplicate of #954
