### ISSUE TITLE
building errors in "universal windows platform"

### ISSUE THREAD

**Issue by hencohen3** [firebase/quickstart-unity#98]
I am using unity 2017.1.0f3.

and i getting "the type or namespace 'firebase' could not be found"

how can i solve it?
thanks

![capture2](https://user-images.githubusercontent.com/19545791/29062528-bb7c77f2-7c2a-11e7-89d2-4e8d89aefc5e.PNG)
![capture1](https://user-images.githubusercontent.com/19545791/29062527-bb79d768-7c2a-11e7-80b6-2d23273267a9.PNG)

**Comment by stewartmiles** [comment]
We don't support UWP.

Our supported platforms are documented here:
https://firebase.google.com/docs/unity/setup

Cheers,
Stewart
