### ISSUE TITLE
-BUG-  Firebase forces users to install GameKit.framework, Otherwise you'll get XCODE ERROR-  OBJC_CLASS$_GKLocalPlayer in libFirebaseCppAuth.a symbol not find for architecture arm64

### ISSUE THREAD

**Issue by shlighter** [firebase/quickstart-unity#981]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version:2020.1.11f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK:unitypackage  _____ (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: auth _____ (Auth, Database, etc.)
  * Other Firebase Components in use: auth database storage functions(Auth, Database, etc.)
  * Additional SDKs you are using: admob (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: windows(Mac, Windows, or Linux)
  * Platform you are targeting: ios (iOS, Android, and/or desktop)
  * Scripting Runtime: _____ (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:
I can't build my project in XCODE, I get this error-
Undefined symbol: OBJC_CLASS$_GKLocalPlayer referenced from objc-class-ref in libFirebaseCppAuth.a
ld: symbol not find for architecture arm64
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
Building unity IOS project,  Building in XCODE
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
Might similiar to issue- 
https://github.com/firebase/quickstart-unity/issues/954

**Comment by shlighter** [comment]
I also see the same error here, but it's not relevant to Facebook, since in my case I don't have Facebook, notice how they wrote-  "OBJC_CLASS$GKLocalPlayer", referenced from:
objc-class-ref in libFirebaseCppAuth.a

https://github.com/facebook/facebook-sdk-for-unity/issues/504

**Comment by shlighter** [comment]
OK I solved the issue for now but the bug is still open.  Firebase now forces you to install GameKit.framework for some reason. The temporary solution is to go to FIRGameCenterAuthProvider.m and change their file.  Full explanation about the firebase bug is here-   https://github.com/facebook/facebook-sdk-for-unity/issues/504#issuecomment-746729238  Please fix it.

**Comment by chkuang-g** [comment]
@shlighter  Thanks again for the information. 

I will close this bug due to duplication to #954. This is easier for us to manage bugs.

Also add the summary here https://github.com/firebase/quickstart-unity/issues/954#issuecomment-791891479. Please comment and follow that issue from now on.
