### ISSUE TITLE
Error getting credential from Apple on linking with popup with firebase

### ISSUE THREAD

**Issue by tamngonesv030** [firebase/quickstart-unity#985]
In my unity project.  I'm implementing link with popup with Apple as a provider. I checked: Services ID, Apple team Id, Key Id, Private key but  I'm always getting the following error:

Firebase.FirebaseException: The supplied auth credential is malformed or has expired. [ Error getting access token from https://appleid.apple.com, OAuth2 redirect uri is: https://myproject.firebaseapp.com/__/auth/handler, response: OAuth2TokenResponse{params: error=invalid_client, httpMetadata: HttpMetadata{status=400, cachePolicy=NO_CACHE, cacheDurationJava=null, cacheImmutable=false, staleWhileRevalidate=null, filename=null, lastModified=null, retryAfter=null, headers=HTTP/1.1 200 OK
    
    , contentSecurityPolicies=[], originTrials=[], cookieList=[]}} ]
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> Firebase.FirebaseException: The supplied auth credential is malformed or has expired. [ Error getting access
 No account for auth token provided

**Comment by vimanyu** [comment]
Hi, 
Just wanted to point out that there is documentation for Apple sign in Firebase Auth here.
If you followed that and are still running into errors, it seem like a backend issue and [FirebaseSupport](https://firebase.google.com/support) will be able to help you with this.
