### ISSUE TITLE
[Bug] Firebase Remote Config SIGSEGV in Docker container

### ISSUE THREAD

**Issue by louis030195** [firebase/quickstart-unity#995]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.2.0f1
  * Firebase Unity SDK version: 7.1.1
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Remote config (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Additional SDKs you are using: None (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Linux (Mac, Windows, or Linux)
  * Platform you are targeting: Linux, iOS, Android (iOS, Android, and/or desktop)
  * Scripting Runtime: Mono for dev, IL2CPP for prod (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Running Firebase Remote Config works fine on clients (Linux, Android) and headless instance (Linux), but it crashes with SIGSEGV when the headless build is run within a ubuntu:20.04 Docker container?!?

Tried both with .net standard 2.0 and .NET 4.x

> Fetching data...
> 
> /proc/self/maps:
> 4039f000-403af000 rwxp 00000000 00:00 0 
> 4111b000-411ad000 rwxp 00000000 00:00 0 
> 5633b5915000-5633b5916000 r--p 00000000 08:02 3353555                    /app/hg_worker
> 5633b5916000-5633b5917000 r-xp 00001000 08:02 3353555                    /app/hg_worker
> 5633b5917000-5633b5918000 r--p 00002000 08:02 3353555                    /app/hg_worker
> 5633b5918000-5633b5919000 rw-p 00003000 08:02 3353555                    /app/hg_worker
> 5633b6283000-5633b7109000 rw-p 00000000 00:00 0                          [heap]
> 7f5748000000-7f5748021000 rw-p 00000000 00:00 0 
> 7f5748021000-7f574c000000 ---p 00000000 00:00 0 
> 7f5750000000-7f5750021000 rw-p 00000000 00:00 0 
> 7f5750021000-7f5754000000 ---p 00000000 00:00 0 
> 7f5754000000-7f5754021000 rw-p 00000000 00:00 0 
> 7f5754021000-7f5758000000 ---p 00000000 00:00 0 
> 7f5758000000-7f5758021000 rw-p 00000000 00:00 0 
> 7f5758021000-7f575c000000 ---p 00000000 00:00 0 
> 7f575c000000-7f575c021000 rw-p 00000000 00:00 0 
> 7f575c021000-7f5760000000 ---p 00000000 00:00 0 
> 7f5760000000-7f5760123000 rw-p 00000000 00:00 0 
> 7f5760123000-7f5764000000 ---p 00000000 00:00 0 
> 7f5764000000-7f5764021000 rw-p 00000000 00:00 0 
> 7f5764021000-7f5768000000 ---p 00000000 00:00 0 
> 7f5768000000-7f57680e4000 rw-p 00000000 00:00 0 
> 7f57680e4000-7f576c000000 ---p 00000000 00:00 0 
> 7f576c000000-7f576c021000 rw-p 00000000 00:00 0 
> 7f576c021000-7f5770000000 ---p 00000000 00:00 0 
> 7f5770000000-7f5770200000 rw-p 00000000 00:00 0 
> 7f5770200000-7f5780000000 ---p 00000000 00:00 0 
> 7f5780000000-7f5780001000 rw-p 00000000 00:00 0 
> 7f5780001000-7f5781000000 ---p 00000000 00:00 0 
> 7f5781000000-7f5782001000 rw-p 00000000 00:00 0 
> 7f5782001000-7f5790000000 ---p 00000000 00:00 0 
> 7f5790000000-7f5791000000 rw-p 00000000 00:00 0 
> 7f5791000000-7f57a0000000 ---p 00000000 00:00 0 
> 7f57a3d19000-7f57a3d5a000 rw-p 00000000 00:00 0 
> 7f57a3d5a000-7f57a3d5c000 r--p 00000000 08:02 2816535                    /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
> 7f57a3d5c000-7f57a3d60000 r-xp 00002000 08:02 2816535                    /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
> 7f57a3d60000-7f57a3d61000 r--p 00006000 08:02 2816535                    /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
> 7f57a3d61000-7f57a3d62000 r--p 00006000 08:02 2816535                    /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
> 7f57a3d62000-7f57a3d63000 rw-p 00007000 08:02 2816535                    /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
> 7f57a3d63000-7f57a3d64000 ---p 00000000 00:00 0 
> 7f57a3d64000-7f57a4564000 rw-p 00000000 00:00 0 
> 7f57a4564000-7f57a4565000 ---p 00000000 00:00 0 
> 7f57a4565000-7f57a4d65000 rw-p 00000000 00:00 0 
> 7f57a4d65000-7f57a4d66000 ---p 00000000 00:00 0 
> 7f57a4d66000-7f57a5566000 rw-p 00000000 00:00 0 
> 7f57a5566000-7f57a5567000 ---p 00000000 00:00 0 
> 7f57a5567000-7f57a5d6b000 rw-p 00000000 00:00 0 
> 7f57a5d6b000-7f57a5d6c000 ---p 00000000 00:00 0 
> 7f57a5d6c000-7f57a5d6d000 rw-p 00000000 00:00 0 
> 7f57a5d6d000-7f57a5d75000 ---p 00000000 00:00 0 
> 7f57a5d75000-7f57a5f70000 rw-p 00000000 00:00 0 
> 7f57a5f70000-7f57a5f71000 ---p 00000000 00:00 0 
> 7f57a5f71000-7f57a5f72000 rw-p 00000000 00:00 0 
> 7f57a5f72000-7f57a5f7a000 ---p 00000000 00:00 0 
> 7f57a5f7a000-7f57a6175000 rw-p 00000000 00:00 0 
> 7f57a6175000-7f57a6176000 ---p 00000000 00:00 0 
> 7f57a6176000-7f57a6177000 rw-p 00000000 00:00 0 
> 7f57a6177000-7f57a617f000 ---p 00000000 00:00 0 
> 7f57a617f000-7f57a637a000 rw-p 00000000 00:00 0 
> 7f57a637a000-7f57a637b000 ---p 00000000 00:00 0 
> 7f57a637b000-7f57a637c000 rw-p 00000000 00:00 0 
> 7f57a637c000-7f57a6384000 ---p 00000000 00:00 0 
> 7f57a6384000-7f57a657b000 rw-p 00000000 00:00 0 
> 7f57a657b000-7f57a6597000 r--p 00000000 08:02 3353592                    /app/hg_worker_Data/Managed/System.Net.Http.dll
> 7f57a6597000-7f57a65d7000 rw-p 00000000 00:00 0 
> 7f57a65d7000-7f57a65d8000 ---p 00000000 00:00 0 
> 7f57a65d8000-7f57a65d9000 rw-p 00000000 00:00 0 
> 7f57a65d9000-7f57a65e1000 ---p 00000000 00:00 0 
> 7f57a65e1000-7f57a6698000 rw-p 00000000 00:00 0 
> 7f57a6698000-7f57a66ad000 r--p 00000000 08:02 3353702                    /app/hg_worker_Data/Managed/netstandard.dll
> 7f57a66ad000-7f57a6b8c000 rw-p 00000000 00:00 0 
> 7f57a6b8c000-7f57a6e2c000 r--p 00000000 08:02 3353610                    /app/hg_worker_Data/Managed/System.dll
> 7f57a6e2c000-7f57a6f2c000 r--p 00000000 08:02 3353580                    /app/hg_worker_Data/Managed/System.Core.dll
> 7f57a6f2c000-7f57a6fee000 rw-p 00000000 00:00 0 
> 7f57a6fee000-7f57a6fef000 ---p 00000000 00:00 0 
> 7f57a6fef000-7f57a77ef000 rw-p 00000000 00:00 0 
> 7f57a77ef000-7f57a77f0000 ---p 00000000 00:00 0 
> 7f57a77f0000-7f57a7ff0000 rw-p 00000000 00:00 0 
> 7f57a7ff0000-7f57a7ff1000 ---p 00000000 00:00 0 
> 7f57a7ff1000-7f57a87f1000 rw-p 00000000 00:00 0 
> 7f57a87f1000-7f57a87f2000 ---p 00000000 00:00 0 
> 7f57a87f2000-7f57a8ff2000 rw-p 00000000 00:00 0 
> 7f57a8ff2000-7f57a8ff3000 ---p 00000000 00:00 0 
> 7f57a8ff3000-7f57a97f3000 rw-p 00000000 00:00 0 
> 7f57a97f3000-7f57a97f4000 ---p 00000000 00:00 0 
> 7f57a97f4000-7f57a9ff4000 rw-p 00000000 00:00 0 
> 7f57a9ff4000-7f57a9ff5000 ---p 00000000 00:00 0 
> 7f57a9ff5000-7f57aa7f5000 rw-p 00000000 00:00 0 
> 7f57aa7f5000-7f57aa7f6000 ---p 00000000 00:00 0 
> 7f57aa7f6000-7f57aaff6000 rw-p 00000000 00:00 0 
> 7f57aaff6000-7f57aaff7000 ---p 00000000 00:00 0 
> 7f57aaff7000-7f57ab7f7000 rw-p 00000000 00:00 0 
> 7f57ab7f7000-7f57ab7f8000 ---p 00000000 00:00 0 
> 7f57ab7f8000-7f57abff8000 rw-p 00000000 00:00 0 
> 7f57abff8000-7f57abff9000 ---p 00000000 00:00 0 
> 7f57abff9000-7f57ac7f9000 rw-p 00000000 00:00 0 
> 7f57ac7f9000-7f57ac7fa000 ---p 00000000 00:00 0 
> 7f57ac7fa000-7f57acffa000 rw-p 00000000 00:00 0 
> 7f57acffa000-7f57acffb000 ---p 00000000 00:00 0 
> 7f57acffb000-7f57ad7fb000 rw-p 00000000 00:00 0 
> 7f57ad7fb000-7f57ad7fc000 ---p 00000000 00:00 0 
> 7f57ad7fc000-7f57adffc000 rw-p 00000000 00:00 0 
> 7f57adffc000-7f57adffd000 ---p 00000000 00:00 0 
> 7f57adffd000-7f57ae7fd000 rw-p 00000000 00:00 0 
> 7f57ae7fd000-7f57ae7fe000 ---p 00000000 00:00 0 
> 7f57ae7fe000-7f57aeffe000 rw-p 00000000 00:00 0 
> 7f57aeffe000-7f57aefff000 ---p 00000000 00:00 0 
> 7f57aefff000-7f57af7ff000 rw-p 00000000 00:00 0 
> 7f57af7ff000-7f57af800000 ---p 00000000 00:00 0 
> 7f57af800000-7f57b1000000 rw-p 00000000 00:00 0 
> 7f57b1000000-7f57c0000000 ---p 00000000 00:00 0 
> 7f57c0000000-7f57c1000000 rw-p 00000000 00:00 0 
> 7f57c1000000-7f57d0000000 ---p 00000000 00:00 0 
> 7f57d0000000-7f57d1000000 rw-p 00000000 00:00 0 
> 7f57d1000000-7f57e0000000 ---p 00000000 00:00 0 
> 7f57e0000000-7f57e0800000 rw-p 00000000 00:00 0 
> 7f57e0800000-7f57f0000000 ---p 00000000 00:00 0 
> 7f57f0000000-7f57f1000000 rw-p 00000000 00:00 0 
> 7f57f1000000-7f5800000000 ---p 00000000 00:00 0 
> 7f5800000000-7f5800400000 rw-p 00000000 00:00 0 
> 7f5800400000-7f5800800000 ---p 00000000 00:00 0 
> 7f5800800000-7f5800840000 rw-p 00000000 00:00 0 
> 7f5800840000-7f5800880000 ---p 00000000 00:00 0 
> 7f5800880000-7f58008c0000 rw-p 00000000 00:00 0 
> 7f58008c0000-7f5800900000 ---p 00000000 00:00 0 
> 7f5800900000-7f5800940000 rw-p 00000000 00:00 0 
> 7f5800940000-7f5800980000 ---p 00000000 00:00 0 
> 7f5800980000-7f58009c0000 rw-p 00000000 00:00 0 
> 7f58009c0000-7f5800a00000 ---p 00000000 00:00 0 
> 7f5800a00000-7f5800a40000 rw-p 00000000 00:00 0 
> 7f5800a40000-7f5800a80000 ---p 00000000 00:00 0 
> 7f5800a80000-7f5800ac0000 rw-p 00000000 00:00 0 
> 7f5800ac0000-7f5800b00000 ---p 00000000 00:00 0 
> 7f5800b00000-7f5800b40000 rw-p 00000000 00:00 0 
> 7f5800b40000-7f5800b80000 ---p 00000000 00:00 0 
> 7f5800b80000-7f5800b88000 rw-p 00000000 00:00 0 
> 7f5800b88000-7f5800b90000 ---p 00000000 00:00 0 
> 7f5800b90000-7f5800b98000 rw-p 00000000 00:00 0 
> 7f5800b98000-7f5800ba0000 ---p 00000000 00:00 0 
> 7f5800ba0000-7f5800ba8000 rw-p 00000000 00:00 0 
> 7f5800ba8000-7f5800bb0000 ---p 00000000 00:00 0 
> 7f5800bb0000-7f5800bb8000 rw-p 00000000 00:00 0 
> 7f5800bb8000-7f5800bc0000 ---p 00000000 00:00 0 
> 7f5800bc0000-7f5800bc8000 rw-p 00000000 00:00 0 
> 7f5800bc8000-7f5800bd0000 ---p 00000000 00:00 0 
> 7f5800bd0000-7f5800bd8000 rw-p 00000000 00:00 0 
> 7f5800bd8000-7f5800be0000 ---p 00000000 00:00 0 
> 7f5800be0000-7f5800be8000 rw-p 00000000 00:00 0 
> 7f5800be8000-7f5800bf0000 ---p 00000000 00:00 0 
> 7f5800bf0000-7f5800bf8000 rw-p 00000000 00:00 0 
> 7f5800bf8000-7f5800c00000 ---p 00000000 00:00 0 
> 7f5800c00000-7f5800c08000 rw-p 00000000 00:00 0 
> 7f5800c08000-7f5800c10000 ---p 00000000 00:00 0 
> 7f5800c10000-7f5800c18000 rw-p 00000000 00:00 0 
> 7f5800c18000-7f5800c20000 ---p 00000000 00:00 0 
> 7f5800c20000-7f5800c28000 rw-p 00000000 00:00 0 
> 7f5800c28000-7f5800c30000 ---p 00000000 00:00 0 
> 7f5800c30000-7f5800c38000 rw-p 00000000 00:00 0 
> 7f5800c38000-7f5800c40000 ---p 00000000 00:00 0 
> 7f5800c40000-7f5800c48000 rw-p 00000000 00:00 0 
> 7f5800c48000-7f5800c50000 ---p 00000000 00:00 0 
> 7f5800c50000-7f5800c58000 rw-p 00000000 00:00 0 
> 7f5800c58000-7f5800c60000 ---p 00000000 00:00 0 
> 7f5800c60000-7f5800c68000 rw-p 00000000 00:00 0 
> 7f5800c68000-7f5800c70000 ---p 00000000 00:00 0 
> 7f5800c70000-7f5800c78000 rw-p 00000000 00:00 0 
> 7f5800c78000-7f5800c80000 ---p 00000000 00:00 0 
> 7f5800c80000-7f5800c90000 rw-p 00000000 00:00 0 
> 7f5800c90000-7f5800ca0000 ---p 00000000 00:00 0 
> 7f5800ca0000-7f5800ce0000 rw-p 00000000 00:00 0 
> 7f5800ce0000-7f5810000000 ---p 00000000 00:00 0 
> 7f5810000000-7f5810401000 rw-p 00000000 00:00 0 
> 7f5810401000-7f5820000000 ---p 00000000 00:00 0 
> 7f5820000000-7f5820f02000 rw-p 00000000 00:00 0 
> 7f5820f02000-7f5830000000 ---p 00000000 00:00 0 
> 7f5830000000-7f5830102000 rw-p 00000000 00:00 0 
> 7f5830102000-7f5840000000 ---p 00000000 00:00 0 
> 7f5840000000-7f5840102000 rw-p 00000000 00:00 0 
> 7f5840102000-7f5850000000 ---p 00000000 00:00 0 
> 7f5850000000-7f5850102000 rw-p 00000000 00:00 0 
> 7f5850102000-7f5860000000 ---p 00000000 00:00 0 
> 7f5860000000-7f5860100000 rw-p 00000000 00:00 0 
> 7f5860100000-7f5870000000 ---p 00000000 00:00 0 
> 7f5870003000-7f587003c000 rw-p 00000000 00:00 0 
> 7f587003c000-7f587003d000 ---p 00000000 00:00 0 
> 7f587003d000-7f587083d000 rw-p 00000000 00:00 0 
> 7f587083d000-7f587083e000 ---p 00000000 00:00 0 
> 7f587083e000-7f587103e000 rw-p 00000000 00:00 0 
> 7f587103e000-7f587103f000 ---p 00000000 00:00 0 
> 7f587103f000-7f587183f000 rw-p 00000000 00:00 0 
> 7f587183f000-7f5871840000 ---p 00000000 00:00 0 
> 7f5871840000-7f5872040000 rw-p 00000000 00:00 0 
> 7f5872040000-7f5872041000 ---p 00000000 00:00 0 
> 7f5872041000-7f5872841000 rw-p 00000000 00:00 0 
> 7f5872841000-7f58779f3000 r-xp 00000000 08:02 3353725                    /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so
> 7f58779f3000-7f5877bf2000 ---p 051b2000 08:02 3353725                    /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so
> 7f5877bf2000-7f5877d1b000 r--p 051b1000 08:02 3353725                    /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so
> 7f5877d1b000-7f5877f1a000 ---p 054da000 08:02 3353725                    /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so
> 7f5877f1a000-7f5877f6f000 rw-p 052d9000 08:02 3353725                    /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so
> 7f5877f6f000-7f5878000000 rw-p 00000000 00:00 0 
> 7f5878000000-7f5878024000 rw-p 00000000 00:00 0 
> 7f5878024000-7f587c000000 ---p 00000000 00:00 0 
> 7f587c002000-7f587c202000 rw-p 00000000 00:00 0 
> 7f587c202000-7f587c203000 ---p 00000000 00:00 0 
> 7f587c203000-7f587c223000 rw-p 00000000 00:00 0 
> 7f587c223000-7f587c224000 ---p 00000000 00:00 0 
> 7f587c224000-7f587c324000 rw-p 00000000 00:00 0 
> 7f587c324000-7f587c325000 ---p 00000000 00:00 0 
> 7f587c325000-7f587cc4d000 rw-p 00000000 00:00 0 
> 7f587cc4d000-7f587cc51000 r--p 00000000 08:02 2816568                    /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
> 7f587cc51000-7f587cc61000 r-xp 00004000 08:02 2816568                    /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
> 7f587cc61000-7f587cc64000 r--p 00014000 08:02 2816568                    /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
> 7f587cc64000-7f587cc65000 ---p 00017000 08:02 2816568                    /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
> 7f587cc65000-7f587cc66000 r--p 00017000 08:02 2816568                    /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
> 7f587cc66000-7f587cc67000 rw-p 00018000 08:02 2816568                    /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
> 7f587cc67000-7f587cc69000 rw-p 00000000 00:00 0 
> 7f587cc69000-7f587cc6c000 r--p 00000000 08:02 2816537                    /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
> 7f587cc6c000-7f587cc73000 r-xp 00003000 08:02 2816537                    /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
> 7f587cc73000-7f587cc75000 r--p 0000a000 08:02 2816537                    /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
> 7f587cc75000-7f587cc76000 r--p 0000b000 08:02 2816537                    /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
> 7f587cc76000-7f587cc77000 rw-p 0000c000 08:02 2816537                    /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
> 7f587cc77000-7f587cc81000 rw-p 00000000 00:00 0 
> 7f587cc81000-7f587cc82000 ---p 00000000 00:00 0 
> 7f587cc82000-7f587cc83000 rw-p 00000000 00:00 0 
> 7f587cc83000-7f587cc8b000 ---p 00000000 00:00 0 
> 7f587cc8b000-7f587ce86000 rw-p 00000000 00:00 0 
> 7f587ce86000-7f587d269000 r--p 00000000 08:02 3353701                    /app/hg_worker_Data/Managed/mscorlib.dll
> 7f587d269000-7f587d26a000 rw-p 00000000 00:00 0 
> 7f587d26a000-7f587d2c9000 ---p 00000000 00:00 0 
> 7f587d2c9000-7f587d40a000 rw-p 00000000 00:00 0 
> 7f587d40a000-7f587d760000 r-xp 00000000 08:02 3353723                    /app/hg_worker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
> 7f587d760000-7f587d960000 ---p 00356000 08:02 3353723                    /app/hg_worker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
> 7f587d960000-7f587d967000 r--p 00356000 08:02 3353723                    /app/hg_worker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
> 7f587d967000-7f587d96e000 rw-p 0035d000 08:02 3353723                    /app/hg_worker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
> 7f587d96e000-7f587db8c000 rw-p 00000000 00:00 0 
> 7f587db8c000-7f587db8f000 r--p 00000000 08:02 2816570                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
> 7f587db8f000-7f587db93000 r-xp 00003000 08:02 2816570                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
> 7f587db93000-7f587db94000 r--p 00007000 08:02 2816570                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
> 7f587db94000-7f587db95000 ---p 00008000 08:02 2816570                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
> 7f587db95000-7f587db96000 r--p 00008000 08:02 2816570                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
> 7f587db96000-7f587db97000 rw-p 00009000 08:02 2816570                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
> 7f587db97000-7f587db99000 rw-p 00000000 00:00 0 
> 7f587db99000-7f587db9a000 r--p 00000000 08:02 2816483                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
> 7f587db9a000-7f587db9c000 r-xp 00001000 08:02 2816483                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
> 7f587db9c000-7f587db9d000 r--p 00003000 08:02 2816483                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
> 7f587db9d000-7f587db9e000 r--p 00003000 08:02 2816483                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
> 7f587db9e000-7f587db9f000 rw-p 00004000 08:02 2816483                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
> 7f587db9f000-7f587dbc4000 r--p 00000000 08:02 2816472                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 7f587dbc4000-7f587dd3c000 r-xp 00025000 08:02 2816472                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 7f587dd3c000-7f587dd86000 r--p 0019d000 08:02 2816472                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 7f587dd86000-7f587dd87000 ---p 001e7000 08:02 2816472                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 7f587dd87000-7f587dd8a000 r--p 001e7000 08:02 2816472                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 7f587dd8a000-7f587dd8d000 rw-p 001ea000 08:02 2816472                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
> 7f587dd8d000-7f587dd91000 rw-p 00000000 00:00 0 
> 7f587dd91000-7f587dd98000 r--p 00000000 08:02 2816566                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
> 7f587dd98000-7f587dda9000 r-xp 00007000 08:02 2816566                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
> 7f587dda9000-7f587ddae000 r--p 00018000 08:02 2816566                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
> 7f587ddae000-7f587ddaf000 r--p 0001c000 08:02 2816566                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
> 7f587ddaf000-7f587ddb0000 rw-p 0001d000 08:02 2816566                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
> 7f587ddb0000-7f587ddb4000 rw-p 00000000 00:00 0 
> 7f587ddb4000-7f587ddb7000 r--p 00000000 08:02 2816497                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f587ddb7000-7f587ddc9000 r-xp 00003000 08:02 2816497                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f587ddc9000-7f587ddcd000 r--p 00015000 08:02 2816497                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f587ddcd000-7f587ddce000 r--p 00018000 08:02 2816497                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f587ddce000-7f587ddcf000 rw-p 00019000 08:02 2816497                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f587ddcf000-7f587ddde000 r--p 00000000 08:02 2816514                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
> 7f587ddde000-7f587de85000 r-xp 0000f000 08:02 2816514                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
> 7f587de85000-7f587df1c000 r--p 000b6000 08:02 2816514                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
> 7f587df1c000-7f587df1d000 r--p 0014c000 08:02 2816514                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
> 7f587df1d000-7f587df1e000 rw-p 0014d000 08:02 2816514                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
> 7f587df20000-7f587e603000 r--p 00000000 08:02 3353553                    /app/UnityPlayer.so
> 7f587e603000-7f587fc86000 r-xp 006e3000 08:02 3353553                    /app/UnityPlayer.so
> 7f587fc86000-7f587fd1b000 r--p 01d66000 08:02 3353553                    /app/UnityPlayer.so
> 7f587fd1b000-7f587fd46000 rw-p 01dfb000 08:02 3353553                    /app/UnityPlayer.so
> 7f587fd46000-7f587fe40000 rw-p 00000000 00:00 0 
> 7f587fe40000-7f587fe41000 r--p 00000000 08:02 2816450                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
> 7f587fe41000-7f587fe64000 r-xp 00001000 08:02 2816450                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
> 7f587fe64000-7f587fe6c000 r--p 00024000 08:02 2816450                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
> 7f587fe6c000-7f587fe6d000 rw-s 00000000 00:51 3                          /dev/shm/mono.1
> 7f587fe6d000-7f587fe6e000 r--p 0002c000 08:02 2816450                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
> 7f587fe6e000-7f587fe6f000 rw-p 0002d000 08:02 2816450                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
> 7f587fe6f000-7f587fe70000 rw-p 00000000 00:00 0 
> 7ffed6cb6000-7ffed6cbe000 ---p 00000000 00:00 0 
> 7ffed7494000-7ffed74b5000 rw-p 00000000 00:00 0                          [stack]
> 7ffed75b3000-7ffed75b7000 r--p 00000000 00:00 0                          [vvar]
> 7ffed75b7000-7ffed75b9000 r-xp 00000000 00:00 0                          [vdso]
> ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
> 
> Native stacktrace:
> 
>         /app/hg_worker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so(+0xd7fac) [0x7f587d4e1fac]
>         /app/hg_worker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so(+0x5bd4f) [0x7f587d465d4f]
>         /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0) [0x7f587dda63c0]
>         /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so(_ZN8firebase13remote_config8internal20RemoteConfigResponse13MarkCompletedEv+0x1e) [0x7f587605539e]
>         /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so(_ZN8firebase4rest23BackgroundTransportCurlD1Ev+0x29d) [0x7f5876080f7d]
>         /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so(_ZN8firebase4rest10CurlThread15ProcessRequestsEv+0x371) [0x7f5876083b31]
>         /app/hg_worker_Data/Plugins/FirebaseCppApp-7_1_0.so(+0x24559c7) [0x7f5874c969c7]
>         /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f587dd9a609]
>         /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f587dcc1293]
> 
> Debug info from gdb:
> 
> mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
> 
> =================================================================
> Got a SIGSEGV while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
> 

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? No
What's the issue repro rate? (eg 100%, 1/5 etc) 0%

What happened? How can we make the problem occur? 
1: Build a headless Unity artifact with  Mono
2:
 ```docker
FROM ubuntu:20.04
ARG ARTIFACT_DIRECTORY
COPY $ARTIFACT_DIRECTORY /app/
ENTRYPOINT ["/app/artifact"]
```
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```csharp
using System;
using System.Threading.Tasks;
using Cysharp.Threading.Tasks;
using Firebase;
using Firebase.RemoteConfig;
using JetBrains.Annotations;
using UnityEngine;
using Utils;

namespace Game.Global
{
    public class RemoteConfig : Monobehaviour
    {
   
        private DependencyStatus firebaseStatus;
        [CanBeNull] private FirebaseApp firebaseApp;

        protected override void Awake()
        {
            FirebaseApp.CheckAndFixDependenciesAsync().ContinueWith(task => {
                firebaseStatus = task.Result;
                if (firebaseStatus == DependencyStatus.Available) {
                    // Create and hold a reference to your FirebaseApp,
                    // where app is a Firebase.FirebaseApp property of your application class.
                    firebaseApp = FirebaseApp.DefaultInstance;
                    Debug.Log("Firebase initialized");
                    // Set a flag here to indicate whether Firebase is ready to use by your app.
                } else {
                    Debug.LogError($"Could not resolve all Firebase dependencies: {firebaseStatus}");
                    // Firebase Unity SDK is not safe to use here.
                }
            });
            
        }
        
        private void ApplyRemoteSettings()
        {
            // ...
        }

        public async Task FetchDataAsync()
        {
            await UniTask.WaitUntil(() => firebaseApp != null);
            Debug.Log("Fetching data...");
            if (!await FirebaseRemoteConfig.DefaultInstance.FetchAndActivateAsync())
            {
                Debug.LogError($"Failed to FetchAndActivateAsync");
            }
            // .
            ApplyRemoteSettings();
        }
    }
}

```

**Comment by louis030195** [comment]
Could it be that Firebase plugin (FirebaseCppApp-7_1_0.so) needs specific Linux libraries?

**Comment by paulinon** [comment]
Hi @louis030195,

This issue seems rather unusual. First, I'd like you to verify if this could be resolved by updating the Unity Editor to version 2020.3.0f1.

Also, the Unity SDK version you specified doesn't seem to be available as of writing because the latest version is at 7.1.0. Could you confirm if you're using the latest version of the SDK? If not, let's see if the latest SDK makes any difference.

Thanks.

**Comment by louis030195** [comment]
I could not fix this issue but I stopped using Firebase Remote Config, feel free to reopen.
